### ISSUE TITLE
Option to disable internal authentication / use external authentication

### ISSUE THREAD

**Issue by sammcj** [open-webui/open-webui#1000]
**Is your feature request related to a problem? Please describe.**

Could we please have an option to disable it's internal authentication?

This would be very useful for people that are already running the app behind an centralised authentication / identity provider such as Authentik / Okta etc...

**Describe the solution you'd like**

- An option to disable the apps internal authentication.
- Take the user from the headers or URL parameter.
or
- Set a default user to assume if internal authentication is not used.

**Describe alternatives you've considered**

I've tried passing the email/password details in via some dodgy middleware but it's far from ideal.

**Additional context**

- Related to #430, #483, #340

**Comment by sammcj** [comment]
Just found https://github.com/open-webui/open-webui/issues/483#issuecomment-1964158623 (sorry my first search didn't show it up for some reason) - perhaps this will provide a solution when ready?

**Comment by tjbck** [comment]
Duplicate https://github.com/open-webui/open-webui/issues/483
