### ISSUE TITLE
feat: "Cancel" in the Playground does not stop Ollama generation

### ISSUE THREAD

**Issue by robertvazan** [open-webui/open-webui#1006]
# Bug Report

## Description

**Bug Summary:**
This is the same problem as #456 but in Playground.

**Steps to Reproduce:**
Start generation in Playground and press Cancel. It does not matter whether you use chat or text completion mode.

**Expected Behavior:**
Ollama should stop immediately.

**Actual Behavior:**
UI stops streaming, but Ollama continues to generate tokens in the background.

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I have reviewed the troubleshooting.md document.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Additional Information

More info available upon request.

**Comment by tjbck** [comment]
It's in beta for a reason :) feel free to make a PR!
