### ISSUE TITLE
Easier way to find keyboard shortcuts

### ISSUE THREAD

**Issue by robertvazan** [open-webui/open-webui#1007]
**Is your feature request related to a problem? Please describe.**
Took me a while (and some code browsing) to find the button that shows keyboard shortcuts.

**Describe the solution you'd like**
Just put keyboard shortcuts as a new item into the menu next to Settings and Playground. It will be easier to find. Or put shortcuts into tooltips for all buttons as part of #259.

**Comment by tjbck** [comment]
Duplicate https://github.com/open-webui/open-webui/issues/259
