### ISSUE TITLE
Freezing during generation and 1+ GB Chrome tab memory usage

### ISSUE THREAD

**Issue by horiacristescu** [open-webui/open-webui#1009]
# Bug Report

## Description

**Bug Summary:**
When generating text, either with ollama or OpenAI, the interface becomes laggy and eventually freezes.
It looks like the browser is caught in an infinite loop and no longer processing mouse events - maybe it is appending to the DOM too fast, or some kind of intensive polling happening.
The first few lines of text flow nicely, but after about one screen of text it starts acting up.
It can kill a tab or the whole browser. When I checked the offending tab was using 200% CPU and 1.3GB RAM

**Steps to Reproduce:**
This happens on all models and both on Mac and Ubuntu

I removed my conversation history because it was too slow to load (33MB total JSON export), so it's not on account of too many messages in history.

Ollama Web UI Version
v1.0.0-alpha.100
Ollama Version
0.1.27

**Comment by horiacristescu** [comment]
was caused by another extension interfering with Open WebUI

**Comment by tjbck** [comment]
Side note, you should probably update your open webui :)

**Comment by horiacristescu** [comment]
I updated open-webui to the latest docker version but still have freezing. Even on Safari and Firefox, not just on Chrome.
