### ISSUE TITLE
feat: persist settings to backend

### ISSUE THREAD

**Issue by tjbck** [open-webui/open-webui#1022]
Related #981 #988 #900

**Comment by changchiyou** [comment]
I don't have a clear idea yet on how to persist settings to the backend, but may I ask if you would welcome me to create a workaround PR for #988 in the meantime?

Here's my idea: Even though there is no documentation mentioning it, I observed that users can set `DEFAULT_USER_ROLE` in the environment variables and have it read by :

https://github.com/open-webui/open-webui/blob/7ae4669f350ad30b44594c5e76759db445d9bf5d/backend/config.py#L290

Then assigned to `app.state.DEFAULT_USER_ROLE` in:

https://github.com/open-webui/open-webui/blob/7ae4669f350ad30b44594c5e76759db445d9bf5d/backend/apps/web/main.py#L33

Could I apply a similar logic to handle `USER_PERMISSIONS` as well? For example:

https://github.com/open-webui/open-webui/blob/7ae4669f350ad30b44594c5e76759db445d9bf5d/backend/config.py#L291

```diff
+ import ast

- USER_PERMISSIONS = {"chat": {"deletion": True}}
+ USER_PERMISSIONS = ast.literal_eval(os.environ.get("USER_PERMISSIONS", {"chat": {"deletion": True}})
```

**Comment by Fusseldieb** [comment]
This also applies to the OpenAI API key. It gets lost every container restart, even with a volume present.

**Comment by ChaoticByte** [comment]
For me also the "Enable New Sign Ups" setting resets to "Enable" every time the container is restarted.  
Especially this setting should persist, and honestly this looks more like a bug than a missing feature.

**Comment by frost19k** [comment]
Chiming in to point out that `Embedding Model Engine` set to `OpenAI` does not persist either. Also, `OPENAI_API_BASE_URL` & `OPENAI_API_KEY` do not seem to reflect there. However, `Embedding Model` can be updated by setting `RAG_EMBEDDING_MODEL` var.

**Comment by changchiyou** [comment]
@JTHesse It's already possible to make `Default User Role` persistent:

According to

https://github.com/open-webui/open-webui/blob/90503be2edef1a1f7ce2074286b6316d5cb8868a/backend/config.py#L411

, create your own enviroment at

https://github.com/open-webui/open-webui/blob/90503be2edef1a1f7ce2074286b6316d5cb8868a/docker-compose.yaml#L27-L29

. For example:

```diff
 environment: 
   - 'OLLAMA_BASE_URL=http://ollama:11434' 
   - 'WEBUI_SECRET_KEY=' 
+ - 'DEFAULT_USER_ROLE=user'
```

**Comment by mmmmmmmgo** [comment]
https://github.com/open-webui/open-webui/discussions/1876
