### ISSUE TITLE
feat: display model descriptions in new chat

### ISSUE THREAD

**Issue by CtrlAiDel** [open-webui/open-webui#1041]
**Problem Description:**
Currently, there's a challenge with identifying models in the New Chat page dropdown list, especially when many models haven't been renamed and possess generic names. As a result, users, particularly those without admin privileges, lack access to model descriptions, which can be crucial for informed selection.

**Requested Solution:**
Implement a feature that provides model descriptions either upon selection, through a clickable button, or via hover-over functionality. This could involve collapsible sections for descriptions, a button labeled with "?" for accessing descriptions, or displaying descriptions directly below the selected model.

**Alternative Considerations:**
1. Introduce a "?" button next to existing options for accessing model descriptions.
2. Display descriptions directly on the page, possibly underneath the selected model.
3. Implement a hide/show toggle for descriptions to prevent user annoyance.
4. Enable hover-over functionality on model names to reveal descriptions in collapsible sections.

**Additional Context:**
Integration of descriptions could be visually integrated into the yellow line of the screenshot provided for optimal user accessibility and convenience.

![image](https://github.com/open-webui/open-webui/assets/40178706/82a14e68-682e-425b-98f9-3855a4d714cb)

Thank you for your great UI, and I hope to see this in it one day :) Keep on the amazing work!

**-Written by CtrlAiDel & chatGPT :)**

**Comment by tjbck** [comment]
Closing in favour of #1725
