### ISSUE TITLE
feat: filter by untagged chats

### ISSUE THREAD

**Issue by mherrmann3** [open-webui/open-webui#1060]
**The problem**
Tagging is a nice way to organize the chats, but it is currently not possible to:
* only show new/uncategorized chats;
* tidy up the chat list while keeping all tagged chats, effectively treating them as "archived".

**The solution I'd like**
The possibility to only show chats _without_ a tag.

Above the chat list, I see one tag button without a name (it only contains a whitespace character " "), which does not do anything (apparently). Exactly this item could take over the "untagged" functionality.

**Alternatives I've considered**
If a chat is not yet tagged, it could appear above a horizontal separator (indicating it as a "new" chat; tagging it will bring it below the separator).

**Comment by tjbck** [comment]
Closing this in favour of #1106, let's continue our discussion there!

**Comment by mherrmann3** [comment]
Even with the new archiving feature, couldn't this feature request still be useful?

I also would like to know the purpose of the tag button without a name (which only contains a whitespace character " "). It seems to not have any function. And I still believe exactly this item could take over the "untagged" functionality.
