### ISSUE TITLE
Extra 'S' in 'ASSISTANT' field for GGUF model upload template

### ISSUE THREAD

**Issue by justinh-rahb** [open-webui/open-webui#1061]
https://github.com/open-webui/open-webui/blob/eb51ad14e4caafda1c9fd24c4945044b8776a7a3/src/lib/components/chat/Settings/Models.svelte#L48

Helpfully spotted by a Discord member, **beegie**

![Screenshot 2024-03-06 at 10 59 06 AM](https://github.com/open-webui/open-webui/assets/52832301/7e5d7ff3-7c59-4048-95c0-62aff133633d)

**Comment by justinh-rahb** [comment]
Fix in:
- #1062

**Comment by jannikstdl** [comment]
Yes, we should generally edit this template. Also there's no need for ":" in Modelfiles.

**Comment by justinh-rahb** [comment]
I may as well while I got the PR open, gimme a few minutes 👍

**Comment by justinh-rahb** [comment]
> Yes, we should generally edit this template. Also there's no need for ":" in Modelfiles.

On looking at this again, the colons I removed aren't part of Modelfile "commands", they're in the prompt template. I feel these should remain.
