### ISSUE TITLE
feat: System-wide Light/Dark Mode Theme Setting

### ISSUE THREAD

**Issue by Silentoplayz** [open-webui/open-webui#1065]
**Is your feature request related to a problem? Please describe.**
Yes, the feature request is related to the problem of manually switching between light and dark modes on different applications, which can be frustrating and challenging for many users, including those with visual impairments or sensitivities to certain light levels. Specifically, the issue lies in the current manual theme selection feature in Open WebUI, which does not incorporate the user's system light/dark mode setting.

**Describe the solution you'd like**
The proposed solution is to add a new theme option labeled `System` in Open WebUI. This option will enable Open WebUI to automatically switch between light and dark modes based on the user's systems setting. This feature would improve accessibility for users with visual impairments or sensitivities to certain light levels and reduce the need for manual intervention. Enabling the `System` theme by default upon the first sign up for Open WebUI (the admin account) would better suit the needs of those users and provide a consistent user experience across all applications. Additionally, this would allow users to immediately experience the benefits of the system-wide light/dark mode theme setting without having to manually change their settings.

**Describe alternatives you've considered**
An alternative solution considered is manually switching themes within Open WebUI. However, this approach would not provide a consistent user experience across all applications and would require manual intervention.

**Additional context**
Incorporating the system's light/dark mode setting into Open WebUI's theme settings would provide a more seamless and accessible user experience for all users. This feature would be particularly beneficial for those users who have visual impairments or sensitivities to certain light levels. By automatically switching between light and dark modes based on the user's system setting, Open WebUI can provide a more user-friendly and accessible platform for all users.

**Comment by jlar0che** [comment]
So, this was closed a year ago but I see no way of doing this within the settings menus. Could you please explain how to implement dark mode as the default for all users?

**Comment by silentoplayz** [comment]
> So, this was closed a year ago but I see no way of doing this within the settings menus. Could you please explain how to implement dark mode as the default for all users?

There is no way to toggle on a specific theme mode for **ALL** users within Open WebUI. Setting the theme is available on a per-user level.
![Image](https://github.com/user-attachments/assets/6e074777-c478-43b5-b010-42e54ed881d8)
