### ISSUE TITLE
feat: rag in playground and instruct mode in notebook

### ISSUE THREAD

**Issue by FemBoxbrawl** [open-webui/open-webui#1087]
**Describe the solution you'd like**
Add an instruct mode in the "text completion" playground, so you instruct it specifically what to generate, (or summarize) and have a RAG support in it too.

**Examples**
[ATTACHED DOC]  Instruction:Write me a story that involves the concept provided. 

or [ATTACHED DOC] Instruction: summarize the document.

[ATTACHED DOCS] (text that involves descriptions of characters) Lola was typing on her computer, as ... (chat completion)

They should be either able to be added with hashtags or some drag and drop feature. PLEASE i have not had one single "notebook" mode where the was a RAG feature. please add this feature.

**Comment by FemBoxbrawl** [comment]
Maybe also add the "/" commands too!

**Comment by tjbck** [comment]
Closing in favour of #2000, Let's continue our discussion there!
