### ISSUE TITLE
Something went wrong :/ 'AuthModel' object has no attribute 'model_dump'

### ISSUE THREAD

**Issue by liucoj** [open-webui/open-webui#1089]
Hi,
after running for long time OpenWebUi  I can't register o login anymore, 
An error "Something went wrong :/ 'AuthModel' object has no attribute 'model_dump'" pop-ups
For terminal i see: 
INFO:     127.0.0.1:49949 - "POST /auths/signup HTTP/1.1" 500 Internal Server Error

I don't use Docker but manual installation.
No problem during install (npm, bun, pip) and localhost:8080 starts with no errors.
Any help?
Thank you!

ps:
I'm on a MacOS sonoma, python 3.11

**Comment by justinh-rahb** [comment]
Possibly tangential to the issue you're having, but why are you using signup if you already have an account? Unless you're clearing your `backend/data` folder each time you update you should be able to login with the account you created previously.

**Comment by liucoj** [comment]
Solved, it was something related to python version after macOS update (maybe command line tools update)
Using python3 venv solved auth issue.

**Comment by dukai289** [comment]
I met the same problem: "ERROR:apps.webui.routers.chats:'ChatModel' object has no attribute 'model_dump'"
Just because i set the port "open-webui serve --port 8502", the I got that error.
First time when I excute "open-webui serve", it's ok. When I set the port, it raises errors like above.
