### ISSUE TITLE
Any model based on Starcoder2 breaks Open-WebUI

### ISSUE THREAD

**Issue by elabz** [open-webui/open-webui#1093]
# Bug Report
Trying to run Starcoder2 or any model off of Starcoder2, such as Dolphincoder , breaks WebUI

<img width="851" alt="Screenshot 2024-03-07 at 2 49 15 PM" src="https://github.com/open-webui/open-webui/assets/9451173/79ddc8f6-e89a-4908-921c-3e1bd20f934e">
<img width="722" alt="Screenshot 2024-03-07 at 2 49 32 PM" src="https://github.com/open-webui/open-webui/assets/9451173/622fb86d-a70c-4acd-bc09-87e422e1bb8d">

[192.168.0.152-1709841238653.log](https://github.com/open-webui/open-webui/files/14529307/192.168.0.152-1709841238653.log)

Ollama Version
0.1.28

this version was required by Ollama to run Starcoder2

No Docker logs seems to be generated

## Description

**Bug Summary:**
Cannot run Starcoder2 models

**Steps to Reproduce:**
[Outline the steps to reproduce the bug. Be as detailed as possible.]

**Expected Behavior:**
[Describe what you expected to happen.]

**Actual Behavior:**
[Describe what actually happened.]

## Environment

- **Operating System:** Ubuntu 22.04
- **Browser (if applicable):**Chrome 122

## Reproduction Details

**Confirmation:**

- [ x] I have read and followed all the instructions provided in the README.md.
- [ x] I am on the latest version of both Open WebUI and Ollama.
- [ x] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Installation Method

[Describe the method you used to install the project, e.g., manual installation, Docker, package manager, etc.]

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by justinh-rahb** [comment]
Could I know please how much system RAM and GPU VRAM you have?

**Comment by elabz** [comment]
@justinh-rahb , this time, having learned the hard way (the other ticket we talked on), I am coming in on different, beefy machines. Well, at least one of those is beefy, but both show the same result

```
$ lshw -c cpu
WARNING: you should run this program as super-user.
  *-cpu
       product: AMD Ryzen 7 7700X 8-Core Processor
       vendor: Advanced Micro Devices [AMD]
       physical id: 1
       bus info: cpu@0
       version: 25.97.2
       size: 400MHz
       capacity: 5573MHz
       width: 64 bits
       capabilities: fpu fpu_exception wp vme de pse tsc msr pae mce cx8 apic sep mtrr pge mca cmov pat pse36 clflush mmx fxsr sse sse2 ht syscall nx mmxext fxsr_opt pdpe1gb rdtscp x86-64 constant_tsc rep_good amd_lbr_v2 nopl nonstop_tsc cpuid extd_apicid aperfmperf rapl pni pclmulqdq monitor ssse3 fma cx16 sse4_1 sse4_2 x2apic movbe popcnt aes xsave avx f16c rdrand lahf_lm cmp_legacy svm extapic cr8_legacy abm sse4a misalignsse 3dnowprefetch osvw ibs skinit wdt tce topoext perfctr_core perfctr_nb bpext perfctr_llc mwaitx cpb cat_l3 cdp_l3 hw_pstate ssbd mba perfmon_v2 ibrs ibpb stibp ibrs_enhanced vmmcall fsgsbase bmi1 avx2 smep bmi2 erms invpcid cqm rdt_a avx512f avx512dq rdseed adx smap avx512ifma clflushopt clwb avx512cd sha_ni avx512bw avx512vl xsaveopt xsavec xgetbv1 xsaves cqm_llc cqm_occup_llc cqm_mbm_total cqm_mbm_local avx512_bf16 clzero irperf xsaveerptr rdpru wbnoinvd cppc arat npt lbrv svm_lock nrip_save tsc_scale vmcb_clean flushbyasid decodeassists pausefilter pfthreshold avic v_vmsave_vmload vgif x2avic v_spec_ctrl vnmi avx512vbmi umip pku ospke avx512_vbmi2 gfni vaes vpclmulqdq avx512_vnni avx512_bitalg avx512_vpopcntdq rdpid overflow_recov succor smca fsrm flush_l1d cpufreq
       configuration: microcode=174068225
```
This one has 64GB RAM, 24GB VRAM RTX3090, runs pretty much everything, and fast. Just not Starcoder2

**Comment by tjbck** [comment]
@elabz Could you try interacting with Ollama directly and rule out Ollama is the culprit here?

**Comment by elabz** [comment]
@tjbck yes, this appears to be an Ollama issue https://github.com/ollama/ollama/issues/2953 . Thank you for the tip, somehow I did not think of checking there myself
