### ISSUE TITLE
feat: Option to disable OpenAI

### ISSUE THREAD

**Issue by lainedfles** [open-webui/open-webui#1112]
**Is your feature request related to a problem? Please describe.**
Directly related to #1111 1111

**Describe the solution you'd like**
I'd like a toggle to disable OpenAI integration.

**Describe alternatives you've considered**
At the very least, models shouldn't poll api.openai.com unless `OPENAI_API_KEYS` is valid.

**Comment by justinh-rahb** [comment]
They don't poll api.openai.com if there's no key. Any error you see related to this is between the frontend and backend only, not from external calls to the API, those are only made if a key is set.

**Comment by lainedfles** [comment]
Respectfully, I think you're wrong. Supporting evidence in my comment [here](https://github.com/open-webui/open-webui/issues/1111#issuecomment-1987485736)

**Comment by tjbck** [comment]
I'll merge this with #1111, Let's continue our discussion there!
