### ISSUE TITLE
@ only lists ollama models, not external/litellm ones

### ISSUE THREAD

**Issue by antonme** [open-webui/open-webui#1116]
# Bug Report

## Description

**Bug Summary:**
Can't make multi-model dialogue with external models.
@ only lists ollama models, not external/litellm ones. 

**Steps to Reproduce:**
Press @ in the input field while having one or more external models configured in litellm

**Expected Behavior:**
List of all models

**Actual Behavior:**
Only ollama models

**Comment by tjbck** [comment]
Duplicate: #463, Let's continue our discussion there!
