### ISSUE TITLE
Impossible to upload your GGUF model

### ISSUE THREAD

**Issue by zaperda** [open-webui/open-webui#1124]
# Bug Report

## Description
In v0.1.110 I can't load my GGUF model. The link is there, but nothing happens when you click on it.

## Environment

- **Operating System:** Windows 11, macOS 14.0
- **Browser Chrome , Safari

## Reproduction Details

**Confirmation:**

- [ x] I have read and followed all the instructions provided in the README.md.
- [ x] I am on the latest version of both Open WebUI and Ollama.
- [ x] I have included the browser console logs.
- [ x] I have included the Docker container logs.

## Logs and Screenshots
<img width="502" alt="image" src="https://github.com/open-webui/open-webui/assets/13097248/92d54293-52dd-4db4-b5eb-ff74f1b6ff16">

**Comment by justinh-rahb** [comment]
Try re-pulling the image, there was a fix pushed to `main` for that. Here's a quick way to do that:

```bash
docker run --rm --volume /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --run-once open-webui
```

**Comment by KevinKrueger** [comment]
![image](https://github.com/open-webui/open-webui/assets/25382167/f54020e3-db8e-4c84-9eb2-158c3381a5a8)

Why can't I upload my own model?

**Comment by tjbck** [comment]
@KevinKrueger seems like the webui can't access Ollama, check out our troubleshooting doc.

**Comment by KevinKrueger** [comment]
> @KevinKrueger seems like the webui can't access Ollama, check out our troubleshooting doc.

I have tested all your variants (in doc) both locally and on a server and none of them work reliably and as expected.

I have also had the case where I was able to upload a model but the progress bar was permanently at 0%

**Comment by tjbck** [comment]
@KevinKrueger GGUF model upload is labeled as experimental for a reason and if you're able to see the 0% for the progress bar it usually means that it will update once it's done uploaded :)

**Comment by zaperda** [comment]
> GGUF model upload is labeled as experimental for a reason and if you're able to see the 0% for the progress bar it usually means that it will update once it's done uploaded :) it just won't reflect the real upload progress.

I don't use docker )

**Comment by zaperda** [comment]
URL mode - work
File mode - doesn't work

**Comment by tjbck** [comment]
Duplicate #499
