### ISSUE TITLE
feat: Add Missing Keyboard Shortcuts to Help List UI

### ISSUE THREAD

**Issue by Silentoplayz** [open-webui/open-webui#1132]
**Is your feature request related to a problem? Please describe.**

Yes, the problem is that the Open WebUI keyboard shortcuts list is missing some commonly used and useful keyboard shortcuts, such as `Shift+Enter` for new line, `Ctrl/⌘+Shift+R` for refreshing the current tab, and `F11` or `Ctrl/⌘+Shift+F` for entering and exiting full-screen mode.

**Describe the solution you'd like**

I would like the following keyboard shortcuts to be added to the keyboard shortcuts help list UI:
1. `Shift+Enter` for a new line
2. `Ctrl/⌘+Shift+R` for refreshing the current tab
3. `F11` or `Ctrl/⌘+Shift+F` for entering and exiting full-screen mode
These shortcuts are already built into most modern web browsers, and including them in the help list will enhance the user experience.

**Describe alternatives you've considered**
N/A

**Additional context**

Here are the detailed descriptions of the suggested keyboard shortcuts:

1. `Shift+Enter` for a new line: This shortcut allows users to create a new line while typing in a text area or input field. Currently, this shortcut is not listed in the Open WebUI keyboard shortcuts help list.
2. `Ctrl/⌘+Shift+R` for refreshing the current tab: This shortcut reloads the current tab in the browser. This shortcut is not listed in the Open WebUI keyboard shortcuts help list.
3. `F11` or `Ctrl/⌘+Shift+F` for entering and exiting Fullscreen mode: These shortcuts allow users to enter and exit Fullscreen mode in Open WebUI. Additionally, `Ctrl/⌘+Shift+F` is not mentioned at all.

![Screenshot 2024-03-10 225206](https://github.com/open-webui/open-webui/assets/50341825/ea551c41-cafb-4297-a461-997b5549adeb)

**Comment by tjbck** [comment]
Duplicate: #1008

**Comment by Silentoplayz** [comment]
Updated the additional context.

>**Additional context**
> - Ensure that keyboard shortcuts are consistent across the entire application. For example, if a particular action has a specific shortcut in one part of the application, it should have the same shortcut in other parts of the application as well.
> - Global vs. local shortcuts: Clearly differentiate between global shortcuts (applicable across the entire web app) and local shortcuts (specific to certain pages or components).
> - Group shortcuts by functionality: Organize shortcuts into categories based on their functionality, such as navigation, chat management, and settings. This will help users find and learn the shortcuts relevant to their needs.
> - Prefer two-key combinations over three-key combinations when possible.
> - Avoid using modifier keys (Ctrl, Shift, Alt, etc.) in isolation, as they are often used in other applications for different purposes.
> - Allow users to edit/customize and save keyboard shortcuts according to their preferences.
> - Provide a way to import and export custom shortcut sets for easy sharing and backup.
