### ISSUE TITLE
illegal base64 data at input byte 33 (After creating image in chat)

### ISSUE THREAD

**Issue by kegscruiser** [open-webui/open-webui#1137]
# Bug Report

## Description

**Bug Summary:**
When trying to continue a chat after generating an image the error occurs.
(illegal base64 data at input byte 33)

**Steps to Reproduce:**
During a chat create an image and then try to continue the chat.

**Expected Behavior:**
To continue the chat.

**Actual Behavior:**
Open Webui shows the error "illegal base64 data at input byte 33" and will not continue the chat

## Environment

- **Operating System:** Windows 11 Pro
- **Browser (if applicable):** Chrome, Edge

## Reproduction Details

**Confirmation:**

- [x ] I have read and followed all the instructions provided in the README.md.
- [x ] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots (if applicable):**

![Screenshot 2024-03-12 153540](https://github.com/open-webui/open-webui/assets/66354462/14602b28-d67c-4a48-ab5b-7c26a8be8a7c)

## Installation Method

Docker installation

## Additional Information

This issue only appeared in version v0.1.111. 
Previous version v0.1.110 was fine.

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
Fixed on the dev branch! Let me know if the issue persists!

**Comment by kegscruiser** [comment]
> Fixed on the dev branch! Let me know if the issue persists!

Issue is corrected, thank you :)
