### ISSUE TITLE
feat: Attach RAG documents to ModelFiles

### ISSUE THREAD

**Issue by nick-tonjum** [open-webui/open-webui#1154]
Good afternoon!
I had a great idea when playing with ModelFiles in the webui.

What if it were possible to attach RAG documents (or a group of RAG documents) to a modelfile? I know a lot of work would have to be put into this because ollama doesn't support this directly, but I think it could be done. It would be nice to have a model file that would just always have a rag document attached to it when conversing with it, rather than including all my data in the system prompt or manually attaching a document every time I ask it a question.

For example, I could make a modelfile that's based on mixtral or something but has a RAG document attached to it with a big essay about my life or whatever, and anyone who asks the model a question about me would get an answer from it utilizing RAG. This would also be nice if this worked through the API as well.

**Comment by tjbck** [comment]
Duplicate: #529
