### ISSUE TITLE
feat: relative path support

### ISSUE THREAD

**Issue by hahchenchen** [open-webui/open-webui#1162]
# Bug Report
webui docker images do not support relative path. 
## Description
for xample, i want to start webui at localhost:8080/webui/, does the image parameter support the relative path configuration?

**Comment by hahchenchen** [comment]
@tjbck

**Comment by blackshot** [comment]
i'm having the same problem, i can't deploy it behind a reverse proxy under specific path ONLY because static files doesn't have the path prefix
![image](https://github.com/open-webui/open-webui/assets/3688208/129ef7f8-d1d2-46ae-8c27-42946a4bef4d)

**Comment by CyberIngeniero** [comment]
I also have the same problem.

**Comment by tjbck** [comment]
If not officially supported, but I can see that being useful for a lot of people. Feel free to make a PR!

**Comment by justinh-rahb** [comment]
This can be accomplished through reverse-proxy and request rewrite rules as well.

**Comment by blackshot** [comment]
> This can be accomplished through reverse-proxy and request rewrite rules as well.

nope, i deployed behind a reverse proxy but static files needs to be compiled with basepath too

**Comment by hahchenchen** [comment]
> If not officially supported, but I can see that being useful for a lot of people. Feel free to make a PR!

no, the proxy is not useful. the static files path is hard code.

**Comment by blackshot** [comment]
https://kit.svelte.dev/docs/configuration#paths

**Comment by hahchenchen** [comment]
> This can be accomplished through reverse-proxy and request rewrite rules as well.

no, the proxy is not useful. the static files path is hard code.

**Comment by hass-demacia** [comment]
Use caddy2, Caddyfile config
```
        rewrite /_app/* /open-webui{http.request.uri}

        handle_path /open-webui/* {
                reverse_proxy http://localhost:8080
        }
```

It seems browser cant fetch javascript static files. But get a runtime error:
```
app.78c246b0.js:1 Error: Not found: /open-webui/
    at ce (start.867272e0.js:1:14918)
    at re (start.867272e0.js:1:8155)
    at Object.goto (start.867272e0.js:1:18073)
    at Module.Nt (start.867272e0.js:3:1691)
    at open-webui/:66:11
```

**Comment by behackl** [comment]
I've successfully deployed an instance behind a reverse proxy using the branch attached to #1701. I wouldn't say that I am particularly happy with the way how I solved it, but perhaps this is useful to whoever decides to work on a proper implementation. :smile:

**Comment by lmorin-inria** [comment]
The feature was critical for me. I have implemented it there: 
     https://github.com/lmorin-inria/open-webui/tree/feat/base-path-relocatable

The path is set dynamically when launching the container (variable). I will had a documentation if there are people asking for it.

The MR was rejected. I will keep that fork up to date from time to time with only that feature for the next few weeks at least.

**Comment by TomlDev** [comment]
I am interested @lmorin-inria!
I tried with our nginx proxy and this config where I rewrite the URL and use sub_filters to rewrite all paths:
```
        location /ai/ {
            rewrite ^/ai(/.*)$ /$1 break;
            proxy_pass http://10.0.0.3:8080;
            proxy_http_version 1.1;

            sub_filter_types application/javascript application/json text/css text/html;
            sub_filter_once off;
            sub_filter 'href="/' 'href="/ai/';
            sub_filter 'src="/' 'src="/ai/';
            sub_filter 'action="/' 'action="/ai/';
            sub_filter 'import("/' 'import("/ai/';

            proxy_set_header Upgrade $http_upgrade;
            proxy_set_header Connection "upgrade";
            proxy_set_header X-Forwarded-Host $http_x_forwarded_host;
            proxy_set_header X-Forwarded-Proto $http_x_forwarded_proto;
            proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        }
```

It is able to rewrite most of the calls, but not all as it seems:
![grafik](https://github.com/open-webui/open-webui/assets/48552168/c1c49ff8-5ee1-4aa9-8db8-f79c4e357142)

**Comment by massih10** [comment]
Can you push the image/container to docker hub? I'm unable to build it myself.

**Comment by massih10** [comment]
> Can you push the image/container to docker hub? I'm unable to build it myself.

got it working! thank you :)

**Comment by lmorin-inria** [comment]
Dear Sir,

I am very sorry I could not help you on the way, I am really overloaded.
I am preparing a new merge by the way (version 3.x).

Regards,
Best regards,
L. Morin.

Le 20/06/2024 à 13:48, Sayed Hoseini a écrit :

**Comment by guidocioni** [comment]
Hey @lmorin-inria I tried to use your image but unfortunately it does not seem to work..
The login page is correctly loaded but I can already see that the `/static` path (not a big deal) and the `/socket.io` path (big deal) are not correctly passed/found

![Screenshot 2024-08-06 at 09 37 53](https://github.com/user-attachments/assets/a94fefc6-88ef-418b-bce3-c6daedc5b87d)

If I try to signin I get a `not found` error on the path `https://<base_path>/<ROOT_PATH>/api/v1/auths/signin`.

I feel like I'm missing something on the nginx subpath directive, and I see you haven't shared that in your issue. I'm using something like this 

```
    location /openwebui/ {
        proxy_pass http://<internal-ip>:8080/;
        # Optional: Set headers that might be required by the backend or for compliance with CORS, etc.
        proxy_set_header Host $host;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-Proto $scheme;

        # Handle WebSocket upgrades if your application uses WebSockets
        proxy_http_version 1.1;
        proxy_set_header Upgrade $http_upgrade;
        proxy_set_header Connection "upgrade";
    }
```

**Comment by natohutch** [comment]
Hi all, this is something that would be useful for me so keen to see this move forward. I also see there've been attempts with #2148 and #1701. I'm happy to provide a little bit of help if its needed to push this across the line.

**Comment by hsmallbone** [comment]
Was in a similar boat to @lmorin-inria (requirement to run in slurm) so have made a similar patch to main as of today. Unlikely to be merged and only sporadically updated by myself.
https://github.com/hsmallbone/open-webui/tree/relative-urls

**Comment by usrdmn** [comment]
> Was in a similar boat to @lmorin-inria (requirement to run in slurm) so have made a similar patch to main as of today. Unlikely to be merged and only sporadically updated by myself. https://github.com/hsmallbone/open-webui/tree/relative-urls

Well, I may be kinda stupid, but it was unsuccessful attempt to build image from your fork, and have access by path. If you can kindly give me a hint what Im doing wrong it will be very appreciated.
My docker-compose.yaml is bellow:
```services:
  open-webui:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: open-webui-test
    volumes:
      - open-webui-1:/app/backend/data
    ports:
      - ${OPEN_WEBUI_PORT-3001}:8080
    environment:
      ROOT_PATH: "ai"
      OLLAMA_BASE_URL: "http://192.168.0.41:11434"
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  open-webui-1: {}```

When Im trying to access /ai , browser is pulling a bunch of js files with 304 statuses, and /ai/static/splash.png in the center of screen with status 200 .

**Comment by hsmallbone** [comment]
The webapp is mounted at ${ROOT_PATH}/app so the path would be /ai/app

**Comment by usrdmn** [comment]
> The webapp is mounted at ${ROOT_PATH}/app so the path would be /ai/app

Thank you very much mister. You are legend!

**Comment by lmorin-inria** [comment]
Sorry for being away for such a long time.
Please find a new update. I did not push the version 0.3.21 earlier because I was facing some small bugs
It shall be better with this 0.3.30 version (same branch)

**Comment by lmorin-inria** [comment]
> > Sorry for being away for such a long time. Please find a new update. I did not push the version 0.3.21 earlier because I was facing some small bugs It shall be better with this 0.3.30 version (same branch)
> > Note that I changed my method this time, avoiding any renaming. It shall help me to keep track of future changes with less efforts.
> 
> how to set the config?

It is a fork validated using the generation of an OCI container (i.e. Docker). You can deploy as explained in the regular documentation. It shall work. But if you want to change the PATH of the URL, set the *ROOT_PATH* environment variable.
Typically for Podman or Docker, that would be "-e ROOT_PATH=<my root path>" in the *run* command line.

**Comment by hahchenchen** [comment]
> > > Sorry for being away for such a long time. Please find a new update. I did not push the version 0.3.21 earlier because I was facing some small bugs It shall be better with this 0.3.30 version (same branch)
> > > Note that I changed my method this time, avoiding any renaming. It shall help me to keep track of future changes with less efforts.
> > 
> > 
> > how to set the config?
> 
> It is a fork validated using the generation of an OCI container (i.e. Docker). You can deploy as explained in the regular documentation. It shall work. But if you want to change the PATH of the URL, set the _ROOT_PATH_ environment variable. Typically for Podman or Docker, that would be "-e ROOT_PATH=" in the _run_ command line.

dont need config the nginx?

**Comment by lmorin-inria** [comment]
> > It is a fork validated using the generation of an OCI container (i.e. Docker). You can deploy as explained in the regular documentation. It shall work. But if you want to change the PATH of the URL, set the _ROOT_PATH_ environment variable. Typically for Podman or Docker, that would be "-e ROOT_PATH=" in the _run_ command line.
> 
> dont need config the nginx?

Sorry, that's another issue ! I do not provide a machine/cluster configuration. By the way, I use HaProxy in a more complex cluster infrastructure that goes beyond the usage of that container.

However, many web software support path relocation as a parameter, that feature is quite common. Nothing special about that one. Many proxy configurations shall work with that container.

**Comment by frdidonato** [comment]
> The feature was critical for me. I have implemented it there: https://github.com/lmorin-inria/open-webui/tree/feat/base-path-relocatable
> 
> The path is set dynamically when launching the container (variable). I will had a documentation if there are people asking for it.
> 
> The MR was rejected. I will keep that fork up to date from time to time with only that feature for the next few weeks at least.

This is an essential change for my production environment, and it works like a charm! please let's make sure this feature is integrated into the main project!

**Comment by lmorin-inria** [comment]
The changes required to accept the feature would also require a strong update of all svelte developers : they put absolute paths in the source code... Not something I would let one of my student do. But I also appreciate all the work shared by this great project. I cannot complain.

**Comment by EvanLin1704** [comment]
Can you support setting the rootpath to multiple levels?
My attempts to use the following configuration failed

`
ROOT_PATH=project01/job1/ai
URL: http://192.168.1.100:8080/project01/job1/ai
`

When she jumps to http://192.168.1.100:8080/project01/job1/ai/app
You will see a lot of following errors in developer options

`
Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.
`

> The changes required to accept the feature would also require a strong update of all svelte developers : they put absolute paths in the source code... Not something I would let one of my student do. But I also appreciate all the work shared by this great project. I cannot complain.

**Comment by lmorin-inria** [comment]
Indeed, it's a bug. It was supposed to work, but I reproduced it. Sorry about that.
I will try to fix it for my next update (~end of November).

**Comment by tjbck** [comment]
Relative path support is not something we intend to officially support at this time. The primary reasons are straightforward: I do not have the capacity to introduce additional complexities to the project right now, and no one has bothered to submit an atomic pull request that aligns with the contribution guidelines. On top of this, there are more pressing bug fixes and priority tasks that require attention, so I won’t be dedicating time to this feature for the foreseeable future.

While I acknowledge that relative path support might be helpful for a subset of users, it’s simply not a current priority. If this feature is important to you, I strongly encourage you to fork the project and maintain your own version. This is the beauty of open source—nothing is stopping you from taking ownership of the changes you care about.
