### ISSUE TITLE
[SOLVED] Weird behaviour after upgrading to 0.1.111 by deleting the old docker container+image and running the update one

### ISSUE THREAD

**Issue by PieBru** [open-webui/open-webui#1164]
# Bug Report
I'm on Arch Linux. Ollama serve/run works fine, but the WebUI became unusable after the ugrade.
  
## Description
Models that used to work properly now doen't work anymore or begin printing something, usually starting with "{" (a graph parenthesis) and then loop with the GPU at 100% until manually stopped or the ollama.service is restarted.
Again ollama works fine in all it functions, as works fine other UI that call the ollama API.
Other WebUI features work fine, like settings, update all models, etc.

**Bug Summary:**
[Provide a brief but clear summary of the bug]
This picture should explain the problem, I had to interrupt the last reply.
![image](https://github.com/open-webui/open-webui/assets/6537434/a6a6e3fa-277d-4cee-8510-f66dcc38f6b2)

**Steps to Reproduce:**
[Outline the steps to reproduce the bug. Be as detailed as possible.]
Not easy to reproduce, as I don't remember what version was the previous WebUI.

**Expected Behavior:**
[Describe what you expected to happen.]
Chat normally, like I did with all the previous UI versions.

**Actual Behavior:**
[Describe what actually happened.]
See picture above.

## Environment

- **Operating System:** [e.g., Windows 10, macOS Big Sur, Ubuntu 20.04]
- Arch Linux, updated daily
- ollama version is 0.1.29, installed with `yay -S ollama-cuda` and used as a systemd service whit this additional environment:
```bash
[Service]
Environment="OLLAMA_HOST=0.0.0.0:11434"
Environment="OLLAMA_ORIGINS='*'"
Environment="OLLAMA_MODELS=/var/lib/ollama/.ollama/models"
```
- WebUI version is 0.1.111, run with 
```bash
sudo docker run \
  -e OLLAMA_BASE_URL="http://127.0.0.1:11434" \
  --network="host" \
  -v "open-webui:/app/backend/data" \
  --name "open-webui" \
  --restart "always" \
  "ghcr.io/open-webui/open-webui:main" 
```

- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]
- Firefox 

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots
See above.

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]
It seems normal. Tell me what to search for.

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]
It seems regular. Tell me what to search for.

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]
See above.

## Installation Method
See above.

[Describe the method you used to install the project, e.g., manual installation, Docker, package manager, etc.]

## Additional Information
Please tell me iif you need more info.

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by PieBru** [comment]
All fine on the same notebook, using the same ollama:

![image](https://github.com/open-webui/open-webui/assets/6537434/bc0efa23-34dc-4170-80c9-6fead41467a9)

Thank you,
Piero

**Comment by justinh-rahb** [comment]
DeepSeek Coder **BASE** versions are not instruct-tuned, so they only do code-completion. This usually breaks chat apps in ways similar to what you demonstrate. SOLAR is just following the lead of the existing conversation context, try starting a chat and only using SOLAR and see what happens then.

**Comment by PieBru** [comment]
Thank you @justinh-rahb ,
I'm concentrating on the "weird" behaviour, not comparing models, so the output quality isn't relevant here, only the output (missing) content and formatting.

So I restarted all:
```bash
sudo systemctl restart ollama.service
sudo docker container rm open-webui
sudo docker run -e OLLAMA_BASE_URL="http://127.0.0.1:11434" ...
```
Then I:
- refreshed the browser page,
- logged in with the same user as before (admin),
- deleted the previous chats,
- cleared the vector storage
... and this is the result:

![image](https://github.com/open-webui/open-webui/assets/6537434/5dacd3d0-c4c7-4ce0-a983-8d58c598d3f8)

The WebUI was in a infinite loop with CUDA at 100% load, manually interrupted by hitting the WebUI button.

**Comment by justinh-rahb** [comment]
Wouldn't happen that you've got this set to `JSON`?

<img width="761" alt="Screenshot 2024-03-14 at 9 12 18 AM" src="https://github.com/open-webui/open-webui/assets/52832301/2537ed58-e80d-4fc4-b02b-c7239a3f3167">

**Comment by PieBru** [comment]
Did another try:
```bash
sudo docker container stop open-webui
sudo docker container rm open-webui
sudo docker image rm 664000904e8d
sudo rm -rf /var/lib/docker/volumes/open-webui/_data
sudo mkdir /var/lib/docker/volumes/open-webui/_data
sudo docker run   -e OLLAMA_BASE_URL="http://127.0.0.1:11434" ...
```
and signed-in and then logged in as admin. Similar result and 100% loop, I had to stop the chat again.
![image](https://github.com/open-webui/open-webui/assets/6537434/ec3631cf-ef07-418c-bff9-8e73b9e0ae61)

This is the relevant log:
```
Give Feedback / Get Help: https://github.com/BerriAI/litellm/issues/new


INFO:     127.0.0.1:51886 - "GET / HTTP/1.1" 304 Not Modified
INFO:     127.0.0.1:51886 - "GET /api/config HTTP/1.1" 200 OK
INFO:     127.0.0.1:51886 - "GET /api/v1/auths/ HTTP/1.1" 401 Unauthorized
INFO:     127.0.0.1:51886 - "GET /static/favicon.png HTTP/1.1" 200 OK
authenticate_user admin@gmail.com
INFO:     127.0.0.1:53108 - "POST /api/v1/auths/signin HTTP/1.1" 400 Bad Request
insert_new_auth
INFO:     127.0.0.1:37360 - "POST /api/v1/auths/signup HTTP/1.1" 200 OK
get_all_models
get_all_models
INFO:     127.0.0.1:37360 - "GET /ollama/api/tags HTTP/1.1" 200 OK
get_all_models
get_all_models
INFO:     127.0.0.1:37360 - "GET /openai/api/models HTTP/1.1" 200 OK
id='22ff489e-977e-4c8e-81ac-ffb7c09d5032' name='Admin' email='admin@gmail.com' role='admin' profile_image_url='/user.png' timestamp=1710436419
INFO:     127.0.0.1:37360 - "GET /litellm/api/v1/models HTTP/1.1" 200 OK
INFO:     127.0.0.1:37360 - "GET /api/v1/modelfiles/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:37360 - "GET /api/v1/prompts/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:37360 - "GET /api/v1/documents/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:37360 - "GET /api/v1/chats/tags/all HTTP/1.1" 200 OK
get_all_models
INFO:     127.0.0.1:37380 - "GET /api/changelog HTTP/1.1" 200 OK
INFO:     127.0.0.1:37360 - "GET /ollama/api/tags HTTP/1.1" 200 OK
INFO:     127.0.0.1:37366 - "GET /api/v1/chats/ HTTP/1.1" 200 OK
get_all_models
get_all_models
INFO:     127.0.0.1:37360 - "GET /openai/api/models HTTP/1.1" 200 OK
id='22ff489e-977e-4c8e-81ac-ffb7c09d5032' name='Admin' email='admin@gmail.com' role='admin' profile_image_url='/user.png' timestamp=1710436419
INFO:     127.0.0.1:37360 - "GET /litellm/api/v1/models HTTP/1.1" 200 OK
INFO:     127.0.0.1:37078 - "POST /api/v1/chats/new HTTP/1.1" 200 OK
INFO:     127.0.0.1:37078 - "GET /api/v1/chats/ HTTP/1.1" 200 OK
/ollama/api/chat
http://127.0.0.1:11434
b'{"model":"solar:latest","messages":[{"role":"user","content":"Write a bash script to rename all the directories contained in the current directory. Change the name so it will became all lowercase."},{"role":"assistant","content":""}],"format":"json","options":{},"stream":true}'
INFO:     127.0.0.1:37078 - "POST /ollama/api/chat HTTP/1.1" 200 OK
INFO:     127.0.0.1:41868 - "GET /ollama/cancel/f000cad1-f3bd-4473-9e67-ca03a91520f5 HTTP/1.1" 200 OK
INFO:     127.0.0.1:41868 - "POST /api/v1/chats/20ce552f-97dc-420e-929c-407ec5b6f4bf HTTP/1.1" 200 OK
INFO:     127.0.0.1:41868 - "GET /api/v1/chats/ HTTP/1.1" 200 OK
http://127.0.0.1:11434
User: canceled request
INFO:     127.0.0.1:41868 - "POST /ollama/api/generate HTTP/1.1" 200 OK
INFO:     127.0.0.1:41868 - "POST /api/v1/chats/20ce552f-97dc-420e-929c-407ec5b6f4bf HTTP/1.1" 200 OK
INFO:     127.0.0.1:41868 - "GET /api/v1/chats/ HTTP/1.1" 200 OK
INFO:     127.0.0.1:41868 - "GET /api/v1/chats/ HTTP/1.1" 200 OK
^CINFO:     Shutting down
INFO:     Waiting for application shutdown.
INFO:     Application shutdown complete.
INFO:     Finished server process [1]
```

**Comment by PieBru** [comment]
SOLVED, big thank you!
I don't know why, but the `Request mode` wasn't `Default', but `JSON`.
All my resets and restarts didn't solve.
Maybe a `Reset settings to factory defaults` button may help in these "restart from zero" noob initiatives.
Thank you again.

**Comment by justinh-rahb** [comment]
Second report like this now, might not be coincidence.

**Comment by PieBru** [comment]
Waiting to understand why it happened, maybe a *Request=JSON* may be temporarily added to the answer header only if it isn't `Default`.
