### ISSUE TITLE
Allow Disable What's New in Open WebUI

### ISSUE THREAD

**Issue by v3i1y** [open-webui/open-webui#1167]
**Is your feature request related to a problem? Please describe.**
Every time I open Open WebUI I get the pop up "What's new...."

**Describe the solution you'd like**
Only show what's new once or allow disabling it in user preference.

**Comment by v3i1y** [comment]
Ok I found the issue, you have to click "Ok, Let's Go" instead of the close button on the top :)

**Comment by haydonryan** [comment]
I love openwebui. Such an amazing app.

It would be amazing you were able to add a user preference to disable the "what's new" popup.  

My workflow is that I update the container every night, and then I'll periodically go and read what's new when I have time.  But when I'm using openwebui, it's more "new tab, open openwebui, get ready to type query, oh login, oh click Ok let's go, then type query"  

Another option would be to show what's new on the landing page, but allow the user to start typing their next chat.  For some of us type A people - less friction is better when we just need to ask our LLM something.

**Comment by haydonryan** [comment]
@tjbck  Just wondering how we do disable the "what's new dialog"?

**Comment by v3i1y** [comment]
> @tjbck Just wondering how we do disable the "what's new dialog"?

If you click on "Ok, Let's Go" it's essentially disabled unless you update it again.

**Comment by haydonryan** [comment]
That's not disabling the dialog :) - I want to update nightly, (it's an active project)  but not be forced to see the new features dialog.

**Comment by v3i1y** [comment]
> That's not disabling the dialog :) - I want to update nightly, (it's an active project) but not be forced to see the new features dialog.

Why bother updating it if you don't care what's new.

**Comment by haydonryan** [comment]
I never sai

> > That's not disabling the dialog :) - I want to update nightly, (it's an active project) but not be forced to see the new features dialog.
> 
>  you don't care what's new.
I never said that. Clearly I care.

**Comment by v3i1y** [comment]
> > you don't care what's new.
> 
> I never said that. Clearly I care.

You said you only want to read when you have time, doesn't that mean you don't care otherwise? I think you are getting yourself into a corner use case that the devs are not likely going to prioritize. This is very different from my initial issue so can you open a new issue? This one is already closed, and I don't want to get new notifications for it.
