### ISSUE TITLE
May I choose the RAG Embedding model?

### ISSUE THREAD

**Issue by leoleelxh** [open-webui/open-webui#1169]
May I choose the RAG Embedding model? Since I have deployed openwebui onto my NAS server, which has limited computing power, can I opt for OpenAI's embedding model to reduce local computational resources usage?

**Comment by leoleelxh** [comment]
> Embedding is currently only possible locally, there's no support for using external embedding model APIs as of right now. PRs of course welcome, we _could_ potentially support Ollama or OpenAI embedding I think.

Yes, that's a great idea, which would give openwebui more flexibility.

**Comment by jannikstdl** [comment]
related #679

**Comment by tjbck** [comment]
Duplicate https://github.com/open-webui/open-webui/issues/679
