### ISSUE TITLE
Support timeout or cancel the request

### ISSUE THREAD

**Issue by yeasy** [open-webui/open-webui#1170]
**Is your feature request related to a problem? Please describe.**
When calling some model such as gemma, it happens to get stuck for quite a while, and the console can do nothing. Even close the web-ui, the calculation is still going in the background.

**Describe the solution you'd like**
Add timeout in the configuration, or allow cancel the request.

**Describe alternatives you've considered**
Maybe the timeout can be supported at ollama side, too.

**Additional context**
N/A

**Comment by tjbck** [comment]
Our webui supports cancelling the request when you press the stop button in the input textarea, if you had other implementation in mind feel free to make a PR!
