### ISSUE TITLE
There was an issue connecting to Ollama ("POST /chat HTTP/1.1" 400 Bad Request)

### ISSUE THREAD

**Issue by Touffman78** [open-webui/open-webui#1171]
# Bug Report
After image génération, unable to send new request.
Always get the "Uh-oh! There was an issue connecting to Ollama."

## Description
After generating an image with AUTOMATIC111 (txt2img), all new requests results in the error "Uh-oh! There was an issue connecting to Ollama." which ever LLM selected.
The corresponding error on Ollama side is a 400 for the "POST /api/chat".

When starting a new chat, all is OK, but going back to the chat with image is still NOK

**Steps to Reproduce:**
Ollama v0.1.27, OpenWebUI v0.1.111, Stable-Diffusion-webui v1.8.0

Generate a prompt for image generation (repeat this : ....) then click on "image generation".
When image is shown, try to ask anything => error

## Logs and Screenshots

**Screenshots (if applicable):**
![Capture d’écran 2024-03-14 173558](https://github.com/open-webui/open-webui/assets/48481054/68761b05-74c6-4533-b955-3e349dd3116d)

## Installation Method

[Docker]

**Comment by tjbck** [comment]
This issue has been resolved on our dev branch! #1137 We'll be merging to main soon, but feel free to switch to our dev branch in the meantime!
