### ISSUE TITLE
bug: hanging when trying to setup automatic1111 integration

### ISSUE THREAD

**Issue by jsuto** [open-webui/open-webui#1172]
# Bug Report

## Description

I try to setup image generation integration with automatic1111. When I enter the url, I can see a successful connection from the webui to port 7860, and I can even select the default model. However, when I click on the green save button, it doesn't save the settings, instead it hangs. See the below screenshot.

I use open-webui v0.1.111 - 2024-03-10

**Bug Summary:**
[Provide a brief but clear summary of the bug]

**Steps to Reproduce:**
[Outline the steps to reproduce the bug. Be as detailed as possible.]

**Expected Behavior:**

The settings should be saved

**Actual Behavior:**

It's hanging, and I can't select the realvisxIV40 model to generate an image

## Environment

Linux Firefox, the Chrome

## Reproduction Details

**Confirmation:**

- [ ] I have read and followed all the instructions provided in the README.md.
- [ ] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

<img width="668" alt="image" src="https://github.com/open-webui/open-webui/assets/5683354/f1b7e2ec-52ea-4ad5-857f-be5fa20fff19">

**Browser Console Logs:**

"Uncaught (in promise) Oops! It looks like there's a hiccup. The API key is missing. Please make sure to provide a valid API key to access this feature."

Note that I don't want to connect to openai, instead to automatic1111 running on the same host, which doesn't need an api key

**Docker Container Logs:**

INFO:     x.x.x.28:55462 - "POST /images/api/v1/url/update HTTP/1.1" 200 OK
INFO:     x.x.x.28:55462 - "GET /images/api/v1/models HTTP/1.1" 200 OK
INFO:     x.x.x.28:55462 - "GET /images/api/v1/models/default HTTP/1.1" 200 OK
INFO:     x.x.x.28:55463 - "POST /images/api/v1/key/update HTTP/1.1" 400 Bad Request

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Installation Method

It runs in docker container

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by Yabbo** [comment]
im on Open WebUI Version
v0.1.111 [(latest)](https://github.com/open-webui/open-webui/releases/tag/v0.1.111)

When i try and save its just spins on saving
![image](https://github.com/open-webui/open-webui/assets/1466651/1bc9892e-a4b1-4659-8735-c36fb4316829)

the webui for stable difusion / automatic1111 is running and reachable from the URL provided. the check comes back good.

**Comment by Ethike458** [comment]
This happens to me as well since the last release.  The save button for this section just spins and your settings do not stick.  I noticed it will run the first model in the list of models (or I believe the last one since update), but it will not save any changes, nor let you change models.

**Comment by Real-Bimox** [comment]
I have the same issue as above.

**Comment by tjbck** [comment]
Taking a look!

**Comment by tjbck** [comment]
Should be fixed on our dev branch now, feel free to try it out and let me know if the issue persists!

**Comment by jsuto** [comment]
Sure, what's the docker image I could test with?

**Comment by jsuto** [comment]
Thank you, I can confirm that your fix has worked.
