### ISSUE TITLE
feat: last online status in admin panel

### ISSUE THREAD

**Issue by jannikstdl** [open-webui/open-webui#1176]
**Describe the solution you'd like**
It would be informative to have a "last online" badge in the admin panel to see the users activity and get an eye on the usage load and which accounts could be deleted because they are not in use anymore.

**Comment by jannikstdl** [comment]
Could be at first easily done to update the last online status of someone sends a message.

**Comment by tjbck** [comment]
LiteLLM integration would complicate things here, so I would suggest we support this feature for native integrations (Ollama and OpenAI APIs)
