### ISSUE TITLE
feat: title generation support for external models

### ISSUE THREAD

**Issue by mafrasiabi** [open-webui/open-webui#1178]
# Bug Report

## Description

**Bug Summary:**
The Title Auto-generate doesn't work with LiteLLM and Claude Model

**Comment by tjbck** [comment]
LiteLLM auto-title generation is unsupported, but you should still be able to set the title generation model to your local model which will generate the title for you.

**Comment by mafrasiabi** [comment]
I don't have local model. Just a question , does LiteLLM use OpenAI completion underneath?

**Comment by justinh-rahb** [comment]
> I don't have local model. Just a question , does LiteLLM use OpenAI completion underneath?

It uses whatever API(s) you configure it for:
- #1038

**Comment by mafrasiabi** [comment]
thanks!
I meant is it using backend/apis/openai methods?
