### ISSUE TITLE
feat: InvokeAI Image Generation Support

### ISSUE THREAD

**Issue by alfi4000** [open-webui/open-webui#1188]
Hi i personally like invokeai more then A1111 because it is healthier handeling gpu resource for consumer hardware is there any plan to support their api for image generation?

Here there repo:
https://github.com/invoke-ai/InvokeAI

It supports very small GPUs too not like A1111 when you get in trouble because of not enough vram!

**Comment by justinh-rahb** [comment]
Unclear whether they even _have_ an API. Did you find any documentation that I've been unable to find so far?

https://github.com/invoke-ai/InvokeAI/discussions/2600

**Comment by alfi4000** [comment]
There is apiwhen running invokeai just behind access ip adress or localhost and port /doc! ill show I screen recording!

**Comment by justinh-rahb** [comment]
> There is api when running invokeai just behind access ip adress or localhost and port /doc! ill show I screen recording!

As noted here: https://github.com/invoke-ai/InvokeAI/discussions/2600#discussioncomment-7573198

This doesn't seem to cover generation, although that was some months ago. If the current status is changed, let us know.

**Comment by alfi4000** [comment]
Oh ok i will check that! And ask Invokeai community because they were talking about It will happen soon and I will check on my instance the api and reach back!

**Comment by alfi4000** [comment]
Someone Figured out how to do it over endpoint: https://github.com/invoke-ai/InvokeAI/discussions/2600#discussioncomment-8816493

**Comment by alfi4000** [comment]
It appears to me to be possible this user explained it a bit could you may take a look at it. :) for me it is like a different language I am not a dev or so just a consumer!

**Comment by alfi4000** [comment]
The Invokeai contributers haven’t answerd me yet maybe the next days!

**Comment by psychedelicious** [comment]
We've had a REST API for quite a while. A maintainer provided the URL to the autodoc for it about a year ago. I've just replied to the linked discussion again: https://github.com/invoke-ai/InvokeAI/discussions/2600#discussioncomment-8821697

**Comment by justinh-rahb** [comment]
Ya... none of that new discussion is giving me any additional confidence that this is something we could _easily_ add, looks like it would indeed be a significant amount of work and possibly require reverse-engineering the client->backend communications. The spec is complete, but that's just a map... it provides no directions.

**Comment by psychedelicious** [comment]
Sorry, to be clear, I am also a maintainer for Invoke.

Indeed, integrating it into this project would be rather complicated. Besides constructing a valid graph, you'd need a socket.io client to listen for events. You'd also probably want to provide some queue and model install interaction capabilities.

While we have a REST API, it's built for the application and not particularly well suited to run as a headless server for an arbitrary frontend. It certainly can be done but would be a substantial effort.

**Comment by justinh-rahb** [comment]
Totally get it, same for us.. our API exists, but only to serve the needs of our frontend. If someone finds a novel use for that, cool, but that wasn't in our plans 😜

**Comment by alfi4000** [comment]
Oh so it will most likely not happen yet!?

**Comment by justinh-rahb** [comment]
Unless an unexpected pull request emerges, it appears unlikely that our current contributors will undertake this project, given our focus on numerous other unimplemented features. We already support two image generation backends, including a local one that utilizes the same models as Invoke. Therefore, the justification for developing extensive new code to achieve the same outcome seems limited.

**Comment by alfi4000** [comment]
Ok got it

**Comment by TheRsKing** [comment]
Would love to see this because of the great Docker support from both sides.
