### ISSUE TITLE
basic docker set up question

### ISSUE THREAD

**Issue by LaptopDev** [open-webui/open-webui#1190]
I am accessing the webui remotely, running both ollama and open-webui on my remote server.
I want models to run on my powerful server, and want to interact with them through the webui.

For some reason the instructions do not explicitly inform you of what docker run command to use for this configuration. There are two docker run commands to choose from, one which is used for local connection to a local ollama server, which I chose, and another which is used to connect to a remote ollama server. 

I can not connect to ollama. I cannot add models. On my server I can list 2 models available in terminal with ollama which do not show up in open-webui. Do I need to use the other docker run command?

**Comment by justinh-rahb** [comment]
The method of communication between the two containers remains consistent whether they're hosted on a remote server or your local machine, provided they're deployed together. The only change involves how you interact with the WebUI; instead of using http://localhost:3000, you'd connect via the server's IP address or hostname. Given this setup, leveraging Docker Compose for installation is advisable. This approach not only simplifies managing the containers as a single unit but also makes full use of Docker's capabilities on a server environment.

https://docs.openwebui.com/getting-started/#using-docker-compose

**Comment by LaptopDev** [comment]
> ... ...communication between the two containers... ...provided they're deployed together. ... ... Given this setup, leveraging Docker Compose for installation is advisable. This approach ... ... simplifies managing the containers as a single unit but also makes full use of Docker's capabilities on a server environment.
> 
It seems to me, maybe I did not make clear, you are under the impression that I ran both in containers. I technically did follow the instructions since my binary execution of 'ollama serve' is  "on my computer".

```
If Ollama is on your computer, use this command:

docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main
```
But what I am understanding from your reply is this means they are not "deployed together", and must be (making the quick start documentation inapplicable for those running ollama as a binary). Do I got that right?

I am connecting via the server's IP address fine, and assume that I would be doing the same with a set up involving docker-compose.yml/compose.yml according to the documentation you linked. But it seems there is some misunderstanding about my set up configuration still and what is causing it to not connect to ollama.

**Comment by justinh-rahb** [comment]
Now I understand your deployment scenario better:

```bash
docker run -d -p 3000:8080 -e OLLAMA_BASE_URL=http://your-computer-ip:11434 -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main
```

**Comment by LaptopDev** [comment]
> docker run -d -p 3000:8080 -e OLLAMA_BASE_URL=http://your-computer-ip:11434 -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main
This doesn't seem to work for me.

**Comment by justinh-rahb** [comment]
Your Ollama is running on a server or your desktop/laptop, which is it? I'm getting mixed messages here which is confusing my ability to assist.

**Comment by LaptopDev** [comment]
I see. Thank you for your patience! I got it working now.
