### ISSUE TITLE
Nvidia GPU in docker doesn't work

### ISSUE THREAD

**Issue by jynrock** [open-webui/open-webui#1192]
Hi,
I tried to activate the gpu by adding these lines (as here https://github.com/open-webui/open-webui/discussions/1017 ) to the docker stack:
deploy :
      resources :
        reservations :
          devices :
            - driver : nvidia
              count : 1
              capabilities : [gpu]

But when I deploy the stack, I get this error:

failed to deploy a stack : ollama Pulling ollama Pulled Container ollama Recreate Container ollama Recreated Container open-webui Recreate Container open-webui Recreated Container ollama Starting Error response from daemon : could not select device driver "nvidia" with capabilities : [[gpu]] 

Ubuntu 22.04
Docker 25.0.4
RTX 3080
Driver Version: 535.161.07
CUDA Version: 12.2

**Comment by cjhmdm** [comment]
Are you using Docker Desktop? If so, it doesn't have gpu support in linux. I had to remove Docker Desktop completely in order to get this working.

**Comment by jynrock** [comment]
If I quit Docker Desktop, all my containers stop too

**Comment by justinh-rahb** [comment]
> If I quit Docker Desktop, all my containers stop too

That is expected behaviour.

**Comment by jynrock** [comment]
Ok, but how the containers start without docker desktop ?

**Comment by cjhmdm** [comment]
> Ok, but how the containers start without docker desktop ?

command line

**Comment by jynrock** [comment]
Without docker desktop launch I can't access to portainer, openwebui doesn't work, and the command "docker ps -a" show no container.

**Comment by justinh-rahb** [comment]
Jynrock, uninstall Docker Desktop, and install Docker this way instead:

https://docs.docker.com/engine/install/ubuntu/

**Comment by jynrock** [comment]
Thank you very much
Finally everything work

**Comment by DavidOrakpo** [comment]
I deleted docker desktop. I tried running open web ui docker install command for gpus. But I get the error "Cannot connect to the Docker daemon"

> Thank you very much Finally everything work
