### ISSUE TITLE
feat: Setting to auto search documents in RAG

### ISSUE THREAD

**Issue by ShaunBoughey** [open-webui/open-webui#1194]
**Is your feature request related to a problem? Please describe.**
Currently you need to use # to select a file or collection to search. I would love an ability as an admin to set it to be able to auto search documents. Primary usecase is document searching for a project.

This would allow prompts added in the "user interface" section to actually search documents.

**Describe the solution you'd like**
An admin setting to toggle default searching a collection/list of collections

**Comment by nejib1** [comment]
For your information, this issue will be closed due to duplication. There have been multiple similar requests, and the author has closed all of them citing the same reason.
 However, **none of these requests have been done**. It seems there's a reluctance to undertake this development; the only response given is "duplicated".

**Comment by tjbck** [comment]
@nejib1 Not that I'm reluctant to implement this; we all simply have our day jobs and are working on this project in our free time :) We encourage everyone to make a pull request!

**Comment by justinh-rahb** [comment]
> For your information, this issue will be closed due to duplication. There have been multiple similar requests, and the author has closed all of them citing the same reason.
>  However, **none of these requests have been done**. It seems there's a reluctance to undertake this development; the only response given is "duplicated".

Send patches.

**Comment by nejib1** [comment]
> > For your information, this issue will be closed due to duplication. There have been multiple similar requests, and the author has closed all of them citing the same reason.
> > However, **none of these requests have been done**. It seems there's a reluctance to undertake this development; the only response given is "duplicated".
> 
> Send patches.

Please read again...

**Comment by justinh-rahb** [comment]
> Please read again...

No.

**Comment by jannikstdl** [comment]
@tjbck guess he thinks you are ChatGPT or smh
