### ISSUE TITLE
Support custom prompts per conversation

### ISSUE THREAD

**Issue by lukemauldinks** [open-webui/open-webui#1198]
**Is your feature request related to a problem? Please describe.**
I cannot set custom prompts that will be retained for different conversations.

**Describe the solution you'd like**
In AnythingLLM, each separate "workspace" is allowed to have its own system prompt.  With this functionality, I can have one Workspace with a prompt for software engineering questions and another Workspace with a prompt tailored to managerial functions.  

**Describe alternatives you've considered**
Using the `/prompt` functionality but this requires resetting of the prompt for each comment in the conversation.

**Comment by tjbck** [comment]
Duplicate #619, Let's continue our discussion there!
