### ISSUE TITLE
feat: pure text ingestion API for RAG

### ISSUE THREAD

**Issue by icsy7867** [open-webui/open-webui#1200]
**Is your feature request related to a problem? Please describe.**
Straight text ingestion is fast.  In most of my cases I am trying to ingest certain policy pages or confluence pages.  Confluence has an api which allows me to get html of a page.  I can then easily parse and send this as plain text.  Currently I am sending a few hundred confluence pages in a couple minutes. 

**Describe the solution you'd like**
It would be nice to have a restapi endpoint to ingest straight text.  It should include a document title name, and the text body.  Ideally the title could also be a URL to a website location.

**Describe alternatives you've considered**
Trying to save the documents as text files first.  And then ingesting.  But the extra overhead here is a lot.

**Additional context**
While I need a text ingestion api, might be nice to be able to have a file ingestion api as well.

**Comment by tjbck** [comment]
Added to our dev branch! You can check out the RAG API endpoints here:`http://[Your Open WebUI]/rag/api/v1/docs`

**Comment by longfei-zhang** [comment]
@tjbck I can't find the RAG API endpoint through http://[Your Open WebUI]/rag/api/v1/docs
it show me 404: Not Found

the log from the open web ui pod:
`INFO:     10.77.0.2:0 - "GET /rag/api/v1/docs HTTP/1.1" 304 Not Modified
INFO:     connection closed
INFO:     10.77.0.2:0 - "GET /favicon/favicon.svg HTTP/1.1" 304 Not Modified
INFO:     10.77.0.2:0 - "GET /_app/version.json HTTP/1.1" 200 OK
INFO:     10.77.0.2:0 - "GET /api/config HTTP/1.1" 200 OK
`
