### ISSUE TITLE
add RAG: cpu/cuda/mps as a config variable rather than hardcode

### ISSUE THREAD

**Issue by drawingthesun** [open-webui/open-webui#1210]
File: `backend/config.py` has the following hardcoded variable:

```python
RAG_EMBEDDING_MODEL_DEVICE_TYPE = os.environ.get(
    "RAG_EMBEDDING_MODEL_DEVICE_TYPE", "cpu"
)
```

I use open-webui locally without Docker, and whenever I do an update I have config.py replaced, however the hardcoded variable I have to change everytime to "mps" and I forget a lot of the time.

**Comment by jannikstdl** [comment]
Related #1165
