### ISSUE TITLE
bug: i18n chinese not working

### ISSUE THREAD

**Issue by jxyk2007** [open-webui/open-webui#1214]
## Issue Description
Despite changing the language setting to Chinese in the settings, the interface continues to display in English. I tried clearing the cache and restarting the app, but the issue persists.

## Steps to Reproduce
1. Open the app and go to Settings.
2. Change the language setting to Chinese.
3. Save and exit the settings.
4. The interface language does not change to Chinese and continues to display in English.

## Expected Behavior
After changing the language setting to Chinese, the app interface should display all text in Chinese.

## Actual Behavior
After changing the language setting to Chinese, the app interface still displays in English.

## Environment Information
- Device: [Please fill in your device model, e.g., iPhone 12]
- Operating System: [Please fill in your operating system version, e.g., iOS 15.4]
- App Version: [If applicable, please provide the app version]

## Additional Information
Please provide any additional information (such as screenshots) here.

I hope this can be resolved soon. Thank you!

**Comment by jxyk2007** [comment]
I didn't install it using Docker; I installed it by running npm run build, and I can't switch languages.

**Comment by asedmammad** [comment]
I could not reproduce the issue in `dev` branch, @jxyk2007 Can you check if any errors are displayed in the browser's console?

**Comment by jxyk2007** [comment]
The container running docker already supports Chinese, so there is no need to modify the language yourself, which is very good.

**Comment by tjbck** [comment]
@jxyk2007 not sure if I understand your issue report entirely, Is the issue resolved then?
