### ISSUE TITLE
Piper TTS as additional TTS Engine

### ISSUE THREAD

**Issue by ei23fxg** [open-webui/open-webui#1224]
**Is your feature request related to a problem? Please describe.**
The currently available options for TTS (Text-to-Speech) are limited to OpenAI and the local TTS.

**Describe the solution you'd like**
[Piper TTS](https://github.com/rhasspy/piper) is a great open source TTS project with a variety of TTS voices, you also can create your own. It's also used in Home Assistant for example

**Comment by justinh-rahb** [comment]
All related:
- #126 
- #406
- #1224
