### ISSUE TITLE
feat: Model Whitelisting for LiteLLM

### ISSUE THREAD

**Issue by flyfox666** [open-webui/open-webui#1227]
**Is your feature request related to a problem? Please describe.**
I have both local model and litellm model in use, then when assigning to registered users, I found that I can only use model whistling function for local model, litellm connected model can still be selected in users. Is it possible to limit Model Whitelisting to litellm models as well?

**Describe the solution you'd like**
Model Whistling function could also be affected in litellm connected model

**Describe alternatives you've considered**
Set up password for litellm connected model useing

![1](https://github.com/open-webui/open-webui/assets/121539277/e8b2965d-1705-4e18-8a6c-be77ef58f95a)
![2](https://github.com/open-webui/open-webui/assets/121539277/b3dccdd3-5162-4fcb-bf56-721678438861)

**Comment by justinh-rahb** [comment]
In the Ollama and OpenAI endpoints, you have no control over what the `/api/models` or `/v1/models` endpoints return, so a whitelist was deemed useful to limit what's displayed to users. In LiteLLM, you control which models you add so it was assumed that admins would only add models they want their users to use. More granular access controls in general are still on the roadmap.

**Comment by flyfox666** [comment]
Oh ,thanks, justinh-rahb, 
Appreciate if it is possible to update this fuction in future. 
The main reason for my issue is sometimes could only Litellm for my wife and not for my friend.

**Comment by justinh-rahb** [comment]
I agree it would be good to extend the feature to cover LiteLLM as well, just trying to shed light on the possible reasons it was overlooked or deferred.

**Comment by flyfox666** [comment]
much appreicate
