### ISSUE TITLE
feat: configurable webui name

### ISSUE THREAD

**Issue by terminationshok** [open-webui/open-webui#1238]
**Is your feature request related to a problem? Please describe.**
I would like to be able to change the webui name / html title / app name. In my fork, I have hard coded changes in several places.

**Describe the solution you'd like**
Put the values in .env and read the values at build / runtime.

**Describe alternatives you've considered**
Without the pull request, I will be doing merges on every update.

**Additional context**
<img width="1174" alt="Screenshot 2024-03-20 at 5 31 39 PM" src="https://github.com/open-webui/open-webui/assets/1037899/fba05772-b8ff-47d7-9c93-bbc03ffe4b3f">

**Comment by tjbck** [comment]
I'll be gradually adding this to the config.json file, stay tuned!
