### ISSUE TITLE
Updating OpenWebUI disables Whitelisted models & OpenAI API Key in Admin Settings

### ISSUE THREAD

**Issue by Rep0se** [open-webui/open-webui#1248]
# Bug Report

## Description

**Bug Summary:**
Updating OpenWebUI resets Admin Settings which includes Whitelisted models and OpenAI API Key cofiguration. After each update manual configuration setting is required as a workaround.

**Steps to Reproduce:**
1. Update WebUI using the following command:
docker run --rm --volume /var/run/docker.sock:/var/run/docker.sock containrrr/watchtower --run-once open-webui
2. Navigate to Admin Settings to find Whitelisting and OpenAI API Key disabled.

**Expected Behavior:**
Admin Settings should persist through updates.

**Actual Behavior:**
Admin Settings do not persist through updates.

## Environment

- **Operating System:** macOS Sonoma
- **Browser (if applicable):** Brave (Chrome)

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
N/A

**Docker Container Logs:**
N/A

**Screenshots (if applicable):**
N/A

## Installation Method

Terminal installation using docker commands (see above)

## Additional Information

N/A

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by justinh-rahb** [comment]
Read these two guides to set it permanently:
https://docs.openwebui.com/tutorial/openai
https://docs.openwebui.com/tutorial/ollama

**Comment by Rep0se** [comment]
Thanks. I’ll set up ENV vars for OpenAI. How about whitelisting?

**Comment by Rep0se** [comment]
Thanks. I’ll set up ENV vars for OpenAI. How about whitelisting?

**Comment by Rep0se** [comment]
Oh, sweet. Thanks for the answer. It in itself is some good documentation for people searching in issues. Much appreciated!
