### ISSUE TITLE
RAG source retrieval

### ISSUE THREAD

**Issue by JonoSax** [open-webui/open-webui#1251]
**Is your feature request related to a problem? Please describe.**
Suggestion to have a new feature. This would enable feature parity with PrivateGPT's RAG interface.

**Describe the solution you'd like**
When using RAG, return the source of the queried content (ie document names and the location within these used in the prompt). This would be similar to what PrivateGPT is able to do by providing the references of where it gets the content from (ie pg. 2 of [doc name]) which is extremely helpful in order to validate the output of any LLM.

**Describe alternatives you've considered**
Including in the prompt, "return the queries used to generate the response" and other similar prompts unreliably shows returns the content from the document used.

**Additional context**
No additional info.

**Comment by tjbck** [comment]
Duplicate #715, let's continue our discussion there!
