### ISSUE TITLE
feat: configurable `i18n` translation feature / default language

### ISSUE THREAD

**Issue by changchiyou** [open-webui/open-webui#1256]
**Is your feature request related to a problem? Please describe.**
Currently, i18n only automatically detects the local language and applies the corresponding translated content. However, I hope to allow users to decide whether to enable this feature during the deployment phase. 

The reason for such a demand is because the translation quality of various languages is currently not stable enough (and I am assisting in improving this at https://github.com/open-webui/open-webui/pull/1247 ). Additionally, considering that some non-native English speakers may still prefer using the English interface, I hope to have an option available during Docker deployment for users to decide whether to enable the translation into the local language.

**Describe the solution you'd like**
I hope to allow users to decide whether to enable this feature(`i18n` translation) during the deployment phase by setting `config.json` mentioned in https://github.com/open-webui/open-webui/issues/1238#issuecomment-2010994094, https://github.com/open-webui/open-webui/pull/1151#issuecomment-2008159124.

**Describe alternatives you've considered**
Alternatively, allowing users to specify the desired target language for translation after disabling the automatic detection of the local language.

**Additional context**
Nothing.

**Comment by asedmammad** [comment]
@changchiyou I've made some crude adjustments in [asedmammad/feat/i18n-navigator-config](https://github.com/asedmammad/open-webui/tree/feat/i18n-navigator-config) branch that I believe address the issue you reported. Please be aware that the code is not yet ready for production use and has low quality. Could you please confirm whether these changes address your request?

**Comment by changchiyou** [comment]
> @changchiyou I've made some crude adjustments in [asedmammad/feat/i18n-navigator-config](https://github.com/asedmammad/open-webui/tree/feat/i18n-navigator-config) branch that I believe address the issue you reported. Could you please confirm whether these changes address your request?

@asedmammad Looks like it indeed meets my needs. Bravo! 👍

**Comment by asedmammad** [comment]
Thank you for the confirmation, @changchiyou ! Once I've cleaned up the code, I'll create a pull request to merge the changes.
