### ISSUE TITLE
bug: "Scan for documents" does nothing

### ISSUE THREAD

**Issue by greyivy** [open-webui/open-webui#1261]
# Bug Report

## Description

**Bug Summary:**
I've mapped a directory to `/data/docs` but **Scan for documents** doesn't seem to do anything apart from show **Scan complete!**. I've confirmed that the bind is working and files are accessible. My files are in subfolders in markdown format, but text files do not seem to work either. No error message is shown in the logs. Manually uploading individual files works.

**Steps to Reproduce:**
- Bind mount a folder into `/data/docs`
- Click **Scan for documents**

**Expected Behavior:**
- Documents from the mount are populated and **Scan complete!** is shown

**Actual Behavior:**
- **Scan complete!** is shown but nothing happens

## Environment

- **Operating System:** macOS M1 / Docker Desktop
- **Browser (if applicable):** Safari

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
No logs, but `http://localhost:3000/rag/api/v1/scan` returns `true` in its response

**Docker Container Logs:**
```
2024-03-22 08:30:20 INFO:     192.168.65.1:20300 - "GET /rag/api/v1/scan HTTP/1.1" 200 OK
```

Nothing else relevant, no errors.

**Screenshots (if applicable):**
![image](https://github.com/open-webui/open-webui/assets/5335625/68a172ed-7a2e-4e0a-a74a-e0229c8b3728)

## Installation Method

Docker using the provided instructions. Everything else is functional.

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by justinh-rahb** [comment]
Full directory path is `/app/backend/data/docs`, try binding to that.

**Comment by greyivy** [comment]
Thank you, that fixed it!
