### ISSUE TITLE
OpenAI key keeps resetting

### ISSUE THREAD

**Issue by NinjaPerson24119** [open-webui/open-webui#1264]
# Bug Report

## Description

**Bug Summary:**

OpenAI key keeps getting reset when I reload the page. Maybe there's something wrong with persistency?

My chat history still exists, but the OpenAI key disappears.

**Steps to Reproduce:**

Use the app

**Expected Behavior:**

My settings don't reset.

**Actual Behavior:**

My settings do get reset

## Environment

Linux, EndeavourOS, deployed on docker using README.md command
Chromium 123.0.6312.46

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Installation Method

[Describe the method you used to install the project, e.g., manual installation, Docker, package manager, etc.]

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by justinh-rahb** [comment]
We'll soon be able to save these settings from the UI to a config.json file, but for now you can use environment variable:
`OPENAI_API_KEY`.

**Comment by JuanjoJG-WATA** [comment]
> environment

Sorry I'm new to this and I have very little idea, how am I supposed to change that environment variable, and where?
