### ISSUE TITLE
System prompt for 1 user gets copied and applied for all users

### ISSUE THREAD

**Issue by airdogvan** [open-webui/open-webui#1265]
I have 5 different users on my system.  One user created a system prompt, saved it in the appropriate space in the UI configuration (General/System prompt) and exactly the same prompt was copied to all users and the AI's response was responding in accordance with new prompt for all users.

Going in each user's profile I saw that the prompt had been copied in their config.

Running docker-compose, Open Webui version: v0.1.107

OS: Ubuntu 22.04 LTS

**Comment by tjbck** [comment]
System prompt is saved on the browser-side, so if you're using the same browser to access it'll copy over to the other account. Keep our progress here for persisting settings in the background: #1022

**Comment by airdogvan** [comment]
not only not the same browser, not the same computer.  Different machines...

**Comment by airdogvan** [comment]
upon further reflection the actual prompt text was created in the same browser, and only after used on another machine.
