### ISSUE TITLE
feat: custom model selector

### ISSUE THREAD

**Issue by NiLon** [open-webui/open-webui#1281]
When opening a new chat there is option to select a model. This dropdown menu should have filtering option where you write something, it only shows matching models. I'm dealing with 30+ models and it's bit tedious to find the one from the list. It should be fuzzy search, such as matching "Gemma" when given "gem" as filtering option, or "13b" etc.

Optional feat 2: Possibly with some sort of regex option such as "7b|13b" would show both 7B and 13B parameter models.
Optional feat 3: And this option possibly could be sticky, so that the search option stays active until removed even when going to new chat. This is closely related to "favorite" model concept, but with having multiple that could dynamically change.

**Comment by justinh-rahb** [comment]
My list is getting quite unmanageable as well, **+1** from me!

**Comment by tjbck** [comment]
![image](https://github.com/open-webui/open-webui/assets/25473318/a1bdf85e-91ac-4e69-b98d-65922ee8c4bf)

Just added model search feature with a custom model selector to our dev branch, please try it out and let us know if you encounter any issues!

**Comment by NiLon** [comment]
The search seems to work in its basic form. But could we also get back the old feature that did split models from different sources. Such as local ollama models and different api's? It is useful to know. Also if possible could the dropdown size scale with the viewport size? If there is more room, the dropdown could be longer so that there is less need to scroll.

**Comment by justinh-rahb** [comment]
> The search seems to work in its basic form. But could we also get back the old feature that did split models from different sources. Such as local ollama models and different api's? It is useful to know. Also if possible could the dropdown size scale with the viewport size? If there is more room, the dropdown could be longer so that there is less need to scroll.

Agreed, some sort of label to delineate the sources would be nice to have back.
