### ISSUE TITLE
feat: Make LLM integrations toggleable (Ollama, LiteLLM, ...?)

### ISSUE THREAD

**Issue by qdrop17** [open-webui/open-webui#1288]
I host Open WebUI on a small server at home. I connect various inference providers to it, such as OpenRouter and OpenAI. Additionally, I have a gaming rig with an RTX 3090 GPU, which I only power on when needed due to its high energy consumption.

**Problem**:
When the gaming rig is offline, Open WebUI encounters a timeout while loading tags, causing the application to display a blank white screen for 5-10 seconds. This issue seems to be related to a network layer problem because even if the Ollama endpoint is down, the timeout does not occur as long as the host is running.

**Desired Solution**:
It would be beneficial if the different integrations could be toggled in the settings or if the Ollama endpoint could be lazy-loaded, preventing it from hindering the application's startup process.

**Current Workaround**:
As a temporary workaround, I set the IP address to another online host, such as the gateway, but this is merely a temporary fix.

Thanks for delivering this impressive piece of software!

**Comment by justinh-rahb** [comment]
I agree and have some similar situations in my home setups where various backends may not be available all the time.

**Comment by ScuttleSE** [comment]
Similarly, I am running just the webui, using it as an alternate frontend to OpenAI. There doesn't seem to be a way to disable or remove the ollama integration. 

In Settings - Connections, even if you delete the predefined ollama-url http://host.docker.internal:11434 and click save, it is back when you go back into settings.

**Comment by justinh-rahb** [comment]
@ScuttleSE it can't be removed. If it can't resolve that URL it just won't use it.

**Comment by ScuttleSE** [comment]
It still generates errors in the log that it can't reach http://host.docker.internal:11434/

**Comment by lee-b** [comment]
I've had a similar thought for offline use on phones etc.  It would be great to have fallback to even a relatively dumb local AI, but use the more powerful AI when available.  Ideally the dumb AI would cue complicated requests and say "I'll think about that and get back to you" or something, then "get back to you" when the smarter AI is available, but that's more like agentic workflow that could come much later. Supporting the dumb local AI fallback would be a step in that direction, though.

**Comment by tjbck** [comment]
![image](https://github.com/open-webui/open-webui/assets/25473318/8f5a2aca-0a7c-4bbc-b4b4-3a1cd78493fc)


Implemented on our dev branch! Let us know if you encounter any issues!
