### ISSUE TITLE
feat: more env vars

### ISSUE THREAD

**Issue by scharc** [open-webui/open-webui#1301]
**Is your feature request related to a problem? Please describe.**
I am trying to streamline the redeployment of the current webui and some of the settings have default values which do not have a corresponding env var. 

**Describe the solution you'd like**
Have env vars for all default settings

**Comment by silentoplayz** [comment]
Hope all is sufficient enough now for users. I'm sure new environment variables will come in the future as well! For reference, here's the current documented list of environment variables that can be set for Open WebUI: https://docs.openwebui.com/getting-started/env-configuration
