### ISSUE TITLE
no option to pull model from ollama.com

### ISSUE THREAD

**Issue by PierreGode** [open-webui/open-webui#1314]
# Bug Report

## Description

**Bug Summary:**
no option to pull model from ollama.com

**Steps to Reproduce:**
have ollama as docker container and executed docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main

**Expected Behavior:**
see the Ollama model download as in the gif presentation

**Actual Behavior:**
only option to manage LiteLLM models visible in models menu.

## Environment

- **Operating System:** [e.g., Windows 10, macOS Big Sur, Ubuntu 20.04]
- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]
-Raspberry PI 5
all browsers

## Reproduction Details

**Confirmation:**

- [ x] I have read and followed all the instructions provided in the README.md.
- [x ] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]
![image](https://github.com/open-webui/open-webui/assets/8579922/e7cc7426-be8a-4803-8e5b-0e49744aaa59)

## Installation Method

[Describe the method you used to install the project, e.g., manual installation, Docker, package manager, etc.]
docker installation

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by justinh-rahb** [comment]
https://github.com/ollama/ollama/blob/main/docs/faq.md#setting-environment-variables-on-mac

**Comment by PierreGode** [comment]
Just wiped my docker and cloned this repo and used the docker compose from here.
Now it works
