### ISSUE TITLE
Feat: Allow setting API key in user settings

### ISSUE THREAD

**Issue by max00346** [open-webui/open-webui#1320]
**Is your feature request related to a problem? Please describe.**
There is no option to set per-user API keys. It would be nice to set individual limits and track costs for the users.

**Describe the solution you'd like**
An input field in the settings, available to users, to set an API key for the default OpenAI-compatible endpoint.

**Describe alternatives you've considered**
Using one key for all users (neither comfortable nor secure).

**Additional context**
I would love to see a solution to this in the future, making this project even more awesome!

**Comment by Raymond0Hui** [comment]
+1，只有管理能填apiurl和key，用户是免费用的。可以让用户自己填key，用自己的key对话。这样相当于比nextchat多一个上传文件了

**Comment by krrishdholakia** [comment]
@max00346 wouldn't it be simpler to just allow passing a user_id to the proxy?

**Comment by max00346** [comment]
> @max00346 wouldn't it be simpler to just allow passing a user_id to the proxy? 

yes thanks, that would be even better!

**Comment by krrishdholakia** [comment]
cc: @tjbck can you pass the user id to the openai endpoint? 

This should help here + in abuse detection.

**Comment by tjbck** [comment]
Implemented as manifold pipe function in dev, more examples will be added to our community platform.

![image](https://github.com/open-webui/open-webui/assets/25473318/9d0a5d56-2c28-4d7f-8849-669887ab46b0)
![image](https://github.com/open-webui/open-webui/assets/25473318/944d1fc1-7a79-41c4-8c81-29917c77890e)
![image](https://github.com/open-webui/open-webui/assets/25473318/72b24e87-d3bb-40c5-827a-ba98384500df)

[function-openai_manifold-export-1719090778471.json](https://github.com/user-attachments/files/15941957/function-openai_manifold-export-1719090778471.json)

**Comment by justinh-rahb** [comment]
> cc: @tjbck can you pass the user id to the openai endpoint?
> 
> This should help here + in abuse detection.

There's an example of a moderation filter already in the Discord, we'll be sure to get that on the community site when integration is available. I'll be whipping all the present authors into getting uploaded 💪
