### ISSUE TITLE
Mixtral Api Support

### ISSUE THREAD

**Issue by thekeithbinder** [open-webui/open-webui#1322]
**Is your feature request related to a problem? Please describe.**
i dont have gpu now and openai dont have all what i need

**Describe the solution you'd like**
ilove if if you can implement the use of mixtral api to your project

they recently release the api with free 25 usd
https://console.mistral.ai/api-keys/

**Comment by justinh-rahb** [comment]
Already possible: you can set the API Base URL for "OpenAI" connections to `https://api.mistral.ai/v1` and use your Mistral API key to get access to their models:

![Screenshot 2024-03-27 at 9 42 35 AM](https://github.com/open-webui/open-webui/assets/52832301/c6d4d828-e5b7-4077-a73a-1cf85b3ce7f2)
