### ISSUE TITLE
bug: OLLAMA_BASE_URL env var not registering

### ISSUE THREAD

**Issue by G4Zz0L1** [open-webui/open-webui#1326]
> @G4Zz0L1 The settings will not persist if you restart the container so you'd have to set OLLAMA_BASE_URL env var manually. Could you share your installation command with us? Persistent config is in the works with https://github.com/open-webui/open-webui/issues/1022, so stay tuned for that.

It was in another issue (https://github.com/open-webui/open-webui/issues/1295), but it was closed due to an arrogant guy.

@tjbck 
I installed ollama as a native service on arch linux (managed via systemd, with ollama serve, on the address `http://127.0.0.1:11434`).
Then I put open-webui as a docker container, via docker compose, in its own stack, just to test and see if I could get everything started.
I used, as rightly said by you, `http://host.docker.internal:11434` via the `extra_hosts` in the container, but it doesn't seem to work, ollama is not seen by open-webui.
I then tried the only other alternative, i.e. `network_mode: host`, replacing the `OLLAMA_BASE_URL` env in the container with `http://localhost:11434` (or `http://127.0.0.1:11434` with the same results), but it still doesn't work.
The first load after logging in fails with a blank page, giving the error below in the logs, then the page loads and I can change the URL from the frontend.
In seems to ignore the `OLLAMA_BASE_URL` variable by the tests I am doing.
I'm definitely doing something wrong on my side, if it works for everyone else, but I honestly don't know what.
Below you will find the docker-compose that I am currently using to try to get it started, and other info.
I had to change the port, it conflicted with other services I use.

## Environment

- **Operating System:** Arch Linux
- **Browser (if applicable):** Chrome 123.0.6312.86

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
![image](https://github.com/open-webui/open-webui/assets/13220636/f12d2e32-996d-458b-a34a-b5def5b3fd68)

**Docker Container Logs:**
```
open-webui  | INFO:apps.web.models.auths:authenticate_user: me@mail.com
open-webui  | INFO:     127.0.0.1:59870 - "POST /api/v1/auths/signin HTTP/1.1" 200 OK
open-webui  | INFO:apps.ollama.main:get_all_models()
open-webui  | ERROR:apps.ollama.main:Connection error: Cannot connect to host ollama-service.open-webui.svc.cluster.local:11434 ssl:default [Temporary failure in name resolution]
open-webui  | INFO:apps.ollama.main:get_all_models()
open-webui  | ERROR:apps.ollama.main:Connection error: Cannot connect to host ollama-service.open-webui.svc.cluster.local:11434 ssl:default [Temporary failure in name resolution]
open-webui  | INFO:     127.0.0.1:59870 - "GET /ollama/api/tags HTTP/1.1" 200 OK
open-webui  | INFO:apps.openai.main:get_all_models()
open-webui  | INFO:apps.openai.main:get_all_models()
open-webui  | INFO:     127.0.0.1:59870 - "GET /openai/api/models HTTP/1.1" 200 OK
open-webui  | INFO:     127.0.0.1:59870 - "GET /litellm/api/v1/models HTTP/1.1" 200 OK
open-webui  | INFO:     127.0.0.1:59870 - "GET /api/v1/modelfiles/ HTTP/1.1" 200 OK
open-webui  | INFO:     127.0.0.1:59870 - "GET /api/v1/prompts/ HTTP/1.1" 200 OK
open-webui  | INFO:     127.0.0.1:59870 - "GET /api/v1/documents/ HTTP/1.1" 200 OK
open-webui  | INFO:     127.0.0.1:59870 - "GET /api/v1/chats/tags/all HTTP/1.1" 200 OK
open-webui  | INFO:apps.ollama.main:get_all_models()
open-webui  | ERROR:apps.ollama.main:Connection error: Cannot connect to host ollama-service.open-webui.svc.cluster.local:11434 ssl:default [Temporary failure in name resolution]
open-webui  | ERROR:apps.ollama.main:Connection error: Cannot connect to host ollama-service.open-webui.svc.cluster.local:11434 ssl:default [Temporary failure in name resolution]
open-webui  | INFO:     127.0.0.1:59870 - "GET /ollama/api/version HTTP/1.1" 500 Internal Server Error
```

## Installation Method
```yaml
open-webui:
   image: ghcr.io/open-webui/open-webui:dev
   container_name: open-webui
   restart: unless-stopped
   network_mode: host
   #ports:
   #   - 3080:8080
   #extra_hosts:
   #   - host.docker.internal:host-gateway
   volumes:
      - ./open-webui:/app/backend/data
   environment:
      - PORT=3080
      - OLLAMA_BASE_URL=http://localhost:11434
```

```
# /usr/lib/systemd/system/ollama.service
[Unit]
Description=Ollama Service
Wants=network-online.target
After=network.target network-online.target

[Service]
ExecStart=/usr/bin/ollama serve
WorkingDirectory=/var/lib/ollama
Environment="HOME=/var/lib/ollama" "GIN_MODE=release"
User=ollama
Group=ollama
Restart=on-failure
RestartSec=3
Type=simple
PrivateTmp=yes
ProtectSystem=full
ProtectHome=yes

[Install]
WantedBy=multi-user.target

# /etc/systemd/system/ollama.service.d/override.conf
[Service]
Environment="OLLAMA_HOST=0.0.0.0:11434"
```

**Comment by dtsoden** [comment]
@G4Zz0L1 it's the arrogant guy from the other ticket. Odd that another exact same issue came up in another ticket (perhaps rethink before calling visitors names and like in my ticket telling me how to behave and my tone... - like who's actually arrogant??? [rhetorical]). 

I found this one because I was searching to close my ticket, but I see you not only talk smack about your users you kindly closed mine. Also, your profile pic with the FU middle finger says it all and matches the personality to a "T". Cheers!

I love the app but given the treatment here on this project... I am just going to find another project to use - that should make us both happy. Unbelievable rudeness here!!

**Comment by G4Zz0L1** [comment]
I'm not a developer of the project, I'm just a user and I haven't closed your issue.
Furthermore, our two problems were only connected for the saving part, which they are already working on.
I know for a fact that in open source most developers are in it in their free time, so unlike you, instead of going on a rant about the rebranding of the project, I'm just politely seeking information on an issue.
So, yeah, your posts in the other issue seem a little arrogant, that's all.
PS: the profile photo is the only profile photo that I normally use on social media, as I have no other photos, it doesn't indicate much of my personality.

**Comment by tjbck** [comment]
@G4Zz0L1 Could you tell us more about the installation method you used? Trying to understand why the backend is trying to connect to `ollama-service.open-webui.svc.cluster.local:11434` instead of the specified `http://localhost:11434` here 😅

**Comment by G4Zz0L1** [comment]
I'm trying to use docker-compose to launch open-webui, with the snippet in the first post of this issue.
For ollama, I used the already packaged ollama found in the Arch Linux repo (https://archlinux.org/packages/extra/x86_64/ollama/).
I'm not sure I understand what else do you need, sorry.
The only moving parts here are those two, to my knowledge.
That url baffles me just as much as you, honestly.
That's the reason for the issue   xD

**Comment by tjbck** [comment]
What command did you use to run the compose file? Seem like you might be using [our k8s file](https://github.com/open-webui/open-webui/blob/ac294a74e7bc5f080970c049c656506e36f9407b/kubernetes/manifest/base/webui-deployment.yaml#L30) for some reason. Here's a docker compose doc that might help us: https://docs.openwebui.com/getting-started/#one-line-command-to-install-ollama-and-open-webui-together

**Comment by G4Zz0L1** [comment]
Oh, I didn't get it before, sorry.
Nothing fancy, just the usual `docker compose up -d --build`.
I don't need gpu support for docker, ollama it's installed locally.

**Comment by justinh-rahb** [comment]
> Oh, I didn't get it before, sorry. Nothing fancy, just the usual `docker compose up -d --build`. I don't need gpu support for docker, ollama it's installed locally.

@G4Zz0L1 can you see if reinstalling Ollama will help? We've had some recent issues that went away after a reinstall of it.

**Comment by tjbck** [comment]
@justinh-rahb I highly suspect like our webui is causing the issue here, not our code but rather the infra side of things.

@G4Zz0L1 have you tried just using the docker run command?

**Comment by slash-proc** [comment]
This seems to be an issue with the [k8s fixes](https://github.com/open-webui/open-webui/blame/dev/backend/config.py#L255) recently pulled into dev.

```if ENV == "prod":
    if OLLAMA_BASE_URL == "/ollama" and KUBERNETES_SERVICE_HOST == "":
        OLLAMA_BASE_URL = "http://host.docker.internal:11434"
    else:
        OLLAMA_BASE_URL = "http://ollama-service.open-webui.svc.cluster.local:11434"
```

I think it's better to either ignore Kubernetes in config.py and leave things to the helm chart / manifests to pass OLLAMA_BASE_URL or to change the code above to:
```if ENV == "prod":
    if OLLAMA_BASE_URL == "/ollama" and KUBERNETES_SERVICE_HOST == "":
        OLLAMA_BASE_URL = "http://host.docker.internal:11434"
    elif KUBERNETES_SERVICE_HOST != "":
        OLLAMA_BASE_URL = "http://ollama-service.open-webui.svc.cluster.local:11434"
    else:
        OLLAMA_BASE_URL = "http://localhost:11434" # or whatever is most appropriate here
```

**Comment by tjbck** [comment]
@jannikstdl could you take a look? thanks in advance!

**Comment by tjbck** [comment]
@G4Zz0L1 Just added a quick fix, let me know if that fixes the issue!

**Comment by G4Zz0L1** [comment]
It works perfectly now, thanks a lot!
Now it only has to save settings, I'll watch the other issue for that, thanks.

**Comment by jannikstdl** [comment]
> This seems to be an issue with the [k8s fixes](https://github.com/open-webui/open-webui/blame/dev/backend/config.py#L255) recently pulled into dev.
> 
> 
> 
> ```if ENV == "prod":
> 
>     if OLLAMA_BASE_URL == "/ollama" and KUBERNETES_SERVICE_HOST == "":
> 
>         OLLAMA_BASE_URL = "http://host.docker.internal:11434"
> 
>     else:
> 
>         OLLAMA_BASE_URL = "http://ollama-service.open-webui.svc.cluster.local:11434"
> 
> ```
> 
> 
> 
> I think it's better to either ignore Kubernetes in config.py and leave things to the helm chart / manifests to pass OLLAMA_BASE_URL


The K8s OLLAMA_BASE_URL is also added in the manifests. 
For me this wouldn't work, so I added the check lines in config.py

It may have picked the else not because of the KUBERNETES_SERVICE_HOST being an empty string (which means there is no ENV) rather than the /ollama beeing false. 
Because it would be weird if the KUBERNETES_SERVICE_HOST ENV exists in this Linux with docker compose. 

or to change the code above to:
> 
> ```if ENV == "prod":
> 
>     if OLLAMA_BASE_URL == "/ollama" and KUBERNETES_SERVICE_HOST == "":
> 
>         OLLAMA_BASE_URL = "http://host.docker.internal:11434"
> 
>     elif KUBERNETES_SERVICE_HOST != "":
> 
>         OLLAMA_BASE_URL = "http://ollama-service.open-webui.svc.cluster.local:11434"
> 
>     else:
> 
>         OLLAMA_BASE_URL = "http://localhost:11434" # or whatever is most appropriate here
> 
> ```

This seems like a good approach for me. 

I will have a look at this.

**Comment by adjiap** [comment]
I have the same problem still in ` v0.6.26`. 

Expectation:
When I explicitly put `K8S_FLAG=False`, I would get to use the given OLLAMA_BASE_URL (or OLLAMA_BASE_URLS)  

Reality:
When I explicitly put `K8S_FLAG=False`, and also OLLAMA_BASE_URL, I still use `http://ollama-service.open-webui.svc.cluster.local:11434`.

Only when I remove the K8S_FLAG in the environment variables, then we're using the OLLAMA_BASE_URL
