### ISSUE TITLE
Whitelisting LiteLLM Models

### ISSUE THREAD

**Issue by rfernandez760** [open-webui/open-webui#1330]
# Bug Report

## Description

**Bug Summary:**
Whitelist functionality to only show specific models are not applying to LiteLLM models. It's only currently working for local models, and models using the OpenAI API. The only way to make whitelisting work with LiteLLM models is to add it to the environment variables when creating the docker container.

**Steps to Reproduce:**
Configure Whitelist of models in the UI in the Admin Panel > Admin Settings > Users > Model Whitelisting

**Expected Behavior:**
Models that are not whitelisted should not be visible to the "users" group.

**Actual Behavior:**
LiteLLM models are displaying for users in the "user" group even though they are not added into the whitelist.

## Environment

- **Operating System:** [e.g., Windows 10, macOS Big Sur, Ubuntu 20.04]
- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]

Ubuntu 22.04.4 LTS (GNU/Linux 5.15.0-101-generic x86_64)

Browser: Edge Version 123.0.2420.53 (Official build) (64-bit) and Chrome Version 123.0.6312.59 (Official Build) (64-bit)

## Reproduction Details

**Confirmation:**

- [ X] I have read and followed all the instructions provided in the README.md.
- [X] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]
![image](https://github.com/open-webui/open-webui/assets/76540757/099535a1-3bfc-4106-8468-c1eb7ef517e3)

## Installation Method
Installed Ollama via the command:
curl -fsSL https://ollama.com/install.sh | sh

Installed Open-WebUI using docker command:
docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main

## Additional Information

The workaround is to add environment variables into the docker command.
-e MODEL_FILTER_ENABLED=True \
-e MODEL_FILTER_LIST="gemma:latest" \

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by justinh-rahb** [comment]
Thanks for your help in diagnosing this one on Discord @rfernandez760 🙏

**Comment by tjbck** [comment]
Should be fixed on our dev branch, let me know if the issue persists!
