### ISSUE TITLE
feat: ComfyUI Custom Workflow Support

### ISSUE THREAD

**Issue by Michelklingler** [open-webui/open-webui#1336]
**Is your feature request related to a problem? Please describe.**

The feature will enhance the text to image capability of OpenWebUI.
Especially for company using Multimedia and Image/video content creation pipeline.
By enabling this feature the user could use multiple workflow not only to generate image from text, but would open multiple other image generation custom features. Compatible ComfyUI Workflow could be shared within the OpenWebUI Prompt/ModelFile webpage.

**Describe the solution you'd like**

The option to load an Exported workflow into the setting windows of OpenWebUI.
With a few basic setting exposed: Dimension, steps, models, etc... (like it is already the case with the current integration)

**Describe alternatives you've considered**

Manually update the comfyui.py file in the repo for a hardcoded alternative

**Comment by Michelklingler** [comment]
I did try to manually update the comfyui.py file with a basic SDXL + refiner workflow that works well, but it does not seems to work. I get the following error when I click the generate image button:

![Screenshot 2024-03-28 at 8 57 33 AM](https://github.com/open-webui/open-webui/assets/63208430/00ca84a0-02ae-4949-84c2-f231dde08ebf)

[comfyui_sdxl.py.zip](https://github.com/open-webui/open-webui/files/14790145/comfyui_sdxl.py.zip)

**Comment by Michelklingler** [comment]
FYI - I manage to make a custom ComfyUI work flow work!
I was missing a "," and also as ComfyUI nodes ID are generated randomly depending at which moment you create the node, it needs to be updated accordingly in the code to point the variable for the prompt, model, steps and dimension.

Below is the updated comfyui.py file that can be replaced in /app/backend/apps/images/utils/comfyui.py.

If you have enough ressource t
[comfyui.py.zip](https://github.com/open-webui/open-webui/files/14794713/comfyui.py.zip)
o load SDXL + the REFINER on a machine it provide pretty high quality image as output.
Just make sure you download the 2 models below in your ComfyUI checkpoint server before infering.
Setup the settings like the screenshot attached for best results.

![Screenshot 2024-03-28 at 1 05 29 PM](https://github.com/open-webui/open-webui/assets/63208430/c6a7319f-0574-458b-be3b-b19bcd270b19)
![Screenshot 2024-03-28 at 1 07 42 PM](https://github.com/open-webui/open-webui/assets/63208430/0fbbdced-4183-44f6-bee6-5388daa4ce6b)

**Comment by Michael-YongWang** [comment]
1.

**Comment by cmalpass** [comment]
@Michelklingler I second this request. 

I have different workflows for different kinds of output types and subjects. Would be great to switch between them as needed so that I can get high quality results for each rather than subpar one-size-fits-all as it is right now. Love having comfyui as a part of the application, so this would just make it that much better.

**Comment by schuster-rainer** [comment]
it doesn't work this way. The change to support this is more complex. Each workflow is unique. So either the open-webui team sets up some standards what need to be in a workflow or we put a mapping mechanism in place that let's a user use any workflow he likes put it in some folder in open-webui and a configuration file "xpath" or some other mechanism to tell open-webui where to put the negative prompt ... and so on. So many options on how to advance this. If you even be possible to give the LLM tools/functions it can call, to customize the negative prompt, model, seed and so on, from within the chat

**Comment by alex13by** [comment]
It may be possible to support some special workflows in the form of lists, such as SDXL, LCM, cascade, etc.

**Comment by ER-EPR** [comment]
maybe just a COMFYUI_DEFAULT_PROMPT replacement UI should be enough

**Comment by silentoplayz** [comment]
https://openwebui.com/t/heffrecito/comfyui_manifold
