### ISSUE TITLE
Ollama model rename feature

### ISSUE THREAD

**Issue by nijisakai** [open-webui/open-webui#1354]
is it possible to rename the ollama models so i can give users a more friendly model description name and they can choose models more clear.

**Comment by tjbck** [comment]
Closing this in favour of #1041, let's continue our discussion there!

**Comment by ckizer** [comment]
I cannot figure out after several hours how to simply rename the model I'm using:
mannix/llama3.1-8b-abliterated:latest

![CleanShot 2024-09-12 at 14 38 58@2x](https://github.com/user-attachments/assets/980f6420-9fcd-470b-9a08-e02be2ea1fff)

Can't figure it out, UI if it supports this is very confusing :-)

**Comment by branrickman** [comment]
> is it possible to rename the ollama models so i can give users a more friendly model description name and they can choose models more clear.

This can be accomplished by simply renaming the model directory name in the library.

For example, if I wanted to rename llama3.2 in the following example:

![Image](https://github.com/user-attachments/assets/629e1d4e-5472-4ff1-8668-f3f31f347783)

I could simply rename the folder to "L3.2":

![Image](https://github.com/user-attachments/assets/6cdfab78-9a73-414a-b3bc-995f90a9ed6f)

And then listing the models in the command line (without even restarting Ollama) will show the model name is changed:

![Image](https://github.com/user-attachments/assets/0fd71d03-73bf-45fa-841b-f105bd5e2d25)

I have not tested how this change is taken in by Open-webui.
