### ISSUE TITLE
bug: scroll overflow on conversations with LaTeX rendering

### ISSUE THREAD

**Issue by dannyl1u** [open-webui/open-webui#1359]
# Bug Report

## Description

**Bug Summary:**
In conversations where there is math output rendered with LaTeX, the page allows the user to scroll off the page at the bottom. 

**Steps to Reproduce:**
Get the chatbot to return some output that includes rendered math equations, and scroll down the page.

**Expected Behavior:**
Prevent user from scroll overflow.

**Actual Behavior:**
Page keeps scrolling down showing a blank white area.

## Environment

- **Operating System:**: macOS Big Sur
- **Browser (if applicable):** issue occurs on Chrome, Safari

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
n/a

**Docker Container Logs:**
n/a

**Screenshots (if applicable):**

https://github.com/open-webui/open-webui/assets/45186464/ea258a3d-f5d6-4ad8-b264-684e2d6bd920

## Installation Method
Manual installation

## Additional Information
Only occurs in conversations including rendered output.

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by dannyl1u** [comment]
this is probably related to the katex library

**Comment by tjbck** [comment]
Should be fixed on our dev branch now, let me know if the issue persists!

**Comment by dannyl1u** [comment]
> Should be fixed on our dev branch now, let me know if the issue persists!

@tjbck lgtm! thanks for the fix! 👍
