### ISSUE TITLE
feat: modularity

### ISSUE THREAD

**Issue by lainedfles** [open-webui/open-webui#1360]
**Describe the solution you'd like**
Establish modular design, requirement, process, security, best practice, etc. With all of the innovation surrounding LLM technology, software like [code execution](https://github.com/open-webui/open-webui/issues/1321) & [extended RAG](https://github.com/open-webui/pipelines/issues/15) can be extremely beneficial but not without capacity and security considerations. Candidates like [open-interpreter](https://github.com/OpenInterpreter/open-interpreter) and [self-operating-computer](https://github.com/OthersideAI/self-operating-computer) are exciting!

My hope is that we can keep the core of Open-WebUI secure, lightweight, and performant. One solution may be modularity. I'd love to see capability like _code execution_ available as an opt-in module with logical and secure separation. If we can establish guidelines for **Open-WebUI Modules**, this can simplify the development of future modules.

**Comment by tjbck** [comment]
Related: https://github.com/open-webui/pipelines
