### ISSUE TITLE
feat: backend timeout error handling

### ISSUE THREAD

**Issue by shaul75** [open-webui/open-webui#1376]
## Description
Whenever the API request to the backend takes a while to return any data (usually because the model wasn't loaded yet), and there's a "504 Gateway Time-out" error, the client does not handle it and the user would see the loading skeleton indefinitely, with no indication of a problem unless you open the dev tools.

I suggest adding error handling that'll show a failure message and a retry button to make it clear the request to the backend failed.

**Comment by tjbck** [comment]
Steps to reproduce would be extremely helpful here!

**Comment by tjbck** [comment]
Closing in favour of #1611
