### ISSUE TITLE
[SOLVED] Ollama Open web Ui in WSL2 Bug after Reinstall - BASE URL & admin User

### ISSUE THREAD

**Issue by Gara06** [open-webui/open-webui#1377]
# Bug Report

## Description
I installed in a first time Ollama and OpenWebUi; It was working , but only CPU. So i uninstall it to make a clean install with nvidia gpu.

**Bug Summary:**
install on Win11 - Docker desktop - WSL2- Docker Compose : 
version: '3.8'

services:
  ollama:
    deploy:
      resources:
        reservations:
          devices:
            - driver: nvidia
              capabilities: [gpu]
    volumes:
      - ollama:/root/.ollama
    container_name: ollama
    restart: unless-stopped
    image: ollama/ollama:latest

  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    volumes:
      - open-webui:/app/backend/data
    depends_on:
      - ollama
    ports:
      - ${OPEN_WEBUI_PORT-3000}:8080
    environment:
      - 'OLLAMA_BASE_URL=http://ollama:11434'
      - 'WEBUI_SECRET_KEY='
    extra_hosts:
      - host.docker.internal:host-gateway
    restart: unless-stopped

volumes:
  ollama: {}
  open-webui: {}

**Steps to Reproduce:**
I uninstall with revo uninstaller to delete every thing from ollama, docker desktop and openWebUi, But all time , more than 20 times , i re-install all. i have all time my first old admin User working. Why ? why cannot delete it and create a new admin user ? this is the first BUG. But tho most important it's i cannot connect OpenWebUi to Ollama with Base URL. BASE URL doesnt save any change , and doesnt valide to work any change. If i use http://localhost:3000 i get acces to OpenWebUi, If i go to http://localhost:11434/  "Ollama is running" but never exept the first time i connected OpenWebUi to ollama.
i tryed to use docker run instead of docker compose after , but same result. Admin User stay the same even i delete and erase alle things. And never connect to ollama.

**Expected Behavior:**
There is a data base i can delete to erase all from old install and restart reely clean and NEW?

**Actual Behavior:**
[Describe what actually happened.]

## Environment

- Win 11 up to date. Nvidia 4060ti, 64 g Ram, Docker desktop, 
- Browser : same thing with Brave, Firefox, Edge, Chrome

**Confirmation:**

- [ ] I have read during a week all result about this probleme but , i never found something serious. May be i dont speak and read to good english, but french doesnt on the web. 
Thank you

**Comment by justinh-rahb** [comment]
Not a bug, misunderstanding of how Docker works. Delete the persistent volume that WebUI's data is stored in:
```bash
docker rm -f open-webui
```
