### ISSUE TITLE
Bug: Incorrect Rendering of Dollar Amounts in Output

### ISSUE THREAD

**Issue by tusing** [open-webui/open-webui#1387]
# Bug Report

## Description

**Bug Summary:**
The AI-generated output contains dollar amounts, but they are being incorrectly rendered with LaTeX-style formatting (e.g., `$740 for $5 million` is rendered as *740for*5 million in LaTeX font). This makes the output difficult to read and understand.

**Steps to Reproduce:**
1. Provide the AI with input text containing dollar amounts and insurance coverage details, as shown in the example.
2. Generate the AI output based on the provided input.
3. Observe the rendered output image.

**Expected Behavior:**
The dollar amounts in the AI-generated output should be correctly rendered as regular text, without any LaTeX-style formatting. For example, "$740 for $5 million coverage" should appear as is, without any distortion.

**Actual Behavior:**
The dollar amounts in the AI-generated output are being rendered with LaTeX-style formatting, such as "*740for*5 million coverage". 

## Environment

- **Operating System:** macOS, iOS
- **Browser (if applicable):** Safari

## Logs and Screenshots

**Screenshots (if applicable):**

<img width="717" alt="Screenshot 2024-04-01 at 5 35 51 PM" src="https://github.com/open-webui/open-webui/assets/1077203/d850059b-7698-4da9-b6ca-7df8964ccbee">

## Additional Information

- The issue seems to be related to the rendering of dollar amounts specifically, as other parts of the output appear to be rendered correctly.
- This bug may be caused by a conflict with LaTeX-style formatting or an issue with the rendering engine used in the project.

**Comment by tusing** [comment]
@tjbck it looks like a fix was introduced in #130 but then regressed in  #835 ([line]).(https://github.com/open-webui/open-webui/blame/5558514ff19c088fd0c8c87205d7a89a0d115a1c/src/lib/components/chat/Messages/ResponseMessage.svelte#L131)].

**Comment by justinh-rahb** [comment]
LaTeX has been a thorn in our side for a bit.. 😔

**Comment by tjbck** [comment]
Should be fixed on our dev branch now, let us know if the issue persists!

**Comment by tusing** [comment]
Closing this as fixed due to 2c03021, will re-open if needed!
