### ISSUE TITLE
feat: Implement Multi-System Prompt Selection

### ISSUE THREAD

**Issue by petunder** [open-webui/open-webui#1391]
**Is your feature request related to a problem? Please describe:**
Yes, the current limitation in Open WEBUI restricts users to a single, predefined system prompt. This becomes quite problematic when working across multiple projects or with diverse clients, each with unique requirements. The inability to quickly switch between different system prompts without manual adjustments significantly hampers productivity and complicates what could otherwise be a streamlined, efficient process.

**Describe the solution you'd like:**
I propose a new feature for the Open WEBUI that facilitates the creation, management, and selection of multiple system prompts directly within the chat interface. Ideally, this could be integrated as a user-friendly dropdown menu or a toggle system, allowing users to effortlessly switch between different saved prompts based on the task at hand. This feature would significantly enhance usability and flexibility, ensuring users can adapt to different demands rapidly.

**Describe alternatives you've considered:**
One alternative considered was implementing a "favorites" system that lets users star or mark certain configurations for quicker access. However, while this might slightly reduce the time spent switching between configurations, it falls short of providing the immediate, seamless transition that a dedicated selection feature would offer.

Another consideration was running separate application instances for each unique system prompt configuration. Yet, this approach isn't practical, as it introduces unnecessary complexity into the workflow, increases resource consumption, and detracts from the overall user experience by forcing users to juggle multiple application windows or tabs.

**Additional context:**
The ability to switch between system prompts on the fly can cater to a wide array of scenarios, including but not limited to, adapting to different clients' needs, testing various prompt efficiencies, or simply personalizing the chat experience. 

It significantly enhance Open WEBUI's appeal and functionality, making it a more versatile tool.

**Comment by tjbck** [comment]
Related #619

**Comment by petunder** [comment]
> Related #619
The proposed solutions for unique system prompts per chat/model align with my request, highlighting the need for flexibility. Adjusting settings like temperature for specific models sounds good too. However, I advocate for a more detailed mechanism allowing admins/users to manage their own system prompts (create, edit, delete) at the chat (message) level, not just system-wide. This would enhance usability, letting users tailor system behaviors more precisely to their needs.

**Comment by strikeoncmputrz** [comment]
This would be an outstanding feature!
