### ISSUE TITLE
feat: external DB support

### ISSUE THREAD

**Issue by tjbck** [open-webui/open-webui#1397]

**Comment by Lanhild** [comment]
PostgreSQL would be a good candidate IMO

**Comment by lainedfles** [comment]
> PostgreSQL would be a good candidate IMO

I agree but I think the best consideration is to support ORM, something like [SQLAlchemy ORM](https://docs.sqlalchemy.org/en/20/orm/index.html#sqlalchemy-orm). As long as we adhere to **Object Relational Mapper** compatible statements, many major databases could be supported! SQLAlchemy presently supports a variety of [dialects](https://docs.sqlalchemy.org/en/20/dialects/index.html#dialects) including [PostgreSQL](https://docs.sqlalchemy.org/en/20/dialects/postgresql.html), [MySQL and MariaDB](https://docs.sqlalchemy.org/en/20/dialects/mysql.html), [SQLite](https://docs.sqlalchemy.org/en/20/dialects/sqlite.html), [Oracle](https://docs.sqlalchemy.org/en/20/dialects/oracle.html), and [Microsoft SQL Server](https://docs.sqlalchemy.org/en/20/dialects/mssql.html).

**Comment by justinh-rahb** [comment]
@lainedfles I am in full agreement that we need a more flexible solution to data storage, but I get real nervous about ORMs, heard too many horror stories of absolutely unhinged monstrosities of queries full of JOINS being emitted by them. They can make writing the code easier, but it's usually at the cost of efficiency.

**Comment by buroa** [comment]
Postgres would be the best use case here.

**Comment by TheBongStack** [comment]
Any update on this one? Where is the data being handled to be stored in database? at /rag/utils.py ?

**Comment by sfn-git** [comment]
> Any update on this one? Where is the data being handled to be stored in database? at /rag/utils.py ?
Not sure whether you are talking about storing the information relating to connecting to the database but I do not believe this path has any relation to that.

 I am currently looking at creating relational diagram based off of the models located at backend\apps\web\models. I also believe [SQLAlchemy ORM](https://docs.sqlalchemy.org/en/20/orm/index.html#sqlalchemy-orm) is the best option to implement this from a relational database perspective. 

Would there also be considerations for something like Mongo in the future?

**Comment by Lanhild** [comment]
> Would there also be considerations for something like Mongo in the future?
@sfn-git 

IMO, MongoDB isn't appropriate for the practical use case here as Open WebUI database is well defined
