### ISSUE TITLE
feat: Create manifest.json dynamically

### ISSUE THREAD

**Issue by theasp** [open-webui/open-webui#1400]
**Is your feature request related to a problem? Please describe.**

Currently the `manifest.json` has the name `Open WebUI` hardcoded so multiple servers all wind up with the same name when I add them as applications on my phone.

**Describe the solution you'd like**

I'd like to be able to pass a new name as an env variable., for example `MANIFEST_NAME`. 

I've already pushed the relevant changes to my branch, the instructions say to open an issue before a PR though: https://github.com/theasp/open-webui/tree/add-dynamic-manifest

**Describe alternatives you've considered**

An alternative would be to mount `manifest.json` into the container maybe?

**Additional context**

None

**Comment by justinh-rahb** [comment]
If my understanding of Svelte is correct, this would only be possible as a build-time argument, and thus would not be applicable to the container images published by the project.

**Comment by theasp** [comment]
The commit in my repo makes it so that `manifest.json` is generated by the backend dynamically on request as I described, not generated with Svelte.  I'm willing to open a PR for this.

**Comment by tjbck** [comment]
If you think a lot of people would find it useful, feel free to make a PR!

**Comment by theasp** [comment]
Excellent, see #1401.
