### ISSUE TITLE
feat: add Chinese support for pdf export

### ISSUE THREAD

**Issue by igeekbb** [open-webui/open-webui#1417]
# Bug Report
v0.1.117 PDF export feature does not support "Chinese" and "images"
## Description

![CleanShot 2024-04-04 at 16 35 22@2x](https://github.com/open-webui/open-webui/assets/154116268/f8145489-4df7-485d-9f05-0fc8dc0cb2c2)
![CleanShot 2024-04-04 at 16 36 38@2x](https://github.com/open-webui/open-webui/assets/154116268/d9a38883-c1f1-40d2-8cd4-2049335dad3c)

**Comment by nullnuller** [comment]
In my case it also doesn't work for regular PDF.
![image](https://github.com/open-webui/open-webui/assets/32858321/7808edeb-4d1c-4cf1-a1bd-44036f0fa806)

**Comment by tjbck** [comment]
Closing in favour of #1441
