### ISSUE TITLE
Ability to set a maximum usage per day/month per user

### ISSUE THREAD

**Issue by Fusseldieb** [open-webui/open-webui#1430]
**Is your feature request related to a problem? Please describe.**
No, just a feature request.

**Describe the solution you'd like**
Since I share open-webui with family & friends, it would be nice if we could set a maximum token (or message) limit per day and/or month, per user, and model, so they won't use up all my credits if they're not careful, especially because I'm using the LLMs over an API and don't use them locally.

**Describe alternatives you've considered**
Right now, there's no alternative approach to limit this, not even globally.

**Additional context**
\-

**Comment by tjbck** [comment]
Closing in favour of #1067
