### ISSUE TITLE
bug: Download as PDF feature - non latin characters are not displayed properly in the PDF

### ISSUE THREAD

**Issue by pazoff** [open-webui/open-webui#1441]
# Bug Report

## Description

**Bug Summary:**
Download as PDF feature- non latin characters are not displayed properly in the PDF

**Steps to Reproduce:**
Save a pdf from conversation containing non latin characters i.e cyrilic, japan etc.

**Expected Behavior:**
pdf containing the conversation in non latin language

**Actual Behavior:**
pdf containing gibberish

## Environment

- **Operating System:** Windows 11
- **Browser (if applicable):** Chrome

## Reproduction Details

**Confirmation:**

- [*] I have read and followed all the instructions provided in the README.md.
- [*] I am on the latest version of both Open WebUI and Ollama.

## Logs and Screenshots

**Sample PDF from conversation in Japan:**
[chat-ヤギの飼育方法.pdf](https://github.com/open-webui/open-webui/files/14892285/chat-.pdf)

**Comment by tjbck** [comment]
Should be fixed in dev branch, let me know if the issue persists!
