### ISSUE TITLE
feat: Image generation api call is missing cfg scale parameter

### ISSUE THREAD

**Issue by simper** [open-webui/open-webui#1459]
**Is your feature request related to a problem? Please describe.**
Integration with automatic1111 and comfy ui is good, but the settings configuration ui is lack of the key parameter "CFG Scale" value, which impacts the image generation result significantly, with the default stable diffusion value being 7, some sdxl lighting models' generation result is barely usable.

**Describe the solution you'd like**
Add the the "CFG Scale" param in image generation configuration page and take it into API calls properly.

**Describe alternatives you've considered**
No good way to change the default value in automatic1111 stable diffusion side.

**Additional context**
Even more customization approaches in image generation UI can be considered in future roadmap, for example, real time input dialogue for this CFG scale value before clicking generation button in chat view.

**Comment by Silentoplayz** [comment]
Being able to set the sampler used as well would be really beneficial for image generation as well!

**Comment by Xerophayze** [comment]
I'm going to one up this as well. I've got this integrated and I love that I can generate images in line. But I primarily use lightning models which is great because it provides a quick render, but I have no control over the sampler or the cfg setting and so the images tend to look low res and or come out messed up. Is this something that can just be adjusted within the code itself?

**Comment by Xerophayze** [comment]
Hey one more thing, is there a way to add a switch like /imagine to engage the image generation without having to have a prompt there in the first place?

**Comment by silentoplayz** [comment]
Related #1958

**Comment by silentoplayz** [comment]
Related #1714

**Comment by silentoplayz** [comment]
Related - https://github.com/open-webui/open-webui/pull/5256
