### ISSUE TITLE
feat: Possibility to edit LiteLLM model configuration through the webUI

### ISSUE THREAD

**Issue by Michelklingler** [open-webui/open-webui#1460]
**Is your feature request related to a problem? Please describe.**
As an admin I would need to be able to easily change model name or setting of the LiteLLM backend through the interface. Everytime I need to do an adjustmnent, server address, model name, etc... I need to recreate a model from scratch.

**Describe the solution you'd like**
The possibility to pull and edit the LiteLLM model configuration via the WebUI

**Comment by justinh-rahb** [comment]
Agreed, this would remove a major friction point in using LiteLLM as it is currently.

**Comment by tjbck** [comment]
Bundled LiteLLM support will be deprecated for our future releases, I'd recommend you start migrating your LiteLLM config.yaml to a self-hosted LiteLLM instance. You'd still be able to add them to our webui via OpenAI Connections.
