### ISSUE TITLE
Helm chart adds extra / to end of ollama URL, which is invalid 

### ISSUE THREAD

**Issue by cprivitere** [open-webui/open-webui#1478]
# Bug Report

## Description

Bug Summary:
This is a follow up from #1422. That got us closer to fixing the issue, but it's still present because a `/` was left behind. This is just to ask that that last `/` be removed. It seems unlike most browsers, the http libraries open-webui uses doesn't like having two `/` in a row in a URL.

Fix should be a quick removal of the trailing `/` from line 10 of helpers.tpl.

Helm chart adds extra / to end of ollama URL, which is invalid. Can by fixed by removing /from line 10 of the _helpers function

Steps to Reproduce:
Install the helm chart and log in and check ollama's status in the settings. Just trim off the / and then refresh and it works.

Expected Behavior:
Should just work without having to make this fix.

Actual Behavior:
Can't connect to ollama and thus no models work, nor can they be downloaded.

## Environment

Linux (kubernetes on Ubuntu 20.04)
Microsoft Edge

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.

## Installation Method

Helm

**Comment by tjbck** [comment]
Feel free to make a PR!

**Comment by dariothornhill** [comment]
I missed the the issue linking in the PR. I believe this can be closed now.
