### ISSUE TITLE
`/api/version/updates` blocks the server in restricted network environment

### ISSUE THREAD

**Issue by rudeigerc** [open-webui/open-webui#1480]
# Bug Report

## Description

**Bug Summary:**

Visit `Settings > About` may get the whole server stucked in restricted network environment.

**Steps to Reproduce:**

1. Start `open-webui` in a restricted/offline network environment (i.e., cannot visit GitHub API).
2. Visit `Settings > About`.
3. `/api/version/updates` will be visited and the whole server stuck until timeout of `requests`.

Alternatively, you can also visit `/api/version/updates` directly.

**Expected Behavior:**

1. Raise an error when GitHub API is not reachable.
2. Provide a toggle to control whether to trigger update detection.
3. Provide a config to set the timeout of external requests.

Alternatively, use libraries supporting aysnchronous requests such as `httpx` instead when sending requests.

**Actual Behavior:**

The whole server stucks until `GET https://api.github.com/repos/open-webui/open-webui/releases/latest` timeout since the request is synchronous, and the limitaiton of Python GIL.

## Environment

- **Operating System:** Windows 10
- **Browser (if applicable):** Chrome 114.0.5735.199

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**

N/A

**Docker Container Logs:**

N/A

**Screenshots (if applicable):**

N/A

## Installation Method

Kubernetes

## Additional Information

N/A

## Note

N/A

**Comment by tjbck** [comment]
Should be fixed in dev, let me know if the issue persists!

**Comment by rudeigerc** [comment]
@tjbck Thanks for your rapid update! I'll have a look at it.
