### ISSUE TITLE
feat: Provide `extra_body` option to pass extra parameters to OpenAI API proxy

### ISSUE THREAD

**Issue by rudeigerc** [open-webui/open-webui#1484]
**Is your feature request related to a problem? Please describe.**

We use `open-webui` as the frontend of multiple OpenAI API capable backends (e.g. vllm/fastchat) without ollama thanks to the high extensibility of this project. However, we encountered a problem that some of out-of-scope extra parameters provided by inference backends such as [vllm](https://docs.vllm.ai/en/latest/serving/openai_compatible_server.html#extra-parameters-for-chat-api) cannot be passed due to the lack of support.

For example, OpenAI Python SDK provides an `extra_body` paramter for users to additional JSON properties to the request.

**Describe the solution you'd like**

Provide `extra_body` as a configurable option at frontend, so that it can be passed to the proxied API.

**Describe alternatives you've considered**

N/A

**Additional context**

N/A

**Comment by esceptico** [comment]
Second that!
Are there any updates on this?

**Comment by tjbck** [comment]
This is currently supported using Functions, Here's an example of OpenAI Pipe Function: https://openwebui.com/f/hub/openai_manifold

With slight modification to this Function, you should be able to achieve what you've outlined here.
