### ISSUE TITLE
feat: detailed model info

### ISSUE THREAD

**Issue by sammcj** [open-webui/open-webui#1486]
# Bug Report

## Description

**Bug Summary:**

The UI doesn't show which server is providing a given model.

For example, say you have:

1. An OpenAI backend
2. An OpenAI compatible backend (e.g. Groq, Openrouter etc...)
3. A sever running an OpenAI compatible API
4. A local server running an OpenAI compatible API
5. One more more Ollama servers

And you're selecting which model to use - you have no idea which host you're going to be performing the inference on.

For example, in the following screenshot these models could be provided by OpenAI, OpenRouter, Ollama or some other proxy - and if there's multiple accounts/keys for a service - which one is in use?

<img width="709" alt="image" src="https://github.com/open-webui/open-webui/assets/862951/6c6baae0-414a-4315-8233-635060ec7102">

<img width="542" alt="SCR-20240410-oncj" src="https://github.com/open-webui/open-webui/assets/862951/e94bb9e2-3454-47cc-9f37-2045ff976d70">

**Steps to Reproduce:**

Add multiple providers with the same or similar model names and try to select a model to use.

Another nice option might be to give servers a 'name' attribute and show that.

**Expected Behaviour:**

In the models drop down, I'd expect next to the model name to have the server shown.

For example:

![modellist](https://github.com/open-webui/open-webui/assets/862951/8577ecee-39fd-468b-9e70-277a94e2f0c2)

![servers](https://github.com/open-webui/open-webui/assets/862951/8195e4c7-fa48-4d20-aea4-e376a4486115)

**Actual Behaviour:**

No model server is shown.

## Environment

- **Operating System:** Linux/Docker/NA
- **Browser (if applicable):** Firefox 124/NA

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Screenshots (if applicable):**

<img width="874" alt="SCR-20240410-omnh" src="https://github.com/open-webui/open-webui/assets/862951/1dd0a0ab-47a1-4c51-b955-7620bc741b8d">
<img width="692" alt="SCR-20240410-omlv" src="https://github.com/open-webui/open-webui/assets/862951/f3d0de12-c2f3-4d7d-9b81-195b313b86b4">

## Installation Method

n/a

## Additional Information

n/a

## Note

n/a

**Comment by justinh-rahb** [comment]
Ya, tbh I'd kinda like if the "Assistant" profile picture in chats were instead the logo we set for a given model (defaults can be inferred by URLs in many cases) too, along with other things that have been requested by others such as being able to edit names, set rate limits (per user), and other more granular controls for model and API access.

**Comment by sammcj** [comment]
Using the Assistant profile picture would tie in nicely if Assistants end up supporting multiple models/servers as well ;)

**Comment by abqareno** [comment]
i noticed also that [system prompt] is not based on which model in use, instead of is just one per chat. so we can't switch models in between.

**Comment by sammcj** [comment]
@abqareno yeah I noticed that as well, I think that's worth logging a separate bug / feature request for though if you could?

**Comment by tjbck** [comment]
@abqareno blocker: https://github.com/open-webui/open-webui/issues/665

**Comment by tjbck** [comment]
Closing in favour of #1655
