### ISSUE TITLE
feat: powerpoint generation

### ISSUE THREAD

**Issue by changchiyou** [open-webui/open-webui#1487]
**Is your feature request related to a problem? Please describe.**
Generating powerpoint by input documents/needs/topic is not support currently.(brand new feature)

**Describe the solution you'd like**

|[Example from Using Image Generation](https://docs.openwebui.com/tutorial/images#using-image-generation)|My Idea|
|-|-|
|<img src="https://github.com/open-webui/open-webui/assets/46549482/12afc67d-4b76-4c90-bbb5-0dbf75e91a72" alt="drawing" width="400"/>|1. `First ask a model to give you a prompt for your powerpoint generation`<br><br>2. (create a new button for powerpoint generation)|

**Describe alternatives you've considered**
None.

**Additional context**
1. https://github.com/otahina/PowerPoint-Generator-Python-Project

**Comment by justinh-rahb** [comment]
I don't even want to know what extra depends we'd need to add to make this possible, but it seems superfluous if I'm being honest. There's plenty of tools that can take a PDF and turn it into a slideshow, I would suggest using that. You'll get more control over how it looks anyhow.

**Comment by changchiyou** [comment]
> There's plenty of tools that can take a PDF and turn it into a slideshow, I would suggest using that.

Just as the current `Open WebUI`'s image generation feature doesn't simply convert conversation PDFs into images, the FR I'm anticipating here isn't solely about converting conversation PDFs into PowerPoint presentations. 🤔

**Comment by justinh-rahb** [comment]
After discussion amongst the other devs we don't plan to implement this but a PR is more than welcome.

**Comment by tan-yong-sheng** [comment]
Example to refer to for powerpoint generation using html:
https://chat.z.ai/s/79e01943-68d1-4be8-bb92-36b375e056ef

**Comment by silenceroom** [comment]
> Example to refer to for powerpoint generation using html: https://chat.z.ai/s/79e01943-68d1-4be8-bb92-36b375e056ef

with the latest development of Open_Terminal and skills, it's geting closer to this.
