### ISSUE TITLE
Shareability with piper (Speech models similar to OpenAI but free and self-hosted)

### ISSUE THREAD

**Issue by HirCoir** [open-webui/open-webui#1491]
Please add shareability with piper tts, I leave you a repo with different branches Main (Linux Aoo Flask), api-server and Flask App for windows:
https://tts.hircoir.eu.org/
https://github.com/HirCoir/HirCoir-Piper-tts-app/tree/piper-api-flask
It would work this way:

```
const audioResponse = await axios.post(¨https://piper-low.studio.hircoir.eu.org/¨, {
          text: assistantResponse,
          model: ¨kamora¨
        }, {
          headers: {
            'Content-Type': 'application/json'
          }
        });

        const audioBase64 = audioResponse.data.audio_base64;
        const audioBuffer = Buffer.from(audioBase64, 'base64');

        await sendAudio(client, message, audioBuffer);
      } catch (error) {
        console.error('Error al realizar la solicitud:', error);
        await client.sendText(message.from, 'Error.');
      }
    }

```
Piper has countless models trained by the community and are available on Huggingface: https://huggingface.co/models?sort=trending&search=piper
The quality is similar to an OpenAI model. Even the user can create his own model by following these steps:https://ssamjh.nz/create-custom-piper-tts-voice/

**Comment by tjbck** [comment]
Related: #126, Let's continue our discussion there.
