### ISSUE TITLE
Custom Chat-Character Support

### ISSUE THREAD

**Issue by TheMasterFX** [open-webui/open-webui#1513]
**Is your feature request related to a problem? Please describe.**
We already have the possibility to add custom prompts (/custom-prompt). Which is a nice feature since the user can jump to the variables via tab-key. However the system-prompt is untouched.
To vary the system-prompt we have to use the Modelfiles or the user has to change it every time. Modelfiles are also a great feature, but it has the disadvantage that it is tied to a dedicated language model.

**Describe the solution you'd like**
It would be nice to define a "Character Template" which can be used on any model and has the possibility to overwrite the systempromt (since as far as I know) has a higher weight than anything which comes after.

**Describe alternatives you've considered**
Maybe a Solution like [text-generation-webui](https://github.com/oobabooga/text-generation-webui/wiki/03-%E2%80%90-Parameters-Tab#character) might be a great solution. So non-Admin-Users are able to create and share characters (not only online) but also in an offline company intranet

**Comment by tjbck** [comment]
Related #665, Let's continue our discussion there.+
