### ISSUE TITLE
feat: Global banner for information distribution accross all users

### ISSUE THREAD

**Issue by VfBfoerst** [open-webui/open-webui#1522]
Hi :}  
  
**Is your feature request related to a problem? Please describe.**
We have at the moment ~100 Users and want to inform them in a central way, e.g. if we need a downtime for patching the webui. At the moment, we inform the users via mail, but it would be nice to remind them persistently during webui usage.

**Describe the solution you'd like**
A good way in our opinion would be a banner which will be shown globally in all chats, like it is possible in gitlab, e.g.:
![image](https://github.com/open-webui/open-webui/assets/64251549/92015654-f916-46fa-aa4a-3680926f79f8)

Additionally it would be nice to change the colour of the banner, e.g.:

- red for critical changes, e.g. downtime
- green for success messages, e.g. after downtime
- blue for informational messages, e.g. new features

**Comment by tjbck** [comment]
Great suggestion! PR Welcome!

**Comment by Lanhild** [comment]
@VfBfoerst what about an API method that could allow us to redirect users to a static maintenance page?

Kind of like a maintenance mode for Open WebUI that can be toggled directly using the API.

To push it even further, we could have custom maintenance pages where a custom broadcast message is POSTed through that API method, then displaying it on the said page.

**Comment by silentoplayz** [comment]
This is related to [feat: add configurable notification banners](https://github.com/open-webui/open-webui/pull/2499) - #2499

**Comment by fwxfasp** [comment]
thanks for the heads up, @silentoplayz

**Comment by silentoplayz** [comment]
No problem!

**Comment by tjbck** [comment]
![image](https://github.com/open-webui/open-webui/assets/25473318/67951db7-145e-4a1c-959e-1863157fe42a)

Merged to our dev branch!

**Comment by tkg61** [comment]
I am not sure if this should be a new issue but could we make it so that the banner shows in chat threads after a chat is started? We have some policy items that need to be shown all the time, not just at login like a maintenance window would be.
