### ISSUE TITLE
Model Whitelists do not persist through Container restart

### ISSUE THREAD

**Issue by lewismacnow** [open-webui/open-webui#1524]
# Bug Report

## Description
Model Whitelists do not persist through Container restart

**Bug Summary:**
When the docker container is restarted, the Model Whitelist value is cleared and must be re-entered.
This is despite having storage used in the container - /app/backend/data
Everything else that would be expected to restart, does persist.

**Steps to Reproduce:**

1. Whitelist model(s)
2. docker restart {container}
3. Observe whitelist is empty

**Expected Behavior:**
Model Whitelist should persist

**Actual Behavior:**
Whitelist is lost

## Environment

- **Operating System:** Ubuntu 20.04

## Reproduction Details

**Confirmation:**

- [Y] I have read and followed all the instructions provided in the README.md.
- [Y] I am on the latest version of both Open WebUI and Ollama.
- [N] I have included the browser console logs.
- [N] I have included the Docker container logs.

## Installation Method

sudo docker run -d  -p 13000:8080 --network=host -v open-webui:/app/backend/data -e OLLAMA_BASE_URL={redacted} --name open-webui --restart always ghcr.io/open-webui/open-webui:main

**Comment by tjbck** [comment]
Duplicate #1022
