### ISSUE TITLE
feat: a mode for the UI for rapidly tweaking prompts

### ISSUE THREAD

**Issue by jeremiahsb** [open-webui/open-webui#1542]
**Is your feature request related to a problem? Please describe.**
Related: #619 & #1391
Not a problem per say, just a way to turn open webui into a tool for prompt tweaking.

**Describe the solution you'd like**
It would be great to have the ability to have a screen which the user could:
- test multiple variations of system prompts, holding other attributes constant
- test multiple models holding other attributes constant
- test multiple temperatures holding other attributes constant

Once the user hits a "test" button, it would execute the configurations and display the response and highlight differences.

**Describe alternatives you've considered**
Having something like promptfoo, but integrated directly in the open webui.
https://github.com/promptfoo/promptfoo

**Comment by justinh-rahb** [comment]
This is sorta the intention behind our "Playground" feature, though admittedly it's a first-draft that really needs some more work, including a quick settings sidebar for parameters, and saved profiles, similar to what you see in other platforms' "Playground" UIs now. Extending this even further with some of the ideas you suggest sounds like a useful feature to me as well, and one I'd fully support a PR for.

**Comment by tjbck** [comment]
This would be a great addition to our playground feature, feel free to make a PR! Once I clear out our backlogs I'll also actively start looking into this.

**Comment by tjbck** [comment]
Closing in favour of #1542, Let's continue our discussion there!
