### ISSUE TITLE
Ollama: invalid model path: ':' (colon) is not allowed in tag names

### ISSUE THREAD

**Issue by notasquid1938** [open-webui/open-webui#1545]
Is this a new rule? After updating to 0.1.118 I can no longer import this modelfile https://openwebui.com/m/jamest/dolphin-mistral:7b-v2.8:latest because of the colon in its tag name which I don't recall being an issue before.

**Comment by notasquid1938** [comment]
Removing the :latest in the tag fixed this issue so perhaps it was just a mistake on the part of the modelfile creator?

**Comment by tjbck** [comment]
Yep, bad modelfile. You'll have to edit the tag manually for it to work.
