### ISSUE TITLE
Comfy UI Image Setting not persistent in a WSL Docker deployment.

### ISSUE THREAD

**Issue by BrandXX** [open-webui/open-webui#1546]
# Bug Report
ComfyUI Image setting are not persisting through a reboot in WSL Docker install.

## Description
Open WebUI>Setting>Images
ComfyUI settings are reverting to defaults after shutting down the Distro

**Bug Summary:**
The following settings revert to default after shutting down my WSL2, Ubuntu 22.04 instance in Windows 11 23H2. Setting>Images>
Image Generation Engine: ComfyUI
Image Generation (Experimental): On
ComfyUI Base URL: http://127.0.0.1:7860
Set Default Model: absolutereality_v181.safetensor
Set Image Size: 512x512
Set Steps: 50

I have deployed Ollama, OpenWeb UI and ConmfyUI in Docker containers within a single docker server deployment in Ubuntu 22.04.  My Docker is deployed within my Ubuntu distro rather than running Docker Desktop for Windows.

**Steps to Reproduce:**
Log into Open WebUI
Configure Setting>Images>
Image Generation Engine: ComfyUI
Image Generation (Experimental): On
ComfyUI Base URL: http://127.0.0.1:7860
Set Default Model: absolutereality_v181.safetensor
Set Image Size: 512x512
Set Steps: 50
Save
Logout of Open WebUI
Exit Ubuntu
WSL --shutdown #Shutdown my Ubuntu Distro.
WSL -d OpenWebUI #Launch my WSL Distro with Ollama, ConfyUI and Open WebUI
Log into Open WebUI
All Images setting have reverted back to defaults.

**Expected Behavior:**
I expected the setting to persist through a reboot of the server.

**Actual Behavior:**
After rebooting my WSL2 Distro, the image settings revert to defaults.

## Environment
Windows 11 Pro 23H2
Ubuntu 22.04
Docker version 26.0.1
Docker Compose version v2.26.1
WSL version: 2.1.5.0
Kernel version: 5.15.146.1-2
WSLg version: 1.0.60
MSRDC version: 1.2.5105
Direct3D version: 1.611.1-81528511
DXCore version: 10.0.25131.1002-220531-1700.rs-onecore-base2-hyp
Windows version: 10.0.22631.3447

- **Operating System:**
- Windows 11 Pro, WSL2 and, Ubuntu 20.04

- **Browser (if applicable):**
- Edge

## Reproduction Details
Reproduction listed above.

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [X] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots
N/A

**Browser Console Logs:**
N/A

**Docker Container Logs:**
N/A

**Screenshots (if applicable):**
N/A

## Installation Method
Windows 11 Pro 23H2 with WSL2 and Ubuntu 22.04. Open WebUI is installed using the Readme method for Docker. I'm using Docker server within a WSL2 Distro of Ubuntu 22.04 rather than Docker Desktop for Windows.

## Additional Information
I have added the ComfyUI Base URL of http://127.0.0.1:7860 to the Env Var so it does persist through a reboot.
All Docker containers are fully updated.
I have the same issue with my Embedding model reverting to defaults after a reboot.

## Note
I have a feeling there is a simple solution but I'm not aware of it.

**Comment by tjbck** [comment]
Duplicate #1022
