### ISSUE TITLE
feat: Make the chat tag action more visible in the UI

### ISSUE THREAD

**Issue by autopticio** [open-webui/open-webui#1557]
**Is your feature request related to a problem? Please describe.**
I wasn't aware it was possible to tag chats until I read some of the other feature conversations. I think this may be because the tag action is in the upper right hamburger menu of the selected chat. I think it is a super useful feature to organize chats and would be good to make it more visible in the UI. 
<img width="647" alt="Screen Shot 2024-04-14 at 8 04 12 PM" src="https://github.com/open-webui/open-webui/assets/96583594/cca5ad72-e9c8-4267-8440-1988be944e3f">

**Describe the solution you'd like**
Move the tag action under the left side hamburger menu for the specific chat. I think it deserves to be at the same level as rename and delete. 
<img width="353" alt="Screen Shot 2024-04-14 at 8 04 29 PM" src="https://github.com/open-webui/open-webui/assets/96583594/a32d2bfd-75c4-4241-b5fb-101353048fcb">

**Describe alternatives you've considered**

**Additional context**

**Comment by tjbck** [comment]
Great suggestion! Working on it!
