### ISSUE TITLE
feat: mobile sidebar swipe to open 

### ISSUE THREAD

**Issue by RealMrCactus** [open-webui/open-webui#1578]
**Is your feature request related to a problem? Please describe.**
On mobile it's frustrating to have to manually press the little bar instead of guestures 

**Describe the solution you'd like**
ability to use gestures to open and close the chat area on mobile instead of presses

**Describe alternatives you've considered**
None

**Additional context**
![IMG_20240416_134736.png](https://github.com/open-webui/open-webui/assets/36554881/bb191682-946e-419d-b0f2-87d664554ac9)

**Comment by tjbck** [comment]
Great idea! I'll try to ship this with 0.1.119.

**Comment by RealMrCactus** [comment]
> Great idea! I'll try to ship this with 0.1.119.

Alright thanks
