### ISSUE TITLE
feat: Make embeddings model configurable via env var

### ISSUE THREAD

**Issue by peperunas** [open-webui/open-webui#1587]
It would be great to have a way to setup the default embedding models via an env var.

For example, the user can set up a provider - e.g., Ollama - and its embedding model.

**Comment by tjbck** [comment]
PR welcome!

**Comment by tjbck** [comment]
<img width="787" alt="image" src="https://github.com/open-webui/open-webui/assets/25473318/555537b5-d463-40de-9997-d91101f6f732">

I just realised you can already do this with these env vars. Let me know if you encounter any issues.

**Comment by justinh-rahb** [comment]
> <img alt="image" width="787" src="https://private-user-images.githubusercontent.com/25473318/324201324-555537b5-d463-40de-9997-d91101f6f732.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM2NDMxNDAsIm5iZiI6MTcxMzY0Mjg0MCwicGF0aCI6Ii8yNTQ3MzMxOC8zMjQyMDEzMjQtNTU1NTM3YjUtZDQ2My00MGRlLTk5OTctZDkxMTAxZjZmNzMyLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIwVDE5NTQwMFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWYxMTRlODliYjdmNmQxYmRmZTIwYzQ5ZDIyZDNkNGFkNTNiYjY5YzU1MTEwZDYxODAzNDE1ZmJhNzZhNzAxNDMmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.rpmMqEiumwTHD8hnHecTMmMghVFTcMTzgjrrbRZ95jM">
> I just realised you can already do this with these env vars. Let me know if you encounter any issues.

So like embedding engine options would be `ollama`, `openai` and...?

**Comment by tjbck** [comment]
empty string for default, `ollama` for Ollama, `openai` for OpenAI 😅
