### ISSUE TITLE
Better error display of toast when the request to OpenAI API server via proxy fails

### ISSUE THREAD

**Issue by rudeigerc** [open-webui/open-webui#1596]
# Bug Report

## Description

**Bug Summary:**

The conversations shows the toast with text "Uh-oh! There was an issue connecting to [object Object]." when the request to OpenAI API server via proxy fails.

**Steps to Reproduce:**

1. Send the chat request to the OpenAI API server, and get an unsuccessful response. (e.g. body length > max token length)

**Expected Behavior:**

The toast displays "Uh-oh! There was an issue connecting to `Model Name / Server Address`.".

**Actual Behavior:**

The toast displays "Uh-oh! There was an issue connecting to [object Object].".

## Environment

- **Operating System:** Windows 10
- **Browser (if applicable):** Chrome 114.0.5735.199

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
N/A

**Docker Container Logs:**
N/A

**Screenshots (if applicable):**
N/A

## Installation Method

N/A

## Additional Information

https://github.com/open-webui/open-webui/blob/e0ebd7aeaf379a7016be5802b455601eb3336fb7/src/routes/(app)/%2Bpage.svelte#L683-L696

## Note

N/A

**Comment by tjbck** [comment]
Duplicate: #1454
