### ISSUE TITLE
feat: SAML / Entra ID authentication options for cloud-based deployments (Microsoft Azure Entra ID integration)

### ISSUE THREAD

**Issue by odonnja** [open-webui/open-webui#1605]
The current implementation of Open WebUI does not offer any alternative authentication methods such as SAML-based authentication. Having these options would help administrators with user management, implementation  of RBAC, and would enhance overall security of the Open WebUI application server.

**Describe the solution you'd like**
Would like to be able to use a SAML / Microsoft Entra ID-compatible authentication system option in Open WebUI for cloud-based deployments. Perhaps Leverage the existing user JWT to assist in this process. 

Here is some information on how this might be done:
https://learn.microsoft.com/en-us/entra/identity/enterprise-apps/migrate-adfs-saml-based-sso

**Comment by justinh-rahb** [comment]
Multiple duplicates, let's stick to here:
- #483
