### ISSUE TITLE
feat: ability to download answers in table format as an Excel or CSV file.

### ISSUE THREAD

**Issue by Taehui** [open-webui/open-webui#1612]
**Is your feature request related to a problem? Please describe.**
When the LLM answer is in table form as shown in the picture below, the ability to download the results in Excel or CSV is required.

**Describe the solution you'd like**
<img width="767" alt="table" src="https://github.com/open-webui/open-webui/assets/612173/a1dd0e8f-7088-4c83-9dba-b853752a77de">

The ability to download 5 records of table data as a file is required.

**Comment by LucasArusiewicz** [comment]
I did some tests and was unable to render a table through the model response.
The best I could do was return an HTML code as code. For example \`\`\`html {{generated content}}\`\`\`.

Is there any specific input pattern to be rendered in the chat interface?
If not, maybe I can be the first step to have the option of downloading the data in csv or xls.

_Observation: I started using open-webui less than a day ago hehe_

**Comment by gelbzucht** [comment]
I just started to test another way: have you tried to run the python code within the chat to generate a csv or XLSX? 
Excel file: Error when "run". 
CSV: get's generated (at least that is the feedback :) But have to check if it is really available somewhere and how to access it via Chat interface. #juststarted
<img width="850" alt="image" src="https://github.com/open-webui/open-webui/assets/42704390/f880b25a-81c6-4a0c-acb6-80aab74869d3">

**Comment by mafzaal** [comment]
I conducted some research and discovered that we are using [Marked](https://github.com/markedjs/marked) to tokenize content. Specifically, for table content, the token type is "table" as defined in [MarkdownTokens.svelte](https://github.com/open-webui/open-webui/blob/c3faed71ef24ee23465fdd0db995819d424cc672/src/lib/components/chat/Messages/Markdown/MarkdownTokens.svelte#L57). 

Given our existing use of [Pyodide](https://pyodide.org/en/stable/), I'm considering developing a program that runs in the browser to generate an Excel or CSV file and subsequently add a download link beneath the content.

## Solution Approach

1. Add export buttons when the token type is "table".
2. Use a Python program executed in Pyodide to generate the CSV or Excel file.
3. Insert a download link beneath the content for accessing the file.

Please provide feedback on this solution approach. I am ready to work on it.

**Comment by mafzaal** [comment]
Please review [RP](https://github.com/open-webui/open-webui/pull/6661) for this feature.

**Comment by tjbck** [comment]
Added to dev!

![image](https://github.com/user-attachments/assets/60e4f8cb-47fd-49c5-a8a6-eee8d34bf40f)
