### ISSUE TITLE
Ollama embedding model selection setting not persistent after Save and Docker container restart

### ISSUE THREAD

**Issue by odonnja** [open-webui/open-webui#1615]
# Bug Report

## Description
Ollama Embedding model selection setting not persistent after save and Docker container restart (resets to default model)

**Bug Summary:**
In Document settings > General > Update Embedding Model. After the "Embedding Model Engine" was selected as "Ollama" and the model was chosen (in this case "snowflake-arctic-embed:335m". Setting was saved and double checked after the save to make sure it saved. Setting was ok at that point, but after the docker image was shutdown and restarted via Docker Desktop, the "Default (SentienceTransformer"  setting of "all-MiniLM-L6-v2" had returned and replaced the custom setting. 

**Steps to Reproduce:**
1. In Document settings > General > Update Embedding Model. Set the "Embedding Model Engine" to "Ollama" and the model was chose an embedding model that has been previously downloaded.  (in this case "snowflake-arctic-embed:335m". Click the check mark next to the dropdown box to select the model. Click the "Save" button at the bottom of the window.
2. Logout of Open WebUI and close the browser. 
3. In Docker Desktop. Stop the container and then start the container.
4. Log back into Open WebUI in the web browser.
5. Go to the Document > Document settings > General and you will see that the default settings have returned and replaced the custom ones that were set in step 1. 

**Expected Behavior:**
The saved settings should have remained in place after the Docker container was stopped and restarted.

**Actual Behavior:**
After the Docker container was stopped and restarted, the saved settings were replaced with the default settings. 

## Environment
- **Operating System:** [Windows Server 2022 Data Center Edition(
- **Browser (if applicable):** Chrome Version 124.0.6367.61 

## Reproduction Details

**Confirmation:**

- [ X] I have read and followed all the instructions provided in the README.md.
- [ X] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Installation Method

Installed WebUI with the standard Docker Command included in the instructions.

**Comment by c9482** [comment]
I am experiencing similar problem but, in addition to that, document settings do not persist event without restarting the container. 

I can modify the document settings, click Save, close the dialog, re-open the dialog and all my changes are gone.

**Comment by tjbck** [comment]
Duplicate #1022

**Comment by c9482** [comment]
For what it's worth, the way to save the document embedding settings is to click the button next to embedding model dropdown rather than clicking the Save button. 

![image](https://github.com/open-webui/open-webui/assets/17013052/a277dbb4-feb2-4b24-aa75-d5e47fe79aca)

**Comment by Erik262** [comment]
> For what it's worth, the way to save the document embedding settings is to click the button next to embedding model dropdown rather than clicking the Save button.
> 
> ![image](https://private-user-images.githubusercontent.com/17013052/324142247-a277dbb4-feb2-4b24-aa75-d5e47fe79aca.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTM3NzYzNTcsIm5iZiI6MTcxMzc3NjA1NywicGF0aCI6Ii8xNzAxMzA1Mi8zMjQxNDIyNDctYTI3N2RiYjQtZmViMi00YjI0LWFhNzUtZDVlNDdmZTc5YWNhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA0MjIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNDIyVDA4NTQxN1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWMyMzdlZDg4ZmYyNjhkYmViZjg3YTVmMGNjYmFkZjhhOTU4MDYyM2YxOGYxNDkyODRhZTAxZDFkYzU0M2Y5OGEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.u3IgLJZFbT7IPhmsxWzfCclDVxUOUSoPF0OX6vCSDBw)

unfortunately did not work on my side.
