### ISSUE TITLE
Graphs/Charts/plot_graph support

### ISSUE THREAD

**Issue by ack72tdp** [open-webui/open-webui#1618]
**Is your feature request related to a problem? Please describe.**
Can't display graphs/charts ... for ex: I asked to display population of USA by state and in a bar chart. It gives me the data.. but won't display the bar chart. or it gives me code to run .. 

**Describe the solution you'd like**
It would be nice to have graph/chart/plot_graph support for data analysis support in the UI itself .. so one don't need to execute code

**Describe alternatives you've considered**

**Additional context**

**Comment by tjbck** [comment]
Duplicate #1321
