### ISSUE TITLE
Admin Panel "Enable New Sign Ups" not persistent after Save and Docker container restart

### ISSUE THREAD

**Issue by nicolasluckie** [open-webui/open-webui#1645]
# Bug Report

## Description

**Bug Summary:**
In Admin Panel > Admin Settings > General > Enable New Sign Ups. Toggling and Saving this setting persists **only** until the container is restarted.

**Steps to Reproduce:**
1. Login as admin.
3. Open the sidebar and click your User icon in the bottom-left.
4. Select Admin Panel.
5. Click Admin Settings in the top-right.
6. Toggle Enable New Sign Ups
7. Save
8. Log out and back in to verify the setting saved successfully.
9. Restart the container (in my case, `docker compose down` then `./run-compose.sh --enable-gpu --build`)

**Expected Behavior:**
The Enable New Sign Ups setting is persistent when Saved **and** after the container is restarted.

**Actual Behavior:**
The Enable New Sign Ups setting is persistent when Saved **but not** after the container is restarted.

## Environment

- **Open WebUI Version:** 0.1.120
- **Ollama (if applicable):** 0.1.32

- **Operating System:** WSL2 for Windows 11 running Ubuntu 22.04.4 LTS (GNU/Linux 5.15.133.1-microsoft-standard-WSL2 x86_64)
- **Browser (if applicable):** Brave v1.65.114

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
No console logs were produced.

**Docker Container Logs:**
```
INFO: - "GET /api/v1/users/ HTTP/1.1" 200 OK
INFO: - "GET /api/v1/auths/signup/enabled HTTP/1.1" 200 OK
INFO: - "GET /api/v1/auths/signup/user/role HTTP/1.1" 200 OK
INFO: - "GET /api/v1/auths/token/expires HTTP/1.1" 200 OK
INFO: - "GET /api/webhook HTTP/1.1" 200 OK
INFO: - "GET /api/v1/auths/signup/enabled/toggle HTTP/1.1" 200 OK
INFO: - "POST /api/v1/auths/token/expires/update HTTP/1.1" 200 OK
INFO: - "POST /api/webhook HTTP/1.1" 200 OK
```

**Screenshots (if applicable):**
**After Save, Before restart**
![setting-before-restart](https://github.com/open-webui/open-webui/assets/18017189/e323f088-2fb3-4a79-b96c-7e72aeec82c8)

**After Restart**
![setting-after-restart](https://github.com/open-webui/open-webui/assets/18017189/5e3b0ac3-8a71-4eb3-9831-ba4bfbe23f63)

## Installation Method
1. Clone latest release
2. Run `./run-compose.sh --enable-gpu --build` (WSL2 for Windows 11, details above)

**Comment by tjbck** [comment]
Duplicate #1022
