### ISSUE TITLE
feat: tag llms

### ISSUE THREAD

**Issue by RealMrCactus** [open-webui/open-webui#1655]
**Is your feature request related to a problem? Please describe.**
Browsing models when you have too many or many different varients

**Describe the solution you'd like**
The ability to make folders to organize them in the selector

**Describe alternatives you've considered**
Tags to search by?

**Additional context**
Not really

**Comment by RealMrCactus** [comment]
> Edit: Another consideration might be whether this should be a system-wide setting by the admin or a per-user categorization/tagging. Personally it doesn't matter to me since I'm only using this myself, but if I shared with friends I could see some use in being able to set up categories/tags on models for them. On the other hand, I could see a user wanting to make their own categories so I think it could go either way. Maybe it's beyond an MVP to allow non-admin users to uncheck a "use system model categories/tags" to enable the categorization/tagging settings and to ignore the system settings for that user. Personally I think the MVP should be a system-wide categorization with a further ticket for per-user setting if there's interest/demand for such a feature.


I think it should be both user and systemwide admin and the user can choose to see the admin ones or not if the user would like their own

**Comment by Silentoplayz** [comment]
I did have an idea for the model selector dropdown to be able to **Star** models to mark them as a favorite, so that starred/favorited models are prioritized and displayed first over other models in the model selector dropdown. Just thought I'd bring this idea over to this thread and make it known where discussion is occurring.

**Comment by RealMrCactus** [comment]
>  I did have an idea for the model selector dropdown to be able to **Star** models to mark them as a favorite, so that starred/favorited models are prioritized and displayed first over other models in the model selector dropdown. Just thought I'd bring this idea over to this thread and make it known where discussion is occurring.

Maybe users could have stars and the admins can make the folders then

**Comment by tjbck** [comment]
![image](https://github.com/open-webui/open-webui/assets/25473318/cbc38def-8812-424a-aff2-7e90c5eb81f8)

![image](https://github.com/open-webui/open-webui/assets/25473318/0d8b4c15-db8c-49b1-855e-1b19e99a1b10)

Model tagging feature has been added to our dev branch, let me know if you encounter any issues!

**Comment by tjbck** [comment]
FYI, You can also set the position of the model from the model workspace by dragging it to the position you want.

**Comment by RealMrCactus** [comment]
damn nice thanks 👍🏽

**Comment by silentoplayz** [comment]
Sweet! This is fantastic!

**Comment by justinh-rahb** [comment]
https://github.com/open-webui/open-webui/assets/52832301/ead534c6-51db-453a-8fa7-d15fbc45067e


https://github.com/open-webui/open-webui/assets/52832301/58892f21-cfc6-4831-9908-2b72a64b0faf

**Comment by Classic298** [comment]
@ctdavi you can do so by editing the connection and adding a prefix

**Comment by silentoplayz** [comment]
@ctdavi You can add either a specific tag or tags for a connection or you can choose to add a prefix to all model IDs provided by an API connection.

![Image](https://github.com/user-attachments/assets/587503cb-9edf-4b5c-b4fb-8c17d34509a7)
