### ISSUE TITLE
Possible regression on Share Link with v0.1.120

### ISSUE THREAD

**Issue by seandearnaley** [open-webui/open-webui#1656]
I originally opened this ticket which was supposed to be fixed w 0.1.120, thanks for the hard efforts but it seems that may have caused a regression as the share link / copy to clipboard now just copies null on both ios and chrome on the desktop.

https://github.com/open-webui/open-webui/issues/1608

**Comment by tjbck** [comment]
Just pushed a fix, let me know if the issue persists!
