### ISSUE TITLE
feat: persist model download status in Settings/Models

### ISSUE THREAD

**Issue by bkopec** [open-webui/open-webui#1660]
**Is your feature request related to a problem? Please describe.**
Model download status line doesn't persist when changing pages in settings.

**Describe the solution you'd like**
I believe the status should persist.

**Comment by bkopec** [comment]
Isn't it retarded design ?

The model download feature is core to new users, the download bar is important as they need to wait until it's achieved to start using the app, problem is the download takes time so user is tempted to explore around, and it's completely counter-intuitive that you have to "pull the model again" just to "view the download status bar".

Perhaps i'm getting old, perhaps software isn't what it used to be and keeping the code clean is more important than user experience now.

**Comment by justinh-rahb** [comment]
> Isn't it bad design ?
> 
> The model download feature is core to new users, the download bar is important as they need to wait until it's achieved to start using the app, problem is the download takes time so user is tempted to explore around, and it's counter-intuitive that you have to "pull the model again" just to "view the download status bar".

It is what it is. Short of re-architecting the frontend to spawn some sort of listening process in the background to listen for those server-side events, this is not currently acheivable. PRs more than welcome, always.

**Comment by tjbck** [comment]
@bkopec should be fixed on our dev branch, let me know if the issue persists :)
