### ISSUE TITLE
`<br>` is not escaped in output text

### ISSUE THREAD

**Issue by AnotiaWang** [open-webui/open-webui#1663]
# Bug Report

## Description

**Bug Summary:**
The HTML tag `<br>` is not escaped in the model output, even if wrapped in Markdown code block (see the screenshot below)

**Steps to Reproduce:**
1. Ask a LLM model to write a HTML file with some `<br>`

**Expected Behavior:**
The `<br>`s should be displayed directly

**Actual Behavior:**
`<br>` is rendered as new line

## Environment

- **Open WebUI Version:** 0.1.120
- **Ollama (if applicable):** None

- **Operating System:** macOS 14.5 Beta 2
- **Browser (if applicable):** Vivaldi 6.6.3271.61 (Stable channel) (arm64) 

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
None

**Docker Container Logs:**
None

**Screenshots (if applicable):**
<img width="576" alt="截屏2024-04-22 14 14 46" src="https://github.com/open-webui/open-webui/assets/62269186/eaab3ff5-778c-4c31-9597-e93ba62bf5bc">

## Installation Method

Docker

## Additional Information

None

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by dannyl1u** [comment]
Fixed on `dev` branch
