### ISSUE TITLE
show a list of citation,  for user to check if there  is problem in LLM, or in citation

### ISSUE THREAD

**Issue by glowzz** [open-webui/open-webui#1664]
show a list of citation,  for user to check if there  is problem in LLM, or in citation
just like AnythingLLM do
![v2-aee69b4deaea733979373955a27c41cc_1440w](https://github.com/open-webui/open-webui/assets/46548252/9ad88e23-0ad3-421d-bbb1-2226c398ed20)

**Comment by justinh-rahb** [comment]
General improvements to RAG are being discussed in this issue:
- #715
