### ISSUE TITLE
Polish locale doesn't work

### ISSUE THREAD

**Issue by lucz-volue** [open-webui/open-webui#1673]
# Bug Report

## Description

**Bug Summary:**
[Provide a brief but clear summary of the bug]

**Steps to Reproduce:**
[Outline the steps to reproduce the bug. Be as detailed as possible.]

**Expected Behavior:**
After switching to polish, language is changed.

**Actual Behavior:**
After switching to polish, language is still english

## Environment

- **Open WebUI Version:** [e.g., 0.1.120]

## Logs and Screenshots
Seems like directory name for polish translation is incorrect - it is name 'pl-pl', and probably should be 'pl-PL, as for other languages':
![image](https://github.com/open-webui/open-webui/assets/65351037/38c6d51c-0c0e-4344-89b7-90dc8e14531d)

**Comment by justinh-rahb** [comment]
There was a PR for this that may have been closed in error.

**Comment by tjbck** [comment]
Should be fixed now, let me know if the issue persists!
