### ISSUE TITLE
cmd (windows) + enter to submit prompt. Enter create new line

### ISSUE THREAD

**Issue by tranghoang15591** [open-webui/open-webui#1676]
I'd like to write long prompt in multiple paragraphs, however, hit Enter just submit the prompt. 
Please allows (optional?) new line by Enter, and submit prompt by cmd+Enter or window+Enter

**Comment by justinh-rahb** [comment]
It currently works the opposite way, you can enter new lines with Ctrl (win / Cmd (mac) + Enter. I don't see a benefit in flipping the behaviour, I only envision a lot of folks being confused about why we chose to do so.

**Comment by tranghoang15591** [comment]
hmmm, i'm on Mac M1 and Ctr (Cmd) + Enter DOES NOT create new line. I'm using docker.

**Comment by justinh-rahb** [comment]
My mistake, it's Shift+Enter, which is the common combo for entering newlines in multi-line input boxes.

**Comment by ElSamhaa** [comment]
hello, can we add a setting to flip this behavior?
