### ISSUE TITLE
Configured OpenAI APIs not saving between restarts

### ISSUE THREAD

**Issue by chand1012** [open-webui/open-webui#1679]
# Bug Report

## Description

**Bug Summary:**
Whenever I set up my OpenAI compatible endpoints and hit save, it works great until I restart the container, when it gets wiped. I made sure that there is storage set up, which there is. Audio and Image generation setup also reset. All other configuration, chat history, and users save just fine.

**Steps to Reproduce:**
1. Download latest container.
2. Run the container.
3. Set up OpenAI endpoints.
4. Restart container.
5. Endpoints are gone.

**Expected Behavior:**
The OpenAI compatible endpoints, image config, and audio config should save between restarts.

**Actual Behavior:**
The OpenAI endpoints, image config, and audio config get reset between restarts.

## Environment

<img width="531" alt="image" src="https://github.com/open-webui/open-webui/assets/3521582/5bc81f9c-181b-4449-b5e7-f29d30bf5520">

- **Operating System:** MacOS Sonoma 14.4.1, Ubuntu 22.04 LTS
- **Browser (if applicable):** Firefox 125.0.1

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] ~~I have included the browser console logs.~~ Not Relevant.
- [x] ~~I have included the Docker container logs.~~ Logs show no sign of issue.

## Installation Method
On MacOS, followed the official [Quick Start Docker instructions](https://github.com/open-webui/open-webui?tab=readme-ov-file#quick-start-with-docker-).

Installation on Ubuntu 22.04 LTS was manual as I'm using [Coolify v4](https://coolify.io/self-hosted) to host all my personal use containers on my Linux server.

**Comment by justinh-rahb** [comment]
Duplicate:
- #1264
