### ISSUE TITLE
bug: tags not being restored when unarchiving

### ISSUE THREAD

**Issue by tjbck** [open-webui/open-webui#1690]
#1106

**Comment by silentoplayz** [comment]
Pinned chats are not restored as a pinned chat when archived and then unarchived as well.

**Comment by Krzysi3k** [comment]
tags are not being restored at all.
If you install open-webui from scratch and then restore chats from json file via: settings -> chats -> Import Chats
Chats are restored (not sorted by date tho) but no tags are present.

**Comment by tjbck** [comment]
Fixed on dev!

**Comment by silentoplayz** [comment]
> Fixed on dev!

I can confirm that any chat tags and the pinned status of a chat are indeed restored from unarchiving chats now, but when I pin a chat, add a tag to it, download the chat .json export and then delete the chat to re-import it, the chat is not added to the pinned chats section and has no tags restored with it.

**Comment by tjbck** [comment]
@silentoplayz addressed!
