### ISSUE TITLE
bug: Account Activation Pending can be bypassed by setting

### ISSUE THREAD

**Issue by JoeABCDEF** [open-webui/open-webui#1695]
# Bug Report

## Description

**Bug Summary:**
My account is in the Pending Activation state, but there are some things you can do to use it directly

Open WebUI Version
v0.1.120

**Steps to Reproduce:**
![image](https://github.com/open-webui/open-webui/assets/39638510/de2edccc-7a68-4fc4-98a6-f7134e6b6ea5)
It's just that it still doesn't work, because the list of models is empty
![image](https://github.com/open-webui/open-webui/assets/39638510/62419555-53f4-4876-ae85-4543286f4bc2)
When I click on Full Screen Mode, it goes directly to the list of models, so I can use it without activating it
![image](https://github.com/open-webui/open-webui/assets/39638510/3db8c166-46fb-43b0-bb20-7de529ddaf6b)

**Expected Behavior:**
[Describe what you expected to happen.]

**Actual Behavior:**
[Describe what actually happened.]

## Environment

- **Open WebUI Version:** [e.g., 0.1.120]
- **Ollama (if applicable):** [e.g., 0.1.30, 0.1.32-rc1]

- **Operating System:** [e.g., Windows 10, macOS Big Sur, Ubuntu 20.04]
- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Installation Method

[Describe the method you used to install the project, e.g., manual installation, Docker, package manager, etc.]

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by constLiakos** [comment]
I tried it with external models, but i get below message, the problem might be only on the local ones.
"You do not have permission to access this resource. Please contact your administrator for assistance."

**Comment by tjbck** [comment]
Fixed on dev, let me know if the issue persists!
