### ISSUE TITLE
bug: Audio settings can't save unless openai key is provided

### ISSUE THREAD

**Issue by ugthefluffster** [open-webui/open-webui#1705]
# Bug Report

## Description

**Bug Summary:**
When I'm in Settings->Audio and Text-to-Speech Engine is set to "Open AI", and I don't provide an API key, when I switch to "Default (Web API)", I cannot save the settings. A POST request is sent to http://localhost:3000/audio/api/v1/config/update, which returns status code 400, with this response:
detail: "Oops! It looks like there's a hiccup. The API key is missing. Please make sure to provide a valid API key to access this feature."

**Expected Behavior:**
When Text-to-Speech Engine is set to "Default (Web API)", it should be able to save the setting without having to put an openai API key. 

## Environment
Runs in docker as per the install recommendation, and browsing with Chrome.

**Comment by tjbck** [comment]
Fixed on our dev branch!
