### ISSUE TITLE
feat: Auto-detect the user's language or set a default language.

### ISSUE THREAD

**Issue by PasserDreamer** [open-webui/open-webui#1713]
**Is your feature request related to a problem? Please describe.**
When accessing the WebUI for the first time or from another device, the language is set to English, and it remains unchanged even after login, even if the language setting was previously altered during an earlier session.

**Describe the solution you'd like**
Allow the WebUI to detect the user's browser language and automatically change the locale.
Add an environment variable ```WEBUI_LANGUAGE``` to set a default language.

**Comment by justinh-rahb** [comment]
Edit `backend/config.json` or use this command for Docker install:
```bash
docker exec -it open-webui sed -i 's/"en-US"/"<locale>"/g' /app/backend/data/config.json
```

**Comment by tjbck** [comment]
Added to our dev branch!

**Comment by saxsoares** [comment]
Despite the "Auto-detect" user's language.... How to force a default language?

**Comment by omeryounus** [comment]
this command didn't work --> docker exec -it open-webui sed -i 's/"en-US"/"<locale>"/g' /app/backend/data/config.json

sed: -e expression #1, char 1: unknown command: `''

What's next:
    Try Docker Debug for seamless, persistent debugging tools in any container or image → docker debug open-webui
    Learn more at https://docs.docker.com/go/debug-cli/
