### ISSUE TITLE
feat: HTTP Basic Authorization for AUTOMATIC1111 Stable Diffusion web UI

### ISSUE THREAD

**Issue by kmc7468** [open-webui/open-webui#1714]
**Is your feature request related to a problem? Please describe.**
I'm currently running AUTOMATIC1111 Stable Diffusion web UI on a different server with authorization enabled. However, since Open WebUI does not support HTTP Basic Authorization at present, I have temporarily disabled authorization. In this case, unauthorized users may access my server and use my GPU resources. It would be good if authorization were added to Open WebUI as well when sending requests to the Stable Diffusion server.

**Describe the solution you'd like**
I would like to request that you add support for HTTP Basic Authorization as mentioned above. I appreciate your efforts.

**Comment by spammenotinoz** [comment]
I have implemented and it works (username:password) defined as system variables, but I have not created a merge as my code change causes the settings screen to bug out. So I need to fix that first.
