### ISSUE TITLE
feat: rename models + descriptions

### ISSUE THREAD

**Issue by PasserDreamer** [open-webui/open-webui#1725]
**Is your feature request related to a problem? Please describe.**
Even though the model names on the menu are pretty straightforward, over time, it's easy to forget what these models are used for.

**Describe the solution you'd like**
Add nicknames to replace model names, displaying the model name when a nickname isn't set.
When a nickname is set, the model name will appear in the hover information on the right side.
![imagine](https://github.com/open-webui/open-webui/assets/30385417/6f0ec6ba-4051-4331-a8ba-7a5e443c0cba)

**Describe alternatives you've considered**

**Additional context**
Additionally, implement a five-star rating system or categories/tags for easier future reference.

**Comment by rmcc3** [comment]
Would also like this see this.

**Comment by CtrlAiDel** [comment]
Hi guys, since https://github.com/open-webui/open-webui/issues/1041 is closed, could I suggest to put the description in the info button ? That would be useful and would fix "my" little problem :) ! 

Thanks

**Comment by silentoplayz** [comment]
Related #2140

**Comment by Hugobox** [comment]
It would be nice to be able to nickname models in the "Connections" settings, we have some OpenAI compatible models that we'd like to nickname but currently can't.

**Comment by justinh-rahb** [comment]
> It would be nice to be able to nickname models in the "Connections" settings, we have some OpenAI compatible models that we'd like to nickname but currently can't.

Already possible:

![Screenshot 2024-06-21 at 1 09 20 PM](https://github.com/open-webui/open-webui/assets/52832301/cce89473-a612-45a9-9e9d-822923985d88)

**Comment by Hugobox** [comment]
Thanks @justinh-rahb ! Works like a charm!

**Comment by ckizer** [comment]
> Thanks @justinh-rahb ! Works like a charm!

What works like a charm? Where do I change the model name? I'm so lost in this UI 
![CleanShot 2024-09-12 at 14 38 58@2x](https://github.com/user-attachments/assets/bfeb5c03-2341-43c3-b37f-7784979c2fec)

**Comment by silentoplayz** [comment]
> > Thanks @justinh-rahb ! Works like a charm!
> 
> What works like a charm? Where do I change the model name? I'm so lost in this UI ![CleanShot 2024-09-12 at 14 38 58@2x](https://private-user-images.githubusercontent.com/191738/367020970-bfeb5c03-2341-43c3-b37f-7784979c2fec.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjYxNzE5NDksIm5iZiI6MTcyNjE3MTY0OSwicGF0aCI6Ii8xOTE3MzgvMzY3MDIwOTcwLWJmZWI1YzAzLTIzNDEtNDNjMy1iMzdmLTc3ODQ5NzljMmZlYy5wbmc_WC1BbXotQWxnb3JpdGhtPUFXUzQtSE1BQy1TSEEyNTYmWC1BbXotQ3JlZGVudGlhbD1BS0lBVkNPRFlMU0E1M1BRSzRaQSUyRjIwMjQwOTEyJTJGdXMtZWFzdC0xJTJGczMlMkZhd3M0X3JlcXVlc3QmWC1BbXotRGF0ZT0yMDI0MDkxMlQyMDA3MjlaJlgtQW16LUV4cGlyZXM9MzAwJlgtQW16LVNpZ25hdHVyZT0wNGRhOGI5ZmI5ZDlkMTE1ZGI1MjVmZmRkZDg3ZGFmYTlhYzg3ZjY4YjY0YzZmOWZjZTczOWRlZWJkMGI2ZGEwJlgtQW16LVNpZ25lZEhlYWRlcnM9aG9zdCZhY3Rvcl9pZD0wJmtleV9pZD0wJnJlcG9faWQ9MCJ9.6QikbJaMy6uITV2VOLBvaIUK8GB8SJxzE7ifZQoltbc)

https://github.com/open-webui/open-webui/issues/5383#issuecomment-2347098415

**Comment by zaventh** [comment]
This would be great to have as a system-wide setting and not only at the user level.

**Comment by silentoplayz** [comment]
> This would be great to have as a system-wide setting and not only at the user level.

The ability to rename models and set a description for them are restricted to Admin users only. It is not accessible to modify at the user level. I disagree with the stance that it would be great to have this made available at a system-wide level, as I don’t want user accounts changing model names and descriptions that I have set up myself in the Workspace section.

**Comment by HA-TB303** [comment]
Sorry for this noob question. I am administrator, but can't change the model name. I also can't find any reference to such a feature in the documentation.

![Image](https://github.com/user-attachments/assets/8606189d-39bc-481a-b221-233dcc02910a)

**Comment by rgaricano** [comment]
> Sorry for this noob question. I am administrator, but can't change the model name. I also can't find any reference to such a feature in the documentation.
> 
> ![Image](https://github.com/user-attachments/assets/8606189d-39bc-481a-b221-233dcc02910a)

To change the name simply type over the model name and edit it.

**Comment by HA-TB303** [comment]
I feel a lilttle silly now. It was not directly obvious to me it would work like that. :)

Thanks!

**Comment by malteneuss** [comment]
Related to this topic. How do i rename a model through environment variables like [DEFAULT_MODEL_METADATA](https://docs.openwebui.com/reference/env-configuration#default_model_metadata)?

The following doesn't work.
```json
DEFAULT_MODEL_METADATA='{
        "models": [
          {
          "id": "gemma4:26b",
          "name": "Generalist gemma4:26b"
          }
        ]
      }'
```

Background: I'm configuring Open-WebUI in NixOS and only have the environment variable available.
