### ISSUE TITLE
way to pull already pulled models to get updates

### ISSUE THREAD

**Issue by TadayukiOkada** [open-webui/open-webui#1726]
**Is your feature request related to a problem? Please describe.**
ollama models are sometimes updated silently to fix issues with template, params, etc. you can pull the model again to update, but you may not notice there's an update.

**Describe the solution you'd like**
add a pull all button to initiate pulling (ollama pull <model>) for local models. this only pulls the differences.

**Describe alternatives you've considered**
it would be nice if you can show which model is stale and a button to update each model, but ollama doesn't seem have an ability to show which model is stale.

**Additional context**
ollama's llama3 and phi3 models both had silent updates.

**Comment by justinh-rahb** [comment]
Already have that:
![Screenshot 2024-04-24 at 1 29 23 PM](https://github.com/open-webui/open-webui/assets/52832301/1e236f61-6e49-434c-a511-9ff68bee0ccf)

**Comment by TadayukiOkada** [comment]
oops, didn't notice it. 🤦‍♂️
