### ISSUE TITLE
download database is not working.

### ISSUE THREAD

**Issue by arjunkrishna** [open-webui/open-webui#1733]
# Bug Report

## Description

download database in not working

**Bug Summary:**
[Provide a brief but clear summary of the bug]
when you click on download database under admin panel it does not do anything and throws network error.

**Steps to Reproduce:**
[Outline the steps to reproduce the bug. Be as detailed as possible.]
cick download database under admin panel

**Expected Behavior:**
[Describe what you expected to happen.]
it shoudl download webui.db

**Actual Behavior:**
[Describe what actually happened.]
does not do anything.

## Environment

- **Open WebUI Version:**  0.1.121
- **Ollama (if applicable):** 0.1.32

- **Operating System:** windows 11, docker, wsl2
- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]

## Reproduction Details

```powershell
docker run -d -p 3000:8081 -e OLLAMA_BASE_URL=http://host.docker.internal:11434 -e PORT=8081 -e MODEL_FILTER_ENABLED=True -e MODEL_FILTER_LIST="mistral:latest;llava:latest;llama3:latest" -e USER_PERMISSIONS_CHAT_DELETION=True -e DEFAULT_USER_ROLE=user -e ENABLE_ADMIN_EXPORT=True -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main
```
![image](https://github.com/open-webui/open-webui/assets/5271912/cc3317d9-dd04-4f27-9ad5-e59ad2df5707)

**Confirmation:**

- [ ] I have read and followed all the instructions provided in the README.md.
- [ ] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Installation Method

[Describe the method you used to install the project, e.g., manual installation, Docker, package manager, etc.]

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
Should be fixed now!

**Comment by arjunkrishna** [comment]
Could restore database functionality be added to this page, wherein a prior copy can be uploaded?
