### ISSUE TITLE
Bypass login for simple users or faster login

### ISSUE THREAD

**Issue by MohamedAliRashad** [open-webui/open-webui#1746]
I want to host open-webui for my local community and i don't want to bother them with repetative login requests everytime they leave the app and come back again.
Is there away to disable login or save cookies so they login directly after the first time (Remember me button) ?

**Comment by justinh-rahb** [comment]
Set the `WEBUI_SECRET_KEY` variable to something long and random, but as long as it's kept the same between container re-runs it will preserve all logged in sessions indefinitely.
