### ISSUE TITLE
Stop Sequence with Backslash '\' Does Not Work

### ISSUE THREAD

**Issue by ibndias** [open-webui/open-webui#1747]
# Bug Report
Stop Sequence with Backslash '\' Does Not Work

## Description
It seems there is a post process that escape the backslash character. So the final stop sequence produces is incorrect.

**Bug Summary:**
It seems there is a post process that escape the backslash character. So the final stop sequence produces is incorrect.

**Steps to Reproduce:**
I am using VLLM Backend.
Open any model, and set stop token on every line break, example set: `\n`

**Expected Behavior:**
Stop token should be stay `\n` instead of becoming `\\n`

**Actual Behavior:**
The stop token shown in my inspection is escaped and added another backslash prefix.

## Environment

- **Open WebUI Version:** v0.1.121
Ollama Version 0.1.32
- **Operating System:** POP OS 22.04]
- **Browser (if applicable):** Chrome Version 123.0.6312.105 (Official Build) (64-bit)

## Reproduction Details
I am using VLLM Backend.
Open any model, and set stop token on every line break, example set: `\n`

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots
![image](https://github.com/open-webui/open-webui/assets/3958152/9fd1f5e1-2c5b-40cd-9539-a1c86a8c17c4)

As we can see the system prompt has no problem handling line break into `\n`

But the stop sequence becomes `\\n` instead of just `\n`

## Installation Method
Docker Method

**Comment by tjbck** [comment]
<img width="606" alt="image" src="https://github.com/open-webui/open-webui/assets/25473318/adebb8f4-f861-4d0e-a2b8-aacdbf8491d5">

I can't seem to reproduce this issue on my end :/

**Comment by tjbck** [comment]
Should be fixed on our dev branch, let me know if the issue persists!
