### ISSUE TITLE
Unhandled Promise Rejection: TypeError: undefined is not an object (evaluating 'r.choices[0].delta')

### ISSUE THREAD

**Issue by mandasaka** [open-webui/open-webui#1759]
# Bug Report

## Description
Hello,
I noticed that the newly added [src](https://github.com/open-webui/open-webui/tree/main/src)/[lib](https://github.com/open-webui/open-webui/tree/main/src/lib)/[apis](https://github.com/open-webui/open-webui/tree/main/src/lib/apis)/[streaming](https://github.com/open-webui/open-webui/tree/main/src/lib/apis/streaming)
/index.ts script in version v0.1.121 fails to handle responses where the 'choices' field lacks a 'delta', with these responses coming from Azure OpenAI.

The first response from completions:

data: {"choices":[],"created":0,"id":"","model":"","object":"","prompt_filter_results":[{"prompt_index":0,"content_filter_results":{"hate":{"filtered":false,"severity":"safe"},"self_harm":{"filtered":false,"severity":"safe"},"sexual":{"filtered":false,"severity":"safe"},"violence":{"filtered":false,"severity":"safe"}}}]}

Thank you and looking forward to your response.

**Comment by tjbck** [comment]
@cheahjs

**Comment by tjbck** [comment]
Should be fixed on our dev branch now, let me know if the issue persists!

**Comment by mandasaka** [comment]
It’s ok now, thx
