### ISSUE TITLE
Easily create Litellm modelfiles via the web UI and not only Ollama

### ISSUE THREAD

**Issue by flefevre** [open-webui/open-webui#1787]
**Is your feature request related to a problem? Please describe.**
When I try to create a model file with a model that is store not on the ollama server but on the litellm server in my openwebui configuartion files, the oepn webui interface try to download it "pull model manifest: Get "https://ollama.com/token?nonce=PVU8K_tursrhgMstjAboFw&scope=repository%3Alibrary%2Fmixtral-8x7b%3Apull&service=ollama.com&ts=1714223332": EOF"

i do confirm the litellm model is accessible through the open webui
in my case I am using litellm > vllm > mixtral 8x7b

**Describe the solution you'd like**
It should be possible to create a model file for a model accessible through the litellm server.

**Comment by tjbck** [comment]
Duplicate #665
