### ISSUE TITLE
Adding RAG documents per user

### ISSUE THREAD

**Issue by Eirfire** [open-webui/open-webui#1818]
**Is your feature request related to a problem? Please describe.**
Documents is a huge part of running LLM's locally and I love the feature. Something I would really love is the ability for other users to upload their own documents which others will not be able to access, as my family would love to use the tool as well but I do not wish to share my documents with them nor they share their documents with me.

**Describe the solution you'd like**
What might this look like? well, users that aren't admins would have the ability to upload their own documents that would be contained to them and them only (admins would still have access to this). 

For admins when they upload documents they would have the ability to set `public` to `true` or `false` so that their own personal documents don't get mixed with other users, this could be extended for users to do the same where they choose to make one of their documents public

This could be further extended with the Admin choosing whether it is possible for users to upload their own documents

**Additional context**
It make look something like this for admins when uploading documents
![image](https://github.com/open-webui/open-webui/assets/77374574/5c262103-bbb2-4f9d-9997-32857243dfe4)

And the side bar having something like this:
![image](https://github.com/open-webui/open-webui/assets/77374574/f4c4b4a8-a6d4-4675-ae53-8032b9c765a2)

**Comment by justinh-rahb** [comment]
You've got some great mockups here, we'd love to continue discussion in this related issue:

- #1096
