### ISSUE TITLE
Custom OpenAI API Endpoints Do Not Load

### ISSUE THREAD

**Issue by jmstacey** [open-webui/open-webui#1826]
# Bug Report

## Description

**Bug Summary:**
Custom OpenAI API Endpoints don't seem to work, such as api.together.xyz, and api.replicate.com 

**Steps to Reproduce:**
1. Settings, Connections, OpenAPI
2. Add an endpoint using together or replicate API base and key

**Expected Behavior:**
Available models load and become available to interact with.

**Actual Behavior:**
No models shown. No useful logs in container console that I can see. ENV contains GLOBAL_LOG_LEVEL=DEBUG, and the expected OPENAI_API_BASE_URLS and OPENAI_API_KEYS.

## Environment

- **Open WebUI Version:** v0.1.122

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

[Container Log.txt](https://github.com/open-webui/open-webui/files/15142651/Container.Log.txt)

## Installation Method

Docker, following Docs with API details set through the Web UI. Also tried defining through docker run parameters:
```
docker run -d -p 3000:8080 \
  -v open-webui:/app/backend/data \
  -e OPENAI_API_BASE_URLS="https://api.together.xyz/v1" \
  -e OPENAI_API_KEYS="the_key" \
  --name open-webui \
  --restart always \
  ghcr.io/open-webui/open-webui:main
```

## Additional Information

Same API Base URLs and keys work in another chat app.

**Comment by tjbck** [comment]
Seems like `api.together.xyz` api wasn't directly compatible with openai API spec (model list being directly sent as an array with `/models` endpoint). Just updated the code on our dev branch to add support for `api.together.xyz` at least, let me know if the issue persists!

**Comment by jmstacey** [comment]
@tjbck thanks for speedy fix. I downloaded dev branch and commit 9832e6edba4fd30aff3e30da4c128cfb581f922d does seem to have fixed the issue and both together.ai and groq.com APIs are now working. I'll leave comment open incase you want to close it after the merge.

**Comment by Yanyutin753** [comment]
you can try use oneapi to resolve this problem
