### ISSUE TITLE
feat: Pin Chats

### ISSUE THREAD

**Issue by SurvivaLlama** [open-webui/open-webui#1840]
**Is your feature request related to a problem? Please describe.**
I would like to pin chats. I dont want something I am working on to be lost to the other topics I started.

**Describe the solution you'd like**
When I click on the 3 dots ... I should see the option "Pin". When I select that option that chat stays at the top of the chats.

**Describe alternatives you've considered**
Gemini does this

**Comment by Silentoplayz** [comment]
I fully support this idea. The "Pin Chats" feature you suggest complements the recently introduced "Archive Chats" feature perfectly. On one hand, archiving conversations allows you to remove clutter from your chats navbar list without deleting important conversations. On the other hand, pinning important chats enables you to keep critical conversations at the top of your chats list for easy access. This feature would provide a nice balance between organization and prioritization. The "Pin Chats" feature would be particularly useful for users who need to manage multiple conversations simultaneously, such as project managers, customer support teams, or anyone who needs to keep track of multiple threads.

**Comment by SurvivaLlama** [comment]
Would you limit pinned chats to a specific number of pinned chats? Maybe 3? or allow an unlimited number of pins?

**Comment by tjbck** [comment]
Would having a shortcut for tagging a chat with a 'pinned' tag suffice for your use case?

**Comment by tjbck** [comment]
@SurvivaLlama

**Comment by SurvivaLlama** [comment]
do tags stay at the the chats?

**Comment by tjbck** [comment]
![image](https://github.com/open-webui/open-webui/assets/25473318/26be05fc-6ec4-4a5e-9693-59fdba4229d5)
![image](https://github.com/open-webui/open-webui/assets/25473318/533b6bcf-f99d-47cd-9f71-e1bfe5222b67)


It would look something like this.

**Comment by SurvivaLlama** [comment]
That is not the same thing. However, it does solve the problem (just in a different way).

**Comment by Silentoplayz** [comment]
@tjbck I personally wouldn't mind the solution to use a tag for pinned chats and think that it is an acceptable solution for the time being. Instead of adding the pinned tag manually through the usual 'Add Tag' option, I suggest introducing a newly dedicated 'Pin Chat' button in the 3 dots menu that creates the pinned tag automatically when a chat is pinned, if the tag doesn't already exist from other pinned chats. The pinned tag should remain until all chats are unpinned, at which point it would be removed.

**Comment by SurvivaLlama** [comment]
> @tjbck I personally wouldn't mind the solution to use a tag for pinned chats and think that it is an acceptable solution for the time being. Instead of adding the pinned tag manually through the usual 'Add Tag' option, I suggest introducing a newly dedicated 'Pin Chat' button in the 3 dots menu that creates the pinned tag automatically when a chat is pinned, if the tag doesn't already exist from other pinned chats. The pinned tag should remain until all chats are unpinned, at which point it would be removed. After all though, this is not my open issue. I'd like to hear from @SurvivaLlama on this one.

That works. It just sounds like more work... But what do I know.

**Comment by tjbck** [comment]
![image](https://github.com/open-webui/open-webui/assets/25473318/ba469766-ed88-44c9-b8bb-575a36f2e1f7)
![image](https://github.com/open-webui/open-webui/assets/25473318/ff6fad81-b83f-4d12-ad70-522fb5915f86)


Added to latest dev!

**Comment by ghost** [comment]
@tjbck please also add remove all unpinned chats?
