### ISSUE TITLE
feat: add users from admin panel

### ISSUE THREAD

**Issue by FruitTea2015** [open-webui/open-webui#1844]
**Is your feature request related to a problem? Please describe.**
I'm a teacher in middle school, and I want to create multiple users in batches.

**Describe the solution you'd like**
adding users in batches, and handle multiple requests in parallel when multiple users are in use at the same time

**Comment by justinh-rahb** [comment]
CSV import would be a simple way to import users in bulk, 4 columns:
| Name | Email | Password | Role |
| ---------------- | ------ | ---- | ---- |

**Comment by FruitTea2015** [comment]
@justinh-rahb 
Hello, thank you for your reply. Where can I import csv files to add users in batches? I don't see a button to do this on the WebUI administrator Settings page.

**Comment by justinh-rahb** [comment]
@FruitTea2015 This is not a feature we have as of yet, I was only proposing an idea for how we might be able to implement such.

**Comment by rikhuijzer** [comment]
To be clear, I upvoted this issue for the "add users from admin panel" feature. I could use that as well.

> is a larger conversation but suffice it to say that Ollama backend is not suitable for handling large amounts of users concurrently, unless you have a herd of them.

Would it be fine when using some 3rd party API?

**Comment by Yanyutin753** [comment]
but，This can be implemented through scripts

**Comment by Yanyutin753** [comment]
I have time to write one for you🤩

**Comment by rikhuijzer** [comment]
Thanks @Yanyutin753 for responding. 😄  I have now just used a separate browser and clicked sign up a few times. Worked good enough for me.

**Comment by justinh-rahb** [comment]
> To be clear, I upvoted this issue for the "add users from admin panel" feature. I could use that as well.
> 
> > is a larger conversation but suffice it to say that Ollama backend is not suitable for handling large amounts of users concurrently, unless you have a herd of them.
> 
> Would it be fine when using some 3rd party API?

There's at least one user in our Discord that has deployed their WebUI instance to 500 users, mostly using external APIs (Azure) and a local vLLM inference endpoint as well.

**Comment by tjbck** [comment]
This will be implemented for our next release. I appreciate your patience.

**Comment by tjbck** [comment]
Added to dev branch, will be releasing 0.1.123 soon!

**Comment by rikhuijzer** [comment]
> Added to dev branch, will be releasing 0.1.123 soon!

You are shipping 🚀 Thanks.

Thanks @tjbck  also by the way for making this UI in the first place! I was just now using it and it's great. 😄  The UI is very solid on phone and desktop. It's not getting in the way at all.

**Comment by DarianBrezon** [comment]
大佬，您好！问一下csv中角色字段应该如何填写啊，用户与数字1，空都不可以，无法批量创建用户

**Comment by DarianBrezon** [comment]
大佬，您好！问一下csv中角色字段应该如何填写啊，用户与数字1，空都不可以，无法批量创建用户
