### ISSUE TITLE
BUG Change of OpenAU connection doesn't stick after reboot

### ISSUE THREAD

**Issue by corticalstack** [open-webui/open-webui#1846]
# Bug Report

## Description

**Bug Summary:**
Changed OpenAI API url/key from default `https://api.openai.com/v1` to `https://<external LiteLLM server>/v1`.

On reboot of server, OpenAI API url/key reverted to api.openai.com

## Environment

- **Open WebUI Version:** v0.1.121
- **OS** Ubuntu 22.04.3 LTS
- **Running as Docker container**

Thanks

**Comment by tjbck** [comment]
Duplicate: #1022

**Comment by justinh-rahb** [comment]
Adding this tutorial for persisting it with environment variables:
https://docs.openwebui.com/tutorial/openai

**Comment by corticalstack** [comment]
That's awesome @justinh-rahb , can confirm works setting openai api as follows in docker-compose for open-webui in Portainer, for external LiteLLM:

```
 environment:
      - OPENAI_API_BASE_URLS="http://<my ip>:4000/v1"
      - OPENAI_API_KEYS="sk-<my key>"
```

Thanks!

**Comment by corticalstack** [comment]
Incidentally @justinh-rahb , setting automatic1111 url/default model/image size also don't stick after reboot.

Might this also be solved by setting the appropriate environment variables? Would you know what those are?

Thanks!
