### ISSUE TITLE
Mobile guestures

### ISSUE THREAD

**Issue by RealMrCactus** [open-webui/open-webui#1854]
# Bug Report

## Description

**Bug Summary:**
When you're scrolling through code it still activates the guesture

**Steps to Reproduce:**
Be on mobile and have the ai make you core that's horizontally longer than your screen and try to scroll quickly through it

**Expected Behavior:**
No chat window, code scrolls 

**Actual Behavior:**
Code scrolls but chats open as well 

## Environment

- **Open WebUI Version:** 0.1.122

- **Operating System:** Ubuntu 23.10
- **Browser (if applicable):** Add to home application from chrome on android

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [?] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Screenshots (if applicable):**
https://github.com/open-webui/open-webui/assets/36554881/1017d480-a514-4386-b6dc-fe738439833c

## Installation Method

Docker

**Comment by tjbck** [comment]
Fixed on dev branch.
