### ISSUE TITLE
bug: Shortcut for Deleting Chat Not Working

### ISSUE THREAD

**Issue by barrettgp** [open-webui/open-webui#1859]
# Bug Report

## Description

**Bug Summary:**
When attempting to use the shortcut to delete a chat, (Ctrl/⌘ Shift ⌫) it seems to do nothing other than printing "deleteChat" in the console. 
**Steps to Reproduce:**
Use the shortcut to delete a chat (Ctrl/⌘ Shift ⌫) with a chat in focus

**Expected Behavior:**
A popup to show asking if you want to delete the chat.

**Actual Behavior:**
It prints "deleteChat" in the console

## Environment

- **Open WebUI Version:** [e.g., 0.1.120]
- **Ollama (if applicable):** [e.g., 0.1.30, 0.1.32-rc1]

- **Operating System:** MacOS Sonoma
- **Browser:** Google Chrome

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**None**

## Installation Method

I updated my Docker container to the latest version using the following commands: 
docker pull ghcr.io/open-webui/open-webui:main
docker stop open-webui
docker rm open-webui
docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main

## Additional Information

**None**

**Comment by tjbck** [comment]
Fixed on dev branch.
