### ISSUE TITLE
Truncating or Summarizing Message History to handle Long Conversations for Models with Small context windows 

### ISSUE THREAD

**Issue by shivanipatel7** [open-webui/open-webui#1866]
I'm using a model that has a small context window. I want to either truncate the conversation so only the last few messages are passed into the context or pass in a summarization from the conversation into the context to help with this. Does anyone know the best way to implement this?

**Comment by tjbck** [comment]
Duplicate #1268, Let's continue our discussion there!

**Comment by tjbck** [comment]
Here's a simple context clipping filter enabled by the newly introduced "Functions" feature: https://openwebui.com/f/hub/context_clip_filter Hope this helps!
