### ISSUE TITLE
infra: publish to pypi.org using namespace package

### ISSUE THREAD

**Issue by tcztzy** [open-webui/open-webui#1885]
**Is your feature request related to a problem? Please describe.**
Publish this project to Pypi.org using [namespace package](https://packaging.python.org/en/latest/guides/packaging-namespace-packages/).

**Describe the solution you'd like**
Once it is publish as a namespace like `open_webui`, then third party developer can publish their package like `open_webui.apps.<my_app>`

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by tjbck** [comment]
Github workflow PR welcome!

**Comment by tcztzy** [comment]
I can contribute but It will rename the top level `backend` directory to `open-webui`, would you accept such a big change? And we also need a [Pypi organization account](https://docs.pypi.org/organization-accounts/).

**Comment by tjbck** [comment]
If we can rename the `backend` directory during our workflow that would be ideal.

**Comment by tcztzy** [comment]
it can be done without renaming the directory, but renaming the python imports is required in most cases. For example
https://github.com/open-webui/open-webui/blob/30b053116d6a40fc60dad1766e83ed41ffcb712c/backend/main.py#L20
should be refactored as 
```python
from open_webui.apps.ollama.main import app as ollama_app 
```
and
https://github.com/open-webui/open-webui/blob/30b053116d6a40fc60dad1766e83ed41ffcb712c/backend/main.py#L38
should be refactored as
```python
from open_webui.utils.utils import get_admin_user
```

`apps`/`utils`/`constants`/`config` are very common module names and will conflict with other packages.

**Comment by tcztzy** [comment]
Maybe we should publish it firstly, use `pipx` will install package separated from other, therefore name conflict is not a big problem

**Comment by tjbck** [comment]
I'll prioritise this in the near future!
