### ISSUE TITLE
Edit/Threading Posts

### ISSUE THREAD

**Issue by skyler14** [open-webui/open-webui#1895]
**Is your feature request related to a problem? Please describe.**
Chat GPT has the exceptionally useful threading feature, where you can edit your questions and split onto a new thread. This is very useful for example when you prompt and the llm makes code changes that you dislike and you want the system to ignore existing. There is also alot of room for improvement on the existing implementations that could be done here.

**Describe the solution you'd like**
1. I'd like to be able to edit my question, be able to press an edit button on any previous question I asked and regenerate from context at that answer and previous, and be able to navigate between the threads that this makes. 
2. Additionally, I'd like to be able to then edit the system prompt and/or model (or at least the extra instructions you can provide a model), so that after having my LLM assist me in making all this useful context and answers, I can completely regear it towards using the context it has to solving a problem in a different way. 
3. Finally having a bookmark/pin icon would be awesome, which pins particular breakpoints you like in the threading so you can navigate back to those query parts and be able to easily start a new thread from.  

**Describe alternatives you've considered**
1. Being able to just edit the post and regenerate a new answer, still navigate between histories.
2. Be able to pin a previous prompt, then refer to just all the context before it in a similar way to the #rag system. That way you can just in text refer to a previous breakpoint and then submit your new prompt. Maybe allow for collapsing all answers between the pinned message and that for easy viewing.

**Additional context**
example images though I suspect we're all familiar with these, having and edit button:
![image](https://github.com/open-webui/open-webui/assets/849064/66ff4b48-1174-4547-97f9-a66994945f21)
being able to adjust and submit a new query:
![image](https://github.com/open-webui/open-webui/assets/849064/abd463c4-b828-4254-9120-42d4fd0fddc7)
navigate to various versions of queries:
![image](https://github.com/open-webui/open-webui/assets/849064/763ed644-8f81-410c-ba84-321952f97dea)
With regards to pinning this is a common feature seen in apps like LINE or WhatsApp, clicking the pin bar would show you a list of all the queries you pinned, and this could be placed by the edit button
![image](https://github.com/open-webui/open-webui/assets/849064/62ce0e46-c380-4139-8392-15bfa0b8c8be)
for editing the system prompt this can itself just be another edit button like so
![image](https://github.com/open-webui/open-webui/assets/849064/834fc3ff-9328-4ade-a7c7-e7dd18f44704)

**Comment by tjbck** [comment]
This feature already exists if I'm not mistaken.
