### ISSUE TITLE
feat: switching to completion mode instead of chat

### ISSUE THREAD

**Issue by chrisbward** [open-webui/open-webui#1914]
Hi, sometimes I would like to just run inference without using the chat-based format, especially useful if I need to run a completion.

I've come over from ooba's interface, and they have the option there for reference.

Thanks!

**Comment by justinh-rahb** [comment]
Check the `Playground` interface:

<img width="266" alt="Screenshot 2024-05-02 at 5 10 04 PM" src="https://github.com/open-webui/open-webui/assets/52832301/4449043b-cf78-420a-944f-87ca8dc083ec">

**Comment by chrisbward** [comment]
thanks, but I don't see that in my interface? are you using an older version?

**Comment by chrisbward** [comment]
oh, it's a pop-out from the user button down the bottom left - thanks!

just a UX issue then

**Comment by tjbck** [comment]
Closing in favour of #2000, Let's continue our discussion there!
