### ISSUE TITLE
Enter key doesn't send message

### ISSUE THREAD

**Issue by wanestar** [open-webui/open-webui#1921]
The latest update changes the Enter key function to only move to the next line instead of sending the message. 

While this is interesting, I find using Shift-Enter to send messages works well. However, I would greatly prefer it if the Enter key were used for sending messages, as it feels more intuitive. 

Perhaps adding a setting for this would be a good solution?

Thanks

**Comment by arsaboo** [comment]
Yes, that is the behavior across all UIs. Enter to send and Shift+Enter for the next line.
