### ISSUE TITLE
bug: The text in the model selector menu are invisible

### ISSUE THREAD

**Issue by Eisaichen** [open-webui/open-webui#1934]
# Bug Report

## Description

**Bug Summary:**
In the most recent update v0.1.123 https://github.com/open-webui/open-webui/commit/38ff3209ad2a57d8adb61cd597a7a5f55737ab25

The text in the model selector menu is invisible.
happens on all three available themes, **but only occurs when the sidebar is opened**.

**Steps to Reproduce:**
1. Login to webui, reach the landing page
2. open model selector

**Expected Behavior:**
[Describe what you expected to happen.]
text in the menu were able to see.

**Actual Behavior:**
[Describe what actually happened.]
<img width="953" alt="image" src="https://github.com/open-webui/open-webui/assets/12467320/81961472-b57b-4afe-817c-f1bf5aeaa691">

## Environment

- **Open WebUI Version:** [e.g., 0.1.120]
0.1.123
- **Ollama (if applicable):** [e.g., 0.1.30, 0.1.32-rc1]
0.1.32
- **Operating System:** [e.g., Windows 10, macOS Big Sur, Ubuntu 20.04]
Win11
- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]
Edge

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]
<details>

```
Defaulted container "ollama-webui" out of: ollama-webui, init-postgres (init)
No WEBUI_SECRET_KEY provided
Generating WEBUI_SECRET_KEY
Loading WEBUI_SECRET_KEY from .webui_secret_key
/usr/local/lib/python3.11/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_name" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
/usr/local/lib/python3.11/site-packages/pydantic/_internal/_fields.py:160: UserWarning: Field "model_info" has conflict with protected namespace "model_".

You may be able to resolve this warning by setting `model_config['protected_namespaces'] = ()`.
  warnings.warn(
INFO:     Started server process [1]
INFO:     Waiting for application startup.

  ___                    __        __   _     _   _ ___
 / _ \ _ __   ___ _ __   \ \      / /__| |__ | | | |_ _|
| | | | '_ \ / _ \ '_ \   \ \ /\ / / _ \ '_ \| | | || |
| |_| | |_) |  __/ | | |   \ V  V /  __/ |_) | |_| || |
 \___/| .__/ \___|_| |_|    \_/\_/ \___|_.__/ \___/|___|
      |_|


v0.1.123 - building the best open-source AI user interface.
https://github.com/open-webui/open-webui

INFO:apps.litellm.main:start_litellm_background
INFO:apps.litellm.main:run_background_process
INFO:apps.litellm.main:Executing command: ['litellm', '--port', '14365', '--host', '127.0.0.1', '--telemetry', 'False', '--config', '/app/backend/data/litellm/config.yaml']
INFO:     Application startup complete.
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
INFO:apps.litellm.main:Subprocess started successfully.
```
</details>
**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Installation Method

[Describe the method you used to install the project, e.g., manual installation, Docker, package manager, etc.]

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
Could you try pulling the latest main? Unable to reproduce here.

![image](https://github.com/open-webui/open-webui/assets/25473318/80b6e651-cd94-4e15-a5e2-ccc0a6596b28)

**Comment by tjbck** [comment]
Seems to be a browser specific issue, investigating atm.

**Comment by Eisaichen** [comment]
@tjbck wired.. I just tried on another PC without cache or extension enabled on it, and the bug is still there.

<img width="765" alt="Screenshot 2024-05-02 183011" src="https://github.com/open-webui/open-webui/assets/12467320/2f17f1f0-d99a-41ed-a3be-3ba5115910af">
<img width="820" alt="Untitled" src="https://github.com/open-webui/open-webui/assets/12467320/72dee068-3555-45e6-86b2-277e80e9f1f9">

I'm running a docker container with the "latest" tag.

**Comment by Eisaichen** [comment]
Tried disabling all external backends, using the official openAI API only. the bug is still there.

**Comment by tjbck** [comment]
Just added a possible fix, let me know if the issue persists!

**Comment by Eisaichen** [comment]
@tjbck Thank you for the rapid fix! the fix is effective.
