### ISSUE TITLE
Model select dropdown displays behind the sidebar

### ISSUE THREAD

**Issue by mjtechguy** [open-webui/open-webui#1939]
# Bug Report

## Description

**Bug Summary:**
Model select dropdown displays behind the sidebar

**Steps to Reproduce:**
1. Install OWUI 0.1.32 and connect to ollama
2. Go to chat window and try to select a model
3. Cant see model list until sidebar is collapsed

**Expected Behavior:**
I expect the models to be visible to select from without closing the sidebar

**Actual Behavior:**
Sidebar hides model names

## Environment

- **Open WebUI Version:** 0.1.32
- **Ollama (if applicable):** v0.1.33

- **Operating System:** OWUI running on WSL Ubuntu 22.04 but open on WIndows browser 
- **Browser (if applicable):** Chromium 124.0.6367.91 (Brave)

## Reproduction Details

**Confirmation:**

- [x ] I have read and followed all the instructions provided in the README.md.
- [x ] I am on the latest version of both Open WebUI and Ollama.
- [x ] I have included the browser console logs.
- [x ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
open-webui  | INFO:     192.168.0.1:56196 - "GET /ollama/api/version HTTP/1.1" 200 OK
open-webui  | INFO:     192.168.0.1:41974 - "GET /api/v1/chats/334c8830-ffe0-4e0f-8b63-3f3838384e88 HTTP/1.1" 200 OK
open-webui  | INFO:     192.168.0.1:41974 - "GET /api/v1/chats/334c8830-ffe0-4e0f-8b63-3f3838384e88/tags HTTP/1.1" 200 OK
open-webui  | INFO:     192.168.0.1:41974 - "GET /api/v1/chats/6374e5b0-98c4-4002-8fe8-c90976b1fd07 HTTP/1.1" 200 OK
open-webui  | INFO:     192.168.0.1:41974 - "GET /api/v1/chats/6374e5b0-98c4-4002-8fe8-c90976b1fd07/tags HTTP/1.1" 200 OK
open-webui  | INFO:     192.168.0.1:41974 - "GET /api/v1/chats/24d78147-6f16-4f0c-938e-4a84d2f017a0 HTTP/1.1" 200 OK
open-webui  | INFO:     192.168.0.1:41974 - "GET /api/v1/chats/24d78147-6f16-4f0c-938e-4a84d2f017a0/tags HTTP/1.1" 200 OK
open-webui  | INFO:     192.168.0.1:41974 - "GET /api/v1/chats/93997dff-55a7-493a-a882-1f35eea5e2db HTTP/1.1" 200 OK
open-webui  | INFO:     192.168.0.1:41974 - "GET /api/v1/chats/93997dff-55a7-493a-a882-1f35eea5e2db/tags HTTP/1.1" 200 OK
open-webui  | INFO:     192.168.0.1:57382 - "GET / HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57382 - "GET /_app/immutable/entry/start.03043b3e.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57396 - "GET /_app/immutable/chunks/scheduler.7238b518.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57410 - "GET /_app/immutable/chunks/singletons.0ad53426.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57396 - "GET /_app/immutable/chunks/index.6bf40fed.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57382 - "GET /_app/immutable/entry/app.e0d454d4.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57420 - "GET /_app/immutable/chunks/index.5768aeba.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57420 - "GET /_app/immutable/nodes/0.2000b784.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57420 - "GET /_app/immutable/chunks/index.d6b34b00.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57420 - "GET /_app/immutable/chunks/navigation.fccb995b.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57420 - "GET /_app/immutable/chunks/each.b7dbf2c4.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57420 - "GET /_app/immutable/chunks/Toaster.svelte_svelte_type_style_lang.93775e0f.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57420 - "GET /_app/immutable/chunks/index.6a6efc06.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57382 - "GET /_app/immutable/chunks/index.c5fd21ca.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57396 - "GET /_app/immutable/chunks/index.1873deba.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57410 - "GET /_app/immutable/assets/0.d0791dc7.css HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57434 - "GET /_app/immutable/nodes/1.bd6a6d03.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57442 - "GET /_app/immutable/chunks/stores.0f72e029.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57382 - "GET /_app/immutable/assets/index.f15c51aa.css HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57396 - "GET /_app/immutable/assets/Messages.e8d876d7.css HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57420 - "GET /_app/immutable/assets/2.aa9f4d80.css HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57410 - "GET /_app/immutable/nodes/2.93839ef5.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57434 - "GET /_app/immutable/chunks/index.f1edc29e.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57442 - "GET /_app/immutable/chunks/index.c96f4261.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57396 - "GET /_app/immutable/chunks/index.545bc149.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57382 - "GET /_app/immutable/chunks/index.4e9fd85b.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57420 - "GET /_app/immutable/chunks/index.63ce3869.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57434 - "GET /_app/immutable/chunks/index.9e754bfc.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57410 - "GET /_app/immutable/chunks/Modal.485dfe88.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57442 - "GET /_app/immutable/chunks/dayjs.min.056d298b.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57396 - "GET /_app/immutable/chunks/index.1d4c93a7.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57420 - "GET /_app/immutable/chunks/AdvancedParams.9c68df98.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57434 - "GET /_app/immutable/chunks/ShareChatModal.d10ea67c.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57382 - "GET /_app/immutable/chunks/create.d7af4d12.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57442 - "GET /_app/immutable/chunks/menu-trigger.410969e8.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57396 - "GET /_app/immutable/chunks/Tags.a196c744.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57410 - "GET /_app/immutable/chunks/updater.82b4828f.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57434 - "GET /_app/immutable/chunks/index.76879409.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57420 - "GET /_app/immutable/nodes/3.44ff5ffc.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57382 - "GET /_app/immutable/chunks/index.1315b263.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57442 - "GET /_app/immutable/chunks/AddFilesPlaceholder.7a46d7d4.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57396 - "GET /_app/immutable/chunks/Messages.92bc3659.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57410 - "GET /_app/immutable/chunks/Selector.b05f1f00.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57410 - "GET /manifest.json HTTP/1.1" 200 OK
open-webui  | INFO:     192.168.0.1:57410 - "GET /static/logo.png HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57410 - "GET /api/config HTTP/1.1" 200 OK
open-webui  | INFO:     192.168.0.1:57382 - "GET /_app/immutable/chunks/translation.4c741fc2.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:57410 - "GET /api/v1/auths/ HTTP/1.1" 200 OK
open-webui  | INFO:     192.168.0.1:57410 - "GET /api/changelog HTTP/1.1" 200 OK
open-webui  | INFO:apps.ollama.main:get_all_models()
open-webui  | INFO:     192.168.0.1:57410 - "GET /ollama/api/tags HTTP/1.1" 200 OK
open-webui  | INFO:apps.openai.main:get_all_models()
open-webui  | INFO:apps.openai.main:get_all_models()
open-webui  | INFO:     192.168.0.1:57410 - "GET /openai/api/models HTTP/1.1" 200 OK
open-webui  | INFO:     192.168.0.1:57410 - "GET /litellm/api/v1/models HTTP/1.1" 200 OK
open-webui  | INFO:     192.168.0.1:57410 - "GET /api/v1/modelfiles/ HTTP/1.1" 200 OK
open-webui  | INFO:     192.168.0.1:57410 - "GET /api/v1/prompts/ HTTP/1.1" 200 OK
open-webui  | INFO:     192.168.0.1:57410 - "GET /api/v1/documents/ HTTP/1.1" 200 OK
open-webui  | INFO:     192.168.0.1:57410 - "GET /api/v1/chats/tags/all HTTP/1.1" 200 OK
open-webui  | INFO:apps.ollama.main:get_all_models()
open-webui  | INFO:     192.168.0.1:57382 - "GET /api/v1/chats/ HTTP/1.1" 200 OK
open-webui  | INFO:     192.168.0.1:57382 - "GET /static/favicon.png HTTP/1.1" 200 OK
open-webui  | INFO:     192.168.0.1:57410 - "GET /ollama/api/tags HTTP/1.1" 200 OK
open-webui  | INFO:apps.openai.main:get_all_models()
open-webui  | INFO:apps.openai.main:get_all_models()
open-webui  | INFO:     192.168.0.1:57410 - "GET /openai/api/models HTTP/1.1" 200 OK
open-webui  | INFO:     192.168.0.1:57442 - "GET /ollama/api/version HTTP/1.1" 200 OK
open-webui  | INFO:     192.168.0.1:57410 - "GET /litellm/api/v1/models HTTP/1.1" 200 OK
open-webui  | INFO:     192.168.0.1:58616 - "GET /_app/immutable/nodes/11.bb090233.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:35696 - "GET /_app/immutable/chunks/languages.26077fee.js HTTP/1.1" 304 Not Modified
open-webui  | INFO:     192.168.0.1:35696 - "GET /ollama/api/version HTTP/1.1" 200 OK
open-webui  | INFO:     192.168.0.1:35696 - "GET /api/version/updates HTTP/1.1" 200 OK

**Screenshots (if applicable):**
![image](https://github.com/open-webui/open-webui/assets/29070994/11716f9b-3cb5-4246-a201-1a64bb6ada2e)

![image](https://github.com/open-webui/open-webui/assets/29070994/7e798630-16f3-47cd-b80b-ce208e43ed68)

## Installation Method

Docker Compose

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
Fixed with #1934
