### ISSUE TITLE
The model drop-down list shows an error

### ISSUE THREAD

**Issue by alex13by** [open-webui/open-webui#1940]
! [image](https://github.com/open-webui/open-webui/assets/121482598/cb588955-2e82-47f7-b61f-849f3440062b)

In the latest version of openwebui, 0.1.123, a docker update revealed a display issue with the list of existing models, where name alignment can only see the rightmost few characters

os:win11 23H2
Browser:124.0.6367.61
openwebui: 0.1.123

**Comment by tjbck** [comment]
Fixed with #1934
