### ISSUE TITLE
Ability to download new models are gone

### ISSUE THREAD

**Issue by zono50** [open-webui/open-webui#1947]
On the latest version of open-webui, and when i go to settings > Models, this is the only option I have

![image](https://github.com/open-webui/open-webui/assets/8764705/f0d97d5e-fc87-4dfb-b54c-23b87af657d0)

I remember on a previous installation, i had the ability to download models from the webui. Not sure why that is not showing here.

Installed this using docker command - docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main

OS is Arch Linux

Any help would be greatly appreciated

**Comment by justinh-rahb** [comment]
What does this show?
```bash
ss -lntp | grep 11434
```

**Comment by zono50** [comment]
LISTEN 0      4096       127.0.0.1:11434      0.0.0.0:*

**Comment by justinh-rahb** [comment]
> LISTEN 0      4096       127.0.0.1:11434      0.0.0.0:*                                             
> 

Ya, the issue is Ollama not listening to all interfaces, only localhost.

**Comment by zono50** [comment]
That was it! thanks for the assistance
