### ISSUE TITLE
feat: Show raw context length in the generation info popup

### ISSUE THREAD

**Issue by notasquid1938** [open-webui/open-webui#1950]
SInce the ollama api returns the raw tokens of the context, counting these to display a raw context length in the generation info could be useful for those wanting to test large context models/see exactly how many tokens the model used.

Edit: Misunderstood Ollama api

**Comment by tjbck** [comment]
<img width="385" alt="image" src="https://github.com/open-webui/open-webui/assets/25473318/1cf8c343-9345-4e29-a0b6-a7f99a9ca6d2">

**Comment by notasquid1938** [comment]
Are you referring to prompt_eval_count? I tried searching the repo but couldn't find any reference to what it means.

**Comment by tjbck** [comment]
Ollama doc: https://github.com/ollama/ollama/blob/main/docs/api.md

**Comment by notasquid1938** [comment]
Thanks for the link
