### ISSUE TITLE
feat: context warning message

### ISSUE THREAD

**Issue by notasquid1938** [open-webui/open-webui#1952]
I decided to test gradient's 1 million context llama3 model by adjusting the context parameter accordingly. However, as can be seen in this server log I run out of memory trying to store all this context:

> llama_new_context_with_model: n_ctx      = 10240000
> llama_new_context_with_model: n_batch    = 512
> llama_new_context_with_model: n_ubatch   = 512
> llama_new_context_with_model: freq_base  = 10000.0
> llama_new_context_with_model: freq_scale = 1
> ggml_cuda_host_malloc: warning: failed to allocate 231424.00 MiB of pinned memory: out of memory
> ggml_backend_cpu_buffer_type_alloc_buffer: failed to allocate buffer of size 242665652256
> llama_kv_cache_init: failed to allocate buffer for kv cache
> llama_new_context_with_model: llama_kv_cache_init() failed for self-attention cache
> llama_init_from_gpt_params: error: failed to create context with model 'C:\Users\\.ollama\models\blobs\sha256-02c4f7e34d04dcde88f545a41bd2ea829645794873082a938f79b9badf37075d'
> {"function":"load_model","level":"ERR","line":410,"model":"C:\\Users\\.ollama\\models\\blobs\\sha256-02c4f7e34d04dcde88f545a41bd2ea829645794873082a938f79b9badf37075d","msg":"unable to load model","tid":"10004","timestamp":1714759655}

The issue I had was the openwebui didn't show or explain this error. It just tries to generate the response forever before erroring out with a message about connection issues to ollama. It would be very helpful if the ui could pop up a message indicating your context length caused an out of memory issue, preferably with the amount of memory it was trying to use to make it easy for users to tune how much context their system can handle.

**Comment by edwardochoaphd** [comment]
Would there be an issue with Settings>Advanced Parameters>Context Length?
I'm also getting errors possibly running out of memory ... 
Would an extra zero be added to the user's setting when sent from OpenWebUI? (i.e., not user error, possibly a bug in OpenWebUI?)
the above user wants to test for 1M, however the extra zero changes their setting to 10M?...
![extraZeroIssue](https://github.com/open-webui/open-webui/assets/20013196/85e3b0d9-4ad3-4362-82eb-7d347b251bb4)

**Comment by justinh-rahb** [comment]
I am in favour of having an environment variable to disable the ability for users to change the `num_ctx` parameter from default.

**Comment by Cdddo** [comment]
The UI should definitely show how much context is available. Maybe as percentage if not in tokens

**Comment by justinh-rahb** [comment]
> The UI should definitely show how much context is available. Maybe as percentage if not in tokens

Not practical to just add it, as one does, or it would have been already. Every model uses a different tokenizer, and it's not always possible to reliably determine it from the model name alone.
