### ISSUE TITLE
bug: Model selection drop down covered by left side hamburger menu

### ISSUE THREAD

**Issue by aniqueta** [open-webui/open-webui#1954]
# Bug Report

## Description

**Bug Summary:**
Model selection drop down covered by left side hamburger menu when visiting Open-WebUI on a device with a large window. 

**Steps to Reproduce:**
1. Navigate to Open-WebUI in browser on a computer with a large screen
2. Have the browser in full-screen mode or with a large window
3. Click the drop down on the right to select model

**Expected Behavior:**
Models available for selection are visible. 

**Actual Behavior:**
Models available for selection are not visible, but are hiding under the hamburger menu per screenshot

<img width="1723" alt="image" src="https://github.com/open-webui/open-webui/assets/65845439/291db090-db61-4e3d-9551-6ca8305ebef3">

## Environment

- **Open WebUI Version:** 0.1.123
- **Ollama (if applicable):**  0.1.32

- **Operating System:** macOS 14.4.1
- **Browser (if applicable):** Safari 17.4.1 (19618.1.15.11.14)

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

See above.

**Browser Console Logs:**
n/a

**Docker Container Logs:**
n/a

**Screenshots (if applicable):**

See above.

## Installation Method

Docker

## Additional Information

n/a

**Comment by tjbck** [comment]
Fixed with https://github.com/open-webui/open-webui/issues/1934

**Comment by aniqueta** [comment]
Sorry to miss this was already reported and fixed!
