### ISSUE TITLE
bug: Title auto-generation sometimes includes quotation marks at start and finish

### ISSUE THREAD

**Issue by aniqueta** [open-webui/open-webui#1955]
# Bug Report

## Description

**Bug Summary:**
Very minor issue. I haven't figured out the pattern, but with certain models, the title auto-generation has titles that have quotation marks at start and finish. I think the expected behavior is no quotes. 

I tested the following:
- llama3:latest - has quotes, buggy(?) behavior
- mistra-openorca:latest - no quotes, expected behavior
- claude-3-opus-20240229 - no quotes, expected behavior
- gpt-4 - has quotes, buggy(?) behavior

**Steps to Reproduce:**
1. Settings: title auto-generation on, using current model (both local and external)
2. Using the llama3 model (or gpt-4), start a chat.

**Expected Behavior:**
Title is generated without quotes e.g., Interesting question vs. "Interesting question"

**Actual Behavior:**
Title is generated without quotes e.g., "Interesting question"

## Environment

- **Open WebUI Version:** 0.1.123
- **Ollama (if applicable):**  0.1.32

- **Operating System:** macOS 14.4.1
- **Browser (if applicable):** Safari 17.4.1 (19618.1.15.11.14)

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

See above.

**Browser Console Logs:**
n/a

**Docker Container Logs:**
n/a

**Screenshots (if applicable):**

n/a

## Installation Method

Docker

**Comment by tjbck** [comment]
#1692
