### ISSUE TITLE
enhancement: non-english youtube rag

### ISSUE THREAD

**Issue by atassis** [open-webui/open-webui#1960]
# Bug Report

## Description

**Bug Summary:**
If you use RAG for youtube without english translation, but with another language provided- request fails with an error from `youtube-transcript-api`

**Steps to Reproduce:**
try to execute next prompt `#https://www.youtube.com/watch?v=FuRem6-sTmQ`

**Expected Behavior:**
prefetch the list of languages of the video from the same package with 
```python
from youtube_transcript_api import YouTubeTranscriptApi

transcript_list = YouTubeTranscriptApi.list_transcripts(YoutubeLoader.extract_video_id(video_url)
languages = list(enumerate(transcript_list))
print(languages[0][1].language_code)
```

**Actual Behavior:**
See the toast error after several seconds.

## Environment

- **Open WebUI Version:** 0.1.123
- **Ollama (if applicable):** 0.1.32

- **Operating System:** Fedora 39 (both client and server, different machines)
- **Browser (if applicable):** Chrome (version doesn't matter)

## Reproduction Details

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [X] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
I'll provide if needed, seems irrelevant

**Docker Container Logs:**
I'll provide if needed, seems irrelevant

**Screenshots (if applicable):**
![image](https://github.com/open-webui/open-webui/assets/5769345/f63f054d-87ed-4b81-88aa-160822c89171)

## Installation Method

Docker

## Additional Information

The problem is that YoutubeLoader from langchain doesn't handle by himselves the verification that requested (or default `'en'`) language is provided by the video. We need to handle it by ourselves.

**Comment by grigio** [comment]
@tjbck 
![Screenshot from 2024-05-09 15-59-15](https://github.com/open-webui/open-webui/assets/8074/ef2076dd-abf4-4951-98c1-5ab1184bec5f)

I've updated but I always get a similar error

**Comment by grigio** [comment]
> @grigio You're still requesting `en`, change this to `it`:
> 
Thanks, it works. I was thinking that it was managed by the UI language

**Comment by atassis** [comment]
What about trying to make a separate toggle with automatic language recognition? With the code suggested by me.
