### ISSUE TITLE
Youtube RAG seems to not support non-English videos

### ISSUE THREAD

**Issue by grigio** [open-webui/open-webui#1974]
@tjbck The YouTube RAG is fantastic! It works on English videos but It seems it can't download the subtitles when the native language is different (but the subtitles are available

![Screenshot from 2024-05-04 21-33-40](https://github.com/open-webui/open-webui/assets/8074/c7719672-3e75-43d5-955e-78ef3faa76a8)

**Comment by tjbck** [comment]
Duplicate #1960
