### ISSUE TITLE
enhancement: Allow selection of OpenAI TTS models

### ISSUE THREAD

**Issue by jmtatsch** [open-webui/open-webui#1978]
OpenAI allows to choose from two model variants, tts-1 and tts-1-hd.

https://help.openai.com/en/articles/8555505-tts-api

open-webui defaults to tts-1 now and does not allow to configure this in the UI.

It would be great if we could choose between tts-1, tts-1-hd or potentially other model names.

That would allow voice cloning with https://github.com/matatonic/openedai-speech/ to work

**Comment by Yanyutin753** [comment]
i want to try and feat it

**Comment by Yanyutin753** [comment]
it’s done. Wait. Update the translation
