### ISSUE TITLE
Title Auto-Generation Doesn’t Respect Custom Context Length

### ISSUE THREAD

**Issue by isr431** [open-webui/open-webui#1980]
# Bug Report

## Description

**Bug Summary:**
When a custom context length is set, it isn't respected by title auto-generation. As a result, the model is being re-loaded entirely with the default context when generating a title, adding unnecessary delay.

**Steps to Reproduce:**
Select 'Settings' > 'General' > 'Advanced Parameters' and set 'Context Length' to any value other than the default of 2048. Turn on title auto-generation.

**Expected Behavior:**
Title auto-generation should respect the custom context length, removing the need to reload the model.

**Actual Behavior:**
Title auto-generation did not respect the custom context length, causing the model to be reloaded with the default context of 2048.

## Environment

- **Open WebUI Version:** v0.1.123
- **Ollama (if applicable):** 0.1.33

- **Operating System:** Windows 11
- **Browser (if applicable):** Chrome Version 124.0.6367.119

## Reproduction Details

**Confirmation:**

- [X ] I have read and followed all the instructions provided in the README.md.
- [X ] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Installation Method

Open WebUI was installed using Docker.

## Additional Information

Was able to confirm issue by checking Ollama server logs.

**Comment by tjbck** [comment]
Should be fixed on our dev branch! Let us know if the issue persists!
