### ISSUE TITLE
Unable To Connect to Automatic1111 API | Images

### ISSUE THREAD

**Issue by Vishnubathala** [open-webui/open-webui#1981]
I've tried so many way running automatic running inside docker, windows, wsl doesn't matter updated open webui to latest version I get same error 

Error : 
Something went wrong :/ HTTPConnectionPool(host='127.0.0.1', port=7860): Max retries exceeded with url: / (Caused by NewConnectionError('<urllib3.connection.HTTPConnection object at 0x7f9bfcad2cd0>: Failed to establish a new connection: [Errno 111] Connection refused'))
![image](https://github.com/open-webui/open-webui/assets/30683908/7780f67c-d9aa-41bc-aafe-c9b53fb9fb60)

Running as docker inside WSL2 below is my argument
docker run -d -p 3000:8080   --add-host=host.docker.internal:host-gateway   -v open-webui:/app/backend/data   --name open-webui   --restart always   ghcr.io/open-webui/open-webui:main

Can someone please help why it is not letting setup a connection.

**Comment by justinh-rahb** [comment]
Use `host.docker.internal` instead of `127.0.0.1` or `localhost`.

https://docs.openwebui.com/faq#q-how-do-i-make-my-hosts-services-accessible-to-docker-containers

**Comment by Vishnubathala** [comment]
Amazing! just like that Legend thanks for the fix
