### ISSUE TITLE
Doesn't find the model installed locally

### ISSUE THREAD

**Issue by Solypsismo** [open-webui/open-webui#1986]
# Bug Report

## Description
I have installed locally on my computer phi3. I am using kubuntu 24.04 as OS. When in the CLI i exec ollama run phi3 it works normally, but when i run the container it doesn't find the model. In the console i get this error message 
GET http://localhost:3000/ollama/api/version [HTTP/1.1 500 Internal Server Error 4ms]
Object { detail: "WebUI could not connect to Ollama" } detail: "WebUI could not connect to Ollama"

**Bug Summary:**
[Provide a brief but clear summary of the bug]

**Steps to Reproduce:**
[Outline the steps to reproduce the bug. Be as detailed as possible.]

**Expected Behavior:**
Find the model installed on my machine.

**Actual Behavior:**
Doesn't fine the model i have installed on my machine.

## Environment

- **Operating System:** Kubuntu 24.04
- **Browser (if applicable):** Firefox

## Reproduction Details

**Confirmation:**

- [ x ] I have read and followed all the instructions provided in the README.md.
- [ x ] I am on the latest version of both Open WebUI and Ollama.
- [ x ] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
GET http://localhost:3000/ollama/api/version [HTTP/1.1 500 Internal Server Error 4ms]
Object { detail: "WebUI could not connect to Ollama" } detail: "WebUI could not connect to Ollama"

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Installation Method

[Describe the method you used to install the project, e.g., manual installation, Docker, package manager, etc.]

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by YO-SC** [comment]
I am having the same issue, was it solved. If so, how? Thanks
