### ISSUE TITLE
Make signup/login optionnal with a docker envar

### ISSUE THREAD

**Issue by beeksiwaais** [open-webui/open-webui#2028]
**Is your feature request related to a problem? Please describe.**
Currently, the signup/login process is mandatory when using the tool, which can be cumbersome for users who want to quickly test or deploy it without going through the signup process.

**Describe the solution you'd like**
I propose making the signup/login process optional by introducing a Docker environment variable. This would allow users to bypass the signup/login step if they choose to do so, enhancing flexibility and ease of use.

**Describe alternatives you've considered**
One alternative could be to provide a separate lightweight version of the tool that doesn't require signup/login. However, this could lead to maintenance challenges in managing two different versions of the tool.

**Additional context**
This feature would significantly improve the user experience for developers and testers who frequently spin up instances of the tool for various purposes, streamlining the setup process and saving time.

**Comment by tjbck** [comment]
Duplicate #1898
