### ISSUE TITLE
enhancement: Improve RAG scalability

### ISSUE THREAD

**Issue by bucovaina** [open-webui/open-webui#2044]
**Is your feature request related to a problem? Please describe.**
I want to export hundreds/thousands of documents to be embedded. Then I want to use them to provide help if I want to retrieve something about those documents. As in: "I want to upgrade our ESXi servers, what do I need to check before I do that". Or another prompt example: "I want to add a user to a project mailinglist. We have a script for that, but I forgot its name, can you tell me and create a short example how to do it?" (Last example implies the script itself is also embedded). Then the RAG implementation should make sure to first look at the local documents, there could be procedures that are company specific, not to be found in any LLM.

If I want to do that now, it's possible with tagging a document. But that requires a user to know in which document the information is located. So the closest I get is tagging a collection of documents (Like #usermanagement or #vsphere, ... ) but if the collection grows too large - which it quicly does - the context window of the LLM is usually too small to remember what it just read. Mostly the LLM replies with a generic answer, or something like: "the provided context does not seem to be relevant to your question"

**Describe the solution you'd like**
When I've embedded a bunch of text files (hundreds/thousands), I'd like to be able to let RAG do the work and if my prompt alone is specific enough, it'll find the relevant information. This without the need to tag a specific document. Tagging could perhaps still be possible if you want to limit the search, but should be optional, not required.

**Describe alternatives you've considered**
None

**Additional context**
I'm a SysAdmin, we have documentation in Confluence, I'd like to export it all to txt files, then import with Open WebUI and have a documents folder to embed all the txt files.

EDIT: forgot to mention: Thanks for your great work already, I love Open WebUI, fantastic software!!

**Comment by defaultsecurity** [comment]
We would also love this feature for our thousands of text files.

Could Open WebUI use LlamaIndex embeddings?
https://docs.llamaindex.ai/en/stable/examples/embeddings/ollama_embedding/

### Could there be a LlamaIndex embeddings selector next to the model selector? 
We would be able to combine any embedding with any model. Could that work? That would be awesome.

_I am so happy that this project exists. You are true pioneers._

**Comment by tjbck** [comment]
Related: https://github.com/open-webui/pipelines

**Comment by tjbck** [comment]
Closing in favour of https://github.com/open-webui/open-webui/issues/3527, Let's continue our discussion there!
