### ISSUE TITLE
feat: improved conversation management

### ISSUE THREAD

**Issue by cwallace** [open-webui/open-webui#2065]
**Problem:**
I start several dozen conversations, sometimes over a hundred per day. When I need to clean up my chats, I have two options:

1. Click to More, Delete, Confirm on each old chat. That is 36 clicks to delete a dozen conversations.
2. Go to settings and delete all chats. However, this also deletes archived chats, which I may want to keep.

**Proposed solution:**
Multi-conversation management: Implement the ability to select multiple conversations at once and then perform batch actions such as tagging, archiving, or deleting them.

Archived chat handling: Ensure that deleting all chats does not include archived messages. If this is intentional, then adding the ability to "lock" conversations to prevent them from being deleted would be a valuable feature.

**Example workflow:**
1. User clicks a "select" button at the top of the conversation list.
2. User selects multiple conversations from the list or click "select all".
3. User can then choose to archive, tag, or delete the selected conversations in a single action.

**Benefit:**
This feature would greatly improve the user experience for users who manage a large number of conversations on a daily basis. It would provide a more efficient way to organize and maintain their chat history, while ensuring that important archived conversations are not accidentally deleted.

![image](https://github.com/open-webui/open-webui/assets/713498/8167aa45-05de-4ff4-a91b-d783b43b41fe)

**Comment by AdaptiveStep** [comment]
Yeah, It would be cool if you could group them up in "folders". LLM Studio has a really nice feature where you can "fork" a conversation. This way a base conversation can work as a starting point.

**Comment by tjbck** [comment]
@AdaptiveStep forking conversation feature has been requested before but I’m struggling to see its utility when conversation branching feature already exists. Am I missing something here? I’d like to hear your opinion!

**Comment by red-co** [comment]
wanted a folder structure, I looked at a lot of front ends and found that none of them had folder structure except stupid tavern.

**Comment by thiswillbeyourgithub** [comment]
> @AdaptiveStep forking conversation feature has been requested before but I’m struggling to see its utility when conversation branching feature already exists. Am I missing something here? I’d like to hear your opinion!

I think librechat's docs neatly integrates forking in a way that seems very satisfactory to me. Here's the link : https://www.librechat.ai/docs/user_guides/fork

**Comment by lehhair** [comment]
Same here, wish there was a feature to multi-select conversations and then delete them 😭

**Comment by silentoplayz** [comment]
> Same here, wish there was a feature to multi-select conversations and then delete them 😭

To quickly delete unwanted chats, hold down the Left Shift key on your keyboard while hovering over a chat title in the sidebar. Then, simply left-click on the Delete icon to remove the chat instantly. However, please note that this method still requires an individual click for each chat deletion - it doesn't allow you to delete multiple chats at once.

**Comment by thiswillbeyourgithub** [comment]
> > Same here, wish there was a feature to multi-select conversations and then delete them 😭
> 
> To quickly delete unwanted chats, hold down the Left Shift key on your keyboard while hovering over a chat title in the chat sidebar. Then, simply left-click on the Delete icon to remove the respective chat instantly. However, please note that this method still requires an individual click for each chat deletion - it doesn't allow you to delete multiple chats at once.

Neat! I didn't know that, maybe it's not documented? In any case it can't be done on mobile right?

**Comment by silentoplayz** [comment]
> > > Same here, wish there was a feature to multi-select conversations and then delete them 😭
> > 
> > 
> > To quickly delete unwanted chats, hold down the Left Shift key on your keyboard while hovering over a chat title in the chat sidebar. Then, simply left-click on the Delete icon to remove the respective chat instantly. However, please note that this method still requires an individual click for each chat deletion - it doesn't allow you to delete multiple chats at once.
> 
> Neat! I didn't know that, maybe it's not documented? In any case it can't be done on mobile right?

To my **absolute surprise**, I've just found out that it **DOES** (or at least **CAN**) work on mobile devices. My test device for mobile is my iPhone 13 Pro. What I did was open up the chat navigation bar and tapped the search bar so that my keyboard could be invoked. Once the keyboard was triggered, you can press and hold down on the shift key. Once held down for about a second, this will show you the archive and delete icons respectively on a chat shown in view. You can then scroll through and tap on any chat in the chat navbar and delete easily. Note that you could hide the keyboard after holding down on the Shift key for about a second.
