### ISSUE TITLE
Something went wrong :/ Oops! The URL you provided is invalid.

### ISSUE THREAD

**Issue by seasoncool** [open-webui/open-webui#2066]
# Bug Report

## Description

**Bug Summary:**
Upload intranet website address failed.

**Steps to Reproduce:**
1. Upload any intranet website like #http://10.136.218.50:50007/upload/2024-04/test_data.json
2. Press Enter button
3. Check the error

**Expected Behavior:**
The website should be uploaded successfully  and  this feature was available in previous versions.

**Actual Behavior:**
Something went wrong :/ Oops! The URL you provided is invalid.

## Environment

- **Open WebUI Version:** [ v0.1.123]
- **Ollama (if applicable):** [0.1.33]

- **Operating System:** [ Ubuntu 20.04]
- **Browser (if applicable):** [Chrome 100.0]

## Logs and Screenshots

![image](https://github.com/open-webui/open-webui/assets/6467295/7645e5e3-3c87-4221-9cb3-a771edd62ff9)

**Browser Console Logs:**

![image](https://github.com/open-webui/open-webui/assets/6467295/3efa0d8f-36e8-4cd8-8328-5e1db61e5a78)

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

![image](https://github.com/open-webui/open-webui/assets/6467295/f07f6189-a605-4bcb-9875-355a8e7e117a)

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Installation Method

[Describe the method you used to install the project, e.g., manual installation, Docker, package manager, etc.]

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by justinh-rahb** [comment]
Use environment variable `ENABLE_LOCAL_WEB_FETCH=true` to allow RAG to fetch from private IP space. Default is `false`, this is a protection against SSRF attacks against the server's local network(s).

**Comment by thiswillbeyourgithub** [comment]
I'm encountering this in 0.8.12, the env var does not fix it.
