### ISSUE TITLE
Feature Request: Cost Reduction \ Chat Context

### ISSUE THREAD

**Issue by spammenotinoz** [open-webui/open-webui#2074]
Brilliant project, but currently using another project as when using this one my API costs are considerably higher.

High API Usage Costs with Some Users who do not appreciate how API's work.

- Ability to truncate conversation history by (n) messages. eg: 10.  This avoids the entire conversation that may contain irrelevant information back to the LLM.  Typically results is a large speed boost and cost reduction due to significant token reduction.

**Describe alternatives you've considered**
- User education (training my children) to regularly start new conversations
- Training users to start a new conversation when finished with embeddings.

**Additional context**
No modifications to GUI

**Comment by justinh-rahb** [comment]
I too had some expensive months due to people putting everything in the same conversation. The solution was user training: telling them to start new threads for new topics.

**Comment by spammenotinoz** [comment]
My bad, this feature is already in "Advanced".

**Comment by GrayXu** [comment]
@spammenotinoz 
hi, how do you make modifications in "Advanced"? It seems there's only `Context Length` related to this, but even when I set it to 1, I can see the full context being used for each interaction (the single token consumption keeps increasing).  
thanks!
