### ISSUE TITLE
Feature: Embeddings Optimizer (Prompt Rephraser)

### ISSUE THREAD

**Issue by spammenotinoz** [open-webui/open-webui#2075]
Brilliant project, but currently using another project as when using this one my API costs are considerably higher.

High API Usage Costs with embeddings.

- Ability to send embeddings to a REPHRASER (lower cost model) before sending the relevant tokens to the users chosen model.
Typically this can have a major speed improvement and cost reduction for premium \ large models.

**Describe alternatives you've considered**
- Using free high-performance services like Groq

**Additional context**
Example of a Rephraser and Reranker as used on another project.  This pull was not merged into the product, but works extremely well.
I do not use the Reranker jusr the Rephraser.
[No modifications to GUI](https://github.com/mckaywrigley/chatbot-ui/pull/1535/files)

**Comment by Yanyutin753** [comment]
Hey dude, with a free high-performance service like Groq, you can use [one-api] (https://github.com/songquanpeng/one-api) to sum it up and then use it in open webui

**Comment by spammenotinoz** [comment]
> @spammenotinoz Hey dude, with a free high-performance service like Groq, you can use [one-api] (https://github.com/songquanpeng/one-api) to sum it up and then use it in open webui

Hi I already use one-api for another project that already has the "sum it up feature".  I don't use one-api here, as litellm already load-balances multiple API keys.
