### ISSUE TITLE
enhancement: chat history pagination (infinite scroll)

### ISSUE THREAD

**Issue by bannert1337** [open-webui/open-webui#2078]
# Bug Report

## Description

**Bug Summary:**
When importing and loading a large number of chat sessions into Open WebUI, the application experiences significant performance degradation, causing the interface to freeze temporarily. This issue seems related to the side-panel attempting to load all chat sessions simultaneously.

**Steps to Reproduce:**
1. Export a large set of ChatGPT chat sessions.
2. Import these sessions into Open WebUI.
3. Access the Open WebUI to observe the loading process.
4. Notice that the interface freezes for a duration, particularly when the side-panel attempts to load all chats.

**Expected Behavior:**
The interface should remain responsive and load chat sessions smoothly without causing the entire application to freeze, regardless of the number of chats being loaded.

**Actual Behavior:**
The interface freezes temporarily when trying to load a large number of chat sessions at once, significantly affecting user experience and accessibility.

## Environment

- **Open WebUI Version:** 0.1.123
- **Ollama (if applicable):** 0.1.32

- **Operating System:** Debian 12
- **Browser (if applicable):** Floorp 11.12.2 (64-Bit)

## Reproduction Details

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [X] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Additional Information

One possible improvement could be the implementation of pagination or lazy loading for the chat sessions to avoid overwhelming the browser's capabilities by attempting to load extensive data simultaneously.

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by lukestanley** [comment]
This should probably be split into separate issues. Importing ChatGPT data happens via the frontend right now and it doesn't show it's status at all, you'd need to open the browser console to see the upload status. Every conversation has it's own POST request. Pagination of the conversation list is a separate issue from the import issues. @tjbck

**Comment by bannert1337** [comment]
The import was successful. After import, the side panel loads all chats at once, therefore freezing for some seconds.
