### ISSUE TITLE
Update the Ukrainian translation files

### ISSUE THREAD

**Issue by SimonOriginal** [open-webui/open-webui#2103]
Update the Ukrainian translation files. 

Link to the Google Drive file: https://drive.google.com/file/d/1fT8otcb7dY8Hr1IqzoWXesmQGrMpUtoE/view?usp=sharing

**Comment by justinh-rahb** [comment]
@SimonOriginal we're going to need to insist on self-submitted PRs unless someone would like to volunteer their time to put this in on your behalf. There are countless tutorials online for how to submit PRs to projects, and I'm sure we can probably meet you halfway to fix any issues if you can at least get it submitted.

**Comment by justinh-rahb** [comment]
Someone's got your back:

- #2104
