### ISSUE TITLE
youtube rag error

### ISSUE THREAD

**Issue by bboysoulcn** [open-webui/open-webui#2120]
# Bug Report

## Description

**Bug Summary:**
youtube rag error 

video url 

`https://www.youtube.com/watch?v=frcird_ffyc`

**Steps to Reproduce:**
error information
```bash
ERROR:apps.rag.main:The content provided is empty. Please ensure that there is text or data present before proceeding.
Traceback (most recent call last):
  File "/app/backend/apps/rag/main.py", line 532, in store_youtube_video
    store_data_in_vector_db(data, collection_name, overwrite=True)
  File "/app/backend/apps/rag/main.py", line 618, in store_data_in_vector_db
    raise ValueError(ERROR_MESSAGES.EMPTY_CONTENT)
ValueError: The content provided is empty. Please ensure that there is text or data present before proceeding.
```

`INFO:     103.143.161.60:0 - "POST /rag/api/v1/youtube HTTP/1.1" 400 Bad Request`

## Environment

`ghcr.io/open-webui/open-webui:0.1.124`

**Comment by justinh-rahb** [comment]
This feature relies on the presence of embedding closed captions or transcription to function. Your provided video hasn't got any:

![Screenshot 2024-05-08 at 11 17 41 PM](https://github.com/open-webui/open-webui/assets/52832301/3984ab51-3217-4d61-8c7e-caed25dca799)
