### ISSUE TITLE
feat: allow anonymous use (disable login page)

### ISSUE THREAD

**Issue by oe3gwu** [open-webui/open-webui#2133]
**Is your feature request related to a problem? Please describe.**
no

**Describe the solution you'd like**
I am using ollama with the webui at home. I dont want a login page at the startup. I just want to use the chatbot and therefore I want to disable the login function completely.

**Describe alternatives you've considered**
Using accounts I tried, but there are issues handling them, especially on tablets.

**Additional context**
This is a family option. I do not host a public website. Therefore I know this is not really a priority and I do respect all the devs. It would be just nice to have. Maybe an ENV Variable that disables this function or so. I dont know.

**Comment by chawza** [comment]
https://github.com/open-webui/open-webui/issues/2133#issuecomment-2102237608

this is not usefull. I want my app to be secured, but one of my chat to be shared easily

@tjbck will such feature be implemented? I would love to help with this 🙏
