### ISSUE TITLE
bug: Sign-in problem when WEBUI_AUTH_TRUSTED_EMAIL_HEADER is enabled

### ISSUE THREAD

**Issue by hkng** [open-webui/open-webui#2138]
# Bug Report

## Description
Sign-in problem after upgrade to v0.1.124 and  WEBUI_AUTH_TRUSTED_EMAIL_HEADER is enabled

**Bug Summary:**

After upgrade to v0.1.124 and WEBUI_AUTH_TRUSTED_EMAIL_HEADER is set, error message detail "The email or password provided is incorrect. Please check for typos and try logging in again." popup. Examine the network traffic, it show bad request on /api/v1/signin

**Steps to Reproduce:**
upgrade to v0.1.124 and WEBUI_AUTH_TRUSTED_EMAIL_HEADER is enabled. No problem on v0.1.123

**Expected Behavior:**
Login sucessful

**Actual Behavior:**
[Describe what actually happened.]

## Environment

- **Open WebUI Version: v0.1.124
- **Ollama (if applicable): any

- **Operating System: Ubuntu 20.04
- **Browser (if applicable):**  Chrome 100.0

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
![signin-problem](https://github.com/open-webui/open-webui/assets/14144067/a76e5aa2-1d69-41e9-8056-d7d526a62689)

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Installation Method

Docker

**Comment by justinh-rahb** [comment]
There were some post-release hotfixes for SSO sign-in issues, please try re-pulling the image and re-running your container.
