### ISSUE TITLE
enhancement: TTS skip code sections

### ISSUE THREAD

**Issue by pcapazzi** [open-webui/open-webui#2152]
**Is your feature request related to a problem? Please describe.**
Text to Speech always reads aloud code snippets (python, sql, etc)

**Describe the solution you'd like**
It would be great if in settings there is an option to have TTS skip code sections.

**Describe alternatives you've considered**
I asked the LLM to not read aloud the code but it continued to do so.

**Additional context**
Nothing else to add. Lots to love about this app though... great work!

**Comment by lee-b** [comment]
I feel like this would help, but would be better as part of a more mode-based UX, where you tell the system that you're now in voice conversation mode, and it adds something to the prompt along the lines of "You are communicating with the user via voice, so try to interpret spelling errors (from the speech recognition engine), keep answers brief and conversational, and avoid code listings and other things which are best presented visually. The user cannot hear any code blocks."  THEN, if the model still outputs code blocks, they could be ignored, and the LLM would understand why you ignore them in your responses.

**Comment by Silentoplayz** [comment]
[Related comment](https://github.com/open-webui/open-webui/issues/1331#issuecomment-2080224728)

**Comment by thiswillbeyourgithub** [comment]
By the way, [openedai-speech (the dropin openai tts replacement) supports regex specification and it seems like it could perfectly handle your issue](https://github.com/matatonic/openedai-speech/blob/main/pre_process_map.default.yaml)
