### ISSUE TITLE
Feature Request: Support for Pulling Models from Privately hosted Model Registries

### ISSUE THREAD

**Issue by RWayne93** [open-webui/open-webui#2153]
## Overview

To enhance the flexibility and usability of Open WebUI for users with private model registry setups, I would like to add the addition of a feature that allows Open WebUI to pull model files from privately hosted Docker registries. 

## Example private registry setup 

```bash
docker run -d -p 5001:5000 --name registry registry:2
./ollama cp mistral:latest localhost:5001/ryan/mistral:latest
./ollama push localhost:5001/ryan/mistral:latest --insecure
./ollama pull localhost:5001/ryan/mistral:latest --insecure
```

## Feature Description

The feature would include a toggle button in the UI. When enabled, it allows users to specify Docker registry and configure Open WebUI to pull model files from these registries. This would be particularly useful for users working in isolated networks or homelab setups and are hosting their own repository of models. 

## Expected Benefits

Enhanced Customization: Users can integrate Open WebUI with their private infrastructure, allowing for more controlled and secure environments. Increased Accessibility: Makes Open WebUI more accessible for scenarios where public or secure registries are not an option.

I have done  the implementation of this feature already and it works with a registry hosted on one of my virtual machines.  Just looking for guidance and any initial thoughts from the community and maintainers. Also i am by no means a front end developer mostly stick to backend / compiled languages so i would appreciate an alternative to the implementation below if it isn't adequate.  

![insecure_registry](https://github.com/open-webui/open-webui/assets/16741629/16b2a6ee-c1dc-4f79-a828-62b92776b8ac)

**Comment by tjbck** [comment]
Added to our dev branch, Let me know if you encounter any issues!
