### ISSUE TITLE
All Documents Mode/Conversation

### ISSUE THREAD

**Issue by K-J-VV** [open-webui/open-webui#2174]
We're able to upload documents per chat, or select previous documents that were uploaded to "converse with them. It would be nice if there were a "Documents Mode" where after selected the LLM automatically references all uploaded documents as a whole. 

This would be similar to Private GPT's Query Mode https://github.com/zylon-ai/private-gpt 

**Describe the solution you'd like**
A new mode/tab that when entered, the entire conversation references all uploaded documents automatically. Without needing to specifically reference individual files

**Describe alternatives you've considered**
Private GPT is only alternative I'm aware of

**Additional context**
It may be nice to have separate "buckets" of documents for user groups. So when entering this mode, only users with appropriate permissions can 'chat' with documents made available to their groups

**Comment by justinh-rahb** [comment]
<img width="1037" alt="Screenshot 2024-05-10 at 5 04 20 PM" src="https://github.com/open-webui/open-webui/assets/52832301/9f77eec8-e13b-4a3e-8bae-6c747db8accb">
<img width="286" alt="Screenshot 2024-05-10 at 5 04 33 PM" src="https://github.com/open-webui/open-webui/assets/52832301/770f8281-25a6-4043-9502-d79edaec5a3b">

**Comment by K-J-VV** [comment]
@justinh-rahb Amazing

What about organizing documents into "buckets" or groups? That way an admin can have access to the central /docs directory but then create /docs/admins /docs/group1 /docs/user3 so that document access can be filtered further?
