### ISSUE TITLE
Arabic Text Alignment Issue with Llama3 Model in Ollama WebUI

### ISSUE THREAD

**Issue by usmandilmeer** [open-webui/open-webui#2179]
While using the Ollama WebUI, I am encountering an issue. 
When I request the Llama3 model in the Ollama WebUI to translate some text from English to Arabic, Urdu or other languages that start from right hand side, it starts writing Arabic from the left-hand side. However, Arabic text should originally start from the right-hand side. Could you please fix this issue?

![image](https://github.com/open-webui/open-webui/assets/51738693/7ef17300-0bf3-4e50-830a-8e9a9cc4a6d7)

**Comment by Silentoplayz** [comment]
Related - #2134
