### ISSUE TITLE
Persistently Store OpenAI and OpenAI-Compatible API Keys Across Server Restarts

### ISSUE THREAD

**Issue by SomaRe** [open-webui/open-webui#2184]
**Is your feature request related to a problem? Please describe.**
Currently, when the server restarts, all the configured OpenAI and OpenAI-compatible APIs and their corresponding API keys are lost. This requires manually re-adding and configuring each API after every restart, which can be a tedious and time-consuming process, especially if new API keys need to be generated.

**Describe the solution you'd like**
The desired solution is to provide a persistent storage mechanism for OpenAI and OpenAI-compatible API keys, similar to how the ollama API is handled. This would allow the system to retain the configured APIs and their respective API keys across server restarts, eliminating the need for manual reconfiguration after each restart.

**Comment by Silentoplayz** [comment]
This is related to [save UI config changes to config.json](https://github.com/open-webui/open-webui/pull/2156) - #2156.

**Comment by Silentoplayz** [comment]
Also related to [persist settings to backend](https://github.com/open-webui/open-webui/issues/1022) - #1022.
