### ISSUE TITLE
Write error when adding a LiteLLM Model (Snap)

### ISSUE THREAD

**Issue by KatjaD-CH** [open-webui/open-webui#2187]
# Bug Report

## Description

**Bug Summary:**
Open WebUI installed as Snap package under Ubuntu.

Write error when adding a LiteLLM Model:
Read-only file system: './data/litellm/config.yaml'

**Steps to Reproduce:**
- Click on Admin-User in the lower left corner
- Select Settings
- Select Models
- Click on Show (Manage LiteLLM Models)
- Click on the '+' button
- The error message shows for a (to) short moment (Screenshot)

**Expected Behavior:**
Having a new model entry available

**Actual Behavior:**
- Error message
- Input box value reverted to default

## Environment

- **Open WebUI Version:** [v0.1.124]

- **Operating System:** Ubuntu 22.04 LTS
- **Browser (if applicable):** [Firefox]

## Logs and Screenshots

**Screenshots (if applicable):**
![WebUiError](https://github.com/open-webui/open-webui/assets/22710571/7133fdbb-d1de-4b5c-a498-7884fd20120a)

## Installation Method

SnapStore provided by Ubuntu

**Comment by justinh-rahb** [comment]
This is an issue in the snap package.

- #724

**Comment by tjbck** [comment]
Bundled LiteLLM support will be deprecated for our future releases, I'd recommend you start migrating your LiteLLM config.yaml to a self-hosted LiteLLM instance. You'd still be able to add them to our webui via OpenAI Connections.
