### ISSUE TITLE
allow customize model display name

### ISSUE THREAD

**Issue by BarcodeQH** [open-webui/open-webui#2198]
**Is your feature request related to a problem? Please describe.**
Ollama is setting rules to standardize the model name created by Modelfile. Eg: non-english characters or uppercase characters (uppercase appears to be a bug, which has been fixed in pre-release v0.1.37) are no longer allowed. This is good for Ollama as a backend service, but may impact user experience. As Open-WebUI can now only list the Ollama "technical" model name for users to select

**Describe the solution you'd like**
When creating Modelfiles via the UI, enable admin to utilize the 'Name' instead of the 'Model Tag Name' for display in the UI

**Comment by Silentoplayz** [comment]
This is related to [feat: configurable model name, description and vision capability](https://github.com/open-webui/open-webui/pull/2140) - #2140
