### ISSUE TITLE
bug: Uncaught (in promise) TypeErrors in Open WebUI, causes page freeze & browser console errors until refresh

### ISSUE THREAD

**Issue by silentoplayz** [open-webui/open-webui#2208]
# Bug Report

## Description

**Bug Summary:**
- I've found a few `Uncaught (in promise) TypeErrors` in Open WebUI, causing unexpected page freeze-like behavior along with a few console log errors produced to potentially help debug the issues.

**Expected Behavior:**
- The page should not freeze up due to `Uncaught (in promise) TypeErrors`, requiring a manual refresh by the user to unfreeze the page and clear out browser console log errors.

**Actual Behavior:**
- A few different `Uncaught (in promise) TypeErrors`, followed by a series of error messages related to `Immutable`, requiring a manual refresh by the user to unfreeze the page to solve.

## Environment

- **Open WebUI Version:** v0.1.124-v0.3.4 [(latest)](https://github.com/open-webui/open-webui/releases/tag/v0.3.4)
- **Ollama:** This bug has been found to be present on versions [v0.1.35](https://github.com/ollama/ollama/releases/tag/v0.1.35)-[v0.1.44](https://github.com/ollama/ollama/releases/tag/v0.1.44) based on my testing.
- **Operating System:** Windows 11 Pro Insider Preview (Edition) - Version: 24H2 - Installed on: May 19, 2024 - OS build: 26120.770 - Experience: Windows Feature Experience Pack 1000.26100.6.0
- **Browser:** Firefox v127.0 (64-bit)

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs + Reproduction Details:**

## 1st error (browser console log):
```javascript
23:06:07.634 Uncaught (in promise) TypeError: t is null
    $ dom.js:252
    m Tooltip.svelte:41
    _t Component.js:44
    m ResponseMessage.svelte:978
    p ResponseMessage.svelte:945
    p ResponseMessage.svelte:642
    p ResponseMessage.svelte:584
    p ResponseMessage.svelte:423
    p ResponseMessage.svelte:383
    at scheduler.js:119
    ut scheduler.js:79
    promise callback*lt scheduler.js:20
    ht Component.js:81
    ctx Component.js:139
    jt Chat.svelte:1351
    M Chat.svelte:1334
    ctx Component.js:138
    K Messages.svelte:215
    K Messages.svelte:212
    J Messages.svelte:295
    n Messages.svelte:311
    t lifecycle.js:105
    t lifecycle.js:104
    w UserMessage.svelte:55
    te UserMessage.svelte:345
    c rocket-loader.min.js:1
dom.js:252:62
    ut scheduler.js:86
    (Async: promise callback)
    lt scheduler.js:20
    ht Component.js:81
    ctx Component.js:139
    jt Chat.svelte:1351
    M Chat.svelte:1334
    ctx Component.js:138
    K Messages.svelte:215
    forEach self-hosted:157
    K Messages.svelte:212
    J Messages.svelte:295
    n Messages.svelte:311
    t lifecycle.js:105
    forEach self-hosted:157
    t lifecycle.js:104
    w UserMessage.svelte:55
    te UserMessage.svelte:345
    c rocket-loader.min.js:1
```

**Steps to Reproduce 1st Error:**
1. Log into Open WebUI on either one of my personal TLDs or directly via localhost.
2. Choose a local or external large language model in the model selector dropdown to begin chatting with.
3. Send a query and await for the finished response.
4. Send another query and await for the finished response.
5. Delete your most recent message (2nd query) sent to the LLM.
6. Press `F12` on your keyboard to open up your browser console and switch to the `Console` tab to observe error.

- The bugs I've reported above are reproducible with both local and external models.
- All steps mentioned for step-by-step bug reproduction methods are crucial for ensuring you can replicate these same (or related) errors in your browser console.

7. Press the `Edit` button of the first message you sent in the chat (before the LLM's response in this chat) and observe new error:
```javascript
23:07:01.736 Uncaught (in promise) TypeError: R is undefined
    I UserMessage.svelte:36
    ee UserMessage.svelte:295
    c rocket-loader.min.js:1
    addEventListener rocket-loader.min.js:1
    St dom.js:361
    m UserMessage.svelte:312
    m Tooltip.svelte:41
    _t Component.js:44
    m UserMessage.svelte:291
    m UserMessage.svelte:419
    m UserMessage.svelte:422
    _t Component.js:44
    m Messages.svelte:308
    m Messages.svelte:370
    m Messages.svelte:374
    p Messages.svelte:285
    p Messages.svelte:380
    at scheduler.js:119
    ut scheduler.js:79
    promise callback*lt scheduler.js:20
    ht Component.js:81
    ctx Component.js:139
    Zi Sidebar.svelte:37
    o index.js:56
    Z Chat.svelte:442
    Ie Chat.svelte:373
    Re MessageInput.svelte:478
    jt dom.js:371
    c rocket-loader.min.js:1
    addEventListener rocket-loader.min.js:1
    St dom.js:361
    m MessageInput.svelte:1001
    m MessageInput.svelte:448
    _t Component.js:44
    m Chat.svelte:1386
    m Chat.svelte:1306
    _t Component.js:44
    m Help.svelte:40
    _t Component.js:44
    p root.svelte:54
    p root.svelte:49
    wt utils.js:203
    p +layout.svelte:190
    p +layout.svelte:187
    at scheduler.js:119
UserMessage.svelte:36:2
    I UserMessage.svelte:36
    InterpretGeneratorResume self-hosted:1412
    AsyncFunctionNext self-hosted:799
    (Async: async)
    ee UserMessage.svelte:295
    c rocket-loader.min.js:1
    (Async: EventListener.handleEvent)
    addEventListener rocket-loader.min.js:1
    St dom.js:361
    m UserMessage.svelte:312
    m Tooltip.svelte:41
    _t Component.js:44
    m UserMessage.svelte:291
    m UserMessage.svelte:419
    m UserMessage.svelte:422
    _t Component.js:44
    m Messages.svelte:308
    m Messages.svelte:370
    m Messages.svelte:374
    p Messages.svelte:285
    p Messages.svelte:380
    at scheduler.js:119
    ut scheduler.js:79
    (Async: promise callback)
    lt scheduler.js:20
    ht Component.js:81
    ctx Component.js:139
    Zi Sidebar.svelte:37
    o index.js:56
    Z Chat.svelte:442
    InterpretGeneratorResume self-hosted:1412
    AsyncFunctionNext self-hosted:799
    (Async: async)
    Ie Chat.svelte:373
    InterpretGeneratorResume self-hosted:1412
    AsyncFunctionNext self-hosted:799
    (Async: async)
    Re MessageInput.svelte:478
    jt dom.js:371
    c rocket-loader.min.js:1
    (Async: EventListener.handleEvent)
    addEventListener rocket-loader.min.js:1
    St dom.js:361
    m MessageInput.svelte:1001
    m MessageInput.svelte:448
    _t Component.js:44
    m Chat.svelte:1386
    m Chat.svelte:1306
    _t Component.js:44
    m Help.svelte:40
    _t Component.js:44
    p root.svelte:54
    p root.svelte:49
    wt utils.js:203
    p +layout.svelte:190
    p +layout.svelte:187
    at scheduler.js:119
```

9. Press the `Edit` button of the LLM's response to your message and observe another new error:
```javascript
23:07:56.721 Uncaught (in promise) TypeError: U is undefined
    Ye ResponseMessage.svelte:316
    Re ResponseMessage.svelte:650
    c rocket-loader.min.js:1
ResponseMessage.svelte:316:2
    Ye ResponseMessage.svelte:316
    InterpretGeneratorResume self-hosted:1412
    AsyncFunctionNext self-hosted:799
    (Async: async)
    Re ResponseMessage.svelte:650
    c rocket-loader.min.js:1
```

### 2nd error; not sure if this is a huge issue at all though, as this doesn't appear to cause any issues and is unrelated to the actual bug report I'm making here (browser console log):
This error occurred upon signing out of my Open WebUI account:
```javascript
Error: Promised response from onMessage listener went out of scope 6 background.js:505:27
```
This error occurred upon signing into my Open WebUI account:
```javascript
Error: Promised response from onMessage listener went out of scope
```

## Docker Container Logs:

- Docker Desktop/Container logs are irrelevant to the issue at hand. There's nothing within Docker logs that screams that there's an "**ISSUE**" like browser logs does specifically.

## Installation Method

Docker Desktop via a custom-built docker-compose.yml file for my Open WebUI instance and domains. Ollama is running natively on Windows via the Windows (Preview) version.

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Please let me know if I've missed anything or if there's any additional information needed!**

**Comment by tjbck** [comment]
1st issue should be fixed on dev!

**Comment by silentoplayz** [comment]
> 1st issue should be fixed on dev!

I apologize for the delayed response, but I'm pleased to confirm that the initial issue has been corrected on both my production and development environments.

To help with debugging the second error, I've included an alternative reproduction method below:

**Reproducing Error: `Uncaught (in promise) TypeError: t is null` and `TypeError: D is undefined`**

1. Log into Open WebUI on either of my personal TLDs.
2. Send a query in a preexisting chat.
3. Delete the message you just sent.
4. The error was produced in the browser console (Latest version of Mozilla Firefox):
```javascript
    Uncaught (in promise) TypeError: t is null
    Immutable 25
    c https://g30ui.xyz/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
    addEventListener https://g30ui.xyz/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
    Immutable 20
    c https://g30ui.xyz/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
    addEventListener https://g30ui.xyz/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
    Immutable 26
scheduler.bcadb9af.js:1:3376
    Immutable 8
    forEach self-hosted:157
    Immutable 4
    forEach self-hosted:157
    Immutable 3
    c https://g30ui.xyz/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
    (Async: EventListener.handleEvent)
    addEventListener https://g30ui.xyz/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
    Immutable 20
    c https://g30ui.xyz/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
    (Async: EventListener.handleEvent)
    addEventListener https://g30ui.xyz/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
    Immutable 11
    InterpretGeneratorResume self-hosted:1412
    AsyncFunctionNext self-hosted:799
    Immutable 15
    InterpretGeneratorResume self-hosted:1412
```
**Additional Steps to Reproduce (Do these steps immediately after the first steps in this comment provided to reproduce this error)**
1. Press the Edit button on the LLM's most recent response.
2. A second error will be produced in the browser console:
```javascript
    Uncaught (in promise) TypeError: D is undefined
    Immutable 2
    c https://g30ui.xyz/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
    addEventListener https://g30ui.xyz/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
    Immutable 27
Messages.3d997bf3.js:404:2106
```

**Comment by Yanyutin753** [comment]
### Every time I delete information, the page fails to report an error and cannot be used normally. After refreshing the page, it can only be used normally.

### Console error
![image](https://github.com/open-webui/open-webui/assets/132346501/a10cb7ac-770e-4625-9d1e-297d0db2717e)

**Comment by silentoplayz** [comment]
Yet another additional error without solidified steps for reproduction (**YET**):
```javascript
Uncaught (in promise) TypeError: y is undefined
    Immutable 2
    c https://g30ui.xyz/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
Messages.3d997bf3.js:1:31921
```

**Expanded:**
```javascript
Uncaught (in promise) TypeError: y is undefined
    Immutable 2
        M
        me
    c https://g30ui.xyz/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
Messages.3d997bf3.js:1:31921
    M Immutable
    InterpretGeneratorResume self-hosted:1412
    AsyncFunctionNext self-hosted:799
    (Async: async)
    me Immutable
    c https://g30ui.xyz/cdn-cgi/scripts/7d0fa10a/cloudflare-static/rocket-loader.min.js:1
```

**Comment by kojdj0811** [comment]
I noticed a similar error. I'm using a 70b model on a slow GPU (P40), and I get an error at exactly 5 minutes and the text won't update.

Even after the above phenomenon occurred, the AI was still generating answers on the server. After the operation of the AI for answers was over, it was confirmed that VRAM was cleared after an additional 5 minutes as the default setting of OLLAMA_KEEP_ALIVE.

![image](https://github.com/open-webui/open-webui/assets/8279233/3b4ee6e0-b6fb-4940-8483-b45e827907d4)

**Comment by silentoplayz** [comment]
> I noticed a similar error. I'm using a 70b model on a slow GPU (P40), and I get an error at exactly 5 minutes and the text won't update.
> 
> Even after the above phenomenon occurred, the AI was still generating answers on the server. After the operation of the AI for answers was over, it was confirmed that VRAM was cleared after an additional 5 minutes as the default setting of OLLAMA_KEEP_ALIVE.

This does not appear similar in case to the bug(s) that I've reported here. If you're still experiencing this problem, I recommend opening up a separate new bug report with more details.

**Comment by silentoplayz** [comment]
> 1st issue should be fixed on dev!

I've updated the bug report, so this comment no longer aligns as of now (just a heads up!).

On a lighter note, I'm glad I could help by reporting bugs I've found that you then have fixed to make Open WebUI better for everyone to enjoy. Thanks for your hard work. 🍻

**Comment by Algorithm5838** [comment]
I'm seeing the same bug and getting this error in the console:
```
dom.js:253 Uncaught (in promise) TypeError: Cannot read properties of null (reading 'insertBefore')
    at $ (dom.js:253:10)
    at Object.m (Tooltip.svelte:37:1)
    at _t (Component.js:44:23)
    at Object.m (ResponseMessage.svelte:978:50)
    at Object.p (ResponseMessage.svelte:945:42)
    at Object.p (ResponseMessage.svelte:642:23)
    at Object.p (ResponseMessage.svelte:584:47)
    at Object.p (ResponseMessage.svelte:423:96)
    at Object.p (ResponseMessage.svelte:383:17)
    at at (scheduler.js:119:30)
```

**Comment by Algorithm5838** [comment]
Thanks! I can confirm that the issue has been fixed in the new update, v0.3.5.

**Comment by silentoplayz** [comment]
> The second issue should also be fixed on latest dev!

Hype! You've fixed the bug I've had for so long. Thanks for all your hard work @tjbck! <3

**Comment by damajor** [comment]
I have a similar issue on my instance.

```
Uncaught (in promise) 
TypeError: Cannot read properties of undefined (reading 'model')
    at Object.p (￼CompareMessages.svelte:113:9)
    at Object.p (￼CompareMessages.svelte:105:94)
    at Object.p (￼CompareMessages.svelte:104:10)
    at Object.p (￼CompareMessages.svelte:103:25)
    at at (￼scheduler.js:119:30)
    at ut (￼scheduler.js:79:5)
p	@	￼CompareMessages.svelte:113
p	@	￼CompareMessages.svelte:105
p	@	￼CompareMessages.svelte:104
p	@	￼CompareMessages.svelte:103
at	@	￼scheduler.js:119
ut	@	￼scheduler.js:79
Promise.then (async)		
lt	@	￼scheduler.js:20
ht	@	￼Component.js:81
(anonymous)	@	￼Component.js:139
he	@	￼Chat.svelte:319
await in he (async)		
(anonymous)	@	￼Chat.svelte:130
Pa.s.$$.update	@	￼Chat.svelte:138
at	@	￼scheduler.js:115
ut	@	￼scheduler.js:79
Promise.then (async)		
lt	@	￼scheduler.js:20
ht	@	￼Component.js:81
(anonymous)	@	￼Component.js:139
s.$$set	@	￼root.svelte:62
$set	@	￼Component.js:507
ce	@	￼client.js:1129
await in ce (async)		
(anonymous)	@	￼client.js:1603
```

I think it can be easily reproduced following these steps:
- create new chat
- use 3 models at once in the chat
- duplicate the chat or create another one with 3 models
- open browser debug
- navigate to first chat and then to the second one (do it again)
- it should hang when switching 1 or 2 times from one chat to the other one.

**Comment by silentoplayz** [comment]
@damajor I am unable to reproduce this `Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'model')` error on the latest dev branch of Open WebUI, but I can produce a couple of new different errors that I have not yet come across before, if I happen to regenerate one of the responses of any of the 3 LLM's in the original chat and then try switching away from this chat to another one.

Steps to reproduce the errors in browser console that **I've** found:

1) Create a new chat
2) Use 3 models at once in the chat
3) Clone this chat
4) Regenerate the 1st model's response (based on the model dropdown selector, models from top to bottom are sorted from left to right) in the cloned chat.
5) Open the browser's debug console (F12).
6. Navigate back to the initial/main chat.
7. Error should be logged to console:
```js
19:43:23.739 Uncaught (in promise) TypeError: t[0].messages[t[11]] is undefined
    p CompareMessages.svelte:111
    p CompareMessages.svelte:105
    p CompareMessages.svelte:104
    p CompareMessages.svelte:103
    at scheduler.js:119
    ut scheduler.js:79
    promise callback*lt scheduler.js:20
    ht Component.js:81
    ctx Component.js:139
    he Chat.svelte:319
    update Chat.svelte:130
    update Chat.svelte:138
    at scheduler.js:115
    ut scheduler.js:79
    promise callback*lt scheduler.js:20
    ht Component.js:81
    ctx Component.js:139
    $$set root.svelte:62
    $set Component.js:507
    ce client.js:1129
    _start_router client.js:1603
    c rocket-loader.min.js:1
CompareMessages.svelte:111:65
```
8. Press the button to go back to the previous message for the 1st model's response that had it's initial response regenerated.
9. Error should be logged to console:
```js
19:54:09.887 Uncaught TypeError: G is undefined
    V CompareMessages.svelte:117
    d CompareMessages.svelte:137
    c rocket-loader.min.js:1
    addEventListener rocket-loader.min.js:1
    St dom.js:361
    m CompareMessages.svelte:162
    m CompareMessages.svelte:105
    m CompareMessages.svelte:104
    p CompareMessages.svelte:103
    at scheduler.js:119
    ut scheduler.js:79
    promise callback*lt scheduler.js:20
    ht Component.js:81
    ctx Component.js:139
    a root.svelte:35
    promise callback*ct/</a< root.svelte:34
    l utils.js:227
    o index.js:56
    f index.js:69
    s utils.js:212
    ut scheduler.js:99
    promise callback*lt scheduler.js:20
    ht Component.js:81
    ctx Component.js:139
    $$set root.svelte:62
    $set Component.js:507
    ce client.js:1129
    _start_router client.js:1603
    c rocket-loader.min.js:1
    addEventListener rocket-loader.min.js:1
    _start_router client.js:1521
    jt start.js:27
    <anonymous> line 10 > injectedScript:14
    promise callback* line 10 > injectedScript:13
    apply <anonymous code>:10
    activateScript rocket-loader.min.js:1
    n rocket-loader.min.js:1
    run rocket-loader.min.js:1
    x rocket-loader.min.js:1
    runOnLoad rocket-loader.min.js:1
    runOnLoad rocket-loader.min.js:1
    x rocket-loader.min.js:1
    <anonymous> rocket-loader.min.js:1
    <anonymous> rocket-loader.min.js:1
    <anonymous> rocket-loader.min.js:1
CompareMessages.svelte:117:31
```

**Comment by silentoplayz** [comment]
> I noticed a similar error. I'm using a 70b model on a slow GPU (P40), and I get an error at exactly 5 minutes and the text won't update.
> 
> Even after the above phenomenon occurred, the AI was still generating answers on the server. After the operation of the AI for answers was over, it was confirmed that VRAM was cleared after an additional 5 minutes as the default setting of OLLAMA_KEEP_ALIVE.
> 
> ![image](https://private-user-images.githubusercontent.com/8279233/337947368-3b4ee6e0-b6fb-4940-8483-b45e827907d4.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjE2MDgxNTYsIm5iZiI6MTcyMTYwNzg1NiwicGF0aCI6Ii84Mjc5MjMzLzMzNzk0NzM2OC0zYjRlZTZlMC1iNmZiLTQ5NDAtODQ4My1iNDVlODI3OTA3ZDQucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDcyMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA3MjJUMDAyNDE2WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NDA4ZTIxNGFkMWE3ZTI5MjJiYzRlNDY0YTRmZDNiZTVhNWY3Y2I1ZmRkNDU1ZTAxYzQ4OGVhYTg0ZTAwMDFkMSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.n2WPXObMH7gGJaonbTMswdmC7nEMZ6hnpcqEto-MLLY)

Related merge that should fix this issue: https://github.com/open-webui/open-webui/pull/3107

**Comment by damajor** [comment]
Well maybe the UI was in a bad state when I get the issue, but I am not able to reproduce the problem atm.

**Comment by silentoplayz** [comment]
Closing in favor of https://github.com/open-webui/open-webui/issues/4408

**Comment by lehhair** [comment]
Now I still have this problem when I use /quick type prompt
