### ISSUE TITLE
BUG: Multi-Model Sequential Response Generation

### ISSUE THREAD

**Issue by cybersholt** [open-webui/open-webui#2209]
# Bug Report

## Description

**Bug Summary:**

When multiple models are selected in OpenWebUI and a question is submitted, the response generation incorrectly starts with the last selected model rather than the first. This behavior is counterintuitive as users expect the response sequence to begin from the first model selected.

**Steps to Reproduce:**

Launch OpenWebUI.
Select multiple models (e.g., five different models).
Submit a question or input to these models.
Observe the order in which the responses are generated.

**Expected Behavior:**

The response generation should initiate from the first selected model and proceed sequentially through to the last model selected.

**Actual Behavior:**

The response generation initiates from the last model selected and proceeds in reverse order.

## Environment

- **Open WebUI Version:** 0.1.124
- **Ollama (if applicable):** 0.1.36

- **Operating System:** Windows 10
- **Browser (if applicable):** Brave 1.65.132, Chromium 124.0.6367.202

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**

**Docker Container Logs:**

**Screenshots (if applicable):**  

## Installation Method

Running with Docker on Windows 10 with docker compose

## Additional Information

Seems like a pretty straight forward fix, I think it should jump to whatever is outputting first.

**Comment by tjbck** [comment]
Closing in favour of #2237
