### ISSUE TITLE
No jump after logging in unless refreshed again

### ISSUE THREAD

**Issue by ALixuhui** [open-webui/open-webui#2221]
# Bug Report
No jump after logging in unless refreshed again

## Description
After clicking login
![image](https://github.com/open-webui/open-webui/assets/40882157/263d8bab-f2c2-407a-9005-0c68666b2588)
Wait for a while but it still won’t jump
![9895](https://github.com/open-webui/open-webui/assets/40882157/8000b450-e72d-4c0e-8197-c46b3fe29f6b)
Unless refreshed again

**Comment by Silentoplayz** [comment]
Please reopen another bug report with the template filled out. This bug report does not help developers, nor contributors pinpoint any issue.
