### ISSUE TITLE
enh: better voice interactions

### ISSUE THREAD

**Issue by tjbck** [open-webui/open-webui#2241]
- [x] voice message recording like imessage
- [x] siri-esque real time voice interaction

**Comment by IIPedro** [comment]
Hello! I'm unaware if work has been done about this topic yet, but it would be interesting to see better voice interactions as part of pipelines. Of course, it should be the front-end's job to provide an easy to use and comfortable interface, but I believe both siri-esque interaction and voice calls can be tackled in one go with a new pipeline function. Just like there's a pipe def in pipelines, it would be very useful to have a voice def that takes an audio buffer as input in a previously determined rate and returns another audio buffer, which would be the assistant's voice in the call. That would make voice interactions as versatile as current chat pipelines and would allow for the support of various libraries and APIs in a standardized manner. Thanks!

**Comment by tjbck** [comment]
Implemented on dev.

@IIPedro Great suggestions, I'll see what can be done!

**Comment by darkvertex** [comment]
@tjbck Is it normal the microphone stays in listening mode permanently until closing the tab even after exiting the Call mode? (Should I file a bug issue for this?)

**Comment by justinh-rahb** [comment]
I've noted this as well on Chrome/Mac and Chrome/Android.
