### ISSUE TITLE
enhancement: external stt

### ISSUE THREAD

**Issue by Stargate256** [open-webui/open-webui#2248]
**Is your feature request related to a problem? Please describe.**
Would it be possible to allow running whisper on another server?

**Describe the solution you'd like**
Adding the ability to connect to whisper via some kind of API.

**Additional context**
I am running open-webui on a server without GPUs, and LLMs, TTS on another server.

**Comment by fedirz** [comment]
I've recently developed [faster-whisper-server](https://github.com/fedirz/faster-whisper-server) which provides an OpenAI compatible transcription/translation (and some extras as well) which could be used as a transcription backend if OpenWebUI adds support for having an external STT

**Comment by tjbck** [comment]
STT & TTS settings have been refactored and you can now configure external OpenAI STT from Admin Settings!

![image](https://github.com/open-webui/open-webui/assets/25473318/b2f1f881-ca24-4f61-805f-b8c6025cceff)

![image](https://github.com/open-webui/open-webui/assets/25473318/9266a41b-4462-4505-9e4f-ceb7f5549246)

**Comment by bannert1337** [comment]
I tried this and the model name for STT is not correctly used.
![Screenshot 2024-06-08 at 16-30-36 Admin Panel Open WebUI](https://github.com/open-webui/open-webui/assets/58707896/1902a3a5-b19e-4eda-bc95-aef4b1750c24)

```
ValueError: Invalid model size 'whisper-1', expected one of: tiny.en, tiny, base.en, base, small.en, small, medium.en, medium, large-v1, large-v2, large-v3, large, distil-large-v2, distil-medium.en, distil-small.en, distil-large-v3
```

**Comment by colaber2** [comment]
> @colaber2
> 
> STT & TTS settings have been refactored on dev and you can now configure external OpenAI STT from Admin Settings!
> 
> ![image](https://private-user-images.githubusercontent.com/25473318/337831319-b2f1f881-ca24-4f61-805f-b8c6025cceff.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMzE0ODgsIm5iZiI6MTcxODAzMTE4OCwicGF0aCI6Ii8yNTQ3MzMxOC8zMzc4MzEzMTktYjJmMWY4ODEtY2EyNC00ZjYxLTgwNWYtYjhjNjAyNWNjZWZmLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDE0NTMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTFkMzI5ZDkzZGM0ZjZkNDBkYTNmOGZjMWNhYjgyZjg4MGZhMGM1Yjk4YTZhNjE4MzhiNzVlM2FmZDI4N2Q3ZDEmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.Ox1mbSchCgVqee3RAzQH_jhLNHQAi6wY2Vaa31rfJuo)
> 
> ![image](https://private-user-images.githubusercontent.com/25473318/337831349-9266a41b-4462-4505-9e4f-ceb7f5549246.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgwMzE0ODgsIm5iZiI6MTcxODAzMTE4OCwicGF0aCI6Ii8yNTQ3MzMxOC8zMzc4MzEzNDktOTI2NmE0MWItNDQ2Mi00NTA1LTllNGYtY2ViN2Y1NTQ5MjQ2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTAlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEwVDE0NTMwOFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTAyZTIwZmEwYjZiNWEwYjJiNTk2ZGU5ZmVlODRmNDk2ZjY1ZTllMDAyODlmZDk1MGIyZmE3ZDUwMjE5NjhlODkmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.s7jEgVekC6K9sq4l-KPTMdFm8UWWXPEwmdJKI5o_x_w)

Amazing.. well done!!

**Comment by JohnSmithToYou** [comment]
> I tried this and the model name for STT is not correctly used. ![Screenshot 2024-06-08 at 16-30-36 Admin Panel Open WebUI](https://private-user-images.githubusercontent.com/58707896/337881085-1902a3a5-b19e-4eda-bc95-aef4b1750c24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxOTg0MzUsIm5iZiI6MTcxODE5ODEzNSwicGF0aCI6Ii81ODcwNzg5Ni8zMzc4ODEwODUtMTkwMmEzYTUtYjE5ZS00ZWRhLWJjOTUtYWVmNGIxNzUwYzI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDEzMTUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjODdiMzBkOTY0ZTJjMWZjOWVlMDFjOWU1ZDhiMjY0MDNjN2E5MGVmZWU4NmNlYmI1NTdkOGM2NzIwMjAzYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tXXy6HVhkg3kbiII3R0Ep0AfHbK8s3O72woKpMqaM7Y)
> 
> ```
> ValueError: Invalid model size 'whisper-1', expected one of: tiny.en, tiny, base.en, base, small.en, small, medium.en, medium, large-v1, large-v2, large-v3, large, distil-large-v2, distil-medium.en, distil-small.en, distil-large-v3
> ```
@tjbck The model name is being ignored. As a result we can't use @fedirz's [faster-whisper-server](https://github.com/fedirz/faster-whisper-server) because it doesn't know what "whisper-1" is. 
I modified faster-whisper-server to treat "whisper-1" as the default model and it worked great! @fedirz, maybe this is a good feature you could add? @tjbck, could you make the fix so we can choose the models?

Thank you both for your work!

**Comment by fedirz** [comment]
Hey, yeah, I'll add special handling for `whisper-1`

**Comment by murtaza-nasir** [comment]
> > I tried this and the model name for STT is not correctly used. ![Screenshot 2024-06-08 at 16-30-36 Admin Panel Open WebUI](https://private-user-images.githubusercontent.com/58707896/337881085-1902a3a5-b19e-4eda-bc95-aef4b1750c24.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTgxOTg0MzUsIm5iZiI6MTcxODE5ODEzNSwicGF0aCI6Ii81ODcwNzg5Ni8zMzc4ODEwODUtMTkwMmEzYTUtYjE5ZS00ZWRhLWJjOTUtYWVmNGIxNzUwYzI0LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA2MTIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNjEyVDEzMTUzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPThjODdiMzBkOTY0ZTJjMWZjOWVlMDFjOWU1ZDhiMjY0MDNjN2E5MGVmZWU4NmNlYmI1NTdkOGM2NzIwMjAzYjUmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.tXXy6HVhkg3kbiII3R0Ep0AfHbK8s3O72woKpMqaM7Y)
> > ```
> > ValueError: Invalid model size 'whisper-1', expected one of: tiny.en, tiny, base.en, base, small.en, small, medium.en, medium, large-v1, large-v2, large-v3, large, distil-large-v2, distil-medium.en, distil-small.en, distil-large-v3
> > ```
> 
> @tjbck The model name is being ignored. As a result we can't use @fedirz's [faster-whisper-server](https://github.com/fedirz/faster-whisper-server) because it doesn't know what "whisper-1" is. I modified faster-whisper-server to treat "whisper-1" as the default model and it worked great! @fedirz, maybe this is a good feature you could add? @tjbck, could you make the fix so we can choose the models?
> 
> Thank you both for your work!

How did you get it to work with faster-whisper-server? I keep getting 404 errors in openwebui. I know my faster-whisper-server endpoint is working because I can use it fine with whisper-writer on my Windows 11 computer.
