### ISSUE TITLE
Version Does Not Seem to Update

### ISSUE THREAD

**Issue by ganakee** [open-webui/open-webui#2282]
# Bug Report

## Description

**Bug Summary:**
I attempted to update a docker open-webui instance but the web GUI still reports:
Ollama Web UI Version
v1.0.0-alpha.61

**Steps to Reproduce:**
I renamed my old docker ollama-webui and re-ran the command:
`docker run -d -p 3030:8080 -e OLLAMA_API_BASE_URL=http://192.168.4.171:11434/api -v ollama-webui:/app/backend/data --name ollama-webui --restart always ghcr.io/ollama-webui/ollama-webui:main`

This creates and starts the new instance. However, I have done this twice. When I go to the webgui, the open-webui is running but going to About shows the past version. I cannot tell whether the instance upgraded.

I also went to https://hub.docker.com/r/ollamawebui/ollama-webui and pulled the version. But I see that the pulled version is from six months ago.

**Expected Behavior:**
Updates to the latest version.

**Actual Behavior:**
See above. It seems like I have the old version.

## Environment

- **Open WebUI Version:** unknown
- **Ollama (if applicable):** custom AMD GPU 0.1.32
e.g., Ch
- **Operating System:**Linux POP OS 22.04
- **Browser (if applicable):** Firefox 125.02

**Comment by justinh-rahb** [comment]
https://docs.openwebui.com/migration

**Comment by ganakee** [comment]
Thank you for the quick reply! Sorry, I did not realize the name change applied to me. Will try the suggestion. Thank you.
