### ISSUE TITLE
enhancement: auth ollama connection

### ISSUE THREAD

**Issue by le-h-des-iles** [open-webui/open-webui#2305]
**Is your feature request related to a problem? Please describe.**
I'm hosting my Ollama on OVH Public Cloud. My application is private so I need to use token authentication to access it. But, unfortunately, I didn't find the possibility to pass token in open-webui connections settings.

**Describe the solution you'd like**
Allow user to pass token per Ollama Base URL.

**Additional context**
The feature is already done and it look like this :
![image](https://github.com/open-webui/open-webui/assets/47544043/febdd26e-ab62-409d-b24a-642d370d8fa1)
The token field is hide by default.

You can show it by clicking on the key :
![image](https://github.com/open-webui/open-webui/assets/47544043/eb069b83-7d66-4eb3-ac37-427cbbc1ba56)

**Comment by tjbck** [comment]
Added to dev
