### ISSUE TITLE
Create modelfiles that use api LLMs, e.g. gpt-4

### ISSUE THREAD

**Issue by mdillondc** [open-webui/open-webui#2314]
**Is your feature request related to a problem? Please describe.**
I tried creating a modelfile with `FROM gpt-4` but despite being able to select and use that model because I have my API key set up, saving the model file results in "pull model manifest: file does not exist". 

**Describe the solution you'd like**
Modelfiles should be able to utilize models connected though an API, such as those from OpenAI.

**Describe alternatives you've considered**
Using prompts after selecting a gpt model, but that is not ideal.

**Additional context**
None.

**Comment by tjbck** [comment]
Duplicate #665, For anyone who might come across this in the future, please refrain from creating duplicate issues. It only slows me down from getting the actual work done for these features to get implemented. @mdillondc @SchneiderSam If you see any duplicate requests by other users please refer them to #665, Thanks in advance!
