### ISSUE TITLE
Model search doesn't work properly.

### ISSUE THREAD

**Issue by MicahZoltu** [open-webui/open-webui#2367]
# Bug Report

## Description

**Bug Summary:**
If you have a large number of models, when you try to search for a model by name it doesn't always show all matches.

**Steps to Reproduce:**
1. Put https://api.together.xyz and an API key in as OpenAI credentials.
2. Go to new chat.
3. Try to search for `Llama-3`
4. Notice that it isn't found.
5. Search for meta-llama.
6. Notice that there is a model named `meta-llama/Llama-3-70b-chat-hf` (and several others) that should have showed up in the search.
7. Attempt to search for `meta-llama/Llama`.
8. Notice that no results show up again.

**Expected Behavior:**
Expected search to do partial match anywhere in the name.

**Actual Behavior:**
It appears to only match up to the first `/`.  I'm not sure what significance the separator has, but it is breaking search.

## Environment

- **Open WebUI Version:** v0.1.123
- **Operating System:** Docker image running in Ubuntu WSL in Windows 11
- **Browser (if applicable):** Firefox 125.0.3

## Reproduction Details

**Confirmation:**

- [ ] I have read and followed all the instructions provided in the README.md.
- [ ] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
None appear during search.

**Docker Container Logs:**
None appear during search.

**Screenshots (if applicable):**
N/A - can provide if needed, but repro steps hopefully are clear enough.

## Installation Method

Docker.

**Comment by tjbck** [comment]
Fixed on dev.
