### ISSUE TITLE
Request two models to display multiple columns.

### ISSUE THREAD

**Issue by igeekbb** [open-webui/open-webui#2381]
**Is your feature request related to a problem? Please describe.**
A single model performs quite well, but with multiple models, switching between models via arrows in the dialogue box is very inconvenient.
**Describe the solution you'd like**
I hope to increase the displayed content in multiple columns, at least two columns side-by-side, making it easier to compare how different models handle issues.

**Additional context**
![CleanShot 2024-05-19 at 08 44 28@2x](https://github.com/open-webui/open-webui/assets/154116268/b2261aaa-cab5-47ee-a637-3e3d812c5b90)

**Comment by Silentoplayz** [comment]
Related #2237
