### ISSUE TITLE
bug: unable to select default model in v0.1.125 in mobile interface

### ISSUE THREAD

**Issue by adan89lion** [open-webui/open-webui#2400]
# Bug Report

## Description

**Bug Summary:**
In a UI overhaul in v0.1.125, the "set default model" option is missing from the conversation page when the window is narrow enough or using in a mobile device.

**Steps to Reproduce:**
1. Update Open WebUI to v0.1.125
2. Open the service in a mobile browser or a narrow browser window (I "pin" the website as a PWA on my PC)
3. Start a conversation
4. Select a model
5. Noticing that you can't choose a model as a default one

**Expected Behavior:**
Users should be able to choose a default model under any circumstances.

**Actual Behavior:**
Users cannot choose the default model in mobile view.

## Environment

- **Open WebUI Version:** 0.1.125
- **Ollama (if applicable):** 0.1.38

- **Operating System:** Windows 10 22H2
- **Browser (if applicable):** Vivaldi 6.7.3329.31 (Stable channel) (64-bit) 

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
N/A

**Docker Container Logs:**
N/A

**Screenshots (if applicable):**
![image](https://github.com/open-webui/open-webui/assets/6585644/fcdfbd05-eca6-4a1a-b6f4-33fd684eccb2)
* You can set default models in desktop view (wide-screen mode)

![image](https://github.com/open-webui/open-webui/assets/6585644/a504f312-d95f-4944-b999-31b106f021c7)
* But the option is missing in mobile view (narrow-screen mode)

## Installation Method

Docker

## Additional Information

N/A

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
It's been removed as a part of a UI redesign.
