### ISSUE TITLE
enh: data/docs folder scan cron job

### ISSUE THREAD

**Issue by msorenss** [open-webui/open-webui#2439]
**Is your feature request related to a problem? Please describe.**
I suggest that we should have a autoscan option for the data/docs folder. Så that we scan the folder in a configurable time. Additionally it could be an api endpoint that we can trigger.

Usecase could be that we have other functions saving their data into data/docs folder and the folder gets scanned so documentation gets avalible to open-webui

**Comment by tjbck** [comment]
PR welcome!

**Comment by rogeryangugdsb** [comment]
Not a cron job, but below code might help. 

import time
from watchdog.observers import Observer
from watchdog.events import FileSystemEventHandler

def processfiles(changed_files):
    print("Changes detected in the following files:")
    for file in changed_files:
        #print(f"- {file}")
    # similar code like scan_docs_dir in main.py of https://github.dev/open-webui/open-webui

class ChangeHandler(FileSystemEventHandler):
    def __init__(self):
        self.changed_files = set()

    def on_any_event(self, event):
        if event.is_directory:
            return
        self.changed_files.add(event.src_path)

if __name__ == "__main__":
    path = "data/docs"
    event_handler = ChangeHandler()
    observer = Observer()
    observer.schedule(event_handler, path, recursive=False)
    observer.start()

    try:
        while True:
            if event_handler.changed_files:
                processfiles(event_handler.changed_files)
                event_handler.changed_files.clear()
            time.sleep(1)
    except KeyboardInterrupt:
        observer.stop()
    observer.join()
