### ISSUE TITLE
feat: Allow Admin to define system prompt for each user model

### ISSUE THREAD

**Issue by nonibytes** [open-webui/open-webui#2445]
**Is your feature request related to a problem? Please describe.**
A clear and concise description of what the problem is.

I want to have Admin create specific system prompts for each model that is exposed to the user. Today this can only be done using Ollama+Modelfiles, but I am using Open AI so model file isn't applicable.

**Describe the solution you'd like**
There are two possible solutions, we can make ollama accept regular ollama API and proxy the request to Open AI, and we define the system prompt in ollama.

We can also have the webUI support fine grain control of system prompts per model.

**Describe alternatives you've considered**
Writing a proxy layer that sends ollama requests to open ai.

**Additional context**
I want to have an interface that has different kinds of chatbots each with different behaviors, and based on openai prompts. Today I can do this with ollama, but I would ideally prefer to use open ai

**Comment by tjbck** [comment]
https://github.com/open-webui/open-webui/issues/665 will be partially resolved by https://github.com/open-webui/open-webui/pull/2140. I appreciate your patience.
