### ISSUE TITLE
[BUG] When i delete the latest message, I can't send the message

### ISSUE THREAD

**Issue by Yanyutin753** [open-webui/open-webui#2460]
# Bug Report

## Description

**Bug Summary:**
[Provide a brief but clear summary of the bug]

**Steps to Reproduce:**
[Outline the steps to reproduce the bug. Be as detailed as possible.]

**Expected Behavior:**
[Describe what you expected to happen.]

**Actual Behavior:**
[Describe what actually happened.]

## Environment

- **Open WebUI Version:** [0.1.125]
- **Operating System:** [e.g., Ubuntu 20.04]
- **Browser (if applicable):** [e.g., Chrome 100.0]

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

### Everything works fine at the beginning
![image](https://github.com/open-webui/open-webui/assets/132346501/878b4056-323e-4d1d-a3ea-bf4d2ccaaa3e)

### The second request was also fine, but after I clicked delete the second message
![image](https://github.com/open-webui/open-webui/assets/132346501/9792ec71-1808-4c38-a923-113cb14e3d43)

### The third message cannot be sent, and the message can only be sent normally if the page is refreshed
![image](https://github.com/open-webui/open-webui/assets/132346501/b110c7a7-0d95-447d-9b4a-747f8b2abd14)

## Note

Please After deleting a message,  can chat normally. It's better to delete the first message

**Comment by silentoplayz** [comment]
#2208 Most likely related

**Comment by silentoplayz** [comment]
Closing this PR as the bug report lacks sufficient information for developers to effectively debug the issue. I encourage you to please provide more detailed logs or context to help better understand and address the problem.  If you could update this PR with detailed logs and clear steps to reproduce the problem, I'm more than certain there is a developer out there somewhere that would be more than happy to revisit this PR and help resolve the issue.
