### ISSUE TITLE
enh: archived chats ui

### ISSUE THREAD

**Issue by peuportier** [open-webui/open-webui#2483]
Greetings,
 
I would greatly appreciate it if we could consider incorporating additional features into our system:
 
- An advanced search functionality in the archive box that would facilitate efficient searching through extensive archives.
- The ability to export the archive contents for easier management and accessibility. (Add export all archive)
- A feature allowing admins to view chat archiving in the admin panel list of users

Thank you very much in advance for considering these suggestions.
 
Best regards,

**Comment by tjbck** [comment]
![image](https://github.com/open-webui/open-webui/assets/25473318/d92c0dcb-cb03-4118-97b6-503538a17e04)
![image](https://github.com/open-webui/open-webui/assets/25473318/eb419a05-54d5-487d-912e-43c3d72a35fc)

Added to our dev branch!

**Comment by peuportier** [comment]
Super @tjbck  you the best. Super job. I've also see you've add in version 0.22 Mermaid. Guys thanks for the hardworking.

**Comment by ricky-davis** [comment]
+1 to "A feature allowing admins to view chat archiving in the admin panel list of users"
Is there a reason this shouldn't be a thing? Deleting chats can currently be disabled but if a user archives the chats the admins have no insight into what was said.

**Comment by rcdailey** [comment]
I see that there is search for archived chats but it doesn't seem to index the contents of the chat. Would there be a way to enable that?
