### ISSUE TITLE
Unable to Directly Set Model Parameters Through Advanced Parameters by Administrator

### ISSUE THREAD

**Issue by cokice** [open-webui/open-webui#2496]
# Bug Report

## Description
I set up OpenWebUI to share my OpenAI GPT with others. However, as the conversation history grows longer, it continuously sends all previous content to OpenAI, resulting in high costs. I want to address this issue by limiting the number of tokens transmitted or the number of chat messages. I've been trying to find a solution, such as configurations in the config file or environment variable settings, but I haven't found a place where I can make these changes. Perhaps I just haven't found it. 

**Expected Behavior:**
The expected result is that when I set the model parameters in the settings panel or environment variables and save them, they should apply to the default settings for all users.

**Actual Behavior:**
The settings do not apply to all users; they are only applied to my own settings.

## Environment

- **Open WebUI Version:** [e.g., 0.1.120]
- **Ollama (if applicable):** [e.g., 0.1.30, 0.1.32-rc1]

- **Operating System:** [e.g., Windows 10, macOS Big Sur, Ubuntu 20.04]
- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Screenshots (if applicable):**
![屏幕截图 2024-05-22 235737](https://github.com/open-webui/open-webui/assets/29631677/5b1a6494-d562-46d3-868d-401227121eaa)

## Installation Method

docker

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
Related https://github.com/open-webui/open-webui/issues/1268, https://github.com/open-webui/open-webui/issues/665 will be the recommended method to set params per model.

**Comment by cokice** [comment]
Sorry, after looking at several other issues, I still don’t understand how to set it up. Could you please point out an effective way to set it up?

**Comment by gaby** [comment]
@tjbck Was this stuff removed from the UI? There's no admin menu for setting model params anymore.
