### ISSUE TITLE
"Select a model" when previously started a conversation where the model has been removed and used a new model instead

### ISSUE THREAD

**Issue by LombudXa** [open-webui/open-webui#2506]
# Bug Report

## Description
When I start a conversation with a model which is no longer present and decide to use a new model and keep using that conversation, I always have to select a model again. This is not the case as long as I have this conversation opened. If I switch to another conversation, then back, I have to select a model again. Of course, I could start a new conversation to fix this issue but I'd like to have the same topics within one conversation.

**Bug Summary:**
I have to keep selecting a model when I started a conversation with a removed model when I log back in, change the conversation or simply leave that page.

**Steps to Reproduce:**
Start a conversation with any model, delete the model you've chosen for that conversation, open up said conversation again, select a new model and keep the conversation going. Then leave the page (conversation), reenter it and you have to select a new model although I have already new entries with a new model.

**Expected Behavior:**
Maybe it just should stick with the latest model selected rather than the initial model selected when starting the conversation.

**Actual Behavior:**
I believe that "Steps to Reproduce:" describes it already.

## Environment

- **Open WebUI Version:** [0.1.125] - 2024-05-19
- **Ollama (if applicable):** v0.1.38

- **Operating System:** Windows 11 23H2
- **Browser (if applicable):** Not browser related.

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.

## Logs and Screenshots

**Screenshots (if applicable):**
Started initial conversation with Llama2 (since I deleted Llama2, this is to be expected):
![Started_initial_conversation_with_llama2_01](https://github.com/open-webui/open-webui/assets/13348327/d39633e2-c9aa-4e6d-b84e-83c3904af9de)

After deleting Llama2, I select Llama3 to keep the conversation going:
![Now_using_llama3_02](https://github.com/open-webui/open-webui/assets/13348327/b380f6be-5bc0-4735-9008-08bbf220fdcc)

Reload the page or do any other action which will change the page, then go back to that conversation:
![After_refresh_select_model_again_03](https://github.com/open-webui/open-webui/assets/13348327/1ff50cd9-6989-4a91-b084-afbf3c26f845)

## Installation Method

Docker (Debian system)

## Additional Information

Not aware of anything to add here.

**Comment by tjbck** [comment]
Fixed on dev branch.

**Comment by LombudXa** [comment]
Cheers :)

**Comment by LombudXa** [comment]
Fixed :) Looks good now. I have tested it and it will now always stick with the latest used model when the conversation continues. Thanks.
