### ISSUE TITLE
enh: archive all button

### ISSUE THREAD

**Issue by cangkuai** [open-webui/open-webui#2508]
**Is your feature request related to a problem? Please describe.**
Yes, currently users need to manually clean chat history and archive chats in Ollama WebUI, which can be time-consuming and inconvenient.

**Describe the solution you'd like**
I would like to add a "Cleanup All" or "Archive All" button to the chat section of the Ollama WebUI. This button should automatically clear chat history or archive all relevant conversations.

**Describe alternatives you've considered**
One alternative is to provide an option in settings to enable automatic cleanup or archiving after a certain period or number of messages. However, this would still require user intervention.

**Comment by tjbck** [comment]
![image](https://github.com/open-webui/open-webui/assets/25473318/3db58021-9200-4f15-a765-94a5718712c5)

Delete all chats button already exists, archive all button would be a nice addition. PR welcome!

**Comment by cangkuai** [comment]
This feature is a commonly feature. It would be most beneficial to showcase it in the prime location of the homepage, ensuring easy access for users.

**Comment by tjbck** [comment]
Closing in favour of #2483
