### ISSUE TITLE
enh: hide signup when enable_signup = false

### ISSUE THREAD

**Issue by oregonpillow** [open-webui/open-webui#2521]
**Is your feature request related to a problem? Please describe.**

Within the admin-panel, when you can disable user sign-ups, the sign-up button still displays on the login page and will allow someone to go through with the process of entering their details, and only at the final moment when they click "Create Account" will it inform them that sign ups are disabled and they should contact administrator.

This behaviour is misleading. If a button exists that says "Sign up" it should actually allow sign ups otherwise it should be hidden. At least, it should be an option to hide it.

**Describe the solution you'd like**

When sign ups are disabled within admin panel the sign up button on login page is hidden.

**Describe alternatives you've considered**

Blocking the sign up path via reverse proxy but it's hacky and not a good solution.

**Comment by bitsokoservices** [comment]
Maybe a guest mode feature instead so we can have both guest mode and sign-ups. Maybe whitelisted models for signed up users would work?

**Comment by oregonpillow** [comment]
> Maybe a guest mode feature instead so we can have both guest mode and sign-ups. Maybe whitelisted models for signed up users would work?

I'm all for a guest mode but I think this should be a different feature as it's not mutually exclusive with hiding the sign up button; you could have a guest mode (no credentials required) regardless of the state of signs ups being enabled or not.

**Comment by bitsokoservices** [comment]
Actually that's a better approach, guest mode regardless of the state of signs ups being enabled or not then whitelist models for guests only. Our use case is to have a UI/modelfile for customers with public facing information and another with more private context for managers.

**Comment by tjbck** [comment]
![image](https://github.com/open-webui/open-webui/assets/25473318/bf57651b-822a-4b63-ab80-e99c5f13c8f7)


Added to our dev branch!

**Comment by tjbck** [comment]
@bitsokoservices Guest mode could be a separate feature request on it's own, feel free to open a new issue!
