### ISSUE TITLE
enh: better playground 

### ISSUE THREAD

**Issue by ehartford** [open-webui/open-webui#2547]
I would request system message to be editable in the chat interface.  Maybe hidden by default, but can be shown if desired.  I would like to be able to change the system message during a conversation.  Like this

<img width="1296" alt="image" src="https://github.com/open-webui/open-webui/assets/1117701/696fb311-baa7-45bc-9068-fe0e74ec4238">

**Comment by ehartford** [comment]
Yeah I know that it's possible to change it through some menus options. 

I wanted it to be more directly in the chat screen and easy to quickly change it.

I know that not all users will want it but maybe an option that enables or disables it, and it can be disabled by default.

**Comment by ehartford** [comment]
![image](https://github.com/open-webui/open-webui/assets/1117701/e314104c-031b-4f65-af46-e88fb0513bd7)

if you could add a flag there, that shows the system message box 

System message, it shouldn't be global.  It's per-conversation, not global.  also I found it using that system message even on other models.  (ie, I set it up for Dolphin but then it use the same system message on other models besides Dolphin). It's conceptually not correct to make system message a global setting.

**Comment by ehartford** [comment]
you see now how Yi-large is using the dolphin system message when it shouldn't, because of this.

**Comment by ehartford** [comment]
Just a flag there in the interface settings that lets me override the system prompt per-conversation, that's what I need.

**Comment by ehartford** [comment]
I am not asking for a "better playground".  I am asking for an option to add "system message" to the chat UI so that it can be set per-conversation.

**Comment by ehartford** [comment]
that is why ollama sets system message in each Modelfile (so each model has its very own default system message)

But then when chatting you can type "/set system <new system message>" to change it while chatting, for that conversation

**Comment by tjbck** [comment]
All great ideas, let's continue our discussion here: #619

**Comment by ehartford** [comment]
fine I'll fork it myself.

**Comment by justinh-rahb** [comment]
> fine I'll fork it myself.

godspeed 🫡
