### ISSUE TITLE
feat: create releases with ollama-webui version numbers

### ISSUE THREAD

**Issue by malteneuss** [open-webui/open-webui#255]
**Is your feature request related to a problem? Please describe.**
I would like to package Ollama-WebUI for the NixOS Linux distribution , but missing versions would make it difficult for users to distinguish newer versions from older ones (currently, we only have Git hashes).

**Describe the solution you'd like**
Create releases or pseudo-releases with version numbers (as frequent as feasible and with whatever breaking changes, changelog or version numbers as you please).

**Additional context**
NixOS or rather the Nix package manager (available for Mac and other Linux distributions) makes it very easy to get and run the app with a single, short terminal call. It will likely be as follows:
```
nix run nixpkgs#ollama-webui
```
Link to NixOS PR: https://github.com/NixOS/nixpkgs/pull/275448

Btw, thanks for this awesome UI (to me it's the best i found so far for Ollama).

**Comment by tjbck** [comment]
Hi, Thanks for creating this feature request! I'm actively looking into this and I was wondering if you're aware of any ways to somehow automate this? I suppose I could manually create new releases with any changes but that seems suboptimal, Thanks!

**Comment by anuraagdjain** [comment]
We could use the version in `package.json` and bump that every time a PR is merged to master using GHA. If there was only a change to the backend, in that case too we modify the version as the whole app is packaged together. Wdyt?

**Comment by tjbck** [comment]
@anuraagdjain Thank you for the suggestion, but the version "tracking" is being done from the backend now: https://github.com/ollama-webui/ollama-webui/blob/13881beeddb81824fc75f4272dc0088efec05216/backend/config.py#L34

I've been manually updating the version number from the line above, so I'm not so sure if using the version in `package.json` would be the best choice. Any other suggestions? Thanks as always!

**Comment by anuraagdjain** [comment]
To avoid manually bumping the version, I recommend something as done in this article https://medium.com/@johnathanmiller/github-actions-npm-version-bump-using-labels-on-pr-merge-8c716a488a64 . 
1. Automatically publishes a new version when PRs are merged. 
2. using the package.json's version you can add tags to git commit or generate changelogs ( https://blog.logrocket.com/automatically-generate-and-release-a-changelog-with-node-js/) 
3. You can read the package.json file and get the version property and return the value via the API. No need to maintain the version when `npm` can handle it. 


Since we've package.json, for above reasons I think its best to use it.

**Comment by hemangjoshi37a** [comment]
I think we should have a feature in which version update notification should be displayed if not running latest version of ollama-webui in settings and update button for downloading latest update should be displayed next to it. 
here we can also have a drop down menu to jump to particular version or nightly version that uses latest github code for latest update by pulling latest github repo code .

**Comment by hemangjoshi37a** [comment]
@rcgtnick this can be done in one particular way.
1 pull the latest docker image.
2 delete container id 
3 restart the container id of the latest running image.

Also this `upgrade` button can be shown to only those who are running it using docker by detecting how the software is run or how it is installed.

**Comment by nickthecook** [comment]
@hemangjoshi37a an app I am running in a container should not have that level of privilege in a production system.

That kind of architecture decision would make this app unsuitable for use outside of a development environment.

**Comment by justinh-rahb** [comment]
Agree with many here, I don't want an upgrade method within the app, Docker and Kubernetes already facilitate version control once we start getting versioned images. I can understand things are in too much flux right now for that, but I imagine once v1.0 is ready it would be appropriate to start tagging the Docker images with version numbers. For now I'm fine pulling the latest image periodically and redeploying my container, this is the Docker way.

**Comment by hemangjoshi37a** [comment]
How can we make a UI that is user-friendly to a dumb person proof? that is by providing dev level control at ease and with great UI/UX , for incorporating this we have to make this button possible. I have noticed in various opensource projects is that they lack UI/UX  most of them to say the least. If we can improve upon this then we can beat proprietary App world.

**Comment by anuraagdjain** [comment]
> Another way to look at it is whether or not updates to the web app are the concern of the web app itself. I think notifying of updates in the UI is fine, but actually trying to perform the update from within the web UI is bound not to work for all users.

I agree with this sentiment. By showing a small UI and a link to the article showing how to upgrade would be much beneficial than focusing on having the auto update mechanism. Again, it depends on the project maintainer to decide the roadmap so we could help them.

**Comment by anuraagdjain** [comment]
Auto update might be a good thing to bundle if this issue https://github.com/ollama-webui/ollama-webui/issues/470 is going to have more focus.

**Comment by Lanhild** [comment]
Indeed, releases are much needed for pulling the code using version numbers in various workflows.

**Comment by justinh-rahb** [comment]
> Indeed, releases are much needed for pulling the code using version numbers in various workflows.
> 
> Using automated releases you could also take advantage of the then newly created release to push the docker image with the same tag version.

All in the plan, Lan. I contributed a modified docker build action that will accomplish exactly this once we start tagging releases.

**Comment by Lanhild** [comment]
@justinh-rahb 

As properly versionned releases are not a thing right now, why not use the git commit hash in an automatic release workflow in the meantime?

**Comment by justinh-rahb** [comment]
> @justinh-rahb
> 
> As properly versioned releases are not a thing right now, why not use the git commit hash in an automatic release workflow in the meantime?

@Lanhild I had something like that in mind, ya. What do you think @tjbck do you think we can find a way to replace the build part of the version string with the hash during the docker build?

**Comment by Lanhild** [comment]
@justinh-rahb I've opened https://github.com/open-webui/open-webui/pull/839. That would add an automatic GitHub release workflow that tags releases with the short-form of the commit hash.

The same behavior could easily be adopted in the Docker building workflow.
Regards.

**Comment by justinh-rahb** [comment]
Looks like we got an extra `v` somewhere @tjbck

**Comment by tjbck** [comment]
@justinh-rahb #850 should fix it!
