### ISSUE TITLE
bug: CSS patch needed, Android Firefox totally unable to click response buttons

### ISSUE THREAD

**Issue by gamepad-coder** [open-webui/open-webui#2587]
# Bug Report

## Description

**=== Bug Summary ===**

**Environment**
- Firefox on Android

**More details at bottom**
- See: "Logs and Screenshots" section below<br>for examples in 4 environments (bug path on Firefox Mobile + happy path in Chrome Mobile)

**Main Idea**
- The buttons under the last response are totally blocked by the user's Prompt entry text box.

![firefox css bug, main idea](https://github.com/open-webui/open-webui/assets/65138515/9414e86d-8c36-4024-8297-4d2d4650eaa1)

> [!NOTE]
>   - Similar to https://github.com/open-webui/open-webui/issues/2231 
>       - **Workaround on PC**: empty the user input field to unblock the buttons
>
>   - However there is no workaround for Firefox on Anrdoid. 
>       - **No Workaround on Firefox Mobile**: Even if there is no text entered, these buttons are always 90% blocked by default on Anrdoid Firefox.

**=== Steps to Reproduce ===**

- [1] Fresh install using bundled ollama command from the README
   - `docker run -d -p 3000:8080 --gpus=all -v ollama:/root/.ollama -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:ollama`

- [2] Install `llama3` using the `open-webui` settings UI

- [3] Get address
   - Local host machine ip from: `ipconfig` (windows) / `ip a` (linux), i.e. `10.0.0.1` for this example
   - Port being served using `docker ps` (or just `3000` if you didn't change the command from step [1])

- [4] On an Android phone, open latest Firefox and navigate to `10.0.0.1:3000` (just an example, your ip:port will vary)

- [5] Say something to an AI

- [6] Once at least one AI Response exists in the chat, try to click one of the buttons under the Response,
   - such as (i) `Generation Info` or `Continue Response` or `Regenerate`.

- [7] Observe it's almost impossible to click these buttons since they're all blocked by the div for the user input.

**=== Expected Behavior ===**

- Should be able to see these buttons.

**=== Actual Behavior ===**

- Can't see these buttons.

## Environment

- **Open WebUI Version:** `v0.1.125`
- **Ollama (if applicable):** `ollama version is 0.1.38`

- **Operating System:** `Windows 11`, `WSL2 `to serve, `Android Phone` to test
- **Browser (if applicable):** `Firefox 126.0` (2024-05-09)

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
   - (n/a hopefully, lol)
   - It seems like Firefox Logs on Android are kind of cumbersome to grab, but lmk if that's necessary for this bug report.
- [ ] I have included the Docker container logs. 
   - (n/a), frontend CSS issue

## Logs and Screenshots

**=== Browser Console Logs ===**

- N/A

**=== Docker Container Logs ===**

- N/A

**=== Screenshots (if applicable) ===**

**❌ Firefox Mobile (Android) -- Totally Broken**

https://github.com/open-webui/open-webui/assets/65138515/9e3cb0f9-8b2b-4457-8d6d-f4dc705912d7

**✅ Firefox Mobile (PC, Devtools) -- Can't reproduce**

https://github.com/open-webui/open-webui/assets/65138515/7cbbb06c-9172-49c5-a7b9-20725c4e7318

**✅Chrome Mobile (Android) -- Totally Fine**

https://github.com/open-webui/open-webui/assets/65138515/2c021fe6-8edf-44b4-b37b-f6917cbe555d

**✅/ ❌ Chrome PC -- Only breaks if input box becomes too tall**

This example is exactly the same as https://github.com/open-webui/open-webui/issues/2231

![bug report - PC - input box blocks bottom of chat (only if too much text)](https://github.com/open-webui/open-webui/assets/65138515/245f468a-6e6e-4f7f-9b9c-0008ae0cc519)

## Installation Method

- See: "Steps to Reproduce" section above

**Comment by tjbck** [comment]
Duplicate #2504, actively being worked on!

**Comment by gamepad-coder** [comment]
✅  [Totally patched](https://github.com/open-webui/open-webui/issues/2504#issuecomment-2143654390) 🎉
