### ISSUE TITLE
feat: tooltips text for icons

### ISSUE THREAD

**Issue by bharath063** [open-webui/open-webui#259]
**Is your feature request related to a problem? Please describe.**
Please add tooltips to icons which do not have any text attached to them

**Describe the solution you'd like**
A tiny description of the what the icon does should appear on hover

**Comment by bhulston** [comment]
I might work on [this](https://github.com/ollama-webui/ollama-webui/issues/337) issue first, but will see if I can make this QOL change sometime next week. At the very least I can write descriptions for the different icons.

**Comment by hemangjoshi37a** [comment]
as I have metioned in #515 
Feat. Req. : 
**Functionality:**
- When a user hovers their mouse over any item in the left side panel, a small tooltip or hint should appear.
- This tooltip will contain a concise yet informative description of the item's function or purpose.

**Example:**
- Hovering over `Modelfies` might display a hint like "Configure and manage your model settings."
- Hovering over `Prompts` could show "Access and create new prompts."
- For `Documents`, the hint might be "View and organize your documents."

**Comment by dannyl1u** [comment]
> I might work on [this](https://github.com/ollama-webui/ollama-webui/issues/337) issue first, but will see if I can make this QOL change sometime next week. At the very least I can write descriptions for the different icons.

Hi @bhulston are you currently working on this issue? If not I'd be happy to implement this feature. Thanks!

**Comment by tjbck** [comment]
Added custom Tooltip component that can be used everywhere, feel free to make a PR!
