### ISSUE TITLE
issue: abnormal md format output

### ISSUE THREAD

**Issue by bahuzh** [open-webui/open-webui#2603]
# Bug Report

## Description

**Bug Summary:**
Markdown format output, displaying abnormally.

**Actual Behavior:**

2. **Enter the Pod**:
   Once you have the Pod's name, you can use the `kubectl exec` command to enter the Pod:

   ```bash
   kubectl exec -it <pod-name> -n ingress-nginx -- /bin/bash
   ```

<img width="768" alt="image" src="https://github.com/open-webui/open-webui/assets/120018648/75f6b2fe-6318-4851-9d7b-f3008bafe2b8">

-----

<img width="700" alt="image" src="https://github.com/open-webui/open-webui/assets/120018648/387e191b-2e53-4864-b67b-05dd01ea3ffb">

## Environment

- **Open WebUI Version:**  ghcr.io/open-webui/open-webui:main

- **Operating System:** [e.g., Windows 10, macOS Big Sur, Ubuntu 20.04]
- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]

**Comment by mtran-code** [comment]
![CleanShot 2024-06-10 at 11 04 59@2x](https://github.com/open-webui/open-webui/assets/65685501/55b6488e-9666-4b54-978f-d3421679db24)

Related: Having code blocks within list items:
- Doesn't use normal code block formatting (with copy code functionality)
- Uses HTML entity encoding for certain symbols; not ideal for code (e.g. `&lt;` instead of `<`)

**Details:**
Open WebUI v0.3.1 running through Docker on macOS
OpenAI model gpt-4o, also tested with phi3:latest on Ollama with same results
Browser: Firefox 126.0.1 (64-bit)

**Comment by imoyy** [comment]
Almost all models will be output in this way, so most related content will be rendered incorrectly :<

**Comment by rztaylor** [comment]
This is particularly annoying as so many models seem to prefer using list based responses when answering tech related queries which often contain many inline code examples with angled brackets used to denote placeholder text.

**Comment by GrayXu** [comment]
I found that no one seems to have explained why the input in open-webui isn't rendered in markdown format. For example, when I want to input a code segment but it still outputs as normal text, it's quite strange.

**Comment by justinh-rahb** [comment]
> I found that no one seems to have explained why the input in open-webui isn't rendered in markdown format. For example, when I want to input a code segment but it still outputs as normal text, it's quite strange.

This is unrelated to the matter at hand.

**Comment by GrayXu** [comment]
@justinh-rahb get it, but just wanted to say that there are still some issues with the open webui Markdown rendering.

**Comment by christian-taillon** [comment]
Drives my team crazy. Presently, I'm attempting to instruct the output to remove indentation from the blocks in the system prompt, but it is imperfect. I think a proper fix would be to render the `code` even if it is nested in a `list`. This would align with some other markdown rendering such as GitHub's.  

Only non-indented code is rendered:
```bash
grep -E 'pattern' file.txt
```

Code in a list isn't. For example, this would not receive a code block visualization nor include syntax highlighting:  
- Listed item
- ```bash
  grep -E 'pattern' file.txt
  ```


**Details:**  
Ollama v0.3.11 on Docker
Linux Debian
Chrome 127.0.6533.88 (various users/browsers)

**Comment by bahuzh** [comment]
version v0.3.13 has resolved this issue.

**Comment by bahuzh** [comment]
Still not displayed correctly in some cases

3. **Adjust Input Method Settings**:
   - Open “Settings” > “Time & Language” > “Language & Region”.
   - In the “Preferred languages” section, find your current input method, click on the options on the right, and adjust the settings.

<img width="896" alt="image" src="https://github.com/user-attachments/assets/a3b77783-48ba-496f-8296-d5fee6d74f7d">

**Comment by bahuzh** [comment]
version v0.3.16 test passed
