### ISSUE TITLE
feat: Prompt templates should be able to insert clipboard image and show image. (Image-Text-to-Text /Visual Question Answering /Document Question Answering)

### ISSUE THREAD

**Issue by tqangxl** [open-webui/open-webui#2618]
add feature to upload images directly from my clipboard,  When using multimodal models that combine text and images, such as Image-Text-to-Text, Visual Question Answering, or Document Question Answering, it is quite common to utilize images. Having a feature that allows for the easy uploading of images from your clipboard, like a prompt template, would be more convenient.

![image](https://github.com/open-webui/open-webui/assets/9669944/bbc6d257-3d5e-42c1-ba14-e07f66a2a41f)

![image](https://github.com/open-webui/open-webui/assets/9669944/f048b84c-829b-46e3-8ec7-dd78d2e50501)

**Comment by tjbck** [comment]
![image](https://github.com/open-webui/open-webui/assets/25473318/e4691ee8-2661-4177-8662-e5a8355c8575)

Added on dev!
