### ISSUE TITLE
Latex cannot render correctly with \( \) or multi-lines

### ISSUE THREAD

**Issue by xiao-zy19** [open-webui/open-webui#2629]
# Bug Report

## Description

**Bug Summary:**
GPT sometimes gives responses across lines, and it sometimes uses \( \) instead of \[ \], both situations cannot be rendered correctly.

The rendered response:
![1](https://github.com/open-webui/open-webui/assets/57801570/7e8e7e27-0048-4afd-bb6f-ae3a673b8e6a)

Raw response:
![2](https://github.com/open-webui/open-webui/assets/57801570/9be8adac-827a-42c1-9573-353264c67804)

**Steps to Reproduce:**
Simply tell the model:
read after me:
\( p^* \)
\[
p^*
\]

**Expected Behavior:**
Render these latex responses correctly.

**Actual Behavior:**
The responses are not correctly rendered in both situations (see rendered response).

## Environment

- **Open WebUI Version:** [e.g., 0.1.125]
- **Ollama (if applicable):** NA

- **Operating System:** Ubuntu 20.04 & win 11
- **Browser (if applicable):** Chrome 120.0.6099.71

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
No errors in logs

**Screenshots (if applicable):**
See Description part

## Installation Method

Docker

## Additional Information

NA

**Comment by tjbck** [comment]
#2615
