### ISSUE TITLE
enh: agent RAG

### ISSUE THREAD

**Issue by MarlNox** [open-webui/open-webui#2630]
### Feature Request 

ADD mode in searching where the agent finds the most relevant documents, and let's the user choose with which to proceed. 
Additionally, the similarity search could be enhanced with the document names where they also get sifted when searching for relevant passages. 

**Is your feature request related to a problem? Please describe.**
Searching using just similarity can retrieve unneeded passages, or can provide irrelevant results. 
I'm  suggesting a mode of interaction with the agent. where the agent provides a list of relevant documents to the user, to proceed with further queries, after searching for the relevant documents across all docs. 

**Describe the solution you'd like**
I would like a feature where, after asking a question, the system identifies and lists relevant documents that contain information related to my query. I can then select one or more of these documents to interact with. From that point on, the system will use the selected documents to extract information and answer any further questions I have.

**Describe alternatives you've considered**
An alternative solution could be a more advanced search functionality that allows for better filtering and sorting of document search results. Add graph search in addition to the similarity search we do now, add more detail on each passage, to include document names etc. Provide the system with a map of documents, to answer questions like, How many documents, and which documents, talk about "X Topic".

**Additional context**
Here is a practical example to illustrate how the feature would work:

**User:** How can I improve my business's social media engagement?

**AI:** Relevant documents with information on your question are these:
1. "Social Media Strategies for Businesses"
2. "Engagement Techniques for Online Marketing"
3. "Case Studies on Social Media Success"

Please choose one or more documents to interact with.

**User:** I choose documents 1 and 2.

**AI:** Great! You have selected:
1. "Social Media Strategies for Businesses"
2. "Engagement Techniques for Online Marketing"

You can now ask further questions based on these documents.

**User:** What are the top three strategies mentioned in these documents?

**AI:** According to the selected documents, the top three strategies for improving social media engagement are:
1. Creating high-quality, shareable content.
2. Engaging with your audience through comments and direct messages.
3. Using targeted advertising to reach your desired audience.

**Comment by tjbck** [comment]
Related https://github.com/open-webui/pipelines
https://github.com/open-webui/pipelines/issues/9

**Comment by tjbck** [comment]
Closing in favour of #5571
