### ISSUE TITLE
feat: team workspace

### ISSUE THREAD

**Issue by ga-it** [open-webui/open-webui#2632]
**Is your feature request related to a problem? Please describe.**
OpenAI have team features in ChatGPT for sharing Custom GPTs, etc

**Describe the solution you'd like**
It would be very useful to be able to add users to teams and then allow teams to interact in a common workspace. This should allow sharing of custom prompts, documents, etc across a team

**Describe alternatives you've considered**
Currently team members see admin prompts from the / menu but are not able to create prompts. Prompts cannot be shared with a specific group of team members.

**Additional context**
None

**Comment by tjbck** [comment]
Closing in favour of https://github.com/open-webui/open-webui/issues/2924
