### ISSUE TITLE
enh: Optimize the style of the ResponseMessage

### ISSUE THREAD

**Issue by jasinliu** [open-webui/open-webui#2644]
**Is your feature request related to a problem? Please describe.**
As title.  The space between paras is too large.

Before:
![image](https://github.com/open-webui/open-webui/assets/85552719/67ba57e2-bad8-4927-97ef-d284a17197a8)

After:
![image](https://github.com/open-webui/open-webui/assets/85552719/f6daea45-d1c6-430b-b475-8ee738c94754)

**Comment by tjbck** [comment]
Help wanted! PR welcome!

**Comment by tjbck** [comment]
Thanks!
