### ISSUE TITLE
Feat: Refine Notification Behavior to Prevent Excessive Alerts During Task Generation

### ISSUE THREAD

**Issue by bannert1337** [open-webui/open-webui#2663]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I use Open WebUI with notifications enabled and shift focus to another application. The system bombards me with a continuous stream of notifications until the generation is complete, which is extremely annoying as these notifications trigger sound alerts and are constantly displayed. This issue was experienced on an Arch-based system using Firefox.

**Describe the solution you'd like**
I would like the notification system to be refined to prevent excessive alerts. Ideally, if a task is still in progress, there should be an option to either mute subsequent notifications until the task is complete or aggregate multiple notifications into a single alert to minimize disruption.

**Describe alternatives you've considered**
- Allowing users to disable notifications entirely while ensuring a single completion notification is sent once tasks are finished.
- Introducing a silent mode where notifications are accumulated and displayed or sounded at intervals instead of real-time.
- Providing user customization options for notification behavior within the settings, such as sound alerts, frequency of notifications, and grouping of related notifications.

**Additional context**
This is a significant usability concern that could affect productivity, especially for users performing generation tasks frequently. A more streamlined notification approach would greatly enhance the user experience. Screenshots below illustrate the rapid succession of notifications currently being experienced:

[Notification DDoS](https://github.com/open-webui/open-webui/assets/58707896/0809e7e2-5e69-4010-8c62-becfe5a45214)

**Comment by bannert1337** [comment]
Also happens when focus is on different browser tab.

**Comment by tjbck** [comment]
Fixed on dev!
