### ISSUE TITLE
Feat: Conditional Display of Message Edit Options in Shared Chats

### ISSUE THREAD

**Issue by bannert1337** [open-webui/open-webui#2664]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I access a shared chat in Open WebUI and see the message edit options, but I cannot use them. It creates confusion and provides a poor user experience when edit options are shown but not functional.

**Describe the solution you'd like**
I would like the message edit options to be removed entirely when a chat is shared and accessed by an unauthenticated user. Alternatively, the message edit options should only be displayed if the user accessing the chat is logged in and has the necessary permissions to edit messages.

**Describe alternatives you've considered**
An alternative solution could be to disable the message edit options for unauthenticated users while keeping the UI elements visible, perhaps with a tooltip indicating that the user needs to log in to edit messages. Another option could be to hide the edit options by default and provide a notification or prompt encouraging the user to log in to access the edit functionality.

**Additional context**
Here is a screenshot showing the current state where the edit options are visible but not usable in a shared chat: 
![Screenshot 2024-05-30 at 10-27-12 Essence of Domain Driven Desig  Open WebUI](https://github.com/open-webui/open-webui/assets/58707896/851bdc71-4eb6-4482-918a-8163b0de0f9d)

Additionally, making these options conditional based on the user's authentication status would enhance the overall user experience and make the interface cleaner and more intuitive.

**Comment by tjbck** [comment]
Good catch, PR welcome!

**Comment by tjbck** [comment]
Fixed on dev! Will be included in 0.2.0!
