### ISSUE TITLE
feat: Add Assistant/Custom GPT Shortcut to Side Panel

### ISSUE THREAD

**Issue by bannert1337** [open-webui/open-webui#2698]
**Is your feature request related to a problem? Please describe.**
I'm always frustrated when I have to navigate through multiple menus to access my custom models (assistants, custom GPTs). This process is time-consuming and disrupts my workflow.

**Describe the solution you'd like**
I would like to have the ability to create shortcuts to custom models directly on the side panel. When clicked, these shortcuts should open a new chat with the selected model. The shortcut should display the image and name of the custom model. Additionally, clicking the edit button on the shortcut should open the custom model edit modal window. Pressing and holding the shortcut for a specific threshold should unfold all chats associated with this specific model.

**Describe alternatives you've considered**
An alternative solution could be to have a dedicated dropdown menu for custom models, but this would still require additional clicks and navigation, which is less efficient than having direct shortcuts.

**Additional context**
This feature would greatly enhance the user experience by streamlining access to custom models. It would be particularly useful for users who frequently switch between different models.

**Comment by spammenotinoz** [comment]
Hi sorry I am new so could be missing something, after I add custom model they are selectable in the drop down "model selection" along with all the standard models.  They are also selectable via @ shortcut.
Having a different model selection menu for custom models, seems confusing.
