### ISSUE TITLE
wrong response

### ISSUE THREAD

**Issue by jacksonlutw** [open-webui/open-webui#2716]
I am new for llama3. Using Ollama + Docker + Open-webui for three days.
Suddently this morning all of llama3 response on open-webui always with {} when I input anything via open-webui but 
normal on Ollama native mode. I tried to re-install everything but still got same issue.
Anyone can help ?

**Comment by justinh-rahb** [comment]
Make sure this is set to `Default` and not `JSON`:

<img width="753" alt="Screenshot 2024-06-02 at 9 17 01 AM" src="https://github.com/open-webui/open-webui/assets/52832301/094ce31c-fc0d-4ce9-9e69-618de1b54a21">

**Comment by jacksonlutw** [comment]
yes, thank you. My mistake. Solved.
