### ISSUE TITLE
Rendering Issue, new install not showing fully

### ISSUE THREAD

**Issue by AI-MickyJ** [open-webui/open-webui#2726]
# Bug Report

## Description

**Bug Summary:**
Menu on left of UI is limited to display only New Chat, Workspace & Search

![image](https://github.com/open-webui/open-webui/assets/171421294/45892692-31b9-485f-b54c-5ad29982eabb)

**Steps to Reproduce:**
Fresh install with docker and ollama install conditions met

**Expected Behavior:**
Expected to display Documents, Modelfiles and Prompts

**Actual Behavior:**
Multiple attempts to install on diff systems result in limited render

## Environment

- **Open WebUI Version:** 0.2.0
- **Ollama:** 0.1.41
- **Docker Desktop:** 4.30.0

- **Operating System:** Windows 11 & replicated on  macOS Sonoma 14.5
- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]

## Reproduction Details

**Confirmation:**

- [X ] I have read and followed all the instructions provided in the README.md.
- [X ] I am on the latest version of both Open WebUI and Ollama.
- [X ] I have included the browser console logs.
- [X ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
n/a

**Docker Container Logs:**
n/a

**Screenshots (if applicable):**
See above

## Installation Method

> docker run -d -p 3000:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by justinh-rahb** [comment]
It's been moved inside of Workspace.
