### ISSUE TITLE
Unable to install and run docker container on AMD GPU

### ISSUE THREAD

**Issue by vikingnope** [open-webui/open-webui#2727]
# Bug Report

## Description

**Bug Summary:**
I am trying to install and run using the bundled Ollama with GPU Support and I get the following:

```
 docker run -d -p 3000:8080 --gpus=all -v ollama:/root/.ollama -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:ollama
Unable to find image 'ghcr.io/open-webui/open-webui:ollama' locally
ollama: Pulling from open-webui/open-webui
09f376ebb190: Already exists
276709cbedc1: Already exists
a5b1646776ed: Already exists
cc3e860a837e: Already exists
67cbcd94260c: Already exists
e358ace12219: Already exists
4f4fb700ef54: Already exists
508bd2c9e02f: Already exists
523f09651a87: Already exists
a007f02cb6b1: Pull complete
a2b47458994b: Pull complete
4ffea750a65b: Pull complete
9e854451f3a7: Pull complete
57faa2f5ecaa: Pull complete
800f78c4ed40: Pull complete
43f711bf66de: Pull complete
Digest: sha256:9b22fe41eaa0140c272dce431b31049a70cb458245b7ce30564d9010565a508d
Status: Downloaded newer image for ghcr.io/open-webui/open-webui:ollama
da035db0a09ea3d1f235047016abe0bdefe156d6373c55407c6a645ba0d8fa6d
docker: Error response from daemon: failed to create task for container: failed to create shim task: OCI runtime create failed: runc create failed: unable to start container process: error during container init: error running hook #0: error running hook: exit status 1, stdout: , stderr: Auto-detected mode as 'legacy'
nvidia-container-cli: initialization error: WSL environment detected but no adapters were found: unknown.

```

**Steps to Reproduce:**
Try to run and install on AMD GPU

**Expected Behavior:**
Should work normally

**Actual Behavior:**
Gives Nvidia error

## Environment

- GPU: AMD RX7800XT
- CPU: Ryzen 5 5600X
- OS: Windows 11

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [ ] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Installation Method

[Describe the method you used to install the project, e.g., manual installation, Docker, package manager, etc.]

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by justinh-rahb** [comment]
Our `:ollama` tagged images are only supported on Nvidia GPUs.

**Comment by vikingnope** [comment]
@justinh-rahb  Is there any other command I can use?

**Comment by justinh-rahb** [comment]
No official support for our container image. Ollama themselves do have a `:rocm` version, but we aren't using it as of right now.

**Comment by kilrau** [comment]
Can we reopen this? Looking for AMD GPU support of the bundled image too

**Comment by vikingnope** [comment]
@kilrau, you should have a look at this:  https://dev.to/berk/running-ollama-and-open-webui-self-hosted-4ih5

To be clear, I never got this working on Windows, only a few days ago I switched to Arch Linux and that worked.
