### ISSUE TITLE
Context Length Setting Appears to Have No Effect

### ISSUE THREAD

**Issue by cokice** [open-webui/open-webui#2728]
# Bug Report

## Description
The Context Length setting does not seem to take effect. Logically, setting the context length to 9 is already very extreme, but the program still seems to remember my previous questions.

**Steps to Reproduce:**
The setting doesn't work whether I configure it in the personal settings or in the Advanced Params of the workspace model. I am certain that I have saved the settings.

**Actual Behavior:**
Logically, it should not be able to know what my first question was.

## Environment

- **Open WebUI Version:** [0.2.0]

- **Operating System:** [Ubuntu 20.04]
- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Screenshots (if applicable):**
<img width="1201" alt="截屏2024-06-02 23 55 13" src="https://github.com/open-webui/open-webui/assets/29631677/bdf6dfc7-c544-4892-b82b-7dc8c209f8ee">
<img width="1248" alt="截屏2024-06-02 23 56 02" src="https://github.com/open-webui/open-webui/assets/29631677/de8c41a6-453b-4df5-aa2e-674766eb19bc">
<img width="747" alt="截屏2024-06-02 23 59 11" src="https://github.com/open-webui/open-webui/assets/29631677/045da07f-4172-4b0e-b146-6884d50e22f5">

## Installation Method

docker

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by justinh-rahb** [comment]
**Context Length** cannot be set on OpenAI (or compatible) API.

**Comment by cokice** [comment]
> **Context Length** cannot be set on OpenAI (or compatible) API.
what should I do to limit the context length or the history length of the OpenAI API? I really need it (because too long a context brings higher costs).:

**Comment by justinh-rahb** [comment]
Seems an ideal case for the conversation turn limiter pipeline in our new [Pipelines](https://GitHub.com/open-webui/pipelines) sister project.
