### ISSUE TITLE
enh: ts for memories and ability to EDIT memory items

### ISSUE THREAD

**Issue by ItsNoted** [open-webui/open-webui#2729]
Adding timestamps to memories so we don't have to state the date and time would be awesome. The ability to edit our memory items would also be helpful. Thank you for such an amazing software!

**Comment by tjbck** [comment]
Added in dev!

**Comment by Fusseldieb** [comment]
Is there a way to edit the memory programatically?

**Comment by bannert1337** [comment]
@Fusseldieb I saw this action button to add to memory. Maybe this can help you:
https://openwebui.com/f/pad4651/add_to_memories_action_button/

**Comment by Fusseldieb** [comment]
@bannert1337 Thank you! This was exactly what I was searching for. Looks like together with "Filters" and "__event_emitter__" it does exactly what I want. 

May your pillow be cold on both sides. :)
