### ISSUE TITLE
bug: Using Enter/Return key to autocomplete prompts/model selection resulted in sending it as chat instead

### ISSUE THREAD

**Issue by Syakyr** [open-webui/open-webui#2751]
# Bug Report

## Description

**Bug Summary:**
Using the Enter/Return key to autocomplete prompts/model/website selection would result in sending the incomplete prompt/model selection command instead.

**Steps to Reproduce:**
- Try to type part of the selection process using `/`, `@`, `#`, etc. ( I have not tested the other shortcut selections)
- Select the prompt/model/website you want to resolve
- Click Enter/Return key

**Expected Behavior:**
It should just select the prompt/model/website that you want and you can continue writing your chat prompt

**Actual Behavior:**
It sends the incomplete prompt/model/website as the chat prompt

## Environment

- **Open WebUI Version:** 0.2.2
- **Ollama (if applicable):** Not applicable, using external LiteLLM server as backend

- **Operating System:** Docker 26.1.3 on Debian 6 (server)
- **Browser (if applicable):** Brave 1.66.118 (Chromium 125.0.6422.147)

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of ~~both~~ Open WebUI ~~and Ollama~~.
- [x] I have included the browser console logs.
- ~~I have included the Docker container logs.~~

## Logs and Screenshots

**Browser Console Logs:**
[open-webui-1717390482348.log](https://github.com/user-attachments/files/15528928/open-webui-1717390482348.log)

**Docker Container Logs:**
not applicable

**Screenshots (if applicable):**
![Peek 2024-06-03 12-50](https://github.com/open-webui/open-webui/assets/23415399/8d7051f0-71c4-4143-92c7-26552a05cf71)

## Installation Method
Docker

## Additional Information
None

**Comment by tjbck** [comment]
Should be fixed with the latest, Let me know if the issue persists!
