### ISSUE TITLE
Regarding the Issue with Chinese Input Method in Web UI:

### ISSUE THREAD

**Issue by Bahamutzerox** [open-webui/open-webui#2756]
Description

Bug Summary:
When using the Zhuyin input method on a MAC in the Web UI, pressing the enter key once to confirm character selection results in the immediate sending of the text, causing incorrect input. A similar issue occurs with the Japanese input method.

Steps to Reproduce:

Open the Web UI on a MAC.

Switch to the Zhuyin input method for Chinese (or Japanese input method).

Start typing a Chinese (or Japanese) sentence.

Press the enter key to confirm the character selection.

Expected Behavior:
The input method should allow confirming the character selection first and only send the text when the enter key is pressed a second time.

Actual Behavior:
The system sends the text as soon as the enter key is pressed the first time to confirm character selection, leading to premature submission and incorrect input.

Environment

Open WebUI Version: latest version

Ollama (if applicable): latest version

Operating System: macOS Sonoma 14.5

Browser (if applicable): Chrome 125.0.6422.113

**Confirmation:**

- [ ] I have read and followed all the instructions provided in the README.md.
- [ ] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Installation Method

Docker

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by xiao-zy19** [comment]
I'm having the same issue. I had to revert to version v0.1.125 to use my input method normally.

**Comment by tjbck** [comment]
Taking a look!

**Comment by tjbck** [comment]
Unable to test this on my end, but should be fixed on dev branch now! Let me know if the issue persists!

**Comment by minamijoyo** [comment]
I've confirmed that the issue with Japanese input has been fixed in v0.2.3. Thank you!
