### ISSUE TITLE
enh: improve accessibility against WCAG 2.1

### ISSUE THREAD

**Issue by jooyoungseo** [open-webui/open-webui#277]
I am grateful for this fantastic and potentially accessible solution.

While using the web UI with a screen reader, I've noticed that many of the buttons are unlabeled. Adhering to the Web Content Accessibility Guidelines (WCAG) 2.1 would significantly enhance the accessibility and inclusivity of this project, making its benefits more universally available.

**Comment by tjbck** [comment]
Hi, I've been thinking about adding aria labels to all the field/buttons as well but didn't have the time to get around to it, as I'm currently prioritising adding other core features (RAG, Web browsing, etc). I'll get around to it when I can but if you (or anyone) manages to implement it, feel free to make a PR! Thanks!

**Comment by hemangjoshi37a** [comment]
as I have metioned in #515 
Feat. Req. :  ( in left hand side panel )
**Functionality:**
- When a user hovers their mouse over any item in the left side panel, a small tooltip or hint should appear.
- This tooltip will contain a concise yet informative description of the item's function or purpose.

**Example:**
- Hovering over `Modelfies` might display a hint like "Configure and manage your model settings."
- Hovering over `Prompts` could show "Access and create new prompts."
- For `Documents`, the hint might be "View and organize your documents."

**Comment by mhussaincov94** [comment]
hi,
screen reader users don't use the mouse.
we use keybord navigation.
I use orca the screen reader on linux.
up and down arrow keys, screen reader key b to navigate all buttons on the page the c key to navigate all comboboxes etc.
pressing the shift key + b goes to the last button well the button before the one you are on.
it would would be good if all buttons and other controls had correct labels on them.
Majid

**Comment by devinprater** [comment]
I would be greatful if the buttons were labeled as well.

**Comment by tjbck** [comment]
Closing in favour of #2790
