### ISSUE TITLE
enh: Ability to empty/toggle rag context

### ISSUE THREAD

**Issue by GobDevv** [open-webui/open-webui#2804]
**Is your feature request related to a problem? Please describe.**
I am not sure.

**Describe the solution you'd like**
I think having the ability to end/clear the rag generated messages would be super helpful, Instead of having to open a new chat entirely and get the LLM up to speed.
**Describe alternatives you've considered**
N/A
**Additional context**
N/A

**Comment by Shamepoo** [comment]
Agree, the attacted/selected document cannot be removed in a chat, have to start a new chat to get rid of it. It would be nice to have a switch to control it.

**Comment by tjbck** [comment]
This behaviour should be fixed on the latest!
