### ISSUE TITLE
HTTP Basic Auth not working on OLLAMA_BASE_URL

### ISSUE THREAD

**Issue by TheMcSebi** [open-webui/open-webui#2814]
# Bug Report

## Description

**Bug Summary:**
HTTP Basic Auth not working on OLLAMA_BASE_URL, e.g. https://user:pass@ollama-host.tld

**Steps to Reproduce:**
Use a ollama proxy requiring basic auth for setup.

**Expected Behavior:**
Authentication works as expected

**Actual Behavior:**
No connection with the ollama server is possible

## Environment

- **Open WebUI Version:** 0.2.2
- **Ollama (if applicable):** 0.1.41

- **Operating System:** Ubuntu 20.04 (on WSL2)
- **Installation type:** docker command: docker run -d -p 3000:8080 -e NODE_TLS_REJECT_UNAUTHORIZED=0 -e OLLAMA_BASE_URL=https://user:pass@ollama-host.internalnetwork.tld/ -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main

## Reproduction Details

The bug is present in the ollama-python package and will propably be fixed once this PR is accepted: https://github.com/ollama/ollama-python/pull/61
I didn't investigate the open-webui code, so I'm not sure if there's stuff along the way that might breaking things, but as the full url shows up in the web interface on the Ollama API config line I'm quite certain nothing on open-webui's end needs to be done.

**Comment by tjbck** [comment]
#2305
