### ISSUE TITLE
bug: HTML entities not rendered correctly in messages

### ISSUE THREAD

**Issue by bannert1337** [open-webui/open-webui#2815]
# Bug Report

## Description

**Bug Summary:**
HTML entities such as `&lt;` and `&gt;` are not being rendered correctly in messages. Instead of displaying `<` and `>`, the entities are shown as plain text.

**Steps to Reproduce:**
1. Send a message containing HTML entities like `&lt;` and `&gt;`.
2. Observe the rendered message.

**Expected Behavior:**
The HTML entities `&lt;` and `&gt;` should be rendered as `<` and `>` respectively.

**Actual Behavior:**
The HTML entities are displayed as plain text (`&lt;` and `&gt;`).

## Environment

- **Open WebUI Version:** [e.g., 0.1.120]
- **Ollama (if applicable):** [e.g., 0.1.30, 0.1.32-rc1]

- **Operating System:** [e.g., Windows 10, macOS Big Sur, Ubuntu 20.04]
- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]

## Reproduction Details

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [X] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

**Comment by bannert1337** [comment]
An example message from GPT-4o:
```
This will list all processes related to the VM with ID 121. If you see any relevant processes, you can kill them using the kill command:

kill -9 &lt;pid&gt;
```

**Comment by bannert1337** [comment]
You can checkout https://github.com/bannert1337/open-webui/issues/4 if you like

**Comment by tjbck** [comment]
Sanitisation occurs to prevent XSS, however, feel free to make a PR as long as you don't break the sanitisation process.

**Comment by kainatquaderee** [comment]
is there any way to fix this issue with filter function or something??
