### ISSUE TITLE
Support client-side context clipping using OpenAI compliant API

### ISSUE THREAD

**Issue by matbee-eth** [open-webui/open-webui#2819]
**Is your feature request related to a problem? Please describe.**
Yes, once the maximum context window is reached, it fails by sending the entire context to the llm api.

**Describe the solution you'd like**
Support a variety of context clipping mechanisms

I'm trying to use Exllamav2 models as Ollama is far too slow with LLaMa3-70b

**Comment by tjbck** [comment]
#1268
