### ISSUE TITLE
Setting model as default became unavailable on mobile after recent updates

### ISSUE THREAD

**Issue by skobkin** [open-webui/open-webui#2827]
# Bug Report

## Description

**Bug Summary:**
Before recent updates (in ~March?) we had an ability to set currently selected model as "default" on mobile devices the same way as on full-size devices.

**Steps to Reproduce:**
- Open the main screen after logging in
- Select the model
- Setting as default is unavailable

**Expected Behavior:**
Setting as default being available. At least somewhere in an obvious place like model list in workspace or in the list itself.

**Actual Behavior:**
The link is hidden now.

## Environment

- **Open WebUI Version:** 0.2.4 (I don't remember which version broke that feature, but it's still broken)

- **Operating System:** Android
- **Browser (if applicable):** Vivaldi

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

![Screenshot_20240605-014313.jpg](https://github.com/open-webui/open-webui/assets/967576/7c84024c-342c-4eec-b5fe-1e4536ab322a)

## Installation Method

Docker Compose

**Comment by tjbck** [comment]
Set as default as been removed as part of the redesign, all your settings are synced globally so you can set your default model from your PC.

**Comment by skobkin** [comment]
@tjbck What if I use it primarily on mobile device?

**Comment by justinh-rahb** [comment]
> @tjbck What if I use it primarily on mobile device?

Use the "show desktop version" option if your browser has that?

**Comment by skobkin** [comment]
@tjbck **I** can do that.

Don't you think that it's not intuitive?

Do you think new user who don't know about responsive layouts or advanced browser features would know what to do? Or they just shouldn't be able to use this feature?

**Comment by justinh-rahb** [comment]
@skobkin you're entitled to your opinion, and we've heard you. Acting indignant is not going to get very far though, I really think you need to look at reducing your negativity. This is a project developed by volunteers who do it for their own enjoyment... comments like your make it not fun, and that will cause development to cease. Do you understand?

**Comment by skobkin** [comment]
Only partly.

But this is not what you call it. I'm pointing to the flaw in the solution you proposed. That's a discussion.

If I call people who sees problems in my solutions indignant, it'll cause stagnation. That's why I try not to take such things personally.

If you think that my goal here is to make it no fun for you, then I can only say that it's not.
If you think that I think that OSS developers owe something to the end-users, then I can only say that I don't . I'd have no problem if you say "I won't fix that because I don't want to", it's fine with me. If you say that the correct way to achieve what was easily achievable earlier is to use hacks, then it's not a solid argument for me and I'll point that to you.

I hope you can understand too.

**Comment by CoreyB84** [comment]
I'm trying to get open webui on my phone.  Any advice on where to get instructions on how to do it?

**Comment by skobkin** [comment]
@CoreyB84 You need to set it up any some server and then open it in the browser on your phone.

You can use [these instructions](https://docs.openwebui.com/getting-started/) from official documentation. You need to be familiar with Linux and Docker to do that.

There is no magical "one click install" available ATM. If you need an example of non-production setup for personal use, you can use [my configuration](https://git.skobk.in/skobkin/docker-stacks/src/branch/master/ollama) as a reference.

**Comment by CoreyB84** [comment]
> @CoreyB84 You need to set it up on some server and then open it in the browser on your phone.
> 
> You can use [these instructions](https://docs.openwebui.com/getting-started/) from official documentation. You need to be familiar with Linux and Docker to do that.
> 
> There is no magical "one click install" available ATM. If you need an example of non-production setup for personal use, you can use [my configuration](https://git.skobk.in/skobkin/docker-stacks/src/branch/master/ollama) as a reference.

Just wondering for your setup, which linux framework did you use? Ubuntu Full, Debian, XFC, Userland(Ubuntu, Debian), Termux? For Docker how did you get it to install properly? I keep getting install issues that I'm trying to solve when I try to install docker fully.  Any advice is appreciated.

**Comment by skobkin** [comment]
@CoreyB84 I personally use Gentoo, but it's definitely not a good advice. I also don't think using specific distro is so important when you run something in Docker. Just choose whichever you like.
For Docker installation, I can only recommend to follow official Docker documentation. It shows you how to set it up in several popular distros.

P.S. I don't think this is a place to discuss your problems with Docker or WebUI installation. We distract the developers this way. It's better to use some Linux forum or some site like StackOverflow to ask for advice.
