### ISSUE TITLE
bug: Side Panel Stays Open on Mobile After Selecting "Workspace"

### ISSUE THREAD

**Issue by bannert1337** [open-webui/open-webui#2860]
# Bug Report

## Description

**Bug Summary:**
On mobile devices, after pressing “Workspace,” the side panel stays open. The workspace opens in the background, but the side panel should close after a selection is made.

**Steps to Reproduce:**
1. Open the application on a mobile device.
2. Press the “Workspace” button on the side panel.
3. Observe that the side panel remains open while the workspace opens in the background.

**Expected Behavior:**
The side panel should close after selecting “Workspace.”

**Actual Behavior:**
The side panel stays open, obstructing the view of the workspace.

**Comment by tjbck** [comment]
Fix should be trivial, I'll take a look but feel free to make a PR!

**Comment by tjbck** [comment]
fixed on dev.
