### ISSUE TITLE
feat: Endpoint information presented with model (and used in search)

### ISSUE THREAD

**Issue by VertexMachine** [open-webui/open-webui#2863]
**Is your feature request related to a problem? Please describe.**

When using multiple endpoints it's getting hard to distinguish between each of them if they host the same models. Here is example when you search for gpt4 and use both OpenAI API and OpenRouter:

![image](https://github.com/open-webui/open-webui/assets/35311995/8d3138ab-1b4f-493c-a4d6-77db1e78c8af)

Here is another example from workspace tab showing name clash between OpenRouter and Infermatics:

![image](https://github.com/open-webui/open-webui/assets/35311995/6eb12ef7-d9c3-4e29-b58a-c576a6c75a4c)

Another **potential** issue with current implementation: if unique key in the code is model id (which is a model name) - there is potential for name clash if multiple endpoints use the same model id. This is not something I encountered yet and it's not what this feature suggestion is about (but might be related and might need separate task). 

**Describe the solution you'd like**

Providing endpoint name with the model name. Providing also endpoint name in the model details tab. It could be made by adding endpoint name as a tag for example.

**Describe alternatives you've considered**

Right now I've manually tagged one endpoint, which allows me to see which models are theirs:

![image](https://github.com/open-webui/open-webui/assets/35311995/ba43aa95-96fc-4c77-9ccf-12dfa7e93b57)

**Additional context**

n/a

Edit: clarified that model id is right now for me a potential issue, not the actual issue I've already encountered.

**Comment by justinh-rahb** [comment]
Unfortunately, if we were to change the model IDs... every existing model config anyone has customized will break and revert back to the default as shown in your list. Not saying you haven't identified a genuine issue, but the proposed fix is going to be a non-starter.

**Comment by tjbck** [comment]
One workaround for id clash issue would be using a manifold pipeline proxy, which I believe should be the recommended solution.

**Comment by justinh-rahb** [comment]
True, putting your OpenAI endpoints in as manifold pipelines would give them a unique prefix 👌

**Comment by tjbck** [comment]
![image](https://github.com/user-attachments/assets/2fe74d94-dbe2-4ff3-abf5-715958bb8b93)

Admins can now hover over the model selector to check the model id.

![image](https://github.com/user-attachments/assets/e48d4f8a-1934-488e-8113-ddfa42374f13)

In conjunction with the connections prefix id feature, this issue is essentially resolved.
