### ISSUE TITLE
Use of Mermaid have some problem

### ISSUE THREAD

**Issue by peuportier** [open-webui/open-webui#2871]
# Bug Report
When I ask model to draw a chart or flow chart in mermaid, I get a Syntax error in the text 

## Description

<img width="963" alt="Screenshot 2024-06-06 at 10 28 54" src="https://github.com/open-webui/open-webui/assets/30169867/e81a44b1-0e6b-486f-afb7-f79f15153731">

**Bug Summary:**
[Provide a brief but clear summary of the bug]

**Steps to Reproduce:**
[Outline the steps to reproduce the bug. Be as detailed as possible.]
I use llama3:8b as model
Ask him to make a chart or draw something

**Expected Behavior:**
[Describe what you expected to happen.]

**Actual Behavior:**
[Describe what actually happened.]

## Environment

- **Open WebUI Version:** [e.g., 0.1.125]
- **Ollama (if applicable):** [e.g., 0.1.41]

- **Operating System:** [e.g.,  macOS Big Sur]
- **Browser (if applicable):** [e.g.SAFARI]

## Reproduction Details

**Confirmation:**

- [x ] I have read and followed all the instructions provided in the README.md.
- [x ] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

**Comment by silentoplayz** [comment]
It looks like the LLM-generated Mermaid syntax is incorrect. I believe the error here is clear. This highlights the importance of not relying solely on LLMs for accuracy. Instead, you can choose to guide your LLMs by picking apart the documentation (or having an LLM do it) and creating a well-structured prompt or system prompt based on the official documentation. For reference, you can check out the official Mermaid documentation: https://mermaid.js.org/intro/

**Comment by Chewt** [comment]
I believe this was closed prematurely, The error that it provides is unhelpful for future prompting and basically grinds the conversation to a halt. I am getting this error in most of my conversations with a variety of models, including llama3.

I would propose that in the case of a syntax error, or other error in rendering from mermaid, that the mermaid codeblock be shown to the user like any other code block, and the full error message from mermaid be provided, which usually includes things like lines where the error occured. This will provide the necessary context to guide the conversation toward a correct diagram with a follow up prompt such as "There is a syntax error on line [some line number], please fix this error and provide the updated code"
