### ISSUE TITLE
Adding Speech-to-Text via OpenAI API

### ISSUE THREAD

**Issue by colaber2** [open-webui/open-webui#2878]
Using Whisper locally with low to medium resources effects the quality and speed of voice conversations.
Since openAI API is also used in chat and tts, adding the ability to use stt OpenAI API would enhance the experience especially if you plan to add in the future voice only conversations mode just like in chatGPT app.

<img width="552" alt="Screen Shot 2024-06-06 at 1 09 53 PM" src="https://github.com/open-webui/open-webui/assets/153990548/be22a8a1-ced5-493d-910c-4136e738d5b6">

**Comment by colaber2** [comment]
Also big huge thanks in advance.

**Comment by tjbck** [comment]
#2248
