### ISSUE TITLE
Ollama advanced parameters are not saved

### ISSUE THREAD

**Issue by 0x7CFE** [open-webui/open-webui#2896]
# Bug Report

## Description

**Bug Summary:**
Ollama parameters in the advanced section do not persist. When I reopen the settings window, everything is back to defaults.

**Steps to Reproduce:**
1. Open settings view
2. Go to advanced
3. Change `use_mmap`, `use_mock`, `num_threads` parameters
4. Navigate away
5. Return to the settings view
6. Realize that those settings are now back to `Default` values

**Expected Behavior:**
Changed settings should remain set and should affect the backend. Apparently they are not.

**Actual Behavior:**
Settings are not saved, do not affect the backend.

## Environment

- **Open WebUI Version:** 0.2.4
- **Ollama (if applicable):** 0.1.39

- **Operating System:** Ubuntu 22.04
- **Browser (if applicable):** Firefox 125.0

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Installation Method

[Describe the method you used to install the project, e.g., manual installation, Docker, package manager, etc.]

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by silentoplayz** [comment]
Can confirm that this bug also occurs for me on the :dev branch.

**Comment by silentoplayz** [comment]
Changing advanced parameters appears to work fine on the `Workspace page`, but not on the main `New Chat` page. Would you mind giving this a try for me and report back if it works on this page as expected? Modify any advanced parameter(s) while within the `Workspace` page, then press the `Save` button in the same settings page for advanced parameters. Refresh the page and visualize if they were updated as expected, or rather swapped back to default.

**Comment by 0x7CFE** [comment]
> Would you mind giving this a try for me and report back if it works on this page as expected?

I tried changing `num_threads` while standing on a http://localhost:8080/workspace/models page, but apparently it still doesn't work. When I return to the settings view it remains `Default`.

**Comment by tjbck** [comment]
Fixed on dev, let us know if the issue persists!

**Comment by giladrom** [comment]
@tjbck I can save these for the workspace, but new chats always have the default parameters regardless of the workspace settings.

**Comment by Moosdijk** [comment]
Models created through workspace>models also do not inherit the base model parameters. 
Furthermore, open-webui does not read the parameters set in a modelfile and always defaults to its own default parameters.
