### ISSUE TITLE
bug: Icon for 👍 and 👎 stay foused even when the popup is closed

### ISSUE THREAD

**Issue by S1M0N38** [open-webui/open-webui#2908]
# Bug Report

## Environment

- **Open WebUI Version:** [º0.2.4]
- **Ollama (if applicable):** [0.1.41]

- **Operating System:** [macOS Sonoma]
- **Browser (if applicable):** [Firefox 126.0.1]

## Screencast

https://github.com/open-webui/open-webui/assets/22257750/8c2089df-81d9-4dba-9ca5-ef4889f1ca4c

**Comment by tjbck** [comment]
Not a bug, its there to indicate you've left your feedback.
