### ISSUE TITLE
Feature Request: "Send to Playground" Button

### ISSUE THREAD

**Issue by F0x06** [open-webui/open-webui#2914]
**Is your feature request related to a problem? Please describe.**

When working with various setups, including but not limited to Retrieval-Augmented Generation (RAG), I often encounter multiple issues with handling prompts and context. It's frustrating to manually extract and copy the full message from logs for experimentation on different models.

**Describe the solution you'd like**

I would like to have a "send to playground" button. This feature would allow users to copy the prompt, including the `<context>`, from any setup directly to the playground for seamless experimentation on different models without the need for manual extraction.

**Describe alternatives you've considered**

Currently, the only alternative is to manually copy the full message from the logs and paste it into the playground, which is time-consuming and prone to errors.

**Additional context**

Adding this feature would streamline the workflow and improve efficiency for users dealing with various setups. 

maybe an additional button here is a good option for this ?

![image](https://github.com/open-webui/open-webui/assets/7167311/6b69258c-d01a-49dd-b238-23f2e1eae0c3)

Best regards,
F0x

**Comment by tjbck** [comment]
Great idea! Let's continue our discussion #2565
