### ISSUE TITLE
Request to Limit Dialog Rounds posted to llm

### ISSUE THREAD

**Issue by fxsome** [open-webui/open-webui#2949]
**Is your feature request related to a problem? Please describe.**
Some times I want to continue the dialog ,but too much token is spent. Because all history are sent to llm. I want to save some.

**Describe the solution you'd like**
Limit dialog rounds, provide several strategy such as :
1,only keep most recent N rounds; 
2, Keep the system prompt , the first user message, and most recnet N rounds; 
3.only keep first N rounds and the last user message ; 
4. no limit

**Additional context**
LM studio provides things like the  attchment pic, but it based on tokens, not chat rounds, I think dialog rounds are better.
![Snipaste_2024-06-09_19-50-37](https://github.com/open-webui/open-webui/assets/44434587/038e46ea-a4cd-4789-9055-659c6b562fb7)

**Comment by tjbck** [comment]
#1268 PR Welcome!

**Comment by GrayXu** [comment]
+1, this would be a very meaningful feature.  
btw, such a feat issue might be closed as not planned?

**Comment by tjbck** [comment]
> +1, this would be a very meaningful feature.  
> 
> btw, such a feat issue might be closed as not planned?

Already implemented as Functions.

https://openwebui.com/functions

**Comment by GrayXu** [comment]
>Already implemented as Functions.
> https://openwebui.com/functions

Thanks, Functions is very cool. But I tried it out, are you referring to Max turns? This function seems to not allow further conversation after reaching the limit, which is different from OP's question. I wonder if there are other options?  

If not, I will try to see how to implement a function that achieves a similar feature.

**Comment by GrayXu** [comment]
For anyone facing similar issues, you can utilize https://github.com/GrayXu/openwebui-cut-context to achieve the proper functionality implementation.

**Comment by justinh-rahb** [comment]
Or just use this function:
https://openwebui.com/f/hub/context_clip_filter
