### ISSUE TITLE
ComfyUI CFG Option

### ISSUE THREAD

**Issue by williamcboehmjr** [open-webui/open-webui#2950]
Dear Open WebUI Development Team,

I am reaching out to request essential feature enhancements for the Open WebUI interface for ComfyUI. As a regular user, I have found that the inclusion of CFG (Classifier-Free Guidance), Sampler, and Scheduler options, as detailed in the ComfyUI Community Manual for KSampler, would greatly improve the flexibility and control users have over the image generation process.

Is your feature request related to a problem? Please describe.

The current limitation of not having easy access to CFG, Sampler, and Scheduler settings within the Open WebUI interface restricts users from achieving optimal results in their image generation workflows. The CFG scale, in particular, is crucial for controlling how closely the generated image aligns with the provided prompts; without the ability to adjust this setting, users may find it difficult to achieve the desired level of detail and accuracy in their images.

Describe the solution you'd like

I propose that the Open WebUI interface be updated to include:

CFG Scale Adjustment: A slider or input field for users to set the CFG scale, allowing for fine-tuned control over how aggressively the sampler realizes the content of the prompts in the final image.
Sampler Selection: A dropdown menu for users to choose from various available samplers, each offering different qualities and speeds in the denoising process.
Scheduler Options: A similar dropdown for selecting the type of scheduler to use, affecting the progression of the denoising steps.
These additions would provide users with the ability to fine-tune their image generation process, leading to more accurate and satisfying results.

Describe alternatives you've considered

I have considered using the native ComfyUI interface for adjusting these settings, but the lack of a user-friendly interface and the complexity of managing multiple configuration elements can be daunting for new and less technically savvy users. Integrating these options directly into the Open WebUI interface would streamline the process and make the platform more accessible.

Additional context

Incorporating the CFG, Sampler, and Scheduler options into the Open WebUI interface would align with the overall goal of making ComfyUI more user-friendly and efficient for a wide range of users. These features are critical for achieving high-quality results in various applications, including image-to-image tasks, where preserving parts of the original image while generating new details is essential.

**Comment by tjbck** [comment]
Duplicate #1459
