### ISSUE TITLE
Feat: Please dont blind me

### ISSUE THREAD

**Issue by RealMrCactus** [open-webui/open-webui#2958]
**Is your feature request related to a problem? Please describe.**
Loading screen should follow theme user has selected instead of blinding the ones who use dark mode.

**Describe the solution you'd like**
Invert logo colors and set background to whatever gray/black that is

**Comment by tjbck** [comment]
Already implemented on dev!

**Comment by silentoplayz** [comment]
v0.3.0 of Open WebUI now blesses your very eyeballs with a dark mode splash screen. 😇
