### ISSUE TITLE
Persist web search query in chat after search is finished

### ISSUE THREAD

**Issue by Expro** [open-webui/open-webui#2977]
**Is your feature request related to a problem? Please describe.**

As of 0.3.1, when Open WebUI does web search, it shows line "Searching the web for <search query>" while the search and tokenization is performed. Unfortunately, once the search is complete, this line disappears, being replaced by table of websites analyzed. It makes debugging reason for poor results harded than it should be.

**Describe the solution you'd like**
It would be great if said line with generated web search query persisted after search is complete, for example being rewritten from  "Searching the web for <search query>" to " "Searched the web for <search query>". It would be extra nice if those line included info on search engine used, for example "Searching the web for <search query> on searxng.example.com" and "Searched the web for <search query> on searxng.example.com", as search engine used can change in time.

**Comment by tjbck** [comment]
![image](https://github.com/open-webui/open-webui/assets/25473318/86870644-9b81-46b5-9ca8-dd713e09ec45)


Implemented on dev!

**Comment by Expro** [comment]
Amazing :)

**Comment by Expro** [comment]
In recent version this feature disappeared. Will it come back?
