### ISSUE TITLE
Cannot upload audio files after latest update

### ISSUE THREAD

**Issue by mr-gepardas** [open-webui/open-webui#2990]
# Bug Report

## Description

**Bug Summary:**
After updating from [v0.2.1](https://github.com/open-webui/open-webui/releases/tag/v0.2.1) to v0.3.1, the ability to upload audio files for transcription no longer works and website crashes, stops responding until page is refreshed. Using the default RAG settings (no changes made)

**Steps to Reproduce:**
On Windows PC, New Chat -> Select + button -> select an .mp3 or .wav file. Click Open. The website stops responding

**Expected Behavior:**
The audio file will begin being processed and transcription made for LLM to use, like any other document.

**Actual Behavior:**
Website stops responding. Console displays an error. 

## Environment

- **Open WebUI Version:** 
- v0.3.1
- **Ollama (if applicable):** 
- 0.1.42

- **Operating System:** 
- Windows 11
- **Browser (if applicable):** 
- Chrome  v125.0.6422.142 

## Reproduction Details

**Confirmation:**

- [x ] I have read and followed all the instructions provided in the README.md.
- [ x] I am on the latest version of both Open WebUI and Ollama.
- [ x] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
After clicking the "Open" button on Audio file, the following error in Console appears:
Uncaught (in promise) TypeError: t is not a constructor
    at Vt (dom.js:1228:9)
    at Array.ks (Toast.svelte:318:32)
    at ei (Toast.svelte:315:42)
    at Array.ds (Toast.svelte:310:20)
    at Bs (Toast.svelte:282:22)
    at Ot (Component.js:148:34)
    at new Os (Toast.svelte:157:5)
    at di (Toaster.svelte:192:40)
    at pi (Toaster.svelte:170:11)
    at hi (Toaster.svelte:139:9)

**Docker Container Logs:**
Does not appear like the file even reaches the Docker container, like WebUI crashes before it can reach the docker container to start logging.

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Installation Method

Docker + Ollama running locally on Windows 11

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
Good catch, fixed on dev!
