### ISSUE TITLE
enh: call voice input sensitivity  

### ISSUE THREAD

**Issue by hsman2** [open-webui/open-webui#2995]
It seems when you're using the new call feature when it's speaking (tts) it's hearing itself as if you're talking to it. Which results in it cutting off the tts after a word or 2. Only happens when i'm using it like a speaker phone. If I have my headphones in it works great since it doesn't hear itself talking. I think you need to put in a way to prevent it from listening UNTIL it's done talking, then it can resume listening again. Otherwise the the new call feature works great, just this one bug so far.

**Comment by spammenotinoz** [comment]
> It seems when you're using the new call feature when it's speaking (tts) it's hearing itself as if you're talking to it. Which results in it cutting off the tts after a word or 2. Only happens when i'm using it like a speaker phone. If I have my headphones in it works great since it doesn't hear itself talking. I think you need to put in a way to prevent it from listening UNTIL it's done talking, then it can resume listening again. Otherwise the call feature works great, just this one bug so far.

Sorry I can't answer your question, but wondering if there is a trick so playback work.
I can engage in conversation with the model via the new call feature, it hears me fine, but I do not hear any response, but when I end I see the text response.

**Comment by nextosai** [comment]
There are many ways to address that, but the easiest is using a programmable keyboard, "push key," to talk and release it to get the answer while muting the microphone. This is not the perfect scenario because we have to use our hands :) I agree with @hsman2, but I'm not sure about the complexity of coding that, as we would need to get the "end of audio" callback

**Comment by akhdanfadh** [comment]
I'm getting this bug also (MBP). Agree with either holding the mic button or controlling the mic sensitivity.

**Comment by tjbck** [comment]
Updated with the latest!

**Comment by ALLMI78** [comment]
hi guys, i also had this problem and found the solution:

Settings > Voice > Allow Voice Interruption in Call >>> set this to **OFF** if enabled

in my case that was the reason for the feedback loop
