### ISSUE TITLE
issue: ModuleNotFoundError: No module named 'pydub'

### ISSUE THREAD

**Issue by S1M0N38** [open-webui/open-webui#3027]
# Bug Report

ModuleNotFoundError: No module named 'pydub' when running `open-webui serve`

## Description

I have installed the latest version of open-webui using pip (inside a python virtual env create by `venv`)
```
pip install --upgrade open-webui
```

When running
```
open-webui serve
```
I get

```
ModuleNotFoundError: No module named 'pydub'
```

## Version
```
pip freeze | grep open-webui
open-webui==0.3.2
```

**Comment by gsm1258** [comment]
pip install pydub

**Comment by silentoplayz** [comment]
Should be fixed on dev branch

**Comment by walbercardoso** [comment]
Same here
