### ISSUE TITLE
Regenerating first message duplicates chat

### ISSUE THREAD

**Issue by mr-gepardas** [open-webui/open-webui#3030]
# Bug Report

## Description

**Bug Summary:**
When regenerating first Assistant response, or editing User first message, the chat gets duplicated.

**Steps to Reproduce:**
Select any model, write first message, wait for Assistant to respond. Click regenerate button. Or Click edit on the first user message, 'send' message.

**Expected Behavior:**
The new response is generated, still in the same chat. Would see the new number for the messages 2/2

**Actual Behavior:**
The new response is generated, in a new chat. The old chat is unaffected, the new chat is a duplicate with messages showing 2/2. The name of the chat is sometimes the same or different, but if tags were applied to the original chat, this new chat will not have any tags applied.

## Environment

- **Open WebUI Version:** 
- v0.3.2
- **Ollama (if applicable):** 
- 0.1.42

- **Operating System:** 
- Windows 11
- **Browser (if applicable):**
- Chrome

## Reproduction Details

**Confirmation:**

- [ x] I have read and followed all the instructions provided in the README.md.
- [ x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
This appears when sending message, but it also appears on any other normal message, so not sure it is relevant
AbortController {signal: AbortSignal}
signal
: 
AbortSignal {aborted: false, reason: undefined, onabort: null}
[[Prototype]]
: 
AbortController

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots (if applicable):**
![image](https://github.com/open-webui/open-webui/assets/172306433/1ef4340f-264a-4f56-84f7-8060a06ccb86)

## Installation Method

Docker WebUI + Local Ollama

## Additional Information

The bug keeps happening each time you regenerate the first Assistant or User message, so can quickly end up with a lot of duplicates of the same chat. 

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by silentoplayz** [comment]
This should be fixed on the dev branch.
