### ISSUE TITLE
Feature Request: Editing memory items

### ISSUE THREAD

**Issue by Tycho-S** [open-webui/open-webui#3036]
**Is your feature request related to a problem? Please describe.**
No, not related to a problem

**Describe the solution you'd like**
I would love to see an edit function for memories. Right now I can only add and delete memories, but not edit them. One of them is a list and description of my interests for example, which I use to filter news headlines. But these tend to very and I don't like to have to rewrite them every time. Right now I can't even copy and paste them into a new memory because only the first bit of the memory is displayed in the list

**Describe alternatives you've considered**
I thought about hacking into the database somehow but a GUI feature would really be way handier :)

**Additional context**
None sorry

**Comment by Tycho-S** [comment]
PS: I imagine these items need to be kept short because they don't seem to be retrieved on demand but rather inserted in every interaction, right? Thus eating at the context window.

**Comment by silentoplayz** [comment]
Related #2729

**Comment by Tycho-S** [comment]
Oops sorry I did search for it but didn't see that one.

**Comment by silentoplayz** [comment]
This has been added to the dev branch!
![memories](https://github.com/open-webui/open-webui/assets/50341825/85f0a26f-dd0e-400c-bb62-861613d54168)
