### ISSUE TITLE
Request to Skip Image URL in TTS Responses for Better Child Interaction

### ISSUE THREAD

**Issue by snakeying** [open-webui/open-webui#3043]
Firstly, I would like to extend my heartfelt gratitude to the development team and all contributors for bringing us such an amazing project. This is undoubtedly the best open-source UI I have ever experienced on GitHub.

Recently, while using the project, I encountered a minor issue. I have two five-year-old children who are very interested in interacting with AI. Since they have not yet mastered sufficient typing skills, I set up Speech-to-Text (STT) and Text-to-Speech (TTS) functions for them, and everything seemed to work perfectly. To help them better understand the AI interaction, I used prompts that included both text and images, such as:

Please remember for the following interaction, your conversational partner is a five-year-old child:
1. Use a tone that is understandable and interesting to young children.
2. Must include images.
3. Be humorous and friendly.

As a result, an image is generated with each AI interaction. After enabling the auto-playback response in the audio settings, the TTS reads the image URL (https://xxxxxxxxxx) before proceeding to the text of the interaction. I would like to inquire if it is possible to add a filtering option to skip the reading of the image URL?

Thank you for your hard work, and I look forward to your response.

**Comment by justinh-rahb** [comment]
That would be dependent on the TTS API that you are using.

**Comment by snakeying** [comment]
I used the “default” option

**Comment by justinh-rahb** [comment]
Yes, the Web Speech API provided by your browser/OS is responsible in that case. They're pretty unsophisticated.

**Comment by snakeying** [comment]
Well, I just try the openai TTS and it works like a champ...

Thx, and agian, keep up the great work~~ ^^V
