### ISSUE TITLE
 Fix casting of SEARCH_QUERY_PROMPT_LENGTH_THRESHOLD

### ISSUE THREAD

**Issue by jeremi** [open-webui/open-webui#3050]
When setting in the environment SEARCH_QUERY_PROMPT_LENGTH_THRESHOLD to 100 for example, I get the following error:

```
open-webui  |   File "/app/backend/main.py", line 609, in generate_search_query
open-webui  |     if len(form_data["prompt"]) < app.state.config.SEARCH_QUERY_PROMPT_LENGTH_THRESHOLD:
open-webui  |        ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
```

In config.py, there is a need to cast the value to int to fix it:
https://github.com/open-webui/open-webui/commit/4a025cca00a8ae1e7cbc8979ea435bcf78033f10#diff-651976572b51d1a16ede6a1c4c1be9a1482605ce57ca58fbfca25e4a55c43210L676

**Comment by tjbck** [comment]
Good catch, Thanks!
