### ISSUE TITLE
RAG Template Not Being Saved

### ISSUE THREAD

**Issue by glenamac** [open-webui/open-webui#3068]
# Bug Report

## Description

**Bug Summary:**
Changes to the RAG Template are not saved as described [here](https://docs.openwebui.com/tutorial/rag#rag-template-customisation)

**Steps to Reproduce:**
Go to Admin Panel -> Settings -> Documents and then edit RAG Template and click save. 
**Expected Behavior:**
RAG Template is saved. 

**Actual Behavior:**
RAG Template is not saved. It reverts to the default

## Environment

- **Open WebUI Version:** [v0.3.2]
- **Ollama (if applicable):** [0.1.42,

- **Operating System:** [Rocky 8]

## Installation Method
git clone https://github.com/open-webui/open-webui.git
cd open-webui/

cp -RPp .env.example .env

npm i
npm run build

cd ./backend
pip install -r requirements.txt -U
bash start.sh

**Comment by tjbck** [comment]
Fixed on dev!
