### ISSUE TITLE
Mixed Content w/ HTTPS

### ISSUE THREAD

**Issue by Fusseldieb** [open-webui/open-webui#3069]
Since one of the last updates to 3.x, OpenWebUI no longer loads. The DevTools console throws:
```
Mixed Content: The page at 'https://example.com/' was loaded over HTTPS, but requested an insecure resource 'http://example.com/api/v1/tools/'. This request has been blocked; the content must be served over HTTPS.

TypeError: Failed to fetch
    at window.fetch ...
```

The fetch function in question makes a request to an API endpoint that has a constant in it which is hardcoded as **http**:

https://github.com/open-webui/open-webui/blob/0917fa6f4ac015810211d85eb41da5d335762952/src/lib/constants.ts#L7

This causes issues, as the page is trying to load a http resource over a https page, essentially.

A potential solution would be getting the protocol to correctly prepend http or https, depending on the instance. Maybe `location.protocol`?

**Comment by rbrinson** [comment]
I just posted about the same issue (https://github.com/open-webui/open-webui/issues/3074). So, me too!
