### ISSUE TITLE
Playground improvements

### ISSUE THREAD

**Issue by mikygit** [open-webui/open-webui#3077]
**Is your feature request related to a problem? Please describe.**
I'd like to use the playground functionality on a per message basis instead of the current per model basis (if i understand correctly)

**Describe the solution you'd like**
See previous

**Describe alternatives you've considered**
See previous

**Additional context**
The idea would be to be able to change the model's parameter on a per message basis.

Does it make sense? Is it at all considered in your roadmap?
Thx.

**Comment by justinh-rahb** [comment]
Let's keep it here:
- #2565
