### ISSUE TITLE
bug: Admin panel -> Users page freezes 

### ISSUE THREAD

**Issue by Cotton0281** [open-webui/open-webui#3091]
# Bug Report

## Description

**Bug Summary:**
Admin panel -> Users page freezes when opened, and white listing interface doesnt work. changes on that page cannot be saved.
Error in the browser: 
![image](https://github.com/open-webui/open-webui/assets/120597715/25206d4e-898e-45a7-be6d-4826cbd3f5c4)
        
       Failed to load resource: the server responded with a status of 500 (Internal Server Error)
Connections.svelte:143 Uncaught (in promise) OpenAI: Network Problem
Users.svelte:65 Uncaught (in promise) TypeError: Cannot read properties of undefined (reading 'deletion')
    at Be (Users.svelte:65:28)
    at Object.p (Users.svelte:56:81)
    at at (scheduler.js:119:30)
    at ut (scheduler.js:79:5)

**Steps to Reproduce:**
Go to Admin panel -> Users, try to save some white listed models. Ollama is on a remote server on the same LAN.

**Expected Behavior:**
to save white listed models

**Actual Behavior:**
Page becomes irresponsive to the mouse actions

## Environment

- **Open WebUI Version:** [v0.3.3]
- **Ollama (if applicable):** [0.1.42]

- **Operating System:** [e.g., Windows 10, macOS Big Sur, Ubuntu 20.04]
- **Browser (if applicable):** [  Firefox , brave, opera all latest]

## Reproduction Details

**Confirmation:**

- [ ] I have read and followed all the instructions provided in the README.md.
- [ ] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Installation Method

[Describe the method you used to install the project, e.g., manual installation, Docker, package manager, etc.]

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
Should be fixed, let me know if the issue persists!
