### ISSUE TITLE
[bug] cannot edit or delete a document starting with "#" in its name in the workspace

### ISSUE THREAD

**Issue by dev2pew** [open-webui/open-webui#3102]
# Bug Report

## Description

**Bug Summary:**
document cannot be deleted nor edited in any way if it has "#" in its name tag, resulting 404 not found error.

**Steps to Reproduce:**
1. go to workspace;
2. rename any document's name tag to "#anything";
3. attempt to edit the document;
4. attempt to delete the document.

**Expected Behavior:**
document is edited/deleted without any issues.

**Actual Behavior:**
document becomes untouchable, unreachable. unable to edit.

## Environment

- **Open WebUI Version:** v0.3.4
- **Ollama (if applicable):** 0.1.43

- **Operating System:** Windows 10
- **Browser (if applicable):** Microsoft Edge 125.0.2535.92

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**

![image](https://github.com/open-webui/open-webui/assets/65161490/1dc48f4a-001c-4800-bbab-3a6d3cfd140d)

**Docker Container Logs:**

- full log can be found [here](https://pastebin.com/FRHurfws) on pastebin.

```log
Models in use: []
INFO:     172.17.0.1:54740 - "GET /api/v1/auths/ HTTP/1.1" 200 OK
INFO:     172.17.0.1:54730 - "GET /ws/socket.io/?EIO=4&transport=polling&t=P0DygJx&sid=RYHA1R196fgAhkYDAAAG HTTP/1.1" 200 OK
INFO:     172.17.0.1:54752 - "POST /ws/socket.io/?EIO=4&transport=polling&t=P0DygJw&sid=RYHA1R196fgAhkYDAAAG HTTP/1.1" 200 OK
INFO:     172.17.0.1:54752 - "GET /api/changelog HTTP/1.1" 200 OK
INFO:     172.17.0.1:54730 - "GET /api/v1/users/user/settings HTTP/1.1" 200 OK
INFO:     172.17.0.1:54716 - "GET /api/v1/chats/tags/all HTTP/1.1" 200 OK
INFO:     172.17.0.1:54752 - "GET /api/v1/prompts/ HTTP/1.1" 200 OK
INFO:     172.17.0.1:54740 - "GET /api/v1/documents/ HTTP/1.1" 200 OK
INFO:     172.17.0.1:48476 - "GET /api/v1/configs/banners HTTP/1.1" 200 OK
INFO:apps.openai.main:get_all_models()
INFO:apps.ollama.main:get_all_models()
INFO:     172.17.0.1:54730 - "GET /api/models HTTP/1.1" 200 OK
INFO:     172.17.0.1:48476 - "GET /static/favicon.png HTTP/1.1" 304 Not Modified
INFO:     172.17.0.1:54730 - "GET /api/v1/chats/ HTTP/1.1" 200 OK
INFO:     172.17.0.1:37558 - "DELETE /api/v1/documents/name/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:38946 - "GET /health HTTP/1.1" 200 OK
INFO:     172.17.0.1:49480 - "DELETE /api/v1/documents/name/ HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:49480 - "DELETE /api/v1/documents/name/ HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:49480 - "DELETE /api/v1/documents/name/ HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:49480 - "DELETE /api/v1/documents/name/ HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:49480 - "DELETE /api/v1/documents/name/ HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:49480 - "DELETE /api/v1/documents/name/ HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:49480 - "DELETE /api/v1/documents/name/ HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:49480 - "DELETE /api/v1/documents/name/ HTTP/1.1" 404 Not Found
INFO:     172.17.0.1:49480 - "DELETE /api/v1/documents/name/ HTTP/1.1" 404 Not Found
INFO:     127.0.0.1:55220 - "GET /health HTTP/1.1" 200 OK
INFO:     127.0.0.1:60606 - "GET /health HTTP/1.1" 200 OK
```

![image](https://github.com/open-webui/open-webui/assets/65161490/5ce80ec1-2cef-4b40-9f4c-c07f1e461663)

**Screenshots (if applicable):**

![image](https://github.com/open-webui/open-webui/assets/65161490/4205980e-ed7f-453d-9797-6e3f166efe95)

![image](https://github.com/open-webui/open-webui/assets/65161490/f02259a5-be60-4527-8dfa-a38baf42c581)

![image](https://github.com/open-webui/open-webui/assets/65161490/a197edec-863a-4689-aaa1-86968445be99)

![image](https://github.com/open-webui/open-webui/assets/65161490/4ec98342-2289-4e56-83dd-9366daeb875d)

## Installation Method

- Ollama for Windows;
- Windows Subsystem for Linux `ubuntu`;
- Docker `ghcr.io/open-webui/open-webui:main`.

## Additional Information

- I accidentally pasted the wrong name into the name tag and now I can't revert it;
- document's tag name must start with a "#" to reproduce this issue (but I am not sure);
- updated to the latest version of `open-webui`, still the same.

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
Should be fixed on latest, let me know if the issue persists!
