### ISSUE TITLE
enh: bulk (un)tag selected documents

### ISSUE THREAD

**Issue by dev2pew** [open-webui/open-webui#3110]
**Is your feature request related to a problem? Please describe.**
I find myself messing around in the workspace quite often.
I had a time where I had bunch of already uploaded documents, and my task was to tag each one of them by their file extension.

**Describe the solution you'd like**
add new button(s) for tagging (or removing tags from) selected documents.

**Describe alternatives you've considered**
I couldn't think of any alternatives :(

**Additional context**
some screenshots concepts? here is.

random idea 1

![image](https://github.com/open-webui/open-webui/assets/65161490/a4916ef8-d90a-4581-94c7-e23675e1e626)

random idea 2

![image](https://github.com/open-webui/open-webui/assets/65161490/59b4f55c-6a00-45bc-822e-943c408450e9)

1. add tag.
+ tags the document if such tag does not exist;
+ does nothing if tag already exists.

2. delete tag.
+ deletes the tag if such one exists;
+ does nothing if there no such tag.

**Comment by silentoplayz** [comment]
Good idea, but I think the `Delete tags` button you suggest should then bring up an option to select which tag(s) you'd like to remove from the selected documents, based on all tags collected from selected documents. +1 from me.👍🏼

**Comment by tjbck** [comment]
PR welcome!

**Comment by tjbck** [comment]
Closing in favour of #3527
