### ISSUE TITLE
feat: whole/full document mode

### ISSUE THREAD

**Issue by PkmX** [open-webui/open-webui#3129]
**Is your feature request related to a problem? Please describe.**
Sometimes it may be ideal to pass the whole document to LLM for tasks like summarization. Currently, if you upload a document and ask the LLM to summarize it, the RAG would most likely just return no result. As the user can't turn off the retrieval part, the LLM basically becomes useless in this rather common use case. Passing the full document is also useful of tasks like translation or sentiment analysis.

**Describe the solution you'd like**
When using an uploaded document or fetched webpage, there should be a checkbox allowing the user to pass the entire ingested document as the context. This should be a relative easy change to just skip the retrieval straight to the query.

Ideally, there should be a warning if the content is larger than the LLM's context size, so truncation or degraded output does not occur.

**Describe alternatives you've considered**
* Just copy/paste the full document into the chatbox: It works but is not very convenient.
* Have a separate pipeline specifically made for summarization: This can use a myriad of techniques to provide even better results with smaller context sizes, but requires significantly more effort to implement.

**Additional context**
This feature is also present in some other chat UI's, e.g., “document pinning” in AnythingLLM.

I'm not sure how this will interact with pipelines, since pipelines can basically do anything. I think such a flag can also be passed to compatible RAG pipelines to let it know if the user wants to perform context retrieval or just do a full-context insertion.

**Comment by bunnyfu** [comment]
Full support, with 32-128k context models now being more common, sometimes it's just easier and more failsafe to pass the whole document into the context if you want a summary.

**Comment by Peter-De-Ath** [comment]
Yes I like this. 
I currently open the document then paste it into chat, then do some editing of the messages to get the prompting right for the task i want

**Comment by rvkwi** [comment]
That would be really useful for several edge cases, recently ran into this not with summaries but some analysis. It was not about the content but patterns in it (so the entire context was important to survive at once). Ended up copying and pasting a lot, and eventually throwing it into Claude because this got tedious quickly. 

RAG is amazing, but there's cases where a simple 1:1 is all you need.

**Comment by pbasov** [comment]
With llama3.1 supporting 128k context this would be an important feature to have

**Comment by justinh-rahb** [comment]
> With llama3.1 supporting 128k context this would be an important feature to have

I think a lot of people are going to soon realize that Ollama doesn't actually run models at their full context size by default, and that if you wanted to run even 8B at 128K you'd need over 100GB of VRAM...

**Comment by rvkwi** [comment]
> > With llama3.1 supporting 128k context this would be an important feature to have
> 
> I think a lot of people are going to soon realize that Ollama doesn't actually run models at their full context size by default, and that if you wanted to run even 8B at 128K you'd need over 100GB of VRAM...

just because some can't fit it, doesn't mean others can't. num_ctx is not exactly hidden or advanced to understand, and you don't have to max it out just because it can. on top not everything uses standard quadratic attention to sequence length. 

open webui even has it more clearly worded as context length in the model file. 
i'm just saying, RAG is great, but there are also plenty of uses where you specifically don't want to cut a context insertion apart. a lot of these cases don't even need a massive context, but it's not unreasonable that people run high contexts with the webui. i think it would be a helpful feature to have as a toggle.

**Comment by justinh-rahb** [comment]
I wasn't arguing against it @rvkwi, you can see that I did thumbs-up the OP. You and I may know how `num_ctx` works full-well, but there are a LOT of WebUI users that don't understand that.

**Comment by justinh-rahb** [comment]
> Is it possible to bypass the current RAG system? I mean, having the documents inserted in the chat but opt to not use/apply them through the built-in RAG system.

Example for Tools:

```python
class Tools:
    def __init__(self):
        # If set to true it will prevent default RAG pipeline
        self.file_handler = True
```

**Comment by pomoke** [comment]
If we cannot fit the whole file into the ctx, we will need to take some other approaches like memGPT.

**Comment by formigarafa** [comment]
> If we cannot fit the whole file into the ctx, we will need to take some other approaches like memGPT.

ATM, what happens the given prompt (and chat history) does not fit the context? I mean, this problem already exists, doesn't it?

**Comment by pomoke** [comment]
> > Is it possible to bypass the current RAG system? I mean, having the documents inserted in the chat but opt to not use/apply them through the built-in RAG system.
> 
> Example for Tools:
> 
> ```python
> class Tools:
>     def __init__(self):
>         # If set to true it will prevent default RAG pipeline
>         self.file_handler = True
> ```
> 
> From: https://openwebui.com/t/hub/get_files

However, the default RAG is still seems to be enabled with this and `.citation = True`.

**Comment by NeverOccurs** [comment]
Try this:
https://github.com/NeverOccurs/full_doc_pipe
Use it as a filter function in Open-Webui. It allows uploading a file and push it fully into system prompt. Then you can direct ask the LLM to summarize it or whatever. It doesn't support changing file midway through the chat though.
Still optimizing it but for now I think it is enough for my use case. I'm trying to incorporating it with Claude's prompt caching to minimize cost.

**Comment by tjbck** [comment]
<img width="1047" alt="image" src="https://github.com/user-attachments/assets/75e205e7-c240-4cc1-9c1c-7449ab0818c5">


Full document mode toggle option has been added to latest dev, you can find the toggleable option by clicking on the file item component. Testing wanted here!

**Comment by daniel-dona** [comment]
Looks like the context is not being passed to the LLM with the "full document" option. 

![imagen](https://github.com/user-attachments/assets/ab34b8fc-c869-4049-8ad3-e746bb29de29)

![imagen](https://github.com/user-attachments/assets/bea8b28d-f1b9-42a7-846e-a23fdc1b400d)

![imagen](https://github.com/user-attachments/assets/6ce550d5-737e-4d8f-86f7-7905ff7fb7b1)


The query received by Ollama:

```
ollama  | time=2024-10-13T14:43:54.332Z level=DEBUG source=routes.go:1422 msg="chat request" images=0 prompt="<|im_start|>system
You are Qwen, created by Alibaba Cloud. You are a helpful assistant.<|im_end|>
<|im_start|>user
You are given a user query, some textual context and rules, all inside xml tags. You have to answer the query based on the context while respecting the rules.

<context>
BK72XX_SDK_User_Manual-3.0.3-1.pdf:
</context>

<rules>
- If you don't know, just say so.
- If you are not sure, ask for clarification.
- Answer in the same language as the user query.
- If the context appears unreadable or of poor quality, tell the user then answer as best as you can.
- If the answer is not in the context but you think you know the answer, explain that to the user then answer with your own knowledge.
- Answer directly and without using xml tags.
</rules>

<user_query>
Summarize this
</user_query>

Summarize this<|im_end|>
<|im_start|>assistant
```

**Comment by daniel-dona** [comment]
> @daniel-dona It sounds like you are also facing #291 (please check the logs and confirm).

Nope, not a single 40X error found in the Developer Console, I don't think is a CORS problem

**Comment by arsaboo** [comment]
oops....linked the wrong issue. Can you check against #6018

**Comment by arsaboo** [comment]
Either that or you should be seeing some `collection` related error @daniel-dona

**Comment by a-mart** [comment]
Seeing the same issue. Only handing 5 random pages of the document to the model out of roughly 50.

**Comment by a-mart** [comment]
I've also confirmed that I'm not seeing the errors from #291 but still experiencing the same issue

**Comment by maurizioaiello** [comment]
> Try this: https://github.com/NeverOccurs/full_doc_pipe Use it as a filter function in Open-Webui. It allows uploading a file and push it fully into system prompt. Then you can direct ask the LLM to summarize it or whatever. It doesn't support changing file midway through the chat though. Still optimizing it but for now I think it is enough for my use case. I'm trying to incorporating it with Claude's prompt caching to minimize cost.

How does it work? Can you explain better how to use it?

**Comment by jayendra19** [comment]
If i have pdf and i uploaded it when i say summarise it won’t be able to do it how can i enable it ?

**Comment by weathon** [comment]
the full text mode seems to work for me, but is there a way to make it default?

**Comment by curious-broccoli** [comment]
I agree, it works, but it is rather annoying to use. Mainly that you first need to send any message with the uploaded file selected so you can enable the full document mode. Before a message is sent, the file does not show up in the (settings) sidebar. Maybe this is also a bug.

<img width="1919" height="708" alt="Image" src="https://github.com/user-attachments/assets/033f238c-0a7a-4fbd-bff7-2f7cf739f13f" />

---
EDIT: apparently you can already click the file while it is shown in the input to toggle the mode, so ignore what I wrote above

**Comment by curious-broccoli** [comment]
> the full text mode seems to work for me, but is there a way to make it default?

@weathon there seems to be, but it might affect more than you wish

<img width="1852" height="116" alt="Image" src="https://github.com/user-attachments/assets/d08fd62f-d2b4-4468-9a1d-0fa38f5b1b29" />
