### ISSUE TITLE
Web search prompt doesn't used, and noisy RAG

### ISSUE THREAD

**Issue by Fusseldieb** [open-webui/open-webui#3131]
# Bug Report

## Description

**Bug Summary:**
When using the web search capability, it seemingly skips the web search prompt and simply uses the original question prompt.
Eg. if I ask "Make a Google search to tell me who's Fusseldieb", it just skips to `"Searching 'Make a Google search to tell me who's Fusseldieb'...`
When looking at the logs, it really does search for the whole original prompt. Seems like the prompt to transform the query into a Google search doesn't get executed, or ignored.

---

Also, when searching on the web, when it reads individual searches, it doesn't trim the output, which makes it very noisy, and uses A LOT of useless tokens.
See below.

**Steps to Reproduce:**
- Enable the web search capability within the "+" icon.
- Ask anything

**Expected Behavior:**
- Pass through the query transformation prompt

**Actual Behavior:**
- It searches the exact prompt

## Environment

- **Open WebUI Version:** 0.3.4

- **Operating System:** Debian GNU/Linux 11 (bullseye)

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Docker Container Logs:**
```
INFO:root:trying to web search with ('duckduckgo', 'Search the exact term "Fusseldieb" for me')
[SearchResult(...
```

**Screenshots (if applicable):**
![image](https://github.com/open-webui/open-webui/assets/4715129/9d3dadcb-b9ef-4bab-a02f-1b770978db57)

---

![image](https://github.com/open-webui/open-webui/assets/4715129/08a22962-149c-4549-a3e2-be8dbf5a1749)

## Installation Method

Docker

## Additional Information

Suggestion: I think this would ideally be a pipeline, not a built-in function.

**Comment by AeneasZhu** [comment]
I encountered the same promble after the upgrade to 0.34. Hope this issue will be fixed soon.

![image](https://github.com/open-webui/open-webui/assets/44701446/1236e73d-ff5c-40fe-a3b7-f6531f617ce1)

**Comment by justinh-rahb** [comment]
@AeneasZhu that is unrelated to this issue.

**Comment by tjbck** [comment]
You can change the prompt length threshold from admin settings!

**Comment by Fusseldieb** [comment]
@tjbck Thanks for answering, however that doesn't quite address the issues.

The bug in which it skips through the query prompt is, well, a bug.

And the prompt length threshold can be adjusted, but the issue is that it doesn't "clean up" endless ("\n", newlines) which may come from web searches.

**Comment by RayGicEFL** [comment]
The length threshold means that when your prompt word ** exceeds ** the threshold before a web search keyword is generated with the LLM instead of using your request directly, so if you want to generate web search keywords by LLM every time, you should set the threshold to `0`.
