### ISSUE TITLE
Network problems: --network=host not a solution

### ISSUE THREAD

**Issue by johann-petrak** [open-webui/open-webui#3173]
If I use the default suggested docker command to start the containter, which includes `-p 3000:8080` no connection can be established to 127.0.0.1:11434 or localhost:11434
In the documentation, the only workaround proposed is to use instead --network=host, but since 8080 is the default port for many other services, this will not work on any machine where that port is already in use. 
For this reason, some solution for the original connection problem needs to be provided in order to make the webui run on an arbitrary port.

**Comment by justinh-rahb** [comment]
> For this reason, some solution for the original connection problem needs to be provided in order to make the webui run on an arbitrary port.

Been in the docs since forever ago: https://docs.openwebui.com/faq#q-why-cant-my-docker-container-connect-to-services-on-the-host-using-localhost

Use:
```
http://host.docker.internal:11434
```

Why everyone always trying everything **except** what they should I dunno, I don't think we'll find a solution to _that issue_.
