### ISSUE TITLE
enh: Improve Delete Chat Function

### ISSUE THREAD

**Issue by turbosnail11** [open-webui/open-webui#3176]
After clicking on "..." beside your chat and then clicking delete, the expectation is that your chat will be deleted.  In practice, after clicking delete a small check mark and x appear beside the chat that is very easy to miss (I missed it).  Unlike the popup, the delete confirmation is not as obvious.

Additionally, the options aren't intuitive.  I want to delete it, so should I click the "x" to delete or the checkmark?

If confirmation is necessary. then I think a popup with "Delete"/"Cancel" is a more elegant solution.  

<img width="622" alt="WebUI Popup" src="https://github.com/open-webui/open-webui/assets/135905079/b8625322-b4d8-4bb9-9d83-ac5c1dd8cc3a">

<img width="613" alt="WebUI Delete" src="https://github.com/open-webui/open-webui/assets/135905079/0c19646a-d648-473f-b233-0a14c9d44211">

**Comment by tjbck** [comment]
Implemented on dev!
 
![chad](https://github.com/open-webui/open-webui/assets/25473318/7f83c909-95b1-4750-8656-218d3a408037)

**Comment by turbosnail11** [comment]
> Implemented on dev!
>
> 

Awesome!
