### ISSUE TITLE
Open Webui 0.3.4 timesout with long Ollama responses

### ISSUE THREAD

**Issue by joequant** [open-webui/open-webui#3189]
# Bug Report

openwebui fails with a timeout if ollama is sending back a long running ollama chat

## Description

**Bug Summary:**
openwebui fails with a timeout if ollama is sending back a long running ollama chat

**Steps to Reproduce:**
Run a chat with a response that takes more than a minute to respond

**Expected Behavior:**
It should continue to respond

**Actual Behavior:**
After a few minutes it fails with
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 756, in __call__                                                                                                    
open-webui  |     await self.middleware_stack(scope, receive, send)                                                                                                                                           
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 776, in app                                                                                                         
open-webui  |     await route.handle(scope, receive, send)                                                                                                                                                    
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 485, in handle                                                                                                      
open-webui  |     await self.app(scope, receive, send)                                                                                                                                                        
open-webui  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__                                                                                                
open-webui  |     await super().__call__(scope, receive, send)                                                                                                                                                
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__                                                                                               
open-webui  |     await self.middleware_stack(scope, receive, send)                                                                                                                                           
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__                                                                                          
open-webui  |     raise exc                                                                                                                                                                                   
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__                                                                                          
open-webui  |     await self.app(scope, receive, _send)                                                                                                                                                       
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__                                                                                            
open-webui  |     with collapse_excgroups():                                                                                                                                                                  
open-webui  |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__                                                                                                                         
open-webui  |     self.gen.throw(typ, value, traceback)                                                                                                                                                       
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups                                                                                            
open-webui  |     raise exc                                                                                                                                                                                   
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 261, in wrap                                                                                                      
open-webui  |     await func()                                                                                                                                                                                
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 250, in stream_response                                                                                           
open-webui  |     async for chunk in self.body_iterator:                                                                                                                                                      
open-webui  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 50, in __anext__                                                                                                      
open-webui  |     rv = await self.read_func()                                                                                                                                                                 
open-webui  |          ^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                 
open-webui  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 317, in readline                                                                                                      
open-webui  |     return await self.readuntil()                                                                                                                                                               
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                               
open-webui  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 351, in readuntil                                                                                                     
open-webui  |     await self._wait("readuntil")                                                                                                                                                               
open-webui  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 311, in _wait                                                                                                         
open-webui  |     with self._timer:                                                                                                                                                                           
open-webui  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/helpers.py", line 735, in __exit__                                                                                                      
open-webui  |     raise asyncio.TimeoutError from None                                                                                                                                                        
open-webui  | TimeoutError                      

## Environment

- **Open WebUI Version:** [e.g., 0.1.120] 0.3.4

- **Operating System:** linux
- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]

## Reproduction Details

**Confirmation:**

- [ X] I have read and followed all the instructions provided in the README.md.
- [ X] I am on the latest version of both Open WebUI and Ollama.
- [ X] I have included the browser console logs.
- [ X] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/routing.py", line 485, in handle                                                                                                      
open-webui  |     await self.app(scope, receive, send)                                                                                                                                                        
open-webui  |   File "/usr/local/lib/python3.11/site-packages/fastapi/applications.py", line 1054, in __call__                                                                                                
open-webui  |     await super().__call__(scope, receive, send)                                                                                                                                                
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/applications.py", line 123, in __call__                                                                                               
open-webui  |     await self.middleware_stack(scope, receive, send)                                                                                                                                           
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 186, in __call__                                                                                          
open-webui  |     raise exc                                                                                                                                                                                   
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/errors.py", line 164, in __call__                                                                                          
open-webui  |     await self.app(scope, receive, _send)                                                                                                                                                       
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/middleware/base.py", line 189, in __call__                                                                                            
open-webui  |     with collapse_excgroups():                                                                                                                                                                  
open-webui  |   File "/usr/local/lib/python3.11/contextlib.py", line 158, in __exit__                                                                                                                         
open-webui  |     self.gen.throw(typ, value, traceback)                                                                                                                                                       
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/_utils.py", line 93, in collapse_excgroups                                                                                            
open-webui  |     raise exc                                                                                                                                                                                   
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 261, in wrap                                                                                                      
open-webui  |     await func()                                                                                                                                                                                
open-webui  |   File "/usr/local/lib/python3.11/site-packages/starlette/responses.py", line 250, in stream_response                                                                                           
open-webui  |     async for chunk in self.body_iterator:                                                                                                                                                      
open-webui  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 50, in __anext__                                                                                                      
open-webui  |     rv = await self.read_func()                                                                                                                                                                 
open-webui  |          ^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                                 
open-webui  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 317, in readline                                                                                                      
open-webui  |     return await self.readuntil()                                                                                                                                                               
open-webui  |            ^^^^^^^^^^^^^^^^^^^^^^                                                                                                                                                               
open-webui  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 351, in readuntil                                                                                                     
open-webui  |     await self._wait("readuntil")                                                                                                                                                               
open-webui  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/streams.py", line 311, in _wait                                                                                                         
open-webui  |     with self._timer:                                                                                                                                                                           
open-webui  |   File "/usr/local/lib/python3.11/site-packages/aiohttp/helpers.py", line 735, in __exit__                                                                                                      
open-webui  |     raise asyncio.TimeoutError from None                                                                                                                                                        
open-webui  | TimeoutError                   

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Installation Method
docker compose

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by joequant** [comment]
This doesn't seem to be a problem in version v0.2.3

**Comment by joequant** [comment]
This seems to have been fixed in dfa2cf9e6d784ac5b1458911ef8364258dc54cba

**Comment by silentoplayz** [comment]
Related - #3107

**Comment by silentoplayz** [comment]
Related - #3135
This issue *should* also be fixed viahttps://github.com/open-webui/open-webui/commit/dfa2cf9e6d784ac5b1458911ef8364258dc54cba as well.

**Comment by TheTerrasque** [comment]
Well, not *fixed* per se, but it can then be adjustable via environment variable. 

When I submitted the PR I changed the default to 15 minutes, but I see it's been set back to 5 minutes as default.

**Comment by wsargent** [comment]
What environment variable, though?
