### ISSUE TITLE
Improve management of memory entries

### ISSUE THREAD

**Issue by vertago1** [open-webui/open-webui#3197]
**Is your feature request related to a problem? Please describe.**
Memory entries can be added and removed, but there isn't an easy way to edit them or toggle them on/off

**Describe the solution you'd like**
I think the memory feature would be interesting if I could edit them, toggle them on/off for specific chats, and group them (where a whole group could be toggled for a chat at a time).

**Describe alternatives you've considered**
Right now a work around is to back up a copy of the memory somewhere else to edit, delete the existing memory, and add the updated one.

Toggling a memory now involves removing it or adding it back manually.

Grouping of memories has to be done outside of the tool or by creating multiple accounts with different groups of memories.

**Comment by silentoplayz** [comment]
The ability to edit memories was merged to the `dev` branch not too long ago - https://github.com/open-webui/open-webui/pull/3116
