### ISSUE TITLE
Ollama models do not work with external API when URL has trailing forward slash 

### ISSUE THREAD

**Issue by toperator1337** [open-webui/open-webui#3198]
# Bug Report

## Description

**Bug Summary:**
There is an inconsistent behavior seen when using an HTTPS reference with a _trailing forward slash_ in Admin Settings -> Connections. The URL with _and without_ the forward slash validates as being correct, but then the URL with the forward slash in it does not work when the model from the external resource is queried, giving a 404 error.  

**Steps to Reproduce:**
Set the connection to a URL with a trailing forward slash:
<img width="844" alt="1" src="https://github.com/open-webui/open-webui/assets/172933654/e1c10428-5373-4d6f-a62e-a78b14b439a2">
Verify the connection:
<img width="840" alt="2" src="https://github.com/open-webui/open-webui/assets/172933654/2dfe82b6-6284-494c-bcdc-fb83696addd2">
Attempt to use the model:
<img width="805" alt="3" src="https://github.com/open-webui/open-webui/assets/172933654/91ab64f4-63f2-4147-ba75-35c8b8b284a2">

**Expected Behavior:**
Model either fails validation, or succeeds validation and then actually works.

**Actual Behavior:**
Model succeeds at validation and then does not work with a 404 on the /ollama/api/chat POST.

## Environment

- **Open WebUI Version:** v0.3.4
- **Ollama (if applicable):** 0.1.44

- **Operating System:** N/A
- **Browser (if applicable):** N/A

## Reproduction Details

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [X] I am on the latest version of both Open WebUI and Ollama.
- [X] I have included the browser console logs.
- [X] I have included the Docker container logs. 

## Logs and Screenshots

**Browser Console Logs:**
[openwebuiharfailure.har.txt](https://github.com/user-attachments/files/15854031/openwebuiharfailure.har.txt)

**Docker Container Logs:**
[dockerlogs.txt](https://github.com/user-attachments/files/15854082/dockerlogs.txt)

**Screenshots (if applicable):**
See above.

## Installation Method
N/A

## Additional Information
Ollama is running on a RunPod.IO container.

**Comment by tjbck** [comment]
<img width="602" alt="image" src="https://github.com/open-webui/open-webui/assets/25473318/595ee830-3ab8-4087-98f2-3a368634a0fd">

Can't seem to reproduce on my end but I added an enhancement to automatically remove all the trailing slashes in the urls!

**Comment by giladrom** [comment]
Can confirm  - I just spun up the docker instance with a trailing slash/ URL as the OLLAMA_BASE_URL parameter and connection failed.
