### ISSUE TITLE
bug: Message Deletion Causes Sending Issues and UI Discrepancies

### ISSUE THREAD

**Issue by Algorithm5838** [open-webui/open-webui#3224]
# Bug Report

## Description

**Bug Summary:**
If I delete my second message, the UI becomes bugged. I can't send a following message on phone, but I can send it on desktop, though it won't show. After a reload, the issue resolves and the previous message that was sent, but was not showing during the bug, can be seen in a newly created chat.

**Steps to Reproduce:**
1. Start a new chat.
2. Send two messages.
3. Delete the second message.
4. Attempt to send a third message on both mobile and desktop.

**Expected Behavior:**
Messages should send and display correctly on both mobile and desktop after deleting a message.

**Actual Behavior:**
- **Mobile:** Unable to send a third message after deleting the second message.
- **Desktop:** Can send a third message, but it doesn't appear in the current chat.
- **Both:** Issue resolves after reloading the page. The previously sent but invisible message then appears in a new chat.

## Environment

- **Open WebUI Version:** v0.3.4 

- **Operating System:** Android & macOS
- **Browser:** Chrome (Android PWA) & Brave (macOS PWA)

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI. 

## Installation Method

Docker installation.

**Comment by silentoplayz** [comment]
Possibly related - #2208

**Comment by Algorithm5838** [comment]
You are right, I didn’t notice that because my search for “delete” didn’t return a similar issue.  Would you suggest I close this issue?

**Comment by silentoplayz** [comment]
If you can provide any other details that I might've left out from my bug report, you could comment on it. Probably best to close this as a duplicate though, as there's not enough information to go from and mine has been open for quite some time, and has not been reproducible by the maintainer.
