### ISSUE TITLE
feat: KB management

### ISSUE THREAD

**Issue by joelmnz** [open-webui/open-webui#3231]
**Is your feature request related to a problem? Please describe.**

RAG is a great help but when you are trying to maintain a custom knowledge base you have to keep updating the document which means downloading the file, edit, uploading, it gets very tedious for frequently updated information e.g.
 
- if you kept your meeting/conversations for reference and use in chat
- document for project summary and goals, where are you up to
- if you are learning a new topic and want to write notes and have the chat use your new learnings

**Describe the solution you'd like**

Ideally I would like a built in knowledge base management such as a markdown file editor (think Obsidian) or perhaps nominate a kb git repo and pull that into indexing for RAG

**Describe alternatives you've considered**

I've tried

- using the chat history as storage, editing the AI responses with notes and summaries so I can ask questions in context. But you can't delete a AI response (another feature request please for that) so it's just a big running chat. 

- using Obsidian with Smart-Connectiond, this is the best solution I've found BUT it doesn't work on mobile devices 😥

- many other online AI systems that chat with your notes but Open WebUI is so good and so close, having a nominated folder of markdown files to index (with built in editor) would be amazing.

**Additional context**

**Comment by flefevre** [comment]
I do agree
I have opened a discussion here that could enrich perhaps the feature 

https://github.com/open-webui/open-webui/discussions/3226

What do you think of such system of data connectors ?

One of them could be git access

**Comment by tjbck** [comment]
Closing in favour of #3527, Let's continue our discussion there!
