### ISSUE TITLE
enh: Include documents into models (system prompt/...)

### ISSUE THREAD

**Issue by D1yt** [open-webui/open-webui#3260]
**Is your feature request related to a problem? Please describe.**
I feel like there is a usecase for models with file access by default, instead of using a first setup prompt giving relevant files to a model.

**Describe the solution you'd like**
If it's not possible to pass files via the system prompt, there should be a way to pass a hidden first (user) prompt to pass relevant files.

**Comment by D1yt** [comment]
Hey, I've looked everywhere in the Web UI and the documentation and I couldn't find anything to fulfil my need of file-inclusion into the system prompt or other setup parameters of an AI model.

**Comment by justinh-rahb** [comment]
<img width="743" alt="Screenshot 2024-06-19 at 7 24 04 PM" src="https://github.com/open-webui/open-webui/assets/52832301/94e32249-3777-4b15-b55e-648603ea9097">

**Comment by D1yt** [comment]
Thanks for the screenshot, what version are you on?

**Comment by D1yt** [comment]
Okay, something just didn't work with pulling the latest image + watchtower autoupdating, but now I am on 0.3.5
 and it's right there. Thanks a lot.
