### ISSUE TITLE
feat: Allow admins to brand their site 

### ISSUE THREAD

**Issue by moodler** [open-webui/open-webui#3290]
I want to set up multiple Open WebUI interfaces for use by an organisation.  

The default theme/logo is nice, but it can be confusing.  

It would be very useful for admins to be able to do some very simple branding of the interface for a given instance, at least:

   - background colour
   - logo 
   - site name

**Comment by justinh-rahb** [comment]
The current abilities provided align with the project's intended scope. Note that you can customize the name using the `WEBUI_NAME` environment variable, but it will append "(Open WebUI)" to the end. However, paying supporters (via [GitHub Sponsors](https://github.com/sponsors/tjbck)) can utilize the `CUSTOM_NAME` variable to override the suffix and set a custom logo. While anyone is free to fork and modify the appearance or white-label it for their own use, please be aware that the project will not provide direct support for customized versions.
