### ISSUE TITLE
enh: Adding user email address to user object for filter pipeline

### ISSUE THREAD

**Issue by michaeltansg** [open-webui/open-webui#3305]
**Is your feature request related to a problem? Please describe.**
I am trying to create a filter pipeline that will append metadata to the body in the inlet method using information from the [user object](https://github.com/open-webui/pipelines/blob/df2124e75724b3ea5143a1a22b85aeaeac0d2644/examples/scaffolds/filter_pipeline_scaffold.py#L66). However, I would like to use the email address of the user since downstream services uses the email address to identify the user.

**Describe the solution you'd like**
Adding the user email to the user object [here](https://github.com/open-webui/open-webui/blob/9e4dd4b86f77653b59dc1fa97fe3f72e8252b359/backend/main.py#L431).

**Describe alternatives you've considered**
Workarounds I have considered:
- Querying the database by the user id
- GET `/api/v1/auths/`

**Additional context**
Downstream services: litellm, langfuse.

**Comment by tjbck** [comment]
Added to dev!
