### ISSUE TITLE
feat: Configure TTS voice per Model

### ISSUE THREAD

**Issue by chrishart0** [open-webui/open-webui#3347]
**Is your feature request related to a problem? Please describe.**

Add the ability to optionally configure a TTS voice per model. I have many types of Models on my current instance of OpenWeb UI, I'd like to select different default voices for each. 

**Describe the solution you'd like**

* Now that Models in OpenWeb UI are seperated a bit from Modelfiles, an optional field for TTS voice could be added. 
* If that voice isn't present in the TTS configs with the config endpoint is checked, then it could default to whatever the system wide default voice is

**Describe alternatives you've considered**
None

**Additional context**
This will be useful for my current usecase of making a series of educational AI persona impersonating real historical figures, I would like to give each a different voice.

**Comment by tjbck** [comment]
#3097

**Comment by F1xGOD** [comment]
pls this
