### ISSUE TITLE
issue: websearch (SearX)

### ISSUE THREAD

**Issue by manfromdownunder** [open-webui/open-webui#3376]
# Bug Report

## Description
Correct URL for SearX instance ( eg, ```https://metasearx.com/search?q=<query>``` ) returns error.  
- Confirmed that -json is enabled in the SearX instance

**Bug Summary:**
Error message: 
"Something went wrong :/ Oops! The URL you provided is invalid. Please double-check and try again"

**Steps to Reproduce:**
1. Open admin panel, settings, websearch.
2. Searxng Query URL enter: ```https://metasearx.com/search?q=<query>```
3. Save settings
4. Open a new chat and enable websearch
5. Error returned

You can verify that the json is returned correctly for eg:
```https://metasearx.com/search?q=what+is+the+weather%3F%0A%0A&format=json&pageno=1&safesearch=1&language=en-US&time_range=&categories=&theme=simple&image_proxy=0```

You get mixed results when you adjust the URL for example,:
```https://metasearx.com/?q=%```

There is no error and sites are returned, however they are:
```https://www.math.net/percentage```
```https://en.wikipedia.org/wiki/Percent_sign```

Adding in ```<query>``` anywhere seems to break the process.

**Expected Behavior:**
Entering a query with websearch enabled and the websearch searx query url set to ```https://metasearx.com/search?q=<query>```queries the searx instance, returns the JSON and answers the query based on results.

**Actual Behavior:**
Entering a query with websearch enabled and the websearch searx query url set to ```https://metasearx.com/search?q=<query>``` queries the searx instance, returns  "Something went wrong :/ Oops! The URL you provided is invalid. Please double-check and try again"

## Environment

- **Open WebUI Version:** latest
- **Ollama (if applicable):** latest

- Ubuntu 20.04
- Brave

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots
![image](https://github.com/open-webui/open-webui/assets/31198168/84aace8e-cd0a-4e18-9e6e-7c339afdc8a9)

**Browser Console Logs:**
N/A]

**Docker Container Logs:**
Not sure how to get these

**Screenshots (if applicable):**
![image](https://github.com/open-webui/open-webui/assets/31198168/bb66cc48-429c-4831-9d31-8da0e63a179b)

![image](https://github.com/open-webui/open-webui/assets/31198168/115dce5d-02ac-4ced-8d8c-9ff51ac8c9fe)

## Installation Method

1. git clone project locally
2. installed docker nvidia container and settings 
3. docker-compose -f docker-compose.yaml up -d

## Additional Information

From the testing that I have done, even with my own searx instance (not local) and ensuring that json format is enabled the results come back if I use the url directly in the browser.  For some reason open-webui thinks that the json results returned are an error.  

There is something funky happening with the way ```<query>``` is parsed.

**Comment by tjbck** [comment]
I don't use searxng myself, so if anyone could chime in, I'd greatly appreciate it!

@manfromdownunder if you manage to find out what the culprit is, please keep us updated!

**Comment by igeekbb** [comment]
> searxng

 searxng I gave up too. There are issues, it's always unstable to use.

**Comment by manfromdownunder** [comment]
I think I have found the issue and it has nothing to do with the code.  There was an incorrect name server defined first in /etc/resolv.conf.  I fixed dns resolution and everything appears to be working as expected. The error I was seeing was due to the dns lookup failing.

**Comment by justinh-rahb** [comment]
Thanks for the followup @manfromdownunder 🙏
