### ISSUE TITLE
Toggle for back & forth conversation

### ISSUE THREAD

**Issue by jamfor352** [open-webui/open-webui#3389]
**Is your feature request related to a problem? Please describe.**
When reading aloud a message in open-webui, I do not necessarily want to use voice to send a message back. I think this was configurable in previous releases, but seems to have been removed.

**Describe the solution you'd like**
A toggle that avoids recording as soon as a message is read aloud.

**Describe alternatives you've considered**
Cannot think of any alternatives. I have to manually cancel the voice input recording, which is not good UX.

**Comment by tjbck** [comment]
Good catch, Fixed on dev!
