### ISSUE TITLE
[Feature Request] Change/add/remove message image attachements

### ISSUE THREAD

**Issue by josephrocca** [open-webui/open-webui#3403]
**Is your feature request related to a problem? Please describe.**
I was doing a little prompt engineering for an image captioning task today, and tried using `open-webui`, but it was a very poor tool for this task because I had to start a new chat just to switch the image. It'd be better if there were a way to edit/remove/attach an image to/from any message, just like you can edit the text of the message.

**Describe the solution you'd like**
Buttons to edit/remove/attach an image to/from any message.

**Describe alternatives you've considered**
1. Start a new chat each time (annoying)
2. Copy message text, delete all messages, paste message text, attach new image (annoying)
3. Use different software

**Comment by josephrocca** [comment]
An alternative would be to allow attaching images in the "Playground", since that it more designed for prompt engineering, but as far as I can tell, it doesn't yet support image attachments.

**Comment by tjbck** [comment]
Merging this with #3441
