### ISSUE TITLE
feat: Add button to start new chat with the currently selected model

### ISSUE THREAD

**Issue by bannert1337** [open-webui/open-webui#3439]
**Is your feature request related to a problem? Please describe.**
It's somewhat cumbersome to always manually switch models when starting a new chat. A quick way to start a new chat directly with the selected model would streamline the user experience.

**Describe the solution you'd like**
I would like to have a button that, when clicked, starts a new chat with the currently selected model. This would save steps and make the chat initiation process more efficient.

**Describe alternatives you've considered**
An alternative could be to have an automatic prompt or option when ending a chat to start a new one with the same model, but this might be more intrusive compared to a dedicated button.

**Additional context**
This feature could greatly enhance workflow for frequent users who often switch between chats and models. A mockup of the UI with the added button could be provided if needed.

**Comment by tjbck** [comment]
Refactored on dev to use the previously selected models by default. From the new chat page, if you click on the new caht button once again it'll load your "default" selected model configuration.
