### ISSUE TITLE
No support for Gemini API?

### ISSUE THREAD

**Issue by dillfrescott** [open-webui/open-webui#3482]

**Comment by justinh-rahb** [comment]
Supported with either Functions in WebUI:
https://openwebui.com/f/justinrahb/google_genai/

Or in the [Pipelines server](https://github.com/open-webui/pipelines):
https://github.com/open-webui/pipelines/blob/main/examples/pipelines/providers/google_manifold_pipeline.py

**Comment by dillfrescott** [comment]
Oh, thank you

**Comment by ds0nt** [comment]
This should be a first class citizen like GPT-4.

Why does GPT-4 get special treatment and a spot in 'connections'? I'm starting my own project.

**Comment by ds0nt** [comment]
https://github.com/ds0nt/shed
