### ISSUE TITLE
enh: Haptic Feedback in the Mobile UI

### ISSUE THREAD

**Issue by Smoffyy** [open-webui/open-webui#3513]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Well, I thought that it'd be nice to have haptic feedback, like when swiping to open the side menu with chats, or when the LLM is streaming the response. Kinda like the ChatGPT App, those type of haptic feedbacks. And when using the Call mode, it'll vibrate when it finishes transcribing what you said.

**Describe alternatives you've considered**
None, if its not easily do-able its completely fine. Just thought about giving the Idea.

**Additional context**
None

**Comment by dannyl1u** [comment]
iOS doesn't support vibrations on Safari, perhaps it could be implemented for Android though

https://developer.mozilla.org/en-US/docs/Web/API/Navigator/vibrate#browser_compatibility
