### ISSUE TITLE
Bulk Edit Documents and #tag

### ISSUE THREAD

**Issue by JOduMonT** [open-webui/open-webui#3521]
**Is your feature request related to a problem? Please describe.**
It is very painful and I upload 100 documents and I have to
1. rename each of them to add a prefix (ok I could do it on my computer first, but still)
2. have to edit each of them to add tags (maybe it's only me, but I cannot add a tag during the upload like it seams to be suggest)

**Describe the solution you'd like**
It would be awesome if...
1. it was possible to filter document without tags
2. it was possible **to edit**, _at least_, to [add/rename/remove] tags in bulk (same tag on multiple documents)

**Describe alternatives you've considered**
A documentation to explain how to do it via importing and exporting the Documents Mapping

**Comment by tjbck** [comment]
Closing in favour of #3527
