### ISSUE TITLE
Pull a model from Ollama.com always pulls to main ollama instance

### ISSUE THREAD

**Issue by clang88** [open-webui/open-webui#3548]
# Bug Report

## Description

**Bug Summary:**
If multiple ollama instances are connected, `Pull a model from Ollama.com` always pulls the model to the first instance, even if the second is selected in `Manage Ollama Models`

**Steps to Reproduce:**

1. Connect two Ollama instances
2. Pull a new model on the first instance
3. Now switch managed instance in `Manage Ollama Models`
4. Now try to pull the same model on the second instance (will finish instantly)
5. Verify that the model is missing, when going to `Delete a model`

**Expected Behavior:**
When switching Ollama instance, I expect the new model to be pulled on the instance that is selected in `Manage Ollama Models`. Optionally, it would be great to be able to manage all instances at the same time.

**Actual Behavior:**
Always the first Ollama instance is selected.

## Environment

- **Open WebUI Version:** v0.3.6
- **Ollama (if applicable):** 0.1.48

- **Operating System:** Debian (Open WebUI, Ollama instance 2), Windows 11 (Ollama instance 1)
- **Browser (if applicable):** Chrome 126.0.6478.127

**Comment by tjbck** [comment]
Fixed on dev.
