### ISSUE TITLE
0.3.7: Browser Language Detection - Ignores English setting in Chrome

### ISSUE THREAD

**Issue by brunocerq** [open-webui/open-webui#3550]
# Bug Report

## Description

**Bug Summary:**
After updating to 0.3.7 the UI is presented in the browser language ignoring the language option set in settings if the language chosen it English (US and GB).

**Steps to Reproduce:**
Update to 0.3.7 running on a machine with browser language different from the UI language settings.

**Expected Behavior:**
Expected the UI to be displayed with the language set in settings (Portuguese), in my case I want the UI to be presented in English (US) but even with the language setting to English the UI is always showed in Portuguese (My browser language setting).

**Actual Behavior:**
The UI is being presented in the browser language (Portuguese) whenever I choose English (US) or English (GB) in settings, it DOES change for any other language other then English.

## Environment

- **Open WebUI Version:** [0.3.7]
- **Ollama (if applicable):** [0.1.47]

- **Operating System:** [Windows 11/Docker Desktop]
- **Browser (if applicable):** [Chrome 126.0.6478.127]

## Reproduction Details

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [X] I am on the latest version of both Open WebUI and Ollama.

## Logs and Screenshots

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]
![Screenshot 2024-06-30 102330](https://github.com/open-webui/open-webui/assets/30045642/b5e5c5f2-3b8f-4805-8de1-f22dcd431c9a)

## Installation Method

[Docker Desktop]

## Additional Information
Cookies deleted in chrome, behaviour is the same, in Firefox it's working fine.

**Comment by brunocerq** [comment]
![Screenshot 2024-06-30 114557](https://github.com/open-webui/open-webui/assets/30045642/5cf6427c-6d7d-4d61-8eaf-16b0ff518222)

**Comment by PiMaV** [comment]
I can confirm this behaviour for
ubuntu / docker / webui 0.3.7 with Browserlanguage in German

**Comment by agusmdev** [comment]
Same happening to me, can't make it work in english

**Comment by tjbck** [comment]
Should be fixed with the latest main, let me know if the issue persists!
