### ISSUE TITLE
Add switch to disable RAG on attachments.

### ISSUE THREAD

**Issue by nickovs** [open-webui/open-webui#3556]
Currently if you drop even a single document onto Open WebUI and ask a question about that document, it appears that RAG is always used. It would be helpful to be able to switch this off.

Currently, for each attachment the document text is extracted, the text is chunked, embeddings computed and indexed, an index lookup is performed and then some of the chunks are passed to the LLM. While this is an OK solution for retrieval tasks, it abjectly fails for summarisation tasks.

For LLMs with small context windows summarisation is hard, but many LLMs now support very large context windows; GPT-4o has a 128K context windows and Anthropic Claude 3 support 200K tokens or about 400 pages of text. To make best use of these longer-context models it would be helpful to be able to pass the entire extracted text of all attachments into the LLM. Having a switch to bypass the RAG steps would achieve this.

**Comment by tjbck** [comment]
This behaviour has been changed since 0.3.6

**Comment by nickovs** [comment]
Can you describe the new functionality? I am using 0.3.7 (commit 7bc88eb0) and when I attach a multi-page document in only a subset of 5 pages are being passed as context, not in the order of the original document. If I change the "Top K" parameter to 10 then I get 10 pages passed in, again not in the order of the original document. Clearly there is something still preventing more than the "top k" hits from being used and the re-ordering suggests that they are coming from some sort of lookup result.

**Comment by hkosm** [comment]
+1 A toggle to completely disable RAG would be great. E.g. also when using an external RAG system and relying on the __files__ object in custom tools.

**Comment by buger** [comment]
Can confirm, much needed!  In the long term, smth like Claude projects will be amazing, and I'm pretty sure it just puts the whole content of files to the context.

**Comment by NeverOccurs** [comment]
Try this:
https://github.com/NeverOccurs/full_doc_pipe
Use it as a filter function in Open-Webui. It allows uploading a file and push it fully into system prompt. Then you can direct ask the LLM to summarize it or whatever. It doesn't support changing file midway through the chat though.
Still optimizing it but for now I think it is enough for my use case. I'm trying to incorporating it with Claude's prompt caching to minimize cost.

**Comment by juancarlosm** [comment]
Definitely necessary, at least to deactivate the RAG process by model, for example, to send the file to an agent like open-interpreter, or to user an OpenAI assistant that handles the file directly, it doesn't need the RAG stuff.

**Comment by antirez** [comment]
> This behaviour has been changed since 0.3.6

I don't understand. Here with a one liner the problem is dismissed. People continue to tell that it's really needed (with large context LLMs otherwise OpenWebUI is useless) and no reply is added to clarify. So what's the matter here?

**Comment by leboomer-0x42** [comment]
hello all, for those that missed it (like me before digging prior to "put my self on the list" )
here lies the solution : https://github.com/open-webui/open-webui/issues/7209
magic word to look for in admin pan : BYPASS_EMBEDDING_AND_RETRIEVAL
because a pic is often better than a non native explanation :
![Image](https://github.com/user-attachments/assets/eb3f7bba-c084-4c92-bd2c-cf30c442df2f)

**Comment by Buco7854** [comment]
What would be nice is leave the ability to disable it with like a filter function. It seems like it used to be possible but was removed (why?). The main usecase would be for code execution where you typically does not need to embed a spreadsheet for example.

**Comment by ConstantinEilebrecht** [comment]
A toggle per model would be great to have full flexibility if you connect other system like n8n etc. for complex workflow. In these cases you don't need to start the RAG process within owui.

**Comment by Buco7854** [comment]
I do not find the toggle to be really flexible depending on what you need to do. But just giving the ability to handle file upload in a filter function would be enough. People that just want a toggle could just do it based on a UserValve and people that need something a bit more advance could also do it. Looking at the code base it seems embeding the file would be as simple as calling a function.

**Comment by dotmobo** [comment]
+1

I added a model (GLM OCR) as a chat model and I want to be able to pass both images and PDFs to it. 

Images are working correctly. However, for PDFs, the GLM OCR model does not receive the actual file because the system uses Apache Tika for content extraction and a RAG process.

I want to keep the RAG and Apache Tika workflow for all other models, but disable it specifically for the GLM OCR model.

**Comment by Classic298** [comment]
@dotmobo would a file_handle filter do that job for you?

**Comment by mberymon** [comment]
So this is just going to continue to languish in limbo going on three years now? Disappointing :(

**Comment by Classic298** [comment]
@mberymon  you can already disable RAG on attachments by disabling file_context and citations
