### ISSUE TITLE
bug: Unwanted TTS Narration of Web Search Results

### ISSUE THREAD

**Issue by bannert1337** [open-webui/open-webui#3578]
# Bug Report

## Description

**Bug Summary:**
After using the web search, the search results are also narrated with TTS.

**Steps to Reproduce:**
1. Open the Open-WebUI interface.
2. Perform a web search using the search functionality.
3. Observe that the search results are narrated using TTS.

**Expected Behavior:**
The search results should be displayed without being narrated by TTS.

**Actual Behavior:**
The search results are narrated with TTS, which is not the expected behavior.

## Environment

- **Open WebUI Version:** [e.g., 0.1.120]
- **Ollama (if applicable):** [e.g., 0.1.30, 0.1.32-rc1]

- **Operating System:** [e.g., Windows 10, macOS Big Sur, Ubuntu 20.04]
- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]

## Reproduction Details

**Confirmation:**

- [ ] I have read and followed all the instructions provided in the README.md.
- [ ] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Installation Method

[Describe the method you used to install the project, e.g., manual installation, Docker, package manager, etc.]

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by silentoplayz** [comment]
> ## Environment
> Open WebUI Version: [e.g., 0.1.120]
> Ollama (if applicable): [e.g., 0.1.30, 0.1.32-rc1]
> Operating System: [e.g., Windows 10, macOS Big Sur, Ubuntu 20.04]
> Browser (if applicable): [e.g., Chrome 100.0, Firefox 98.0]

It appears that both your Open WebUI and Ollama installations are outdated. This may be causing the issue at hand. Please update them accordingly to their latest versions from their respective GitHub release pages.

**Open WebUI** - [v0.3.7](https://github.com/open-webui/open-webui/releases/tag/v0.3.7)
**Ollama** - [v0.1.48](https://github.com/ollama/ollama/releases/tag/v0.1.48)

**Comment by silentoplayz** [comment]
Please update your Ollama and Open WebUI instances to their latest versions from their respective GitHub release pages and let us know if this issue still occurs still afterwards.

**Open WebUI** - [v0.3.7](https://github.com/open-webui/open-webui/releases/tag/v0.3.7)
**Ollama** - [v0.1.48](https://github.com/ollama/ollama/releases/tag/v0.1.48)
