### ISSUE TITLE
enh: Allow Only OAuth Signup/Signin

### ISSUE THREAD

**Issue by Louden7** [open-webui/open-webui#3663]
**Describe the solution you'd like**
With the ability to sign up/in now with OAuth2, the option to only allow OAuth2 and remove the default email and password fields would be a great feature. This could be accomplished by adding a new optional environment variable to "hide" or remove the default email and password fields. The optional environment variable would have a default value of `false` (not hidden) and only used when `ENABLE_OAUTH_SIGNUP=true`. 

**Describe alternatives you've considered**
Able to disable signups with environment variables but this does not remove the username and password fields resulting in a undesired cluttering when only wanting to use OAuth for logins.

**Comment by tjbck** [comment]
PR welcome!

**Comment by Seth-Rothschild** [comment]
@Louden7 I care about this too! If it's ok with you I can put in a PR for it. I have a branch at https://github.com/Seth-Rothschild/open-webui/tree/hide-password-login that adds an environment variable `ENABLE_PASSWORD_LOGIN` which defaults to `true` and hides the password form when it's switched to `false`.

**Comment by tofasthacker** [comment]
Has there been any progress in merging this to the main branch.

**Comment by 812781385** [comment]
Maybe you should try it：
https://github.com/812781385/ollama-webUI

**Comment by Louden7** [comment]
Started working on an implementation. Looks to be easy enough to set an environment variable that corresponds to a html element style variable and setting it to `display: none;`. 

Taking a bit more time than expected however because Im unfamiliar with all the connections between the backend and frontend with the env vars.

**Comment by Louden7** [comment]
Closing with the recent merge #4068.
