### ISSUE TITLE
{{CURRENT_TIME}} is not shifting to local time in presentation - reporting UTC0.

### ISSUE THREAD

**Issue by jason-e-gross** [open-webui/open-webui#3681]
# Bug Report

## Description

**Bug Summary:**
Giving the prompt  {{CURRENT_TIME}} is off by 5 hours, appears to be a bad timezone shift?

**Steps to Reproduce:**
Add CURRENT_TIME to the prompt, ask  the model what time it is.  

**Expected Behavior:**
For it to report the accurate time according to the machine it's on.

**Actual Behavior:**
The time is 5 hours in the future -- I suspect its a malformed timezone shifting.

## Environment

- **Open WebUI Version:** [e.g., 0.1.120]
- **Ollama (if applicable):** [e.g., 0.1.30, 0.1.32-rc1]

- **Operating System:** [e.g., Windows 10 for browser to openWebUI,   ollama and openWebUI running on Ubuntu server -- all have the same time/date ]
**Confirmation:**

- [X ] I have read and followed all the instructions provided in the README.md.
- [X ] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Screenshots (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

The prompt.
![image](https://github.com/open-webui/open-webui/assets/16501884/c143ad68-6b42-43f0-802f-c91c3d0fc90e)

It responding with an incorrect time.
![image](https://github.com/open-webui/open-webui/assets/16501884/5e97edc7-090d-4f47-bacd-8c439e5c9da3)

Super blurry, but this is the machine webui and ollama are running on, same time/date.
![image](https://github.com/open-webui/open-webui/assets/16501884/017bb40b-5757-49f0-86e0-5e23c6389df6)

Worth noting, I'm in CST - which happens to be -5 -- so this looks like it's not shifting the time to the local time, and using UTC0 time to report the time. 

Seems like date/time should be shifted local, because asking it for something like hourly forecast is gonna be weird - and it doesn't feel very natural for a human having to do that work to talk to an AI?

Later edit:  also worth noting, I asked it for the current time, but shift to CST - and it seems to think the time it reports (which is UTC0 is already shifted).   

Later later edit:
I was able to get it to behave, of sorts, with this prompt 

> The current date and time is {{CURRENT_DATE}}.  The current time is {{CURRENT_TIME}}, but subtract five hours from that time whenever you use or report it.  Don't bother telling me you did the adjustment.   You are a friendly and helpful assistant.  

but, its still kinda braindead in terms of figuring things out, it has July 6/2024 right, but thinks its a Friday
![image](https://github.com/open-webui/open-webui/assets/16501884/dda2b145-dbc1-40d3-aa5c-9dfcc11c0880)

**ANOTHER EDIT**
It appears to taking localized date format, and converting it wrong.    Even though it's telling me correctly that today is July 06, 2024 - when I ask what day of the week that is, it's doing that work via "07-06-2024", European flavor -- (ie, reading it as 7th of June - and telling me its a Friday".

**Comment by jason-e-gross** [comment]
Funnily enough, I got it to behave by adjusting its prompt to this: 

```
The current date and time is {{CURRENT_DATE}}.  The current time is {{CURRENT_TIME}}, but subtract five hours from that time whenever you report it - and don't bother telling me you did the adjustment.  You are a friendly and helpful assistant.  
```

**Comment by justinh-rahb** [comment]
Another fix for this is to set the `TZ` environment variable on your Docker host, or the WebUI container.

**Comment by jason-e-gross** [comment]
I appreciate the response, I'll give that a shot. Thanks.

________________________________

**Comment by jason-e-gross** [comment]
> Another fix for this is to set the `TZ` environment variable on your Docker host, or the WebUI container.

Worked like a charm, that's the answer.   Thanks @justinh-rahb .
