### ISSUE TITLE
Add temperature and top_p adjustion in playground.

### ISSUE THREAD

**Issue by jtc1246** [open-webui/open-webui#3698]
**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add temperature and top_p adjust bar in playground.

**Describe alternatives you've considered**
No

**Additional context**
I know that temperature and top_p can be adjusted in Settings / Advanced parameters. But in api testing, temperature and top_p is a very important parameter to test, which is needed to change very frequently. Each time adjusting in settings is too troublesome.

**Comment by jtc1246** [comment]
#1625

**Comment by jtc1246** [comment]
#1625

**Comment by tjbck** [comment]
Duplicate #2565

**Comment by jtc1246** [comment]
Can use this, https://github.com/jtc1246/openai-playground.
