### ISSUE TITLE
enh: Support disabling connections

### ISSUE THREAD

**Issue by AnotiaWang** [open-webui/open-webui#3735]
**Is your feature request related to a problem? Please describe.**
Sometimes when I want to test the performance of models from different LLM providers, I set up a lot of connections on the website. After testing, I want to temporarily delete a connection from a certain provider and wait to try again later.

**Describe the solution you'd like**
Allow site admins to disable connections in Admin Panel - Connections. Disabled connections will be excluded when fetching the model list.

**Describe alternatives you've considered**
No

**Additional context**
No

**Comment by tjbck** [comment]
Closing in favour of #5119
