### ISSUE TITLE
bug: `__event_emitter__` broken for function outlets

### ISSUE THREAD

**Issue by michaelpoluektov** [open-webui/open-webui#3737]
# Bug Report

## Description

The following definitions for `__event_emitter__` and `__event_call__` make no sense:

https://github.com/open-webui/open-webui/blob/24ef5af2a13caccb917e538f536ba03230dac1d6/backend/main.py#L1180

They expect the user to provide a chat, message and session ID in the payload.

Additionally, neither `__event_emitter__` nor `__event_call__` are available from the `pipe()` method of regular pipelines: only filter pipelines work.

`__event_emitter__` and `__event_call__` should ideally be stored somewhere with the session.

**Comment by nomppy** [comment]
Were you able to fix this? I downloaded a function from [the functions page](https://openwebui.com/functions) ([this one](https://openwebui.com/f/hub/autotool_filter)), but I'm getting errors that the `__event_emitter__` parameter is missing, `__model__` is also not being passed to the `inlet()`

**Comment by michaelpoluektov** [comment]
This was fixed in a PR (I believe merged somewhere around 0.3.8).

I don't know exactly what issue you're facing but assuming you're using the latest version of OWUI I'd try to define your inlets/outlets as:

```python
def outlet(..., __event_emitter__=None):
```

Then check that `__event_emitter__` is not None before calling it.

Might be the inlets/outlets being called to generate titles and whatnot

**Comment by nomppy** [comment]
> I don't know exactly what issue you're facing but assuming you're using the latest version of OWUI I'd try to define your inlets/outlets as:

I'm silly, I wasn't on the latest version. Building the new image now
