### ISSUE TITLE
Error during SSO-Login

### ISSUE THREAD

**Issue by RobinDev03** [open-webui/open-webui#3797]
# Bug Report

## Description

**Bug Summary:**
When trying to Log-In via OIDC, Open-Webui returns an error.

**Steps to Reproduce:**
1) Register normally at Open-WebUI
2) Connect an OIDC Provider (authentik)
3) LogIn to Open-WebUI via this OIDC (same E-Mail)

**Expected Behavior:**
Merge Accounts and Log In

**Actual Behavior:**
Open-WebUI returns an error:
```json
{
  "detail": "The email or password provided is incorrect. Please check for typos and try logging in again."
}
```

## Environment

- **Open WebUI Version:** newest (yesterday installed)
- **Ollama (if applicable):** newest (yesterday installed)

- **Operating System:** Debian 12 (Client Win11)
- **Browser (if applicable):** Opera

## Reproduction Details

**Confirmation:**

- [ X ] I have read and followed all the instructions provided in the README.md.
- [ X ] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**

**Docker Container Logs:**

**Screenshots (if applicable):**

## Installation Method

Ollama via install cmd & Open-WebUI manually

**Comment by tjbck** [comment]
https://github.com/open-webui/open-webui/issues/3757
