### ISSUE TITLE
Change config.py not to store secrets in plain text

### ISSUE THREAD

**Issue by michaelpoluektov** [open-webui/open-webui#3831]
**Is your feature request related to a problem? Please describe.**
By default config.py stores secrets (such as `GOOGLE_CLIENT_SECRET`, `MICROSOFT_CLIENT_SECRET` and other OAuth related things) in `PersistentConfig`, which saves all variables to `config.json` in plain text. This is a potential security vulnerability.

**Describe the solution you'd like**
As `wildtangn:3t` from Discord has suggested, users could use [DotenvX](https://dotenvx.com/blog/2024/06/24/dotenvx-next-generation-config-management.html) to store encrypted environment variables. The main change would be to simply avoid wrapping secrets in `PersistentConfig`, but for backwards compatibility reasons it might be useful to keep reading those variables from `config.json` if present, and warn users that storing secrets there is potentially unsafe. 

I understand that the variable will be decrypted in transit anyway and there are no perfect solutions, but it probably better than nothing. Happy to put up a PR if you agree to a direction.

**Comment by michaelpoluektov** [comment]
DotenvX might work in the short term but if we plan to add secrets from the UI it's not a solution: instead we could encrypt secrets using `WEBUI_SECRET_KEY` which is not itself stored.

Here's the current plan: 
- In `config.py`, attempt to read encrypted secrets and decrypt with `WEBUI_SECRET_KEY`. If encrypted secret not present, read unencrypted for backwards compatibility and add the encrypted key. Advise users to delete unencrypted keys from `config.json` after migration.
- When a secret is added, it's encrypted with `WEBUI_SECRET_KEY` and stored as `f"{secret_name}_ENCRYPTED"` in `config.json`.
- When decrypting the secret, verify if decryption was successful and raise if `WEBUI_SECRET_KEY` was not set correctly.

**Comment by justinh-rahb** [comment]
WEBUI_SECRET_KEY can be stored as a file, when the var is left blank then a secret key is generated and inserted into this file. But I'm not sure if when it's set via envvar it populates said file.

**Comment by michaelpoluektov** [comment]
Original PR closed because config is being moved to the database. For now, you should probably just use environment variables.
