### ISSUE TITLE
OpenAI API key is required

### ISSUE THREAD

**Issue by jjasghar** [open-webui/open-webui#3840]
# Bug Report

## Description

**Bug Summary:**
I am running a local `openai` API server, with no API key. I can't seem to see any models. As soon as I put "asdf" or anything in the API Key field it is able to read my local models.

**Steps to Reproduce:**
Just as above in the bug summary.

**Expected Behavior:**
If you have no API key, you shouldn't need to fill it to.

## Environment

- **Open WebUI Version:** 0.3.18?

- **Operating System:** macOS
- **Browser (if applicable):** Safari

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

**Comment by justinh-rahb** [comment]
Working as intended.
