### ISSUE TITLE
Add LaTeX Text Display Support

### ISSUE THREAD

**Issue by hasanraiyan** [open-webui/open-webui#3872]
**Feature Request: Add LaTeX Text Display Support**

**Description:**
I would like to request the addition of LaTeX text display support in Open WebUI. This feature would enable the rendering of mathematical equations and scientific notations in a more readable and visually appealing format within the chat interface.

**Benefits:**
1. **Improved Clarity:** LaTeX allows for precise formatting of mathematical equations and symbols, making complex expressions clearer and easier to understand.
2. **Enhanced User Experience:** Users who work with mathematical or scientific content will benefit from the ability to see well-formatted equations, enhancing their overall interaction with the tool.
3. **Broader Use Cases:** Integrating LaTeX support will make Open WebUI more versatile, especially for academic, engineering, and scientific communities where precise mathematical representation is crucial.

**Use Case:**
- **Math Students and Educators:** Users can input LaTeX code to render equations and formulas directly in the chat, which can be particularly useful for educational purposes.
- **Researchers and Engineers:** Professionals can share complex mathematical models and scientific data in a readable format, improving communication and collaboration.

**Additional Information:**
To implement this feature, you might consider integrating a LaTeX rendering library such as MathJax or KaTeX. These libraries can parse LaTeX code and render it as high-quality mathematical typesetting.

Thank you for considering this request!

**Comment by justinh-rahb** [comment]
Already implemented, but due to repeated issue reports for it being applied too widely to things that _aren't_ LaTeX it's been refactored multiple times, and nobody seems quite happy with it now. Anyway this FR is moot.
