### ISSUE TITLE
Existing Chats Do Not Work [0.3.9]

### ISSUE THREAD

**Issue by ProjectMoon** [open-webui/open-webui#3932]
# Bug Report

## Description

**Bug Summary:**
A chat created in 0.3.8 (or before, presumably) no longer seems to send user input to the server in 0.3.9. Newly created multi-model chats seem to work fine. In the broken chats, you can enter input and hit enter or click send, but no connection is made to the API. 

**Steps to Reproduce:**
1. Install 0.3.8.
2. Create chat and chat with the models.
3. Upgrade to 0.3.9
4. Attempt to chat in that same chat.

**Expected Behavior:**
All models reply.

**Actual Behavior:**
No API requests are sent to the server, and thus no models reply.

## Environment

- **Open WebUI Version:** 0.3.9
- **Ollama (if applicable):** 0.2.5

- **Operating System:** Gentoo Linux
- **Browser (if applicable):** Firefox 128

## Reproduction Details

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [X] I am on the latest version of both Open WebUI and Ollama.
- [X] I have included the browser console logs.
- [X] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
Probably the reason for this. This is a client-side error from the console.

```
Uncaught (in promise) TypeError: De.push is not a function
    _t Chat.svelte:522
    vt MessageInput.svelte:624
```

## Installation Method

Docker.

## Additional Information

Also notice that the title is not being generated in new multi-model chats. Not sure if related.

I originally reported this for multi-model chats, but it actually happens for all chats...

**Comment by ProjectMoon** [comment]
Happens in both Firefox and Chromium.

**Comment by tjbck** [comment]
Fixed with the latest!

**Comment by ProjectMoon** [comment]
So I'm not sure this is fully fixed. Messages can be sent, yes, but it seems like the existing context isn't being sent along with the new request.
