### ISSUE TITLE
Feat: Be able to select Chat Files/Websearch/Websites for RAG

### ISSUE THREAD

**Issue by mr-gepardas** [open-webui/open-webui#4064]
**Is your feature request related to a problem? Please describe.**
It appears since Open WebUI 0.2.5 and Ollama 0.2.2 updates, the way  RAG works has changed, and no longer works like it used to. It seems now, most of the time, only the first LLM message uses the upload of a file or a websearch, consecutive QnA from LLM are ignoring the file/websearch context in the same chat. It's almost like after the first message LLM is completely unaware of RAG of the uploaded file. The only solution for now I found is re-uploading the same file, which unfortunately will quickly fill up my storage with a great number of duplicate files.

**Describe the solution you'd like**
Just like normally we can reference uploaded documents by Main Admin in a model with "#", it would be very useful to be able to reference already uploaded files into a chat using '#' shortcut, that way would save on space as would no longer need to re-upload the same file or website/websearch. 

**Describe alternatives you've considered**
Another solution could possibly be a user file library that could be used  to reference any user uploaded files in any chat.

And another solution would be some toggle on the chat, to always reference uploaded files to a chat, just like it used to be pre-0.2.5 version of Open WebUI.

**Additional context**
N/A

**Comment by justinh-rahb** [comment]
This has been addressed as of WebUI 0.3.10. All chat messages will reference RAG documents unless they're removed from the Chat Settings side panel now.

**Comment by mr-gepardas** [comment]
> This has been addressed as of WebUI 0.3.10. All chat messages will reference RAG documents unless they're removed from the Chat Settings side panel now.

I have the 0.3.10, and can see that with files that does appear to be the case, even though sometimes there are occasions where it stops referencing the file, but with any Web Search (using Searxng) it seems it does not reference them as files, so those are always only mentioned on the first response, after which the only option would be to add searched websites manually in the next message

**Comment by justinh-rahb** [comment]
Depends on which SearXNG method you're using. The **Tool** available on openwebui.com and installed in **Workspace** indeed does not RAG results, whereas the built-in function that's setup through **Admin Settings**

**Comment by mr-gepardas** [comment]
> Depends on which SearXNG method you're using. The **Tool** available on openwebui.com and installed in **Workspace** indeed does not RAG results, whereas the built-in function that's setup through **Admin Settings** does.

Would it be possible to explain more about the difference between the two? As I am currently using the setup through Admin Settings -> Web Search -> Web Search Engine -> searxng. And from the chats I had it does not appear to use the results at all after the first message.
