### ISSUE TITLE
bug(ui): web search prompt duplicate

### ISSUE THREAD

**Issue by thearyadev** [open-webui/open-webui#4176]
# Bug Report

## Description
web search prompt shows twice

**Bug Summary:**
<img width="1142" alt="image" src="https://github.com/user-attachments/assets/a79f4717-a4f0-46f0-ab2f-0f46bbacc4da">

**Steps to Reproduce:**
1. enable web search
2. send message

**Expected Behavior:**
<img width="1142" alt="image" src="https://github.com/user-attachments/assets/496bd180-7e8c-4fa2-aeef-c4a2ce775820">

**Actual Behavior:**
<img width="1142" alt="image" src="https://github.com/user-attachments/assets/a79f4717-a4f0-46f0-ab2f-0f46bbacc4da">

## Environment

- **Open WebUI Version:** dev branch https://github.com/open-webui/open-webui/commit/0ced153f8663a1cb2182195a1430f9492cf4853f

- **Browser (if applicable):** arc

**Comment by silentoplayz** [comment]
I can confirm this exact issue also happens for me:
![image](https://github.com/user-attachments/assets/09348a32-5ee7-4ba6-abeb-5ff427627fc8)

**Comment by tjbck** [comment]
Fixed!

**Comment by silentoplayz** [comment]
I can confirm this has been fixed.
