### ISSUE TITLE
SSRF Security Advisory

### ISSUE THREAD

**Issue by saimanikanta1992** [open-webui/open-webui#4217]
### Discussed in https://github.com/open-webui/open-webui/discussions/4216

<div type='discussions-op-text'>

<sup>Originally posted by **saimanikanta1992** July 30, 2024</sup>
Kindly review this SSRF security advisory, remediate and approve it. 

https://github.com/open-webui/open-webui/security/advisories/GHSA-hx98-q3cq-qrrp </div>

**Comment by saimanikanta1992** [comment]
@tjbck can you kindly accept this finding.

**Comment by saimanikanta1992** [comment]
@tjbck can you kindly assign the CVE and publish this report.

**Comment by saimanikanta1992** [comment]
@tjbck I have updated the patch version details in the report. Can you please publish the report.

**Comment by rragundez** [comment]
Hi @saimanikanta1992 we found several SSRF vulnerabilities. Unfortunately I cannot see any information on this thread related to see how to solve it or past findings on this same topic.
Can you elaborate on this thread?
