### ISSUE TITLE
Tags not saved for uploaded files

### ISSUE THREAD

**Issue by bcornianu-vsp** [open-webui/open-webui#4235]
# Bug Report

## Description

**Bug Summary:**
When uploading one or more files through the "Workspace -> Documents" section, the tags you set on those files are not saved. The tags are not created in the system and they are not applied to the uploaded files.

**Steps to Reproduce:**
1. Go to Workspace -> Documents
2. Click the plus sign to upload one or more files
3. Select the files to upload
4. Add one or more tags
5. Click "Save"

**Expected Behavior:**
The files are uploaded and the selected tags are created and applied to the files.

**Actual Behavior:**
The files are uploaded but no tag is being created or applied to the files.

## Environment

- **Open WebUI Version:** 0.3.10
- **Ollama (if applicable):** 0.2.6

- **Operating System:** Ubuntu 22.04
- **Browser (if applicable):** Chrome 127.0.6533.89

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.

## Installation Method

Docker

**Comment by tjbck** [comment]
Fixed on dev.
