### ISSUE TITLE
feat: Add support for Min_P (Ollama v0.3.1) in Chat Controls

### ISSUE THREAD

**Issue by Arcitec** [open-webui/open-webui#4278]
Ollama v0.3.1 was just released, which adds support for the incredibly good new `min_p` sampling option:

https://github.com/ollama/ollama/releases/tag/v0.3.1

OpenWebUI has a Chat Controls area in the top right where users can signal which sampling methods and values they want to use. Min P belongs there. Although I am not sure how it interacts with defaults for other values such as Top P.

The whole purpose of Min P is that it's a much better, more creative yet consistent sampler than all others before it. It's a direct replacement for Top P, Mirostat, etc. It achieves this by simply saying "place the minimum token probability cutoff at X% of the top token's probability". This means that you get a dynamically gated word selection, which leads to more creativity, while remaining very logical and consistent.

I see that OpenWebUI sends some default values for the old samplers, such as "Top P = 0.9", so I am unsure how to deal with that. Or perhaps those parameters aren't sent to Ollama's API unless the user changes them from "Default" to "Custom"?

Either way, here's a link to the author's own explanation, which is a very good read:

https://www.reddit.com/r/LocalLLaMA/comments/17vonjo/your_settings_are_probably_hurting_your_model_why/

:)

**Comment by Arcitec** [comment]
Oh and here is the original pull request where llama.cpp implemented it, if anyone wants to see more discussion of its strengths:

https://github.com/ggerganov/llama.cpp/pull/3841

**Comment by Arcitec** [comment]
Here's an image with the author of Min P's own recommended "General Settings" for using this sampler:

![image](https://github.com/user-attachments/assets/865cc524-12c1-4bc8-9f15-57786e1892ed)

**Comment by tjbck** [comment]
Added to dev!

**Comment by Arcitec** [comment]
@tjbck Thank you so much, it works great! I especially liked your 2nd patch which allows the option to be saved on a per-model basis. Very nice! :)

https://github.com/open-webui/open-webui/commit/8fcb5cee667aa2fa26fe45ff9113a913c6979966
