### ISSUE TITLE
Page lag with long conversations

### ISSUE THREAD

**Issue by mdillondc** [open-webui/open-webui#4310]
# Bug Report

## Description

**Bug Summary:**
When having fairly long conversations with an AI (doesn't matter which one), the page UI starts to stutter/lag and sometimes becomes unresponsive until the AI has finished generating a response.

**Steps to Reproduce:**
- Open two windows in your browser of choice
- Have the exact same conversation with e.g. gpt-4o in open-webui in one browser window, then have the exact same conversation with gpt-4o on chatgpt.com in the other window.

**Expected Behavior:**
Neither conversation should cause the tab/browser window to stutter/lag when it becomes long.

**Actual Behavior:**
In open-webui, the page can, if the conversation is long enough, become unresponsive until the AI has finished its response. Before that, it  becomes "stuttery". But on chatgpt.com the page is very fast and responsive no matter how long the conversation is.

## Environment

- **Open WebUI Version:** v0.3.10
- **Ollama (if applicable):** 0.3.0 (not relevant since I am using chatgpt in this example)

- **Operating System:** Ubuntu 22.04
- **Browser (if applicable):** Brave and Firefox
- **CPU**: AMD Ryzen 9 5950X (32) @ 4.000GHz
- **GPU**: AMD ATI Radeon 6900 XT
- **Memory**: 32GB

## Reproduction Details

**Confirmation:**

- [ x] I have read and followed all the instructions provided in the README.md.
- [ x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

**Comment by tjbck** [comment]
#3620
