### ISSUE TITLE
[BUG] Could not be deleted after @model was selected

### ISSUE THREAD

**Issue by Yanyutin753** [open-webui/open-webui#4324]
# Bug Report

## Description

**Bug Summary:**
Could not be deleted after @model was selected

## Note

https://github.com/user-attachments/assets/1b4cf0fa-96ff-4b13-ab31-838208a6e119

**Comment by silentoplayz** [comment]
I can confirm that this bug is happening to me as well on v0.3.11 of Open WebUI.
