### ISSUE TITLE
"(intermediate value).map is not a function" on message send/generation with custom stop tokens

### ISSUE THREAD

**Issue by lee-b** [open-webui/open-webui#4340]
# Bug Report

## Description

When sending messages, with a custom stop token set in the chat's side panel properties, I get this error:

"(intermediate value).map is not a function"

Also, when regenerating a message, I get this similar error inline, as the message body (but when the message background red):

"Uh-oh! There was an issue connecting to (model).
(intermediate value).map is not a function"

Setting a stop token of "<|im_end|>" in the chat properties seems to cause this.

Setting the same stop token in the (base) workspace model advanced properties works fine, however.  This seems to be a good indication of the problem (escaping in the side panel values missing, whilst present in the workspace model properties), as well as a workaround.

## Version

HEAD, as of yesterday (d3146d20ad74c020855142b2bf7e371f981ec098)

**Comment by tjbck** [comment]
Fixed on dev!
