### ISSUE TITLE
🚨 There seems to be a performance reduction after fixing markdown rendering in dev

### ISSUE THREAD

**Issue by Yanyutin753** [open-webui/open-webui#4398]
# Bug Report

### 🚨 There seems to be a performance boost after fixing markdown rendering

![image](https://github.com/user-attachments/assets/abbc7834-fff5-498f-a979-e065f21cfddd)

**Comment by Yanyutin753** [comment]
Especially when dealing with code, memory grows fast 🥹 @tjbck

**Comment by Yanyutin753** [comment]
Usually, it is about 100 MB, now can run 380 to 500MB and sometimes have breakdown

**Comment by tjbck** [comment]
Should be addressed, let me know if it's still being problematic for you.
