### ISSUE TITLE
feat: granular permissions, and user groups

### ISSUE THREAD

**Issue by oliverbob** [open-webui/open-webui#446]
In the admin dashboard, it would be nice if we can add a feature to hide/disable/enable (not just delete) a model.

Reason:

One organization has a private model that they don't want to share with other users or organizations.

Or perhaps, let's provide a convenient way for organizations to access only allowed models via: Groups or organization.

For instance if a news entity will be accessing the UI, it is very impractical for them to see the medical models from a hospital. Also, it is not a good alternative to have a separate UI for them.

**Comment by justinh-rahb** [comment]
More granular permissions, and user groups would be handy and I'm sure these would make sense to put on the longterm roadmap.

**Comment by justinh-rahb** [comment]
Related #449

**Comment by GeoSaffer** [comment]
this would be awesome, please add it

**Comment by silentoplayz** [comment]
Related #1096

**Comment by tjbck** [comment]
Closing in favour of #2924
