### ISSUE TITLE
Enable Chat Sharing for Non-Registered Users

### ISSUE THREAD

**Issue by RexWzh** [open-webui/open-webui#4517]
**Is your feature request related to a problem? Please describe.**

I want to share chats with friends and currently, I can obtain the link by clicking on the button:

![image](https://github.com/user-attachments/assets/e0f09832-44a6-4a0f-b959-c35ef79352d2)

However, non-registered users are unable to access the shared link.

![image](https://github.com/user-attachments/assets/e3001608-4105-4fea-b362-61bfe4c13081)

**Describe the solution you'd like**

After reviewing the README file and searching through the documentation, I couldn't find a variable to control this setting. The available variables only pertain to "sharing to the Web-UI community" using `ENABLE_COMMUNITY_SHARING`.

**Describe alternatives you've considered**

Enable outsiders to view the chat by implementing a variable such as `ENABLE_OUTSIDER_SHARING`.

This feature would be very beneficial when sharing interesting chat logs or useful solutions with friends.

Thanks in advance!

**Comment by tjbck** [comment]
#2904
