### ISSUE TITLE
Custom Logo Support

### ISSUE THREAD

**Issue by anunol** [open-webui/open-webui#4585]
It would be useful if the backend of Open Webui could support the ability to easily change the logo displayed in the interface. This would allow users to customize the branding and appearance of the workspace to better fit their needs or preferences.

**Comment by justinh-rahb** [comment]
The backend already in fact supports this, for sponsors:
https://github.com/sponsors/tjbck

**Comment by MadMacMig** [comment]
This is an open source project right? We could at least have a way of changing the logo and favicon, it wouldn't necessarily have to be UI based, it could even be a file change with the directory, even if everything still says Open-WebUI in the footers and menus etc.
 I appreciate all of the effort put into this project, but giving the option of changing the logo would be great!
