### ISSUE TITLE
ENABLE_ADMIN_CHAT_ACCESS now manages 'see chats' AND 'delete user'. Please allow delete user for admin users regardless of this setting.

### ISSUE THREAD

**Issue by m8dhouse** [open-webui/open-webui#4591]
**Is your feature request related to a problem? Please describe.**
Currently as admin using the ENABLE_ADMIN_CHAT_ACCESS I can see chats from other users and delete users. When ENABLE_ADMIN_CHAT_ACCESS=false (as it should be) is removes chat access, BUT also removes the option for me as admin to delete users. The 'delete users' icon should not be removed when the ENABLE_ADMIN_CHAT_ACCESS=false.

**Describe the solution you'd like**
as admin I should always be able delete users

**Describe alternatives you've considered**
re-enable ENABLE_ADMIN_CHAT_ACCESS=true for now - but also gives me access to chats (GDPR privacy issue)

**Additional context**

**Comment by tjbck** [comment]
Fixed on dev.
