### ISSUE TITLE
Render Math

### ISSUE THREAD

**Issue by maxkonrad** [open-webui/open-webui#4592]
When api's return mathml code to be rendered, it doesn't render math but prints everything as it is. I don't know if it is possible by changing markdown editor, but this app really needs a solution.

I want it to render when api return mathml code.

Alternative solution may be to render math online and see it, but this is of course a bad solution.

I will be sending how it looks like when it is not rendered.

![image](https://github.com/user-attachments/assets/444ec041-5036-4878-bef5-51f6a19d5dd9)
![image](https://github.com/user-attachments/assets/d9c5fbcf-2ba3-4d64-b340-2b977d117ab5)

**Comment by tjbck** [comment]
Please check for duplicate issues, Thanks! #4490

**Comment by maxkonrad** [comment]
Thanks
