### ISSUE TITLE
enh: temp chat

### ISSUE THREAD

**Issue by tjbck** [open-webui/open-webui#4599]
deprecate enable/disable chat history and introduce temp chat mode

**Comment by ccrvlh** [comment]
Was going to suggest the same think - i think ChatGPT UI is a pretty solid implementation:

- small toggle to define "Temporary Chat" on the model selection, or on the new chat button
- grey's out the history
- adds a "Clear Chat" button 

I personally find myself spending quite a bit of time cleaning up simple/old chats that are actually a simple question.

**Comment by tjbck** [comment]
Added to dev.
