### ISSUE TITLE
Regression: 0.3.13 renders < as &lt; and > as &gt;

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [open-webui/open-webui#4615]
It started happening as soon as I got to 0.3.13, which is a problem to me because I was telling the LLM to use`<thinking>` tag before answering.

Here's an example:
![image](https://github.com/user-attachments/assets/a38735b3-6703-45f2-ac25-2ab4a1d7cc77)

**Comment by tjbck** [comment]
Fixed on dev.
