### ISSUE TITLE
feat: tavernai character import support

### ISSUE THREAD

**Issue by velaton618** [open-webui/open-webui#467]
**Is your feature request related to a problem? Please describe.**

Now, there is no way for me to import TavernAI characters as png files, I can only try to copy their content and create modelfile.

**Describe the solution you'd like**

Add a way to import modelfile as png from TavernAI

**Describe alternatives you've considered**

**Additional context**

**Comment by tjbck** [comment]
Hi, Thanks for the suggestion! I'd like to consider your feature request but I'm not really familiar with TavernAI, Could you share example TavernAI character files with us? If you could also elaborate more on the use case and the import workflow you have in mind, that would be clarify things for us and would be helpful to understand what exactly you're asking for, Thanks!

**Comment by uaquax** [comment]
here's an example. You can also find others here: https://www.chub.ai

![main_loki-laufeyson_tavern](https://github.com/ollama-webui/ollama-webui/assets/98014243/19a6871e-ecf7-4535-87ae-785b460b27d4)

There are properties like description of a characer inside png metadata.

**Comment by uaquax** [comment]
TavernAI is a web ui for apis like text-generation-web-ui, where you can role play with virtual characters(they are stored using pngs metadata). It's almost the same as modelfiles in ollama, but it would be easier if I could import any character from the website above.

You could get the metadata and put it to systemprompt and name of modelfile, and then use the png as an avatar of the modelfile.

**Comment by Arcitec** [comment]
It wouldn't work to "just import those things". Open-WebUI would need support for conversation topics/character memory. If that's implemented, it would then be pretty trivial to write a converted that loads a character and saves it as a "topic" with relevant keywords and prompt injection strings.

This feature would not be doable until #2382 exists.

**Comment by tjbck** [comment]
Closing in favour of #2382
