### ISSUE TITLE
Configure "Allow Editing Assistant Messages"

### ISSUE THREAD

**Issue by rndmcnlly** [open-webui/open-webui#4675]
**Is your feature request related to a problem? Please describe.**
I'm going to be using OWUI for structured dialog assignments in an upcoming university course, and I'd like more confidence that the conversation transcripts submitted by the student are authentic. Currently, because users may edit any past messages, including assistant messages, they make manipulate the conversation history to look however they want.

**Describe the solution you'd like**
In `Settings > User Permissions`, just after `Allow Chat Deletion`, I'd like to be able to have an option like `Allow Editing Assistant Messages`. Like the deletion policy, this setting would apply to only users and not admins. The effect should be to remove the pencil icon from the options below assistant messages. This would also help simplify the interface that might be used by stressed-out students.

**Describe alternatives you've considered**
n/a

**Additional context**
In order to make it more likely that the conversations submitted by my students are authentic, I do not ask them to download the conversation (e.g. as a pdf file) and then upload load it to the school systems. Instead, I've implemented a OWUI Action that allows the students to side-load their submissions directly from the chat interface. This avoids a temptation for students to edit intermediate files or submit files generated by another student. However, it doesn't stop students from arbitrarily manipulating the text of assistant messages seen inside the conversation.

**Comment by tjbck** [comment]
<img width="701" alt="image" src="https://github.com/user-attachments/assets/7dfa16e6-24d2-4dc3-a056-d292e843fa86">


Added to dev!
