### ISSUE TITLE
Configure "Allow Response Ratings"

### ISSUE THREAD

**Issue by rndmcnlly** [open-webui/open-webui#4676]
**Is your feature request related to a problem? Please describe.**
The selection of buttons below each message is currently quite busy, and two of them are related to rating the message quality. If I'm deploying OWUI in a setting where there is no staff to review and act on these ratings, I'd like to be able to disable this feature in a way that results in simplifying the interface for my potentially stressed-out student users

**Describe the solution you'd like**
In `Settings > User Permissions`, just after `Allow Chat Deletion`, I'd like to be able to have an option like `Allow Response Ratings`. Like the deletion policy, this setting would apply to only users and not admins. The effect should be to remove the thumbs up/down from the options below assistant messages.

**Describe alternatives you've considered**
n/a

**Additional context**
The fewer buttons that are listed below each message, the more obvious it will be when I am adding custom Actions for my users. Currently, I am reluctant to add more because the interface is already somewhat overwhelming for new users. I would happy disable Rating in order to help direct attention to a wider array of Actions (further showcasing the exciting flexibility of OWUI!).

**Comment by GrayXu** [comment]
+1, we need this feature.  
By the way, I actually don't understand where these Response Ratings will be collected and counted in the end?
