### ISSUE TITLE
Bug: using several of the same model at the same time corrupts the answer

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [open-webui/open-webui#4733]
# Bug Report

## Installation Method

docker compose

## Environment

- **Open WebUI Version:** 0.3.13
- **Operating System:** ubuntu 22
- **Browser (if applicable):** brave

**Confirmation:**

- [ X ] I have read and followed all the instructions provided in the README.md.
- [ X ] I am on the latest version of both Open WebUI and Ollama.
- [ X ] I have included the browser console logs.
- [ X ] I have included the Docker container logs.
- [ X ] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

2 message

## Actual Behavior:

1 empty message and 1 corrupted message

## Description

**Bug Summary:**
If you select twice the same model and ask for an output they will write at the same location at the same time, producing nonsense.

## Reproduction Details

**Steps to Reproduce:**
Select twice the same model at the top, then ask the LLMs something

## Logs and Screenshots

**Browser Console Logs:**
No errors nor warnings

**Docker Container Logs:**
No errors nor warnings

**Screenshots/Screen Recordings (if applicable):**
![image](https://github.com/user-attachments/assets/5cbbb149-1c1e-402d-8271-a4cd318e2e86)
![image](https://github.com/user-attachments/assets/4700133e-9782-4ab1-af6d-975c7d9f384b)

**Comment by tjbck** [comment]
Fixed on dev.
