### ISSUE TITLE
Fabric AI integration 

### ISSUE THREAD

**Issue by fahadshery** [open-webui/open-webui#4741]
**Is your feature request related to a problem? Please describe.**
I am using https://github.com/danielmiessler/fabric a tool that is very handy to take notes from YouTube videos and it works flawlessly with Ollama.
The output then have to be saved manually in a txt/markdown format etc.
It would be nice to integrate it with open-webui and seeing the output there.

**Describe the solution you'd like**
A sub menu for summarisation/fabric that sends and displays fabric output

**Describe alternatives you've considered**
Manually saving output from Fabric

**Comment by justinh-rahb** [comment]
Use search:
- #4102 
- #4111
