### ISSUE TITLE
 Chatting with two models at once, second request takes history (first answer) from one model and uses it in request to both models #4739 

### ISSUE THREAD

**Issue by vlsav** [open-webui/open-webui#4801]
Same issue as in #4739 
Checked with open-webui  v0.3.15
Is it possible to have separate chats with several models, when particular model responses are sent only to this model, not to others?

**Comment by tjbck** [comment]
<img width="1238" alt="image" src="https://github.com/user-attachments/assets/5558607a-78c2-471f-917e-960d0ff29151">

0.3.15 doesn't have the issue, please make sure you've updated to the latest.

**Comment by vlsav** [comment]
@tjbck please have a look on my screenshot, on second request and second answer from two models. It is evident, that both models receive answer on first question from "model 2" in context with second request. I am wondering if this is an expected behavior or not and if it is possible to achieve completely separate request/answer flow for two models, without answers merge.

**Comment by tjbck** [comment]
This is an expected behaviour, the subsequent requests will utilise selected messages is in the chat history.

**Comment by vlsav** [comment]
@tjbck Thank you for clarification. I see, so only one response (selected, or merged if chosen) is used. So it is more relevant to get better result from several models, not to compare different models answers. Do you have plans to utilize separate requests/answers per model?
