### ISSUE TITLE
enh: abillity to add user/assistant message pair

### ISSUE THREAD

**Issue by CookSleep** [open-webui/open-webui#4808]
**Is your feature request related to a problem? Please describe.**
When I want to quickly create historical message records to migrate chat data from elsewhere, I can only continuously send a request and then press the button to abort the output when the model responds. This wastes a lot of time and my API quota.

**Describe the solution you'd like**
Allow generating an empty conversation pair (User+Assistant) by pressing Ctrl+Enter, enabling users to quickly create historical messages.

**Describe alternatives you've considered**
There are no alternative solutions.

**Additional context**
Of course, in the discussion of #4357, there is also an alternative solution of importing data in bulk using CSV files with a specified format. But after careful consideration, I still think creating a pair of empty messages is more convenient and simpler.

**Comment by tjbck** [comment]
<img width="1248" alt="image" src="https://github.com/user-attachments/assets/956261aa-49c3-4135-ae2e-4ddcae8947bf">

You can now use Cmd/Ctrl + Shift + Enter to create a new message pair. Added in dev, testing wanted here!
