### ISSUE TITLE
FEAT: Document Groups for Enhanced Access Control

### ISSUE THREAD

**Issue by RobinBially** [open-webui/open-webui#4809]
**Is your feature request related to a problem? Please describe.** 
Our chat tool is used by various clients, and currently, there is no way to restrict access to confidential documents between different clients. However, documents within a company should be accessible to all employees of that company. This lack of access control can lead to potential security issues and unauthorized access to sensitive information.

**Describe the solution you’d like** 
I propose the implementation of “_Document Groups_” within the Workspace area. This would involve adding a new tab for Document Groups, where each group can have a list of documents and collections, as well as a list of users assigned to it. This feature should function similarly to the existing “Models” feature. If a user with the “User” role is not assigned to any Document Group, they should not be able to select any documents in the chat. A user can also be assigned to multiple Document Groups, in which case they would have access to the union of all documents within those groups.

**Describe alternatives you’ve considered** 
An alternative solution could be to implement individual document permissions, where each document’s access is controlled on a per-user basis. However, this approach could become cumbersome to manage, especially for larger teams or companies with a significant number of documents. 

I am willing to implement this feature and would like to gather feedback from the developers to ensure it aligns with the overall vision and architecture of the tool.

**Comment by tjbck** [comment]
#2924
