### ISSUE TITLE
Fraction Rendering Issue

### ISSUE THREAD

**Issue by IridescentXs** [open-webui/open-webui#4841]
# Bug Report

## Installation Method
Docker

## Environment

- **Open WebUI Version:** [v0.3.15]
- **Operating System:** [Windows 11]
- **Browser (if applicable):** [Edge]

## Description

Fractions are not rendering correctly. As shown in the image, the fraction is displayed as "23" instead of the expected "2/3".

**Screenshots/Screen Recordings:**
![image](https://github.com/user-attachments/assets/02b2bf98-94a9-4fd0-ad4f-271c5144969b)
![image](https://github.com/user-attachments/assets/43ce6316-5d9f-4288-803a-bced3e633686)

**Comment by tjbck** [comment]
Fixed on dev.
