### ISSUE TITLE
Entire application hangs while images are being generated via automatic1111

### ISSUE THREAD

**Issue by tkg61** [open-webui/open-webui#4854]
# Bug Report

## Installation Method

helm install in k8s 

## Environment

- **Open WebUI Version:** v0.3.13 - 3.15 not available in helm yet 
- different server running automatic1111 - latest 
- external openai api for LLMs

- **Operating System:** k8s 1.29 
- **Browser (if applicable):**  Chrome 127

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [X] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [X] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Multiple users are able to use the application without it hanging when an image is being generated

## Actual Behavior:

The entire application stalls while an image is being waited upon. No one else can log in, load the webui, send normal messages to LLMs, etc

## Description

**Bug Summary:**
When an image is being generated the entire application stalls 

## Reproduction Details

**Steps to Reproduce:**

- Run openwebui
- configure for automatic1111 
-  have two web browsers open with two different user accounts. 
- Use one user account to send a request for an image
- use the other to try to log in or do something else that is not an image generation request. 
- Nothing will work

## Logs and Screenshots

**Browser Console Logs:**
there are no error or abnormal logs from the browser
the browser running the image shows no errors and the browser that hangs shows nothing since it is just waiting 

**Docker Container Logs:**
there are no error or abnormal logs from the container

**Screenshots/Screen Recordings (if applicable):**
On the left an image is being re-generated and on the right i am trying to interact with the webui
![image](https://github.com/user-attachments/assets/4b4ad617-107a-4bae-a57a-bce6a8f6c7dd)

**Comment by tjbck** [comment]
Fixed on dev!
