### ISSUE TITLE
A logged-in User can list and view ALL files via API ( /api/v1/files )

### ISSUE THREAD

**Issue by TheMasterFX** [open-webui/open-webui#4855]
# Bug Report
As already mentioned [HERE](https://github.com/open-webui/open-webui/issues/4601#issuecomment-2306889915) it is possible as a User to list, view and I think also deleate ALL files with the User bearer. So it is really easy for a user to see private files of other users.

## Installation Method

Docker

## Environment

- **Open WebUI Version:** v0.3.15
- **Ollama (if applicable):** v0.3.4
- **Operating System:** AlmaLinux 9.4
- **Browser (if applicable):** Chrome 127.0.6533.122 (doens't really matter)

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:
A logged-in user are at least not able to list the files (I think guessing a valid document ID is hard enough)
Since the 

## Actual Behavior:
If a user is logged in the user can open http://WEBUI_API_BASE_URL/api/v1/files to list all files. To view a file the user can view the content by using the document id http://WEBUI_API_BASE_URL/api/v1/files/ec77fad4-a65a-4327-90b7-b64a8910a83/content

## Description

**Bug Summary:**
A user should is able to list and view ALL files via API ( /api/v1/files). This should be reduced only to the files which are uploaded by himself. Since each files has the user information (user_id) it should be possible.

## Reproduction Details

**Steps to Reproduce:**
1. Log-In as a user
2. Enter the url of your Open WebUI and append /api/v1/files
3. Pick a file id and view by appending  /api/v1/files/${id}/content

## Logs and Screenshots
**Screenshots/Screen Recordings (if applicable):**
![image](https://github.com/user-attachments/assets/0777ab77-6576-45bd-97b9-82239145ea94)

## Additional Information
I think this is the affected file https://github.com/open-webui/open-webui/blob/main/src/lib/apis/files/index.ts

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
Fixed on dev.
