### ISSUE TITLE
pip install does not look at PORT env var

### ISSUE THREAD

**Issue by kyllan16693** [open-webui/open-webui#4865]
# Bug Report

## Installation Method

pip

## Environment

- **Open WebUI Version:** v0.3.15

- **Operating System:** Ubuntu 20.04

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

The port OpenWebUI is on should change when the environment variable `PORT` is changed 

## Actual Behavior:

It stays with the default 8080

## Description

**Bug Summary:**
The port does not change when the environment variable `PORT` is set.

## Reproduction Details

**Steps to Reproduce:**
install with pip
`pip install open-webui`
set port variable
`export PORT=8081`
start 
`open-webui serve`

## Logs and Screenshots

```
INFO:     Uvicorn running on http://0.0.0.0:8080 (Press CTRL+C to quit)
$ echo $PORT
8081
```

## Additional Information

I created a blank vm and just installed and set the `PORT` env var. Nothing special.

**Comment by tjbck** [comment]
it's `--port 8081`.

**Comment by kyllan16693** [comment]
Thank you!

Do you think this could be added to `open-webui --help` and the docs website?
