### ISSUE TITLE
PWA orientation is now a mandatory field if you want rotation 

### ISSUE THREAD

**Issue by Rotoslider** [open-webui/open-webui#4870]
On IOS 16 the PWA rotates correctly. On  Android 13 and 14 its stuck in portrait mode. Using latest version of Chrome on both devices. Same issue on both. Researching found that the PWA needs to have orientation  set to any or landscape or whatever you prefer.

**Comment by thiswillbeyourgithub** [comment]
I second this, on my tablet it's very annoying to be stuck in portrait mode and didn't know it was open-webui's fault!

**Comment by Rotoslider** [comment]
i don't think its any ones fault. its just how it is. 
Its something that would be nice to have updated.
I tried changing the orientation to any but it did not make a difference in android 13. maybe it needs to be in the manifest.json to be active.

**Comment by tjbck** [comment]
PR Welcome!

**Comment by imoyy** [comment]
This became a demon when I lay in bed to use it 👿👿

**Comment by imoyy** [comment]
This became a evil when I lay in bed to use it 👿👿
