### ISSUE TITLE
bug: memory reset API endpoint

### ISSUE THREAD

**Issue by phil-ogb** [open-webui/open-webui#4921]
# Bug Report

## Installation Method
N/A - Deployed using a helm chart

## Environment

- **Open WebUI Version:** v0.3.15
- **Operating System:** N/A

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

POST or PUT HTTP method should be used when resetting memories

## Actual Behavior:

GET HTTP method is used to reset memories, which is a stat-changing operation

## Description

**Bug Summary:**
In memory reset endpoint, HTTP GET method is used for a state-changing operation, which resets the collection in ChromaDB, presenting design risks. This practice violates HTTP protocol standards, which specify that GET requests should be used for retrieving data, not modifying server state.

Other concerns include increased vulnerability to Cross-Site Request Forgery (CSRF) attacks and potential for unintended state changes due to caching or bookmarking.

Ideally, state-changing operations should use appropriate HTTP methods like POST, PUT, or DELETE.

Addressing this issue would be helpful

## Reproduction Details

**Steps to Reproduce:**
[Outline the steps to reproduce the bug. Be as detailed as possible.]
1. Ensure memories feature has been enabled for the test user and a memory has been create
2. Make a GET request to `{ORIGIN}/api/v1/memories/reset` in URL bad
3. `true` is returned in the response indicating the operation was successful

## Logs and Screenshots

**Screenshots/Screen Recordings (if applicable):**
![image](https://github.com/user-attachments/assets/ae228520-5da1-4f8b-8e9f-85c1e3344cdb)

**Comment by tjbck** [comment]
Addressed in dev.
