### ISSUE TITLE
Unable to upload epub files do workspace - documents

### ISSUE THREAD

**Issue by correajl** [open-webui/open-webui#4939]
# Bug Report

## Installation Method

docker run --rm -p 3000:8080 --gpus=all -v ollama:/root/.ollama -v open-webui:/app/backend/data --name open-webui ghcr.io/open-webui/open-webui:ollama'

## Environment

- **Open WebUI Version:**  v0.3.15
- **Ollama (if applicable):** 0.3.6

- **Operating System:** Ubuntu server 20.04 LTS
- **Browser (if applicable):** Chrome 127.0.6533.119

## Expected Behavior:

Upload epub files to be used with RAG, for example. I was using that but after upgrade to last release I couln't upload those file anymore. 

## Actual Behavior:

When I try to upload epub files I got the following error:

Something went wrong :/ ********************************************************************** Resource [93mpunkt_tab[0m not found. Please use the NLTK Downloader to obtain the resource: [31m>>> import nltk >>> nltk.download('punkt_tab') [0m For more information see: https://www.nltk.org/data.html Attempted to load [93mtokenizers/punkt_tab/english/[0m Searched in: - '/root/nltk_data' - '/usr/local/nltk_data' - '/usr/local/share/nltk_data' - '/usr/local/lib/nltk_data' - '/usr/share/nltk_data' - '/usr/local/share/nltk_data' - '/usr/lib/nltk_data' - '/usr/local/lib/nltk_data' **********************************************************************

Tried with pdf format and it worked. 

## Description

**Bug Summary:**
Something got wrong when uploading epub files in workspace > documents. 

## Reproduction Details

**Steps to Reproduce:**
Run the docker bundle with open-webui + ollama. Create a new user, log in, go to workspace -> documents. Try to upload a epub file. 

## Logs and Screenshots

Something went wrong :/ ********************************************************************** Resource [93mpunkt_tab[0m not found. Please use the NLTK Downloader to obtain the resource: [31m>>> import nltk >>> nltk.download('punkt_tab') [0m For more information see: https://www.nltk.org/data.html Attempted to load [93mtokenizers/punkt_tab/english/[0m Searched in: - '/root/nltk_data' - '/usr/local/nltk_data' - '/usr/local/share/nltk_data' - '/usr/local/lib/nltk_data' - '/usr/share/nltk_data' - '/usr/local/share/nltk_data' - '/usr/lib/nltk_data' - '/usr/local/lib/nltk_data' **********************************************************************

## Additional Information

I was using a release from some weeks ago and everything was working normally. When I recreate the container with the lastest version I started to get this error.

**Comment by tjbck** [comment]
Should be fixed on dev!
