### ISSUE TITLE
enh: tag filtering

### ISSUE THREAD

**Issue by go-run-jump** [open-webui/open-webui#4959]
**Is your feature request related to a problem? Please describe.**
Currently, users can only include tags when filtering conversations and cannot exclude specific tags from their results, limiting flexibility in viewing relevant conversations.

**Describe the solution you'd like**
Add a tag exclusion option in the filtering system, allowing users to exclude specific tags when filtering conversations, similar to how label filtering works in GitLab and GitHub.

**Describe alternatives you've considered**
- Creating separate tag combinations

**Additional context**
Examples of desired functionality:
- Show all conversations except those tagged with "Archived"
- Display conversations tagged with "Project A" but exclude those also tagged with "Completed"

This feature would greatly improve the ability to focus on specific subsets of conversations by excluding irrelevant tags.

**Comment by tjbck** [comment]
![image](https://github.com/user-attachments/assets/cd6bf05e-2308-4902-9b01-3a1c11b5149b)


Partially implemented with search input refac, closing in favour of #6190
