### ISSUE TITLE
Implement combined tag filtering in Open WebUI

### ISSUE THREAD

**Issue by go-run-jump** [open-webui/open-webui#4960]
**Is your feature request related to a problem? Please describe.**
Users can only filter conversations by single tags and cannot combine multiple tags for more precise filtering, limiting the ability to narrow down searches effectively.

**Describe the solution you'd like**
Implement combined tag filtering, allowing users to select multiple tags when filtering conversations. This should include both AND and OR operations, similar to how labels work in GitLab and GitHub.

**Describe alternatives you've considered**
- Creating new composite tags for common combinations

**Additional context**
Examples of desired functionality:
- Show all conversations tagged with both "Project A" AND "Urgent"
- Display conversations tagged with either "Client X" OR "Client Y"

**Comment by tjbck** [comment]
Closing in favour of #4959, please do not spam our issues page, thanks!
