### ISSUE TITLE
Improve tag selection UI in Open WebUI

### ISSUE THREAD

**Issue by go-run-jump** [open-webui/open-webui#4961]
**Is your feature request related to a problem? Please describe.**
The current UI doesn't clearly indicate which tags are selected when filtering conversations, leading to confusion about the current view.

**Describe the solution you'd like**
Implement a visual indicator (e.g., highlighting, checkmarks, or bold text) to clearly show which tags are currently selected in the filter UI, especially when filters other than "All" are active.

**Describe alternatives you've considered**
- Using a different color scheme for selected tags

**Additional context**
This improvement will enhance the user experience by providing better visual feedback on the current filtering state, reducing potential confusion about applied filters.

**Comment by tjbck** [comment]
Closing in favour of #4959
