### ISSUE TITLE
"Untagged" filter option for conversations in Open WebUI

### ISSUE THREAD

**Issue by go-run-jump** [open-webui/open-webui#4962]
**Is your feature request related to a problem? Please describe.**
Currently, there's no way to filter and view only untagged conversations in Open WebUI. This makes it difficult to manage and organize conversations that haven't been categorized yet.

**Describe the solution you'd like**
Add an "Untagged" filter option that shows only conversations without any tags. This should coexist with the current "All" filter and the ability to filter by specific tags.

**Describe alternatives you've considered**
- Manually scrolling through all conversations to find untagged ones

**Additional context**
This feature would be particularly useful for users who frequently tag their conversations for different workflows or projects. Consider adding a count of untagged conversations next to the filter option for quick reference.

**Comment by tjbck** [comment]
Closing in favour of #4959. Please do not spam.
