### ISSUE TITLE
issue: pip install 0.3.16

### ISSUE THREAD

**Issue by gsm1258** [open-webui/open-webui#4964]
# Bug Report

Running migrations
Error: Can't load plugin: sqlalchemy.dialects:driver

OperationalError: (sqlite3.OperationalError) no such table: config [SQL: SELECT config.id AS config_id, config.data AS config_data, config.version AS config_version, config.created_at AS config_created_at, config.updated_at AS config_updated_at FROM config ORDER BY config.id DESC LIMIT ? OFFSET ?]
[parameters: (1, 0)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)

## Installation Method
pip install open-webui

## Environment

- **Open WebUI Version:**  v0.3.16
- **Ollama (if applicable):**  v0.3.8

- **Operating System:**  Windows 11
- **Browser (if applicable):**  Edge 128.0

**Comment by GitLeandroHub** [comment]
Me also @gsm1258 , exacly same Error. (Windows 10 - Local Machine)

**Comment by Edofin** [comment]
Same issue Windows 11.

**Comment by rofoto** [comment]
same error
```

    938 │   │   cursor.executemany(statement, parameters)                                                             │
│    939 │                                                                                                             │
│    940 │   def do_execute(self, cursor, statement, parameters, context=None):                                        │
│ ❱  941 │   │   cursor.execute(statement, parameters)                                                                 │
│    942 │                                                                                                             │
│    943 │   def do_execute_no_params(self, cursor, statement, context=None):                                          │
│    944 │   │   cursor.execute(statement)                                                                             │
│                                                                                                                      │
│ ╭──────────────────────────────────────────────── locals ────────────────────────────────────────────────╮           │
│ │    context = <sqlalchemy.dialects.sqlite.base.SQLiteExecutionContext object at 0x000001D330189110>     │           │
│ │     cursor = <sqlite3.Cursor object at 0x000001D33081EE40>                                             │           │
│ │ parameters = (1, 0)                                                                                    │           │
│ │       self = <sqlalchemy.dialects.sqlite.pysqlite.SQLiteDialect_pysqlite object at 0x000001D3200C8ED0> │           │
│ │  statement = 'SELECT config.id AS config_id, config.data AS config_data, config.version AS con'+146    │           │
│ ╰────────────────────────────────────────────────────────────────────────────────────────────────────────╯           │
╰──────────────────────────────────────────────────────────────────────────────────────────────────────────────────────╯
OperationalError: (sqlite3.OperationalError) no such table: config
[SQL: SELECT config.id AS config_id, config.data AS config_data, config.version AS config_version, config.created_at AS
config_created_at, config.updated_at AS config_updated_at
FROM config ORDER BY config.id DESC
 LIMIT ? OFFSET ?]
[parameters: (1, 0)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
```

**Comment by vikrantrathore** [comment]
This issue can be fixed by running the alembic migration in the backend. You can do it in following way:

First try create an alembic.ini in the root of open-webui project you have setup, e.g. if you used .venv directory for python virtual environment in your project root the things would look like this.

Create a file named alembic.ini and change the path of migrations an example file is at the end of the comment. If you used python 3.11 or python 3.12 change it accordingly.

After you have created the file follow the following commands:

```
project_root> . .venv/bin/activate 
project_root> export DATA_DIR=<replace_it_with_your_data_directory>
project_root> alembic -c alembic.ini upgrade head

/project_root/.venv/lib/python3.11
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 7e5b5dc7342b, init
INFO  [alembic.runtime.migration] Running upgrade 7e5b5dc7342b -> ca81bd47c050, Add config table
```

Once you see this response the config table is created. Now you can go back to your open_webui project folder and start it and the data will automatically moved from config.json to config table in your database.

Now you can use your upgraded open-webui which will be version 0.3.16. 

One way to fix this is to run alembic upgrade command on the start of the open-webui server.


```
# A generic, single database configuration.

[alembic]
# path to migration scripts
script_location = .venv/lib/python3.11/site-packages/migrations

# template used to generate migration file names; The default value is %%(rev)s_%%(slug)s
# Uncomment the line below if you want the files to be prepended with date and time
# file_template = %%(year)d_%%(month).2d_%%(day).2d_%%(hour).2d%%(minute).2d-%%(rev)s_%%(slug
)s

# sys.path path, will be prepended to sys.path if present.
# defaults to the current working directory.
prepend_sys_path = .

# timezone to use when rendering the date within the migration file
# as well as the filename.
# If specified, requires the python>=3.9 or backports.zoneinfo library.
# Any required deps can installed by adding `alembic[tz]` to the pip requirements
# string value is passed to ZoneInfo()
# leave blank for localtime
# timezone =

# max length of characters to apply to the
# "slug" field
# truncate_slug_length = 40

# set to 'true' to run the environment during
# the 'revision' command, regardless of autogenerate
# revision_environment = false

# set to 'true' to allow .pyc and .pyo files without
# a source .py file to be detected as revisions in the
# versions/ directory
# sourceless = false

# version location specification; This defaults
# to migrations/versions.  When using multiple version
# directories, initial revisions must be specified with --version-path.
# The path separator used here should be the separator specified by "version_path_separator"
below.
# version_locations = %(here)s/bar:%(here)s/bat:migrations/versions

# version path separator; As mentioned above, this is the character used to split
# version_locations. The default within new alembic.ini files is "os", which uses os.pathsep.
# If this key is omitted entirely, it falls back to the legacy behavior of splitting on space
s and/or commas.
# Valid values for version_path_separator are:
#
# version_path_separator = :
# version_path_separator = ;
# version_path_separator = space
version_path_separator = os  # Use os.pathsep. Default configuration used for new projects.

# set to 'true' to search source files recursively
# in each "version_locations" directory
# new in Alembic version 1.10
# recursive_version_locations = false

# the output encoding used when revision files
# are written from script.py.mako
# output_encoding = utf-8

# sqlalchemy.url = REPLACE_WITH_DATABASE_URL


[post_write_hooks]
# post_write_hooks defines scripts or Python functions that are run
# on newly generated revision scripts.  See the documentation for further
# detail and examples

# format using "black" - use the console_scripts runner, against the "black" entrypoint
# hooks = black
# black.type = console_scripts
# black.entrypoint = black
# black.options = -l 79 REVISION_SCRIPT_FILENAME

# lint with attempts to fix using "ruff" - use the exec runner, execute a binary
# hooks = ruff
# ruff.type = exec
# ruff.executable = %(here)s/.venv/bin/ruff
# ruff.options = --fix REVISION_SCRIPT_FILENAME

# Logging configuration
[loggers]
keys = root,sqlalchemy,alembic

[handlers]
keys = console

[formatters]
keys = generic

[logger_root]
level = WARN
handlers = console
qualname =

[logger_sqlalchemy]
level = WARN
handlers =
qualname = sqlalchemy.engine

[logger_alembic]
level = INFO
handlers =
qualname = alembic

[handler_console]
class = StreamHandler
args = (sys.stderr,)
level = NOTSET
formatter = generic

[formatter_generic]
format = %(levelname)-5.5s [%(name)s] %(message)s
datefmt = %H:%M:%S
```

**Comment by hronoas** [comment]
@vikrantrathore 
> project_root> . .venv/bin/activate 
> project_root> export DATA_DIR=<replace_it_with_your_data_directory>
> project_root> alembic -c alembic.ini upgrade head

Thx.
One thing: `alembic -c alembic.ini upgrade head` working only from `venv\Lib\site-packages` path as CWD

**Comment by M4g3dd0** [comment]
I'm using pyenv, in my case I had to find alembic.ini and run open-webui serve in the same directory. 
`find .pyenv/ -name alembic.ini
.pyenv/versions/openwebui/lib/python3.11/site-packages/alembic.ini
cd .pyenv/versions/openwebui/lib/python3.11/site-packages/ 
open-webui serve
`
Upgrade process is initiated right on start, config table gets created, and data from config.json, where settings from connection menu are stored, is transferred into the table.

**Comment by vikrantrathore** [comment]
That should work as well given alembic.ini has directory called migrations
where it will look for migration file and its inside the site-packages.
This can be in virtual environment or in system python or pyenv. DATA_DIR
is only necessary when using Sqlite for database, if using postgresql or
another sqlalchemy databae with URL set in environment variable. This
information is picked up from env.py.

**Comment by gsm1258** [comment]
New issue：
#  conda activate d:\webui-3.16
#  cd D:\webui-3.16\Lib\site-packages
#  open-webui serve

Loading WEBUI_SECRET_KEY from file, not provided as an environment variable.
Generating a new secret key and saving it to D:\webui-3.16\Lib\site-packages\.webui_secret_key
Loading WEBUI_SECRET_KEY from D:\webui-3.16\Lib\site-packages\.webui_secret_key
d:\webui-3.16\Lib
Running migrations
INFO  [alembic.runtime.migration] Context impl SQLiteImpl.
INFO  [alembic.runtime.migration] Will assume non-transactional DDL.
INFO  [alembic.runtime.migration] Running upgrade  -> 7e5b5dc7342b, init
INFO  [alembic.runtime.migration] Running upgrade 7e5b5dc7342b -> ca81bd47c050, Add config table
INFO  [env] 'DEFAULT_LOCALE' loaded from the latest database entry
INFO  [env] 'DEFAULT_PROMPT_SUGGESTIONS' loaded from the latest database entry
WARNI [env]

WARNING: CORS_ALLOW_ORIGIN IS SET TO '*' - NOT RECOMMENDED FOR PRODUCTION DEPLOYMENTS.

INFO  [env] Embedding model set: sentence-transformers/all-MiniLM-L6-v2
INFO  [apps.audio.main] whisper_device_type: cpu
WARNI [langchain_community.utils.user_agent] USER_AGENT environment variable not set, consider setting it to identify your requests.

OSError: [WinError 126] The specified module could not be found. Error loading "D:\webui-3.16\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

**Comment by ANK789** [comment]
pip install open-webui==0.3.15 ,will ok.

**Comment by shadowfaxproject** [comment]
Any resolution on this. Facing the exact same issue on M3-mac. Works fine with 0.3.15

> I'm using pyenv, in my case I had to find alembic.ini and run open-webui serve in the same directory. `find .pyenv/ -name alembic.ini` `.pyenv/versions/openwebui/lib/python3.11/site-packages/alembic.ini` `cd .pyenv/versions/openwebui/lib/python3.11/site-packages/` `open-webui serve` Upgrade process is initiated right on start, config table gets created, and data from config.json, where settings from connection menu are stored, is transferred into the table.

I am facing the exact same problem on M3-mac and this workaround works for now. Will be good to get a permanent solution.

**Comment by M4g3dd0** [comment]
> OSError: [WinError 126] The specified module could not be found. Error loading "D:\webui-3.16\Lib\site-packages\torch\lib\fbgemm.dll" or one of its dependencies.

I'm not running Open-WebUI on windows, so I can not check this myself. I think that you have just to add the dll file to the required folder.

The following link has a solution to similar problem.
https://github.com/Acly/krita-ai-diffusion/issues/965#issuecomment-2254244554

**Comment by sjswerdloff** [comment]
> I'm using pyenv, in my case I had to find alembic.ini and run open-webui serve in the same directory. `find .pyenv/ -name alembic.ini` `.pyenv/versions/openwebui/lib/python3.11/site-packages/alembic.ini` `cd .pyenv/versions/openwebui/lib/python3.11/site-packages/` `open-webui serve` Upgrade process is initiated right on start, config table gets created, and data from config.json, where settings from connection menu are stored, is transferred into the table.

Very helpful!

Once in the proper site-packages I had to activate my virtualenv (py311_llm): 
pyenv activate py311_llm

and then it worked.

**Comment by cantalupo555** [comment]
I have the same problem on Ubuntu LTS.

```
OperationalError: (sqlite3.OperationalError) no such table: config
[SQL: SELECT config.id AS config_id, config.data AS config_data, config.version AS config_version, config.created_at AS config_created_at, config.updated_at AS config_updated_at 
FROM config ORDER BY config.id DESC
 LIMIT ? OFFSET ?]
[parameters: (1, 0)]
(Background on this error at: https://sqlalche.me/e/20/e3q8)
(open-webui-env) root@webui:~# exit
exit

```

**Comment by tjbck** [comment]
Should be fixed with 0.3.17, let me know if the issue persists!

**Comment by shadowfaxproject** [comment]
Tried it with 0.3.18. It works as expected now.

**Comment by ftgreat** [comment]
@gsm1258 麻烦您关注下这个issue，谢谢

https://github.com/gsm1258/1383298/issues/1
