### ISSUE TITLE
Unable to remove image from chat thread/context window

### ISSUE THREAD

**Issue by tkg61** [open-webui/open-webui#4992]
# Bug Report

## Installation Method

Helm in k8s 1.29

## Environment

- **Open WebUI Version:** 0.3.15
- **Ollama (if applicable):** N/A

- **Operating System:** Ubuntu
- **Browser (if applicable):** Chrome

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [X] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [X] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

When a user uploads an image to interact with, they should be able to remove that image, similar to how documents can be removed from a thread, if they want to interact with another image in the same thread.

## Actual Behavior:

When uploading an image it is inserted into the chat but you can not remove it when you go to the three bars in teh top right. For some on-prem LLM solutions you can't have 2 images in the same chat OR you might just want to remove an image from a thread.

## Description

**Bug Summary:**
Unable to remove image from a chat thread

## Reproduction Details

**Steps to Reproduce:**
Upload an image to a thread, try to open the three bar menu on the right to remove it, similar to how documents are removed, and you aren't given an option to do that.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots/Screen Recordings (if applicable):**
![image](https://github.com/user-attachments/assets/228f2f34-c070-416b-8397-15d746b00729)

## Additional Information

To resolve this we have to start a new thread for each image we upload, get a little cluttered :(

## Note

Another nice to have option (not sure if it is worth it) would be to remove the previous image from the context window automatically upon uploading a second image but continue to keep the description of that image for continued use while other images are interacted with

**Comment by silentoplayz** [comment]
That is because the conversation just started. You can not delete the first query you sent to start a chat. If you had just uploaded one more image and asked another question, you would become aware of this. I don't see a bug here.

**Comment by tkg61** [comment]
Ah i see, our problem lies in the fact that if a second image is sent our local backend is unable to process both images and i was hoping to solve that by removing the first image from being sent a second time. 

If i send follow up messages (no more images) or start chatting with the model before sending an image, should that enable me to remove it? Cause i don't see the image appear after trying both of those.

E.g. I said hello first and then asked it about an image and don't see it appear. Since the documents don't exhibit the same behavior i was hoping it would be the same case here: 

![image](https://github.com/user-attachments/assets/e9a7b856-ff7a-42c7-b52e-5413732394eb)

Appreciate the help

**Comment by tkg61** [comment]
So would it be the case that even with chatting with the model before hand that it still doesn't show and would only show upon a second image being sent?

![image](https://github.com/user-attachments/assets/13575ebe-f135-44c2-965a-6f63132803f7)


Appreciate the help

**Comment by silentoplayz** [comment]
> So would it be the case that even with chatting with the model before hand that it still doesn't show and would only show upon a second image being sent?
> 
> ![image](https://private-user-images.githubusercontent.com/3945114/362431918-13575ebe-f135-44c2-965a-6f63132803f7.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NzUyMjgsIm5iZiI6MTcyNDg3NDkyOCwicGF0aCI6Ii8zOTQ1MTE0LzM2MjQzMTkxOC0xMzU3NWViZS1mMTM1LTQ0YzItOTY1YS02ZjYzMTMyODAzZjcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMTk1NTI4WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NWVkNzYwZDZhZmZmZGYwYTE3NmQ2NGJlN2E3MjFkNGJlMDA4NDU0YTM0OTliYzlmNjEzNjgxYmY3NjdmYzQyNSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.keqocBGu2-QKYR055wgAXygyI5g3NBfSW9TTMJSVhWE)
> 
> Appreciate the help

Yes, that is the case. Your first query sent in a chat can not be deleted, no matter if it contains text, text + a document linked for RAG, or text + a document for use with vision models.

**Comment by tkg61** [comment]
Sorry for being a little dense then, So in the pic above, the image is my second query, should i still not be able to delete it then on the right hand menu based on what you just said? Since if i upload a non-picture file it shows up on the side for me to delete after the first query: 

![image](https://github.com/user-attachments/assets/6d239d33-73eb-4834-9ff4-ed57c3094f12)

Was hoping the image to show up under "files"

**Comment by silentoplayz** [comment]
> Sorry for being a little dense then, So in the pic above, the image is my second query, should i still not be able to delete it then on the right hand menu based on what you just said? Since if i upload a non-picture file it shows up on the side for me to delete after the first query:
> 
> ![image](https://private-user-images.githubusercontent.com/3945114/362436810-6d239d33-73eb-4834-9ff4-ed57c3094f12.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjQ4NzYwMzQsIm5iZiI6MTcyNDg3NTczNCwicGF0aCI6Ii8zOTQ1MTE0LzM2MjQzNjgxMC02ZDIzOWQzMy03M2ViLTQ4MzQtOWZmNC1lZDU3YzMwOTRmMTIucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MDgyOCUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDA4MjhUMjAwODU0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NTk5YWI3NzkzMDBhODVlOTcwOThiYTA5ODZiNGZlNTY2NzE4ZTZkODY2M2EzZWJhMTM2ZTNkZTRhNzJkZDlkOSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QmYWN0b3JfaWQ9MCZrZXlfaWQ9MCZyZXBvX2lkPTAifQ.xoWwD1_BEHehOq2MYax4tSCfX_MM2HV8Z8DbAa7VCww)
> 
> Was hoping the image to show up under "files"

Images will not show up within the `Chat Controls` sidebar beneath the `Files` section like you might've been expecting.

A document or a collection of documents will only appear within the `Files` section of the `Chat Controls` sidebar if documents were sent in the chat with a query of yours. The `X` button you circled in red within the `Chat Controls` sidebar is to remove a Document from the chat context, so that you can carry on in the chat without the LLM using your document(s) as ground truth for knowledge.

**Comment by tkg61** [comment]
Would that be a separate feature request then so that we can remove it from the context window? Should i make a new issue for that or can we convert this one?

I'd like to be able to remove a picture without having to start a separate thread altogether for each picture we interact with. We will end up with a lot of chats that need deleting
