### ISSUE TITLE
"Temporary Chat" feature results a pop-up "You do not have permission to access this resource."" error after upgrading to v0.3.16

### ISSUE THREAD

**Issue by ddimarx** [open-webui/open-webui#5009]
# Bug Report

## Installation Method

Docker

## Environment

- **Open WebUI Version:** [v0.3.16]
- **Previous Version: v0.3.15 (where the feature worked correctly)**
- **Operating System:** [Ubuntu 22.04.4 LTS]
- **Browser :** [ Chrome, Firefox, Edge]

**Confirmation:**

- [Y] I have read and followed all the instructions provided in the README.md.
- [Y] I am on the latest version of both Open WebUI and Ollama.
- [N] I have included the browser console logs.
- [Y] I have included the Docker container logs.
- [Y] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

The "Temporary Chat" should accept the question and respond as intended.

## Actual Behavior:

On "Temporary Chat" a pop-up error message appears: "You do not have permission to access this resource." with a "401 Unauthorized" status in the logs.

## Description

**Bug Summary:**

After upgrading to Open-WebUI Docker version v0.3.16, the "Temporary Chat" feature, which was functioning correctly in v0.3.15, results in a pop-up error "You do not have permission to access this resource. Please contact your administrator for assistance." when trying to submit a question, and then the chat/conversation continues without any other issue.

## Reproduction Details

**Steps to Reproduce:**

1. Upgrade Open-WebUI to Docker v0.3.16.
2. Enable "Temporary Chat" feature in the chat/model dropdown settings.
3. Submit a question in the chat interface.
4. Observe the error popup that states "You do not have permission to access this resource. Please contact your administrator for assistance."

## Logs and Screenshots

**Docker Container Logs:**

***
open-webui    | INFO:     xxx.xxx.xxx.xxx:0 - "GET /api/v1/users/user/settings HTTP/1.1" 200 OK
open-webui    | INFO:     xxx.xxx.xxx.xxx:0 - "POST /api/chat/completions HTTP/1.1" 200 OK
open-webui    | INFO:     xxx.xxx.xxx.xxx:0 - "POST /api/chat/completed HTTP/1.1" 200 OK
open-webui    | INFO:     xxx.xxx.xxx.xxx:0 - "POST /api/v1/chats/local HTTP/1.1" 401 Unauthorized
open-webui    | generate_title
open-webui    | gpt-4o-mini
open-webui    | INFO:     xxx.xxx.xxx.xxx:0 - "POST /api/task/title/completions HTTP/1.1" 200 OK
open-webui    | INFO:     xxx.xxx.xxx.xxx:0 - "GET /api/v1/chats/?page=1 HTTP/1.1" 200 OK
***

**Screenshots/Screen Recordings:**

Edge Browser Screenshot:

![image](https://github.com/user-attachments/assets/9ba3f22e-7d9d-4290-9105-c0f161b4071a)

Docker Container Logs Screenshot:

![image](https://github.com/user-attachments/assets/061fbb20-db45-4c97-8153-5f384a12b152)

## Additional Information

This issue began occurring after the upgrade to v0.3.16.
No changes were made to permissions or authentication settings prior to the upgrade

**Comment by silentoplayz** [comment]
Already reported [here](https://github.com/open-webui/open-webui/discussions/4916), although, it has not been fixed on the dev branch yet.
