### ISSUE TITLE
feat: flag to decide whether user can install prompts locally from community

### ISSUE THREAD

**Issue by changchiyou** [open-webui/open-webui#5036]
**Is your feature request related to a problem? Please describe.**
Currently, the only way a user can add a prompt is by contacting an admin to do it, which is very inconvenient.

**Describe the solution you'd like**
Despite the various tools and functions available, prompts do not pose a security issue. Therefore, I believe it is completely fine to allow each user to set their own prompts locally while still retaining the admin’s ability to set prompts globally.

Add a flag `USER_PERMISSION_PROMPTS_INSTALLATION` to determine whether users can access `Workplace.Prompts`, view global prompts, and install prompts locally from the community.

**Describe alternatives you've considered**
Nothing to add.

**Additional context**
Nothing to add.

**Comment by tjbck** [comment]
#2924, Please check for duplicates.
