### ISSUE TITLE
Feature Req: Web Search URL shortcut

### ISSUE THREAD

**Issue by mr-gepardas** [open-webui/open-webui#5046]
**Is your feature request related to a problem? Please describe.**
Browser Search Engine Integration is quite a neat feature, especially since can have additional parameters like model and if it is a private chat (not to be saved). Would also be very useful if it was possible to add another parameter if Web Search should be enabled. This way could have a web search done and LLM summarise the results, which then you could continue questioning. 

**Describe the solution you'd like**
Additional URL parameter like "web-search=true", to force the chat to have web search enabled on the very first response. Would also be useful if the web search RAG would then appear in the chat, just like if user uploaded a file or used "#" for the website.

**Comment by tjbck** [comment]
Added to dev!
