### ISSUE TITLE
Tagging existing documents in batch.

### ISSUE THREAD

**Issue by LumenYoung** [open-webui/open-webui#5062]
**Is your feature request related to a problem? Please describe.**

Currently the documents that has been uploaded doesn't have a efficient way to add tag in batch. You have to add tag for each individual document. This means that trying to add new tags to group existing documents is extremely manual , time consuming and repetitive. 

Since there could be many cases you want to query a group of documents, and therefore you want to add tag to multiple documents so that you can use `#` to query them all, tagging is a very frequently used action therefore deserve better interface for efficient editing.

**Describe the solution you'd like**

Since there is already the multi selection and you can delete documents when multiple files are selected, it would be straight forward if we can add an additional button "add tag" when in multi-selection and allow to add multiple tags in the pop up window.

**Describe alternatives you've considered**

**Additional context**

**Comment by tjbck** [comment]
#3527
