### ISSUE TITLE
Mermaid syntax error when clicking on review response buttons

### ISSUE THREAD

**Issue by DadiAnas** [open-webui/open-webui#5078]
# Bug Report

## Installation Method

Docker image ghcr.io/open-webui/open-webui:cuda

## Environment

- **Open WebUI Version:** v0.3.16
- **Ollama (if applicable):** 0.3.8

- **Operating System:** all
- **Browser (if applicable):** Firefox/Chrome

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [] I have included the Docker container logs (no errors).
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Give my review regarding the response

## Actual Behavior:

Many mermaid syntax error appeared in the bottom of the page. 

## Description

**Bug Summary:**
Mermaid syntax error appeared in the bottom of the page after clicking on like or unlike review button while I asked before for mermaid diagram in my conversation (the geAI replied with syntax error diagram)

## Reproduction Details

**Steps to Reproduce:**
Ask for mermaid diagram with syntax error -> try to give a review on the genAI reply

## Logs and Screenshots

![image](https://github.com/user-attachments/assets/a06e8153-c420-4115-922a-7bc16e771f8a)

**Browser Console Logs:**

This is related to diagram syntax error in the console, that resolved after asking to remove it,  but it is not the main issue:
Uncaught (in promise) 
Object { str: `Parse error on line 54:\n...FA07AclassDiagram C9E4CA, "Compute Ser\n---------------------^\nExpecting 'SEMI', 'NEWLINE', 'EOF', 'AMP', 'START_LINK', 'LINK', got 'NODE_STRING'`, message: `Parse error on line 54:\n...FA07AclassDiagram C9E4CA, "Compute Ser\n---------------------^\nExpecting 'SEMI', 'NEWLINE', 'EOF', 'AMP', 'START_LINK', 'LINK', got 'NODE_STRING'`, hash: "Error", error: Error }
2

**Comment by tjbck** [comment]
Fixed on dev!
