### ISSUE TITLE
FR: copy whole chat into clipboard

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [open-webui/open-webui#5081]
**Is your feature request related to a problem? Please describe.**
There's a button to copy a message into clipboard but noway to copy several message or even the whole chat.

**Describe the solution you'd like**
In the "controls" button in the top right corner, add a button to copy the whole chat.

**Describe alternatives you've considered**
Manually copying each message.

**Additional context**
It's the only way to share a chat with someone who hasn't an account.

**Comment by silentoplayz** [comment]
It's currently possible to download a chat in the formats .json, .txt, or .pdf, allowing you to easily share the chat with others if desired.
![image](https://github.com/user-attachments/assets/865f27b9-524b-4102-963e-518ad6a6b75e)

**Comment by silentoplayz** [comment]
Initially, I was on the fence about the suggestion, but after having done more thinking about it, I'm not opposed to a 'Copy whole chat' feature, but I think it's a low-priority issue for now. If someone wants to PR a simple 'Copy whole chat to clipboard' option within the `Share` menu for a chat, that would be great. The current `Share` option would need modified so that `Share Chat Link` is an option, as well as `Copy Whole Chat` or something along the lines of this that lets the user know that the entire conversation will be copied to their device's clipboard.

**Comment by Lanhild** [comment]
@thiswillbeyourgithub Thanks for the feature request.

Though, I feel like this isn't necessary as the action to export a chat isn't all that complex.

The advantage of the export actions is that they all (at least, PDF and JSON) present you with a structured data;

- The PDF export is essentially a copy of what you'd see on screen
- The JSON export leverages the features of the format

I feel like going out of my way to copy the entire conversation to my clipboard, and then send it to someone else (be it by email or text messages) is useless.

It's altogether easier and more convenient for both parties to simply send the file export.

**Comment by thiswillbeyourgithub** [comment]
Thank you for taking the time. In my case it surely is not a gain of time to have to deal with a text files instead of text directly. Here are a couple of situations that happen multiple times per week for me:

- I learn a lot of stuff via LLM, a lot of it is then manually distilled and stored into [anki flashcards](https://apps.ankiweb.net/) and because it is long term, I absolutely want to store the source. In my case, what's least disrupting of my workflow is via simply pasting the chats. If I sent the file it would not be searchable via anki, including via any of my software I made to index my contents.
- Often people ask me stuff, and before answering I like to double check with LLMs for a more thorough answer, examples etc. I then send my reply along with the whole chat as a clipboard. **This is my main way to convince people of the amazing power LLM bring so it's a high value situation to my eyes**. Sending a file would increase the friction for the sender (me) but also for the receiver. This friction is present both on mobile and on computer.
- Every time I want to send a chat to a friend via a messaging app on my phone. All device handle inline text but if you send an actual txt, aside from the friction for both users, you also depend on if the receiver has an appropriate app to read it (not trivial for non power users!).


> I feel like going out of my way to copy the entire conversation to my clipboard, and then send it to someone else (be it by email or text messages) is useless.

Either I misunderstood or this seems like circular reasoning :thinking: . Of course *going out of your way to copy the conversation* is useless compared to an alternative that fits you. But my point is that I have to go out of my way too currently because the UI only allows your use case and not mine. The whole purpose of this thread is to not have neither your nor I having to got out of anyone's way: simply click on the appropriate button at the time. *Note: I don't have the energy right now to figure out why but it seems my message can be perceived as mean or sarcastic but I promise it's not!*

Now that I think of it, why would open-webui even have a very accessible UI button to copy a single message in the first place? There's got to be *value* for people to be able to get quickly the text of a message right? Then I'm just among the people that need that but for multiple messages in a row basically.

Have a nice day!

**Comment by Lanhild** [comment]
Thanks for your reply and enlightening me on the potential use cases.

It makes more sense now as to why someone would want this feature.

Thank you for the suggestion, they're always welcome.

**Comment by thiswillbeyourgithub** [comment]
Glad I wasn't a d*** :)

Also new example that comes to mind is the new release of the model called Reflection70B. I actually took the habit of copying and pasting previous LLM chats to have a sort of second opinion from Reflection70b, and it's been extremely interesting.

**Comment by Lanhild** [comment]
> Also new example that comes to mind is the new release of the model called Reflection70B. I actually took the habit of copying and pasting previous LLM chats to have a sort of second opinion from Reflection70b, and it's been extremely interesting.


Is this a model you use in Open WebUI? If so, you could simply edit your query, change model and simply save it to resend as-is. (Depends what's the behavior you expect, but that's what I do)

I could post a simple recording as an example if necessary.

**Comment by thiswillbeyourgithub** [comment]
Yes it's in openwebui but no I don't want to do that. It's not the same for an LLM to judge a text than to judge it's own prejous assistant message. Maybe the performance difference is minimal but I'd like to avoid that unknown anyway

**Comment by tjbck** [comment]
Added to dev!
