### ISSUE TITLE
Temperature In “Advanced Parameters” Is Not Being Applied To Chat

### ISSUE THREAD

**Issue by HaloGamer33** [open-webui/open-webui#5090]
# Bug Report

## Installation Method

Installed via docker with the command `docker run -d -p 3000:8080 --gpus all --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:cuda`

## Environment

- **Open WebUI Version:** v0.3.16
- **Ollama (if applicable):** 0.3.9

- **Operating System:** Windows 11
- **Browser (if applicable):** Brave v1.69.160

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Temperature defined within "Advanced Settings" being applied to the chats.

## Actual Behavior:

Temperature defined within "Advanced Settings" is not being applied to the chats.

## Description

**Bug Summary:**
When using the temperature slider in "Advanced Settings" to apply a temperature to new chats it does not apply it.

## Reproduction Details

**Steps to Reproduce:**
1. Set temperature in "Advanced Settings"
2. Create a new chat with a defined seed for recreation purposes (seed defined from "Chat Controls")
3. Ask something, for example: "Could you explain the MessagePack-RPC protocol?"
4. Note how the answer, regardless of the temperature defined in "Advanced Settings", is the same as if the temperature was the default 0.8

## Logs and Screenshots

**Browser Console Logs:**
Not relevant

**Docker Container Logs:**
Not relevant

**Screenshots/Screen Recordings (if applicable):**

### Temperature Defined in Advanced Settings:
![image](https://github.com/user-attachments/assets/f4f81fd3-bbf7-443e-bfb8-5e5d71cbb2c0)

### Chat With Defined Seed and Temperature Defined Through "Advanced Settings"
![image](https://github.com/user-attachments/assets/bd54fcf9-02d3-499b-b132-373d7cb1d91f)

### Chat With Defined Seed and Temperature 0.8:
![image](https://github.com/user-attachments/assets/44eb60ce-bdea-4bc2-b2c6-587cc46acb37)

### Chat With Defined Seed and Temperature 0.1:
![image](https://github.com/user-attachments/assets/40786fa6-1f00-4a6c-9b6d-102436e69f4d)

### JSON POST request to the server without a defined temperature (temperature defined in "Advanced Settings"):
![image](https://github.com/user-attachments/assets/5ed54334-53b3-4476-851d-9bdcf66eb86c)

### JSON POST request to the server with a defined temperature (defined from "Chat Controls"):
![image](https://github.com/user-attachments/assets/becb760d-14b8-4611-9ca5-25fb55d36e89)

## Additional Information

None

**Comment by tjbck** [comment]
Good catch, fixed on dev!

**Comment by Kamology** [comment]
Sorry I'm kind of new to Github but this still hasn't been fixed in live yet right? There's been quite a few updates since it was apparently fixed in dev so just wanted to make sure it wasn't forgotten or something. The issue persists for me on latest version 0.3.30

**Comment by HaloGamer33** [comment]
It's fixed on the dev branch, I don't know if the fixed has been implemented into other branches, this is how you use the dev branch with docker (extracted from the README.md):

### Using the Dev Branch 🌙

> [!WARNING]
> The `:dev` branch contains the latest unstable features and changes. Use it at your own risk as it may have bugs or incomplete features.

If you want to try out the latest bleeding-edge features and are okay with occasional instability, you can use the `:dev` tag like this:

```bash
docker run -d -p 3000:8080 -v open-webui:/app/backend/data --name open-webui --add-host=host.docker.internal:host-gateway --restart always ghcr.io/open-webui/open-webui:dev
```

**Comment by MikitaPetukhou** [comment]
Hi @Kamryx,
I am facing the same issue and can not figure out whether it was fixed...
Have you managed to find the version where the fix was applied?

**Comment by HideLord** [comment]
Yeah, noticed the same issue as well.

**Comment by Kamryx** [comment]
It still hasn’t been fixed as far as I’m aware. I’m kind of a noob to this stuff but I think at the top of this page the “tasks” thing needs to show completed instead of 3/5. 

Again, idk enough to speak on this really but it is pretty head scratching that it hasn’t been fixed yet. That’s like the main setting most people adjust and last time I was here it was apparently already fixed in the dev build, they just haven’t pushed it to main? Not sure

**Comment by tjbck** [comment]
![image](https://github.com/user-attachments/assets/749176f1-e5eb-4db2-b876-1fbf672d2e56)
![image](https://github.com/user-attachments/assets/717a33da-2cc3-4f3c-a1dd-dd07177bfa69)

It's been fixed and merged to main a long time ago, otherwise this issue wouldn't be closed. You can test it for yourself.

**Comment by MikitaPetukhou** [comment]
Hi @tjbck,

Thanks a lot for the confirmation!
I am on version 0.4.8.

Seems I had some difficulties to see it, or I am trying to view it somehow incorrectly.
I have configured the temperature from Admin panel on Model level. Also the model was assigned with a UserGroup who should have access to it.
<img width="1183" alt="image" src="https://github.com/user-attachments/assets/ce6fc09e-a188-436c-bc58-8fb3e4417a48" />


- This is what I see from a non-admin user
![image](https://github.com/user-attachments/assets/d937fae8-4163-4f8a-b38c-90f36845251d)
I don't see info about the temperature

- This is what I see from Admin user session
![image](https://github.com/user-attachments/assets/eaa1fab5-a21d-480e-b01c-86d49dd7e9e7)

You are right, I do see the temperature parameter from here.
I don't understand why I see value 0.45, while in database it is 0.4... 0.45 was my previous values that I have tested..but it is another question

**Comment by rhajou** [comment]
Hello, I am using the latest version of open-webui and still facing a similar issue.

If the user general temperature is put to 0.2, in the chat controls the **default** temperature will be shown as 0.8 which is false. Of course if I change it to 0.3 it will work. 
Any idea how to inherit the set up temperature in the General settings of the user into the chat controls?


Same issue if we set up the model temperature, it does not reflect in the default value in the chat. and I think it should be disabled to the user the possibility of changing the temperature according to the priority put by openwebui
