### ISSUE TITLE
feat: Allow selecting default model on mobile

### ISSUE THREAD

**Issue by crizCraig** [open-webui/open-webui#5114]
**Is your feature request related to a problem? Please describe.**
Can't select default model on mobile

**Describe the solution you'd like**
Ability to set default on mobile

**Describe alternatives you've considered**
You can set it on desktop and it will transfer to mobile

**Additional context**
Looks like you can set it on tablets, but not mobile resolutions
![image](https://github.com/user-attachments/assets/6ee929c0-3d5b-48e7-8c7a-a4823662c691)
![Google Chrome 2024-09-02 13 51 28](https://github.com/user-attachments/assets/8c78bfd2-fbca-480b-b5c7-f07ba7d01130)

**Comment by tjbck** [comment]
You can already select default model from settings.
