### ISSUE TITLE
enh: add search bar to document selection in model editor

### ISSUE THREAD

**Issue by JTHesse** [open-webui/open-webui#5170]
**Is your feature request related to a problem? Please describe.**
For a large set of documents, the search for a specific document is very tedious. Currently, the user needs to scroll through the whole list to find a document.

**Describe the solution you'd like**
The dropdown of the document selector in the knowledge section should contain a search bar for filtering documents. 

**Describe alternatives you've considered**
A search component seams to be the best solution.

**Additional context**
![search](https://github.com/user-attachments/assets/90cd4285-966f-447d-8ad8-24dfb9a5c90f)

**Comment by tjbck** [comment]
Added to dev!
