### ISSUE TITLE
Incorrect view of wide tables (Frontend)

### ISSUE THREAD

**Issue by treepoint** [open-webui/open-webui#5201]
# Bug Report

## Installation Method
Docker Desktop
## Environment
- **Open WebUI Version:**  v0.3.19 with CUDA
- **Ollama:** 3.1 8B

- **Operating System:** Windows 10
- **Browser (if applicable):** Edge 128.0.2739.54

**Confirmation:**
- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [-] I have included the browser console logs (i can't, there is sensitive info).
- [-] I have included the Docker container logs (i can't, there is sensitive info).
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:
When i get really wide table in response, it has a scroll and head/content not become unreadable.

## Actual Behavior:
Table are trying to fit in only working area, which is about 930px, and all data and header become vertical alignment columns of unreadable letters.

## Description
I use OWUI with custom function to connect to PostgresDB to write and execute SQL query. Some of data stored in tables with 20+ columns, and when i get response as a table it can't fit in propeply. My temporary fix:

1. Set property «overflow: auto;» to CSS class «chat-assistant».
2. Set property «width: max-content;» to CSS class «chat-assistant.table».

Then table can use all needed space and response become scrollable.

## Reproduction Details

**Steps to Reproduce:**

1. Ask LLM «Give me example of table with 10 columns and 5 rows».
2. You will get generic example without problems.
4. Edit response to make table with 20 columns of just edit some columns name to make table wider.
5. See the problem.

Also, you _need to_ edit table by yourself, cause it can't response with wider tables in correct way, it compose wider table in 2 rows which not a table, but mess too. Maybe LLM know smth.

## Logs and Screenshots
Before fixes:
![before](https://github.com/user-attachments/assets/b99dff15-0edd-44ef-8598-2b919d936a5b)

After:
![after](https://github.com/user-attachments/assets/1cdb8eef-2770-41fb-9e08-66a045dec499)

**Comment by tjbck** [comment]
PR Welcome!

**Comment by tjbck** [comment]
Fixed on dev!
