### ISSUE TITLE
URL parameter for prompt

### ISSUE THREAD

**Issue by kekosaurusrexx** [open-webui/open-webui#5214]
**Is your feature request related to a problem? Please describe.**
When using a browser shortcut, like in the Arc Browser, you could directly openwebui with a prompt, if you could pass this prompt trough the url

**Describe the solution you'd like**
Having a url parameter that can open the page with a prompt and instantly start generation
For example ?prompt=text

**Describe alternatives you've considered**
I did not find anything in the documentation or issues

**Comment by tjbck** [comment]
We already have this with `/?q=`

**Comment by sbhal** [comment]
This doesn't seem to be working. If prompt is defined as `/analyze-tweet`, both `/?q=anayze-tweet` and `/?q=%2Fanayze-tweet` doesn't seem to be working.
