### ISSUE TITLE
markdown images not getting rendered

### ISSUE THREAD

**Issue by shadowfaxproject** [open-webui/open-webui#5231]
# Bug Report

## Installation Method

pip install.

## Environment

- **Open WebUI Version:** 0.3.19, 0.3.18 ... 0.3.10 (tested with these)
- **Ollama (if applicable):** 0.3.9 (FYI)

- **Operating System:** MacOS on M3 Mac
- **Browser (if applicable):** Chrome Version 128.0.6613.120 (Official Build) (arm64), Safari Version 17.1 (19616.2.9.11.7)

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [x] I have included the Docker container logs (NA)
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:
When following markdown is provided as input to chat, it's expected to display the favicon.png icon twice (one with link enabled, other just an image):
```
Hello! It's nice to meet you. Is there something I can help you with or would you like to chat? 
[![Test](/favicon.png)](https://google.com) 
![Test](/favicon.png)
```

## Actual Behavior:
open_webui version 0.3.10: it behaves as expected. (screenshot attached)

[Describe what actually happened.]
open_webui version 0.3.11 onward, the first image does not get rendered. Instead it shows the link-text. The second image gets rendered. Tested and found the behavior for 0.3.12, 0.3.18, 0.3.19

## Description

**Bug Summary:**
Broken markdown rendering 

## Reproduction Details
**Steps to Reproduce actual behavior (0.3.19):**
1. Make sure Ollama is running in the background with some standard model like 'llama2:latest' for testing.
2. pip install open_webui `pip install open-webui`
3. Run open_webui server `open-webui serve`
4. Open [0.0.0.0:8080](http://0.0.0.0:8080/) in browser
5. Signup if not already or sign-in using existing username/passwd.
6. Select 'llama2:latest' from *Select a model* menu on the upper-left corner.
7. Input message 'Hi'
8. When the model response comes back, use the *edit* icon to modify the message and add following lines to it:
```
[![Test](/favicon.png)](https://google.com) 
![Test](/favicon.png)
```
9. *Save* the edited message to see the final rendering.

**Steps to Reproduce desired behavior (0.3.10):** 
Exact same steps. Just make sure you are working with *open_webui 0.3.10*

## Logs and Screenshots
Desired Behavior
<img width="300" alt="Screenshot 2024-08-30 at 11 21 28 PM" src="https://github.com/user-attachments/assets/a9d7d336-c65c-42db-84f7-ddd59d537c34">

Actual behavior
<img width="300" alt="Screenshot 2024-08-30 at 11 25 31 PM" src="https://github.com/user-attachments/assets/12124b91-d3af-4fb6-8d24-291c56c975af">

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots/Screen Recordings (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
Fixed on dev.

**Comment by shadowfaxproject** [comment]
Thanks for jumping on to this so quickly. Tested this with dev. It is able to display both images now which is great.

There is still a behavior not identical to 0.3.10. When you click on the first image (that links to google.com), it opens that link in a new tab (as expected). But in the original window it also expands and shows the image in full-screen (not what I was expected or experienced). Attached is a screenshot.
<img width="300" alt="Screenshot 2024-09-06 at 4 37 33 PM" src="https://github.com/user-attachments/assets/96166533-223e-49ac-b41c-e4778745e9c2">
