### ISSUE TITLE
Add support for the new Ollama /api/embed api endpoint

### ISSUE THREAD

**Issue by geekbozu** [open-webui/open-webui#5239]
**Is your feature request related to a problem? Please describe.**
Ollama added a newer endpoint for embeddings /api/embed. 
OpenWebUI does not expose this on its API proxy. 

**Describe the solution you'd like**
OpenWebUI proxies this endpoint as it does with other Ollama Endpoints. 

**Describe alternatives you've considered**
We can always talk to ollama directly but doing that defeats the purpose of having OpenWebUI be in the middle!

**Additional context**
New endpoint documentation from Ollama 
https://github.com/ollama/ollama/blob/main/docs/api.md#generate-embeddings

Deprecated endpoint 
https://github.com/ollama/ollama/blob/main/docs/api.md#generate-embeddings

**Comment by tjbck** [comment]
Added to latest main!

**Comment by geekbozu** [comment]
Thanks for getting to this so fast!
Sadly there is a signature difference between /api/embed and /api/embeddings. 
The body field that the data to generate embedding for has changed. 

`/api/embed/` expects `body` or `input`. 
/api/embeddings` expects `prompt`.

The way this was implemented will cause a regression on anyone expecting the older behavior (with `prompt` body) to still work!

**Comment by vills** [comment]
@tjbck as i can see there is already a pull request to support Ollama's batch processing endpoint. Could you look at it please? https://github.com/open-webui/open-webui/pull/4715
