### ISSUE TITLE
enh: chat overview general enhancements

### ISSUE THREAD

**Issue by go-run-jump** [open-webui/open-webui#5254]
**Is your feature request related to a problem? Please describe.**
When revisiting a conversation in Open WebUI that has multiple branches due to regenerations or changed prompts, only the last iteration or prompt is directly visible and obvious. This makes it difficult to keep track of preferred conversation paths.
Having little side conversations along a topic is very nice, but it makes it very difficult to get back to where the main thread was afterwards. 

**Describe the solution you'd like**
Implement a feature that allows users to mark their favorite paths in the conversation tree. At each node where there are multiple options (due to regenerations or changed prompts), users should be able to designate a favorite. When revisiting the conversation or a subtree within, the marked favorite path would be displayed by default.

**Describe alternatives you've considered**
- Enabling the deletion of parts of a conversation tree (this would actually be nice when added additionally).
- Displaying all branches simultaneously, which might be overwhelming for complex conversations.
- Starting a new chat with each regeneration or prompt change.  With this we would lose the context.

**This feature would be particularly useful for:**
- Researchers and writers who explore multiple conversation paths and want to keep track of the most promising ones.
- Users who frequently revisit conversations and need quick access to the most relevant information.
- Improving the overall user experience by allowing more control over how conversation histories are displayed and navigated.

**Comment by Alino** [comment]
Something like this is what's on my mind last 2 days. Some kind of tree of thought view support. A mind map is a good representation for that. And I just found this thread on librechat repo -> https://github.com/danny-avila/LibreChat/discussions/1655

**Comment by tjbck** [comment]
<img width="805" alt="image" src="https://github.com/user-attachments/assets/15b3c723-9103-4907-9b93-00cfa4ab430f">


Added a feature enabling users to indicate favourite response from the Chat Overview, available now in dev!
