### ISSUE TITLE
open-webui stopped working

### ISSUE THREAD

**Issue by AxelFooley** [open-webui/open-webui#5259]
# Bug Report
chat is not working anymore, doesn't matter which model i choose, the ui just hangs waiting forever and in browser console i see the polling going on without any result:

+layout.svelte:89 usage {models: Array(1)}
+layout.svelte:89 usage {models: Array(1)}
+layout.svelte:89 usage {models: Array(1)}

Connection to ollama works fine, i can pull new models, i can force a recheck of all manifests, i can push to ollama new GGUF models, just the chat is not working anymore.

Nothing in container logs as well:

open-webui-1  | INFO:     10.0.110.139:0 - "POST /api/v1/chats/new HTTP/1.1" 200 OK
open-webui-1  | INFO:     10.0.110.139:0 - "GET /api/v1/chats/?page=1 HTTP/1.1" 200 OK
open-webui-1  | INFO:     10.0.110.139:0 - "POST /api/v1/memories/query HTTP/1.1" 200 OK

## Installation Method

docker

## Environment

- **Open WebUI Version:** latest docker image
- **Ollama (if applicable):** latest windows version

- **Operating System:** open-webui: linux, ollama: windows
- **Browser (if applicable):**Brave

**Confirmation:**

- [x ] I have read and followed all the instructions provided in the README.md.
- [ x] I am on the latest version of both Open WebUI and Ollama.
- [ x] I have included the browser console logs.
- [ x] I have included the Docker container logs.
- [ x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

I can actually use chat
## Actual Behavior:

Never getting a response

## Description

**Bug Summary:**
[Provide a brief but clear summary of the bug]

## Reproduction Details

**Steps to Reproduce:**
[Outline the steps to reproduce the bug. Be as detailed as possible.]

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots/Screen Recordings (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by AxelFooley** [comment]
Forgot to mention, ollama is of course working, it is configured to be reachable by hosts in my lan and i can use all models via ollama shell.

**Comment by tjbck** [comment]
Duplicate #5257
