### ISSUE TITLE
feat: cancel model download

### ISSUE THREAD

**Issue by hemangjoshi37a** [open-webui/open-webui#526]
I want to have a stop download button at the end of the progressbar in the model download setting . thanks

**Comment by bhulston** [comment]
Will do this one!

**Comment by anuraagdjain** [comment]
<img width="482" alt="image" src="https://github.com/open-webui/open-webui/assets/4705103/c1852f33-1ba2-4d71-b380-a950aa1db8c8">

I have this on my local, lmk if I should push this. I can refactor and push it next week.

**Comment by hemangjoshi37a** [comment]
> <img width="482" alt="image" src="https://github.com/open-webui/open-webui/assets/4705103/c1852f33-1ba2-4d71-b380-a950aa1db8c8">
> 
> I have this on my local, lmk if I should push this. I can refactor and push it next week.

It is good but there should be a square ⬛ shaped stop button instead of delete button as a symbol. Otherwise you are on the right track. Baki Bhai mereko Finland ana he kuch setting karvao na. Me industrial automation engineer hu aur apna business as hjLabs.in chalata hu.
