### ISSUE TITLE
feat: Allow line breaks within Default Prompt Suggestions

### ISSUE THREAD

**Issue by GrayXu** [open-webui/open-webui#5264]
**Is your feature request related to a problem? Please describe.**

It is currently not possible to input multi-line prompts in Default Prompt Suggestions, and some models are sensitive to this difference, which affects the final result.

**Describe the solution you'd like**

Simply allow input of line breaks, to avoid disrupting the UI, you can, for example, only display the last 3 lines on the layout.

**Comment by tjbck** [comment]
Added to dev!
