### ISSUE TITLE
frontend only

### ISSUE THREAD

**Issue by firashacker** [open-webui/open-webui#5278]
i install ollama on my machine and i don't like the extra dependencies and space this project require like docker , i will prefer having a simple npm package that i can just use to connect to my local ollama server

**Comment by justinh-rahb** [comment]
https://github.com/ollama-webui/ollama-webui-lite

**Comment by firashacker** [comment]
but it says no longer maintained and u tried using it from different clients than the host it doesn't work and it's missing most of the features!!!!!

**Comment by silentoplayz** [comment]
https://github.com/ollama-webui/ollama-webui-lite/pull/31

**Comment by kroonen** [comment]
I'll provide extended support at openwebui.org
