### ISSUE TITLE
ENH: Azure TTS support

### ISSUE THREAD

**Issue by bergutman** [open-webui/open-webui#5288]
**Is your feature request related to a problem? Please describe.**
Current supported TTS engines (OpenAI & ElevenLabs) are quite expensive. [Azure gives away 1/2 million free characters per month](https://azure.microsoft.com/en-us/pricing/details/cognitive-services/speech-services/). I know that custom TTS support is on the timeline but just wanted to state that (personally) Azure integration is at the top of my feature request list. Thank you for the amazing software!

**Describe the solution you'd like**
Native Azure support for TTS.

**Describe alternatives you've considered**
Fully platform/API agnostic TTS support and integration.

**Comment by tjbck** [comment]
PR Welcome!
