### ISSUE TITLE
feat: collections/docs for modelfiles with models

### ISSUE THREAD

**Issue by racso-dev** [open-webui/open-webui#529]
**Is your feature request related to a problem? Please describe.**
It's frustrating having to mention documents manually every time.

**Describe the solution you'd like**
It would be nice to have a RAG integration inside the Modelfiles definition.
OpenAI and their GPTs allow users to activate RAG and upload documents upon creation of a new GPT.
It would be really amazing to have such a feature ;)

**Comment by JasonPad19** [comment]
yes, looking at GenAI stack from docker,neo4j.

I am looking for a way to integrate a neo4j knowledge graph which has structured data and RAG pdf chunk data.

**Comment by racso-dev** [comment]
Any plans on that feature?

**Comment by MarlNox** [comment]
What's the approach? I'm also very interested in this feature. If there's a roadmap, id be glad to help realize it.

**Comment by tjbck** [comment]
Blockers: #665

**Comment by pspeskoett** [comment]
This is really what is missing right now to make the assistent setup really great

**Comment by flefevre** [comment]
How can I help? Is there any test to perform?

**Comment by racso-dev** [comment]
Any news on that?

**Comment by tjbck** [comment]
I'll prioritise this feature for v0.4.0!

**Comment by flefevre** [comment]
Hello Timothy,
That will be great but I think it should be associated with

-Enabling multi workspaces
-A workspace could have its own models, documents ,prompts.
-A workspace should be associated with its own embedded vector database base
-a workspace could be accessed by a group of users, thanks to the creator
and the managers of a workspace.


Hope we could discuss about these features.

And once again, 'BRAVO' for your project.

François, from France

**Comment by tjbck** [comment]
Implemented on dev!
![image](https://github.com/open-webui/open-webui/assets/25473318/50130791-5558-437b-b832-7f7fd3f5a816)

**Comment by Derekt2** [comment]
has anyone successfully used this? I can't get the responses to include data from the collection and it doesn't cite the sources either. Is there any documentation on this feature?

**Comment by amrsa1** [comment]
I have attached very basic pdf and link it to relevant model llma 3.2 8b and adjust the emeddings model to nomic.

And for some reasons lllm in unable to give relevant answers ??

Am i missing anything ?
