### ISSUE TITLE
Advanced Params are not honored or logged correctly

### ISSUE THREAD

**Issue by tkg61** [open-webui/open-webui#5321]
# Bug Report

## Installation Method

Helm 0.3.21

Using openai compatible endpoint (not ollama)

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

1. When Advanced params are updated for a model under workspace, all the modified params will be logged 
2. When Advanced params are overridden in the chat controls in a particular thread they will work (overriding the workspace params) and they will also be logged correctly 

## Actual Behavior:

1. Advanced params set in the workspace are not all logged correctly (top_k or min_p are not logged)
2. Advanced params modified in the chat controls do NOT override the workspace advanced params and also do not log correctly (top_k, min_p)

## Description

**Bug Summary:**

Advanced params are not logged all the time and overriding them in the chat thread does not work. 
This means i don't know if the setting (e.g. top_k) is actually honored and being sent correctly to the backend AND i can't give users the ability to modify things to their liking

## Reproduction Details

**Steps to Reproduce:**

My situation today was needing to modify the defaults of LLAMA3-70b to Top_k = 10, Temp=0.7, Top_P=1

When i went to the logs to check if it had worked i saw that only Temp and Top_P were logged 

In my chat thread advanced params i: 
- Modified all three items again to be the same as the workspace settings above, still didn't log Top_k
- Modified all three items to be something different than the workspace settings above, still didn't log Top_K AND still logged temp=.7 and top_p=1 even though i had changed them 
- Modified 2 other Advanced params in the chat controls just to see if it was more than these 3: 
  - Modified Min_P and it didn't log 
  - Modified Frequency Penalty and it did log  
  - Modified Batch size and it didn't log
  - Modified context length and it didn't log

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**

**Screenshots/Screen Recordings (if applicable):**

Here is a screenshot of the workspace params: 

![image](https://github.com/user-attachments/assets/eea156fb-00fb-4ee9-8c4b-02d9467b9b72)

Here is a screenshot of the advanced params being modified after the workspace params have been modified: 

![image](https://github.com/user-attachments/assets/0f840f10-db79-479d-b6c0-eaf141cd88ef)

here is the cooresponding log of the request that was sent 

```
[open_webui.apps.openai.main] {"stream": true, "model": "meta-llama/Meta-Llama-3-70B-Instruct", "messages": [{"role": "user", "content": "tell me a short story"}, {"role": "assistant", "content": "Here is a short story:\n\nThe Old Piano\n\nEmma had always been fascinated by the old piano that sat silently in the corner of her grandmother's attic. As a child, she would sneak up to the attic and run her fingers over the yellowed keys, imagining the stories it could tell.\n\nYears went by, and Emma grew up. She moved away from home and started a family of her own. But when her grandmother passed away, Emma returned to the old house to sort through her belongings.\n\nAs she was packing up boxes and trunks, Emma stumbled upon an old diary hidden beneath the piano bench. It was worn and dusty, but as she opened it, she saw that it belonged to a young woman named Sophia.\n\nSophia had lived"}, {"role": "user", "content": "tell me another story"}, {"role": "assistant", "content": "Here is another short story:\n\nThe Starlight Serenaders\n\nIn a small village nestled in the rolling hills of Tuscany, there lived a group of elderly men who called themselves the Starlight Serenaders. For years, they had been gathering under the stars on warm summer evenings to play their instruments and sing together.\n\nTheir music was like nothing anyone had ever heard before. It was as if the stars themselves were singing in harmony with the men's rustic voices and worn instruments. People would come from all around to listen, mesmerized by the beauty of the music.\n\nBut as time went on, one by one, the Serenaders began to pass away. The villagers thought that would be the end of the magical performances. However,"}, {"role": "user", "content": "write me anothe story"}], "temperature": 0.7, "top_p": 1, "frequency_penalty": 1.05}

```

## Additional Information

i have tried new threads, continuing threads, almost every combination but i can't get these items to log or be used

i took LLAMA3-70 out of the mix and tried a different model with NO workspace param modifications. Instead i modified just the chat control advanced params and had the same issue in a brand new thread: 

```[open_webui.apps.openai.main] {"stream": true, "model": "meta-llama/Llama-2-70b-chat-hf", "messages": [{"role": "user", "content": "Tell me a story"}], "temperature": 1}```

![image](https://github.com/user-attachments/assets/3059ca74-f5ee-41f4-95af-3b9ab49ff2a7)

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by jocull** [comment]
I can confirm this specific issue:

> Modified context length and it didn't log

In the requests when the context has been modified at the chat level we see something like this:

```json
{
	"options": {
		"num_ctx": 32000
	}
}
```

However when the default in Advanced Parameters has been modified I don't see it taking effect at all:

```json
{
	"options": {
	}
}
```

Am I configuring something wrong? 😕

**Comment by jocull** [comment]
After upgrading versions I modified and saved the global setting again, then refreshed the UI. Now it appears to be sticky on new chats. Perhaps something weird in the initial migration for settings that were previously saved?

**Comment by tjbck** [comment]
Models accessible via `openai` connections do not support all the advanced params.
