### ISSUE TITLE
Incorrect numbering on Numbered lists with lines in between.

### ISSUE THREAD

**Issue by lufixSch** [open-webui/open-webui#5369]
# Bug Report

## Installation Method

Docker/Docker-Compose

## Environment

- **Open WebUI Version: 0.3.16** 

- **Operating System: Debian**
- **Browser (if applicable): Firefox**

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

The numbering in a list displayed in OpenWebUI should be the same as the numbering produced by the LLM.

## Actual Behavior:

When rendering a numbered list generated by the LLM, the numbering provided by the LLM is ignored

## Description

**Bug Summary:**
When the LLM generates a numbered List in Markdown, the numbering of the lists restarts at "1" if a text block is between the two items in the list. This happens even though the LLM numbered the items correctly.

## Reproduction Details

**Steps to Reproduce:**
1. Start Open WebUI
2. Create a Chat
3. Replace the LLM Response with the minimal example below
4. Press Save

## Logs and Screenshots

**Screenshots/Screen Recordings (if applicable):**
Original Markdown:
```
Sure, here are 5 random names:

1. Alex Johnson

Text between the list items

2. Sophia Wang
Another Text between the list items

3. Felipe Martinez

4. Jordan Baker

5. Amina Patel
```

Rendered Markdown
![image](https://github.com/user-attachments/assets/91921c93-08f8-47c8-9772-589f1a7bf9b4)

**Comment by tjbck** [comment]
Fixed on dev!
