### ISSUE TITLE
Still logged in and can reset password, but it says wrong email. Where do I view the email I signed up with?

### ISSUE THREAD

**Issue by ckizer** [open-webui/open-webui#5381]
# Bug Report
iCloud has saved several dozen autofill passwords for localhost:3000

Since open-webui is still open I can reset the password. However it says wrong email for any email I try. If I view my profile it doesn't show the signed in email address.

How can I find the email addressed tied to my open-webui account _before_ I get locked out?

Running the docker version, copied the command on my Mac from the install instructions on this repo readme.

It does appear that I used the right email, because creating new accounts, can't sign in either when I know the email I signed up with. 

I was able to find out my admin email has a typo, how can I fix this?
`Admin: Name (name@gmail.coPM)`

**Comment by jannikstdl** [comment]
If you log in with the email you find out you can change it in the admin panel

**Comment by ckizer** [comment]
Yes the admin panel UI is confusing, why not put it down with the profile menu in bottom left? There's even an option to jump to admin settings, but it doesnt' take you to the top right admin settings. Basically there's 3 places to change settings, and easy to overlook :-) 
![CleanShot 2024-09-12 at 15 06 01@2x](https://github.com/user-attachments/assets/ad267132-0a05-4843-ac29-2d1c4de95dab)

**Comment by ckizer** [comment]
Please close
