### ISSUE TITLE
Rename Chat Model - Nickname

### ISSUE THREAD

**Issue by ckizer** [open-webui/open-webui#5383]
**Is your feature request related to a problem? Please describe.**
I want to rename a model from:
`mannix/llama3.1b-8b-abliteriated:latest`

To:
`Uncensored 3.1b 8b
`

I saw several discussions and bug reports on this, which suggest that this feature exists, but I can't figure out how to change the name of an Ollama model inside Open-WebUI as people have suggested. Maybe I'm having trouble navigating the UI. I even tried creating a new model, but that didn't work. I simply want to rename an existing model that I use.

**Comment by silentoplayz** [comment]
Workspace
![image](https://github.com/user-attachments/assets/6147cf64-c3ce-4d57-80a7-ece6588ac3dd)

Models
![image](https://github.com/user-attachments/assets/3a69e8ec-5deb-47ee-a265-6cd98e2bd025)

Edit button for a model
![image](https://github.com/user-attachments/assets/d9ebd6f9-1752-4b4e-bdfe-789916b5de2f)

Type name
![image](https://github.com/user-attachments/assets/b48b89fd-46cb-4344-a861-8a7120f496fe)

**Comment by ckizer** [comment]
Thank you, please also add it under the top right when I go to the model overview page from admin settings. So many different places to configure!

**Comment by c-hoffmann** [comment]
For me, when I click on "Models" in "My workspace" it doesn't show any models - even though there clearly is one (connected via OpenAI API), which I can use when starting a new conversation. The model shows up in the Admin panel, but I can't change the name there. Also, I'd like to change the name for all users, not just myself.

**Comment by Iemand005** [comment]
I cannot find out how to change the model name and icon with koboldcpp thought OpenAI API. Such a basic feature as just changing the name shouldn't be such a tough thing to find, if it's even possible at all with koboldcpp + open-webui. My webui looks different than all the screenshots too, I just want to rename the model instead of having it show "koboldcpp/llama2...". Extremely frustrating.
