### ISSUE TITLE
Disable "Enable new sign ups" does not work

### ISSUE THREAD

**Issue by stevenbaert** [open-webui/open-webui#5386]
# Bug Report

## Installation Method

Docker 

## Environment

0.3.21

- **Operating System:** Linux (Synology) 
- **Browser (if applicable):Edge Chromium 

**Confirmation:**

- [ x] I have read and followed all the instructions provided in the README.md.
- [x ] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [ ] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

New sign ups should be rejected

## Actual Behavior:

Sign ups are allowed and totally unknown users show up as *pending* member into my list of users. 

## Description

**Bug Summary:**
See actual behavior 

## Reproduction Details

**Steps to Reproduce:**
Not relevant, users sign up though they should not be allowed to.

**Comment by silentoplayz** [comment]
Working fine for me on the latest dev.
![image](https://github.com/user-attachments/assets/261257e4-e925-4f78-9a92-ccf59a3a9aea)

**Comment by stevenbaert** [comment]
“I’m not sure I fully understand your point. I exclusively use OAuth for sign-ins, as it’s the most secure method, and passwords are vulnerable to brute-force attacks. Through OAuth, users can log in via Google, but they still appear in a ‘pending’ state. I’m using the latest version of Open-Webui, so the issue isn’t resolved for me. My goal is to prevent random users from signing up.

**Comment by silentoplayz** [comment]
Have you set `ENABLE_SIGNUP` as an environment variable for your Open WebUI instance or disabled new sign ups within the UI?

**Comment by stevenbaert** [comment]
Only within the GUI.

**Comment by stevenbaert** [comment]
Have now done it in gui and in variable container but no change. Any user can still login then it shows this user status pending.

**Comment by silentoplayz** [comment]
If you have the `OAUTH_MERGE_ACCOUNTS_BY_EMAIL` environment variable set to `true`, this bypasses the env var/toggle in the UI to disable new sign ups, which is intended behavior.

**Comment by stevenbaert** [comment]
Have now done it in gui and in variable container but no change. Any user can still login then it shows this user status pending.

Also merge is not enabled.

**Comment by tjbck** [comment]
Should be fixed with the latest dev, test wanted here!
