### ISSUE TITLE
Can't change the favicon permanently

### ISSUE THREAD

**Issue by Sjoholm** [open-webui/open-webui#5417]
# Bug Report

## Installation Method

pip

## Environment

- **Open WebUI Version:** 0.3.21
- **Ollama (if applicable):** 

- **Operating System:** Windows 11

**Confirmation:**

- [ x] I have read and followed all the instructions provided in the README.md.
- [ x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x ] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

I replace the static\favicon.png, but when restarting open web ui it's replaced with the original favicon again?

## Actual Behavior:

I want to permanently replace the favicon to be able to customize the look

## Description

**Bug Summary:**
[Provide a brief but clear summary of the bug]

## Reproduction Details

**Steps to Reproduce:**
[Outline the steps to reproduce the bug. Be as detailed as possible.]

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots/Screen Recordings (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by bgeneto** [comment]
Same problem here. I've mounted a volume for static files, changed the and icons but changes won't remain. I see that there are two static files location in open webui docker container:
/app/build/static
And
/app/backend/open_webui/static 
If I remember correctly. What is the proper way to change logo and icon permanently while using docker? TIA
