### ISSUE TITLE
[BUG] Memory function error in latest dev version

### ISSUE THREAD

**Issue by Yanyutin753** [open-webui/open-webui#5433]
# Bug Report

## Installation Method

Memory function error in latest [dev version](https://github.com/open-webui/open-webui/tree/dev)

## Environment

- **Open WebUI Version:** [dev latest]

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Normal use of memory function!

## Description

**Bug Summary:**

Each session that uses the memory function(**api/v1/memories/query**)  to request the port query return the error of 500

![image](https://github.com/user-attachments/assets/69e20b83-3c67-441d-b7b8-70cf96305023)

![image](https://github.com/user-attachments/assets/fb4627be-e6e3-4312-a879-313050ed40e5)

![image](https://github.com/user-attachments/assets/2421ff39-7784-4363-91e9-75237360a9bd)

## Note

Hope to fix this bug, Thanks!

**Comment by tjbck** [comment]
Taking a look

**Comment by tjbck** [comment]
Fixed!

**Comment by Yanyutin753** [comment]
Thanks！！！
