### ISSUE TITLE
The upgrade of `langchain-openai` caused some functions that depend on it to fail

### ISSUE THREAD

**Issue by CookSleep** [open-webui/open-webui#5471]
# Bug Report

## Installation Method

Docker

## Environment

- **Open WebUI Version:** v0.3.21
- **Operating System:** Ubuntu 22.04
- **Browser:** Edge 128.0.2739.79

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

The various functions of `langchain-openai` work normally

## Actual Behavior:

The various functions of `langchain-openai` do not work properly, and the following error is shown during import:
```
Something went wrong :/ no validator found for <class 'langchain_core.callbacks.base.BaseCallbackHandler'>, see arbitrary_types_allowed in Config
```

## Description

**Bug Summary:**
The upgrade of `langchain-openai` caused some functions that depend on it to fail

## Reproduction Details

**Steps to Reproduce:**
1. Import any function that requires `langchain-openai`, using [OpenAI ReAct Agent](https://www.openwebui.com/f/michaelpoluektov/openai_react) as an example
2. This function works with `langchain-openai==0.1.24`, but completely fails in the latest version. When re-importing, you will encounter:
```
Something went wrong :/ no validator found for <class 'langchain_core.callbacks.base.BaseCallbackHandler'>, see arbitrary_types_allowed in Config
```
> You may need to rebuild the container to trigger this issue, as `langchain-openai` may not have been upgraded previously

**Comment by tjbck** [comment]
`langchain-openai` is not shipped with open-webui.
