### ISSUE TITLE
enh: Save edited response as copy.

### ISSUE THREAD

**Issue by 5E-324** [open-webui/open-webui#5477]
**Is your feature request related to a problem? Please describe.**
Currently, after a response message is edited, the original message is overwritten. But I generally prefer keeping the original response as well.

**Describe the solution you'd like**
After the response message is edited and the save button is clicked or Ctrl+Enter is pressed, create another variant of the message with the edited content, the original response is left unchanged, similar to the behavior of "regenerate". Preferably, indicate somewhere that the message is edited.

Add an "overwrite" button that keeps the original behavior that overwrite the message.

It would be reasonable to make "save a copy" the default behavior, because even if the original response is no longer needed, you can simply ignore it. However, if the original response is still needed but is overwritten, currently there's no way to get it back.

**Describe alternatives you've considered**
Copy the message, click regenerate, stop generation, click edit, paste, edit message, save.
This is inconvenient and will waste computing power.

**Comment by tjbck** [comment]
Great idea! Taking a look!
