### ISSUE TITLE
enh: Pinning models

### ISSUE THREAD

**Issue by 5E-324** [open-webui/open-webui#5478]
**Is your feature request related to a problem? Please describe.**
Some provider (e.g. OpenRouter) provides a huge number of models, this make finding models much more difficult.

**Describe the solution you'd like**
Add a button to pin models. When a model is pinned, it shows on the top of the list. Similar to pinning chats.

**Describe alternatives you've considered**
- Disable unused models: There doesn't seem to be a way to disable all models, and there are way too many models to disable one by one. And if I want to try some other models, I will have to enable them and maybe disable them again afterwards, which is more inconvenient.
- Searching: Need to search every time, and there may still be multiple models shown because they share similar names.
- Reorder models by dragging: Having an extremely long list also makes this more difficult.

**Comment by tjbck** [comment]
"Move to top" button has been added to dev!
