### ISSUE TITLE
Open webui cant use o1-model

### ISSUE THREAD

**Issue by 123hi123** [open-webui/open-webui#5490]
# Bug Report

## Installation Method

I installed Open WebUI using Docker(GPU version) by pulling the official Docker image and running it according to the provided documentation.

## Environment

- **Open WebUI Version:** v0.3.11
- **Operating System:** Ubuntu 22.04 LTS
- **Browser (if applicable):** Google Chrome 112.0.5615.49

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of Open WebUI.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior

I expect to be able to use the `o1-model` within Open WebUI seamlessly, allowing for model loading and inference without any errors.

## Actual Behavior

When attempting to use the `o1-model` in Open WebUI, the system fails to recognize the model and displays an error message. The model fails to load, rendering the related functionalities unusable.

## Description

**Bug Summary:**
Unable to use the `o1-model` in Open WebUI as the system does not recognize or load the model, causing related features to fail.

## Reproduction Details

**Steps to Reproduce:**

1. Pull and run the Open WebUI Docker image using the following commands:

   ```bash
   docker pull openwebui/openwebui:latest
   docker run -d -p 8080:8080 openwebui/openwebui:latest
   ```

2. Place the `o1-model` in the designated models directory within the Docker container.

3. Navigate to the models management page in Open WebUI.

4. Attempt to add the `o1-model`.

5. Observe that the system displays an error message and fails to load the model.

## Logs and Screenshots

**Browser Console Logs:**

**Docker Container Logs:**

**Screenshots/Screen Recordings (if applicable):**

![image](https://github.com/user-attachments/assets/58aa106e-3def-41a0-b5db-20e57f0d978f)
![image](https://github.com/user-attachments/assets/6b617789-8c70-4aad-9936-3d3d8f77507d)

## Additional Information

I have verified that the `o1-model` files are correctly placed in the models directory and that other models are functioning correctly within Open WebUI. The issue only occurs when attempting to use the `o1-model`. I suspect that the problem might be related to the model file format or version incompatibility.

**Comment by TianzeWang** [comment]
Likewise. Same issue.

**Comment by crzroot** [comment]
Yes, I am too

**Comment by bahuzh** [comment]
Unsupported value: 'stream' does not support true with this model. Only the default (false) value is supported.

**Comment by 123hi123** [comment]
> Unsupported value: 'stream' does not support true with this model. Only the default (false) value is supported.
> 
> 
> https://platform.openai.com/docs/guides/reasoning/beta-limitations

I see so can we shut down the stream mode manually?

**Comment by fangyuan99** [comment]
> > Unsupported value: 'stream' does not support true with this model. Only the default (false) value is supported.
> > https://platform.openai.com/docs/guides/reasoning/beta-limitations
> 
> I see so can we shut down the stream mode manually?

The same need

**Comment by tjbck** [comment]
<img width="779" alt="image" src="https://github.com/user-attachments/assets/e23e9f2a-a411-4c6c-80b8-ff25f45ea5bb">


Stream Chat Response toggle option has been added to Settings > Interface in dev!

**Comment by 123hi123** [comment]
what version you are
my show below and i try close the most likey one but still not work 'Fluidly stream large external response chunks'
![image](https://github.com/user-attachments/assets/0cbf0e86-caac-402d-baee-5dec64df19e6)

**Comment by fangyuan99** [comment]
> what version you are my show below and i try close the most likey one but still not work 'Fluidly stream large external response chunks' ![image](https://private-user-images.githubusercontent.com/36217117/369063317-0cbf0e86-caac-402d-baee-5dec64df19e6.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MjY3NTk3NDQsIm5iZiI6MTcyNjc1OTQ0NCwicGF0aCI6Ii8zNjIxNzExNy8zNjkwNjMzMTctMGNiZjBlODYtY2FhYy00MDJkLWJhZWUtNWRlYzY0ZGYxOWU2LnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA5MTklMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwOTE5VDE1MjQwNFomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPWZjYjM5YzUyMGI0OTQ4MjZjNTZiYzlkNmFhNGUxN2JjOTk4MWJlYWMwOTVhODg4NDFiMmY0MTQ3MDBmMWM0ZDYmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.Mpw2pgQD9v1O3dH3UYU-Y6In14OyDb4iJq2oMh1CYb4)

His should be a development version, not yet release

**Comment by 123hi123** [comment]
ok but is can i think add this to workplace will be better fulfill way

**Comment by hxt365** [comment]
o1 model still can't not use stream, needed to disable stream response for this specific model

**Comment by 123hi123** [comment]
> o1 model still can't not use stream, needed to disable stream response for this specific model

Ya , now the o1 works will in my owu
If you turn off the stream the o1 will work nice in o1 series
