### ISSUE TITLE
bug: RBAC file API 

### ISSUE THREAD

**Issue by jannikstdl** [open-webui/open-webui#5491]
# Bug Report

## Environment

- **Open WebUI Version:**  -> latest dev (0.3.22)
- Also on older versions

## Description

**Bug Summary:**
The new added RBAC in file access allows you to only download files if you uploaded them. But for collections it fails. Since collections are uploaded by admins by now and if you then give a model this collection as a normal user you cant download the file in the citations.p
## Reproduction Details

**Steps to Reproduce:**
1. Add a collection as admin user
2. Add the collection to a models knowledge
3.  Log i as normal user
4. Ask the model something
5. Try to open the file from the citations 

## Logs and Screenshots

https://github.com/user-attachments/assets/7e4f97bf-4acd-45dc-b689-840cfae3ab00

**Comment by tjbck** [comment]
Merging this issue with #3527
