### ISSUE TITLE
Adjusting workspace contents on a user basis

### ISSUE THREAD

**Issue by AlbertoManuel07** [open-webui/open-webui#5493]
**Is your feature request related to a problem? Please describe.**
Not being able to make user-based selections for the tools, functions and documents we add in the Workspace section causes everyone to have access.

**Describe the solution you'd like**
Being able to make user-based selections for these and making them available only to the relevant person will add great innovation to the application.

**Describe alternatives you've considered**
Maybe we can add an extra role for this. Why not.

**Additional context**

**Comment by tjbck** [comment]
#2924
