### ISSUE TITLE
bug: Collections are not being correctly updated when uploading or tagging new documents

### ISSUE THREAD

**Issue by jannikstdl** [open-webui/open-webui#5494]
# Bug Report

## Environment

- **Open WebUI Version:** latest dev (0.3.22)
- Also on older versions

## Expected Behavior:

Collections are updated automatically when uploading or tagging new files.

## Actual Behavior:

Collections is not updated (see screenrecording)

## Reproduction Details

**Steps to Reproduce:**
in my screenrecording

## Logs and Screenshots

https://github.com/user-attachments/assets/1a4e1b70-4136-4b14-9de3-51a3dbf9f1ae

**Comment by tjbck** [comment]
Merging this issue with #3527
