### ISSUE TITLE
Show tool usage in chat

### ISSUE THREAD

**Issue by MindFreeze** [open-webui/open-webui#5520]
**Is your feature request related to a problem? Please describe.**
I don't know if the LLM used the proper tool or hallucinated. Even if I export the chat, this info is missing.

**Describe the solution you'd like**
We should see in the chat when the LLM used a tool, what were the params and what was the result. This could be collapsed by default and expand on click.

**Describe alternatives you've considered**
Logging and looking at the logs I guess

**Comment by tjbck** [comment]
`self.citation` = True

https://www.theregister.com/2024/08/26/ai_llm_tool_calling/

**Comment by MindFreeze** [comment]
I saw the code for this. Might give it a crack tomorrow
