### ISSUE TITLE
Disable Change Log Pop Up At Login

### ISSUE THREAD

**Issue by stondino00** [open-webui/open-webui#5521]
Is there a way to disable the change log/release notes pop-up for normal users who login

**Comment by rikhuijzer** [comment]
@tjbck I appreciate all the updates that open webui is receiving and think it's a great tool. However, my instance is set to auto-update, so in practice this means that each day I will get a new release notes pop up for each device. Clicking this away can be very frustrating especially when, for example, I'm walking in a supermarket and want to ask a quick question.

Would it be possible to make the note less often visible?
