### ISSUE TITLE
High CPU Usage and Performance Issues with Long Chat Threads

### ISSUE THREAD

**Issue by Keithsc** [open-webui/open-webui#5533]
Description:  

I want to highlight a significant performance issue that affects many users of the OpenWeb UI, especially those interacting with long chat threads. As mentioned in issue #3620, I've noticed that the application exhibits substantial lag and high CPU usage when handling extensive conversations, which is becoming a blocker for my daily usage of this otherwise excellent product. 

Problem: 
The performance of the UI deteriorates significantly in chats with long threads, leading to: 

    High CPU Usage:  My machine’s fan ramps up due to the CPU workload, indicating potential overheating concerns.
    Long Wait Times:  The chat interface often becomes unresponsive, necessitating users to wait for the UI to catch up or restart their browsers.
    Rapid Chat Growth:  When engaging with the Whisper interface, it doesn't take long to build a lengthy conversation. After about 10 minutes of back-and-forth dialogue, the chat can grow quickly, leading to substantial CPU usage.
     

Requested Solution: 
Rather than considering this an enhancement, this is a fundamental issue that deserves urgent attention: 

    Prioritize Optimization:  Address the performance bottlenecks associated with long chat threads.
    Consider Features for Mitigation:  A shallow clone feature that retains only the last few exchanges could help ease the burdens on system resources.
     

As a regular user who utilizes this fantastic tool multiple times a day, I appreciate all the hard work and dedication that has gone into developing it. However, this performance issue is causing frustrations that impact my experience. It would be wonderful to see this addressed, as it greatly affects usability. 

Thank you for your attention to this matter! I'm looking forward to any improvements that can be made.

**Comment by tjbck** [comment]
Closing in favour of https://github.com/open-webui/open-webui/issues/3620 

I agree 100% and I've been trying to investigate this issue, and will try to allocate my effort into resolving this when I have more time but I'd appreciate some help from the community here!
