### ISSUE TITLE
O1 not working, streaming should be disabled

### ISSUE THREAD

**Issue by TianzeWang** [open-webui/open-webui#5539]
# Bug Report

## Installation Method

Docker

## Environment

- **Open WebUI Version:**  v0.3.22

- **Operating System:** macOS Big Su
- **Browser (if applicable):** Arc

**Confirmation:**

- [X ] I have read and followed all the instructions provided in the README.md.
- [ X] I am on the latest version of both Open WebUI and Ollama.
- [ X] I have included the browser console logs.
- [X ] I have included the Docker container logs.
- [ X] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

O1 should be working

## Actual Behavior:

O1 not working due to: 
<img width="960" alt="image" src="https://github.com/user-attachments/assets/726a87d2-5fdb-47c6-848e-404bad292a7b">

**Comment by silentoplayz** [comment]
Look for the `Stream Chat Response` option found in your Settings for Open WebUI and disable it. O1 does not stream its responses.

**Comment by c0h1b4** [comment]
There is no `Stream Chat Response` option :/ 
BTW I'm using v0.3.32 (latest).

**Comment by c0h1b4** [comment]
<img width="779" alt="image" src="https://github.com/user-attachments/assets/ff2541b1-2f8a-4ba4-b8b7-ae9d8543bdf2">

<img width="777" alt="image" src="https://github.com/user-attachments/assets/9fdccf14-9948-42fe-b0a4-511cfcb18d86">

**Comment by silentoplayz** [comment]
> There is no `Stream Chat Response` option :/ BTW I'm using v0.3.32 (latest).

The `Stream Chat Response` option was moved to the top of the `Advanced Parameters` section. It can be modified on a per-chat, per-account, and per-model level basis now. See [https://docs.openwebui.com/tutorials/features/chat-params](Chat Parameters documentation) for more info.

**Comment by Nitschi** [comment]
Can it be disabled for the o1-models separately?
I would be nice for this to work with the default config.

**Comment by Nitschi** [comment]
This is already very helpful, thank you. 
I'm still of the opinion that no manual steps (like changing this setting in the WebUI) should have to be taken to use the model.
I opened #6900 .
It would allow us to have the full setup as code (mostly a `docker-compose.yml` + an `.env`-file) and minimal to no admin account intervention (Accounts are created via OIDC).
Thanks!
