### ISSUE TITLE
Download Plain Text does not work anymore in v0.3.22

### ISSUE THREAD

**Issue by bgeneto** [open-webui/open-webui#5561]
# Bug Report

## Installation Method

Docker with docker-compose

## Environment

- **Open WebUI Version:**v0.3.22
- **Ollama (if applicable):** n/a

- **Operating System:** Debian 12
- **Browser (if applicable):** Chrome/Edge 129

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

A markdown/text file should be download when clicking in the chat "Download" -> "Plain text (.txt)" button.

## Actual Behavior:

Nothing happens. works for pdf and json downloads.

## Description

**Bug Summary:**

 Download Plain text .txt file not working. 

## Reproduction Details

**Steps to Reproduce:**

Ask LLM anything, wait for the response and then click "Download" -> "Plain text (.txt)" button. 

## Logs and Screenshots

**Browser Console Logs:**
```
Menu.svelte:49  Uncaught (in promise) ReferenceError: _chat is not defined
    at v (Menu.svelte:49:24)
v @ Menu.svelte:49
await in v
H @ Menu.svelte:231
(anonymous) @ lifecycle.js:105
(anonymous) @ lifecycle.js:104
(anonymous) @ events.js:8
hs @ event.js:43
(anonymous) @ event.js:48
Show 5 more frames
Show less
```

**Docker Container Logs:**
none

**Screenshots/Screen Recordings (if applicable):**

![image](https://github.com/user-attachments/assets/14a8c9db-ceea-41fc-982b-77bff22c664b)

## Additional Information

It worked in the previous version v.0.3.21 (but neither in the dev branch).

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by silentoplayz** [comment]
Can confirm this error is happening for me as well.

Browser error log upon pressing the `Plain text (.txt)` option for downloading a chat:
```
Uncaught (in promise) ReferenceError: _chat is not defined
    v Menu.svelte:49
Menu.svelte:49:23
```

**Comment by tjbck** [comment]
Fixed with the latest.

**Comment by silentoplayz** [comment]
Can confirm it's been fixed. Thanks!
