### ISSUE TITLE
WEBUI_AUTH=False error

### ISSUE THREAD

**Issue by zsolt-dev** [open-webui/open-webui#5575]
easy to reproduce:

1. run:
`docker run -e WEBUI_AUTH=False -d -p 3100:8080 --add-host=host.docker.internal:host-gateway -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:main`

2. open localhost:3100

3. see error in browser: 
`You do not have permission to access this resource. Please contact your administrator for assistance.`

**Comment by tjbck** [comment]
Please do not create duplicate issues. 
#5566

**Comment by thams** [comment]
The duplicate issue you mention #5566 is user-error by mis-specification of the "Fales" vs. "False".

In either case, the error exists, and happens on Linux hosts but not Mac hosts.
