### ISSUE TITLE
FR: Support model parameter in request

### ISSUE THREAD

**Issue by fangyuan99** [open-webui/open-webui#5602]
**Describe the solution you'd like**
When using the ChatGPT official website, you can switch to a temporary-chat and select the corresponding model like: [https://chatgpt.com/?temporary-chat=true&model=gpt-4o](https://chatgpt.com/?temporary-chat=true&model=gpt-4o) . However, it seems that openwebui currently only supports the temporary-chat parameter and doesn't support selecting models through the model parameter.

**Comment by tjbck** [comment]
Added to dev!
