### ISSUE TITLE
Bug/UI: going to the admin settings from the sidebar should close the sidebar

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [open-webui/open-webui#5608]
# Bug Report

## Installation Method

docker compose

## Environment

- **Open WebUI Version:** 0.3.23
- **Browser (if applicable):** brave (desktop / android)

**Confirmation:**

- [ X ] I have read and followed all the instructions provided in the README.md.
- [ X ] I am on the latest version of both Open WebUI and Ollama.
- [ X ] I have included the browser console logs.
- [ X ] I have included the Docker container logs.
- [ X ] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

From the sidebar, clicking on 'Admin settings' should get me there without me having to close the sidebar

## Actual Behavior:

The sidebar is still present so the admin settings are hidden.

## Description

**Bug Summary:**
From the sidebar, clicking on 'Admin settings' should get me there without me having to close the sidebar

## Reproduction Details

**Steps to Reproduce:**
1. resise the window to be verticalish / use a vertical screen smartphone directly
2. Open the sidebar
3. click on your account name
4. Click on 'Admin panel'
5. Notice the admin settings are opened but the sidebar is still blocking the view

## Logs and Screenshots

**Screenshots/Screen Recordings (if applicable):**
![image](https://github.com/user-attachments/assets/c9b23de5-f328-45e1-99ca-f78b9a78dc03)

## Additional Information

Related to #5607

**Comment by tjbck** [comment]
Fixed.
