### ISSUE TITLE
Bug/UI : searching for chats should hide the pinned chats

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [open-webui/open-webui#5609]
# Bug Report

## Installation Method

docker compose

## Environment

- **Open WebUI Version:** 0.3.23

**Confirmation:**

- [ X ] I have read and followed all the instructions provided in the README.md.
- [ X ] I am on the latest version of both Open WebUI and Ollama.
- [ X ] I have included the browser console logs.
- [ X ] I have included the Docker container logs.
- [ X ] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Searching for chats should show more than 3 chats at a time

## Actual Behavior:

Because of the pinned chats, I can only see 2-3 chats at a time. If I had a few more pinned chats I might not even be able to search for any chats!

## Description

**Bug Summary:**
Screen real estate is wasted on search by always showing pinned chats. Hindering search, possibly to the point of making it unusable (if you have many pinned chats then the search space is too small)

## Reproduction Details

**Steps to Reproduce:**
1. Make the window vertical-ish or use a vertical screen smartphone
2. Pin some chats
3. Search for more chats and notice that the search space is noticeably small.

## Logs and Screenshots

**Screenshots/Screen Recordings (if applicable):**
![image](https://github.com/user-attachments/assets/0c00b6e5-fe3c-4e14-a51b-7f9cacd53cac)

## Additional Information

Related to #5607

**Comment by tjbck** [comment]
Added.
