### ISSUE TITLE
issue: Milvus - failed to create index on collection

### ISSUE THREAD

**Issue by aouicher** [open-webui/open-webui#5622]
# Bug Report

## Installation Method

Docker

## Environment

- **Open WebUI Version:** 0.3.23

- **Operating System:** Amazon Linux / Red Hat Enterprise Linux

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Description

I'm encountering an error when trying to create an index in Milvus after uploading documents to OpenWebUI. The collection is successfully created, but the index creation fails.

## Reproduction Details

Upload a document (XLS or CSV file) to OpenWebUI
Attempt to create a prompt about the uploaded document

## Logs and Screenshots

```
DEBUG [pymilvus.milvus_client.milvus_client] Created new connection using: 7f116f666a75408580eb200a667b1e27

DEBUG [pymilvus.milvus_client.milvus_client] Successfully created collection: open_webui_c69e46a84c2f4cffc25f529588d460cf61b5f75add2a3aad4a0a47affd0d0e6

ERROR [pymilvus.milvus_client.milvus_client] Failed to create an index on collection: open_webui_c69e46a84c2f4cffc25f529588d460cf61b5f75add2a3aad4a0a47affd0d0e6

ERROR [pymilvus.decorators] RPC error: [create_index], <MilvusException: (code=1100, message=efConstruction out of range: [1, 2147483647]: invalid parameter[expected=valid index params][actual=invalid index params])>, <Time:{'RPC start': '2024-09-23 06:10:04.605969', 'RPC error': '2024-09-23 06:10:04.611462'}>

pymilvus.exceptions.MilvusException: <MilvusException: (code=1100, message=efConstruction out of range: [1, 2147483647]: invalid parameter[expected=valid index params][actual=invalid index params])>

ERROR [pymilvus.milvus_client.milvus_client] Failed to search collection: open_webui_c69e46a84c2f4cffc25f529588d460cf61b5f75add2a3aad4a0a47affd0d0e6
```

You can see that collection is created but without index on Milvus
![image](https://github.com/user-attachments/assets/4574bafa-c0c3-4848-a6f6-98db38183083)

## Additional Information

The error occurs with all file types
Using default Milvus configuration settings
The collection is successfully created, but the index creation fails

## Note

Any assistance or guidance on resolving this issue would be greatly appreciated. Please let me know if you need any additional information.

**Comment by sir3mat** [comment]
Same issue

**Comment by tjbck** [comment]
PR Welcome!

**Comment by tjbck** [comment]
Fixed on dev!

**Comment by icfai-aniketsingh** [comment]
Any ETA do we have to get that release from dev?
