### ISSUE TITLE
issue: windows Functions - [WinError 32] The process cannot access the file because it is being used by another process

### ISSUE THREAD

**Issue by tjbck** [open-webui/open-webui#5642]

**Comment by tjbck** [comment]
@EtiennePerot Related #5511

**Comment by EtiennePerot** [comment]
Hmm. It seems like it is complaining that a file is being accessed from multiple processes, but the code specifically closes the temporary file prior to calling `exec` (by virtue of ending the `with` block):

https://github.com/open-webui/open-webui/blob/6b463164f4b129e0ce4bdc9008dd661214fe5eb5/backend/open_webui/apps/webui/utils.py#L87-L97

I don't have a Windows machine to test this on either, but the [Python documentation on `tempfile.NamedTemporaryFile`](https://docs.python.org/3/library/tempfile.html#tempfile.NamedTemporaryFile) helpfully states:

> Opening the temporary file again by its name while it is still open works as follows:
> On POSIX the file can always be opened again.
> On Windows, make sure that at least one of the following conditions are fulfilled:
> * `delete` is false
> * additional open shares delete access (e.g. by calling [os.open()](https://docs.python.org/3/library/os.html#os.open) with the flag O_TEMPORARY)
> * `delete` is true but `delete_on_close` is false. Note, that in this case the additional opens that do not share delete access (e.g. created via builtin [open()](https://docs.python.org/3/library/functions.html#open)) must be closed before exiting the context manager, else the [os.unlink()](https://docs.python.org/3/library/os.html#os.unlink) call on context manager exit will fail with a [PermissionError](https://docs.python.org/3/library/exceptions.html#PermissionError).

So I think adding `delete_on_close=True` should suffice, given that the file is deleted later in the `finally` block. I can send a PR for that later today.

**Comment by tcgumus** [comment]
faced the same problem with the latest build on windows.  @EtiennePerot does your solution solves it? I will try it today.

**Comment by EtiennePerot** [comment]
No, I was wrong above. But I just sent #5649 which should fix it.

**Comment by tcgumus** [comment]
Yes. #5649 solved my problem on windows. thanks @EtiennePerot 👏

**Comment by tjbck** [comment]
Thanks everyone!

**Comment by github-pmj** [comment]
Just upgraded to 0.3.28 - issue resolved - thanks all for your efforts
