### ISSUE TITLE
Issue: RAG_FILE_MAX_COUNT and RAGE_FILE_MAX_SIZE are ineffective and don't work.

### ISSUE THREAD

**Issue by tcgumus** [open-webui/open-webui#5652]
Hello,

I’ve followed the documentation and added the necessary configuration parameters, while also ensuring I'm using the latest release. However, it seems that these two specific parameters may not yet be fully functional. Despite reviewing the code, I couldn't identify where they are actively utilized. At the moment, it appears they are simply registered within `config.py` and `main.py`, without triggering any checks or errors elsewhere in the codebase.

Could you clarify if this is an intended feature or if it's reserved for future development? 

Thank you!

**Comment by tjbck** [comment]
https://github.com/open-webui/open-webui/blob/6b463164f4b129e0ce4bdc9008dd661214fe5eb5/src/lib/components/chat/MessageInput.svelte#L182

it's being used.
