### ISSUE TITLE
issue: "RuntimeError: no running event loop" After upgrade to 0.3.25 via pip on Windows

### ISSUE THREAD

**Issue by e-uhlich** [open-webui/open-webui#5658]
# Bug Report

## Installation Method

pip install --upgrade open-webui

## Environment

- **Open WebUI Version:** 0.3.25
- **Ollama (if applicable):** /

- **Operating System:** Windows 10
- **Browser (if applicable):** /

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:
When entering "open-webui serve" in the windows command prompt, the server should be started.

## Actual Behavior:

After entering "open-webui serve" I'm getting an error message ending with:
"RuntimeError: no running event loop
sys:1: RuntimeWarning: coroutine 'periodic_usage_pool_cleanup' was never awaited"

open-webui version 0.3.23 worked just fine and after reverting to this version, the server starts.

## Description

**Bug Summary:**
After upgrading to open-webui version 0.3.25 the server doesn't start and returns an error.

## Reproduction Details

**Steps to Reproduce:**
- latest working open-webui version: 0.3.23
- run "pip install --upgrade open-webui"
- run "open-webui serve"

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots/Screen Recordings (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Additional Information

Error message after running "open-webui serve":
RuntimeError: no running event loop
sys:1: RuntimeWarning: coroutine 'periodic_usage_pool_cleanup' was never awaited

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by shenyunhuan** [comment]
0.3.26 on windows issue "RuntimeError: no running event loop
sys:1: RuntimeWarning: coroutine 'periodic_usage_pool_cleanup' was never awaited"

**Comment by tjbck** [comment]
https://pypi.org/project/open-webui/0.3.27.dev2/ seems to have solved the issue, 0.3.27 will be released shortly.
