### ISSUE TITLE
Add options to completely shut down Whisper or include functionality in environment variables to install or enable Whisper

### ISSUE THREAD

**Issue by CookSleep** [open-webui/open-webui#5663]
**Is your feature request related to a problem? Please describe.**
Whisper takes up a lot of memory, but not everyone needs it

**Describe the solution you'd like**
Add an option to completely disable Whisper or include functionality in environment variables to install or enable Whisper

**Describe alternatives you've considered**
It seems to be installed along with the project, and I have no way to prevent this

**Comment by tjbck** [comment]
https://docs.openwebui.com/tutorial/reduce-ram-usage
