### ISSUE TITLE
feat: Set stream capability per model (not global setting)

### ISSUE THREAD

**Issue by juancarlosm** [open-webui/open-webui#5664]
To make OpenAI o1 models to work you now you have to disable model stream globaly:

![image](https://github.com/user-attachments/assets/e1f1ce0a-aa12-4bc3-9e32-55ce60c91966)

I think it will be better if we can set "stream" capability per model:

![image](https://github.com/user-attachments/assets/856dfb0b-5366-4459-935b-58cbe53c34d6)

This way we can make it work and we don't loose stream capabilities for the rest of models that supports it

**Comment by bgeneto** [comment]
@tjbck How can we set stream to false programmatically via manyfold functions (even if the user set it to True)? Is there any way? I need this in order to provide image gen models...
