### ISSUE TITLE
refac: ollama separate endpoint mode

### ISSUE THREAD

**Issue by rampageservices** [open-webui/open-webui#5680]
**Is your feature request related to a problem? Please describe.**
I'd like to use the same Open WebUI instance with two different Ollama servers, one remote and one local. The remote server may not always have a connection. If the remote server is inaccessible and both local and remote API endpoint connections are set in the admin settings then Open WebUI will become unresponsive for sometime until it realizes the connection does not exist. I have to navigate through multiple windows in order to disable the remote server.

**Describe the solution you'd like**
I'd like the model selector to allow me to show me which endpoints are active and which models are available from those endpoints.

**Describe alternatives you've considered**
I'm considering having two Open WebUI instances, one solely for remote and one solely for local as to not impede my productivity if I just need to try something local and offline.

**Additional context**
Open WebUI has the ability to do [load balancing](https://docs.openwebui.com/tutorial/ollama/) but if I am using a remote server for larger models, the request may run locally instead also causing productivity loss.

**Comment by rgaricano** [comment]
I'm not very familiar with that project, but I think the pipelines are designed for these functions,
create a pipeline with a valve for each ollama connection ( https://github.com/open-webui/pipelines/blob/main/examples/pipelines/providers/ollama_manifold_pipeline.py ) and do a monitoring of servers process (as is done  in https://github.com/open-webui/pipelines/blob/main/examples/pipelines/providers/mlx_manifold_pipeline.py ) for on/offline detection, more specific balance,...

**Comment by tjbck** [comment]
You can now disable the default ollama load balancing by specifying the prefix id for each endpoints like such:

![image](https://github.com/user-attachments/assets/38644c8e-e8be-4db4-b08d-180a608386cb)

![image](https://github.com/user-attachments/assets/46c7366d-d7d0-47c2-a58b-e69a85ac16c5)

![image](https://github.com/user-attachments/assets/6419928e-5da9-4de7-a0bc-a68049d2322c)


Testing wanted here!

**Comment by rampageservices** [comment]
This really made a bad day brighter. Thank you so much.  I'll be sure to provide feedback soon.
