### ISSUE TITLE
feat: autocomplete suggestions or/and presets for personalizing prompts in chat 

### ISSUE THREAD

**Issue by cxbignekoc** [open-webui/open-webui#5687]
**Is your feature request related to a problem? Please describe.**

Not a Problem but makes it easier for typing and suggesting terms and such things.
It would be nice if, when prompting in the chat, I could get suggestions for word completiton or tags at like four letters, especially for longer words or prompt presets.

**Describe the solution you'd like**

In the Settings i would like to adjust parameters or preset-phrases so that the function becomes active after a certain number of characters and then again after a specified number of additional characters. Adding such long words should also be an option that can be applied directly in the chat.

Presets are like: "translate to english:" what is suggest wenn type "trans" or "eng".
A step further is personalizing Prompts, so the full text is not shown anymore. So in the Chat i type "eng", the background is "translate to english:" And the Chat Window shows just "eng:".

Suggestions could be selected via arrows up and down . The right arrow for leave the selecting popup to type further.

**Additional context**
its common in Coding and Prompting like VS Code, Forge UI
Also In Linux Bash similar to Aliases for personalizing commands.

**Comment by tjbck** [comment]
#5183
