### ISSUE TITLE
Change tab title on chat rename.

### ISSUE THREAD

**Issue by SunkenHero** [open-webui/open-webui#5705]
**Is your feature request related to a problem? Please describe.**
When renaming the chat, the tab title does not change to the new name. A site refresh is needed to update the title.

**Describe the solution you'd like**
The tab title should change to the new chat name when renaming it.

**Describe alternatives you've considered**
...

**Additional context**
![image](https://github.com/user-attachments/assets/62ea2a3c-553b-4606-b964-f4ba5a3b9da3)
![image](https://github.com/user-attachments/assets/6f75ec50-6371-44cb-ad85-6e1fde00e343)
after i renamed the chat to "Test 2", the tab title stays "Test".

**Comment by tjbck** [comment]
Fixed with 0.3.30
