### ISSUE TITLE
Upgrade using pip install caused settings to default back to normal after server restart

### ISSUE THREAD

**Issue by dewrama** [open-webui/open-webui#5709]
# Bug Report
**Please help. Am I doing something wrong? Settings are not saved after pip install upgrade. Tried a few times and server restart seems to default it back and wipe all connections saved.** 

## Installation Method
**pyenv with python 3.11.8 on Ubuntu 24.04
pip install --upgrade open-webui
(also tried pip install --force-reinstall open-webui)**

[Describe the method you used to install the project, e.g., git clone, Docker, pip, etc.]
**The upgrade goes through without any errors and I see the new release notes. If I start the server with open-webui serve, I can log in with my previous account setting. All my connections are gone. When I re-add and re-save, changes are saved for the session. Once I restart the server with open-webui serve again, all the settings are restored back to default (new connections saved are gone). I also noticed that all my api keys generated are gone and reset every time server restarts (not sure if related or if this helps).

Other conversation history seems to be fine.** 

## Environment
v0.3.29
[(latest)](https://github.com/open-webui/open-webui/releases/tag/v0.3.29)

- **Open WebUI Version:** [e.g., v0.3.11]
- **Ollama (if applicable):** [e.g., v0.2.0, v0.1.32-rc1]

- **Operating System:** [e.g., Windows 10, macOS Big Sur, Ubuntu 20.04]
- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]

**Confirmation:**

- [ ] I have read and followed all the instructions provided in the README.md.
- [ ] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [ ] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

[Describe what you expected to happen.]

## Actual Behavior:

[Describe what actually happened.]

## Description

**Bug Summary:**
[Provide a brief but clear summary of the bug]

## Reproduction Details

**Steps to Reproduce:**
[Outline the steps to reproduce the bug. Be as detailed as possible.]

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots/Screen Recordings (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
Fixed with 0.3.30
