### ISSUE TITLE
feat: groupping chats/documents for tagging and deletion

### ISSUE THREAD

**Issue by peperunas** [open-webui/open-webui#571]
**Is your feature request related to a problem? Please describe.**

As of now, it's pretty cumbersome to cleanup old chats. We have to click - one by one - on each chat twice. It would be great to have a "mass select" mode that allows for quick deletion.

**Comment by tjbck** [comment]
Perhaps this is what you're looking for!

<img width="662" alt="image" src="https://github.com/ollama-webui/ollama-webui/assets/25473318/500b58a6-7b99-4bcc-8544-95c6ca714c2e">

**Comment by peperunas** [comment]
Hello, I saw that feature and that's not what I mean.

Please, do not close issues when the discussion is not over.

The point I was making is different: it would be good to select which chats - and not all together - to delete. Batch deletion.

For me the issue should not be closed.

**Comment by tjbck** [comment]
Sure! Feel free to make a PR!

**Comment by peperunas** [comment]
Sorry I did not phrase it properly, my bad. 

I guess that, UI wise, a way would be to have a "select" button on top of the conversation list. Clicking it is going to show up a checkbox on the left of each chat. Once one or more conversations are selected, a red "delete" button would appear near the select one.

Would that work?

**Comment by tjbck** [comment]
<img width="264" alt="image" src="https://github.com/open-webui/open-webui/assets/25473318/bf5888d9-19c7-4763-ad16-41892fd9d56f">

Implemented as shiftKey + hover shortcut on dev!
