### ISSUE TITLE
Swagger docs require an Internet connection

### ISSUE THREAD

**Issue by gaby** [open-webui/open-webui#5714]
# Bug Report

## Installation Method
- Docker

## Environment
- Latest Open-WebUI
- Both Firefox and Chrome

## Expected Behavior:

Visiting the API docs page would render the Swagger page.

## Actual Behavior:

Swagger / API docs do not render.

## Description

**Bug Summary:**
While Open-WebUI relies on FastAPI by default it requires internet to download the JS/CSS files for the Swagger docs.

This is heavily documented here: https://github.com/fastapi/fastapi/issues/608

And can be easily solved by using the `fastapi offline` package here: https://github.com/turettn/fastapi_offline

**Comment by tjbck** [comment]
Will not be using [fastapi_offline](https://github.com/turettn/fastapi_offline) but investigating at the moment.

**Comment by gaby** [comment]
@tjbck There's a solution here that doesnt use a dependency:

https://github.com/fastapi/fastapi/discussions/8500#discussioncomment-5152408

**Comment by tjbck** [comment]
PR welcome!

**Comment by lee-b** [comment]
> @tjbck There's a solution here that doesnt use a dependency:
> 
> [fastapi/fastapi#8500 (comment)](https://github.com/fastapi/fastapi/discussions/8500#discussioncomment-5152408)
> 
> The versions of the .js/.css files prob need to be updated since it was posted 2 years ago.

Would suggest that tracking these updates is important, cybersecurity wise.  The build process should probably pull the latest versions in automatically, subject to subsequent scans.

I tend to agree that using fastapi_offline here would mostly just introduce new supply chain security concerns, no guarantees of any improved maintenance, so that it's probably simpler to maintain this in-project for now.

Longer-term, the solution is probably to raise this issue with the fastapi team, and have them fix it there.

**Comment by gaby** [comment]
> > @tjbck There's a solution here that doesnt use a dependency:
> > [fastapi/fastapi#8500 (comment)](https://github.com/fastapi/fastapi/discussions/8500#discussioncomment-5152408)
> > The versions of the .js/.css files prob need to be updated since it was posted 2 years ago.
> 
> Would suggest that tracking these updates is important, cybersecurity wise. The build process should probably pull the latest versions in automatically, subject to subsequent scans.
> 
> I tend to agree that using fastapi_offline here would mostly just introduce new supply chain security concerns, no guarantees of any improved maintenance, so that it's probably simpler to maintain this in-project for now.
> 
> Longer-term, the solution is probably to raise this issue with the fastapi team, and have them fix it there.

I has been brought up in the fastapi repo multiple times and there's still no built-in way of doing this.

Both Open-WebUI and Ollama use a ton of dependencie, I don't see anyone bringing up the "supply chain" concerns on those.

Whichever solution works, I just want to be able to use Open-WebUI offline as it's README says. That is currently *not* possibly, a lot of features don't work at all.

**Comment by flefevre** [comment]
@gaby for a newbee like me could you give the url to access the initial fastapi of open-webui?
http(s)://localhost:port/XXX ?
Thanks

**Comment by semidark** [comment]
https://docs.openwebui.com/getting-started/advanced-topics/api-endpoints/#swagger-documentation-links

I am also having trouble finding the API Docs in my locally hosted Open-WebUI instance.

http://localhost:3000/api/v1/docs returns 
```
{"detail":"Not Found"}
```

Though the API is working. as described in the Link to the docs.

**Comment by lililililli1** [comment]
是的，在完全断网的情况下webui完全不能使用

**Comment by gaby** [comment]
@semidark I was getting that error until I added an environment variable to docker run:

`-e ENV=dev`

Regardless, the swagger docs or any api docs do *not* load when self-hosted without internet access.

**Comment by gaby** [comment]
Fixed via #7905 released in https://github.com/open-webui/open-webui/releases/tag/v0.5.0
