### ISSUE TITLE
Bug: Call mode still listening after being closed

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [open-webui/open-webui#5738]
# Bug Report

## Installation Method

docker compose

## Environment

- **Open WebUI Version:** 0.3.30
- **Browser (if applicable):** Brave

**Confirmation:**

- [ X ] I have read and followed all the instructions provided in the README.md.
- [ X ] I am on the latest version of both Open WebUI and Ollama.
- [  ] I have included the browser console logs.
- [  ] I have included the Docker container logs.
- [ X ] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Closing the call should stop the recording

## Actual Behavior:

If I say "Can you hear me" after the call was closed I see a new message appear "Can you hear me" then the model starts answering on its own. All this while the call is closed.
 
## Description

**Bug Summary:**
If you resize the window during a call then close the call, it's still listening to you!

## Reproduction Details

**Steps to Reproduce:**
1. Resize your window to be verticalish so that the UI switches to "phone mode"
2. Start a call (the call UI should now take the whole scren)
3. Send one vocal message and wait for its response to finish
4. Resize the window to be horizontal (the UI switches back to desktop mode)
5. Close the call
6. Say 'Can you hear me' out loud.
 
## Additional Information

I've seen it happen multiple times now. This is particularly annoying if you left the window opened and then notice you've been sending messages all along because you were talking with someone. This might also be related to issues where the microphone would stay 'on' after sending a message that was supposed to be fixed some releases ago.

**Comment by tjbck** [comment]
Should be fixed on dev, testing wanted here!

**Comment by thiswillbeyourgithub** [comment]
Thanks! Not available for testing though, just FYI
