### ISSUE TITLE
FR: Floating copy button like the ChatGPT official website

### ISSUE THREAD

**Issue by fangyuan99** [open-webui/open-webui#5767]
**Describe the solution you'd like**
When generating long code, the copy code button will move with the code block generation and stay in the top right corner, so that you don't have to slide to the top to copy the code every time.

Here's how it's implemented on the ChatGPT official website: https://chatgpt.com
![image](https://github.com/user-attachments/assets/c8355f47-b5ff-4794-9ab0-10818327168e)
![image](https://github.com/user-attachments/assets/abc22178-f565-4387-bd1b-bbe8fdf9ca7d)

**Comment by silentoplayz** [comment]
Good suggestion! Perhaps the `Run` button for running code blocks within the chat could also float. And it wouldn't hurt to give the two options (`Run` & `Copy Code`) slightly more spacing between the buttons + an icon before the text label within each button for better visuals. Just my two cents being thrown into the suggestion, as it would be a QOL adjustment that I can hop on board with.

**Comment by tjbck** [comment]
Added to dev!

**Comment by Svyable** [comment]
broken again

**Comment by silentoplayz** [comment]
> broken again

What exactly is "broken again"?
Just like attention, context is also everything.
