### ISSUE TITLE
Paginate conversation

### ISSUE THREAD

**Issue by uhidontkno** [open-webui/open-webui#5778]
**Is your feature request related to a problem? Please describe.**
When having long conversations with an AI model, Open WebUI tends to slow down as the conversation gets longer and longer making new messages appear to take longer and slowing down the UI (eventually leading to the browser freezing)
**Describe the solution you'd like**
Simply paginate the messages (eg. only show 20 messages at a time) to improve performance and load them dynamically similar to how Discord does it

**Comment by uhidontkno** [comment]
Why did this issue get closed? As of the latest version, Open WebUI loads the entire conversation which tanks web performance

**Comment by justinh-rahb** [comment]
I would guess because tjbck would rather fix performance issues at the source than apply bandaid fixes like pagination. Either way, the direction of the project is up to him.

**Comment by tjbck** [comment]
Try updating to the latest, pagination is already implemented.

**Comment by uhidontkno** [comment]
> Try updating to the latest, pagination is already implemented and has been for several versions now.

Docker version seems to be outdated then

**Comment by uhidontkno** [comment]
nevermind

**Comment by uhidontkno** [comment]
my docker container just never updated
