### ISSUE TITLE
UI Lockup on Message Interaction

### ISSUE THREAD

**Issue by chrisoutwright** [open-webui/open-webui#5794]
# Bug Report: UI Lockup on Message Interaction

## Installation Method

- **Method used:** Manual for Win10

## Environment

- **Open WebUI Version:** v0.3.28
- **Ollama Version:** v0.3.11
- **Operating System:** Windows 10
- **Browser:** Version 129.0.6668.71 (Official Build) (64-bit)  , also tried on Edge with same behaviour.

**Confirmation:**

- [x] I have read and followed all instructions provided in the README.md.
- [ ] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior

The chat message should be clickable, allowing interaction without causing the browser to freeze or CPU to spike.

## Actual Behavior

When clicking on a specific message (ID: `6fee83cf-52c6-4c20-bc44-390858f2e848`), the UI freezes, and the CPU usage spikes to 100%. The browser becomes unresponsive until manually stopped.

## Description

**Bug Summary:**
The UI becomes unresponsive when clicking on the last message (`6fee83cf-52c6-4c20-bc44-390858f2e848`) in the chat history, causing a CPU spike and browser freeze. (Multi-Model Messaging used)

## Reproduction Details

**Steps to Reproduce:**
1. Load the attached chat history (file: `chat-export-1727554950475.json`). (not sure if possible via json, but found no other way)
2. Attempt to click on the message with ID: `6fee83cf-52c6-4c20-bc44-390858f2e848`.
3. Observe the UI freezing and Chrome’s CPU usage spiking to 100%.

## Logs and Screenshots

**Browser Console Logs:**
```
Message ID: 6fee83cf-52c6-4c20-bc44-390858f2e848
Stack Trace:
ye (MultiResponseMessages.svelte:191)
c (MultiResponseMessages.svelte:199)
```

**Screenshots/Screen Recordings (if applicable):**
[Attach screenshots or screen recordings if available]

## Additional Information

- This issue seems to be linked to the following snippet in the Svelte component:
   ```html
   <div
      class="snap-center w-full max-w-full m-1 border {history.messages[messageId]
          ?.modelIdx == modelIdx
          ? `border-gray-100 dark:border-gray-800 border-[1.5px] ${$mobile ? 'min-w-full' : 'min-w-[32rem]'}`
          : `border-gray-50 dark:border-gray-850 border-dashed ${$mobile ? 'min-w-full' : 'min-w-80'}`
      } transition-all p-5 rounded-2xl"
      on:click={() => {
          if (messageId != _messageId) {
              let messageChildrenIds = history.messages[_messageId].childrenIds;
              while (messageChildrenIds.length !== 0) {
                  messageId = messageChildrenIds.at(-1);
                  messageChildrenIds = history.messages[_messageId].childrenIds;
              }
              history.currentId = _messageId;
              dispatch('change');
          }
      }}
   ```
- The issue could relate to the logic in `on:click` that handles `messageChildrenIds`, possibly creating an infinite loop or resource lockup.

## Note

Please ensure that the bug report follows the guidelines, including all required details, logs, and reproduction steps. Thank you!

[chat-export-1727554950475.json](https://github.com/user-attachments/files/17176200/chat-export-1727554950475.json)

**Comment by tjbck** [comment]
Good catch, fix on dev! Testing wanted here!
