### ISSUE TITLE
feat:  cleanup unused tags

### ISSUE THREAD

**Issue by explorigin** [open-webui/open-webui#580]
**Is your feature request related to a problem? Please describe.**
The tag interface is not obvious. I was clicking around and ended up creating a tag that didn't apply to any of my chats. Now I have a tag in the nav drawer that won't go away and doesn't describe any of my chats.

**Describe the solution you'd like**
Provide a way to curate unused tags or (even better) automatically clean them up periodically. Some documentation around the tag feature (or tooltips) would be nice.

**Describe alternatives you've considered**
- Ignore the extra tags - Call it OCD, I like my interfaces to be clean and relevant
- Go into the DB and manually remove them - "ain't nobody got time for that"

**Comment by justinh-rahb** [comment]
This feels like a bug of some kind, certainly unintended behaviour at the least. If there's no chat with a given tag in the chats list, the tag should be automatically deleted. IE if the last chat with a given tag is deleted, the tag should be deleted too.

**Comment by explorigin** [comment]
I don't mind calling a bug. It's a matter of perspective since only the UX is mildly broken on a non-critical feature.

**Comment by tjbck** [comment]
Hi, Thanks for the suggestion!  For now, you should be able to remove the unused tag from the sidebar by adding the tag to a random chat and removing it from the chat. Also, Feel free to make a PR!
