### ISSUE TITLE
bug: ReferenceError: Cannot access 'ae' before initialization

### ISSUE THREAD

**Issue by juancarlosm** [open-webui/open-webui#5800]
# Bug Report

Console error when calling function for an ACTION button:

![image](https://github.com/user-attachments/assets/4e636129-4830-45f5-9a52-2480787bbf8b)

console log:
![image](https://github.com/user-attachments/assets/f23d3dd4-ebfe-4e74-94b1-a84b22987d50)

Messages.svelte:
![image](https://github.com/user-attachments/assets/eefaafee-9dbe-4cfe-857b-6fb4c6ff1bf7)

## Environment

- **Open WebUI Version:** 0.3.30

## Changes that creates de error:
**Commit:** https://github.com/open-webui/open-webui/commit/1d225dd804575af9ae5981528dfdce695f7f7040

Version 0.3.29 is working fine.

**Comment by tjbck** [comment]
Good catch, should be fixed on dev, testing wanted here!

**Comment by EtiennePerot** [comment]
I can confirm that this is fixed on dev.
