### ISSUE TITLE
Deleting models from the Web UI does not work if they have been renamed

### ISSUE THREAD

**Issue by robertosw** [open-webui/open-webui#5803]
# Bug Report
When trying to delete a model using the admin panel, this only works if the model has not been renamed. Otherwise the user assigned name will be used in the delete request and an error will pop up that the model could not be deleted.

I added some icons to the models to distinguish between their use cases, so I renamed phi3 from `phi3:14b` to `💬 phi3` and get this error:
![image](https://github.com/user-attachments/assets/610abbad-ef8d-487c-b1d3-18ec6fea0041)

## Installation Method
```shell
docker run \
                              -e OLLAMA_BASE_URL=http://ollama:11434 \
                              --name open-webui -p 8080:8080 --network local-llms \
                              ghcr.io/open-webui/open-webui:0.3.30
```

## Environment

- **Open WebUI Version:** v0.3.30
- **Ollama:** v.0.3.6

- **Operating System:** linux 6.10.11 | NixOS 24.11
- **Browser (if applicable):** Mozilla Firefox 130.0.1

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
  - All ollama versions since 0.3.6 have a bug which leads to segmentation faults
- [ ] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Docker container logs
```shell
INFO  [open_webui.apps.ollama.main] url: http://ollama:11434
ERROR [open_webui.apps.ollama.main] 400 Client Error: Bad Request for url: http://ollama:11434/api/delete
Traceback (most recent call last):
  File "/app/backend/open_webui/apps/ollama/main.py", line 478, in delete_model
    r.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/requests/models.py", line 1024, in raise_for_status
    raise HTTPError(http_error_msg, response=self)
requests.exceptions.HTTPError: 400 Client Error: Bad Request for url: http://ollama:11434/api/delete
INFO:     172.20.0.1:40838 - "DELETE /ollama/api/delete/0 HTTP/1.1" 500 Internal Server Error
INFO  [open_webui.apps.ollama.main] get_all_models()
INFO:     172.20.0.1:40838 - "GET /api/models HTTP/1.1" 200 OK
```

**Comment by tjbck** [comment]
Fixed on dev!
