### ISSUE TITLE
bug: Default Model Setting Inconsistencies in Open WebUI

### ISSUE THREAD

**Issue by silentoplayz** [open-webui/open-webui#5880]
# Bug Report: Default Model Setting Inconsistencies in Open WebUI
### Environment
- **Open WebUI Version:** [v0.3.30 (latest)](https://github.com/open-webui/open-webui/releases/tag/v0.3.30)
- **Installation Method:** Docker Desktop
##
- **Ollama Version:** [v0.3.12 (latest)](https://github.com/ollama/ollama/releases/tag/v0.3.12)
- **Installation Method:** Ollama Windows (preview)
##
- **Operating System:** Windows 11 Pro 24H2, OS build 26120.770, Windows Feature Experience Pack 1000.26100.6.0
- **Browser (if applicable):** Firefox v131.0 (64-bit)
##
### Confirmation
- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.
#
### Description
**Bug Summary:**
Multiple inconsistencies have been discovered in the default model settings across the Open WebUI platform. These issues affect the `Set as default` functionality, Admin account settings, and Whitelisted model constraints.
#
### **Issue 1: Inconsistent Default Model Setting**
When a user sets a model as the default from the chat page's model drop-down selector, the change is not reflected in their Interface settings for the Default Model option. However, if the default model is set from the Interface settings, the update is correctly reflected in both the chat page and the Interface settings.

**Expected Behavior:**
- Setting a model as default from the chat page drop-down selector should update the default model in both the chat page and the Interface settings.

### **Issue 2: Admin Account Settings Not Overriding User Default Model**
Setting the Default Model under the Users tab in an Admin account does not override the user's default model for new chats. Instead, it only updates the user's Interface settings for the Default Model option, requiring the user to manually save the changes.

**Expected Behavior:**
- Setting the Default Model under the Users tab in an Admin account should override the user's default model for new chats, without requiring manual user intervention.

### **Issue 3: Admin Account Model Setting Validation**
An Admin account can set the Default Model under the Users tab to a model not present in the list of Whitelisted models. This results in the default model being cleared in the user's Interface settings for the Default Model option.

**Expected Behavior:**
- The Admin account should only allow setting the Default Model to a model present in the list of Whitelisted models.
- A validation mechanism should be implemented to ensure the selected model is Whitelisted before applying the default model setting.
#
### Reproduction Details
**Steps to Reproduce:**
1. Set a model as default from the chat page's model drop-down selector.
   - The change should be updated in both the chat page and the Interface settings, but it is not.
2. Set the default model from the Interface settings.
   - The change is correctly reflected in both the chat page and Interface settings.
3. As an Admin, set the default model under the Users tab for a user.
   - The setting should override the user's default model for new chats, but it does not.
4. As an Admin, set the default model under the Users tab to a model not present in the list of Whitelisted models.
   - The Admin account should not allow this, but it does, resulting in the default model being cleared in the user's Interface settings.
#
### **Recommendations**
To address these issues, the recommend fixes might be introduced:
- Update the `Set as default` functionality to correctly reflect the default model in both the chat page and Interface settings.
- Enhance the Admin account settings to override the user's default model for new chats without manual user intervention.
- Implement validation mechanisms to restrict the selection of models not present in the list of Whitelisted models.

#
### Note
This bug report aims to provide all necessary information for reproduction and addressing of the issue. If any additional details are required, please let me know.

**Comment by thiswillbeyourgithub** [comment]
I notice those too and it's an issue for my family setup.

**Comment by flefevre** [comment]
What should be also the behaviour for the 'whitelist models' in the interface settings?
When set, should the models for all users and the admins matched the given list in the model selector in chat? (Preferred behaviour)
Or admin user should have all models accessible in the model selector in chat? ( Actual version)

**Comment by silentoplayz** [comment]
> What should be also the behaviour for the 'whitelist models' in the interface settings?
> 
> When set, should the models for all users and the admins matched the given list in the model selector in chat? (Preferred behaviour)
> 
> Or admin user should have all models accessible in the model selector in chat? ( Actual version)

I believe the current functionality of the Admin's ability to whitelist models on a User account level is desired and the preferred behavior.

**Comment by silentoplayz** [comment]
This issue has been closed due to the depreciation of the `Set as default` option found within the `Interface` settings menu and the depreciation of the `Users` tab in the Admin settings menu.

**Comment by neo-pan** [comment]
Hi there,
I've looked through the documentation but couldn't find any information about this: is there still a way for Admin to set Default Models for other users through alternative means or interfaces? This functionality is quite important for our team's workflow.
