### ISSUE TITLE
Make metadata.chat_id available in custom pipeline

### ISSUE THREAD

**Issue by weixu365** [open-webui/open-webui#5883]
**Is your feature request related to a problem? Please describe.**

I'm integrating open-webui with AWS Bedrock Agents using bedrock_agent_runtime.invoke_agent() in a custom pipeline. This method requires a sessionId parameter, as the Bedrock Agent manages the chat session.

I would like to use chat_id as the sessionId, but it's no longer available in the pipeline.pipe() method. The metadata field, where this information was previously stored, was removed 3 months ago in commit [f462744](https://github.com/open-webui/open-webui/commit/f462744#diff-84fe56d58871cf1f81dfe7cc81a247f1f61226cf2a152e95c8ee06c13d83f28fR360).

**Describe the solution you'd like**

I propose restoring the metadata field from the payload at: https://github.com/open-webui/open-webui/blob/main/backend/open_webui/apps/openai/main.py#L383-L384

**Describe alternatives you've considered**

If reintroducing the metadata field could cause other issues, I suggest adding an environment variable, such as `ENABLE_PIPELINE_METADATA`. When this variable is not set or set to false, the default behavior (without metadata) would remain unchanged, while enabling it would send the field to custom pipelines

**Additional context**
None

**Comment by weixu365** [comment]
Solved by adding to a custom field in body:
```
    async def inlet(self, body: dict, user: Optional[dict] = None) -> dict:
        body["pipeline_metadata"] = {"chat_id": body["chat_id"]}

        return body
```

**Comment by codysandahl** [comment]
For future people, if you need to get the extra metadata to the Pipelines server, I wrote a Pipe to package the info into the body and send it to Pipelines.
https://openwebui.com/f/codysandahl/pipeline_enriched_with_metadata
