### ISSUE TITLE
`RESET_CONFIG_ON_START` environment variable appears to reset the whole db

### ISSUE THREAD

**Issue by andrew-stclair** [open-webui/open-webui#5898]
# Bug Report

## Installation Method

Using docker container with an external ollama service running on another host

## Environment

- **Open WebUI Version:** v0.3.30
- **Ollama (if applicable):** v0.3.12

- **Operating System:** Host is Ubuntu 22.04 but open-webui is in a container
- **Browser (if applicable):** N/A

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [X] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

When setting `RESET_CONFIG_ON_START` environment variable to true, only the configuration is reset, leaving users and their permissions, chat history, etc... as they were

## Actual Behavior:

Everything is reset and open-webui behaves like a fresh install

## Description

**Bug Summary:**
the entire database appears to be wiped when `RESET_CONFIG_ON_START` environment variable is set to true, causing everything to be lost including user accounts, permissions, custom models, prompts, documents, tools, and functions to name a few that i have checked. this is not what i would have expected as this used to only reset the configuration that was in the config.json file

## Reproduction Details

**Steps to Reproduce:**

1. setup open-webui docker container following the usual configuration, but also set `RESET_CONFIG_ON_START=True` and mount the container path `/app/backend/data` to a docker volume or host path
2. create a user account following the first setup proccess via the webui, (feel free to also configure a custom model, other users, prompts etc... but not required for reproducing the issue)
3. stop the container and delete it
4. setup the container again as configured in the first step
5. login to webui, it should be following the first time setup process again, this is not expected as the webui.db is in the volume mounted to the host

## Logs and Screenshots

**Browser Console Logs:**
N/A

**Docker Container Logs:**
N/A

**Screenshots/Screen Recordings (if applicable):**
N/A

## Additional Information

My environment is setup with open-webui in a docker container on aws ecs with ollama running on multiple aws ec2 instances inside an auto scaling group with an application load balancer in front for open-webui to connect to, though i do not believe this is part of the bug.

only one open-webui container is running at any time

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by sanebg** [comment]
I have the same exact issue. It's so frustrating. This doesn't happen with any other docker based chat (LobeChat for example)

**Comment by andrew-stclair** [comment]
@sanebg turns out my issue was unrelated to WebUI but was instead the nfs volume i was mounting for the WebUI storage wasn't mounting properly.

I'd suggest filing your own bug report detailing as much as you can about the issue you are experiencing.
