### ISSUE TITLE
enh: expose WHISPER_MODEL env to admin settings

### ISSUE THREAD

**Issue by thiswillbeyourgithub** [open-webui/open-webui#5906]
Hi, Openai just release their latest whisper version. It's not better in ALL languages (heard mixed results about some asian languages but can't evaluate myself) but is faster and more compact. Switching the default to the new v3 version should be very simple. Potentially just switching the model name string and the documentation. [Here's an example using faster-whisper-server](https://github.com/fedirz/faster-whisper-server/issues/93)

Cheers

**Comment by allansouzasnowfox** [comment]
I made some tests here, the experience using the turbo model for STT even for portuguese, that is my main language, is very impressive. I can't wait to use it in openwebui

**Comment by thiswillbeyourgithub** [comment]
> i will work on this. i think it should be user selectable.

I think it already is, sort of, you can change [environment variables](https://docs.openwebui.com/getting-started/env-configuration/)

**Comment by thiswillbeyourgithub** [comment]
> Hi, Openai just release their latest whisper version. It's not better in ALL languages (heard mixed results about some asian languages but can't evaluate myself) but is faster and more compact. Switching the default to the new v3 version should be very simple. Potentially just switching the model name string and the documentation. [Here's an example using faster-whisper-server](https://github.com/fedirz/faster-whisper-server/issues/93)
> 
> Cheers

As I said there and unless I'm mistaken, it's already available on faster whisper

**Comment by allansouzasnowfox** [comment]
Oh, of course! Sorry about that, I have the worst memory. Only just re-read the last message.

**Comment by tjbck** [comment]
Default model will not be changed for the foreseeable future due to the model being much bigger than the current model, however I'll be modifying the audio UI admin settings to allow users to easily change the default whisper model.

**Comment by tjbck** [comment]
![image](https://github.com/user-attachments/assets/60696178-ba40-484d-affa-803594de9755)


Added to dev!

**Comment by ice6** [comment]
@tjbck wonderful feature! just looking forward to it.

**Comment by fedirz** [comment]
@thiswillbeyourgithub FYI, the variable name includes two underscores `__` instead of a single one `_`. So `WHISPER__MODEL` instead of `WHISPER_MODEL`. Letting you know since the issue summary only has a single one.

**Comment by thiswillbeyourgithub** [comment]
> @thiswillbeyourgithub FYI, the variable name includes two underscores `__` instead of a single one `_`. So `WHISPER__MODEL` instead of `WHISPER_MODEL`. Letting you know since the issue summary only has a single one.

Well your repo needs 2 underscores but open-webui only one, as per https://docs.openwebui.com/getting-started/env-configuration/

Or am I missing something?
