### ISSUE TITLE
Ask/Explain tooltip doesn't dissapear properly

### ISSUE THREAD

**Issue by myturnthistime** [open-webui/open-webui#5957]
# Bug Report

## Installation Method

Docker

## Environment

- **Open WebUI Version:** v0.3.11
- **Ollama (if applicable):** latest

- **Operating System:** Latest Arch
- **Browser (if applicable):** Brave [Version 1.70.119 Chromium: 129.0.6668.70 (Official Build) (64-bit)

**Confirmation:**

- [*] I have read and followed all the instructions provided in the README.md.
- [*] I am on the latest version of both Open WebUI and Ollama.
- [*] I have included the browser console logs.
- [] I have included the Docker container logs.
- [*] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

The software is great, thanks to the whole team. It's really minor bug. The new Ask/Explain doesn't seem to disappear properly

## Actual Behavior:

![Screenshot_20241007_054654](https://github.com/user-attachments/assets/44937fb2-eb89-4458-85d5-1ab47c437e06)

Clicking away doesn't disappear it and nothing is highlighted in the second message anymore. Sometimes it also pops up on it's own in the centre of the screen. I was unable to reproduce that in a conversation without personal info in thought.

## Description

**Bug Summary:**
The Ask/Explain tooltip doesn't disappear properly

## Reproduction Details

**Steps to Reproduce:**
Click about a bit randomly to highlight some stuff and it should reproduce. I don't have steps to reproduce the one when I wasn't clicking, just also happened randomly without text selection in a long conversation.

## Logs and Screenshots

**Browser Console Logs:**
usage Object
+layout.svelte:82 usage Object
+layout.svelte:82 usage Object
+layout.svelte:82 usage {models: Array(1)}
+layout.svelte:82 usage {models: Array(1)}
...etc

**Docker Container Logs:**
N/A

**Screenshots/Screen Recordings (if applicable):**
See above

## Additional Information

To the whole team, please keep up the good work. Sorry I'm reporting this so soon after you pushed but I love your software so much I literally am on the latest version as soon as you push it. I appreciate the work you all do SOOOO MUCH.

**Comment by tjbck** [comment]
Should be fixed with 0.3.32, let me know if the issue persists!
