### ISSUE TITLE
[feat] Hope to add code block folding buttons

### ISSUE THREAD

**Issue by kivvi3412** [open-webui/open-webui#5964]
- Currently, the webpage code occupies a large amount of space. It would be helpful to add an option to collapse the code. This way the response can appear shorter, as sometimes when there's a lot of code, scrolling through the chat takes a long time.

Now:
<img width="1392" alt="image" src="https://github.com/user-attachments/assets/72c11b73-88e2-4861-b509-e0261a000887">

The appearance of hope (ChatGPT-NextWeb):
<img width="1001" alt="image" src="https://github.com/user-attachments/assets/0099cb3a-c799-4749-a990-c9f6d069efa3">

**Comment by thiswillbeyourgithub** [comment]
#4427  similarly, I asked for code line wrapping because it's unreadable on phones, tablets and other vertical screens.
