### ISSUE TITLE
In temporary conversation mode, mobile users cannot use the three dots in the top right corner of the interface to reopen the Artifacts function that was closed during the conversation

### ISSUE THREAD

**Issue by CookSleep** [open-webui/open-webui#5974]
# Bug Report

## Installation Method

Docker

## Environment

- **Open WebUI Version:** v0.3.32
- **Operating System:** Ubuntu 22.04
- **Browser (if applicable):** Android Edge 129.0.2792.65

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

When enabling temporary conversation mode on mobile, the three dots in the top right corner should allow reopening of Artifacts that were closed during the conversation.

## Actual Behavior:

There are no three dots in the top right corner of the temporary conversation on mobile.

## Description

**Bug Summary:**
In temporary conversation mode, mobile users cannot use the three dots in the top right corner of the interface to reopen the Artifacts function that was closed during the conversation.

## Reproduction Details

**Steps to Reproduce:**
1. Open Open WebUI on a mobile browser and enable temporary conversation mode
2. Ask LLM to output some HTML code
3. Notice that there are no three dots at the top right corner, so Artifacts cannot be opened

## Additional Information

Although what I'm about to say might not be a bug, I still think it should be improved: allow the three dots on the top right corner to be accessible even when a conversation has not started on mobile. After all, many times I need to add special system prompts rather than using my custom commands.

Thank you!

**Comment by tjbck** [comment]
Added to dev!
