### ISSUE TITLE
enh: chat auto tag

### ISSUE THREAD

**Issue by tjbck** [open-webui/open-webui#5997]

**Comment by TFWol** [comment]
Just a quick note. The side bar may need a way to collapse/resize and/or have a scrollbar for tags so that the chat history list isn't shrunk down so much. At this point, I can only see it.
![image](https://github.com/user-attachments/assets/a6f40fb0-4dbc-42a4-b23b-1df069fa2734)

**Comment by tjbck** [comment]
![image](https://github.com/user-attachments/assets/50200fbb-dc16-43d9-be5a-26fa664e4666)

@TFWol already addressed.

**Comment by TFWol** [comment]
Oh, is that from Dev branch?

**Comment by tjbck** [comment]
@TFWol Yes, I'd appreciate if you could hop on our dev branch so we can iron out all the bugs!

**Comment by tjbck** [comment]
Added to dev!
