### ISSUE TITLE
Urgent: Follow-up on High-Severity Vulnerabilities Reported

### ISSUE THREAD

**Issue by dkonis** [open-webui/open-webui#6010]
Hello, [amit-laish](https://github.com/amit-laish) and I reported two high-severity vulnerabilities over a month ago. Please review the submitted vulnerabilities and contact us so we can remediate them.

**Comment by justinh-rahb** [comment]
Who are you talking to? Read our policy on security vulnerability reporting: https://github.com/open-webui/open-webui/blob/main/docs/SECURITY.md#reporting-a-vulnerability

If you're being ignored, you probably didn't follow policy.
