### ISSUE TITLE
bug: Model IDs appears as hashes in Workspace.

### ISSUE THREAD

**Issue by adan89lion** [open-webui/open-webui#6040]
# Bug Report

## Installation Method

Docker

## Environment

- **Open WebUI Version:** v0.3.32
- **Ollama (if applicable):** v0.3.12

- **Operating System:** Windows 11 23H2
- **Browser (if applicable):** _Universal_ (Chromium-based, Firefox, Safari...)

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Open WebUI should use human-readable model IDs under each model's name.

## Actual Behavior:

Open WebUI shows model hashes under each model's name.

## Description

**Bug Summary:**
Since Open WebUI v0.3.30 (or a Ollama update), Open WebUI shows model hashes instead of human-readable IDs under each model's name in Workspace. If a user wants to check the model ID, they have to edit the model to show a proper ID. For instance, Qwen 2.5 14b is displayed as `9a78d35195bb269e06cd35834290d...` in the models list, but is correctly displayed as `qwen2.5:14b` in edit mode.

## Reproduction Details

**Steps to Reproduce:**
1. Download models.
2. In Open WebUI, open Workspace
3. The model ID is showed as hashes instead of their ID (e.g. `gemma2:27b` or `llama3.2:3b`)
4. Custom models created in Open WebUI are displayed correctly.

## Logs and Screenshots

**Screenshots/Screen Recordings (if applicable):**
![image](https://github.com/user-attachments/assets/196fa56f-8bb0-49e9-a30f-a4041ee2598c)
> Notice that Ollama model IDs are displayed as hashes, whereas a custom model ID is correctly displayed.

![image](https://github.com/user-attachments/assets/9e02fa73-5548-440a-97df-a91effaf124d)
> The model ID is correctly displayed in the edit panel.

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

It seems like this behavior appeared since the v.0.3.30 update. If it's intentional, it might be counter-intuitive since no one can actually read the hashes.

**Comment by tjbck** [comment]
Expected behaviour.
