### ISSUE TITLE
Input box issue in the new UI

### ISSUE THREAD

**Issue by imoyy** [open-webui/open-webui#6042]
## Describe
Wouldn't it be better to set a width limit for the input box in the new UI here? Full doesn't seem very harmonious for the whole page. The shorter one in the picture below is the width of `w-lg`.

![image](https://github.com/user-attachments/assets/8f8b7ec8-209b-49ff-8a6b-089a002e8fb8)

![image](https://github.com/user-attachments/assets/fe2a61b8-906e-4e67-b8c3-af92b9e3f20e)

**Comment by tjbck** [comment]
Refactored
