### ISSUE TITLE
Missing "Scan for documents from DOCS_DIR (/data/docs)" option

### ISSUE THREAD

**Issue by cristovamperes** [open-webui/open-webui#6073]
## Environment

- **Open WebUI Version:** v0.3.32
- **Ollama (if applicable):** 0.3.9
- **Operating System:** Linux (docker running on server)
- **Browser (if applicable):** Microsoft Edge (client)

## Expected Behavior:

Map a host folder containing docs to webui docker container and scan for use with the models.

## Actual Behavior:

There's no  Scan button on Settings > Documents

**Comment by tjbck** [comment]
<img width="942" alt="image" src="https://github.com/user-attachments/assets/65d6c98a-737d-4948-8847-378e37abcfe4">

**Comment by cristovamperes** [comment]
Using file upload and/or file directory syncing makes the files duplicates as it will be saved again, through the UI, correct?

**Comment by tjbck** [comment]
It will be removed then added, before the update with `DOCS_DIR` it used to just add without removing anything.

Using API will be considered as a best practice for `DOCS_DIR` replacement, please refer to our docs here: https://docs.openwebui.com/api/#-retrieval-augmented-generation-rag

**Comment by poweredbycoffee** [comment]
How do i use file directory syncing?
