### ISSUE TITLE
feat: monitoring dashboard

### ISSUE THREAD

**Issue by yeahdongcn** [open-webui/open-webui#609]
**Is your feature request related to a problem? Please describe.**
In serving multi-models, I'd like to see the GPU metrics through UI.

**Describe the solution you'd like**
I have done some experiments in my repo [OllamaStack](https://github.com/yeahdongcn/OllamaStack), but the metrics couldn't reflect enough information, and the whole setup is somewhat complicated.

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by jnkstr** [comment]
Yes, as an addition to that you could also implement a total/monthly tokens used per user/of all users in the dashboard.

**Comment by tjbck** [comment]
Closing in favour of #1450, Let's continue our discussion there!
