### ISSUE TITLE
🐛 Settings Voices menus show multiple instances of the same voice

### ISSUE THREAD

**Issue by thinkyhead** [open-webui/open-webui#6113]
# Bug Report

## Installation Method

Installed from the shell on macOS Sequoia within a Miniconda environment.

## Environment

- **Open WebUI Version:** v0.3.32
- **Operating System:** macOS Sequoia
- **Browser (if applicable):** Safari

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Should see only one instance of each distinct voice in Settings panels Voices menus.

## Actual Behavior:

Multiple instances of each voice is shown in Settings panels Voices menus.

## Description

**Bug Summary:**
Voices menus in the Settings panels have multiple instances of the same voice.

## Reproduction Details

**Steps to Reproduce:**
Install Open-WebUI on current macOS, enable TTS, open up Voices menus.

## Logs and Screenshots

![image](https://github.com/user-attachments/assets/a6b377e4-c2b5-402d-b8fb-407480045e46)

**Comment by tjbck** [comment]
![image](https://github.com/user-attachments/assets/8e83110f-c3a7-4b8f-b2b8-a7a9b925c7ac)

**Comment by thinkyhead** [comment]
The list has always looked fine in the User Settings >  Audio panel. But even with the latest version it still repeats names (without any parenthetical extras) in the Admin > Settings > Audio > Web API voices list as shown above. Note that I am running on a case-insensitive file system, if that makes any difference.
