### ISSUE TITLE
can't ues mysql database

### ISSUE THREAD

**Issue by JiangYeming** [open-webui/open-webui#6132]
I want to use the external database mysql. The DATABASE_URL configuration is as shown in the figure. When running the program, an error is reported: "cannot access local variable 'db' where it is not associated with a value". What is the problem?
![20241012074441](https://github.com/user-attachments/assets/8a107ba6-ca11-4441-8d5c-74315faeef95)

In addition, how to set the database name when using milvus vector database?
![图像_2024-10-12_075133141](https://github.com/user-attachments/assets/672b9b9a-3f2c-4d26-9958-4a4065692720)

**Comment by tjbck** [comment]
mysql is not supported.

**Comment by JiangYeming** [comment]
Using postgresql, the same error occurs

**Comment by andreclaudino** [comment]
Yes, I have the same problem using postgres, which is suposed to be supported.
