### ISSUE TITLE
feat: per-chat and/or per-model system prompt

### ISSUE THREAD

**Issue by lainedfles** [open-webui/open-webui#619]
**Describe the solution you'd like**
Enable unique system prompt per-chat and/or per-model. This will allow for flexibility when working with multiple models.

**Comment by jukofyork** [comment]
Yeah, per-model settings would be good too:

- Coding models need a really small temperature and a repeat penalty of just a fraction over 1.0 to work properly.
- Story generation models need a much higher temperature and repeat penalty.
- General purpose models need something in between.

**Comment by jcdiv47** [comment]
I was wondering if it could be like the Modelfiles but the prompt version of it, i.e., one could import/export/create/discover all sorts of pre-set prompts and/or parametes setting. In the meantime, just like the llm model selection for each chat, there could be an entry where prompts could be selected for different chats as well.

**Comment by minhhungit** [comment]
ChatTemplate or ChatProfile is good name I guess

**Comment by tjbck** [comment]
Per model config has been added to our dev branch!

**Comment by tjbck** [comment]
![image](https://github.com/open-webui/open-webui/assets/25473318/f274ae95-e6bc-422f-af7e-d5e020418ecc)


Per chat config feature has been added to our dev branch as "Chat Controls"!
