### ISSUE TITLE
Hidden models are still showing in `Settings/Interface` for selecting default model.

### ISSUE THREAD

**Issue by kevinleeex** [open-webui/open-webui#6197]
# Bug Report

## Installation Method

1. Clone the repo.
2. Run `npm run dev` for front-end, and run `./dev.sh` for back-end.

## Environment

- **Open WebUI Version:** v0.3.32
- **Ollama (if applicable):** does not apply.

- **Operating System:** macOS Sonoma 14.6.1
- **Browser (if applicable):** does not apply.

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Those models which are opted as hidden should not be presented to users at any place.

## Actual Behavior:

Those models which are hidden by admin in Workplace are still presenting in `Settings/Interface` when selecting the default model.

## Description

**Bug Summary:**
Those models which are opted as hidden should not be presented to users at any place.

## Reproduction Details

**Steps to Reproduce:**
1. Logged in as `admin`, go to Workspace and hide some of your ollama models.
2. Go to User Settings -> Interface -> Select a Model.
3. Those hidden models are still seeable to users. 

## Logs and Screenshots

**Screenshots/Screen Recordings (if applicable):**
![image](https://github.com/user-attachments/assets/f11c52a0-4aa3-419a-9d08-eb2ac645a79e)
**Mark two models as hidden**

![image](https://github.com/user-attachments/assets/316b0ddd-1816-4728-a463-59c66e9ba1d6)
**These two models are still presenting to users when selecting a default model.**

![image](https://github.com/user-attachments/assets/7c491399-bfc3-4cb3-83c0-83c03312a219)
**These two models are hidden in the home chat view, which is considered as expected.**

## Additional Information

I'll raise a PR to resolve the issue, please help review, thank you!

**Comment by tjbck** [comment]
This is an expected behaviour, they're only hidden from the selector and they're still usable for the admins.
