### ISSUE TITLE
enh: allow disabling openwebui community

### ISSUE THREAD

**Issue by g4challenge** [open-webui/open-webui#6198]
# Feature Request

**Is your feature request related to a problem? Please describe.**  
I'm obsessed about cleanliness and a little frustrated when the OpenWebUI community interface clutters my browser, making it look less organized and harder to navigate, two models, my rules.

**Describe the solution you'd like**  
I would like an option to disable the OpenWebUI community feature to achieve a cleaner and more streamlined browser interface.

**Describe alternatives you've considered**  
I've considered hiding individual elements manually, but this doesn't fully remove the clutter or provide a consistent clean look.

**Additional context**  
Disabling this feature would enhance user experience by reducing distractions. A toggle option in settings would be ideal for users who prefer a minimalistic interface.

**Comment by tjbck** [comment]
Not entirely sure what you meant here, but if you'd like to disable the chat share option you can do so from here.


<img width="1205" alt="image" src="https://github.com/user-attachments/assets/9e5096f8-f25c-4f41-84ca-4890425fbb9e">

**Comment by g4challenge** [comment]
<img width="546" alt="image" src="https://github.com/user-attachments/assets/91cbf856-6b3c-4ce3-8b67-ebea6e96eb8a">
