### ISSUE TITLE
issue: youtube video errors

### ISSUE THREAD

**Issue by zabirauf** [open-webui/open-webui#6208]
# Bug Report

## Installation Method

Installed using Docker

## Environment

- **Open WebUI Version:** 0.3.32
- **Ollama (if applicable):** 0.3.12

- **Operating System:** Ubuntu 22.04
- **Browser (if applicable):** Safari on Mac 15.0.1

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [X] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [X] I have included the Docker container logs.
- [X] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Expect the Youtube video info to be extracted

## Actual Behavior:

Something went wrong :/ Exception while accessing title of https://www.youtube.com/watch?v=LJbUaciFdV8. Please file a bug report at https://github.com/pytube/pytube

## Description

**Bug Summary:**
Using #youtubeurl pretty consistently runs into following error

```
Something went wrong :/ Exception while accessing title of https://www.youtube.com/watch?v=LJbUaciFdV8. Please file a bug report at https://github.com/pytube/pytube
```

## Reproduction Details

**Steps to Reproduce:**
1. Copy a Youtube URL e.g. https://www.youtube.com/watch?v=LJbUaciFdV8
2. In OpenWebUI add it #https://www.youtube.com/watch?v=LJbUaciFdV8which gets detected as Youtube URL
![image](https://github.com/user-attachments/assets/6a598bba-4d8d-4822-9b23-1b36eb173ff3)
3. Press Enter

## Logs and Screenshots
![Screenshot 2024-10-15 at 20 49 37](https://github.com/user-attachments/assets/85ec0068-aa37-4f07-94fb-875c1f00a1a1)

**Docker Container Logs:**

```
INFO:     100.85.106.59:0 - "POST /retrieval/api/v1/process/youtube HTTP/1.1" 200 OK
ERROR [open_webui.apps.retrieval.main] Exception while accessing title of https://youtube.com/watch?v=LJbUaciFdV8. Please file a bug report at https://github.com/pytube/pytube
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pytube/__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/backend/open_webui/apps/retrieval/main.py", line 925, in process_youtube_video
    docs = loader.load()
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_community/document_loaders/youtube.py", line 258, in load
    video_info = self._get_video_info()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_community/document_loaders/youtube.py", line 325, in _get_video_info
    "title": yt.title or "Unknown",
             ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytube/__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=LJbUaciFdV8. Please file a bug report at https://github.com/pytube/pytube
INFO:     100.85.106.59:0 - "POST /retrieval/api/v1/process/youtube HTTP/1.1" 400 Bad Request
```

**Comment by thiswillbeyourgithub** [comment]
Wouldn't it be better if open-webui used [ytdlp](https://github.com/ytdl-patched/ytdl-patched)?  I've had far better results with it for fetching youtube data.

**Comment by tjbck** [comment]
Seems like pytube library is being unmaintained at the moment, PR welcome!

**Comment by rgaricano** [comment]
> Seems like pytube library is being unmaintained at the moment, PR welcome!

maybe pytubefix? (more update lib)
https://github.com/JuanBindez/pytubefix
https://pypi.org/project/pytubefix/

**Comment by Varming73** [comment]
I have a similar problem (and I understand it's because of the usuage of pytube)

```
INFO:     87.104.45.18:0 - "POST /retrieval/api/v1/process/youtube HTTP/1.1" 400 Bad Request
DEBUG [open_webui.main] Commit session after request
ERROR [open_webui.apps.retrieval.main] Exception while accessing title of https://youtube.com/watch?v=fJszPAk-WHk. Please file a bug report at https://github.com/pytube/pytube
Traceback (most recent call last):
  File "/usr/local/lib/python3.11/site-packages/pytube/__main__.py", line 341, in title
    self._title = self.vid_info['videoDetails']['title']
                  ~~~~~~~~~~~~~^^^^^^^^^^^^^^^^
KeyError: 'videoDetails'

During handling of the above exception, another exception occurred:

Traceback (most recent call last):
  File "/app/backend/open_webui/apps/retrieval/main.py", line 925, in process_youtube_video
    docs = loader.load()
           ^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_community/document_loaders/youtube.py", line 258, in load
    video_info = self._get_video_info()
                 ^^^^^^^^^^^^^^^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/langchain_community/document_loaders/youtube.py", line 325, in _get_video_info
    "title": yt.title or "Unknown",
             ^^^^^^^^
  File "/usr/local/lib/python3.11/site-packages/pytube/__main__.py", line 346, in title
    raise exceptions.PytubeError(
pytube.exceptions.PytubeError: Exception while accessing title of https://youtube.com/watch?v=fJszPAk-WHk. Please file a bug report at https://github.com/pytube/pytube
```

**Comment by Varming73** [comment]
I would like to test if needed, just tell me what you need me to do. Am running dockerized so that might limit it a bit.

**Comment by tjbck** [comment]
Directly using yt-dlp sounds like would be the best option here like @thiswillbeyourgithub suggested. PR welcome!

**Comment by grigio** [comment]
+1 currently I'm using a workaround with`yt-dlp`

**Comment by VideoFX** [comment]
I am also getting this error lately. Is there any more specifics/help on a fix/workaround?

**Comment by tjbck** [comment]
Should be fixed on dev!

**Comment by spammenotinoz** [comment]
> Should be fixed on dev!

Thank-you, confirming that YouTube is working fine in dev.
