### ISSUE TITLE
user name not displayed properly in the chat when model name is changed in workspace

### ISSUE THREAD

**Issue by yz342** [open-webui/open-webui#6226]
## Environment

- **Open WebUI Version:** [e.g., v0.3.12]

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [X] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [X] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Hello, Last Name, First Name (in welcome message)

## Actual Behavior:

Model Name ((in welcome message))

## Description

**Bug Summary:**
user name not displayed properly in the chat when model name is changed in workspace

## Reproduction Details

**Steps to Reproduce:**
add ollama API or openai API in connection
Go to workspace, change the model name
Welcome message changed to model name

## Logs and Screenshots
![Screenshot 2024-10-16 095210](https://github.com/user-attachments/assets/2fa7e712-d4b3-4693-b1d4-2ae86a5e5a21)

**Comment by tjbck** [comment]
Expected Behaviour
