### ISSUE TITLE
feat: Enhance delete conversation workflow with keyboard shortcuts

### ISSUE THREAD

**Issue by MurphyLo** [open-webui/open-webui#6244]
I would like to suggest an enhancement to the delete conversation workflow for a more consistent and efficient use. Currently, the `ctrl + shift + delete` keyboard shortcut triggers the delete conversation confirmation modal, which is a great feature. However, it would be even more efficient if we could also confirm the deletion by pressing the `enter` key within the modal.

Here is a suggested modification:

```svelte
<DeleteConfirmDialog
    bind:show={showDeleteConfirm}
    title={$i18n.t('Delete chat?')}
    on:confirm={() => {
        deleteChatHandler(deleteChat.id);
    }}
    on:keydown={(event) => {
        if (event.key === 'Enter') {
            event.preventDefault();
            deleteChatHandler(deleteChat.id);
        }
    }}
>
    <div class="text-sm text-gray-500 flex-1 line-clamp-3">
        {$i18n.t('This will delete')} <span class="font-semibold">{deleteChat.title}</span>.
    </div>
</DeleteConfirmDialog>
```

I am not entirely sure if this implementation is feasible, but it should provide a good starting point for discussion.

<img width="1324" alt="image" src="https://github.com/user-attachments/assets/3702509e-235b-4d9f-b464-49e1a33cc6ac">

**Comment by flefevre** [comment]
Would it be possible also to add a delete button the message generated by the LLM.
There is small delete button for the human input but not for the answer by the LLM.
Thanks

**Comment by silentoplayz** [comment]
> Currently, the ctrl + shift + delete keyboard shortcut triggers the delete conversation confirmation modal, which is a great feature.

Ctrl+Shift+Delete on my keyboard prompts me to `Clear browsing data and cookies` on Firefox v131.0.3 (64-bit), which is the latest version as of the time of me making this comment.

**Comment by tjbck** [comment]
Added to dev!

**Comment by silentoplayz** [comment]
> Added to dev!

I can confirm `Ctrl+Shift+Delete` now prompts me to delete a chat as expected on Firefox browser and pressing `Enter` confirms the deletion of the chat as expected.
