### ISSUE TITLE
feat: clone modelfiles for new model creation

### ISSUE THREAD

**Issue by Geezus42** [open-webui/open-webui#625]
**Is your feature request related to a problem? Please describe.**
A way to easily duplicate saved modelfiles, within the UI. This would be useful in testing different models with otherwise the same configuration. I find it annoying having to manually copy the system prompt and fill in all the other information just to try different models with the same configuration otherwise. Especially since you can't save an incomplete modelfile. 

**Describe the solution you'd like**
A duplicate button that takes you to an edit screen with all of the existing modelfile information already filled in, so you can simply make the adjustments you want and save. 

**Describe alternatives you've considered**
Are there any?

**Comment by tjbck** [comment]
Added with #790, let us know if you encounter any issues!

![image](https://github.com/open-webui/open-webui/assets/25473318/257d3a1e-5885-42f9-be8c-d788f550c38f)

**Comment by heblol** [comment]
Hi @tjbck! thank you for this reply. I found out that only Admin users are able to upload a JSON to the workspace. Do you happen to know if a normal "USER" is also able to do this?
