### ISSUE TITLE
Knowledge Upload / docs/embedding/vector db (chromadb.sqlite3) creates Duplicate embedding

### ISSUE THREAD

**Issue by quantumalchemy** [open-webui/open-webui#6252]
# Bug Report

=
## Installation Method
Docker: ghcr.io/open-webui/open-webui ghcr.io/open-webui/open-webui:dev / 

## Environment

- **Open WebUI Version:** v0.3.32

- **Operating System:** [e.g., docker cont.]
- **Browser (if applicable):** [e.g., Chrome / Firefox latest]

## Expected Behavior:

One collection db / embedding per document

## Actual Behavior:

2 collections / Duplicate embedding per document
see screenshots

## Description

**Bug Summary:**
Workspace
Knowledge
Upload --> Creates Duplicate embeddings

## Reproduction Details
**Steps to Reproduce:**
Workspace
Knowledge
Upload --> 

## Logs and Screenshots
sqlite db showing dups 
![sqlite_dups](https://github.com/user-attachments/assets/916caceb-453d-4c72-9a8c-c22e8d4d0804)
vector_db showing 2 
![vector_db](https://github.com/user-attachments/assets/346f261b-1cce-46b3-b170-aa9ab9f20ca4)

**Comment by tjbck** [comment]
One's for the file itself, another's for the collection.
