### ISSUE TITLE
enh: prompt auto completion

### ISSUE THREAD

**Issue by tjbck** [open-webui/open-webui#6276]

**Comment by tjbck** [comment]
![image](https://github.com/user-attachments/assets/78eb56f2-7796-4231-aa8c-c678c845468f)

Added to dev.

**Comment by codeMonkey-shin** [comment]
how to disable?

**Comment by PeterMinin** [comment]
To disable, go to [your user pic] > Admin panel > Settings > Interface, find "Autocomplete Generation".
There's also apparently an option to limit autocomplete to prompts shorter than a threshold.

**Comment by Mavyre** [comment]
> is there a way to use the generated autocomplete prompt?

Tab, didn't found how on mobile

**Comment by febryanvaldo** [comment]
There is no Autocompletion Generation setting in the Interface menu. How to disable it? or set the threshold for it? @PeterMinin

**Comment by PeterMinin** [comment]
@febryanvaldo You're probably not looking in the Admin Panel.

**Comment by febryanvaldo** [comment]
Ah yes. Actually there are 2 Interface. From settings > Interface, and Admin Panel > Settings > Interface.
