### ISSUE TITLE
Add a button to show the original document from knowledge collection view

### ISSUE THREAD

**Issue by NordMike** [open-webui/open-webui#6284]
# Feature Request

**Is your feature request related to a problem? Please describe.**
In the knowledge collection view while inside a collection I can select a document from the list on the left and see its recognized text on the right. But I couldn't find a way to see the original document. 

**Describe the solution you'd like**
I'd like to have a button to open the original document besides the title above the recognized text in Workspace -> Knowledge collections -> Collection.

**Describe alternatives you've considered**
open-webui is already able to show original documents from the chat view. If LLM used any document there are links at the bottom of the reply which open a citation pop-up with links to original documents.

**Additional context**
The version of open-webui I've tried is 0.3.32. I've tried to upload only PDF files.

**Comment by tjbck** [comment]
![image](https://github.com/user-attachments/assets/f487e95a-fe6c-4e86-a1df-595ace7d4131)

Added to dev.
