### ISSUE TITLE
Could support lower version of firefox?Such as firefox 52.0

### ISSUE THREAD

**Issue by winger1982-lee** [open-webui/open-webui#6301]
# Bug Report

when open the webui on low version of firefox, it could not show the right login page but stop on the logo page. It seems could not run on lower version of firefox such as 52.0 due to the js issue. Can anyone help me because in my working environment there is limited to use higher version of firefox or chrome. Please!

## Installation Method

I installed it by pip and by source code.

## Environment

Open WebUI Version:** [e.g., v0.3.32]

Operating System: [Windows 10,  Ubuntu 20.04]
Browser :** [Firefox 52.0]

**Confirmation:**

- [ ] I have read and followed all the instructions provided in the README.md.
- [ ] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [ ] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Could use lower version of firefox such as 52.0

## Actual Behavior:
stop at logo page and there is js error 

## Logs and Screenshots
![1729475450100](https://github.com/user-attachments/assets/bd920b84-336f-4c2b-b273-f67e5eb97fdd)

**Browser Console Logs:**
SyntaxError: expected expression, got '.'
SyntaxError: expected expression, got keyword 'import'

**Screenshots/Screen Recordings (if applicable):**
![1729475450100](https://github.com/user-attachments/assets/bd920b84-336f-4c2b-b273-f67e5eb97fdd)

**Comment by tjbck** [comment]
Won't be officially supported, but if there is a quick fix, PR welcome.
