### ISSUE TITLE
feat: Permitting user access to Workspace elements

### ISSUE THREAD

**Issue by pikaro** [open-webui/open-webui#6330]
# Feature Request

**Is your feature request related to a problem? Please describe.**
We're currently deploying Open WebUI as an org-internal platform in an IT company. Our users are developers and can be trusted to configure models or knowledge, but should not have access to functions or system administration. There is currently no way to enable such a trust model.

**Describe the solution you'd like**
Environment variables like `ALLOW_USER_WORKSPACE_MODELS` or `ALLOW_USER_WORKSPACE_FUNCTIONS` = `(True|False)` could be added to configure this behavior. The workspace bar / elements would be displayed conditionally and the respective API endpoints would be switched to respect these env variables.

**Describe alternatives you've considered**
A feature request for a solution involving user team creation exists (https://github.com/open-webui/open-webui/issues/2924), but it is much more involved. The two wouldn't necessarily conflict, allowing the admin to use a simpler permission model if teams are not desired.

**Additional context**
I would be willing to tackle this, but would like to receive a comment on whether there are potential stoppers that a cursory read of the code has not revealed or if this does not match your vision for the project.

**Comment by tjbck** [comment]
https://github.com/open-webui/open-webui/issues/2924
