### ISSUE TITLE
Dev branch - Default model selection not working

### ISSUE THREAD

**Issue by ajikmr** [open-webui/open-webui#6331]
# Bug Report

There seems to be a bug in dev branch. Default model is not getting selected. Instead Arena Model is displayed.

## Installation Method

Ubuntu 22.04
Docker build using dev branch

## Environment

- **Open WebUI Version:** docker built from dev branch
- **Ollama (if applicable):** latest

- **Operating System:** Ubuntu 22.04
- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]

**Comment by tjbck** [comment]
Unable to reproduce.
