### ISSUE TITLE
feat: prompt token/s

### ISSUE THREAD

**Issue by robertvazan** [open-webui/open-webui#634]
**Is your feature request related to a problem? Please describe.**
Perf info under chat response shows response speed in tokens/sec, but prompt processing speed is only shown as token count and total time.

**Describe the solution you'd like**
Show tokens/sec for prompt processing too.

**Comment by tjbck** [comment]
Feel free to make a PR!

**Comment by bolavefasfas** [comment]
+1 Need token per second in the bottom of the webui like bottom left or right would be helpful.

Love the project.

**Comment by tjbck** [comment]
@dannyl1u here's another good first issue
