### ISSUE TITLE
Chat Folder renaming broken on Firefox

### ISSUE THREAD

**Issue by PretzelVector** [open-webui/open-webui#6414]
# Bug Report

## Installation Method

Docker

## Environment

- **Open WebUI Version:** v0.3.33

- **Operating System:** NixOS unstable
- **Browser (if applicable):** Librewolf 131.0.3

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Chat folder name changes

## Actual Behavior:

Chat folder name remains the same

## Description

**Bug Summary:**
Chat folder renaming is broken on FIrefox

## Reproduction Details

**Steps to Reproduce:**
Open open-webui on firefox. Double click to rename or use the menu. Press enter after renaming.

## Logs and Screenshots

**Browser Console Logs:**
N/A. There is the suprious "Edit" console log when double clicking (that should probably get cleaned up) but no logs related to the failure nor any related network traffic.

**Docker Container Logs:**
N/A

**Screenshots/Screen Recordings (if applicable):**
N/A

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
Duplicate #6391

**Comment by PretzelVector** [comment]
That's a discussion item. This is a bug report of an issue that repros on firefox. That discussion just contains information confirming that it is a firefox related problem.

Please leave active bugs open so that people can find them.

**Comment by tjbck** [comment]
@PretzelVector We need your help!

![image](https://github.com/user-attachments/assets/1494702c-fbb1-4022-bc73-317b0cb3d985)

**Comment by PretzelVector** [comment]
I don't understand but not my project. You do you.
