### ISSUE TITLE
bug: Cannot Rename Folders And Threads

### ISSUE THREAD

**Issue by bergutman** [open-webui/open-webui#6422]
# Bug Report

## Installation Method

Latest version of OWUI was deployed to a kubernetes cluster using the official helm chart (forked to update to v0.3.33).

## Environment

- **Open WebUI Version:** v0.3.33
- **Ollama (if applicable):** None

- **Operating System:** Linux / iOS / Android / Etc
- **Browser (if applicable):** Latest Firefox Linux, Latest Safari iOS, and latest  Chrome Android

**Confirmation:**

- [ ✅] I have read and followed all the instructions provided in the README.md.
- [ ✅] I am on the latest version of both Open WebUI and Ollama.
- [ ✅] I have included the browser console logs.
- [ ✅] I have included the Docker container logs.
- [ ✅] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

When creating a new folder it should prompt you for a name first. When renaming a folder/thread it should update the value.

## Actual Behavior:

The folder is automatically assigned a name such as "Untitled 1" and editing the name does not actually update the value. Additionally, renaming threads no longer works on v0.3.33 either.

## Description

**Bug Summary:**
Renaming folders (introduced in v0.3.33) does not work. The name is always reset back to "Untitled X." Additionally, renaming threads does not work either. This worked on v0.3.32.

## Reproduction Details

**Steps to Reproduce:**
Deploy OWUI v0.3.33 with the official helm chart, create a new folder/thread, and attempt to rename it.

## Logs and Screenshots

**Browser Console Logs:**
`Edit RecursiveFolder.svelte:285:10`

**Docker Container Logs:**
`INFO:     104.130.246.175:0 - "POST /api/v1/folders/0dda95f3-0d6c-42bd-a3fd-b929a18ab691/update/expanded HTTP/1.1" 200 OK
INFO:     104.130.246.175:0 - "DELETE /api/v1/folders/6f694764-ecb5-48aa-9466-ad1af804bdc4 HTTP/1.1" 200 OK
INFO:     104.130.246.175:0 - "GET /api/v1/chats/all/tags HTTP/1.1" 200 OK
INFO:     104.130.246.175:0 - "GET /api/v1/chats/pinned HTTP/1.1" 200 OK
INFO:     104.130.246.175:0 - "GET /api/v1/chats/?page=1 HTTP/1.1" 200 OK
INFO:     104.130.246.175:0 - "GET /api/v1/folders/ HTTP/1.1" 200 OK`

**Screenshots/Screen Recordings (if applicable):**

https://github.com/user-attachments/assets/d8c71fa6-1e95-4fdc-8754-a97a98eb6114

## Additional Information

Creating folders works and conversations can be dragged to them. The only thing that is not working is renaming.

**Comment by tjbck** [comment]
Should be fixed on dev! Testing wanted!

**Comment by silentoplayz** [comment]
Working fine for me on the latest dev commit.
