### ISSUE TITLE
Increased rate of intermittent javscript errors. v0.3.33

### ISSUE THREAD

**Issue by pipars** [open-webui/open-webui#6444]
# Bug Report

I see an increased rates of javascript errors while I am clicking between Workspace Tabs

## Installation Method

Downgraded from 0.3.34 using Docker Pull

## Environment

- **Open WebUI Version:** v0.3.33
- **Ollama (if applicable):** 0.3.13

- **Operating System:** Ubuntu 24.04
- **Browser (if applicable):** Chrome 130.0.6723.70

**Confirmation:**

- [X ] I have read and followed all the instructions provided in the README.md.
- [ ] I am on the latest version of both Open WebUI and Ollama.
- [X ] I have included the browser console logs.
- [X] I have included the Docker container logs.
- [X ] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

switching between workspace tabs would navigate to appropriate page

## Actual Behavior:

I see either a white page, or a page with OI logo. Navigation to home page then opening Workspace mostly works. Refreshing the same page (in workspaces) mostly causes errors.
Although. I see this error on home page console:
websocket.js:43 WebSocket connection to 'wss://xxx/ws/socket.io/?EIO=4&transport=websocket&sid=tPzruM8CDR-57ijIAAAo' failed: 

## Description

**Bug Summary:**
Clicking on Workspace tabs or refreshing workspace pages produces errors in browser console

## Reproduction Details

**Steps to Reproduce:**
Click between workspace tabs. Refresh browser while on workspace tab.

## Logs and Screenshots

**Browser Console Logs:**
index.JIjGThd1.js:1 Failed to load module script: Expected a JavaScript module script but the server responded with a MIME type of "text/html". Strict MIME type checking is enforced for module scripts per HTML spec.Understand this errorAI
tools:1 Uncaught (in promise) TypeError: Failed to fetch dynamically imported module: https://xxxx/_app/immutable/entry/start.CMhFz1uP.js

**Docker Container Logs:**
INFO:    xxx:30862 - "GET /ws/socket.io/?EIO=4&transport=polling&t=PB8kJXq&sid=1_HENtSoi3WH3HYpAAAg HTTP/1.1" 200 OK
INFO:     xxx:12546 - "POST /ws/socket.io/?EIO=4&transport=polling&t=PB8kPgC&sid=1_HENtSoi3WH3HYpAAAg HTTP/1.1" 200 OK
INFO:     xxx:54932 - "GET /workspace/tools HTTP/1.1" 304 Not Modified
INFO:     xxx:5364 - "GET /static/splash.png HTTP/1.1" 304 Not Modified
INFO:     xxx:26436 - "GET /_app/immutable/chunks/index.CgxZR317.js HTTP/1.1" 304 Not Modified
INFO:     xxx:43376 - "GET /manifest.json HTTP/1.1" 200 OK

## Additional Information

I did not experience this issue on 0.3.32

**Comment by pipars** [comment]
The issue is not happening in 0.3.34

**Comment by rragundez** [comment]
how was this solved? we are experiencing a similar issue.

**Comment by pipars** [comment]
It was resolved in the next version

**Comment by rragundez** [comment]
@pipars  yes, but how?

**Comment by pipars** [comment]
> [@pipars](https://github.com/pipars) yes, but how?

just upgrade to the latest version. This issue is for an earlier version and it was auto-resolved later. I didn't do anything.
