### ISSUE TITLE
feat: Prompt templates should be able to insert clipboard text.

### ISSUE THREAD

**Issue by horiacristescu** [open-webui/open-webui#648]
**Describe the solution you'd like**
The clipboard is often inserted in a prompt as reference material. We should add a {CLIPBOARD} template variable to substitute the clipboard inside the prompt. This would work great for summarization prompts or any prompt taking web cuttings as input, and presumably be easy to implement.

**Comment by tjbck** [comment]
Great idea! I'll take a look and see if it's feasible to implement.

**Comment by tjbck** [comment]
You can now use `{{CLIPBOARD}}` variable! Let me know if you encounter any issues!

**Comment by this-josh** [comment]
@tjbck I'm having trouble with this feature on Mac in Safari and Chrome.
I'm on version `v1.0.0-alpha.101` and have created the following prompt (I've tried `[{{CLIPBOARD}}]` too and that has the same issue)
![SCR-20240222-hywm](https://github.com/open-webui/open-webui/assets/59419126/d777d390-13aa-4158-b3c6-89219f903262)

When I try selecting the prompt nothing happens.
![SCR-20240222-hzal](https://github.com/open-webui/open-webui/assets/59419126/7cb9e1bb-2dfe-4db2-820a-2a016315774c)

I've also gone into my Chrome setting and manually given the URL clipboard access.

I am running open-webui in portainer on a remote machine, I'm not sure if that could be the cause of the problem. 

Looking in my console I see this error message 

![image](https://github.com/open-webui/open-webui/assets/59419126/329da3d0-905c-43bc-bbda-8304711cf1f6)

**Comment by tjbck** [comment]
@this-josh clipboardAPI requires https!

**Comment by this-josh** [comment]
Thanks for your quick reply

Okay we're on the brink of my understanding here, sorry if I say something not quite right. The webui doesn't load at all when I try accessing with https, and my localhost version works with just `http`

working
- `http://localhost:3000/`

Error as above
- `http://155.198...`

Page doesn't load at all
- `https://localhost:3000/`
- `https://155.198...`

**Comment by justinh-rahb** [comment]
You'll need to get the WebUI put behind a reverse proxy that can handle the HTTPS termination and translation to HTTP.

**Comment by elsatch** [comment]
I think there are two ways to move forward and clarify the situation for the final user:
- Include a note in the prompt page, explaining that clipboardAPI requires https. Ideally link to a page in the docs that explains...
- What is the fastest, simplest way to make it work when connecting to a remote server running Open WebUI?

I can volunteer to document this and send a PR to docs.

**Comment by justinh-rahb** [comment]
I would recommend against including detailed instructions for setting up HTTPS directly in the documentation. This is because there are many ways to set up production deployments with HTTPS termination, and I believe that if a user wishes to use Open WebUI at this level, they should already have the necessary knowledge to implement HTTPS termination. Providing this information may actually lead to more questions and confusion for users who are not familiar with these concepts.

**Comment by tbendien** [comment]
@justinh-rahb @tjbck I am looking to provide small GPU OWUI computers to school classrooms and home offices for use on local wifi networks. Any suggestions on how  to implement basic https in that type of local deployment? 
![IMG_7500](https://github.com/open-webui/open-webui/assets/47579015/7e6829d0-75b1-4d96-9097-26ad7578b863)
![IMG_6997](https://github.com/open-webui/open-webui/assets/47579015/b15089ae-4b76-4aa5-8d7e-0d7e88dbfab2)
![IMG_6872](https://github.com/open-webui/open-webui/assets/47579015/09d5b5aa-6e9c-47eb-b03e-1453761ab232)
![IMG_7047](https://github.com/open-webui/open-webui/assets/47579015/21fe68bd-7557-48b4-ae94-5f75b8a74920)
![IMG_7493 (2)](https://github.com/open-webui/open-webui/assets/47579015/e824b9e5-e9eb-4fb8-8e9a-166ec6d88a1c)
