### ISSUE TITLE
Feat: delete parts of conversation.

### ISSUE THREAD

**Issue by sanyi** [open-webui/open-webui#652]
I often face a situation when a discussion diverges because a prompt mistake or necessity of some side questions. This adds unneeded parts to the context that I would rather remove. 

A simple delete X button that would remove a chat bauble all together. I am not sure if would make sense to delete entries in pairs (as prompt and response) or separately.

I think this would greatly help users maintain a shorter and clean context, to avoid context fading, but also for archiving purposes.

**Comment by dannyl1u** [comment]
+1 I agree this would be a useful feature to keep a clean conversation history and avoid having side questions, clarifications, etc. affect the context.

One solution would be to add a deletion button (🗑️) directly into each message's toolbar. This way, when a message is deleted by a user, it would be permanently removed from both the DOM as well as the message history payload in subsequent requests.

However, this could disrupt the conversational context. Specifically, deleting messages from earlier in the conversation could lead to a loss of continuity and make subsequent interactions less coherent. Perhaps we should only allow deletion of the most recent sent message/response?

I'm happy to work on this, @tjbck let me know if you have any thoughts.

**Comment by tjbck** [comment]
@dannyl1u A sensible approach would be only allowing users to remove subsequent messages after the first prompt and removing both user message and response as a pair, ideally we would also want to retain the deleted messages in the history object as well. Just added a button to https://github.com/open-webui/open-webui/tree/delete-message branch, feel free to make a PR!

**Comment by dannyl1u** [comment]
Sounds good, @tjbck is it okay if I push my changes to the `delete-message` branch or should I make a separate branch for the PR?

**Comment by tjbck** [comment]
@dannyl1u whatever is the most convenient for you!

**Comment by dannyl1u** [comment]
@tjbck published my PR, please review when you get the chance, thank you!

**Comment by Happ1ness-dev** [comment]
Hello, is this feature still available? I can't find it on mobile for some reason. 

It's really needed for me because I do a lot of experimenting, and ideally all messages should be deletable. Not just messages from the user or recent ones.

**Comment by quartzar** [comment]
This feature is desperately needed. I cannot even cancel an image generation if it was triggered while the configured image generator was not running.
