### ISSUE TITLE
Bug when setting wrong embedding model and restarting container 

### ISSUE THREAD

**Issue by kim-gtek** [open-webui/open-webui#6533]
Add incompatible embedding model from huggingface, type name into embedding model text area. 

Press download, get the error that says you need to run the code and set the environment variable concerning code to true.

This changes the config in database.
Pull new openwebui, rebuild docker container and run.

Will not launch due to above error.
Container restartes in loop.

TempFix: manually reset embedding model in db.

**Comment by bgeneto** [comment]
Confirmed. Noticed this a long time ago. Forgot to report :-(

**Comment by tjbck** [comment]
Fixed on dev!
