### ISSUE TITLE
[Feature Request] Enhanced Privacy for Knowledge Base Collections/Data through User Access Permissions

### ISSUE THREAD

**Issue by samuelpetermoshi** [open-webui/open-webui#6540]
### Feature Request: Enhanced User Group Management

**Description:**

I would like to propose an enhancement to the user management functionality within Open WebUI. Currently, there is no option to group users and assign them to multiple groups (e.g., Data Science Team, Marketing Team, Data Engineering Team). This feature would significantly improve user organization and access management.

---

**Proposed Feature:**

- Introduce a new column in the user dashboard to create and manage user groups.
- Allow admins to assign users to one or multiple groups easily.
- Ensure that access permissions can be managed at a group level, promoting more efficient access control.

---

**Use Case:**

With the implementation of user groups, the privacy of workspace knowledge bases can be effectively managed. By integrating RAG to access documents and data based on user access groups, we can ensure that:

- Sensitive information is accessible only to authorized users based on their group assignments.
- Knowledge bases can have tailored visibility, allowing specific teams to access relevant documents while maintaining confidentiality for others.
- Teams can collaborate more effectively as they can seamlessly access shared resources specific to their group.

---

**Benefits:**

- Streamlined user management for organizations.
- Enhanced privacy and security of knowledge bases.
- Improved collaboration among team members.
- Easier tracking of user roles and access rights.

---

Thank you for considering this feature!

Images Example:
<img width="1429" alt="Screenshot 2024-10-29 at 17 59 47" src="https://github.com/user-attachments/assets/ab98fd08-2290-4fcc-a6b3-029b88017283">
<img width="1676" alt="Screenshot 2024-10-29 at 17 56 52" src="https://github.com/user-attachments/assets/cb8238ac-008d-42d0-8a69-ca1218212bf5">
<img width="1669" alt="Screenshot 2024-10-29 at 17 50 38" src="https://github.com/user-attachments/assets/2d9225f6-a113-48bd-bd13-8a703b56b17f">

**Comment by tjbck** [comment]
#2924
