### ISSUE TITLE
Missing "All Documents" Option

### ISSUE THREAD

**Issue by tdiprima** [open-webui/open-webui#6564]
**Description:**

In the latest release (v0.3.35) of Open WebUI, the option to search "All Documents" is no longer available when hitting `#` in the user prompt to bring up the list of documents and collections. This option was previously available and was very useful for conducting a broad search across all documents without having to specify individual collections.

**Steps to Reproduce:**

1. Go to the user prompt in Open WebUI v0.3.35.
2. Press `#` to display the list of documents and collections.
3. Observe that the "All Documents" search option is missing.

**Expected Behavior:**

The list of search options should include an "All Documents" option, as in previous versions, allowing users to search across all collections without selecting each individually.

**Current Behavior:**

In v0.3.35, the "All Documents" option no longer appears, limiting the ability to conduct a comprehensive document search.

**Environment:**

- **Open WebUI Version:** v0.3.35 (latest)
- **OS:** macOS 14.1

**Additional Context:**

This change impacts workflows that rely on quickly accessing information across multiple documents without having to manually specify each collection. Please consider reinstating the "All Documents" option or providing guidance on how to achieve this functionality in the latest version.

**Comment by tjbck** [comment]
It’s been deprecated.

**Comment by tdiprima** [comment]
@tjbck I understand it's deprecated and you're not bringing it back.  Could you please tell me why &mdash; it could give me insight into a current issue I'm having.  In searching a collection of over 1000 short documents, it can only "see" 3 of them.  If I ask it about a different document it certainly knows about it.  But it didn't list it in the original search across 1000+ documents.

**Comment by abbaselmas** [comment]
why do you even deprecate the most meaningful feature!
