### ISSUE TITLE
PWA mode not respecting rotation lock - need to change manifest?

### ISSUE THREAD

**Issue by Tycho-S** [open-webui/open-webui#6608]
# Bug Report

## Important Notes

The problem is that with the current manifest orientation setting, the PWA always rotates on android phones in Chrome, even when rotation lock is on.

## Installation Method

docker

## Environment

- **Open WebUI Version:** 0.3.35

- **Operating System:** Ubuntu 22.04
- **Browser (if applicable):** Chrome 130.0 on Mobile (Android 14)

**Confirmation:**

- [X ] I have read and followed all the instructions provided in the README.md.
- [ X] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [X ] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

When rotation is locked, PWA should stay in portrait mode (or landscape if locked in that). And when rotation is unlocked it should rotate.

## Actual Behavior:

PWA rotates on phone even when rotation lock is on. This is annoying because if I hold it sideways (e.g. in bed) it goes to landscape mode.

## Description

I think this is due to an error in the manifest. If it says "orientation: any" like it does now, it always rotates regardless of lock setting. "orientation: natural" should allow it to obey the system rotation lock (rotate if it's unlocked, stick if not)

PS: I checked if this bug was already logged but I only saw ones for the opposite problem.

**Bug Summary:**
## Reproduction Details

**Steps to Reproduce:**
- Install PWA on Chrome
- Lock rotation
- Open PWA
- Rotate phone

**Note:**
Strange enough in Firefox this does not happen. But in Firefox the interactive audio session (the headphone icon) doesn't work properly (it hears itself during playback and thinks you're interrupting it, so I use chrome instead). I'll log a separate ticket for that if needed but I don't normally use FF for PWAs anyway.

**Browser Console Logs:**
I can't, it's mobile chrome, there is no console

**Comment by tjbck** [comment]
Updated on dev to `natural`
