### ISSUE TITLE
webui openapi spec does not pass validation for the /files/$id/content/$file_name endpoint

### ISSUE THREAD

**Issue by mitchty** [open-webui/open-webui#6616]
# Bug Report

## Installation Method

For this I'm using nix flakes but thats not really relevant. I can probably pr a fix if I can get a pointer to where the spec is implemented.

## Environment

- **Open WebUI Version:** 
0.3.35, 0.3.32 may exist earlier but thats all i've tested against so far.
- **Ollama (if applicable):**
n/a

- **Operating System:**
nixos 24.05
- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]
n/a

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [ ] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Should be able to generate openapi libraries from the openapi spec without errors or using --skip-validate-spec. Think all thats really needed is file-name needs to be entered in as a path component to the uri but haven't looked yet. Not sure where those specs are defined in here but willing to fix it and PR a fix.

I snagged the openapi json like so:

https://github.com/mitchty/open-webui-cli/blob/b152431cab01321dd43f14ec63a9e3445ca849d7/bin/openapispecs.sh#L31-L34

```sh
# webui api
webuidir="${destver}/webui"
install -dm755 "${webuidir}"
curl -s "${HOST}/api/v1/openapi.json" -o - | jq > "${webuidir}/openapi.json"
```

Then using that and the latest openapi-generator-cli try to generate specs I get:

```

################################################################################
+ /nix/store/v38wk1ndqfnxinmcnss1akjgvychdkpn-openapi-generator-cli-7.9.0/bin/openapi-generator-cli generate --input-spec openapi/0.3.35/webui/openapi.json --generator-name rust --output api/webui --package-name webui
Exception in thread "main" org.openapitools.codegen.SpecValidationException: There were issues with the specification. The option can be disabled via validateSpec (Maven/Gradle) or --skip-validate-spec (CLI).
 | Error count: 1, Warning count: 0
Errors: 
        -paths.'/files/{id}/content/{file_name}'. Declared path parameter file_name needs to be defined as a path parameter in path or operation level

        at org.openapitools.codegen.config.CodegenConfigurator.toContext(CodegenConfigurator.java:717)
        at org.openapitools.codegen.config.CodegenConfigurator.toClientOptInput(CodegenConfigurator.java:744)
        at org.openapitools.codegen.cmd.Generate.execute(Generate.java:527)
        at org.openapitools.codegen.cmd.OpenApiGeneratorCommand.run(OpenApiGeneratorCommand.java:32)
        at org.openapitools.codegen.OpenAPIGenerator.main(OpenAPIGenerator.java:66)
zsh: exit 1     rebuild-api-crates
```

## Actual Behavior:

[Describe what actually happened.]

## Description

**Bug Summary:**
Webui openapi spec is missing file_name as a path component in the openapi spec for /files/$id/content/$file_name causing code generators to generate invalid code that cannot compile (for rust at least). Without that patch things do indeed not build:

```
error: builder for '/nix/store/ax72jq1idla4dqnxji964y4w6n9jhfh5-owuicli-0.1.0.drv' failed with exit code 101;                                                                       
       last 10 log lines:                                                                                                                                                           
       >                                                                                                                                                                            
       > error[E0425]: cannot find value `file_name` in this scope                                                                                                                  
       >    --> api/webui/src/apis/files_api.rs:230:33                                                                                                                              
       >     |                                                                                                                                                                      
       > 230 |         "{}/files/{id}/content/{file_name}",                                                                                                                         
       >     |                                 ^^^^^^^^^ not found in this scope                                                                                                    
       >                                                                                                                                                                            
       > warning: `ollama` (lib) generated 4 warnings (run `cargo fix --lib -p ollama` to apply 2 suggestions)                                                                      
       > For more information about this error, try `rustc --explain E0425`.                                                                                                        
       > error: could not compile `webui` (lib) due to 1 previous error                                                                                                             
       For full logs, run 'nix log /nix/store/ax72jq1idla4dqnxji964y4w6n9jhfh5-owuicli-0.1.0.drv'.                                                                                  
zsh: exit 1   
```

## Reproduction Details

**Steps to Reproduce:**
Not really a bug with open-webui but the openapi spec itself for the webui api.

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots/Screen Recordings (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Additional Information

For now I'm just hacking the generated code so it actually builds like so by adding it in as a parameter to the method:
https://github.com/mitchty/open-webui-cli/blob/b152431cab01321dd43f14ec63a9e3445ca849d7/patches/webui.patch#L9

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
Expected behaviour here, but feel free to make a PR!

**Comment by mitchty** [comment]
Sounds good, quick question on this function/api path, would this be the appropriate fix for now? It looks more like the file_path is entirely ignored as only the id is used for lookup in the rest of the function. Or should I just change the path to remove everything after {id}? I don't see that uri path variable actually influencing anything and what appears to be happening is openapi considers that a validation failure.

Figure I'd ask prior to shooting off a pull request which way you'd prefer. Or if I am off the reservation entirely, whichever it turns out being. Cheers!

```
diff --git a/backend/open_webui/apps/webui/routers/files.py b/backend/open_webui/apps/webui/routers/files.py
index b8695eb6..96001e48 100644
--- a/backend/open_webui/apps/webui/routers/files.py
+++ b/backend/open_webui/apps/webui/routers/files.py
@@ -274,7 +274,7 @@ async def get_html_file_content_by_id(id: str, user=Depends(get_verified_user)):
 
 
 @router.get("/{id}/content/{file_name}")
-async def get_file_content_by_id(id: str, user=Depends(get_verified_user)):
+async def get_file_content_by_id(id: str, file_name: str, user=Depends(get_verified_user)):
     file = Files.get_file_by_id(id)
 
     if file and (file.user_id == user.id or user.role == "admin"):
```
