### ISSUE TITLE
case sensitivity in model name

### ISSUE THREAD

**Issue by coy247** [open-webui/open-webui#6632]
# Bug Report
I intentionally named my model with a lowercase initial letter. While the model name displays correctly in the models section, it appears incorrectly capitalized on the main splash screen asking "how can I help you today:". The model name on this page should match the model name exactly, preserving the lowercase initial letter.

please and thank you. love what you guys have created here!

just saw the contribution area. I've been reluctant to contribute in fear of messing up, but these bots have given me the confidence to take a stab at it, so i'll give it a whirl!

---

## Installation Method

[Describe the method you used to install the project, e.g., git clone, Docker, pip, etc.]

## Environment

- **Open WebUI Version:** v0.3.35
- **Ollama (if applicable):** 0.3.14
- **Operating System:** macOS 15.1 (24B83)
- **Browser (if applicable):** 15.1 (24B83)

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [ ] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

I expected my model name to reflect correctly when using the bot I created

## Actual Behavior:

the bot's name appears with an inital capital letter.

## Description

**Bug Summary:**
I named my model purposefully with a lowercase initial letter. Although the model name is correctly reflected in the model's directory; when the main splash screen appears with the prompt "how can I help you today:", the bot's name is incorrectly capitalized. The model name on this page should be identical (===) to the active model name, preserving the lowercase initial letter in this case.

## Reproduction Details

create a bot where the name is not capitalized
enter required information
save the model
use the model

## Logs and Screenshots

**Browser Console Logs:**
n/a

**Docker Container Logs:**
working on this...

**Screenshots/Screen Recordings (if applicable):**
working on this...

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
Fixed on dev!
