### ISSUE TITLE
feat: LDAP User management

### ISSUE THREAD

**Issue by this-josh** [open-webui/open-webui#668]
**Is your feature request related to a problem? Please describe.**
Users should be managed via LDAP, similar to [Portainer](https://docs.portainer.io/admin/settings/authentication/ldap)

**Describe the solution you'd like**
LDAP user management implemented

**Describe alternatives you've considered**
- OAUTH
- Microsoft Active directory

I believe LDAP is the best starting point

**Additional context**

One key feature of `ollama-webui` is its ability to have users, but without LDAP this doesn't have same network level utility.

**Comment by jnkstr** [comment]
Yes agree, this would be a use case for us as well.

**Comment by tjbck** [comment]
Related: https://github.com/ollama-webui/ollama-webui/issues/483

**Comment by SurvivaLlama** [comment]
I can help test this.

**Comment by eingemaischt** [comment]
This would be great for us as well - an auth via Header, set by an reverse proxy, would be a great alternative. Then we could add different auth mechanisms (OpenID, LDAP, Kerberos etc) without implementing each of them in webui itself...

**Comment by justinh-rahb** [comment]
> This would be great for us as well - an auth via Header, set by an reverse proxy, would be a great alternative. Then we could add different auth mechanisms (OpenID, LDAP, Kerberos etc) without implementing each of them in webui itself...

Excellent news, this has been implemented:
- #1347

**Comment by Manfredzimmermann** [comment]
How can I connect Open-WebUI with Microsoft Active directory? I'm looking for an excellent solution. A fixed module in Open-WebUI for Active Directory (LDAP) would be a dream

**Comment by hostingnuggets** [comment]
Me too! +100 from me ;-)

**Comment by peske** [comment]
+1

**Comment by sry9681** [comment]
+1

**Comment by lduplaga** [comment]
Would be awesome to have this feature.

**Comment by seal61** [comment]
+1

**Comment by lduplaga** [comment]
I solved my case with Microsoft authentication by this 

https://docs.openwebui.com/tutorial/sso#microsoft

**Comment by seal61** [comment]
> I solved my case with Microsoft authentication by this
> 
> https://docs.openwebui.com/tutorial/sso#microsoft

does not help with local active directory / ldap server sadly, but might be useful for some.

**Comment by WilsonZiweiWang** [comment]
My implementation: https://github.com/WilsonZiweiWang/open-webui/commit/bfe556010bed6e6e4a0a63a9ef1e27fe20e3ca17
It worked in my case with my LDAP server. Feel free to play with it and leave a comment. Thanks.

**Comment by hostingnuggets** [comment]
Bravo @WilsonZiweiWang for your LDAP implementation. @tjbck could @WilsonZiweiWang's code be integrated to this project?

**Comment by tjbck** [comment]
Feel free to make a PR!

**Comment by jhayesdev** [comment]
@WilsonZiweiWang with some refac that might be workable for more servers. Not working on my AD server, but honestly I'm fairly sure it's either a layer8 problem, or we just need more environment variables to tune the (too many) options for LDAP binding, user search and field mappings.

**Comment by justinh-rahb** [comment]
WilsonZiweiWang with some refac that might be workable for more servers. Not working on my AD server, but honestly I'm fairly sure it's either a layer8 problem, or we just need more environment variables to tune the (too many) options for LDAP binding, user search and field mappings.

**Comment by Peter-De-Ath** [comment]
> My implementation: [WilsonZiweiWang@f4e4874](https://github.com/WilsonZiweiWang/open-webui/commit/f4e487480f414f24ff19b0243e6357c0625b330f) It worked in my case with my LDAP server. Feel free to play with it and leave a comment. Thanks.

I wasn't quite able able to get this working out the box, but adding

`LDAP_USER_DN = f'cn={cn},{LDAP_USERS_DN}'`

inside `if uid == form_data.user:`

**Comment by justinh-rahb** [comment]
I got this to work with @Peter-De-Ath's modification on a test LDAP server, but still unable to get working on my (probably misconfigured by my predecessor) AD domain. 

Some notes I'd add:
- This won't interact well with `WEBUI_LOGIN=false`, the email/username and password fields are hidden
- Could we not use the `email` field for login? We already get it from the LDAP server to create the account
- Would prefer if LDAP is enabled that a button be shown in similar style to the OIDC login buttons, hidden otherwise
- May want to be able to configure which field is used for the username

**Comment by WilsonZiweiWang** [comment]
hi all, thanks for testing my code and leaving comments, I have created the PR for this issue: https://github.com/open-webui/open-webui/pull/5056

**Comment by ticoneva** [comment]
> My implementation: [WilsonZiweiWang@f4e4874](https://github.com/WilsonZiweiWang/open-webui/commit/f4e487480f414f24ff19b0243e6357c0625b330f) It worked in my case with my LDAP server. Feel free to play with it and leave a comment. Thanks.

I am getting the following error when I install your fork over the official one:
```
OperationalError: (sqlite3.OperationalError) no such table: config
[SQL: SELECT config.id AS config_id, config.data AS config_data, config.version AS config_version, config.created_at AS
config_created_at, config.updated_at AS config_updated_at
FROM config ORDER BY config.id DESC
 LIMIT ? OFFSET ?]
[parameters: (1, 0)]
```

**Comment by ticoneva** [comment]
> hi all, thanks for testing my code and leaving comments, I have created the PR for this issue: #5056

I tried to install from your fork following the instructions on [Ollama's documentation for git installation](https://docs.openwebui.com/getting-started/#build-and-install-%EF%B8%8F), but I do not see any options to connect to a LDAP server in Admin Panel > Connections. Am I supposed to install it another way?

**Comment by tjbck** [comment]
LDAP support merged to dev. More testing wanted from the community here!

**Comment by arthur-flam** [comment]
Hello! We managed to make it work with LDAP. Thanks a lot for adding this feature.
Some small issues I ran into:
- `Auths.insert_new_auth` only gets `mail`/`hash`/`cn` parameters. Other auth methods also accept a role (default to `pending` otherwise no matter how `DEFAULT_USER_ROLE`  is defined. It's also not possible to add profile picture (although it could be difficult with ldap, at least in my experience with our LDAP, `ldapsearch` returns a path to a temp image file, not a real URL).
- The `LDAP_SEARCH_FILTERS` is always messy to get right. I didn't understand that it already did f`&(LDAP_ATTRIBUTE_FOR_USERNAME={login})({LDAP_SEARCH_FILTERS})`.
In any case testing with `dev` was very easy, amazing work all around.

**Comment by nordy1145** [comment]
I also got LDAP working with a simple ldap filter to a specific group, TLS and no issues authenticating.  The only issue I see is the default Role is Pending instead of User as mentioned above.

**Comment by GabrielRamirez** [comment]
Are the LDAP variables set in the .env file?

**Comment by WilsonZiweiWang** [comment]
> Are the LDAP variables set in the .env file?

You can set initial values to them in the .env file or edit them with the interface

**Comment by SurvivaLlama** [comment]
works great. thank you.

**Comment by VfBfoerst** [comment]
thanks for the implementation :) I also tested it, works like a charm.

**Comment by wixyskywriter** [comment]
would it be possible to share a sample of a working configuration?

**Comment by WilsonZiweiWang** [comment]
> would it be possible to share a sample of a working configuration?

You will need to know how your active directory is configured.

**Comment by wixyskywriter** [comment]
I know, but still not able to integrate and the binding error appearing. If there is a guide or tutorial for setting up AD integration would be helpful to everyone.

**Comment by WilsonZiweiWang** [comment]
> I know, but still not able to integrate and the binding error appearing. If there is a guide or tutorial for setting up AD integration would be helpful to everyone.

The configurations can be very different from case to case, I think first it is best that you let us know what errors you are having. You could create an issue.

**Comment by AndreasUpb** [comment]
Thank you for the hard work! I have the LDAP auth running but wondering how am i able to map different Ldap-Groups to OpenWebUI's Permission-Groups. Is this to customized so that i have to fork or do you see the same use case?

**Comment by nordy1145** [comment]
> Thank you for the hard work! I have the LDAP auth running but wondering how am i able to map different Ldap-Groups to OpenWebUI's Permission-Groups. Is this to customized so that i have to fork or do you see the same use case?

Why not just create a single group and nest groups under that one?

**Comment by AndreasUpb** [comment]
> > Thank you for the hard work! I have the LDAP auth running but wondering how am i able to map different Ldap-Groups to OpenWebUI's Permission-Groups. Is this to customized so that i have to fork or do you see the same use case?
> 
> Why not just create a single group and nest groups under that one?

I already have a meta-group in ldap, so that the login works for both groups. But i want ldap-group-a to have openwebui-permission-group-a (can only access model llamaX) and ldap-group-b to have openwebui-permission-group-b (can also access model gpt4 + working area).

**Comment by scas-johni** [comment]
Out of interest, did anyone get sAMAccountName working for LDAP_ATTRIBUTE_FOR_USERNAME?  Thanks.

Trying filter: `(sAMAccountName=%s)`
