### ISSUE TITLE
feat: search in settings 

### ISSUE THREAD

**Issue by dannyl1u** [open-webui/open-webui#6687]
# Feature Request

**Is your feature request related to a problem? Please describe.**
When changing settings on my mac, I often use the search bar to locate what I'm looking for, something similar in the open-webui settings would be very useful, especially for new users who are unfamiliar with the UI.

**Describe the solution you'd like**
Search bar in the settings tab, similar to the MacOS settings search bar.

**Describe alternatives you've considered**
I'm willing to create a PR for this feature, submitting this issue in case anyone has suggestions on how it would be implemented.

**Additional context**
MacOS settings search
<img width="827" alt="image" src="https://github.com/user-attachments/assets/a29d4df6-3825-4804-95c6-5f61f39d716d">
Chrome settings search
<img width="1624" alt="image" src="https://github.com/user-attachments/assets/80a755d2-3400-4379-a8b2-5fad957cb97c">

**Comment by tjbck** [comment]
Great idea, feel free to make a PR and I'll provide guidance or edit the PR myself where needed!

**Comment by dannyl1u** [comment]
Closing as completed in #6749
