### ISSUE TITLE
Markdown files imported into workspace knowledge strips out important markdown (link urls)

### ISSUE THREAD

**Issue by danielj23** [open-webui/open-webui#6690]
# Bug Report

## Installation Method

git clone

## Environment

- **Open WebUI Version:** [v0.3.35](https://github.com/open-webui/open-webui/releases/tag/v0.3.35)

- **Operating System:**  Windows 10  

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

If I import markdown files into workspace/knowledge for a model, I would expect that a link would get imported with the markdown so that the model has access to the link to provide during prompts.

## Actual Behavior:

Markdown is imported without any actual markdown and only plain text is imported.  When I ask my model for links from the imported knowledge, it doesn't have it because its stripped out during import.

## Description

**Bug Summary:**
Markdown files (.md) imported into workspace/knowledge will not include important knowledge from the markdown file.   

## Reproduction Details
 

**Steps to Reproduce:**
Create a markdown file that contains a proper link.

`Make a link to something [the link](https://microsoft.com)!
This link will not show up once imported into open-webui`

Save the file as test.md
Go to a workspace model and attempt to import test.md into "knowledge"
Try to view the test.md after import and you will not see the https://microsoft.com
Ask your model for the link and it will not know (because it was stripped from import)

**Comment by tjbck** [comment]
Fixed on dev!

**Comment by danielj23** [comment]
sweet
