### ISSUE TITLE
Unable to Bypass SSL Verification when using Web Search

### ISSUE THREAD

**Issue by erussell86** [open-webui/open-webui#6735]
# Bug Report

---

## Installation Method

I installed the latest Docker container (v0.3.35). Everything else, to include directly adding websites to context via `#` works fine.  

## Environment

- **Open WebUI Version:** v0.3.35
- **Operating System:**  Docker is running in Ubuntu server
- **Browser (if applicable):**  Chrome 130.0.6723.70

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [X] I am on the latest version of both Open WebUI and Ollama.
- [] I have included the browser console logs.
- [X] I have included the Docker container logs.
- [X] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

When Openwebui is behind a TLS proxy, and `Bypass SSL verification for Websites` is `On`, it obtains web pages from duckduckgo, attempts to connect to them,  sees that there is a self-signed certificate in the trust chain and ignores it, reading website content despite the self-signed cert. 

## Actual Behavior:

Openwebui fails to read the content from the web pages returned by duckduckgo due to the SSL Verification Error. 

## Description

**Bug Summary:**
When Open Webui attempts to connect to websites based on Web Search results, it fails to ignore self-signed certificates despite  `Bypass SSL verification for Websites` being `On`. Directly adding websites to context via `#` works fine. It's only the RAG Web Search that cannot bypass SSL verification.  

## Reproduction Details

**Steps to Reproduce:**
1. Install latest Open WebUI Docker Image
2. Enable duckduckgo web search
3.  Ensure that  `Bypass SSL verification for Websites` is `On` and click **[Save]**
4. Execute a prompt with Web Search Enabled

## Logs and Screenshots

**Docker Container Logs:**
```
 Given the user's message and interaction history, decide if a web search is necessary. You must be concise and exclusively provide a search query if one is necessary. Refrain from verbose responses or any additional commentary. Prefer suggesting a search if uncertain to provide comprehensive or updated information. If a search isn't needed at all, respond with an empty string. Default to a search query when in doubt. Today's date is 2024-11-05.

User Message:
Who won the 2024 world series?

Interaction History:                                                                                  USER: Who won the 2024 world series?
                                                                                                      Search Query:
INFO:     172.19.0.1:32860 - "POST /api/task/query/completions HTTP/1.1" 200 OK                       ERROR [open_webui.apps.retrieval.web.utils] Error loading https://www.mlb.com/news/dodgers-win-world-series-2024: HTTPSConnectionPool(host='www.mlb.com', port=443): Max retries exceeded with url: /news/dodgers-win-world-series-2024 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')))     ERROR [open_webui.apps.retrieval.web.utils] Error loading https://abcnews.go.com/Sports/los-angeles-dodgers-win-world-series/story?id=115282153: HTTPSConnectionPool(host='abcnews.go.com', port=443): Max retries exceeded with url: /Sports/los-angeles-dodgers-win-world-series/story?id=115282153 (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')))
ERROR [open_webui.apps.retrieval.web.utils] Error loading https://en.wikipedia.org/wiki/2024_World_Series: HTTPSConnectionPool(host='en.wikipedia.org', port=443): Max retries exceeded with url: /wiki/2024_World_Series (Caused by SSLError(SSLCertVerificationError(1, '[SSL: CERTIFICATE_VERIFY_FAILED] certificate verify failed: self-signed certificate in certificate chain (_ssl.c:1006)')))
INFO  [open_webui.apps.retrieval.main] save_docs_to_vector_db [] 07cef926cff1fa04e42f32a29e72e986247dd6a3b2c9eeb1872040d51ee8eba
ERROR [open_webui.apps.retrieval.main] The content provided is empty. Please ensure that there is text or data present before proceeding.
Traceback (most recent call last):                                                                      File "/app/backend/open_webui/apps/retrieval/main.py", line 1168, in process_web_search                 save_docs_to_vector_db(docs, collection_name, overwrite=True)
  File "/app/backend/open_webui/apps/retrieval/main.py", line 687, in save_docs_to_vector_db
    raise ValueError(ERROR_MESSAGES.EMPTY_CONTENT)                                                    ValueError: The content provided is empty. Please ensure that there is text or data present before proceeding.                                                                                           
```

**Screenshots/Screen Recordings (if applicable):**
![image](https://github.com/user-attachments/assets/13453e0d-e8d0-481f-b934-96f3f20466a2)

**Comment by tjbck** [comment]
Fixed on dev
