### ISSUE TITLE
feat: New admin setting to display or hide citations in chat messages

### ISSUE THREAD

**Issue by DiegoRodriguez83** [open-webui/open-webui#6767]
### Feature
- New admin setting to display or hide citations in chat messages: **Show citations in messagens**

### Demo
https://github.com/user-attachments/assets/c1012205-4071-407b-afca-854ecc664b05

**Comment by hjbarraza** [comment]
I love/need this
: )

**Comment by khamsakamal48** [comment]
+1 to this. It would be a neat addition for organisations with stringent Information Security Policies.

**Comment by hudahoeda** [comment]
+1, Would love to see this being supported too!

**Comment by tjbck** [comment]
Added to dev!
