### ISSUE TITLE
feat: support openai embeddings for rag

### ISSUE THREAD

**Issue by peperunas** [open-webui/open-webui#679]
**Is your feature request related to a problem? Please describe.**
It would be great to have support for OpenAI's embedding models. As of now, to the best of my knowledge, only local embeddings are supported.

Link: https://platform.openai.com/docs/guides/embeddings

**Comment by justinh-rahb** [comment]
> As of now, to the best of my knowledge, only local embeddings are supported.

Believe you're correct. I'd go further and suggest to support the OpenAI API's embedding endpoint spec in general so that other compatible sources could be used.

**Comment by tjbck** [comment]
Hi, I'm not entirely sure why or where this is useful, as we don't utilize any embeddings api directly and only use the `chat completion` api which handles embedding automatically. Could you guide me through and elaborate more on its potential use cases?

**Comment by justinh-rahb** [comment]
@tjbck right now the RAG feature uses an internal embedding model in the container, we're proposing to be able to use API embeddings models as alternative, some of them work significantly better than the default `all-MiniLM-L6-v2` used right now.

**Comment by tjbck** [comment]
@justinh-rahb makes sense if that's what OP meant, thanks for the explanation!

**Comment by bozo32** [comment]
will this permit choice of index?
https://docs.llamaindex.ai/en/stable/module_guides/indexing/index_guide/
not sure, but for data sources that are somewhat internally structured (e.g. academic papers), when iterating through data sources the tree structure may perform differently.

**Comment by thienedits** [comment]
Is it me or does this openai embedding model not work correctly? In the Document settings, OpenAI settings don't seem to work.

**Comment by Tiiiiiida** [comment]
> Is it me or does this openai embedding model not work correctly? In the Document settings, OpenAI settings don't seem to work.是我还是这个 OpenAI 嵌入模型出了问题？在文档设置中，OpenAI 设置似乎不起作用。

u need to restart the server for this setting to take effect
