### ISSUE TITLE
support `o1-*` family models by not filtering for just `gpt`

### ISSUE THREAD

**Issue by rndmcnlly** [open-webui/open-webui#6820]
# Feature Request

I want to try using the new [o1](https://openai.com/o1/) family models from OpenAI, but OWUI seems to filter the list of available OpenAI models down to those with "gpt" in the name. Supporting these new models might be as easy as revising this filtering criterion.

For the one line of code in question, see https://github.com/open-webui/open-webui/blob/7228b39064ac28e1240bf8998f2a35535c6f7ef5/src/lib/apis/openai/index.ts#L265

**Comment by tjbck** [comment]
This endpoint is not being used.
