### ISSUE TITLE
enh: manual model list for almost-OpenAI-compatible providers

### ISSUE THREAD

**Issue by rndmcnlly** [open-webui/open-webui#6821]
# Feature Request

Commercial LLM providers like Google and SambaNova are recently trying to offer OpenAI endpoint compatibility, but they often forget to fully implement the `/models` endpoint used by OWUI to dynamically list available models. If the Connections admin panel had some sort of optional "model list override", we could start using these providers even was they drag their feet building out fill OpenAI compatibility.

When the user clicks the "Verify connection" button when an override list is non-empty, then OWUI would instead try to get information only for the first item on the override list rather than trying to dynamically load the list.

**Comment by tjbck** [comment]
Been on my mind lately, investigating.

**Comment by fabigr8** [comment]
Had the same issue for LitServe, as they don't implement it in their standard as well, luckily I could extend their API via a workaround. So 👍🏼  +1 from my side, would be a great feature.

**Comment by tjbck** [comment]
![image](https://github.com/user-attachments/assets/b118c44f-8209-43de-bece-9ce207f8952a)

Added to dev, Testing wanted here!
