### ISSUE TITLE
enh: image compression

### ISSUE THREAD

**Issue by utopeadia** [open-webui/open-webui#6848]
When we take pictures with modern phones or cameras, the image pixels and size are huge. The size of images passed into the API may be several MB or even tens of MB, which can be a disaster for some small VLM (perhaps it's also a disaster for large VLM, as there is too much redundant information in the picture). Can we provide an upfront image processing step to compress the image before passing it to the LLM API according to user settings, reducing its size to KB?  (of course, users can also choose not to compress it, lol)

**Comment by parniantaghipour** [comment]
@tjbck Do you think this is helpful?

https://openwebui.com/f/lamkhatinh/image_resizer

**Comment by 123hi123** [comment]
is this already sppourt by the newest version?

**Comment by spammenotinoz** [comment]
> is this already sppourt by the newest version?

The function is already supported but you need to download and install it.
I am finding it works as intended.  I am not personally impacted by the slow uploads, so this function fixed my issues, especially with Anthropic.

**Comment by 123hi123** [comment]
> > is this already sppourt by the newest version?這是否已由最新版本支援？
> 
> The function is already supported but you need to download and install it.該功能已受支援，但您需要下載並安裝它。 I am finding it works as intended. I am not personally impacted by the slow uploads, so this function fixed my issues, especially with Anthropic.我發現它按預期工作。我個人沒有受到上傳速度慢的影響，所以這個功能解決了我的問題，特別是與 Anthropic 有關的問題。

you say download this? https://openwebui.com/f/lamkhatinh/image_resizer
I thought this feature was included in the latest version.

**Comment by tjbck** [comment]
<img width="914" alt="image" src="https://github.com/user-attachments/assets/34c1f94e-6b6e-4113-9819-998d30ecac6d" />

Added to dev!

**Comment by Fusseldieb** [comment]
@tjbck Does this resize on the server or on the device?

**Comment by tjbck** [comment]
You should be using filter functions for server-side compression, above is for client-side.
