### ISSUE TITLE
openwebui censorship?

### ISSUE THREAD

**Issue by joshuacox** [open-webui/open-webui#6867]
## Installation Method

docker compose

## Environment

- **Open WebUI Version:** [e.g., v0.3.11]
- **Ollama (if applicable):** [e.g., v0.2.0, v0.1.32-rc1]

both installed from the docker compose:

```
commit 96c865404d36637eafadb6d2dd2365c85d452648
Author: Timothy Jaeryang Baek <tim@openwebui.com>
Date:   Sat Nov 9 18:01:23 2024 -0800

    refac: disable openapi.json
```

- **Operating System:** [e.g., Windows 10, macOS Big Sur, Ubuntu 20.04]

cat /etc/os-release 
PRETTY_NAME="Ubuntu 22.04.5 LTS"
NAME="Ubuntu"
VERSION_ID="22.04"
VERSION="22.04.5 LTS (Jammy Jellyfish)"
VERSION_CODENAME=jammy
ID=ubuntu
ID_LIKE=debian
HOME_URL="https://www.ubuntu.com/"
SUPPORT_URL="https://help.ubuntu.com/"
BUG_REPORT_URL="https://bugs.launchpad.net/ubuntu/"
PRIVACY_POLICY_URL="https://www.ubuntu.com/legal/terms-and-policies/privacy-policy"
UBUNTU_CODENAME=jammy

- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]

Version 130.0.6723.116 (Official Build) Arch Linux (64-bit)

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.

I'll not include the logs, as that would expose my users and what they asked, you can test this yourself with whatever offensive prompt that you can dream up.

## Expected Behavior:

I expect openwebui to pass my users prompt to the model without censorship.

## Actual Behavior:

openwebui censors my users prompt, whereas I can run the model directly with `ollama run model` and it answers my prompt truthfully.

## Description

Censorship in openwebui

**Bug Summary:**

OpenWebui appears to be censoring input.

## Reproduction Details

**Steps to Reproduce:**

find a prompt offensive enough to get rejected using an uncensored model like: wizard-vicuna-uncensored

then run the same prompt using  `ollama run wizard-vicuna-uncensored`

## Logs and Screenshots

Again, the prompts and screenshots themselves would obviously be inappropriate for github.  But I maintain that hosting a private instance of openwebui, and running uncensored LLMs, that openwebui should not be interjecting itself, the LLM should speak for itself.

**Comment by tjbck** [comment]
There's no censorship.
