### ISSUE TITLE
Better error handling when models throw error

### ISSUE THREAD

**Issue by karan5291** [open-webui/open-webui#6878]
# Feature request

## Environment

- **Open WebUI Version:** 0.3.35
- **Operating System:** macOS
- **Browser (if applicable):** Chrome

**Confirmation:**

- [ x ] I have read and followed all the instructions provided in the README.md.
- [ x ] I am on the latest version of both Open WebUI and Ollama.
- [  x ] I have included the Docker container logs.
- [ x ] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Wanted Behavior:

After model throwing error, in this 400 because the message is too long, the chat should be usable by excluding the failing message from history. This is the case in ChatGPT where you are not able to send in a too long message but the chat itself i still usable after.

## Actual Behavior:

When the model return an error the whole chat become stale and a new chat has to be created.

## Description

When the model throws an error the chat enters a stale mode and cannot be used further. The chat history of the session is lost (it i possible to download the chat but it i awkward to recreate it in new chat.)

## Reproduction Details

Start a chat with a model that has a limit on input length and try to send in a message bigger than that limit. 

## Logs and Screenshots

**Docker Container Logs:**

ASSISTANT: 
ERROR [open_webui.apps.openai.main] 400, message='Bad Request', url='https:/my-endpoint/v1/chat/completions'
Traceback (most recent call last):
  File "/app/backend/open_webui/apps/openai/main.py", line 475, in generate_chat_completion
    r.raise_for_status()
  File "/usr/local/lib/python3.11/site-packages/aiohttp/client_reqrep.py", line 1121, in raise_for_status
    raise ClientResponseError(
aiohttp.client_exceptions.ClientResponseError: 400, message='Bad Request', url='https://my-endpoint/v1/chat/completions'
</chat_history>
INFO:     192.168.65.1:26941 - "POST /api/task/tags/completions HTTP/1.1" 400 Bad Request
INFO:     192.168.65.1:26941 - "GET /api/v1/chats/954c33ac-17cc-4f6b-89e3-5895c347d746 HTTP/1.1" 200 OK
INFO:     192.168.65.1:26941 - "GET /api/v1/chats/all/tags HTTP/1.1" 200 OK
INFO:     192.168.65.1:26941 - "GET /api/v1/chats/?page=1 HTTP/1.1" 200 OK

<img width="1140" alt="image" src="https://github.com/user-attachments/assets/2802feab-90c8-4a32-a829-e1717fec237f">

Also with an openai model:
<img width="1167" alt="image" src="https://github.com/user-attachments/assets/7044b07c-8dfb-4906-bff2-9ec18931c382">

**Comment by tjbck** [comment]
Expected behaviour here, however PR welcome!
