### ISSUE TITLE
Duplicate names in model selection

### ISSUE THREAD

**Issue by lucyknada** [open-webui/open-webui#6880]
# Feature Request

**Is your feature request related to a problem? Please describe.**
Currently if you point openwebui at two different instances of the same backend; the models in the "users" section are all duplicated (because it does a request to /models and gets the same ones twice) making it near impossible to tell which entry corresponds to which backend

**Describe the solution you'd like**
Suffix all entries with the id of the backend e.g. `llama-3.1 (#1)` which would map to the backend order setup in connections tab

**Describe alternatives you've considered**
I suppose bruteforce until I see usage on the right backend? with 5+ connections thats quite a game though because the entries are not sorted in any way.

Thanks!

**Comment by tjbck** [comment]
Already added to dev.
