### ISSUE TITLE
Support GitHub Models API

### ISSUE THREAD

**Issue by gunamata** [open-webui/open-webui#6892]
# Feature Request
Support [GitHub Models](https://github.com/marketplace/models) in Open WebUI

The GitHub Models `/models` API end point returns models info in a slightly different format than what Open WebUI expects. 
It looks like the `id` value provides the full path (ex: `azureml://registries/azureml/models/Phi-3-small-8k-instruct/versions/3`) of the model in the Azure registry where as the `/chat/completions` api requires the model's short name (ex: `Phi-3-small-8k-instruct`). The `name` attribute has the model short name.

May be below code can be modified to handle what GitHub Models `/models` endpoint returns. Something like, `.map((model) => ({ id: model.id.find('://') > 0 ? model.name : model.id, name: model.name ?? model.id, external: true }))` ??

https://github.com/open-webui/open-webui/blob/main/src/lib/apis/openai/index.ts#L264C3-L264C4

**Comment by tjbck** [comment]
Should be supported on dev, testing wanted here.

**Comment by gunamata** [comment]
@tjbck , It doesn't work when I tried with the dev image. It still complains about the full model path.

![image](https://github.com/user-attachments/assets/3a4a46ce-8f75-4851-8d83-8a4d4f4d4d50)
