### ISSUE TITLE
enh: support Markdown or HTML formatting in interface banners

### ISSUE THREAD

**Issue by Xtrah** [open-webui/open-webui#6908]
# Feature Request

**Is your feature request related to a problem? Please describe.**
The implemented interface banners (ref: #1522) are working great, but they currently only support plain text, which limits their communication effectiveness.

**Describe the solution you'd like**
Implement Markdown support for banner content, allowing familiar syntax for formatting:
- `**bold**`
- `*italic*`
- `[link text](url)`

**Describe alternatives you've considered**

As as alternative to Markdown, one could consider basic HTML tags for formatting:
- `<strong>`, `<b>`
- `<em>`, `<i>`
- `<u>`
- `<a href="">`

**Additional context**

Benefits:
- Improved readability of banner messages
- Better emphasis on important information
- Direct linking to relevant resources
- Consistent with other text formatting features

**Comment by tjbck** [comment]
Added to dev!
