### ISSUE TITLE
feat: image generation integration

### ISSUE THREAD

**Issue by raphaelmaenle** [open-webui/open-webui#696]
**Feature request Summary**
Analogous to ChatGPT's integration of mixed models, I would like to have a single place for AI requests.
1, connect ollama webui via openAI api to dall-e 3 image generation
2, be able to connect ollama webui to other image generation models which run locally

Example of how dall-e image generation is presented in chatGPT interface:
![dall-e](https://github.com/ollama-webui/ollama-webui/assets/17550607/dc45cf7e-7f19-45e9-a636-d07fa1d0edec)

**Comment by shadowdoggie** [comment]
would love this aswell, with auto1111 please :)

**Comment by justinh-rahb** [comment]
> This would be awesome and a feature I miss. Curious how to integrate this. Using something from automatic1111 isn't as simple as using DALLE3 with ChatGPT. You have a lot of variables, models, tweaks etc that make an easy implementation complicated.
> 
> Dalle3 yields good results because it adds prompts to your existing prompt, and hides all the complicated settings.

I think the holy grail is figuring out how to replicate that. Probably involves using a specialized fine-tuned model to parse the requested generation and create parameters to achieve it.

**Comment by Henglund** [comment]
1234567890
192.168.4.1.
