### ISSUE TITLE
dev: actions are broken in latest version

### ISSUE THREAD

**Issue by gjgd** [open-webui/open-webui#6976]
# Bug Report

## Environment

- **Open WebUI Version:** dev

- **Operating System:** Ubuntu 22.04
- **Browser (if applicable):** Firefox 133

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Using image `ghcr.io/open-webui/open-webui:git-c44036e` from 2 weeks ago, actions are still working
![CleanShot 2024-11-15 at 16 52 43](https://github.com/user-attachments/assets/2c40a8d7-006e-41fb-a5b1-710860311ae2)

## Actual Behavior:

Using image `ghcr.io/open-webui/open-webui:main` or `ghcr.io/open-webui/open-webui:dev`, actions are not working, and I am getting an error in the dev console:

![CleanShot 2024-11-15 at 16 54 41](https://github.com/user-attachments/assets/a3588a91-2b31-49ab-a252-fe8623da2c13)
![CleanShot 2024-11-15 at 16 54 27](https://github.com/user-attachments/assets/98e55f70-3aee-4424-a6f9-8e641b4ba474)

**Comment by parniantaghipour** [comment]
Which tool are you using?

**Comment by gjgd** [comment]
Sorry I meant "action" not "tool", here is one that you can use to repro for example: https://openwebui.com/f/hub/custom_action.

**Comment by silentoplayz** [comment]
Thanks for the bug report. I can confirm this error is happening with `Action` button functions on the latest dev comment. It has been reported internally to the maintainer as well.
