### ISSUE TITLE
issue: "Update and Copy Link" not working, the shared chat was not updated

### ISSUE THREAD

**Issue by chulanpro5** [open-webui/open-webui#7003]
# Bug Report

## Installation Method

- Local setup: `git clone`

## Environment

- **Open WebUI Version:** `v0.3.35`

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

After click "Update and Copy Link" on a shared conversation, the shared conversation should be updated.

## Actual Behavior:

After click "Update and Copy Link" on a shared conversation, the shared conversation not update with new change.

Screenshot on: http://localhost:3000/c/c708a046-1ea8-4fb2-9db2-12a5f2ef640e:
![image](https://github.com/user-attachments/assets/af8e37a2-2b6c-446a-81c8-9d081cfa9297)

Screenshot on: http://localhost:3000/s/1a30758c-a757-4fd6-afbe-6688d906f058:
![image](https://github.com/user-attachments/assets/9c76a7b5-9d24-4c40-92bb-3a639612b4fa)

## Reproduction Details

**Steps to Reproduce:**
1. Create new conversation and send a message.
2. Share that conversation by click "Share Chat" -> "Copy Link"
3. Send other message to previous conversation.
4. Update the shared link by click "Share Chat"-> "Update and Copy Link"
5. Goto the copied link.

## Logs and Screenshots

**Browser Console Logs:**
![image](https://github.com/user-attachments/assets/e28553b5-e666-4135-9c33-c122fca2b9d2)

**Comment by tjbck** [comment]
Good catch, fixed on dev!
