### ISSUE TITLE
Bug: Auto formatting in textbox if copy text contains `#`, `//`, etc

### ISSUE THREAD

**Issue by devanenWl** [open-webui/open-webui#7019]
# Bug Report

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Description

**Bug Summary:**
When pasting code that contains `#`, `//`, etc, and try to continue to type on that line, it will reformat all the code. It won't reformat if I break line/enter some rows. This issue happens in **v0.3.35**, works normally in **v0.3.33**

## Screen Recordings 

**Screen Recordings:**

https://github.com/user-attachments/assets/0a0e98ce-8b38-4c77-a5bd-476d37a26da4

**Comment by tjbck** [comment]
#6973
