### ISSUE TITLE
Various internal endpoints not working on a fresh install of 0.4.0

### ISSUE THREAD

**Issue by samling** [open-webui/open-webui#7059]
# Bug Report

## Installation Method

Kubernetes

## Environment

- **Open WebUI Version:** v0.4.0

- **Operating System:** Ubuntu 24 (host)
- **Browser (if applicable):** Chrome 130.0.6723.119

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Certain endpoints to function correctly:
- Create user API key
- Save model changes (e.g. visibility, tool selection)

## Actual Behavior:

Client-side 404s hitting various internal open-webui API endpoints

## Description

**Bug Summary:**
I was initially experiencing issues having upgraded an existing deployment, so I backed up everything and started fresh in an incognito tab to rule out migration and cache issues.

- Attempting to create an API key throws an error in the console: `Uncaught (in promise) TypeError: Cannot read properties of null (reading 'api_key')`

The container logs show FastAPI errors:

```
open-webui-55c55cd9db-t2w48 open-webui                ^^^^^^^^^^^^^^^^^^^
open-webui-55c55cd9db-t2w48 open-webui   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 278, in app
open-webui-55c55cd9db-t2w48 open-webui     raw_response = await run_endpoint_function(
open-webui-55c55cd9db-t2w48 open-webui                    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui-55c55cd9db-t2w48 open-webui   File "/usr/local/lib/python3.11/site-packages/fastapi/routing.py", line 191, in run_endpoint_function
open-webui-55c55cd9db-t2w48 open-webui     return await dependant.call(**values)
open-webui-55c55cd9db-t2w48 open-webui            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
open-webui-55c55cd9db-t2w48 open-webui   File "/app/backend/open_webui/apps/webui/routers/auths.py", line 742, in create_api_key
open-webui-55c55cd9db-t2w48 open-webui     if not request.app.config.state.ENABLE_API_KEY:
open-webui-55c55cd9db-t2w48 open-webui            ^^^^^^^^^^^^^^^^^^
open-webui-55c55cd9db-t2w48 open-webui AttributeError: 'FastAPI' object has no attribute 'config'
```

- Attempting to update a model setting seems to be hit or miss. Anecdotally it seems like I can (sometimes) save the first change to a model, but subsequent saves throw an error in the console: `index.ts:170 POST https://open-webui.(mydomain)/api/v1/models/id/anthropic/claude-2/update 404 (Not Found)`

Nothing extra in the container logs, just a 404 attempting to hit the endpoint.

## Reproduction Details

**Steps to Reproduce:**
1. Install open-webui 0.4.0 with no existing data
2. Create an account
3. Navigate to settings > account > "create new secret key"; observe console errors

1. Add a model provider (maybe specific to litellm?)
2. Edit a model, change the visibility to public, save (successful)
3. Edit the same mode, change the visibility to private, save (unsuccessful)

Any help is appreciated. Thank you!

**Comment by tjbck** [comment]
Fixed on dev!

**Comment by samling** [comment]
Unfortunately creating an API key still seems to be broken:

```
open-webui-5fcddfc59-7b89k open-webui   File "/app/backend/open_webui/apps/webui/routers/auths.py", line 748, in create_api_key
open-webui-5fcddfc59-7b89k open-webui     api_key = create_api_key()
open-webui-5fcddfc59-7b89k open-webui               ^^^^^^^^^^^^^^^^
open-webui-5fcddfc59-7b89k open-webui TypeError: create_api_key() missing 1 required positional argument: 'request'
```

The issue with saving models after the first update persists as well.

**Comment by tjbck** [comment]
Should be fixed with the latest dev 😅

**Comment by samling** [comment]
Appreciate the super quick fixes! Happy to keep trying them as they roll out. 😄

**Comment by tjbck** [comment]
As for the other issue, the model id containing '/' is not supported. You might want to try deleting the model if possible!

**Comment by samling** [comment]
Got it - did that change in this version? They were working properly in 0.3.x. It's a naming convention I use in litellm to quickly find models by provider. Saving does work at least once, but maybe that creates a record that then has issues on subsequent updates?

**Comment by samling** [comment]
I can confirm creating an API key works and removing `/` from the model name fixes the other issue. Still not sure if the latter is a regression, but it's a small ask to update my model names to avoid the issue. Many thanks!

**Comment by tjbck** [comment]
Updated the endpoints to allow `/` in the id, but I'd strongly discourage using `/` in the id in general, as they can be used as a part of url path parameters. Everything should work as intended now I believe, 0.4.1 will be released shortly!

**Comment by samling** [comment]
Understood, I totally understand from an API ambiguity perspective. Thank you so much!

**Comment by JunweiDuan** [comment]
Solved or not? I meet the same issue, urgent, urgent, urgent.
