### ISSUE TITLE
VPS Install

### ISSUE THREAD

**Issue by team-boo** [open-webui/open-webui#7080]
Hello,

I didn't find anywhere a HOWTO for installing on VPS Like Virtualmin.

Please some help.

**Comment by duhow** [comment]
Virtualmin is not a VPS, is a dashboard to manage VPS.

📝 There's a link to [manual install instructions](https://github.com/ollama/ollama/blob/main/docs/linux.md) in https://www.ollama.com/download .

**Comment by team-boo** [comment]
You want to say that Ollama is better LLM Management tool from Open WebUI?
