### ISSUE TITLE
Group level chat folders

### ISSUE THREAD

**Issue by tkg61** [open-webui/open-webui#7109]
# Feature Request

Building on 0.4.0 and concept of groups.

Can we have the ability to have chat folders be shared at a group level? This might be a large lift but wanted to propose the idea.

The reason for this is that now that we can share knowledge at a group level, having volunteer collaboration on a chat level would be helpful for group users who might receive different results or have questions about what they are seeing amongst their teammates or if someone comes up with a fantastic system prompt they can share that with others without having to create a new model (its the communal dev before "prod" concept for private models)

**Describe the solution you'd like**

- A new Group permission toggle is created for admins: Chat Folder Access (?)
   - This toggle will create a folder for all users inside of the group, named after the group (e.g. "__groupname__ Chats")
- The chat folder can not be deleted by group members, but would be removed if an admin untoggled the chat folder access setting...
   -  In the spirit of not actually deleting data, chats return to their original owners to preserve data
- Group members will see this folder appear or disappear as their group membership changes
- All chats not in group folders will remain private for individual users
   - They must elect to share/ move their chats into this folder
- Group members can not move chats out of a folder, they can only move them into it for security reasons 
   - I think this is a good idea? Exfil of data, stealing chats from others, insider threat, etc...
   - Or it would be that the original chat author/creator can move it out but not other group members 
- Group members can delete chats though since things would get cluttered otherwise or we go down the path of a group level "sub-admin" who has delete privileges 
- A component or "sub-toggle" feature of this could be that chats in the folder are read only for anyone but the creator (similar to the share feature but you don't have to send it to everyone.

**Comment by tjbck** [comment]
Good suggestions! Related: #2890
