### ISSUE TITLE
Can't change its order in the model list by dragging the model anymore

### ISSUE THREAD

**Issue by CookSleep** [open-webui/open-webui#7153]
# Bug Report

## Installation Method

- **Installation Method**: Docker

## Environment

- **Open WebUI Version**: v0.4.2  
- **Operating System**: Ubuntu 22.04  
- **Browser**: Windows Edge v130.0.2849.46  

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Users should be able to reorder models in the model list by dragging them, just like in previous versions. This allows prioritization or better organizational management.

## Actual Behavior:

In the current version, the ability to reorder models in the list by dragging them is not functional, though this feature worked in versions prior to v0.4.

## Description

**Bug Summary:**  
Users can no longer reorder models in the list by dragging them. This functionality was previously available but appears to be broken in the latest version.

## Reproduction Details

**Steps to Reproduce:**

1. Open the "Admin Panel."
2. Navigate to the "Settings" → "Models" page.
3. Attempt to drag a model in the list to reorder its position.
4. Observe that the models cannot be moved.

**Comment by tkg61** [comment]
In 0.4.0, it was noted this was removed but would be back:

https://github.com/open-webui/open-webui/releases/tag/v0.4.0

**Comment by tjbck** [comment]
Please check for duplicate issues https://github.com/open-webui/open-webui/issues/7011
