### ISSUE TITLE
"suffix" request parameter isn't proxied to Ollama instance at /ollama/api/generate endpoint

### ISSUE THREAD

**Issue by vills** [open-webui/open-webui#7158]
# Bug Report

## Environment

- **Open WebUI Version:** v.0.3.25
- **Ollama (if applicable):** 0.4.2

## Description

I came from discussion https://github.com/open-webui/open-webui/discussions/6720#discussion-7426295.

It looks like (by inspecting [GenerateCompletionForm](https://github.com/open-webui/open-webui/blob/main/backend/open_webui/apps/ollama/main.py#L837) class) that Ollama's "suffix" request parameter is ignored at `/ollama/api/generate` endpoint ([Ollama docs](https://github.com/ollama/ollama/blob/main/docs/api.md#generate-a-completion).

This cause problems with recent versions of Continue.dev extension for VSCode.

Please make OWUI respect this parameter.

Thanks.

**Comment by tjbck** [comment]
Added to dev!

**Comment by vills** [comment]
Thanks a lot! Works well with 0.4.3 release.
