### ISSUE TITLE
Allow the three dots on the top right corner to be accessible even when a conversation has not started on mobile.

### ISSUE THREAD

**Issue by CookSleep** [open-webui/open-webui#7217]
# Feature Request

**Is your feature request related to a problem? Please describe.**
Often I need to add special system prompts rather than using my custom commands.

**Describe the solution you'd like**
Allow the three dots on the top right corner to be accessible even when a conversation has not started on mobile.

**Describe alternatives you've considered**
I can only switch the browser UA to the desktop version, which is very troublesome.

**Additional context**
This feature used to exist. I mentioned it in #5974, but it has not been restored in subsequent updates.

**Comment by tjbck** [comment]
Addressed in dev!
