### ISSUE TITLE
Bug: There is no way to remove a custom model image/icon

### ISSUE THREAD

**Issue by willdady** [open-webui/open-webui#7278]
## Installation Method

Docker compose

## Environment

- **Open WebUI Version:** v0.4.3
- **Operating System:** MacOS Sequoia
- **Browser (if applicable):** Firefox

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Description

After adding an image/icon to a custom model there is no way to remove it to reset it back to the default "OI" graphic.

Adding a model image can take a bit of trial and error and sometimes you simply want to remove the image entirely. Ideally there should be a button to remove any custom uploaded image.

**Comment by tjbck** [comment]
Added to dev!
