### ISSUE TITLE
The conversation may disappear under multiple models.

### ISSUE THREAD

**Issue by xcyeye** [open-webui/open-webui#7287]
# Bug Report

## Important Notes

- **Before submitting a bug report**: Please check the Issues or Discussions section to see if a similar issue or feature request has already been posted. It's likely we're already tracking it! If you’re unsure, start a discussion post first. This will help us efficiently focus on improving the project.

- **Collaborate respectfully**: We value a constructive attitude, so please be mindful of your communication. If negativity is part of your approach, our capacity to engage may be limited. We’re here to help if you’re open to learning and communicating positively. Remember, Open WebUI is a volunteer-driven project managed by a single maintainer and supported by contributors who also have full-time jobs. We appreciate your time and ask that you respect ours.

- **Contributing**: If you encounter an issue, we highly encourage you to submit a pull request or fork the project. We actively work to prevent contributor burnout to maintain the quality and continuity of Open WebUI.

- **Bug reproducibility**: If a bug cannot be reproduced with a `:main` or `:dev` Docker setup, or a pip install with Python 3.11, it may require additional help from the community. In such cases, we will move it to the "issues" Discussions section due to our limited resources. We encourage the community to assist with these issues. Remember, it’s not that the issue doesn’t exist; we need your help!

Note: Please remove the notes above when submitting your post. Thank you for your understanding and support!

---

## Installation Method

I install it by Docker Compose, my docker-compose.yaml is 
```yaml
version: '3.8'  # 或者您选择的其他版本

services:
  open-webui:
    image: ghcr.io/open-webui/open-webui:main
    container_name: open-webui
    ports:
      - "0.0.0.0:3000:8080"
    volumes:
      - open-webui:/app/backend/data
    extra_hosts:
      - "host.docker.internal:host-gateway"
    environment:
      OPENAI_API_BASE_URLS: xxx
      OPENAI_API_KEYS: xxx
volumes:
  open-webui:
```

## Environment

- **Open WebUI Version:** v0.4.4
- **Ollama (if applicable):** 0.4.4

- **Operating System:** Windows11
- **Browser (if applicable):** Chrome 130.0.6723.117

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

I am currently trying to evaluate the output results of multiple models. However, after engaging in several rounds of conversation (more than three), when I double-click on one of the conversations, the others disappear. Then, when I click on other areas (such as conversations, blank spaces, or like buttons), the previously disappeared conversations reappear.

## Actual Behavior:

same obove

## Description

**Bug Summary:**
[Provide a brief but clear summary of the bug]

## Reproduction Details

**Steps to Reproduce:**
1. Add multiple models, at least two.
2. Engage in at least three rounds of conversation.
3. Double-click on one of the conversations in the second round.
4. Now, you will notice that the last round of conversation has disappeared.
5. Then, if you double-click on other areas, such as conversations or buttons, the previously disappeared conversations will reappear.

https://github.com/user-attachments/assets/ae6afc8d-1ec6-4a5c-8c7d-a0e816ec5f84

## Logs and Screenshots

**Browser Console Logs:**

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots/Screen Recordings (if applicable):**
Video in `Reproduction Details` section.

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by xcyeye** [comment]
The situation shown in the video exists with my own configuration. I just tested it under a new volume without any custom configurations, only configuring the OpenAI proxy and key, and the same issue occurs.

**Comment by tjbck** [comment]
Intended behaviour here.

**Comment by xcyeye** [comment]
Can I disable this feature? Sometimes, I just want to like a specific conversation, but whenever I click on a conversation, it removes the others. I find this behavior a bit unfriendly.
