### ISSUE TITLE
Customized model creation accessible to users

### ISSUE THREAD

**Issue by PatBQc** [open-webui/open-webui#7350]
### Discussed in https://github.com/open-webui/open-webui/discussions/4589

<div type='discussions-op-text'>

<sup>Originally posted by **Genai-labs** August 14, 2024</sup>
#### Your feature request related to a problem? Please describe.
It’s not a problem, but rather related to the idea of making this app available to a group of people.

#### Describe the solution you’d like
In the case of a large number of users, it could be interesting if they could create their own customized models without having to go through the admins.</div>

**Comment by tjbck** [comment]
Already possible with 0.4

**Comment by PatBQc** [comment]
Wow

That was fast 😄 

Thanks a lot !
