### ISSUE TITLE
Support Svelte 5

### ISSUE THREAD

**Issue by alanxmay** [open-webui/open-webui#7362]
# Feature Request

First of all, open-webui is fantastic and I use it daily.

I’m wondering if Svelte 5 support is on open-webui’s roadmap? As a Svelte newcomer, I’m interested in contributing features and fixing issues for open-webui. However, I’d prefer to learn and work with Svelte 5 rather than investing time in the older Svelte 4. Would there be opportunities for newcomers to contribute once Svelte 5 support is added?

**Comment by tjbck** [comment]
Will be added.
