### ISSUE TITLE
Bug: Incorrect behavior when pressing Enter with non-English keyboard input

### ISSUE THREAD

**Issue by EulerBlind** [open-webui/open-webui#7364]
## Installation Method

ubuntu docker compose

## Environment

- **Open WebUI Version:** v0.4.4
- **Ollama (if applicable):** v0.4.4

- **Operating System:** Ubuntu 23.10
- **Browser (if applicable):** Edge 130.0.2849.80

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of Open WebUI.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

In non-English input mode, after typing a word, pressing Enter should select the word, and pressing Enter again should submit the prompt to wait for the result.

## Actual Behavior:

When pressing Enter after typing an English word using a non-English keyboard layout, the system immediately calls the language model instead of selecting the word or allowing further editing.

## Description

**Bug Summary:**
In non-English input mode on Mac, pressing Enter after typing an English word triggers the language model call immediately instead of selecting the word and requiring another Enter press to submit the prompt.

## Reproduction Details

**Steps to Reproduce:**
1. Switch your Mac keyboard input method to a non-English language (e.g., Chinese).
2. Open the Open WebUI application.
3. In the prompt input field, type an English word using the keys on your Mac keyboard.
4. Press the Enter key.

## Logs and Screenshots

**Screenshots/Screen Recordings (if applicable):**
e.g.
![image](https://github.com/user-attachments/assets/7092ddf7-bfd2-441a-a080-c7cd3a1513d3)
It will submit [fa s ta pi] and call llm, but I just want type word [fastapi].

## Additional Information

It seems to be related to recent commits, such as this judgment method. This issue does not exist in version 0.4.0.
![image](https://github.com/user-attachments/assets/26776c59-f395-4c64-bf76-97a9db2deff1)

**Comment by tjbck** [comment]
Good catch, Fixed on dev!

**Comment by EulerBlind** [comment]
@tjbck There is anathor bug about In non-English input mode with the prompt completion 
<img width="933" alt="image" src="https://github.com/user-attachments/assets/6ebf3ac8-2b81-4f78-88e6-95a60d479829">

**Comment by freejool** [comment]
Hi! I have the same issue on Open WebUI version 0.5.20, Safari 18.3, MacOS Sequoia 15.3.1 (24D70)

It appears to have come with one of the recent commits.

And I have the auto-completion funtion off.

**Comment by RebelliousWhiz** [comment]
I observed the same behavior with the latest version, v0.6.10

When I am trying to type Mooncake and press Enter, I get feeding llm instead:

![Image](https://github.com/user-attachments/assets/01e0d559-bf15-4084-9a12-d46efe9a4e52)

![Image](https://github.com/user-attachments/assets/a8c33016-2ceb-431c-847a-2ee421365fa3)

@EulerBlind @tjbck can we reopen the issue?
