### ISSUE TITLE
`ROOT_PATH` or `WEBUI_BASE_URL` do not work

### ISSUE THREAD

**Issue by hostingnuggets** [open-webui/open-webui#7377]
# Bug Report

## Installation Method

`docker run -d --network=host -v open-webui:/app/backend/data -e OLLAMA_BASE_URL=http://127.0.0.1:11434 -e WEBUI_BASE_URL="http://localhost:8080/open-webui" --name open-webui --restart always ghcr.io/open-webui/open-webui:main`

## Environment

- **Open WebUI Version:** [v0.4.4]
- **Operating System:** [Ubuntu 24.04]
- **Browser (if applicable):** [Firefox 128.4]

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [X] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [X] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

The web interface should be available under the URI /open-webui

## Actual Behavior:

The web interface is NOT available under the URI /open-webui

## Description

**Bug Summary:**
Specify a specific URI using `ROOT_PATH` or `WEBUI_BASE_URL` environment variables do not work.

## Reproduction Details

**Steps to Reproduce:**
Simply install the latest version of the container using the command above.

## Logs and Screenshots

**Browser Console Logs:**
not relevant

**Docker Container Logs:**
not relevant

**Screenshots/Screen Recordings (if applicable):**
not relevant

## Additional Information

I am available for any further questions or testing.

**Comment by hostingnuggets** [comment]
@tjbck I don't understand why you closed this issue as not planned? I reported that these variable environments are not working, shouldn't they be working?

**Comment by tjbck** [comment]
There's no such thing as `ROOT_PATH`, `WEBUI_BASE_URL`.

**Comment by hostingnuggets** [comment]
> There's no such thing as `ROOT_PATH`, `WEBUI_BASE_URL`.

What about: https://github.com/search?q=repo%3Aopen-webui%2Fopen-webui%20WEBUI_BASE_URL&type=code

**Comment by hostingnuggets** [comment]
Thank you @alkaris2 for your answer but still with your recommendations Open WebUI is not available under the `/open-webui` path.

**Comment by 0k00l** [comment]
Use DNS alias and make catch by host ;)
