### ISSUE TITLE
Can't add and delete model

### ISSUE THREAD

**Issue by almagest21** [open-webui/open-webui#7443]
# Bug Report
## Environment
- **Open WebUI Version:** [0.4.6]
- **Ollama Version**: [0.4.2]
- **Operating System:** [Windows 11 24H2]

## Expected Behavior:
Open admin panel -> Setting tab -> Models
Model management for adding and deleting user interface should be existed

## Actual Behavior:
There are only model customization interface for already existing models
Also reorder and default model setting is appear from gear button

## Description
**Bug Summary:**
Model management for adding and deleting user interface is missing

## Logs and Screenshots
<img width="800" alt="models" src="https://github.com/user-attachments/assets/453b4337-7d93-42d1-a7dd-fc263c628c06">

Could you check this issue?
Thank you!

**Comment by tjbck** [comment]
https://github.com/open-webui/open-webui/discussions/7314 Hope this helps!

**Comment by almagest21** [comment]
@tjbck  Thank you for your information. Anyway, this new design makes sense
