### ISSUE TITLE
Bug: Gemini artifacts render error

### ISSUE THREAD

**Issue by TecReaGroup** [open-webui/open-webui#7450]
When using Gemini models (like flash 1.5, exp 1121...) artifacts to render HTML, it will generate double items.
In other models without this problem.
![390625766-f7cf8328-4396-471a-840d-b320d567d1e7.png](https://github.com/user-attachments/assets/6b26b7df-23c7-4e1c-aa17-b81ee7d4fbd0)

So it's a bit strange that artifacts are actually affected directly or indirectly by the model type. This means artifact's not absolutely independent. Or the Gemini's response has error message.

**Comment by silentoplayz** [comment]
Use the search bar on the issues page to search for and see if any similar issue is already open before opening one of your own. Related - https://github.com/open-webui/open-webui/issues/6154
