### ISSUE TITLE
Model ID Missing and Import Fails When Using Chinese Model Name

### ISSUE THREAD

**Issue by honwei189** [open-webui/open-webui#7490]
### **Bug Description**  
There are two related issues:  

1. When creating a model with a Chinese name and setting a model ID, the model ID disappears after saving.  
2. Importing a model (via a JSON file) does not work. After importing, there is no feedback, and the model is not imported into the system.  

These issues create significant obstacles when managing models with Chinese names.  

---

### **Steps to Reproduce**  

**Issue 1: Model ID Missing**  
1. Create a new model and use a Chinese name as the model name.  
2. Set the model ID.  
3. Save the model.  
4. Reopen the model and observe that the model ID is missing.  

**Issue 2: Import Failure**  
1. Prepare a valid JSON file representing a model configuration (downloaded the file from existing model, and edit the model id in the file).
2. Attempt to import the model using the import functionality.  
3. Observe that there is no feedback (no success or error messages), and the model is not imported into the system.  

---

### **Expected Behavior**  
1. The model ID should persist after saving, regardless of whether the model name is in Chinese or English.  
2. The import functionality should successfully import the model and provide appropriate feedback (e.g., success or error messages).  

---

### **Actual Behavior**  
1. The model ID is missing after saving when the model name is in Chinese.  
2. Importing a model via JSON does nothing—there is no feedback, and the model is not imported.  

---

### **Additional Notes**  
- In previous versions, users could edit the model ID directly. This option has been removed in the newer version, further complicating the issue.  
- As a workaround for the model ID issue, deleting the model and recreating it with an English name works, but this is inefficient and not user-friendly.  
- The import issue is particularly disruptive as it prevents restoring or sharing model configurations via JSON files.  

---

### **Impact**  
These issues significantly affect usability and efficiency. The inability to manage models with Chinese names and the broken import functionality limit the system's usability for international users or collaborative workflows.

**Comment by tjbck** [comment]
Only alphanumeric characters are supported as an ID, will refactor the model editor to provide an appropriate error message. Thanks!

**Comment by honwei189** [comment]
Yes, the model id I created is string, like "myfirst-model".

**Comment by tjbck** [comment]
@honwei189 should be addressed in dev!
