### ISSUE TITLE
Text editor deletes newlines after saving and reloading document

### ISSUE THREAD

**Issue by sherbie** [open-webui/open-webui#7492]
# Bug Report

## Installation Method

```
git checkout v0.4.6
git pull

docker build -t open-webui .
```

## Environment

- **Open WebUI Version:** v0.4.6
- **Ollama (if applicable):** 0.4.5

- **Operating System:** Ubuntu 24.04.1 LTS
- **Browser (if applicable):** Brave 1.73.91

## Expected Behavior:

After reloading a saved document, all characters and formatting should be unchanged.

## Actual Behavior:

After reloading a saved document, newlines are deleted.

Example:

Document contents after saving:
```
a

a
```

Document contents after reloading page:
```
a
a
```

## Description

**Bug Summary:**
Saved documents have all newlines deleted between the last newline of the previous line and the next line.

## Reproduction Details

**Steps to Reproduce:**
1. Create a new document
2. Press keys when the document is open: `a` `[return]` `[return]` `a`
3. Save document
4. Open document

**Comment by tjbck** [comment]
should be address in dev, testing wanted here!
