### ISSUE TITLE
Code indentations in sent messages are missing

### ISSUE THREAD

**Issue by Eureka-0** [open-webui/open-webui#7514]
# Bug Report

## Installation Method

Docker

## Environment

- **Open WebUI Version:*0.4.7*
- **Ollama (if applicable):*None*

- **Operating System:*Ubuntu 24.10*
- **Browser (if applicable):*Safari 18.1.1*

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

I typed some python code with indentations in the input box:

<img width="643" alt="image" src="https://github.com/user-attachments/assets/e207e3ad-e21f-4929-badf-6edf8f7db2bb">

 It should be rendered as in the answer from GPT-4o:

<img width="946" alt="image" src="https://github.com/user-attachments/assets/9a184139-1387-4828-b1c9-890e3cac9407">

## Actual Behavior:

However, when I sent the message, the indentations disappeared:

<img width="367" alt="image" src="https://github.com/user-attachments/assets/7f377e90-89e7-448a-ad56-eb4fcc0e7c09">

## Description

**Bug Summary:**
[Provide a brief but clear summary of the bug]

## Reproduction Details

**Steps to Reproduce:**
[Outline the steps to reproduce the bug. Be as detailed as possible.]

## Logs and Screenshots

**Browser Console Logs:**
[Include relevant browser console logs, if applicable]

**Docker Container Logs:**
[Include relevant Docker container logs, if applicable]

**Screenshots/Screen Recordings (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
Fixed on dev!
