### ISSUE TITLE
Model List Reordering and Bulk Enable/Disable Feature Request

### ISSUE THREAD

**Issue by honwei189** [open-webui/open-webui#7534]
**Description:**  
When using the OpenRouter API as a replacement for OpenAI, I encountered an issue where disabling a few models causes the model list to reorder continuously. This behavior makes managing the model list inefficient and frustrating, the list is blinking.  

Additionally, managing models one by one is cumbersome when dealing with a large list of models. I suggest adding a feature to allow bulk enabling/disabling of models for better usability.  

---

**Steps to Reproduce:**  
1. Use the OpenRouter API with a list of models.  
2. Attempt to disable a few models in the Admin -> Setting -> Model.  
3. Observe the model list reordering itself repeatedly, the list is blinking.  

**Expected Behavior:**  
- Disabling models should take effect immediately without causing the list to reorder repeatedly.  
- The interface should provide an option to bulk enable/disable models to improve management efficiency.  

**Actual Behavior:**  
- Disabling a few models causes the model list to reorder continuously for about one minute.  
- There is no bulk enable/disable option available, requiring users to handle models one by one.  

---

**Suggested Feature Improvements:**  
1. Fix the issue where the model list reorders repeatedly after disabling models.  
2. Add a bulk enable/disable option for models to improve user experience when managing large lists.  

**Additional Context:**  
Managing models in bulk is crucial for users with extensive model lists. Improving this functionality would save time and enhance the usability of the API.

**Comment by tjbck** [comment]
Fixed on dev.
