### ISSUE TITLE
Defect found in 'Default Prompt Suggestions' feature within the Admin Panel.

### ISSUE THREAD

**Issue by prasadautomationtesting** [open-webui/open-webui#7537]
**Issue 1:** When attempting to add more than 8 prompts under 'Default Prompt Suggestions', no placeholder is displayed in the UI, preventing users from adding new prompts. This results in a blocked interface.

**Issue 2:** Additionally, if all existing prompts are deleted and an attempt is made to add new ones from scratch, only 2 prompts can be added before the add icon becomes unresponsive. When clicked, the add icon fails to introduce a new placeholder for additional prompt entries.

**Simulation Steps:**

1. Access the Admin Panel.
2. Click on the 'Settings' option.
3. Select 'Interface'.
4. Scroll down to locate the 'Default Prompt Suggestions' feature.
5. Attempt to add more than 8 prompts.
6. Delete all existing prompts and then try adding new ones from scratch, observing that only 2 prompts can be added.

**Expected Results:**
The add icon should display a new placeholder to initiate prompt entry.

**Actual Results:**
1. The add icon becomes unresponsive when there are already 8 prompts already in place.
2. The add icon becomes unresponsive when after adding two prompts (After deleting all the existing prompts)

**Comment by tjbck** [comment]
![image](https://github.com/user-attachments/assets/34468d66-9525-4a53-b4f5-d2b3016be005)

Unable to reproduce the neither of these issues, the content must be provided first before you can add additional prompt suggestions.
