### ISSUE TITLE
Configurations via Environment Variables not precedent over configs in the database

### ISSUE THREAD

**Issue by justbert** [open-webui/open-webui#7560]
# Bug Report

## Installation Method

open-webui Helm chart via ArgoCD on OpenShift.

## Environment

- **Open WebUI Version:** v0.4.6

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [ ] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [X] I have included the Docker container logs.
- [X] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Configurations via environment variables should take precedence over state in database.

## Actual Behavior:

Once a configuration has been set and stored in the database by interacting with the admin panel, they take priority from then on.

## Description

**Bug Summary:**
When setting configurations via environment variables, persisted configurations in the database take precedence. 

Generally, when it comes to configuring applications, environment variables take precedence over saved state at startup since these allow for managing an application programmatically.  [https://12factor.net/config]

## Reproduction Details

**Steps to Reproduce:**

- Install and configure open-webui via container and environment variables
- Interact with the admin panel and change a setting
- Restart container

## Logs and Screenshots

**Docker Container Logs:**

**Fresh Install:**

INFO [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO [alembic.runtime.migration] Will assume transactional DDL.

**Interacted with admin panel:**

INFO [alembic.runtime.migration] Context impl PostgresqlImpl.
INFO [alembic.runtime.migration] Will assume transactional DDL.
INFO [open_webui.env] 'ENABLE_OLLAMA_API' loaded from the latest database entry
INFO [open_webui.env] 'OLLAMA_BASE_URLS' loaded from the latest database entry
INFO [open_webui.env] 'OLLAMA_API_CONFIGS' loaded from the latest database entry
INFO [open_webui.env] 'ENABLE_OPENAI_API' loaded from the latest database entry
INFO [open_webui.env] 'OPENAI_API_KEYS' loaded from the latest database entry
INFO [open_webui.env] 'OPENAI_API_BASE_URLS' loaded from the latest database entry
INFO [open_webui.env] 'OPENAI_API_CONFIGS' loaded from the latest database entry
INFO [open_webui.env] 'DEFAULT_LOCALE' loaded from the latest database entry
INFO [open_webui.env] 'DEFAULT_PROMPT_SUGGESTIONS' loaded from the latest database entry

**Comment by justbert** [comment]
Ooof, gotcha. It doesn't follow general industry patterns and it doesn't seem to be well documented. 

In the [docs](https://docs.openwebui.com/getting-started/advanced-topics/env-configuration#appbackend) it states:

>The following environment variables are used by backend/config.py to provide Open WebUI startup configuration. Please note that some variables may have different default values depending on whether you're running Open WebUI directly or via Docker.

It might be best to state that _**...to provide Open WebUI with an initialization configuration**_

**Comment by tjbck** [comment]
@justbert Agreed, there are some env vars that don't get saved to the database which might add to the confusion. I'm open to accepting PR for this (both the code, and the doc)!

**Comment by justbert** [comment]
Sounds good! Just to clarify, in regards to a PR, would this be to update the docs or to re-align functionality to use set Env Vars as precedent?

**Comment by justbert** [comment]
Oh! I hadn't seen the `RESET_CONFIG_ON_START` env var. This should do nicely!
