### ISSUE TITLE
"Jump to page" in source documents does not work anymore after upgrading to 0.4.7

### ISSUE THREAD

**Issue by InventoCasa** [open-webui/open-webui#7567]
## Installation Method

Docker

## Environment

- **Open WebUI Version:** v0.4.7

- **Operating System:** Ubuntu 22.04
- **Browser (if applicable):** Firefox, Chrome

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

When prompting with a Knowledge Connection and clicking on "Citation" --> "Source" in the answer footer,  the browser did jump to the specific page in the source document

## Actual Behavior:

The jump to the specific page does not work anymore after upgrading to 0.4.7

## Description

**Bug Summary:**
"Jump to page" in source documents does Not Work anymore

## Reproduction Details

**Steps to Reproduce:**
See "actual behaviour"

**Comment by tjbck** [comment]
Fixed in dev!
