### ISSUE TITLE
Custom context size not being respected. 

### ISSUE THREAD

**Issue by luisbrandao** [open-webui/open-webui#7586]
What is the issue?
Hello,

I noticed an inconsistent behavior.
I had edited my model parameters on admin view and set its context size.

however, i should be able to change it "again" in the chat windows:

![image](https://github.com/user-attachments/assets/ce312d07-beae-4b86-a8e8-b79dcb786e4c)
in this image, the number "4096" does not get set, if it is already set on admin -> models.

Is this intentional?

im using:
ghcr.io/open-webui/open-webui:v0.4.7-cuda

**Comment by c0008** [comment]
> Intended behaviour.

Does it mean you can't change the default setting if you want to increase it only for longer prompts/chats?
