### ISSUE TITLE
Only admin can use model 

### ISSUE THREAD

**Issue by ioveeagle** [open-webui/open-webui#7620]
As title, I just update to v0.4.7

and found only admin can see and use models.

Normal user can't ever see one, until I give him admin privileges 

Normal user vision (it should be lots of model which I deploy): 
![image](https://github.com/user-attachments/assets/f523f08e-fceb-4191-a23a-1716ff7ceeaa)

I read all the settings but still can't solve it

**Comment by AzizDXT** [comment]
![1](https://github.com/user-attachments/assets/ada7ceb7-6b89-49f8-9f83-0894f2bcbce5)
![3](https://github.com/user-attachments/assets/4d18da2e-ffcf-4ed3-b3e1-33dbb29b1e12)
![2](https://github.com/user-attachments/assets/a0a5ece4-4f93-44f3-9e0a-33ef64080e9d)

Good Luck bro :).

Public means that the form is available to all users.

**Comment by AzizDXT** [comment]
You're welcome, friend. We all make mistakes, but we learn. I wish you success.

I need a little help if you know where to put or upload the knowledge files and how to make the AI ​​request a specific API or execute a specific script you can help me with any of the problems I face if you can or know how to solve them thank you.

**Comment by ioveeagle** [comment]
I think "AI agent" is quite suitable for your needs. 
It is used to request specific APIs or execute specific scripts in different situations.

**Comment by AzizDXT** [comment]
Where can I find it on the interface? If possible, take a screenshot for me.
