### ISSUE TITLE
Where can I upload the PDF files for knowledge?

### ISSUE THREAD

**Issue by AzizDXT** [open-webui/open-webui#7621]
i wanna help please.

**Comment by flefevre** [comment]
Please us the Discussions or Discord channel for this as it is not a bug.


documentation : https://docs.openwebui.com/features/workspace/knowledge

you can go in the Workspace tab, and then in "Konwledge" section and create a knowledge to upload your files

![createK](https://github.com/user-attachments/assets/70c06dc9-8a51-444d-ab17-0e1b8e91932f)

**Comment by AzizDXT** [comment]
Thanks so much bro🌹
