### ISSUE TITLE
[Feat] Add UI Customization in the Admin Panel

### ISSUE THREAD

**Issue by safe049** [open-webui/open-webui#7652]
# Feature Request

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Add a UI Customization in Admin Panel,which support to change splash,name,"about" in settings,instead of playing around in envs

**Describe alternatives you've considered**
Don't have one

**Additional context**
Don't have one

**Comment by darebfh** [comment]
+1! 
Configuring a banner would also be a nice feature.
