### ISSUE TITLE
Admin Menu Contrast Reduction

### ISSUE THREAD

**Issue by statianzo** [open-webui/open-webui#7671]
# Bug Report

## Installation Method

docker-compose of `ghcr.io/open-webui/open-webui:0.4.7`

## Environment

- **Open WebUI Version:** 0.4.7

- **Operating System:** macOS Sonoma 14.7.1
- **Browser:** Firefox 134.0b3

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [ ] ~~I have included the Docker container logs.~~ (UI Issue)
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Menu items that have sufficient color contrast to align with WCAG 2.2 (4.5:1)

## Actual Behavior:

Admin menu items have a contrast ratio of 1.59:1

## Description

**Bug Summary:**
After upgrading to 0.4.7 from 0.3.x, I was confused when I first saw the Admin Settings menu. All the items appeared disabled. After selecting one, I realized this isn't the case.
There was a style change in fae6731137850fa575d3680d0223ff967eb155b2 to have buttons `text-gray-300`.

The move towards a light font color on top of a white background is challenging for users with reduced contrast perception. [Web Content Accessibility Guidelines](https://www.w3.org/TR/WCAG22/#contrast-minimum) recommend a 4.5:1 ratio for body text like the menu items.

## Reproduction Details

**Steps to Reproduce:**

1. Go to `/admin/settings`
2. Open Firefox developer tools > Accessibility
3. Toggle *Check for Issues* to *Contrast*
4. Observe all menu items listed

## Logs and Screenshots

**Screenshots/Screen Recordings (if applicable):**

#### Admin Settings in 0.4.7

![image](https://github.com/user-attachments/assets/f996e320-f129-4a4a-940c-815b17368bee)

#### Admin Settings in 0.3.35
![image](https://github.com/user-attachments/assets/fa500b97-5d5a-45c8-82e6-fb1f238eb7e3)

#### Firefox Accessibility Panel 0.4.7
![image](https://github.com/user-attachments/assets/40462362-88d2-40f6-aaec-0ada3d590bd8)

## Additional Information

Wanted to take this spot to share my genuine appreciation for OpenWeb UI. It's an excellent project that has been useful for making the most of self-hosted LLMs. ❤️ Thank you!

**Comment by tjbck** [comment]
Intended styling.
