### ISSUE TITLE
issue: v0.4.8 pip install not working

### ISSUE THREAD

**Issue by safe049** [open-webui/open-webui#7677]
# Bug Report

## Installation Method

pip

## Environment

- **Open WebUI Version:** 0.4.7
- **Ollama (if applicable):** 0.4.6

- **Operating System:**Arch Linux
- **Browser (if applicable):** Firefox

**Confirmation:**

- [* ] I have read and followed all the instructions provided in the README.md.
- [ ] I am on the latest version of both Open WebUI and Ollama.
- [* ] I have included the browser console logs.
- [* ] I have included the Docker container logs.
- [* ] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

install v0.4.8 on pip
and the action job work well

## Actual Behavior:

Because in the Actions,the pip is not uploading[says Open-Webui reached the pip package 100MB limit],so unable to install it in pip

## Description

**Bug Summary:**
project reached pip size limit 100MB

## Reproduction Details

**Steps to Reproduce:**
You can try to upload it to pip
## Logs and Screenshots

**Browser Console Logs:**
no

**Docker Container Logs:**
no

**Screenshots/Screen Recordings (if applicable):**
no
## Additional Information

nothing

**Comment by Dnamb** [comment]
Workaround if you still want to install it, download the `open-webui-0.4.8.tar.gz` file from the releases page and install it via pip (make sure you have nodejs/npm installed)
`pip install open-webui-0.4.8.tar.gz`

**Comment by Dnamb** [comment]
Workaround if you still want to install it, download the `open-webui-0.4.8.tar.gz` file from the releases page and install it via pip (make sure you have nodejs/npm installed)
`pip install open-webui-0.4.8.tar.gz`

**Comment by hashms0a** [comment]
This is from the logs:

> Transparency log entry created with index: 153947321
Uploading distributions to https://upload.pypi.org/legacy/
Uploading open_webui-0.4.8-py3-none-any.whl

> WARNING  Error during upload. Retry with the --verbose option for more details. 
> 
> ERROR    HTTPError: 400 Bad Request from https://upload.pypi.org/legacy/        
>          File too large. Limit for project 'open-webui' is 100 MB. See          
>          https://pypi.org/help/#file-size-limit for more information.

**Comment by safe049** [comment]
can anyone please try to build a pip package? because i'm in china,the network issue make me unable to download onnxruntime-node from npm

**Comment by tjbck** [comment]
https://github.com/pypi/support/issues/5250

**Comment by cl93a** [comment]
Same here; Upgrading pip doesn't go to version v0.4.8 (remains at v0.4.7).

**Comment by medul6** [comment]
It's the same for me, under macOS 15.2:
"Requirement already satisfied: open-webui in /Applications/Python/open-webui/lib/python3.11/site-packages (0.4.7)"

**Comment by i0ntempest** [comment]
See the issue above. Until pypi approves the file size limit increase for open webui 0.4.8 cannot be uploaded.

**Comment by tjbck** [comment]
If we want this to be expedited, comments should be left here: https://github.com/pypi/support/issues/5250

There's nothing we can do on our end.

**Comment by Raven-Beholder** [comment]
1. Download the `open-webui-0.4.8.tar.gz` file, and unzip the package
2. `cd ./open-webui-0.4.8`
2. run `python -m build`

hint: NodeJS `npm` is required for building Open Webui

**Comment by dannys-platformsh** [comment]
pypi updated to allow 200MB 
https://github.com/pypi/support/issues/5250#issuecomment-2543232065

Can 0.48 be uploaded to pypi so we may update using pip - thanks

**Comment by tjbck** [comment]
Resolved!
