### ISSUE TITLE
issue: pdf export

### ISSUE THREAD

**Issue by Aleprex** [open-webui/open-webui#7684]
# Bug Report

## Environment

- **Open WebUI Version:** 0.4.8
- **Ollama (if applicable):** 0.4.7

- **Operating System:** Ubuntu 22.04]
- **Browser :**ALL

## Expected Behavior:
Simply export in pdf file

## Actual Behavior:

Works only in json and txt format

## Description
When you try to export the chat in PDF format simply nothing happens and checking on the log console you have an error that I report below.

But I noticed that if you export some old chat made with hide versions then I can export it.

## Logs and Screenshots
**Browser Console Logs:**
{
    "detail": "Character \"’\" at index 43 in text is outside the range of characters supported by the font used: \"courier\". Please consider using a Unicode font."
}

![image](https://github.com/user-attachments/assets/084b3c10-5b6e-4522-a4c4-63455a7f5c17)

**Comment by tjbck** [comment]
should be fixed on dev!

**Comment by silentoplayz** [comment]
I can confirm that downloading a chat as .PDF works on the dev branch.

**Comment by gigascake** [comment]
on the ver 0.5.3, pdf download success, but markdown format error, all charactor format is not regular. openwebui view is different  from pdf view.
