### ISSUE TITLE
 Add option to disable auto-completion

### ISSUE THREAD

**Issue by codeMonkey-shin** [open-webui/open-webui#7703]
It would be very helpful to have an option to disable the auto-completion feature. In some cases, it can be more of a hindrance than a help. Please consider adding a setting to turn it off.

Thanks!

**Comment by silentoplayz** [comment]
Adding onto this, I believe that the auto-completion feature should be de-coupled from the `Rich Text Input for Chat` toggle, if this is possible.

**Comment by tjbck** [comment]
Is definitely possible globally, but I'll add an option for individual toggles as well.

**Comment by codeMonkey-shin** [comment]
where is the global options?!

**Comment by panuud** [comment]
Is Admin Panel → Settings → Interface → Autocomplete Generation what you're looking for?

**Comment by silentoplayz** [comment]
> Isn't this available today in 0.4.8? ![image](https://private-user-images.githubusercontent.com/3945114/393981795-7db78d90-79fb-4811-b6b5-cd8600a8df87.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzQwMjc5MjQsIm5iZiI6MTczNDAyNzYyNCwicGF0aCI6Ii8zOTQ1MTE0LzM5Mzk4MTc5NS03ZGI3OGQ5MC03OWZiLTQ4MTEtYjZiNS1jZDg2MDBhOGRmODcucG5nP1gtQW16LUFsZ29yaXRobT1BV1M0LUhNQUMtU0hBMjU2JlgtQW16LUNyZWRlbnRpYWw9QUtJQVZDT0RZTFNBNTNQUUs0WkElMkYyMDI0MTIxMiUyRnVzLWVhc3QtMSUyRnMzJTJGYXdzNF9yZXF1ZXN0JlgtQW16LURhdGU9MjAyNDEyMTJUMTgyMDI0WiZYLUFtei1FeHBpcmVzPTMwMCZYLUFtei1TaWduYXR1cmU9NmM3ZDJjMmU2NmU2NzZlNWZmNWFjNTIwZDdlZTdjNWQ5ODRkNzUyMTA4MDM0NDY5NDg3ZDU5N2M3NDNiZTY4ZSZYLUFtei1TaWduZWRIZWFkZXJzPWhvc3QifQ.sKOUHTOwDVLjUFd2etDktImgQxKPGgdUsAb8GzNw-fs)

Yep, it's available. You made me go hunt for it and I spotted the global setting to toggle auto-completion. 😄
