### ISSUE TITLE
indents in formatted text, such as markdown, get cleared when starting a new chat or sending a new message

### ISSUE THREAD

**Issue by Eve-146T** [open-webui/open-webui#7746]
Expected behavior: The indents stay 

Observed behavior: the indents get removed, unless editing a message

[output.webm](https://github.com/user-attachments/assets/afad04a7-e313-45d2-b29a-9e9cd001c71d)

**Comment by tjbck** [comment]
Please update to the latest.

**Comment by Eve-146T** [comment]
![image](https://github.com/user-attachments/assets/5719fffc-16aa-4446-b0ff-947a54e64ffa)
