### ISSUE TITLE
indents in formatted text, such as markdown, get cleared when starting a new chat or sending a new message

### ISSUE THREAD

**Issue by Eve-146T** [open-webui/open-webui#7747]
Expected behavior: The indents stay

Observed behavior: the indents get removed, unless editing a message

[output.webm](https://github.com/user-attachments/assets/afad04a7-e313-45d2-b29a-9e9cd001c71d)

Open Webui Version: 0.4.8 (latest) 
docker
debian

![image](https://github.com/user-attachments/assets/e68639b1-f7a4-40cd-8298-f32d38cfd432)

**Comment by tjbck** [comment]
Screen-recording shows its not the latest. Please use the latest version.
