### ISSUE TITLE
UI not loading anymore after setting DEFAULT_PROMPT_SUGGESTIONS

### ISSUE THREAD

**Issue by StefanDanielSchwarz** [open-webui/open-webui#776]
# Bug Report

## Description

**Bug Summary:**
Setting DEFAULT_PROMPT_SUGGESTIONS to a non-empty value breaks the UI. It's not loading anymore, shows "Error loading request body into a dictionary: Expecting value: line 1 column 1 (char 0)" in the log.

**Steps to Reproduce:**
Set envvar "DEFAULT_PROMPT_SUGGESTIONS" to a non-empty value.

**Expected Behavior:**
I want to set the default prompt suggestions through the envvar. Apparently I'm not setting it correctly (couldn't find any documentation on it except for the code itself, but it's unclear to me how to set the Python list and dictionaries in a bash envvar!). I'd expect an incorrect variable to be reported in the log and ignored instead of breaking the whole UI.

**Actual Behavior:**
Website stays blank, Docker logs show: "Error loading request body into a dictionary: Expecting value: line 1 column 1 (char 0)"

## Environment

- **Operating System:** Ubuntu 22.04 LTS
- **Browser (if applicable):** any

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I have reviewed the troubleshooting.md document.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
Doesn't show an error

**Docker Container Logs:**
open-webui   | Error loading request body into a dictionary: Expecting value: line 1 column 1 (char 0)

**Screenshots (if applicable):**
n/a

## Installation Method

Docker

## Additional Information

I'm setting DEFAULT_PROMPT_SUGGESTIONS in the .env file. Setting it correctly should fix my issue, however, an incorrect setting should IMHO not completely break the app but just log a warning.

Anyway, thanks for making such a beautiful und full-featured app! This really takes ollama's usefulness up another notch. So keep up the great work, and I'm happy to see Open WebUI becoming more universal.

**Comment by tjbck** [comment]
Thanks for reporting this issue! Looking at it now, it doesn't make much sense to have it as env var, I must've been in a rush to get this feature out 😅 With #810, you would be able to edit default prompt suggestions via config.json file. `-v /dir/to/config.json:/app/backend/data/config.json` flag should do the job with docker containers!
