### ISSUE TITLE
[BUG] Error when quickly disabling multiple models.

### ISSUE THREAD

**Issue by SammySnake-d** [open-webui/open-webui#7810]
# Bug Report

## Installation Method

Docker Deployment on Hugging Face

## Environment

- **Open WebUI Version:** [v0.4.8]

- **Operating System:** [Windows 10, ]

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

When I disable/enable multiple models at once, there is no failure in disabling/enabling.

## Actual Behavior:

Rapidly disabling/enabling multiple models causes the status to toggle repeatedly.

## Description

**Bug Summary:**
Model enable/disable status, toggle exception.

## Reproduction Details

**Steps to Reproduce:**
[Outline the steps to reproduce the bug. Be as detailed as possible.]

## Logs and Screenshots

**Browser Console Logs:**

**Docker Container Logs:**

**Screenshots/Screen Recordings (if applicable):**
![PixPin_2024-12-12_20-57-08](https://github.com/user-attachments/assets/2f3fc0a3-f9c0-4b73-af50-553e1576eaa2)

## Additional Information
steps:
1.Quickly enable/disable the model.
2.Quickly enable/disable multiple models at once, making it easier to reproduce bugs.

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by silentoplayz** [comment]
I can confirm this bug is reproducible for me on the latest dev commit of the dev branch.

**Comment by surajrimal07** [comment]
I can confirm this as well.

**Comment by Protomyst** [comment]
me too, it's annoying

**Comment by tjbck** [comment]
Should be addressed in dev, testing wanted here.

**Comment by silentoplayz** [comment]
It appears fixed on my end on the latest dev commit.
