### ISSUE TITLE
PyPi PIP Update Version

### ISSUE THREAD

**Issue by mazvi** [open-webui/open-webui#7813]
# Feature Request

**Is your feature request related to a problem? Please describe.**
No

**Describe the solution you'd like**
Please also update on PIP https://pypi.org/project/open-webui/

**Describe alternatives you've considered**
N/A

**Additional context**
N/A

**Comment by hady2010** [comment]
+1

**Comment by tjbck** [comment]
Please check for duplicate issues: #7677
