### ISSUE TITLE
Regular Users Cannot See Models

### ISSUE THREAD

**Issue by kkrick-sdsu** [open-webui/open-webui#7816]
# Bug Report
---

## Installation Method
Running in Kubernetes with image `ghcr.io/open-webui/open-webui:git-bfdbb2d-cuda`

Running Ollama side-by-side in the same namespace.

## Environment

- **Open WebUI Version:** v0.4.8
- **Ollama (if applicable):** 0.5.1

- **Operating System:** Ubuntu 22.04
- **Browser (if applicable):** Edge 131.0.2903.86, Safari 18.1.1

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [X] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [X] I have included the Docker container logs.
- [X] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Regular users should be able to see models in the New Chat > Select a model dropdown. Users should be able to see a list of models via API call to /api/models,

## Actual Behavior:

Regular users see "No results found" in New Chat dropdown. Users get empty array for API call to /api/models.

Admin users can see all Ollama models. Users promoted to admin can see all models, but when put back to the user level can again see no models.

## Description

**Bug Summary:**
It appears that regular users are not able to retrieve Ollama models. The API call returns an empty array.

## Reproduction Details

**Steps to Reproduce:**
1. Login to Open Web UI
2. Click New Chat
3. Click Select a model
4. See No results found

I would be happy to add a project contributor as a regular user to my instance to test this issue.

## Logs and Screenshots

**Docker Container Logs:**
Open Web UI logs:

```
INFO:     connection open
INFO:     2600:1700:6ecc:c000:1cf9:c0b5:ff23:fb05:0 - "GET /ws/socket.io/?EIO=4&transport=polling&t=PEyU0ti&sid=oeodO1GqKsdzMRbQAABI HTTP/1.1" 200 OK
INFO:     2600:1700:6ecc:c000:1cf9:c0b5:ff23:fb05:0 - "GET /api/changelog HTTP/1.1" 200 OK
INFO:     2600:1700:6ecc:c000:1cf9:c0b5:ff23:fb05:0 - "GET /api/v1/users/user/settings HTTP/1.1" 200 OK
INFO:     2600:1700:6ecc:c000:1cf9:c0b5:ff23:fb05:0 - "GET /ws/socket.io/?EIO=4&transport=polling&t=PEyU0u1&sid=oeodO1GqKsdzMRbQAABI HTTP/1.1" 200 OK
INFO  [open_webui.apps.openai.main] get_all_models()
INFO:     2600:1700:6ecc:c000:1cf9:c0b5:ff23:fb05:0 - "GET /opensearch.xml HTTP/1.1" 200 OK
INFO  [open_webui.apps.ollama.main] get_all_models()
INFO:     2600:1700:6ecc:c000:1cf9:c0b5:ff23:fb05:0 - "GET /api/models HTTP/1.1" 200 OK
INFO:     2600:1700:6ecc:c000:1cf9:c0b5:ff23:fb05:0 - "GET /api/v1/configs/banners HTTP/1.1" 200 OK
INFO:     2600:1700:6ecc:c000:1cf9:c0b5:ff23:fb05:0 - "GET /api/v1/tools/ HTTP/1.1" 200 OK
INFO:     2600:1700:6ecc:c000:1cf9:c0b5:ff23:fb05:0 - "GET /api/v1/chats/all/tags HTTP/1.1" 200 OK
INFO:     2600:1700:6ecc:c000:1cf9:c0b5:ff23:fb05:0 - "GET /api/v1/users/user/settings HTTP/1.1" 200 OK
INFO:     2600:1700:6ecc:c000:1cf9:c0b5:ff23:fb05:0 - "GET /api/v1/chats/pinned HTTP/1.1" 200 OK
INFO:     2600:1700:6ecc:c000:1cf9:c0b5:ff23:fb05:0 - "GET /api/v1/folders/ HTTP/1.1" 200 OK
INFO:     2600:1700:6ecc:c000:1cf9:c0b5:ff23:fb05:0 - "GET /api/v1/chats/?page=1 HTTP/1.1" 200 OK
INFO:     2600:1700:6ecc:c000:1cf9:c0b5:ff23:fb05:0 - "GET /api/v1/chats/?page=2 HTTP/1.1" 200 OK
INFO:     2600:1700:6ecc:c000:1cf9:c0b5:ff23:fb05:0 - "GET /ollama/api/version HTTP/1.1" 200 OK
```

Ollama logs:
```
ollama.service: [GIN] 2024/12/12 - 20:05:10 | 200 |    1.350801ms |    10.244.51.20 | GET      "/api/tags"
ollama.service: [GIN] 2024/12/12 - 20:05:10 | 200 |       22.13µs |    10.244.51.20 | GET      "/api/version"
```

User call to /api/models, 200 response:
```
{
    "data": []
}
```

## Additional Information

I am running this in Kubernetes with a separate Ollama instance side-by-side in the same namespace. Verified the connection and again an admin can see all of the models in the UI and via /api/models API. Everything was working about a week ago until upgrading to latest Open WebUI. Also attempted to create groups and grant all permissions, but this did not resolve the issue either. I am wondering if this is related to the groups/permissions change?

**Comment by tjbck** [comment]
Yes, intended behaviour here. I'd strongly recommend you read all the changelogs before updating. Model permissions can be set individually. Hope that helps.

**Comment by kkrick-sdsu** [comment]
Absolutely agree and would normally do that. Just had a deployment accidentally using the main tag and an unplanned restart caused the upgrade.

In case anyone else runs into the same, the solution was to add the new environment variable "BYPASS_MODEL_ACCESS_CONTROL=true". 

Is there further documentation for this new env var? I didn't think this applied since I had not configured any access control rules. I checked the [Environment Variable Configuration][https://docs.openwebui.com/getting-started/advanced-topics/env-configuration#general) but it is not yet listed.

Anyways, thanks for the great work with this project!
