### ISSUE TITLE
feat: style model selector

### ISSUE THREAD

**Issue by RanitManik** [open-webui/open-webui#782]
# Bug Report

## Description:
The current style of the select label requires customization to ensure design consistency across the application. The existing style is the default select label style and may not align with the overall design guidelines.

## Steps to Reproduce:
1. Navigate to the webui home page.
2. Attempt to switch the chat model located at the top.

## Screenshots:
- **Chrome:**
![Chrome Screenshot](https://github.com/open-webui/open-webui/assets/138437760/da804dab-3cc6-4ea5-8cdf-2fd6f3c3adb2)
- **Firefox:**
![Firefox Screenshot](https://github.com/open-webui/open-webui/assets/138437760/b4a81726-0ddd-4845-94f7-cce66bee32f8)

## Additional Information:
- **Browsers Tested:** Chrome, Firefox
- _Feel free to reach out if further clarification or information is needed._

**Comment by justinh-rahb** [comment]
I do get some inconsistent styling on Chrome...

**If it's a regular tab:**
<img width="675" alt="Screenshot 2024-02-19 at 5 49 54 PM" src="https://github.com/open-webui/open-webui/assets/52832301/3cba118a-e5a9-4ab1-9d6f-908f75747ffb">

**Versus an installed PWA:**
<img width="675" alt="Screenshot 2024-02-19 at 5 50 07 PM" src="https://github.com/open-webui/open-webui/assets/52832301/3ef6367b-4fe4-4931-9e45-88cf726ff3d8">

**Comment by jannikstdl** [comment]
I don't think that this is a big deal

**Comment by justinh-rahb** [comment]
> I don't think that this is a big deal

Agreed, I think there's no need for a PR on this alone absent any other issue with usability. This seems to just be cosmetic.

**Comment by tjbck** [comment]
Closing in favour of #1281, let's continue our discussion there!
