### ISSUE TITLE
feat: multiple Ollama servers in one webui + load balancing

### ISSUE THREAD

**Issue by nick-tonjum** [open-webui/open-webui#788]
The #1 downside to Ollama is the fact that it can only process one request at a time, no matter what hardware is available. Right now my solution is to have multiple Ollama instances running, so when one is in use on one graphics card I can use the other instance on the other card.

It would be nice to see open-webui allow multiple Ollama server connections, as I think an environment with multiple users using it simultaneously could really benefit from this. I myself have one machine with two Ollama instances (one per graphics card), and a whole different machine off-site that also has an Ollama instance. Utilizing all three of them would be nice for multiple concurrent users

**Comment by justinh-rahb** [comment]
This might interest you, somebody made a proxy load-balancer specifically for Ollama: https://github.com/ParisNeo/ollama_proxy_server

That said, I think our present direction will eventually bring us here, we're planning to support much more than one backend. If we can do internal load-balancing that'd be neat too.

**Comment by SurvivaLlama** [comment]
Wh

> This might interest you, somebody made a proxy load-balancer specifically for Ollama: https://github.com/ParisNeo/ollama_proxy_server
> 
> That said, I think our present direction will eventually bring us here, we're planning to support much more than one backend. If we can do internal load-balancing that'd be neat too.

When you get to that point I have systems that can test.

**Comment by BigBIueWhale** [comment]
I created a solution https://github.com/BigBIueWhale/ollama_load_balancer
It's a Rust utility that load balances multiple Ollama servers

**Comment by stanthewizzard** [comment]
> OpenWebUI does support load balancing on its own. You do not need to use any third party plugins as of now!

Sorry could you explain how ?
Thanks

**Comment by xuyangbocn** [comment]
If using AWS, below is what i did
https://github.com/xuyangbocn/terraform-aws-self-host-llm
https://youtu.be/hRJEREemyos

**Comment by stanthewizzard** [comment]
Self hosted and not on ads :(

**Comment by xuyangbocn** [comment]
@stanthewizzard 
Under Open WebUI Admin setting >> Setting >> Connections >> Ollama API, you can specify multiple endpoints, one for each Ollama deployment.

<img width="616" alt="Image" src="https://github.com/user-attachments/assets/fe8b7c2f-9c4c-45fb-90df-d2e01a5a3ef0" />

**Comment by stanthewizzard** [comment]
Thanks for the advice 😇 
I already have that. But it doesn't load balance ?

**Comment by xuyangbocn** [comment]
Really? Thought i havent tried on my own, but seemingly this allows differnet models to be directed to different endpoints.

**Comment by stanthewizzard** [comment]
Same model on 2 computers and only one is used. Always the same btw

**Comment by stanthewizzard** [comment]
exactly what I'm looking for

**Comment by gonzalu** [comment]
> I'm adding a silly question - if I have multiple ollama connections configured is there a way to know which I'm using ? E.g. if host1 and host2 both have "modelX" can I select on which one the query will be executed ?

I have the exact same question :D Seems like it should be as easy as picking a server but I am puzzled. 

I have Ollama running on a Jetson Orin Nano 8GB Dev Plus and also on an AMD 7940HS 32GB RAM CPU system. I have both configured on my OpenWebUI (see below) but for the life of me, I can't figure out how I pick one over the other?  

![Image](https://github.com/user-attachments/assets/3ab6f10e-22a7-4fea-b215-20fcd4040e41)

Probably easy and obvious but I am a complete n00b :P 

![Image](https://github.com/user-attachments/assets/a4ffc7c4-ef6f-47e3-8826-755beb085638)

Thanks.

**Comment by d-shehu** [comment]
What is the algo for picking the model if there are multiple endpoints/servers. Does it go down the list as configured in "connections" and pick the 1st working connection?

Fallback logic would be nice in lieu of something as complicated as a gateway. Thanks.

**Comment by gonzalu** [comment]
I found that you can prefix each server with a tag and then when you HOVER OVER the models in the selection dropdown, the tooltip will show you the server it is from. Good enough for me until a more elegant way is available. 

![Image](https://github.com/user-attachments/assets/14a92ec2-0dc2-4e16-9ccb-11e6d0226f57)

![Image](https://github.com/user-attachments/assets/fc754429-0a9f-4f29-b53f-0acf2bc1c48b)

**Comment by WyattLiu** [comment]
second this, right now I have 2 servers of the same model, what open webui currently offer is fail safe, one is backing up for the other... if we can somehow use both and have a little queue, it would be good.

**Comment by GTez** [comment]
I'd love this.  I'm using a HAProxy right now to proxy the ollama calls in order to load balance, but would way rather it be smart, understand what's loaded, then farm out the requests properly.

**Comment by apunkt** [comment]
Used HAProxy until now,
which is great, but not aware of which model is loaded on which ollama server, thus having mixed results.

I am successful now with [NOMYO Router](https://github.com/nomyo-ai/nomyo-router)

**Comment by tumstech** [comment]
An Intelligent Router / Load Balancer would be a greate option. 
In a setup like two base Mac Mini with 16 GB, When i want to use gemma4:e4b and an embedding model qwen3-embedding:8b (Configured directly in Documents section of admin settings), both models try to run on the same machine and end up sharing the model with CPU instead of 100% GPU, due to lack of memory.

All machines have same set of models, so an intelligent way of identifying that one model is loaded in this machine, and not enough memory for the second one, so send the request to another machine having same model would be a greate feature.
