### ISSUE TITLE
Switching chat topic before the current chat response is finished, the last entry completely disappears

### ISSUE THREAD

**Issue by robbyjo** [open-webui/open-webui#7884]
Open WebUI Version: 0.4.8
Ollama Version: 0.5.1
OS: Windows 11
RAM: 192GB
GPU: 2x4090 RTX
Reproducibility: Always
Model: Any model

Installation: Docker CUDA version (Docker Desktop v4.37)

When the answer is pretty long (and thus takes some time) in a chat topic, and I switch to another chat topic and return, the last entry (and the partial answer) was gone. Yet, my computer is still busy churning the answer. When it is done working with that answer and I return to that chat topic, it appears that the entry was completely gone.

Expected behavior: The entry should still be there. I expect to see the answer continues to stream.

This happens since 0.4.x.

**Comment by tjbck** [comment]
Actively being worked on, #2647
