### ISSUE TITLE
Adding models via admin/settings is broken

### ISSUE THREAD

**Issue by dimakovalenko-united-ctm** [open-webui/open-webui#7889]
# Bug Report

Adding new models via Admin portal is currently broken.

Steps:

1. Navigate to `/admin/settings`
2. Click on Models
3. Click on Configure gear in top right corner
4. Click on `+` in model select
5. Nothing happens

Previous behavior in much older version: A text field would open up with model to be inputed
Workaround: Search for new model name in New Chat dialog

## Installation Method

[Describe the method you used to install the project, e.g., git clone, Docker, pip, etc.]

## Environment

- **Open WebUI Version:** v0.4.7, v0.4.8
`docker run -d -p 3000:8080 --gpus=all -v ollama:/root/.ollama -v open-webui:/app/backend/data --name open-webui --restart always ghcr.io/open-webui/open-webui:ollama`

- **Operating System:** Ubuntu
- **Browser (if applicable):** All

**Confirmation:**

- [ X ] I have read and followed all the instructions provided in the README.md.
- [ X ] I am on the latest version of both Open WebUI and Ollama.
- [ X ] I have included the browser console logs.
- [ X ] I have included the Docker container logs.
- [ X ] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

[Describe what you expected to happen.]

## Actual Behavior:

[Describe what actually happened.]

## Description

**Bug Summary:**
[Provide a brief but clear summary of the bug]

## Reproduction Details

**Steps to Reproduce:**
[Outline the steps to reproduce the bug. Be as detailed as possible.]

## Logs and Screenshots

**Browser Console Logs:**
user-count {count: 1}
+layout.svelte:82 usage {models: Array(0)}
Chat.svelte:337 mounted
RichTextInput.svelte:129 
RichTextInput.svelte:160 [tiptap warn]: Duplicate extension names found: ['codeBlock']. This can lead to issues.
resolve @ index.js:1158
un @ index.js:1144
createExtensionManager @ index.js:4470
_g @ index.js:4302
(anonymous) @ RichTextInput.svelte:160
await in (anonymous)
J @ utils.js:41
(anonymous) @ Component.js:47
_t @ scheduler.js:99
Promise.then
ut @ scheduler.js:20
ht @ Component.js:81
(anonymous) @ Component.js:139
(anonymous) @ +layout.svelte:203
await in (anonymous)
J @ utils.js:41
(anonymous) @ Component.js:47
_t @ scheduler.js:99
Promise.then
ut @ scheduler.js:20
ht @ Component.js:81
(anonymous) @ Component.js:139
(anonymous) @ +layout.svelte:189
await in (anonymous)
J @ utils.js:41
(anonymous) @ Component.js:47
_t @ scheduler.js:99
jt @ Component.js:164
ht @ root.svelte:23
tt @ client.js:449
W @ client.js:1425
await in W
et @ client.js:382
en @ client.js:1751
sn @ client.js:310
(anonymous) @ (index):102
Promise.then
(anonymous) @ (index):101Understand this warningAI
MessageInput.svelte:257 destroy

**Docker Container Logs:**
INFO:     204.111.113.79:0 - "GET /api/webhook HTTP/1.1" 200 OK
INFO:     204.111.113.79:0 - "GET /api/v1/auths/admin/config HTTP/1.1" 200 OK
INFO:     204.111.113.79:0 - "GET /api/v1/auths/admin/config/ldap/server HTTP/1.1" 200 OK
INFO:     204.111.113.79:0 - "GET /api/v1/auths/admin/config/ldap HTTP/1.1" 200 OK
INFO:     204.111.113.79:0 - "GET /api/v1/configs/models HTTP/1.1" 200 OK
INFO:     204.111.113.79:0 - "GET /api/v1/models/base HTTP/1.1" 200 OK
INFO  [open_webui.apps.openai.main] get_all_models()
INFO  [open_webui.apps.ollama.main] get_all_models()
[GIN] 2024/12/16 - 16:23:55 | 200 |     363.913µs |       127.0.0.1 | GET      "/api/tags"
INFO:     204.111.113.79:0 - "GET /api/models/base HTTP/1.1" 200 OK

**Screenshots/Screen Recordings (if applicable):**
![add_new_model_plus](https://github.com/user-attachments/assets/bb942f17-cb52-4d54-b4e7-c074a045951c)

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
Please read the change logs, you can add models from Ollama connection area.
