### ISSUE TITLE
Application Freezes with enabled Hybrid search

### ISSUE THREAD

**Issue by gabriel-ecegi** [open-webui/open-webui#7913]
# Bug Report

---

## Installation Method

Conda environment with Open WebUI (`main` branch, v0.4.8).  
Issue is reproducible in Docker as well.

## Environment

- **Open WebUI Version:** v0.4.8 (main branch, 2024-12-07)  
- **Operating System:** macOS 15.2  
- **Browser (if applicable):** Chrome 120.0  

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.  
- [x] I am on the latest version of Open WebUI.  
- [x] I have included the browser console logs.  
- [x] I have included the Docker container logs.  
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

---

## Expected Behavior:

The application should remain responsive while processing a request to the `/completions` endpoint with `ENABLE_RAG_HYBRID_SEARCH` enabled.

---

## Actual Behavior:

The application freezes during the execution of the `/completions` endpoint when `ENABLE_RAG_HYBRID_SEARCH` is enabled.  
- The UI becomes unresponsive and no further interactions can be made.  
- Once the `/completions` request completes, the app becomes functional again.

---

## Description

**Bug Summary:**  
When `ENABLE_RAG_HYBRID_SEARCH` is turned on and the **reranking model** `BAAI/bge-reranker-v2-m3` is used, calling the `/completions` endpoint causes the application to freeze until the request finishes processing. This issue is consistent and reproducible.

---

## Reproduction Details

**Steps to Reproduce:**  
1. Install Open WebUI using Conda or Docker.  
2. Enable `ENABLE_RAG_HYBRID_SEARCH` in the settings.  
3. Set the reranking model to `BAAI/bge-reranker-v2-m3`.  
4. Trigger a request to the `/completions` endpoint (e.g., perform a query using HybridSearch).  
5. Observe that:  
   - The application freezes during the request execution.  
   - No interactions can be performed until the `/completions` endpoint finishes processing.  
6. After the request completes, the app returns to normal.

---

## Logs and Screenshots

**Browser Console Logs:**  
N/A (no relevant logs).

**Docker Container Logs:**  
N/A (no relevant logs).

**Screenshots/Screen Recordings (if applicable):**  
N/A

---

## Additional Information

- The issue consistently occurs during `/completions` calls with HybridSearch enabled.  
- The reranking model in use is `BAAI/bge-reranker-v2-m3`.  
- CPU or memory usage appears normal during the freeze.  
- This behavior happens both in Conda and Docker installations.

---

## Note

Please let me know if further testing or logs are required to resolve this issue. Thank you for maintaining Open WebUI!

**Comment by mahenning** [comment]
What `Embedding Model` did you set?

**Comment by gaboe** [comment]
I use BAAI/bge-reranker-v2-m3, also.

**Comment by tjbck** [comment]
Closing in favour of #7942
