### ISSUE TITLE
Bug: Configure model panel does not show newly enabled (or hide just disabled) models until refresh

### ISSUE THREAD

**Issue by i0ntempest** [open-webui/open-webui#7929]
# Bug Report

## Installation Method
Barebone pip

## Environment

- **Open WebUI Version:** 0.4.8
- **Ollama (if applicable):** 0.5.3

- **Operating System:** macOS 15.2
- **Browser (if applicable):** Safari 18.2

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:
Configure model panel (where one reorders models) should show all and only show enabled models.

## Actual Behavior:
Configure model panel does not show newly enabled (or hide just disabled) models until the page is refreshed.

## Description

**Bug Summary:**
See above

## Reproduction Details

**Steps to Reproduce:**
1. Have a few models available
2. Disable one of them, check the Configure model panel, the disabled model is still there
3. Refresh the page, check again, that model is gone
4. Enable the disabled model, check the Configure model panel, the enabled model is not there
5. Refresh the page, check again, that model is now there

## Logs and Screenshots

**Browser Console Logs:**
```
[Log] [Wipr Extra 2.1.3] Loaded 4182 rules, active variants: WW (utils.js, line 2)
[Log] [Wipr Extra 2.1.3] Not required on this domain (utils.js, line 2)
[Log] Backend config: – {status: true, name: "Nucleus Core Intelligence - Studio (Open WebUI)", version: "0.4.8", …} (0.B4oTNTAn.js, line 1)
{status: true, name: "Nucleus Core Intelligence - Studio (Open WebUI)", version: "0.4.8", default_locale: "", oauth: {providers: {}}, …}Objectaudio: {tts: {engine: "", voice: "alloy", split_on: "punctuation"}, stt: {engine: ""}}Objectdefault_locale: ""default_models: "llama3.3:latest"default_prompt_suggestions: [{title: ["Help me study", "vocabulary for a college entrance exam"], content: "Help me study vocabulary: write a sentence for me …e blank, and I'll try to pick the correct option."}, {title: ["Give me ideas", "for what to do with my kids' art"], content: "What are 5 creative things I could do with my kids…o throw them away, but it's also so much clutter."}, {title: ["Tell me a fun fact", "about the Roman Empire"], content: "Tell me a random fun fact about the Roman Empire"}, {title: ["Show me a code snippet", "of a website's sticky header"], content: "Show me a code snippet of a website's sticky header in CSS and JavaScript."}, {title: ["Explain options trading", "if I'm familiar with buying and selling stocks"], content: "Explain options trading in simple terms if I'm familiar with buying and selling stocks."}, {title: ["Overcome procrastination", "give me tips"], content: "Could you start by asking me about instances when …and then give me some suggestions to overcome it?"}, {title: ["Grammar check", "rewrite it for better readability "], content: "Check the following sentence for grammar and clari…adability while maintaining its original meaning."}]Array (7)features: {auth: true, auth_trusted_header: false, enable_ldap: false, enable_api_key: true, enable_signup: false, …}Objectfile: {max_size: null, max_count: null}Objectname: "Nucleus Core Intelligence - Studio (Open WebUI)"oauth: {providers: {}}Objectpermissions: {workspace: Object, chat: Object}Objectstatus: trueversion: "0.4.8"Object Prototype
[Log] connected – "SYcH3OLoPKcOhndvAAAH" (0.B4oTNTAn.js, line 1)
[Log] user-count – {count: 1} (0.B4oTNTAn.js, line 1)
[Log] usage – {models: []} (0.B4oTNTAn.js, line 1)
```

**Docker Container Logs:**
N/A

**Screenshots/Screen Recordings (if applicable):**
N/A
If needed I can produce a screen recording.

## Additional Information
N/A

**Comment by tjbck** [comment]
This probably has something to do with the model list caching logic, should be somewhat addressed in dev. Testing wanted here!

**Comment by i0ntempest** [comment]
Yup, latest dev does not have this problem.
