### ISSUE TITLE
The table headers in Markdown syntax cannot be copied.

### ISSUE THREAD

**Issue by cr-zhichen** [open-webui/open-webui#7941]
# Bug Report

## Installation Method

docker-compose

## Environment

- **Open WebUI Version:** v0.4.8
- **Operating System:** Windows 10
- **Browser:** Edge 131.0.2903.99 (Official Build) (64-bit)

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

The table headers displayed in the chat can be selected and copied, and the generated CSV file after clicking the download option includes headers.

## Actual Behavior:

The table headers displayed in the chat cannot be selected or copied, and the generated CSV file after clicking the download option does not have headers.

## Description

**Bug Summary:**
Table headers in the chat interface are not selectable or copiable. Additionally, the exported CSV file lacks table headers.

## Reproduction Details

**Steps to Reproduce:**

1. Navigate to the chat interface where a table is displayed.
2. Attempt to select and copy the table headers.
3. Click the download option to generate a CSV file of the table.
4. Open the CSV file and observe the absence of table headers.

**Comment by tjbck** [comment]
Fixed on dev!
