### ISSUE TITLE
You are able to type text into generated code blocks.

### ISSUE THREAD

**Issue by WestonHanners** [open-webui/open-webui#7945]
## Installation Method

Installed via docker following the instructions in the README.md.

## Environment

- **Open WebUI Version:** 0.4.8
- **Ollama (if applicable):** 0.4.5

- **Operating System:** Ubuntu 24.10
- **Browser (if applicable):** Firefox 133

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

You cannot type in code blocks

## Actual Behavior:

You can type in code blocks

## Description

**Bug Summary:**
I am able to type text in code blocks.

## Reproduction Details

**Steps to Reproduce:**
Ask Ollama to generate a code block ie. "generate a hello world application in javascript"
Try to type in the code block

## Logs and Screenshots
![image](https://github.com/user-attachments/assets/45faa740-ffc7-4502-8d1b-babdbeceb14a)

**Comment by tjbck** [comment]
Intended behaviour.
