### ISSUE TITLE
feat: show popup "whats new" on pageload to summarize updates

### ISSUE THREAD

**Issue by jannikstdl** [open-webui/open-webui#799]
**Describe the solution you'd like**
Since the developement of this repo is really fast it would be nice to have (with every release change) a little popup on start to show the "average consumer" new functionalities.

This should be a modal with texts reffering to `constants.ts` in my mind.

**Additional context**
Something like this but with "what's new" (or such tooltips like the blue one)
![Screenshot 2024-02-19 125305](https://github.com/open-webui/open-webui/assets/69747628/14a3daba-f701-4590-8d9b-4d0e36b48edf)

**Comment by justinh-rahb** [comment]
LM Studio also does similar and I think it's a great idea.

**Comment by jannikstdl** [comment]
Working on it.. @tjbck any idea how to set up a state that the Modal is only shown once if you pull a new version? I would do this with a localstorage bool, since this shouldn't be resetted?
