### ISSUE TITLE
Context length parameter doesn't work

### ISSUE THREAD

**Issue by nengoxx** [open-webui/open-webui#7991]
# Bug Report

## Installation Method

pip

## Environment

- **Open WebUI Version:** 0.4.7

- **Operating System:** Windows 11
- **Browser (if applicable):** Firefox

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [ ] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Context shouldn't be longer than the number set in any of the options.

## Actual Behavior:

It doesn't seem to trim the context regardless of where you set it (general settings, per model or per chat).

## Description

**Bug Summary:**
Setting up a number doesn't trim the context, still sends the whole chat to the API.

## Reproduction Details

**Steps to Reproduce:**
Set up a context length in Admin Console>Models, also in the Personal settings and in the chat settings.

## Logs and Screenshots

**Screenshots/Screen Recordings (if applicable):**
![Screenshot 2024-12-21 173739](https://github.com/user-attachments/assets/ec1a4382-d46e-4a7d-9e8f-fa6243731daa)
![Screenshot 2024-12-21 173904](https://github.com/user-attachments/assets/70acbdae-1e73-4f04-bffe-7631c8b78f55)
![Screenshot 2024-12-21 173944](https://github.com/user-attachments/assets/28c1a70d-72bc-4621-ab0a-dbe36cb77e42)

## Additional Information

This makes APIs like groq's unusable for longer chats.

**Comment by tjbck** [comment]
Not what context length param is for.

**Comment by nengoxx** [comment]
Is it just for local inference requests with ollama perhaps?
