### ISSUE TITLE
Import Prompt not working at all

### ISSUE THREAD

**Issue by freeload101** [open-webui/open-webui#8040]
# Bug Report
 
<3 all the work on OpenWeb UI !!

## Installation Method
https://github.com/freeload101/SCRIPTS/blob/master/Bash/OpenWebUI_Fast.bash

## Environment

**Open WebUI Version:** 
 ghcr.io/open-webui/open-webui:dev-cuda
 
**Ollama (if applicable):** 
ollama version is 0.5.4

**Operating System:**
OS Name	Microsoft Windows 11 Pro	
Version	10.0.22621 Build 22621	

**Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]
Version 126.0.6478.115 (Official Build) (64-bit)

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [X] I am on the latest version of both Open WebUI and Ollama.
- [X] I have included the browser console logs.
- [X] I have included the Docker container logs.
- [X] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:
* Export a prompt backup
* rebuild OpenwebUI
* Import a prompt backup

## Actual Behavior:
Nothing happens on import no erro in the UI just backend : 

INFO:     47.4.236.77:0 - "POST /api/v1/prompts/create HTTP/1.1" 422 Unprocessable Entity

## Description

**Bug Summary:**
Can't import any prompts

## Reproduction Details
Cant import my old prompts or Fabric prompts that worked before 
https://github.com/freeload101/SCRIPTS/blob/master/MISC/Fabric_Prompts_Open%20WebUI%20OpenWebUI_20241112.json

**Steps to Reproduce:**
* Cant import my old prompts backup
* Cant import Fabric prompts that worked before Cant import my old prompts or Fabric prompts that worked before 
https://github.com/freeload101/SCRIPTS/blob/master/MISC/Fabric_Prompts_Open%20WebUI%20OpenWebUI_20241112.json
* cant even export a prompt , delete it and then import that deleted prompt...

## Logs and Screenshots
INFO:     47.4.236.77:0 - "POST /api/v1/prompts/create HTTP/1.1" 422 Unprocessable Entity

**Browser Console Logs:** 
 N/A ( it's a pain to sanitize HAR files ... ) I can give you console logs if you really want but this is all fresh build and it was working before on older build.

**Docker Container Logs:**
```
INFO:     47.4.236.77:0 - "POST /api/v1/prompts/create HTTP/1.1" 422 Unprocessable Entity

```

## Additional Information
If you need anything hit me up rmccurdy.com

**Comment by tjbck** [comment]
Good catch, Fixed on dev!
