### ISSUE TITLE
Annoying session_id error message

### ISSUE THREAD

**Issue by peter-ch** [open-webui/open-webui#8060]
I just upgraded to 0.5.0 and after every chat ends, a red error toast pops up saying "session_id". 
Reverting to 0.4.8 fixed it.

**Comment by peter-ch** [comment]
When I logged out and in again, it was fixed.

**Comment by tjbck** [comment]
Proper websocket support is required as mentioned in the changelogs. I'd suggest checking network configuration that might block any websocket requests.

**Comment by peter-ch** [comment]
Do you mean I should better run it in Linux?

**Comment by peter-ch** [comment]
The issue did not exist in 0.4.8. Now it's randomly back.

**Comment by Blygf** [comment]
i have the exact same problem. i went to 0.5.1, and because of some issues reverted back to 0.4.8, andd now, the session_id error message is popping up. any fixes?

**Comment by tjbck** [comment]
#8074

**Comment by Shabanione** [comment]
I also got that session id error message. In my case I solved it for now by deleting the webbrowsers cache and cookies. Probably it helps others too

**Comment by scas-johni** [comment]
Going from 0.4.8 to 0.5.4 I received this session_id error as well.  Clearing browser cache got rid of that error but now I'm getting "Network Problem" errors without much information presented.  Not seeing these problems on 0.4.8.

**Comment by saran-greytip** [comment]
I am also getting this issue on v0.5.7

**Comment by jeandelest** [comment]
Hi all. I am also getting the same issue after upgrade to v0.5.7, it wasn't there until now.
