### ISSUE TITLE
bug: Pipeline stuck at loading in UI for v0.5.0 when using docker.

### ISSUE THREAD

**Issue by ZaibanAli** [open-webui/open-webui#8061]
# Bug Report

## Installation Method

Docker

## Environment

- **Open WebUI Version:** v0.5.0

- **Operating System:** Ubuntu 24.04
- **Browser (if applicable):** Chrome

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [X] I am on the latest version of both Open WebUI and Ollama.
- [X] I have included the browser console logs.
- [X] I have included the Docker container logs.
- [X] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

- It should display the pipelines to setup the valves values

## Actual Behavior:

- Stuck at loading page

## Description

**Bug Summary:**
- Pipelines stuck at loading in UI for v0.5.0 when using docker.

## Reproduction Details

**Steps to Reproduce:**
- Run openwebui using docker
- Goto pipelines section
- Get's stuck at the pipelien page

## Logs and Screenshots

**Browser Console Logs:**
[Error on Browser with console logs](https://snipboard.io/FkQzam.jpg)

**Docker Container Logs:**
[Docker Logs](https://snipboard.io/ZBsrP4.jpg)

**Screenshots/Screen Recordings (if applicable):**
[Connection to pipelines](https://snipboard.io/ediQOk.jpg)

**Comment by tjbck** [comment]
Fixed on dev and merged to main #8063, 0.5.1 will be pushed shortly!
