### ISSUE TITLE
AUTOMATIC1111 Error

### ISSUE THREAD

**Issue by wuseluosi** [open-webui/open-webui#8079]
# Bug Report

## Installation Method

[Docker]

## Environment

- **Open WebUI Version:** [e.g., v0.5.0]

[Describe what you expected to happen.]

Using the Automatic1111 Image Generation API

[Describe what actually happened.]

[ERROR: get_automatic1111_api_auth() missing 1 required positional argument: 'request']
AUTOMATIC1111 Api authentication string missing request

![error](https://github.com/user-attachments/assets/e94712e2-8425-4349-b262-dc915ddd2654)

**Comment by tjbck** [comment]
Please check for duplicate issues first.
