### ISSUE TITLE
Network problem behind reverse proxy

### ISSUE THREAD

**Issue by N4S4** [open-webui/open-webui#8104]
Hello, thank you for the amazing repo.
I am having an issue since the 0.51 update, 
If I access open-webui from local ip everything works as expected. While if i access it from remote behind reverse proxy and start a chat gives me "network problem" error. I can see the model is loaded and start inference but the answer is always the error.

Could someone help me?

Thank you

![Screenshot_20241226_082427_Samsung Internet.jpg](https://github.com/user-attachments/assets/2e5efd95-4c60-4f78-8b19-21283b9201a4)

**Comment by galvanoid** [comment]
Same issue here.

Thx.

**Comment by oldskewlcool** [comment]
Also confirm this issue. Occurred in v0.5.0 and also still occurring on V0.5.1.

Using reverse proxy with custom header for auth (WEBUI_AUTH_TRUSTED_EMAIL_HEADER=X-User-Email) to avoid local network users needing to log in and nginx for the reverse proxy.

Occurs regardless of model used resulting in the installation being non-functional for all intents and purposes.

No issues prior to the upgrade to 0.5.0

**Comment by hasron** [comment]
I solve the problem using information provided here: 
https://github.com/open-webui/open-webui/issues/8074#issuecomment-2562061337

**Comment by N4S4** [comment]
> Same issue here.
> 
> Thx.
> 
> UPDATE:
> 
> Fix it in my Synology reverse proxy:
> 
> ![image](https://private-user-images.githubusercontent.com/33522344/398735331-98129e5e-6816-4268-ac4b-0e5f99c5d16d.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MzUyMjkzMTUsIm5iZiI6MTczNTIyOTAxNSwicGF0aCI6Ii8zMzUyMjM0NC8zOTg3MzUzMzEtOTgxMjllNWUtNjgxNi00MjY4LWFjNGItMGU1Zjk5YzVkMTZkLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDEyMjYlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQxMjI2VDE2MDMzNVomWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTZhN2RlYmE2OWQ1ODI2MjU4ZGZkZDUyYjE3M2Q4ODQxZGU0MmEwZTNmZDI1YTMzZGQ4ZDhkYjNhNWY4OWU3ZDcmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0In0.f-XM4yb8KjNhpU-bBlhSEVVMbFOEMB7RD9z2qz3KNGk)

this fix my issue too, I'll be clsing the issue as is a reverse proxy setup to be modified

**Comment by N4S4** [comment]
thank you for the support
