### ISSUE TITLE
Auto title and tags generation not working in 0.5.1

### ISSUE THREAD

**Issue by alwint3r** [open-webui/open-webui#8106]
# Bug Report

## Installation Method

I installed it using `pip`

## Environment

- **Open WebUI Version:** v0.5.1
- **Ollama (if applicable):** v0.5.4

- **Operating System:** macOS Sequoia 15.2
- **Browser (if applicable):** Chrome 131.0.6778.109

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

I expect the title and the tags of a new chat to be automatically generated after the first answer from the AI is available.

## Actual Behavior:

The title of the new chat remains "New Chat" and the tags are empty.

## Description

**Bug Summary:**
I believe the auto-generation for title and tags of a chat is working before updating from v0.4.8 to v0.5.1

## Reproduction Details

1. Install the v0.5.1
2. Ensure the model tasks are the Current Model, in my case it's qwen2.5-coder:32b
3. Create a new chat and ask the AI anything

## Logs and Screenshots

<img width="1728" alt="Screenshot 2024-12-26 at 19 50 27" src="https://github.com/user-attachments/assets/e3290220-b79f-4024-b17b-0fadff2ddaa5" />

**Comment by alwint3r** [comment]
One more thing, I don't see any code calling this function for some reason, whereas the "Chat.svelte" file in version v0.4.8 calls this function.

https://github.com/open-webui/open-webui/blob/v0.5.1/src/lib/apis/index.ts#L203

**Comment by Simi5599** [comment]
Can you provide Docker logs (if applicable)?

Maybe this is a regression introduced with #8075

**Comment by tjbck** [comment]
@alwint3r Try pulling the latest main instead of 0.5.1, and let us know if that fixed the issue on your end!

**Comment by MigiSenpai416** [comment]
Same problem I am experiencing even after upgrading to latest main(v0.5.1)

Title generation works for OpenAI Models like 4o, 4o-mini. But leaves a blank title when using reasoning models(o1, o1-mini, o1-preview)
![OpenWebUI](https://github.com/user-attachments/assets/37d0b4ae-ca1a-466e-88f3-d56461714575)
![OpenWebUI2](https://github.com/user-attachments/assets/58f82bde-cd8c-4978-9994-baebc8c43aa4)

**Comment by tjbck** [comment]
@MigiSenpai416 expected behaviour from o1 models, however I just added a title generation fallback logic to set the user message as the title.
