### ISSUE TITLE
Session_ID error

### ISSUE THREAD

**Issue by Mapping730** [open-webui/open-webui#8113]
---

## Installation Method

installed as recomended
docker rm -f open-webui
docker pull ghcr.io/open-webui/open-webui:main
docker run -d -p 3000:8080 -v open-webui:/app/backend/data --name open-webui ghcr.io/open-webui/open-webui:main

## Environment

- **Open WebUI Version:** 5.1
- **Ollama (if applicable):** 0.5.1

- **Operating System:** window 10
- **Browser (if applicable):** firefox 133

**Confirmation:**

- [ X] I have read and followed all the instructions provided in the README.md.
- X[ X] I am on the latest version of both Open WebUI and Ollama.
- [X ] I have included the browser console logs.
- [ X] I have included the Docker container logs.
- [ X] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

PLEASE READE FIRST.  i had this error, read all the issues and logs, was looking to fix it and it JUST WENT AWAY.  i dont mean to cap lock, but i want to be clear, i read a bunch of other comments, i was looking to fix my proxies and config files, and when i was researching , i saw a bunch of "Fixes" with proof. but as i was workings on my own, the error just went away and started working as expected.  i'm writing this because i don't know if the other fixes were fixes, or were just buying time until the error fixed itself. i realize that the issue just dint "go away" but im saying that maybe a update file was hanging, a python file was hanging in an environment, something,  i stopped and started . logged put and logged in several times and no fix, it was time that fixed it, and what ever was hanging.  maybe a complete restart of my computer would have fixed it faster, i didnt do that. 
chats able to work

## Actual Behavior:

session_id error, unable to continunie after first comment

## Description
gettin a session_id error and unable to do anything except first line of hi, and then the mopdels return comment, so i know n=odels are working, but i immebiatly get a session_id error
**Bug Summary:**
[Provide a brief but clear summary of the bug]

## Reproduction Details
same error over and over, until it worked
**Steps to Reproduce:**
installed new version, went to start chat and  got session_id errors

## Logs and Screenshots

**Browser Console Logs:**
[console-export-2024-12-26_11-39-15.txt](https://github.com/user-attachments/files/18254396/console-export-2024-12-26_11-39-15.txt)

**Docker Container Logs:**
[DOCKERLOG.txt](https://github.com/user-attachments/files/18254397/DOCKERLOG.txt)

**Screenshots/Screen Recordings (if applicable):**
[Attach any relevant screenshots to help illustrate the issue]

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
#8074

**Comment by st1018380828** [comment]
退出你的id，然后重新登陆即可修复
