### ISSUE TITLE
Cannot add new models on admin interface

### ISSUE THREAD

**Issue by gabriel-kozma** [open-webui/open-webui#8142]
# Bug Report

## Installation Method

Docker

## Environment

- **Open WebUI Version:** v0.5.2
- **Ollama (if applicable):** ollama version is 0.5.4-0-g2ddc32d-dirty

- **Operating System:** ubuntu server 
- **Browser (if applicable):** [e.g., Chrome 100.0, Firefox 98.0]

**Confirmation:**

- [X] I have read and followed all the instructions provided in the README.md.
- [X] I am on the latest version of both Open WebUI and Ollama.
- [] I have included the browser console logs.
- [] I have included the Docker container logs.
- [X] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

Being able to select new models

## Actual Behavior:

Clicking on the `+` button doesn't do anything

## Description

**Bug Summary:**
I'm unable to select a new model

## Reproduction Details

**Steps to Reproduce:**

Try to select new model on admin panel

## Logs and Screenshots

**Browser Console Logs:**
There's no error on the console logs

**Docker Container Logs:**
There's no error on the container logs

**Screenshots/Screen Recordings (if applicable):**

<img alt="screen recording.mov" src="https://github.com/user-attachments/assets/e302987e-51e9-4100-b344-d422b893a7c6">

## Additional Information

[Include any additional details that may help in understanding and reproducing the issue. This could include specific configurations, error messages, or anything else relevant to the bug.]

## Note

If the bug report is incomplete or does not follow the provided instructions, it may not be addressed. Please ensure that you have followed the steps outlined in the README.md and troubleshooting.md documents, and provide all necessary information for us to reproduce and address the issue. Thank you!

**Comment by tjbck** [comment]
https://github.com/open-webui/open-webui/discussions/7054
