### ISSUE TITLE
poor width scaling when using multiple models on a wide browser window

### ISSUE THREAD

**Issue by bartman** [open-webui/open-webui#8183]
Chatting with the models is working great, the problem is displaying multiple models side-by-side.

My screen is wide enough for 3 columns, but the output is squished into about 50% of the screen.

I didn't see anyone report a "width" or "multiple" bug.

## Installation Method

```
$ uv tool install open-webui
$ uv tool run open-webui serve
```

## Environment

- **Open WebUI Version:** v0.5.2
- **Ollama (if applicable):** 0.5.4

- **Operating System:** Debian/testing
- **Python version:** 3.12
- **Browser:** Firefox 133.0.3, also Brave 1.73.104

## Expected Behavior:

I would like to use the dead space for output.

Perhaps even be able to resize the panes?

## Actual Behavior:

It's not usable for reading the code, as shown in screen shot below.

## Description

**Bug Summary:**

I added 3 models to compare their output.  The output columns are very narrow, collectively using maybe 1/2 the screen real-estate.

## Reproduction Details

**Steps to Reproduce:**

- make sure ollama has some models, I used:
  ```
  $ ollama list
  NAME                                  ID              SIZE      MODIFIED
  qwen2.5-coder:14b                     3028237cc8c5    9.0 GB    27 minutes ago
  mannix/qwen2.5-coder:latest           68af2cd13aa9    4.4 GB    39 hours ago
  qwen2.5:14b                           7cdf5a0187d5    9.0 GB    2 weeks ago
  ```
- run using `uv tool run open-webui serve`
- connect with Firefox
- add 3 models
- ask a question that generates code
  > generate C++ generic guard class that uses RAII to execute a lambda when the object gets deleted.
  > implement copy, move, and assignment. 
- should be hard to read

## Logs and Screenshots

**HTML generated:**
[RAII Guard Class - Open WebUI.zip](https://github.com/user-attachments/files/18268398/RAII.Guard.Class.-.Open.WebUI.zip)

**Console logs:**

[RAII Guard Class - Open WebUI.log](https://github.com/user-attachments/files/18268412/RAII.Guard.Class.-.Open.WebUI.log)

**Screenshots:**

Firefox...
![image](https://github.com/user-attachments/assets/1c415492-6f82-42bf-9c3d-1b80d1ffdb21)

Brave...
![image](https://github.com/user-attachments/assets/f2dd6685-a977-4a65-82ef-6725ae429ff8)

**Comment by tjbck** [comment]
You can enable widescreen mode from Settings > Interface

**Comment by bartman** [comment]
Thank you.
