### ISSUE TITLE
Model section feature looks differently.

### ISSUE THREAD

**Issue by radadiavasu** [open-webui/open-webui#8189]
# Need Urgent Help on this issue.

## Installation Method

> For Installation as per mentioned.

1. `pip install open-webui`

> For running.

2. `open-webui serve`

## Environment

- **Open WebUI Version:** _**v0.5.2**_
- **Ollama:** _**v0.5.4**_

- **Operating System:** **_[Windows 11 Pro]_**
- **Browser:** **_[Bing, Brave, Chrome]_**

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.

## Expected Behavior:

1. Need to get a feature for upload the model just like first screenshot.

## Actual Behavior:

2. Actually getting a blank on model's page. means how could I set the model configurations on it's model's page.

## Description

**Bug Summary:**

I get something different layout on model's tab in admin panel setting.

1. Actually recently I watch a video about how to run own LLMS model locally with `OpenWeb UI`. After all the installation process I notice a strange thing that in a video I get different layout on my model section and in a video is different. 

2. Although a video is about 2-3 months old from 24-Dec as I post this date. And we both follow the same downloading process like with using `pip install open-webui`, then `open-webui serve` for run. Can you solve my doubt if I'm wrong or I missed something. Thanks in advance.

## Logs and Screenshots

**Screenshots/Screen Recordings (if applicable):**

# IN YOUTUBE VIDEO
![Screenshot 2024-12-29 223929](https://github.com/user-attachments/assets/52b20b82-b419-4171-941d-5222751535f8)

# MY WORKSPACE
![Screenshot 2024-12-29 224123](https://github.com/user-attachments/assets/18ecfcbe-88d4-4aae-bd6c-74da5ba0f963)

**Comment by beastech** [comment]
The interface has changed since that video was published.  To add models you will need to go under Admin>Settings>Connections and under Ollama API you will see a little wrench icon.  Click on that and you will find the area to download\update models.

**Comment by radadiavasu** [comment]
@beastech Thank buddy. You save my day.
