### ISSUE TITLE
Context Length seems to be ignored in 0.5.2 but worked fine in 0.4.8

### ISSUE THREAD

**Issue by nikow** [open-webui/open-webui#8190]
## Installation Method

[Describe the method you used to install the project, e.g., git clone, Docker, pip, etc.]
I am using ghcr.io/open-webui/open-webui docker image. The problem is with main version which is 0.5.2, but it was not there with 0.4.8.

## Environment

- **Open WebUI Version:** 0.5.2 bug exists, but 0.4.8 worked fine
- **Ollama (if applicable):** 0.5.4

- **Operating System:** Docker container living on Fedora
- **Browser (if applicable):** Google Chrome Version 131.0.6778.204, Firefox 132.0.1

**Confirmation:**

- [ X] I have read and followed all the instructions provided in the README.md.
- [X ] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [X ] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

The answer gets into account context_length set by me so my AI answers are more consistent, even when slower.

## Actual Behavior:

The answers are blazing fast, but lose details from previous messages quickly.

## Description

**Bug Summary:**
When i put my context_length manually to be 32768 it seems to be ignored with new version. It makes my Single User Dungeons with AI less consistent, because it forgets details faster.

## Reproduction Details

**Steps to Reproduce:**

1. Start new chat with mistral-nemo:12b. It does not matter if i am using local or remote image with ollama.
3. Go to Controls, click on Context Length and type manually value 32768.
4. Ask AI to generate a story adventure and choose name for a character. 

## Additional Information

In previous version AI needed 2 minutes and 30 seconds to answer my prompts now it's instant. The problem is that it was able to keep details from my prompts for 5-7 messages and now it loses them quickly. I tested it with CPU only ollama version on my laptop and with GPU (RTX4070) version of Ollama on Windows.

**Comment by tjbck** [comment]
Good catch! Fixed on dev and will be released with 0.5.3 shortly!
