### ISSUE TITLE
feat: add optional support to online providers?

### ISSUE THREAD

**Issue by SethBurkart123** [open-webui/open-webui#822]
**Is your feature request related to a problem? Please describe.**
Sometimes you can't run certain larger models locally eg. a 70b llama model. 

**Describe the solution you'd like**
If we implemented alternative providers that could be connected in by just logging into their accounts e.g. let people log in with their huggingface or perplexity accounts to make available online hosted models. This would largely be a secondary feature similar to the openai api support.

I'd be happy for this to be some kind of implementation with the upcoming **Custom Python Backend Actions** as it might be slightly off the core functionality that some people may not like implemented into the core. But in order to make logging into these services possible from the frontend there would just have to be a way of injecting extra settings into the frontend.

Thoughts?

**Comment by tjbck** [comment]
LiteLLM proxy support has been added!
