### ISSUE TITLE
After the pipe response has ended, the chat interface remains in a state of waiting for the information stream

### ISSUE THREAD

**Issue by danielaskdd** [open-webui/open-webui#8235]
# Bug Report

## Installation Method

docker run -d -p 5023:8080 --restart unless-stopped \
  -v open-webui:/app/backend/data \
  --add-host=host.docker.internal:host-gateway \
  --name open-webui \
  --gpus all \
  -e WEBUI_NAME=znAI \
  -e GLOBAL_LOG_LEVEL="WARNING" \
  -e MAIN_LOG_LEVEL="WARNING" \
  -e MODELS_LOG_LEVEL="WARNING" \
  -e OLLAMA_LOG_LEVEL="WARNING" \
  -e OPENAI_LOG_LEVEL="WARNING" \
  -e RAG_LOG_LEVEL="WARNING" \
  -e LITELLM_LOG_LEVEL="WARNING" \
  -e TZ=Asia/Shanghai \
  ghcr.io/open-webui/open-webui:cuda

## Environment

- **Open WebUI Version: 0.5.2
- **Operating System: Ubuntu 24.04.1

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I am on the latest version of both Open WebUI and Ollama.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.
- [x] I have provided the exact steps to reproduce the bug in the "Steps to Reproduce" section below.

## Expected Behavior:

After pipe response ended, the Action icons show up following the respond message, and the Stop button become the Call button.

## Actual Behavior:

Action icons not show up, and  Stop button Still there until I pressed it.

## Description

**Bug Summary:**

After the pipe response has ended, the chat interface remains in a state of waiting for the information stream. The Action icons not show up, and  Stop button Still there until I pressed it.

## Reproduction Details

1. Install “SMART - Sequential Multi-Agent Reasoning Technique” （function id: smart_core) in official website.
2. Eable the smart/core model
3. Submit a query on any topic/content
4. Wait till the respond end

Action icons not show up, and  Stop button Still there until I pressed it.

**Comment by tjbck** [comment]
This should be resolved in dev.
