### ISSUE TITLE
feat: use haystack for the RAG backend

### ISSUE THREAD

**Issue by Jbollenbacher** [open-webui/open-webui#841]
I'd like to suggest using [haystack](https://github.com/deepset-ai/haystack) as the backend for the RAG system.  It's quickly becoming the industry standard and is well maintained. I figured now would be a good time to suggest it while the RAG system is still mostly in beta. 

Haystack solves a lot of the basic problems like providing flexibility for swapping out embedding models and chunking strategies. It's also robust and comes with a lot of good default options. Basically it offloads the task of engineering a SOTA RAG system to another group of open source developers.

**Comment by tjbck** [comment]
Merging this issue with #780, let's continue our discussion there!
