### ISSUE TITLE
Attempt to connect to OpenAI with no configured API key

### ISSUE THREAD

**Issue by robertvazan** [open-webui/open-webui#860]
# Bug Report

## Description

**Bug Summary:**
It looks like WebUI tries to establish connection to OpenAI server even if no API key is configured.

**Steps to Reproduce:**
No OpenAI API key is configured. Open WebUI in the browser.

**Expected Behavior:**
Nothing special happens.

**Actual Behavior:**
WebUI logs error that it cannot connect to OpenAI without API key.

## Environment

- **Operating System:** Fedora 39
- **Browser (if applicable):** Firefox 122

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I have reviewed the troubleshooting.md document.
- [x] I have included the browser console logs.
- [x] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
Object { detail: "Oops! It looks like there's a hiccup. The API key is missing. Please make sure to provide a valid API key to access this feature." }
[index.3a450642.js:1:1894](http://localhost:3000/_app/immutable/chunks/index.3a450642.js)
OpenAI: Network Problem [2.a0ed6002.js:63:2320](http://localhost:3000/_app/immutable/nodes/2.a0ed6002.js)

**Docker Container Logs:**
https://api.openai.com/v1/models
INFO:     10.0.2.100:36408 - "GET /openai/api/models HTTP/1.1" 401 Unauthorized

## Installation Method

Latest docker image.

**Comment by tjbck** [comment]
Working as intended, it only communicates with the backend to check if API key is provided.
