### ISSUE TITLE
infra: CI for docker-publish does not trigger on tag

### ISSUE THREAD

**Issue by duhow** [open-webui/open-webui#864]
https://github.com/open-webui/open-webui/blob/b1fa32c5d66eb918c4b102d34a990b982f011f70/.github/workflows/build-release.yml#L32

🐞 This is a limitation on GitHub. You'll need to switch to a PAT to publish the `tag`, or `use` the Workflow `docker-publish` as a reusable workflow in another Job within the same Workflow.

> Unfortunately, there's no workaround to trigger a new workflow run from within another workflow without using a personal access token or a GitHub App installation token. This is a limitation put in place by GitHub to prevent recursive workflow runs.
>
> Events triggered by the GITHUB_TOKEN, which is automatically created for each workflow run, will not create new workflow runs. This includes pushing tags or creating releases with the GITHUB_TOKEN.
>
> If you want to avoid using a personal access token, you might need to reconsider your workflow design. For example, you could combine the steps of your two workflows into one single workflow if possible. This way, you won't need to trigger a new workflow from within another workflow.

**Comment by tjbck** [comment]
Closing in favour of #878
