### ISSUE TITLE
infra: Enhance releases workflow and integration

### ISSUE THREAD

**Issue by Lanhild** [open-webui/open-webui#878]
We've discussed in the past days about ways to refine and enhance the release process for Open WebUI. 

Currently, there are automated GitHub release and Docker image publishing workflows. This is a great first step, but there is the need for something more polished and automated, especially as the project and it's community grows.

I found [Semantic-release](https://github.com/semantic-release/semantic-release). It seems like it is the best-fitting tool for this issue and fits most, if not all, our needs in term of CI.

Below is a transcription of a related Discord conversation on the Open WebUI server:

```
Lanhild — Yesterday at 7:31 PM
where are the release notes though? in a CHANGELOG file?

wildtang3nt — Yesterday at 7:34 PM
oh I meant these when you press the generate button, if there were any PRs in my branch since the last release, they'd also be listed there above the automatic changelog link

Lanhild — Yesterday at 7:35 PM
Well, we could have a script in the package.json that generates release notes in a CHANGELOG.md file, and then adapt the release workflow to take the content of the CHANGELOG since last version

wildtang3nt — Yesterday at 7:36 PM
for sure, there's definitely more than one way to go about it, I'm just spitballing ideas, that was your PR so I'm happy to let you run with it how you think would work best 🙂

Lanhild — Today at 5:57 PM
@wildtang3nt I've tested https://github.com/semantic-release/semantic-release.

From what I understand, it automatically creates a release version based on commits messages. Everything seems configurable, from release notes to release publishing to commit analysis.

See https://semantic-release.gitbook.io/ for their doc.

I think we can't go wrong by using this.

```

I don't have the time to do all the work around this issue, but I can prepare the `package.json` file to fit with [Semantic-release](https://github.com/semantic-release/semantic-release) needs and add the dependency to the project.

**Comment by h4ckm1n-dev** [comment]
I will take a look on it, not sure to have the skill to make it btw

**Comment by tjbck** [comment]
Closing in favour of #2738 2738
