### ISSUE TITLE
feat: Ollama embeddings support

### ISSUE THREAD

**Issue by Gyro0o** [open-webui/open-webui#886]
Can you add the option to use ollama embeddings with customized models (such as nomic-embed-text...)
Alongside the native implementation.

**Comment by antonsapt4** [comment]
Hi Guys, is https://huggingface.co/nomic-ai/nomic-embed-text-v1.5 is not currently supported? 

https://github.com/open-webui/open-webui/pull/772 been following till it merged, just want to know if this related and now we can use it to change the embed via dockerfile with nomic file

@tjbck @Gyro0o

**Comment by oliverbob** [comment]
Nomic embed text is the best in the world. 
Better than OpenAI's . Following....

**Comment by MikeyBeez** [comment]
Has this been merged yet?

**Comment by vaclcer** [comment]
Hello, I have tried to change the default embedding model for "mxbai-embed-large-v1". Docker build went fine, but when I try to ingest any document I get error:

"Embedding dimension 1024 does not match collection dimensionality 384"

I guess the new embedding model needs different size of vector db, but how do I configure that? Thanks.

**Comment by JJassonn69** [comment]
@vaclcer is it possible for you to create a guide or instructions on how to it. Would love to try out the new embedding model.

**Comment by vaclcer** [comment]
I have a feeling this will be sorted out in upcoming v0.1.118. Lets see.

**Comment by tjbck** [comment]
Added to our dev branch, let us know if you encounter any issues!

**Comment by sammcj** [comment]
Love your work @tjbck :)

**Comment by sammcj** [comment]
Just tried it out, works as described - Thanks! 🌮

<img width="918" alt="image" src="https://github.com/open-webui/open-webui/assets/862951/2af43f17-87ad-4af2-8045-0a8c076c3ab1">

<img width="1537" alt="image" src="https://github.com/open-webui/open-webui/assets/862951/163e2e22-b74c-411b-83eb-92748dbb4251">

**Comment by justinh-rahb** [comment]
😅 And I just went through the trouble of switching to another built-in model, deleting my documents and vector DB the other day. This opens so many new possibilities!

**Comment by makecent** [comment]
Delete the knowledge database and re-create it solved my problem. Seems like because I changed the embedding model for this knowledge database, which is initialized with the embedding size of the previous embedding model (even it's empty now)
