### ISSUE TITLE
feat: persist settings to local instance (not in browser's local storage)

### ISSUE THREAD

**Issue by mherrmann3** [open-webui/open-webui#900]
**Describe the solution you'd like**
I expected that once I define my settings (such as default model, system prompt, advanced parameters, title generation prompt, etc.), they apply to my user profile. But if I login to my user profile/instance from another device, they are gone and I have the set them anew—they are stored in the browser's local storage (`settings` key). I'm not sure if this is intended, but having already a user profile, I thought it's more intuitive and practical to save those settings on the instance.

**Describe alternatives you've considered**
If current behavior is intended, I could imagine having a "settings sync" button, which:
* (over)writes current settings in/to the profile/instance (but shows a warning message/popup before doing so);
* pulls those settings from the instance **if** no (local) settings are made yet (which the user can enforce by clearing site data with the browser).

**Additional context**
Possibly related: #619

**Comment by tjbck** [comment]
You can utilise modelfiles feature to save the preset on the backend!

**Comment by mherrmann3** [comment]
Thanks, Timothy! Yes, I use model files to specify some model parameters for specific models.
But I believe that model files do not fully address this issue:
* they do not store the default model, system prompt, title generation prompt, etc.;
* if one prefers a _general_ set of model parameters (temperature, top_p, etc.), one would need to create a model file for _each_ model - possible, but tedious.

I just witnessed (accidentally) another reason for persisting the settings to the local instance: settings are lost when the browser clears the data - loosing all made settings (yes, one could set an exception for localhost - or the analog when accessing remotely - in the browser, but many users may not know this).

**Comment by tjbck** [comment]
Closing in favour of #1022
