### ISSUE TITLE
Add litellm to kubernetes path 

### ISSUE THREAD

**Issue by jannikstdl** [open-webui/open-webui#921]
We should add this to our k8s/helm and docker-compose yamls.

Maybe @duhow @braveokafor can help with this.

https://litellm.vercel.app/docs/proxy/deploy

**Comment by duhow** [comment]
I'm guessing you want to decouple services/dependencies from the whole `open-webui` image in separated services, or is there any other plan?
How do we want to scale that service?

**Comment by tjbck** [comment]
FYI, Our webui already ships with LiteLLM proxy built-in!

**Comment by jannikstdl** [comment]
Ok, so is works out of the box with the existing image? 

Do i need to update [test.json](https://github.com/open-webui/open-webui/tree/main)
/test.json)
for other providers?
