### ISSUE TITLE
feat: editable k value for RAG

### ISSUE THREAD

**Issue by Venkman42** [open-webui/open-webui#923]
Could you add a setting to the document settings to set the amount of text snippets that get used in the context?
Is it only one right now?

And it would be great to be able to see the full RAG text for troubleshooting. Answering RAG questions is really slow for me right now, would be great if could see what was inserted as context in the conversation

**Comment by jannikstdl** [comment]
Seems like at the moment it is hardcoded to 4:
`k: Optional[int] = 4` in RAG main.py 

For now you can see the snippets sent to the LLM for RAG in the browser console after sending your request.
