### ISSUE TITLE
when openai compatible reverse proxy name contains 'openai' in its name, models without 'gpt' string are not shown in model dialog

### ISSUE THREAD

**Issue by fbirlik** [open-webui/open-webui#930]
# Bug Report

## Description
When OpenAI compatible API server is defined using 'OPENAI_API_BASE_URL' and this url contains 'openai' string in it, all models that don't contain 'gpt' string will be hidden from model menu.

**Steps to Reproduce:**
Using fastchat openai compatible api server for serving local models.  I use nginx-proxy-manager as reverse proxy and ssl terminator.  URL for the api is
--> https://openai.i.{mydomain.com}/v1
actual host address being proxied:
--> http://ares.i.{mydomain.com}/v1

When 'OpenAI API Base URL' is set to https://openai.i..., models without 'gpt' string disappear.

Culprit:
backend/apps/openai/main.py @ 187:
```
  if "openai" in app.state.OPENAI_API_BASE_URL and path == "models":
      response_data["data"] = list(
          filter(lambda model: "gpt" in model["id"], response_data["data"])
      )
```

**Expected Behavior:**
Ability to disable 'gpt' filter with a config/environment variable.

**Comment by justinh-rahb** [comment]
I've never observed this happen. Before the built-in LiteLLM was merged I had been using it externally as my "OpenAI" proxy with many models, both GPT and others, and they all showed in the list. Can't view on mobile but I'll have a look at that code snippet to see when it was added, it's possible I haven't noticed because I've switched to using the built-in LiteLLM.

**Comment by justinh-rahb** [comment]
That snippet hasn't been touched since last month, so ya I'm unsure what this could be. As you can see I've got multiple different models that do not have "gpt" in the model string:

<img width="656" alt="Screenshot 2024-02-26 at 5 08 47 PM" src="https://github.com/open-webui/open-webui/assets/52832301/f5e849da-0be8-4b0d-93d9-152bc31a5ab7">

**Comment by tjbck** [comment]
Should be an easy fix, feel free to make a PR!

**Comment by fbirlik** [comment]
Issue occurs when 'OPENAI_API_BASE_URL' host contains 'openai' in the name as a way to identify official openai endpoint.  If backend api url does not include openai, no issues.

@tjbck I believe the reason to include this code piece was to filter out embedding, dall-e, whisper, tts models that are returned from official api.openai.com/v1/models api response, which can't be used by the chat ui.

**Comment by justinh-rahb** [comment]
> Issue occurs when 'OPENAI_API_BASE_URL' host contains 'openai' in the name as a way to identify official openai endpoint. If backend api url does not include openai, no issues.
> 
> @tjbck I believe the reason to include this code piece was to filter out embedding, dall-e, whisper, tts models that are returned from official api.openai.com/v1/models api response, which can't be used by the chat ui.

In this case would it make more sense to expand the string matching to the whole FQDN `api.openai.com`? I don't think it'll be changing.

**Comment by fbirlik** [comment]
> > Issue occurs when 'OPENAI_API_BASE_URL' host contains 'openai' in the name as a way to identify official openai endpoint. If backend api url does not include openai, no issues.
> > @tjbck I believe the reason to include this code piece was to filter out embedding, dall-e, whisper, tts models that are returned from official api.openai.com/v1/models api response, which can't be used by the chat ui.
> 
> In this case would it make more sense to expand the string matching to the whole FQDN `api.openai.com`? I don't think it'll be changing.

I believe it would be appropriate.  I was not quite sure about self/azure hosted gpt endpoints, but open-webui has azure specific dedicated configuration for that purpose.  So it should be ok.
