### ISSUE TITLE
AUTOMATIC1111 Base URL throws error

### ISSUE THREAD

**Issue by piedpiper-technologies** [open-webui/open-webui#943]
I am using the container version of open web-ui updated to v0.1.105 [(latest)](https://github.com/open-webui/open-webui/releases/tag/v0.1.105) and AUTOMATIC1111 version: [v1.7.0](https://github.com/AUTOMATIC1111/stable-diffusion-webui/commit/cf2772fab0af5573da775e7437e6acdca424f26e) on 2023 MBP Apple Silicon M2.

AUTOMATIC 1111 is running on local http://127.0.0.1:7860 and launched with arguments: --api --skip-torch-cuda-test --upcast-sampling --no-half-vae --use-cpu interrogate

The API is up and docs can be accessed at http://127.0.0.1:7860/docs

When I attempt to enter base URL in Open Web UI I receive the following error:
![Screenshot 2024-02-27 at 11 17 36](https://github.com/open-webui/open-webui/assets/130253894/5c0ae735-f2c5-4dba-ad91-9fb447ea63a2)

When I accesss the AUTOMATIC1111 endpoint through FASTAPI I get a 200 response:
![Screenshot 2024-02-27 at 11 20 21](https://github.com/open-webui/open-webui/assets/130253894/e7cd7edf-3f21-40be-af06-463f7936305a)

WebUI container logs show:
<img width="881" alt="Screenshot 2024-02-27 at 11 24 12" src="https://github.com/open-webui/open-webui/assets/130253894/13a0e801-499c-460c-b9d1-97e1db834192">

**Comment by justinh-rahb** [comment]
If your Open WebUI is running in Docker, you'd need to use this instead:
```
http://host.docker.internal:7860/
```

**Comment by ronidee** [comment]
I totally missed that too, my bad for sure!
But maybe a small hint in the UI could help?

Kind regards :)
