### ISSUE TITLE
Introduce some smart way to cleanup unfinished downloads 

### ISSUE THREAD

**Issue by kha84** [open-webui/open-webui#946]
**Is your feature request related to a problem? Please describe.**
If you run `ollama run/pull <some_new_model_you_didnt_have>` and then for whatever reason the downloading stops in-between, the unfinished files are left (supposedly) in ~/.ollama/models/blobs/sha256:*-partial* occupying quite a lot of space (depending on when the stop happened). Running `ollama list` doesn't show those unfinished downloads - so you don't see them, can't remove them. This leads to the hdd space wastage without user knowing

**Describe the solution you'd like**
There should be a way for ollama to trigger (automatically, every once in a while) a **reconcile** procedure, to identify and remove whatever files are related to unfinished downloads.

**Describe alternatives you've considered**
1) Manually deleting files related to unfinished downloads (might be tricky for users, because the info about where ollama holds all it's internals and how it's organized isn't part of official documentation - it's kinda hidden under the hood)
2) `ollama list` to show unfinished downloads so they could be deleted with `ollama rm`

**Comment by justinh-rahb** [comment]
Please close this issue, this is not the Ollama project GitHub, and Open WebUI is not affiliated with them.

**Comment by kha84** [comment]
Ah sorry mates, I'm blind and posted the issue in the wrong repo :(
