### ISSUE TITLE
feat (ux): Focus on latest message when opening an existing chat

### ISSUE THREAD

**Issue by incyclum** [open-webui/open-webui#957]
**Is your feature request related to a problem? Please describe.**

Just noticed another small improvement that could be implemented,
after updating to see the amazing prompt autofocus from #936 🎉❤️...

When I open an existing chat conversation,
I have to scroll down to the latest message,
which is kinda annoying when you're continuing a recent conversation.

And I noticed this because now having the prompt autofocus emphasized that seeing a
blinking cursor waiting for you to type but being at the top of the conversation thread
doesn't makes much sense. Imagine opening your WhatsApp chats and being at the top...

Compared to ChatGPT UI where the chat is already focused on the latest message.

**Describe the solution you'd like**

Like on ChatGPT, focus on latest message of a chat, so user don't have to scroll down.

**Describe alternatives you've considered**

When going back and forth between chats in the same work session (in the same Open WebUI tab session),
It may be more useful to stay where the user left instead of latest message.

E.g:

1. Leave "Chat A" somewhere in the middle, e.g. you're reading message 30/50
2. Create a new "Chat B", type right away in the prompt thanks to autofocus :D
3. Go back to "Chat A", instead of being on the latest message (or 1st one) you could stay at 30/50

BUT if I close the tab, log-out, enter a new session, I think opening "Chat A" the next day or so makes more sense focusing on latest message.

Open to discussion or any other ideas :)

Thanks!

**Comment by jannikstdl** [comment]
I could implement a function to scroll to the bottom whenever you open a new chat like chatgpt does.

**Comment by incyclum** [comment]
Yeah, I believe it's already a good thing doing so.

**Comment by incyclum** [comment]
Also realized that regarding my comment,

> When going back and forth between chats in the same work session (in the same Open WebUI tab session), It may be more useful to stay where the user left instead of latest message.

Opening the chats in different tabs does the job when you work on multiple ones at the same time.

**Comment by incyclum** [comment]
Awesome! Thanks!
