### ISSUE TITLE
feat: Add whole folder

### ISSUE THREAD

**Issue by Sloox** [open-webui/open-webui#958]
**Is your feature request related to a problem? Please describe.**
Possible to to add a whole folder and batch the file upload?

**Describe the solution you'd like**
Add a whole folder and it adds document one by one. Would be lovely if it was recursive.

I think its fairly self explanatory.

**Comment by Sloox** [comment]
@justinh-rahb 
This is a manual implmentation yes?
What i mean is when i use the "documents" and click on the "+" icon. I have the option of selecting a folder and it syncing all the documents inside it. 
Does it make sense?

**Comment by justinh-rahb** [comment]
It makes sense, but not as a new feature. You can already multi-select every document in a folder when you click the "+" icon and upload them at once:

![Screenshot 2024-02-28 at 11 31 10 AM](https://github.com/open-webui/open-webui/assets/52832301/3f4df5b0-588f-40c9-8fe6-7852ddb4a60b)

**Comment by jannikstdl** [comment]
Yes, just go into the folder and `STRG/CTRL + A`

**Comment by Sloox** [comment]
understood. Will close.
