### ISSUE TITLE
Numbered list does not display correctly in Safari

### ISSUE THREAD

**Issue by adan89lion** [open-webui/open-webui#963]
# Bug Report

## Description

**Bug Summary:**
Markdown numbered lists generated by LLMs do not display correctly in Safari. Number starting from 10 will be cropped out.

**Steps to Reproduce:**
1. Use Safari browser
2. Ask models to generate a numbered list with more than 10 entries
3. Problem starts appearing starting from number 10

**Expected Behavior:**
Numbers display correctly

**Actual Behavior:**
Numbers does not display correctly

## Environment

- **Operating System:** macOS Sonoma 14.3.1
- **Browser (if applicable):** Safari 17.3.1 (196617.2.4.11.12)

## Reproduction Details

**Confirmation:**

- [x] I have read and followed all the instructions provided in the README.md.
- [x] I have reviewed the troubleshooting.md document.
- [ ] I have included the browser console logs.
- [ ] I have included the Docker container logs.

## Logs and Screenshots

**Browser Console Logs:**
N/A

**Docker Container Logs:**
N/A

**Screenshots (if applicable):**
![Screenshot 2024-02-29 at 13 57 08@2x](https://github.com/open-webui/open-webui/assets/6585644/15f060d4-05df-4957-aff1-5e1c42b38b13)

## Installation Method

Docker

## Additional Information

N/A

**Comment by jannikstdl** [comment]
Can you copy the answer with the copy icon at the bottom of the message and paste it here?

**Comment by adan89lion** [comment]
I've lost the previous conversation, but here's another one.

```
 1. Aki
2. Anna
3. Annika
4. Elina
5. Esa
6. Helmi
7. Heikki
8. Jarkko
9. Johanna
10. Juhani
11. Kaarlo
12. Kati
13. Kirsi
14. Kustaa
15. Lauri
16. Liisa
17. Lumi
18. Mia
19. Mikko
20. Niilo
21. Noora
22. Ossi
23. Paula
24. Pekka
25. Piia
26. Riikka
27. Salla
28. Teija
29. Tina
30. Tommi
```

![Screenshot 2024-02-29 at 15 47 54@2x](https://github.com/open-webui/open-webui/assets/6585644/015b9b4a-a8af-4f1b-85df-62ddb19decb8)

It seems like the numbers are really cropped out.

**Comment by jannikstdl** [comment]
Ok thanks!

Can someone reproduce this on safari? For me on Win 11 / Chrome it is working.

**Comment by taidbui** [comment]
I confirmed this happened with safari on Mac. Changed to Edge (also on Mac) it works fine.

**Comment by jannikstdl** [comment]
Ok, looks like a formatting issue like margin or something.

But the cut off text on the left looks like a 2 for me not the expected 1.
Like it would count 9. 20. 21.

**Comment by taidbui** [comment]
<img width="243" alt="Screenshot 2024-02-29 at 16 58 12" src="https://github.com/open-webui/open-webui/assets/28985154/284579c7-5d2c-4066-a15c-1e2f1d65573d">
