### ISSUE TITLE
Add support for groq api

### ISSUE THREAD

**Issue by oliverbob** [open-webui/open-webui#973]
Low latency inferencing. I'm sure everyone knows about it. Its easy to integrate  according to their documentation at https://console.groq.com/docs/quickstart. Try it at https://groq.com.

**Comment by taidbui** [comment]
@oliverbob: it's openai compatible following this: https://console.groq.com/docs/openai 
Just need to add the base_url: https://api.groq.com/openai/v1 together with your API and enjoy.

**Comment by justinh-rahb** [comment]
Furthermore, it's directly supported by LiteLLM proxy mode as well with models `groq/llama2-70b-4096` and `groq/mixtral-8x7b-32768`

**Comment by oliverbob** [comment]
> @oliverbob: it's openai compatible following this: https://console.groq.com/docs/openai Just need to add the base_url: https://api.groq.com/openai/v1 together with your API and enjoy.

This works on the latest release of Openwebui. Thanks.

**Comment by oliverbob** [comment]
Is whisper dependent on OPENAI? If so, will this affect calls to the groq endpoint? Thanks.

**Comment by justinh-rahb** [comment]
> Is whisper dependent on OPENAI? If so, will this affect calls to the groq endpoint? I tried Groq, but cant make the whisper audio work. Thanks.

Yep. See LiteLLM to solve this for now.

**Comment by oliverbob** [comment]
If you could point me to some docs or perhaps paste a snippet, that would help. Thanks.

**Comment by justinh-rahb** [comment]
> If you could point me to some docs or perhaps paste a snippet, that would help. Thanks.

https://docs.openwebui.com/tutorial/litellm

**Model** strings to use are `groq/mixtral-8x7b-32768` or `groq/llama2-70b-4096`
