### ISSUE TITLE
feat: Allows users to see when a model was downloaded and its hash

### ISSUE THREAD

**Issue by WereCatf** [open-webui/open-webui#975]
Currently, the webui appears to provide no way of checking when a model was downloaded or its hash. Being able to see those would be helpful in determining, if there's a newer version of the model available, like e.g. Gemma was updated multiple times in a short period of time, and thus whether to delete the current one and add a new one or not.

Show the model's download date and its hash somewhere in the UI. Even better, if there was a proper menu entry for managing the model files and a simple button to update a model.

An auto-update feature would also be extremely nice, but maybe implement the basics first and consider auto-updater for later?

**Comment by lainedfles** [comment]
View of additional metadata would be helpful but we may want to postpone any auto-update feature as it may be implemented upstream. See https://github.com/ollama/ollama/pull/2179

**Comment by tjbck** [comment]
<img width="598" alt="image" src="https://github.com/user-attachments/assets/4a2612e4-7edf-47f2-ba8f-3777da0846a6">

Added to dev!
