### ISSUE TITLE
image generation settings are not stored

### ISSUE THREAD

**Issue by tcs-christian-ulrich** [open-webui/open-webui#981]
# Bug Report

## Description

**Bug Summary:**
image genseration settings are not stored

**Steps to Reproduce:**
enter image generation settings for connection to automatic1111 
i also enter image size and change steps
hit save
re-open settings to see if its there
restart container -> settings are gone (all other settings are stored)

**Expected Behavior:**
settings are saved

**Actual Behavior:**
after restart the image settings are gone

## Environment

- **Operating System:** one docker desktop environment on Windows 11, one podman setup on rpi5 both behave same

## Reproduction Details

**Confirmation:**

- [ x] I have read and followed all the instructions provided in the README.md.
- [ x] I have reviewed the troubleshooting.md document.
- [-] I have included the browser console logs.
- [-] I have included the Docker container logs.

## Installation Method

one docker desktop environment on Windows 11, one podman setup on rpi5
both with docker-compose, sligthly adapted to run on podman

**Comment by aaronnewsome** [comment]
I see the same behavior as described above. Once the container is restarted, the Stable Diffusion URL and image generation parameters must be re-entered. Also, when starting the container, I use an environment variable to specify the Ollama instance URL:port, but I did not find a way to specify the Image generation parameters when starting the container.

**Comment by tjbck** [comment]
Closing in favour of #1022, let's continue our discussion there!
